### ISSUE TITLE
Enhancement: Using calibration from other video

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#1003]
Hi Pupil Team!

Is there any way to use a calibration from another recording?

Our problem is that we have a calibration in recording A. Then the recording was stopped and restarted for video B without calibration. We want to do an offline calibration since video B has gaze issues.

I am looking forward for possibilities.

As always - Best
Freddy

**Comment by cpicanco** [comment]
Have you tried copying the `offline_data\offline_calibration_gaze` from recording 1 to recording 2?

**Comment by mkassner** [comment]
This is actually non trivial. We would have to move calibration ref and pupil data from one rec to another.

**Comment by papr** [comment]
One could export/import the gaze mapper config class name/params, though.
