### ISSUE TITLE
What happened with the "adjust calibration" plugin?

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#1004]
I would like to test this plugin in player. My idea is to trigger adjustments along a recording using calibration sections.

**Comment by cpicanco** [comment]
For each section, one must choose the center of the calibration (the adjustment) in the world scene.

**Comment by cpicanco** [comment]
Would be great if the center of existing surfaces could be used to auto set the center of adjustments.

**Comment by cpicanco** [comment]
Here it is [:)](https://github.com/pupil-labs/pupil/blob/v0.9.13/pupil_src/shared_modules/calibration_routines/adjust_calibration.py)

**Comment by papr** [comment]
@cpicanco Is this issue resolved?

**Comment by cpicanco** [comment]
@papr I would like to know why you remove the plugin.

Have you ever consider using this approach (adjusting the calibration using a surface centroid)? I can see that only 2d (polynomial regression) adjustment is implemented and it does not take depth into consideration, only perspective.

**Comment by papr** [comment]
We deprecated this plugin due to it not being a good solution to the actual problem: Slippage.  Use the 3d mode if you need slippage compensation (through model refitting). We are working on better longterm solutions to this problem. Feel free to use the old revision of the `Adjust Calibration` plugin. You might need to adapt it to the new plugin API though.

**Comment by cpicanco** [comment]
@papr , It is important to note that sometimes the problem **is not** slippage. Sometime a participant will move his/her head so that gaze will fall outside the calibrated area. I am wondering if adjustments from this plugin could optimize eye movements in this situation.

**Comment by papr** [comment]
I do not understand. The calibrated area does not move in relation to the head pose, given there is no slippage. How should the gaze fall outside of the calibrated area after an head movement?

**Comment by cpicanco** [comment]
Exactly, the calibrated area does not move. But if you have a relatively small calibrated area in the center of the word camera (for example using Screen Based Calibration) and if you have a stationary object (the screen), moving your head a few centimenters will likely result in gaze falling out the calibrated area.

An alternative solution is to use a calibration method that will map a considerably larger area (lets say, a very good Single Marker Calibration).

**Comment by papr** [comment]
Ok, I understand. But I would follow your alternative and calibrate in a larger area. This is especially important for 3d detection.

**Comment by cpicanco** [comment]
I would like to note that such alternative is only for future studies, does not apply for the past.

**Comment by papr** [comment]
In your case then, I would recommend to restore the plugin from an old version.
