### ISSUE TITLE
Pupil player - Offline calib. w/natural features - cache calibration 

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1012]
Currently, the data is recalibrated upon startup, and this can take a while for large files.  One can save time / processing power if one caches the calibration upon completion, and loads it when the video is loaded.

**Comment by papr** [comment]
Actually, it is not that easy. I tried to implement it, but the data needs to be recalibrated depending on the pupil data such that both are consistent. But I will put some more thought into it.

**Comment by papr** [comment]
Fixed in v1.11
