### ISSUE TITLE
Pupil player - Modify playback speed.

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1013]
When working with fixation detection etc, playing at full speed is far too fast.

**Comment by papr** [comment]
Are you aware that you can seek frame by frame using the arrow keys?

**Comment by papr** [comment]
There is also the option to jump to the next fixation using the thumb button on the left.

**Comment by performlabrit** [comment]
Yes, I'm aware of both methods.  Neither is equivalent to modifying
playback speed.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
That is correct. I will think about how to implement this best without slowing down the other ui.

**Comment by cpicanco** [comment]
@performlabrit please, can you elaborate a bit more on how the playback speed would improve usability in your case?

**Comment by performlabrit** [comment]
When trying to detect fixations, or judge the speed of an eye movement, it
is important that time passes slowly, and at a steady rate.  I can't hit
the arrow keys fast enough, or steadily enough, to iterate through the
frames at the speed I want.  Holding down the arrow key is a reasonable fix
for now, but the flexibility of a speed adjustment would be appreciated.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by cpicanco** [comment]
Thanks, now I got it. Eye inspection of fixations would be easier in slow motion.
