### ISSUE TITLE
Pupil player - hitting an arrow key should interrupt play

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1015]
Perhaps it's just me, but that's expected behavior, and useful when hitting play to quickly find an event.  I then use arrow keys to narrow down the frame.

**Comment by papr** [comment]
The arrow keys are bound to the seek backwards/forward buttons. In the future, their behavior will depend on the playback being stopped or not:
1. Playback stopped (frame-by-frame mode): Seek buttons seek one frame at a time in either direction
2. Playback enabled (playback mode): Seek buttons increase and decrease playback speed (fixes ui interaction problem for #37)

Therefore this issue will not be fixed as asked.
