### ISSUE TITLE
Pupil Player - keep the aspect ratio of the surface debug window

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#102]
Based on the x_size and y_size provided by the user the debug window should be resized to give appropriate feedback.

**Comment by mkassner** [comment]
Agreed. I think it does that on open but does not respond to changes after open.

**Comment by cpicanco** [comment]
@mkassner, how you choose the image that shows up in the debug window?

**Comment by mkassner** [comment]
Each surface submenu has a button that opens a debug window for that surface.

**Comment by cpicanco** [comment]
But how you choose the image, I mean, there is a bunch of frames?

**Comment by mkassner** [comment]
Yes. Its the most recent frame where the surface was found.
