### ISSUE TITLE
new player error "Exception: pyndsi version is to old. Please upgrade"

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1024]
Commit 4afb906aaeeff6bba95e2bf6829ad2d6f7dfb9d9 causes the error:
"Exception: pyndsi version is to old. Please upgrade"

Full console dump below.

> /usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/gjdiaz/PycharmProjects/pupil_pl_2/pupil_src/main.py player
MainProcess - [INFO] os_utils: Disabled idle sleep.
player - [ERROR] player_methods: No valid dir supplied
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [INFO] launchables.player: Starting new session with '/Users/gjdiaz/Dropbox/CFB/1'
player - [INFO] player_methods: Updating meta info
player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "/Users/gjdiaz/PycharmProjects/pupil_pl_2/pupil_src/shared_modules/video_capture/ndsi_backend.py", line 22, in <module>
    assert __version__ >= '0.3.4'
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gjdiaz/PycharmProjects/pupil_pl_2/pupil_src/launchables/player.py", line 74, in player
    from video_capture import File_Source, EndofVideoFileError
  File "/Users/gjdiaz/PycharmProjects/pupil_pl_2/pupil_src/shared_modules/video_capture/__init__.py", line 39, in <module>
    from .ndsi_backend import NDSI_Source, NDSI_Manager
  File "/Users/gjdiaz/PycharmProjects/pupil_pl_2/pupil_src/shared_modules/video_capture/ndsi_backend.py", line 25, in <module>
    raise Exception("pyndsi version is to old. Please upgrade")
Exception: pyndsi version is to old. Please upgrade

player - [INFO] launchables.player: Process shutting down.
MainProcess - [INFO] os_utils: Re-enabled idle sleep.

Process finished with exit code 0

**Comment by papr** [comment]
"Exception: pyndsi version is to old. Please upgrade". pyndsi is the framework that is responsible for the Pupil Mobile communications. Check the source dependencies in the docs for the reference to the repository.

**Comment by iserranoe** [comment]
I have the same problem when running run_service, but I have just installed the pyndsi using the wheel provided in the pupil docs page for Windows, which should be, I believe, already upgraded...

**Comment by cboulay** [comment]
Try [here](https://github.com/pupil-labs/pyndsi/issues/36).

**Comment by iserranoe** [comment]
Thank you!
