### ISSUE TITLE
Pupil Capture - Issue with adjusting ROI parameters in eye video

### ISSUE THREAD

**Issue by arispawgld** [pupil-labs/pupil#1025]
Hey, I recently installed Pupil Capture/player to a new 2017 Macbook Pro and encountered an issue that I do not encounter on my older imac (mid 2012) - not sure if it is due to them possibly being different versions. Any way, in the eye capture screen the ROI will not allow me to adjust any of the four edges except the top left (even when I flip the image, it is the top left one). This has been annoying and I can easily adjust the size on my other mac. Already attempted using w/ and w/o a mouse as well as deleting and reinstalling pupil capture. Pretty sure it is a bug.

Any help is appreciated!

**Comment by papr** [comment]
This should be improved with #1022

**Comment by papr** [comment]
This is actually an issue related to retina displays. I was able to reproduce this issue.
