### ISSUE TITLE
Player:  Offline 3D calibration broken.  In eye windows, nothing but gray, FPS=0

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1028]
The screenshot (attached) was taken about 30 secs into pupil detection.  Notice that the FPS is 0 in the eye video, and the progress bar is stuck at 0%.  Strangely enough, the eye videos still close as if the process did a good job.  No pupil data is cached, and so calibration is impossible.

Confirmed with two recordings.

![screenshot 2018-01-18 13 38 25 2](https://user-images.githubusercontent.com/8962011/35115293-aec68d9e-fc55-11e7-98b8-f1d18adcb833.png)

**Comment by mkassner** [comment]
fixed with https://github.com/pupil-labs/pupil/commit/a356825883fd766d84817d3f2c88a222539788a1
