### ISSUE TITLE
Calibration not working for 200hz binocular w/ Intel RealSense

### ISSUE THREAD

**Issue by conorrussomanno** [pupil-labs/pupil#1033]
This may not be specific to my system settings, but just in case:
MacOS Sierra v10.12.5
MacBook Pro 2017

**Comment by papr** [comment]
Hey @conorrussomanno 
Please specify what the exact issue is. I tried to reproduce the issue but did not have any problems with the calibration.

1. Setup questions:
    1.1. Do you run the bundled application or do you run from source?
    1.2. Which version do you use?

2. Setup issues:
2.1. Does the calibration crash the application?
2.2. Does the calibration conclude with an error message? If yes, which one?
2.3. Does the calibration finish successfully but the calibration is bad?
2.4. What is the pupil confidence during calibration?

Please male a recording during calibration if 2.1. is not the case and share it with us. Then we can try to reproduce the issue ourselves.

Please be aware that the v1.2-7 bundle does not include the new default settings for the 200Hz cameras. These will be included in the v1.3 bundle that should be released soon. Incorrect eye settings can lead to bad pupil detection.

**Comment by mkassner** [comment]
I believe this is resolved now.
