### ISSUE TITLE
Issue w/ Manual Calibration

### ISSUE THREAD

**Issue by arispawgld** [pupil-labs/pupil#1037]
Running into an issue when running Pupil Capture on a 2016 MacBook Pro that I did not run into previously. When trying to do a manual marker calibration (online), I press the calibrate button and almost immediately after announcing calibration has started, the program shut down calibration and announces the end. Have tried:

- deleting  & reinstalling Pupil Capture
- different presentation method (i.e. w/ the marker already in the world view upon starting calibration as well as off)

Haven't yet had a chance to try replicating the error on another machine, however reinstalling did not solve the issue.

**Comment by papr** [comment]
Reinstalling is not as effective as resetting the settings. See my comment on #1038 on how to do that.

Would you mind posting a picture of the marker that you are using. Be aware that there are calibration and stop markers. They look very similar. It is possible that you are using a stop marker and are canceling the calibration with it. I will also try to replicate this issue on my MacBook.

**Comment by papr** [comment]
@arispawgld Is this fixed?

**Comment by arispawgld** [comment]
All fixed, deleting the settings and reopening solved it.
