### ISSUE TITLE
Pupil Player - Side menu not working

### ISSUE THREAD

**Issue by arispawgld** [pupil-labs/pupil#1038]
Another issue with Macbook Pro 2016 model -Pupil Player now entirely nonfunctional; I cannot access any of the side bar tools (general settings etc.). I click on the button, it highlights and nothing pops out. Tried. fiddling with the computer settings, updates and such to no luck. also reinstalled pupil player which also was no help. The issue is not showing up on my mid-2012 iMac, so it is possible it is localized to this machine. Hoping someone can try to recreate on another MacBook!

**Comment by papr** [comment]
This issue has been fixed with https://github.com/pupil-labs/pupil/pull/1006

Please follow these steps to reset Player:
1. Close Pupil Player if it is running 
2. Delete `~/pupil_player_settings` folder to reset 
3. Start Pupil Player
