### ISSUE TITLE
pupil_capture.deb and /lib/x86_64-linux-gnu/libc.so.6

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#104]
Hey guys, this is an issue running in an old CrunchBang 11 (RIP). I think I am doing right just sharing it. I am planning an update to the most recent and pure Debian, but right now, for me, it would be pointless.

> Error loading Python lib '/opt/pupil_capture/libpython2.7.so.1.0': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/pupil_capture/libpython2.7.so.1.0)

The stable version is 2.13x
> https://packages.debian.org/wheezy/libc6

The testing version is 2.19x
> https://packages.debian.org/jessie/libc6

It would be possible to include this dependency?

**Comment by mkassner** [comment]
hi,

I think GlibC should not be shipped with any app. We could add it as a dependency then apt will install it when needed. I can look into that.

**Comment by cpicanco** [comment]
Was it possible to add the dependency?

**Comment by mkassner** [comment]
can you install libc on your machine? does it work then?

**Comment by cpicanco** [comment]
I will try with a fake/root folder,
http://superuser.com/questions/537683/how-to-fix-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-14-not-found

**Comment by cpicanco** [comment]
It is too risk to install this "thing" system wide.

Unfortunately I am stuck in a "Inconsistency detected by ld.so: dl-close.c: 743: _dl_close: Assertion `map->l_init_called' failed!" error with the fakeroot method.
