### ISSUE TITLE
Player: Play speed sometimes does not match indicator (e.g. 1/4x)

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1043]
Still trying to find the cause of this, but it's clear that sometimes it says it's playing at 1/4x when, in fact, it isn't.

**Comment by papr** [comment]
Is it playing faster or slower than expected? Just have a look at the file backend changes in the play back speed commit. It is possible that my playback implementation is incorrect.

**Comment by performlabrit** [comment]
Will do.  It works most of the time, but there are occasions where the play
speed multiplier in the lower left will change in response to keypresses of
left/right, but play speed does not actually change.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
Fixed with  82e6799
