### ISSUE TITLE
Player: Sidebar doesn't work, can't click icons

### ISSUE THREAD

**Issue by koove** [pupil-labs/pupil#1045]
First time I launched player and played around with plugins, the sidebar was working fine. All of a sudden now when I click the icons nothing happens. They look clickable, the color changes to white, but I can't see anything else. Tried reinstalling everything but nothing changed. Recorder seems to be working fine. Any ideas?

**Comment by papr** [comment]
This is a duplicate issue and has been resolved already. The next bundle release will include the fix.

Delete your pupil_player_settings folder for a manual reset of the application.
