### ISSUE TITLE
Capture : My 3D world camera doesn't work on Win10

### ISSUE THREAD

**Issue by njugh** [pupil-labs/pupil#1049]
My world camera is Intel RealSense R200 RGBD camera.I download pupil apps(v1.2-7),and from the doc,I know  the 3D camera is bundle supported on macOS and Windows.But when I uses it on my thinkpad , the 3D camera only shows gray pixels on the screen.I test on my friend's Macbook,and the camera works well.Does anyone else meet this situation?

**Comment by mkassner** [comment]
@njugh  this is a windows driver issue. please make sure the update windows to the latest version and update the drivers as well.
