### ISSUE TITLE
Player frame rate

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#105]
For some reason I am getting 40-50 fps (at least in the REC FPS caption). But the max fps is 30, so I am a little bit confused.

**Comment by mkassner** [comment]
Is that the average? Can you post a screenshot?

**Comment by cpicanco** [comment]
In the first run it is capped to 8-10 FPS
![2015-03-11-152109_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6607425/7bd4bec0-c81d-11e4-8bfa-257348d30d76.png)

After interacting with the seek bar it gives 42- 43 FPS
![2015-03-11-151919_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6607382/102e2b8e-c81d-11e4-9e8f-8aeb2e9b2927.png)

**Comment by cpicanco** [comment]
I was really confused. I could not replicate this with the most recent Capture. I am not sure if I saw this in the capture (possibly not).

**Comment by mkassner** [comment]
Its just a bug in the display of the average framerate. I think we have this fixes now.
