### ISSUE TITLE
do not filter based on confidence in gaze mappers

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#1052]
just map compute gaze confidence and filter this in consuming plugins.

**Comment by performlabrit** [comment]
I'll bump this.  Most eye trackers behave this way - attempt to detect the pupil regardless of the quality, and spit the data out along with its confidence metric and perhaps a blink flag.  In its current setup, the pupil tracker is effectively throwing away data.

**Comment by cpicanco** [comment]
Oh my gosh. That is way my confidence comparisons were indifferent. I will need to redo the job.

**Comment by mkassner** [comment]
Just to clarify. We are reporting pupil detection results for each eye frame. We just have not been mapping low confidence pupil data to gaze. This is what this issue addresses.

**Comment by mkassner** [comment]
But yes. I think this is a good improvement. We will implement and test.

**Comment by mkassner** [comment]
this is related: #1047

**Comment by cpicanco** [comment]
@mkassner , When you say `gaze mapping` does it includes exports or just visualizations?

**Comment by cpicanco** [comment]
@papr Can you clarify this issue a little bit? Whe the boss said that "We just have not been mapping low confidence pupil data to gaze." Does it includes exports or not?

**Comment by papr** [comment]
@cpicanco He was referring to the fact that all binocular mappers dismiss pupil datums with less than 0.6 confidence to avoid bad mappings due to low confidence data. The solution would be to map this low confidence data in a monocular fashion instead of dismissing it.

**Comment by cpicanco** [comment]
So far I am understanding that binocular mappers will dismiss low confidence data (hence, dismissed data cannot be exported).

I have one simple question:

- Lets say your data have 100 items, 90 above, 10 below the confidence threshold. Is it possible to map (calibrate) using only these 90 points but apply this mapping to all points?

**Comment by papr** [comment]
Yes, I am implementing this right now.
