### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by majoge** [pupil-labs/pupil#1059]
Hello,

I would like to calculate the distance between a point on a tracked surface and the user. For example the distance from point [0.5,0.5] (in normalized coordinates) on the surface to the user.

The idea is to calculate two points in 3D and calculate the distance between them.

My current implementation uses eye_center_3d of the gaze message, if available, or otherwise the middle between eye_centers_3d["0"] and eye_centers_3d["1"] for position of the user.

But how can I get the position of a point on the surface in the same coordinate system as the user position?

Greetings

**Comment by papr** [comment]
> My current implementation uses eye_center_3d of the gaze message, if available, or otherwise the middle between eye_centers_3d["0"] and eye_centers_3d["1"] for position of the user.

This is a good start. Unfortunately it is impossible to calculate the depth of a surface marker without fixing its size. See this [PR](https://github.com/pupil-labs/pupil/pull/872) for more work-progress work on this topic.

**Comment by majoge** [comment]
The surface is defined by 4 markers and marker sizes and surface size are fixed and known.

My guess is using camera_pose_3d from "surfaces" messages, but how do I use it to transform a 2D point on the surface to the 3D coordinate system of the user position?

**Comment by papr** [comment]
Please see the #1484 Head Pose Tracker feature. It generates a 3d coordinate system in which the subject's head movement is tracked. Using the current estimation of the subject's head pose, one can translate gaze into the the 3d coordinate system.
