### ISSUE TITLE
Invaild data found when processing input

### ISSUE THREAD

**Issue by marjahn** [pupil-labs/pupil#1067]
![invaliddatafound](https://user-images.githubusercontent.com/36267963/36031369-c9973478-0daa-11e8-9660-0b6b3b5ba4e7.PNG)
This error occurs when importing recorded directories from pupil mobile in pupil player. The detection progress stops. Redetection didn't work. Any advice?

**Comment by papr** [comment]
As the error message says, the video decoder encounters invalid data. This hints to a corrupted eye video file. Are you able to play back the eye video in VLC without problems? Where is your recording located? Are you loading the recording in Pupil Player from an external device, e.g. external hard drive, usb stick, or sd card?

**Comment by marjahn** [comment]
The eye videos play fine in VLC. I copy the directory from the phone and paste it in the recordings folder from pupil capture before dragging them into pupil player...

**Comment by papr** [comment]
Would it be possible that you upload and send me the eye video in a personal message? It would help us to debug your issue.

**Comment by marjahn** [comment]
Alright, email is on the way
