### ISSUE TITLE
replace exception handling with logging.exception

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#1073]
https://docs.python.org/3/library/logging.html#logging.exception

Seems to be the desired built-in solution over:

```
 import traceback
        trace = traceback.format_exc()
        logger.error('Process Capture crashed with trace:\n{}'.format(trace))
```

**Comment by papr** [comment]
This would not integrate well into our pipeline since we serialize the `exc_info` in `zmq_tools.py` and loose the possibility for auto-formatting this information in `main.log_loop`.
