### ISSUE TITLE
World Camera not available

### ISSUE THREAD

**Issue by PeterWolf93** [pupil-labs/pupil#1074]
Hello there,
right now I'm trying to get my Pupil Headset working on Windows 10. I'm using the setup with the 3D world cam (Intel R200) and the binocular eye cameras. My problem right now is that the world camera doesn't work. I have installed the Pupil drivers from [the offical site](https://docs.pupil-labs.com/#download-drivers-and-tools) and my devices now look like [this](https://ibb.co/ddK0i7). But when I try to select the world camera in the Pupil Capture App (1.3.9) only the eye cameras (they work perfectly btw) are [listed](https://ibb.co/e8z5GS).
I already tried to install librealsense as mentioned [here](https://github.com/pupil-labs/librealsense) but since there's no helpful installion guide for windows I can't do the installation.
Is there an easy to understand step-by-step guide which describes how to make the world camera working?
Thanks in advance.

**Comment by mkassner** [comment]
Hi, please make sure that you have selected the Realsense capture backend in the world window. Only with this you can use the realsense camera.

**Comment by PeterWolf93** [comment]
Hi,
Thanks for your answer. I already tried to choose the RealSense3D option and the the Intel RealSense R200 as source in the Backend Manager panel. The next thing what happens is that [this panel open](https://ibb.co/f3gKAn), but I still don't get any video output from the World Camera.

**Comment by mkassner** [comment]
In this case the issue is that your version of Windows does not have the correct drivers from intel. please update your windows and re-install the driver via the device manager.
