### ISSUE TITLE
Lab Streaming Layer: user plugin directory

### ISSUE THREAD

**Issue by BCIstorm** [pupil-labs/pupil#1076]
Hello,
 trying to use LSL for the first time in order to sync Pupil eye tracker with other EEG hardware also able to "talk" with LSL.
 Following the instructions here:
 []https://github.com/sccn/labstreaminglayer/tree/master/Apps/PupilLabs
 
But, where is the **user plugin directory** of Pupil Capture?

Thanks

**Comment by cboulay** [comment]
I think it used to be stated explicitly in the [pupil plugin docs](https://docs.pupil-labs.com/#plugin-guide) but I can't find it.
Anyway, `C:\Users\Chad\pupil_capture_settings\plugins` (obviously change Chad to your username).

**Comment by BCIstorm** [comment]
Thank you @cboulay , but now when starting "pupil_capture" there's a missing liblsl64.dll :

```
C:\>cd C:\Users\Pedro\Downloads\ET\pupil_capture_windows_x64_v1.1.2

C:\Users\Pedro\Downloads\ET\pupil_capture_windows_x64_v1.1.2>pupil_capture.exe
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [WARNING] plugin: Failed to load 'pupil_lsl_relay'. Reason: 'library liblsl64.dll was not found - make sure that it is on the search path (e.g., in the same folder as pylsl.py).'
world - [WARNING] plugin: Failed to load 'pylsl'. Reason: 'library liblsl64.dll was not found - make sure that it is on the search path (e.g., in the same folder as pylsl.py).'
world - [WARNING] plugin: Failed to load 'pylsl'. Reason: 'library liblsl64.dll was not found - make sure that it is on the search path (e.g., in the same folder as pylsl.py).'
world - [WARNING] plugin: Failed to load '__init__'. Reason: 'attempted relative import with no known parent package'
```

**Comment by papr** [comment]
@BCIstorm This is a problem with your `pylsl` build. It should include a file called `liblsl64.dll`. Our plugin will not work without a correctly built `pylsl`. Alternatively, you should be able to install `pylsl` via pip by running `pip3 install pylsl`. This module will include the pre-built library files. You will have to copy the module to the Capture plugin nonetheless.
