### ISSUE TITLE
Running from source: from .detector_3d import Detector_3D ImportError

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/pupil#1077]
Using Windows 10, Python 3.6 from miniconda in a virtual env.
The build seems to have completed.

When I try to run main.py, it crashes during `from .detector_3d import Detector_3D`, with `ImportError: DLL load failed: The specified module could not be found.`.

In `C:\work\pupil\pupil_src\shared_modules\pupil_detectors` I have the two .pyd files and `detector_3d.cp36-win_amd64.pyd` is 1,545 KB.

Is there a way for me to know which DLL is failing? I tried putting a bunch of print statements in between the import steps in detector_3d.pyx but those don't seem to do anything. I see print-related code in the cython-generated cpp file but it doesn't seem to get called. I don't know if that means that the import fails before that point or not.

I don't know if this is important, but after the link step for detector_3d, I get the following output. It's also worth noting that in a few of my build attempts it has crashed at this step due to running out of memory!

```
Generating code
c:\work\ceres-windows\glog\src\logging.cc(2025) : warning C4722: 'google::LogMessageFatal::~LogMessageFatal': destructor never returns, potential memory leak
Finished generating code
EyeModel.obj : warning LNK4049: locally defined symbol ?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ (public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)) imported
EyeModel.obj : warning LNK4049: locally defined symbol ??0LogMessageFatal@google@@QEAA@PEBDHAEBUCheckOpString@1@@Z (public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int,struct google::CheckOpString const &)) imported
EyeModel.obj : warning LNK4049: locally defined symbol ??0LogMessageFatal@google@@QEAA@PEBDH@Z (public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)) imported
EyeModel.obj : warning LNK4049: locally defined symbol ??1LogMessageFatal@google@@QEAA@XZ (public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)) imported
EyeModel.obj : warning LNK4049: locally defined symbol ??0CheckOpMessageBuilder@base@google@@QEAA@PEBD@Z (public: __cdecl google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)) imported
EyeModel.obj : warning LNK4049: locally defined symbol ??1CheckOpMessageBuilder@base@google@@QEAA@XZ (public: __cdecl google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)) imported
EyeModel.obj : warning LNK4049: locally defined symbol ?ForVar2@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ (public: class std::basic_ostream<char,struct std::char_traits<char> > * __cdecl google::base::CheckOpMessageBuilder::ForVar2(void)) imported
EyeModel.obj : warning LNK4049: locally defined symbol ?NewString@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ (public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::base::CheckOpMessageBuilder::NewString(void)) imported
```

**Comment by mattem86** [comment]
Same issue here, no virtual env, plain python3 install with pip etc... 

The build of the pupil detectors works separately (as described in the docs)

**Comment by cboulay** [comment]
I used Dependency Walker and discovered that I had a rogue version of `boost_python3-vc141-mt-1_64.dll` on my path and it was looking for python2-related DLLs. I removed all Boost dirs from my path and copy-pasted the correct `boost_python3-vc141-mt-1_64.dll` from `C:\work\boost\stage\lib` to `C:\work\pupil\pupil_external`. I'm now getting passed this error.

**Comment by mattem86** [comment]
The issue on my side was, I missed the change on this:

Open C:\work\boost\boost\python\detail\config.hpp with Visual Studio 2017 Preview
Change L108 from define BOOST_LIB_NAME boost_python to define BOOST_LIB_NAME boost_python3
Save the file and close Visual Studio

I rerun the batch and build process and voilá :) So I didn't have to copy it to pupil_external.
