### ISSUE TITLE
Online pupil diameter not displaying in pupil_capture

### ISSUE THREAD

**Issue by tombullock** [pupil-labs/pupil#1078]
I noticed that the online pupil diameter displays in the top left hand corner do not appear to be registering anything.  I'm running Pupil-Capture 14-1 on OS X Sierra.  

Not a big deal, but I figured I'd point it out. 

![screenshot 2018-02-17 13 47 20](https://user-images.githubusercontent.com/23244871/36345914-1e412954-13e9-11e8-959c-79d2c8cce7a3.png)

**Comment by papr** [comment]
The diameter is currently only supported for the 3d detection mode. You are running the 2d detection.

**Comment by tombullock** [comment]
OK good to know.  Thanks.
