### ISSUE TITLE
Suggestion: add a real-time annotation indicator to pupil_capture

### ISSUE THREAD

**Issue by tombullock** [pupil-labs/pupil#1079]
It would be helpful if you could add something to the pupil capture GUI that would allow us to check in real time if annotations are being registered.  For example, a button on the left hand side of the display that briefly turns red every time an annotation is received.  This would enable my research assistants and I to easily verify that annotations are being received during an experiment, and troubleshoot if this is not the case.  Thanks.

**Comment by papr** [comment]
Fixed with #1080
