### ISSUE TITLE
Offline Surface Tracker: Reculation only after finishing add/edit of surface 

### ISSUE THREAD

**Issue by sfeu** [pupil-labs/pupil#1088]
Currently with the latest 1.41 release the recalculation process is started after each single corner movement of a surface. This ends up in four recalculations for positioning a new surface and taks a considerable amount of time for huge recordings. 

It would be great if the recalculation process is only started after the edit is finished (therefore the edit button is finally pressed again)'- or even better: a toggle switch that can be used prevent recalculation and can be used while adding several surfaces.

**Comment by papr** [comment]
Fixed in #1268
