### ISSUE TITLE
Windows Bundle crash on window resize

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#109]
When a window is resized it seems to halt the update loop. If you do this for to long I think the videobackend times out and the app closes. 

This should be handled differently:
The videobackend should not be sensitive to a slow or halted update loop.

**Comment by MichaelBarz** [comment]
I could not reproduce this error, neither from source, nor with the bundle.
Can someone confirm this issue and maybe provide further information?

**Comment by mkassner** [comment]
I hunted this down to only happening when using single usb pupil. So this must not be related to resizing.
