### ISSUE TITLE
[Improvement] [Player] Allow manual correction sections

### ISSUE THREAD

**Issue by arispawgld** [pupil-labs/pupil#1094]
An improvement I would love to see in Pupil Player would be to allow for us to section off parts of the video for manual corrections (x-y offsets) rather than applying the offset to the entire video. Another option could be to add a natural features editor to the online calibration (manual correction) section so that we could refine calibrations even when done online. Even with this, being able to section off timestamps for this would be great.

**Comment by papr** [comment]
Offline calibration allows the user to create multiple calibration section. Each section has
- a calibration range (range of calibration markers/natural features and pupil positions) that will be used to calibrate
- a mapping range (range of pupil positions) that will be mapped to gaze points according to this sections calibration
- a manual x-y-offset that is applied to this section's gaze

Therefore I think, most of your improvement idea is already implemented. I would suggest to redo the calibration if you see a consistent offset during operating Capture. I generally advise against the usage of the manual offset. It is a linear offset but slippage is rarely linear. I would suggest to add multiple calibration sequences to your experiment setup to be able to create a new calibration section for each sequence.
