### ISSUE TITLE
Remember 'absolute exposure time' for HTC Vive setup

### ISSUE THREAD

**Issue by Djinn008** [pupil-labs/pupil#1096]
Hello everyone,

mpk ask me on discord to raise an issue about this "problem".

When I launch Captue, every time, I need to change the value of the 'absolute exposure time' between 120 to 127 otherwise the image is too dark and the algorithm doesn't work well.

It's not really handy because I have to remove the HMD to change the value on each eye.

Thank you for your help,
D.

**Comment by cboulay** [comment]
@Djinn008 Just a tip: If you start Steam first, before starting SteamVR, then the SteamVR overlay will have the option to view the Desktop. Then you can look at your desktop while you have the HMD on. This is what I do to tweak the camera settings.

120-127 exposure seems a little high to me. It will limit your sampling rate (but you could still get 60 fps with that, I think) and it will increase motion blur though I don't know how relevant that is. Have you tried instead increasing gamma + contrast?

**Comment by Djinn008** [comment]
Thanks for the idea of desktop it can save me some time.

I manage to keep 60fps @ 1280x720 with 127.

I haven't fin where to modify gamma nor contrast.
