### ISSUE TITLE
Player: Confusing interface for surface editing 

### ISSUE THREAD

**Issue by sfeu** [pupil-labs/pupil#1102]
Please see the attached images of a typical situation with several (23) surfaces.

![playersurfaces](https://user-images.githubusercontent.com/80262/36738394-ad045e8a-1bdd-11e8-94b4-c7109e8aff63.jpg)

I would like to suggest the following changes:

- set the surface name also as the title in the right menu
- if one clicks on the surface list entry on the right menu the corresponding surface gets highlighted and only in this case the editing options are shown.
- if one clicks on a surface frame the corresponding list entry gets highlighted and the the editing options are shown.

**Comment by cpicanco** [comment]
I am impressed, are you doing this manually or by means of a custom plugin?

**Comment by sfeu** [comment]
Actually i did this manually, but doing it automatically was also my first thought. Since i have the regions of interests available on a 2D coordinate system i thought about transforming this data into pupil's surface_definitions config file.

I think this can be done by using the marker_to_screen or screen_to_marker functions:
https://github.com/pupil-labs/pupil-helpers/blob/master/utility_marker_positions_in_pixels.py

Any help is appreciated.

**Comment by papr** [comment]
@sfeu I agree on your core issue but may I make a suggestion on how to simplify the screen surfaces? I would define a single surface that captures the complete screen content. In its menu on the right, you can define the surface size in screen pixels. Gaze that is mapped onto this surface using these dimensions. Therefore you would receive gaze in pixel positions and could map them to the single sub-elements using your 2d coordinate system that you mentioned above.

**Comment by cpicanco** [comment]
Also, if you don't want to use fiducial markers you could try this third party plugin:

https://github.com/cpicanco/player_plugins#how-to-use-the-screen_tracker_offline-plugin

It would be very handy since no surface edit would be required.

**Comment by cpicanco** [comment]
Hummm.... I noticed that you are also trying to record keyboard gaze events. Well, my suggestion would not work in this case.

**Comment by sfeu** [comment]
@papr Many thanks for this suggestion!! I always thought the surface size was just for the heatmap generation but was wondering why i then need to define the size of my surface markups myself ;) Now the purpose of the surface size definition is getting clear to me :+1:
