### ISSUE TITLE
Blink detection data export file

### ISSUE THREAD

**Issue by AlexKonto** [pupil-labs/pupil#1107]
Hi, I am using 1.4.1 and I have an issue with the exported excel file, which includes the blink detection data. The data is shown correctly only for some of the blinks. I am sure there were many more blinks recorded but these are not shown correctly in the file. As you can see with the pink shadow, there is a lot of data not correctly depicted in columns, which I guess should be the start timestamps. Data in other parts of this sheet is also depicted incorrectly. It is very difficult to say what refers to what considering the amount of data. This problem appears only when I use offline pupil detection as the pupil producer. The export file appears correctly when I use pupil from recording.

Any ideas?

![untitled](https://user-images.githubusercontent.com/32708904/36871957-b60d6dc2-1d9b-11e8-91ae-31afa6cad901.png)

**Comment by SarahT8** [comment]
Delete that

**Comment by cpicanco** [comment]
Hi @SarahT8 , what do you mean?

**Comment by cpicanco** [comment]
It seems that @SarahT8 is some sort of bot.

**Comment by mkassner** [comment]
@cpicanco  I reported that. Lets see what happens.
