### ISSUE TITLE
New feature: Video overlay in Pupil Player

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#1109]
more or less exactly like eye video overlay but:

 - non-unique
 - ability to select the video file by dragging onto the plugin gui? Or dropdown list from path.
 - requires that a file_name_timestamps.npy or file_name.time (with auto conversion, depending on implementation speed no need to save result to file.) file is also present.

Use case:
I use Pupil Mobile or Capture to recording a third point of view and want to merge this into my recording.

**Comment by papr** [comment]
We could simplify the eye overlay plugin such that it opens this video overlay plugin once for each eye video found. This would avoid potential code duplication but has the (dis)advantage that one has to set settings (e.g. scale, opactity, etc) for each plugin instance separately.

**Comment by papr** [comment]
Fixed in #1489
