### ISSUE TITLE
Windows Capture bundle survey

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#111]
If you have tested the windows bundle please report Hardware and software configuration with your results here:

**Comment by mkassner** [comment]
OS: Windows 8.1 
Host: Microsoft Surface Pro
Headset: Pupil Pro with single USB

starts: Yes
runs stable: Yes (except for know resize bug)
records: No video (known bug)

comment:
CPU load is hight when texture update : color

**Comment by mkassner** [comment]
OS: Windows 8.1
Host: Lenovo Thinkpad T410
Headset: Pupil Pro with single USB

starts: Yes
runs stable: Yes (except for know resize bug)
records: No video (known bug)

comment:
CPU load is hight when texture update : color

**Comment by mkassner** [comment]
OS: Win 7 Professional SP 1 ; 64 Bit
Host: AMD Athlon 64 X2 Dual Core Processor 5600+ 2.8 GHz 3 GB RAM

starts: No

It immediatley crashes right after launch. The two windows appear in white and then they close again after about half a second.

contributed by pupil-discuss user.

**Comment by mkassner** [comment]
OS: Windows 8.1 Pro
HOST: Intel NUC Intel Core i5-4250 CPU and 8 GB
Device: Pupil Pro (double usb?)

starts: Yes
runs stable: No

comment:
Windows capture bundle starts OK but after around 5 seconds ‘world’ crashes (‘eye’ remains OK).

**Comment by toshikurauchi** [comment]
OS: Windows 7 Professional SP 1 ; 64 bit
Host: Lenovo Thinkpad T440s ; Intel Core i5-4200U CPU and 4 GB
Headset: Pupil Pro Binocular (double usb)
Bundle: v0.5.5.17

starts: Yes
runs stable: Yes
records: Yes

comment:
Second eye camera doesn't show up in binocular mode.

**Comment by Juergen12000** [comment]
As this issue isn't closed yet, I have another info for you:

OS: Windows 10 Home ; 64 bit
Host: Acer Asprie V3-772G, Intel Core i7-4702MQ CPU, 32 GB RAM
Headset: Pupil Pro Binocular
Bundle: v0.6.9

starts: Yes
runs stable: Yes

Issue:
After closing second Eye-Windows for second Eye-Camera, it doesn't appear any more. Not even after a restart of Pupil Capture or deletion of all setting-files.

**Comment by mkassner** [comment]
stale
