### ISSUE TITLE
Pupil-Service for 2 cameras at same time

### ISSUE THREAD

**Issue by kgossage** [pupil-labs/pupil#1112]
I'm trying to get the pupil-service working for 2 cameras at once (similar to running pupil-capture with binocular).  Is there anyway to do this?  No matter what I've tried, I only get data streamed out for Pupil.0.  Thanks

**Comment by papr** [comment]
Make sure that both, `Detect eye 0` and `Detect eye 1` are enabled. Now you should have 3 windows open, two eye windows and the service main window. Do the eye windows show the camera video stream?

![image](https://user-images.githubusercontent.com/168390/36994064-3c58e84a-20b0-11e8-8681-4837c9f79356.png)

**Comment by kgossage** [comment]
I see a settings window that looks just like that when I run pupil-capture,
but there are no controls to turn on to detect eyes in the pupil-service
program.  Is this a very recent addition, I have version 1.2-7.  Thanks

**Comment by papr** [comment]
Ah, yes, this main window comes with a more recent version. Please upgrade to the newest version. I also would recommend to use Pupil Capture in the beginning. It behaves the same as Service but exposes much more options to the user. This is useful for initial experimentation. Service is supposed to be controlled remotely via the Pupil Remote api.

**Comment by kgossage** [comment]
Pablo,

Thank you very much.  I didn't realize how out if date my software was.
That solved it!

Kirk
