### ISSUE TITLE
pyton3 main.py failed after all dependencies installed

### ISSUE THREAD

**Issue by waschbaer00** [pupil-labs/pupil#1113]
Hi there,

after I install all dependencies for Linux, git clone to pupil, and then cd pupil_src, python3 main.py, it gives me this:

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/ics_vr/softwares/pupil/pupil_src/launchables/world.py", line 105, in world
    from methods import normalize, denormalize, delta_t, get_system_info, timer
  File "/home/ics_vr/softwares/pupil/pupil_src/shared_modules/methods.py", line 19, in <module>
    import cv2
ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type

world - [INFO] launchables.world: Process shutting down.

I have Ubuntu 16.04 and ROS installed. 

Should I copy a cv2.so to the path " /opt/ros/kinetic/lib/python2.7/dist-packages/"  from my global dist-package?

Thank you.

Best,bear

**Comment by papr** [comment]
Dear @waschbaer00 
Please be aware that Pupil is not compatible with Python 2. As you can see from the paths, you are not using the Python 3 version of the opencv module. Please make sure to follow the most recent version of the docs in order to compile the opencv module correctly: 

```sh
git clone https://github.com/opencv/opencv
cd opencv
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_TBB=ON -DWITH_CUDA=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=ON ..
make -j2
sudo make install
sudo ldconfig
```
