### ISSUE TITLE
pupil capture no eye cameras

### ISSUE THREAD

**Issue by kbonnen** [pupil-labs/pupil#1115]
I just updated to pupil capture version 1.5.13.  I am running Pupil Capture from source using an intel realsense eye tracker.  When I run capture the world camera starts up as do the eye cameras.  Then they promptly close.  The menu indicates they're being detected but I can't change the control.  When I record, there are no eye videos recorded even though the menu indicates they are.

running on Linux Ubuntu 16.04

**Comment by papr** [comment]
Hey @kbonnen 
Is there any terminal output that might indicate a crash? Do only the eye windows close or the whole program? Could you share your `capture.log` file after such an event with us?

**Comment by kbonnen** [comment]
Only the eye windows close.  The terminal output does not seem to indicate a problem


world - [INFO] launchables.world: Process shutting down.
kate@kate-G551JW:~/dev/pupil/pupil_src$ python3 main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.5.13
world - [INFO] launchables.world: System Info: User: kate, Platform: Linux, Machine: kate-G551JW, Release: 4.13.0-36-generic, Version: #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018
world - [INFO] pupil_detectors.build: Building extension modules...
world - [INFO] calibration_routines.optimization_calibration.build: Building extension modules...
world - [INFO] cython_methods.build: Building extension modules...
world - [ERROR] video_capture.realsense_backend: Setting device option presets failed
world - [DEBUG] video_capture.realsense_backend: Reason: rs_set_device_options(device:0x2fe00b0, options:0x2fdf510, count:39, values:0x2fdb4b0) crashed with: UVCIOC_CTRL_QUERY:UVC_SET_CUR error 5, Input/output error
world - [INFO] camera_models: No user calibration found for camera Intel RealSense R200 at resolution (1920, 1080)
world - [INFO] camera_models: No pre-recorded calibration available
world - [WARNING] camera_models: Loading dummy calibration
world - [WARNING] launchables.world: Process started.
eye0 - [INFO] cython_methods.build: Building extension modules...
eye1 - [INFO] cython_methods.build: Building extension modules...
eye0 - [INFO] pupil_detectors.build: Building extension modules...
eye1 - [INFO] pupil_detectors.build: Building extension modules...
eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID0 at resolution (320, 240)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID1 at resolution (320, 240)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 200 / 256. 
!!!!Packets per transfer = 32 frameInterval = 83263
eye1 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 200 / 256. 
!!!!Packets per transfer = 32 frameInterval = 83263

**Comment by mkassner** [comment]
The logs are not being to helpful nothing look out of the ordinary. What happens when you start with app with default settings?

**Comment by kbonnen** [comment]
Because I couldn't see anything wrong in the logs I just did a clean reinstall of the computer's OS and reinstalled pupil capture.  I'm not sure what was wrong but the clean install worked.

**Comment by Wouter1** [comment]
I had same problem
I needed to go to the General menu and re-enable the "Detect eye 0" and "Detect eye 1" buttons. 
No idea why they turned off.
