### ISSUE TITLE
Menu area and sidebar not correctly alligned in Windows 10

### ISSUE THREAD

**Issue by WillemVlakveld** [pupil-labs/pupil#1119]
In v1.5 the menu area and the side bar at the right side of the screen are not properly aligned when I run Pupil Capture in Windows 10. However, the hot spots are in the correct position. This means that I have to click around half a centimeter underneath the spot where I am visually suppoed to click. I do not if it matters but my screen resolution is 1920X1080.

**Comment by willpatera** [comment]
@WillemVlakveld this should have been fixed in `v1.6` @WillemVlakveld please update and confirm that this has been fixed. I will close this, but please feel free to comment if it has not been resolved and I can re-open.
