### ISSUE TITLE
eye0 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.

### ISSUE THREAD

**Issue by dabinder93** [pupil-labs/pupil#1120]
Hi! 
I just started using the Pupil Pro bilateral rev 021 for my Thesis.
I tried to simply set up the System, but it doesn't show me the Eye Image, just a gray background.

![eye_init_failed1](https://user-images.githubusercontent.com/6490125/37418462-8f5e3258-27b2-11e8-9f3d-a8f2067d7e2d.png)

This is the Error Message which i get:

![eye init failed](https://user-images.githubusercontent.com/6490125/37418479-9dfe159e-27b2-11e8-9ba1-fcd198e7b8c3.png)

I got two different Devices from my University. One Device with 2 Eye Trackers on it and one version with only 1 Tracker on it.
I tried the Pupil Capture Software on two Windows 10 PCs and one Windows 7 PC, just to make sure, that it's not a driver issue.
Sadly nothing worked.

**Comment by willpatera** [comment]
@peteratBHVI @dabinder93 This issue is most likely driver related. We recently made a fix to the driver installer https://github.com/pupil-labs/pupil/pull/1160 - we will merge this PR and include this in the next bundle release.

**Comment by papr** [comment]
@RachelMF do the other cameras work? All cameras should work out of the box on macos.

**Comment by RachelMF** [comment]
The world view camera works as does eye 1. We had eye 0 working when we first opened Pupil Capture. Then as we adjusted the camera for pupil detection- then it stopped working and we get this error.

Sent from my iPhone

On Sep 4, 2018, at 4:28 PM, Pablo Prietz <notifications@github.com<mailto:notifications@github.com>> wrote:


@RachelMF<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_RachelMF&d=DwMCaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=EtazHVxa5am-EBrlP15zb-UA5UP-5OXcXdfQd0CVz8I&m=MBR4Anql6gZ3U89oD_pIz57ffrJkJ0o_RZ9560uVQOo&s=dbH9f8VZmRSfcr0Vxw-h51jqnYJ32yy4LihD5apdMoA&e=> do the other cameras work? All cameras should work out of the box on macos.

-

**Comment by supsensei** [comment]
I am getting the same error on Ubuntu 18.04. All pyuvc installs done per the dependencies. What is the issue here. Any help or trouble shooting greatly appreciated.

**Comment by papr** [comment]
Hi@supsensei
- What do you mean by same error? The same error message?
- For all cameras or only one? If only one, which one?

**Comment by supsensei** [comment]
Hi - When I start the GUI, I get the following error for both cameras on the Linux system. 

![screenshot from 2018-11-26 10-55-43](https://user-images.githubusercontent.com/45256328/48988764-8a110a00-f16a-11e8-8e57-92c56215a415.png)

**Comment by papr** [comment]
@supsensei Are you running from source on Linux? If you open the UVC Manager menu on the right, with which names are the cameras listed?

**Comment by supsensei** [comment]
discussed with wrp on dischord and got in resolved. Appeared to be user user permissions and setting 

echo 'SUBSYSTEM=="usb",  ENV{DEVTYPE}=="usb_device", GROUP="plugdev", MODE="0777"' | sudo tee /etc/udev/rules.d/10-libuvc.rules > /dev/null
sudo udevadm trigger

0664 did not work, but maybe issue with my account.

**Comment by papr** [comment]
Great to see that the issue has been solved.

For reference, the issue is often that the user needs to be added to the plugdev group.

**Comment by Aeelim** [comment]
Hi,
I am getting a similar error on Windows 10 for eye0. The world camera works well, but I have a gray screen for eye0.

eye0 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
eye0 - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [320, 240]
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] launchables.world: Process started.

I tried to restart and reinstall the drivers, but I couldn't find the Pupil camera driver installer to install the drivers manually because the link on Pupil Docs webpage show a Error 404. I don't know what can I do.
Thank you.

**Comment by benedikt-mayer** [comment]
We are having the same error on Windows 10 for eye1. It worked for months for both eyes, now only eye0 and world camera are working. 
We also tried troubleshooting as given in the pupil documentation by uninstalling the drivers, but then faced the same issue as @Aeelim.
Then we tried to install from fresh on a new system, but we got the same error. In device manager, only two cameras (Pupil Cam1 ID2 and Pupil Cam1 ID0) are present. 
We are running the latest version of pupil capture (1.10-20) on the latest version of Windows (10.0.17134 Build 17134). Our device is the hololens add-on.

**Comment by papr** [comment]
@Aeelim @benedikt-mayer Please contact `info@pupil-labs.com` regarding eye cameras that have been working but suddenly do not work anymore.

**Comment by benedikt-mayer** [comment]
@papr We were able to solve our issue by unplugging the connector for each camera and then plugging them in again. ¯\_(ツ)_/¯. Thank you for your fast response.

**Comment by ChrisLeh** [comment]
Hello,
since yesterday, I have the same problem that no camera picture isn't shown anymore (grey picture). Until yesterday everthing worked out. I also removed pupil labs from my computer and installed it again, but without any effect on this problem.

Can you help me regarding this problem?
Best regards 
Christoph
![Ghost Mode](https://user-images.githubusercontent.com/47383374/55667109-73856880-5858-11e9-87ea-ec63670c8239.JPG)

**Comment by papr** [comment]
@ChrisLeh Please follow the instructions above.

**Comment by ChrisLeh** [comment]
@papr Thanks for your quick answer. What instructions do you mean concretly? Unfortonately I'm not a very technical person, so I didn't find out by myself which answers could solve my problem.

Thanks! :-)

**Comment by papr** [comment]
I was referring to contacting info@pupil-labs.com :)

**Comment by papr** [comment]
### Summary
Potential reasons for the _"Init failed. Capture is started in ghost mode. No images will be supplied."_ message are:
- (Linux only) The user is not part of the `plugdev` group. Use `sudo usermod -a -G plugdev $USER` to add the current user to the group. After a computer restart, all cameras should work correctly.
- (Windows only) The drivers are not installed correctly. Go to Device Manager, enable "Show hidden devices" from the menu, remove/deinstall all devices listed in the `libusbk` category. After a restart, all cameras should work correctly.
- Hardware issue. Please contact info@pupil-labs.com in this regard.
