### ISSUE TITLE
Capture on Lenovo Thinkpad T460p Laptop

### ISSUE THREAD

**Issue by njss** [pupil-labs/pupil#1127]
Hi,

I have the pupil eye tracker for Hololens working (3 cameras) on my desktop pc with no problems.

However, on my new laptop it always display an error message:
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables\world.py", line 505, in world
OSError: exception: access violation reading 0x000000000000001C

I have the same python version on both machines and the pupils labs I tried both 1.4 and 1.5, always unsuccessfully.
Any ideas?

Thank you

**Comment by papr** [comment]
Hey @njss 
Which operating systems do you use on your laptop? I have never seen this type of error before...

**Comment by njss** [comment]
I found out that by installing an old nvidia driver (22.21.13.8205 64 bits) this problem is fixed.
It seems to be a problem with new NVIDIA drivers for Optimus technology (automatic switch between Intel or nvidia graphic cards).
Now it work and I can use pupil-labs again...Pupil Labs does't work on Lenovo laptops (we have several models) with the new nvidia drivers on dual graphic cards systems.

**Comment by njss** [comment]
This is really a nasty problem. I installed tensorflow and CUDA 9.0, which in turn installed a new nvidia graphics driver. Again, pupi-labs doenn't work, and I will be forced to install a very old NVIDIA driver to make it work again. This seems to be a problem on the way pupil labs handles OpenGL/GPU calls.

Can you please have a look at this problem?

**Comment by papr** [comment]
Hey @njss 
This seems to be an edge case issue that we are not be able to reproduce on our machines. Without being able to reproduce the issue, it is impossible for us to find a fix.

Are you bound to run everything on one computer? Would it be possible to do the recording on a different computer? The Hololens Relay api is udp based. This means that you can run Capture on one machine and your Hololens application + CUDA on a different one.

**Comment by njss** [comment]
Thank you for your fast reply. Well, I guess you only need to test it on any Lenovo T4xxp model to experience this problem. This is both a Dev and a demo machine for hololens projects. I do honestly just want to be able to use the latest Nvidia Optimus drivers. For now it works by installing old drivers, but I guess you might soon have other complains when using similar newer dual graphic cards laptops.

**Comment by njss** [comment]
After many drivers install and calling the support, we concluded that this really a problem with the Lenovo drivers for the shared video system Intel/NVIDIA on this specific model.

Thank you for the support.

**Comment by papr** [comment]
Good to hear that the origin of the issue has been resolved.
