### ISSUE TITLE
Camera Intrinsic Estimation Not Working

### ISSUE THREAD

**Issue by jinha3411** [pupil-labs/pupil#1130]
I am trying to run the camera intrinsic matrix.
For making sure, I purchased the pupil-labs VR version so I do not have world camera.
When I start up the program, two windows pop up (world view, and pupil detector window). For world view, the screen is grey, which I understand since there is no world camera. 
For pupil detector module, I see the image is correctly streaming.
When I start up the camera intrinsic estimation, the circle pattern pops up and I try to make the board screen fits into the image and I click "i" button to capture the image.
Then, "10 to go" text is displayed next to I button, but the number does not decrease nor estimate the calibration pattern even though I press "i" ten more times.
Is there any certain procedure that I missed to run this plugin?

thank you

**Comment by papr** [comment]
Dear @jinha3411 
The camera estimation plugin is designed to work for the world camera only. Usually it is not necessary to know the eye cameras' intrinsics. Nonetheless, you are able to perform the procedure for the eye cameras as well by following these steps:
1. Close the eye windows
2. Select the eye camera whose intrinsics you want to estimate in the `UVC Manager` menu of the world window.
3. You should see the gray-scaled video of the selected camera
4. Perform the camera intrinsics estimation procedure by holding the pattern* into the eye cameras field of view

\* Be aware that you will need the pattern to be visible in the IR spectrum of the eye cameras. This means that you are not able to use the pattern displayed on the screen.
