### ISSUE TITLE
A query: editing and re-importing pupil data

### ISSUE THREAD

**Issue by loughboroughAccount** [pupil-labs/pupil#1136]
Hi,

I'd like to ask whether it is possible to edit somehow gaze data captured, modify it and use it again in playback so that filtered gaze coordinates would be mapped instead?

In essence, my data are contaminated with a large amount of noise due to impact with the ground while running and I am trying to get around this somehow.

Any advice will be greatly appreciated.

Best regards

**Comment by papr** [comment]
You can use the [post-hoc pupil detection and gaze mapping](https://docs.pupil-labs.com/core/software/pupil-player/#pupil-data-and-post-hoc-detection) in this case.
