### ISSUE TITLE
Screen capture and mapping

### ISSUE THREAD

**Issue by imagoiq** [pupil-labs/pupil#1138]
Hello,

Just wondering if there is or will be a way to capture the screen inside pupils capture for website user testing (for example) ? Or maybe there is a recommended workflow ? I've found this related issue #310 it don't seems to be implemented. Or is there a simple way to map a screen capture into the world camera imagery (probably a dream) ?

Thanks in advance

**Comment by papr** [comment]
Apologies for the very delayed response. It is recommended to use [surface tracking](https://docs.pupil-labs.com/core/software/pupil-capture/#surface-tracking) in this case. Add markers around your computer screen and define your screen as a surface in Pupil Capture/Player.
