### ISSUE TITLE
Not enough ref point or pupil data available for calibration

### ISSUE THREAD

**Issue by cadop** [pupil-labs/pupil#1140]
I had just setup the device for the first time.  When looking at the eye camera, there was both the pupil in red and the eye in green circle.  I used calibrate and it all worked.  Now when going to calibrate again, it returns the error: 

```
Starting Calibration

Stopping Calibration
world - [ERROR] calibration_routines.finish_calibration: Not enough ref point or pupil data available for calibration.
```

I am not sure if it is the eye tracking, but now I do not see the green circle.  However the red circle of pupil is being tracked well.   What are some common issues causing this?

**Comment by cadop** [comment]
Issue was in having the socket used by pupil service at the same time.

**Comment by cadop** [comment]
I had loaded pupil service and then loaded pupil capture.  Because service was using the socket, the capture couldnt access data and then would fail saying that error 'not enough ref point..'

**Comment by alperuzunn** [comment]
How did you solve your problem? I am trying to change the port but the result is the same.

**Comment by papr** [comment]
This is an old error message and has been clarified in newer software versions. Please check if the error message states insufficient reference points **or** pupil data.
- not enough ref points - adjust your scene camera s.t. the markers are visible in the camera's field of view; ensure the markers are large enough
- not enough pupil data - check your [pupil detection quality](https://docs.pupil-labs.com/core/#_3-check-pupil-detection)
