### ISSUE TITLE
libilmbase12 missing from Linux bundle

### ISSUE THREAD

**Issue by jampekka** [pupil-labs/pupil#1142]
Debian has removed libilmbase12 in favor of libilmbase23 in sid and testing. OpenCV links to this library, but it is not included in the bundle. This means that the bundle won't run on Debian sid or testing. This will probably become an issue also in Ubuntu 18.10.

**Comment by willpatera** [comment]
@jampekka you can take a look at all dependencies for Ubuntu `18.04` in our docker container in the [`ubuntu_18.04` branch](https://github.com/pupil-labs/pupil-docker-ubuntu/tree/ubuntu_18.04) - I would assume that `libopencv-dev` will be able to resolve dependencies itself when installed from apt. I can confirm that this image works as I have used it to create bundles that have been tested on the `18.04` preview release.
