### ISSUE TITLE
Oops! That was not a valid recording 

### ISSUE THREAD

**Issue by iserranoe** [pupil-labs/pupil#1143]
Hello, 

I am trying to visualise a recording made with pupil_capture with pupil_player, but when I drop the directory (named xxx) onto the window I obtain the message: "Oops! That was not a valid recording". What could it be the problem?
I am using Windows 10 and the stand alone version.

Thank you

**Comment by mkassner** [comment]
@iserranoe  can you post names of the files that are in `xxx`?

**Comment by iserranoe** [comment]
Hello,

I tried in Linux and it seems to work fine. I even played the recorded files in Linux with the Windows Pupil_player and it is working as well. Comparing both, I see the 'offline_data' folder is missing in the Windows recording folder. I don't know if that is relevant. 
The names of the files (in Windows are):
- eye0
- eye0_timestamps.npy
- info
- pupil_data
- surface_definitions
- user_infor
- world.intrinsics
- world
- world_timestamps.npy

Thank you

**Comment by mkassner** [comment]
if the same recording works on linux I m not sure what the issue is....

**Comment by papr** [comment]
This issue typically occurs on windows if the path includes any non-ascii/utf8 characters.

**Comment by iserranoe** [comment]
I tried recording in a different folder but 'offline_data' folder is still missing.

**Comment by papr** [comment]
The Offline data folder is not the issue. It is created by player and contains intermediate cache results. Nothing to worry about. Could you please post the complete path of the recording?

**Comment by iserranoe** [comment]
I tried two paths, neither of them working:
- C:\Users\Ines\recordings
- D:\recordings

2018-04-13 16:01 GMT+01:00 Pablo Prietz <notifications@github.com>:

**Comment by papr** [comment]
Could you share the recording in question with us? Preferably, upload it to Google Drive and share it with info@pupil-labs.com

**Comment by papr** [comment]
Sorry for the delayed edit. Please share the recording with data@pupil-labs.com instead.

**Comment by iserranoe** [comment]
It was already solved from info@pupil-labs.com 
It has to do with some "Inés" instead of "Ines" in the info.csv file 
Thank you for your time!

**Comment by ethangamer0800** [comment]
Hi I have the same problem how do I fix it?

**Comment by papr** [comment]
@ethangamer0800 Without further information, it is impossible to tell what is going wrong. Can you share the recording with data@pupil-labs.com for concrete feedback?
