### ISSUE TITLE
Intrinsic Camera & Surface mapping

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#1144]
Hi!
I'm confused whether the pupil-player automatically applys the intrinsic camera estimation or not (when I select the fisheye-correction in the intrinsic camera plugin during recording, the "show undistorted image" looks quite good to me).

In the player I get the distorted view (no plugin to "show undistorted image"). But the surface marker shows me an **UNdistorted** rectangle. 

My questions: 
1) On what are calibrations, fixations, surfaces, saccades etc. calculated, distorted or undistorted? 

2) where do I change distorted/undistorted in pupil player?

I'm linking @papr because I was chatting with him in discord.

**Comment by cpicanco** [comment]
As far as I know, camera intrinsics are used for 3d data and homography only in pupil player. For sure, there is no "show undistorted image" in pupil player. Nice question, it would be great to know a bit more about this stuff.

**Comment by mkassner** [comment]
@behinger  we use the intrinsics and dist. coeffs. to project on to the image and unproject from it. This means:

 - We do not undistort the world camera image
 - 2d gaze data (norm_pos etc) is not corrected for distortion thus consistent with the world camera image
 - 3d gaze data is "undistorted"
 - show undistorted image is for assessing the intrinsics calibration quality only.
 

I hope this is helpful.

**Comment by behinger** [comment]
@mkassner thanks for your answer. This helps already quite a bit. 

- I'm was initially confused, because the fitted surface is square. like this:
![image](https://user-images.githubusercontent.com/10183650/38730206-eb311e68-3f15-11e8-8a8d-f6c8290bb3d2.png)
This is visually a bit confusing. Do I understand correctly that the surface-algorithm (with convex hull + simplify) is robust towards the distortion? Does the surface-marker detection take the distortion into account when it searches for the targets?

- I understand that the normpos output of the surface is still in the distorted coordinate frame. Is this a problem when estimating saccade parameters like size? My thinking is, that if I get a delta-X of 0.2 at the edges vs. the middle, right now I would conclude the same saccade size in angles, but actually the one at the edge is larger (due to the distortion). The same would be true for your displacement fixation detection algorithm, or other algorithms using velocities etc.

Is my understanding so far correct? I will then probably try to undistort the normpos values - I do not need the scene camera for more than the mapping & surface detection -> I should be alright there

**Comment by behinger** [comment]
Partial answer to my question: If I understand "reference_surface.py" under "add_marker" correctly, the surface is calculated on undistorted markerpositions
```
        res = self._get_location(visible_markers,min_marker_perimeter,min_id_confidence,locate_3d=False)
        if res['detected']:
            support_marker = Support_Marker(marker['id'])
            marker_verts = np.array(marker['verts'])
            marker_verts.shape = (-1,1,2)
            if self.use_distortion:
                marker_verts_undistorted_normalized = self.g_pool.capture.intrinsics.undistortPoints(marker_verts)
            else:
                marker_verts_undistorted_normalized = self.g_pool.capture.intrinsics.undistortPoints(marker_verts)
            marker_uv_coords =  cv2.perspectiveTransform(marker_verts_undistorted_normalized,res['m_from_undistored_norm_space'])
            support_marker.load_uv_coords(marker_uv_coords)
            self.markers[marker['id']] = support_marker
```

**Comment by papr** [comment]
I will close this issue as a duplicate in favor of https://github.com/pupil-labs/pupil/issues/1260#issuecomment-412449636
