### ISSUE TITLE
Pupil Player Saccade detector

### ISSUE THREAD

**Issue by PatrikPluchino** [pupil-labs/pupil#1145]
Dear All,

               I would like to kindly ask whether there is someone that has created a customized code/plugin in order to detect saccades (at least the duration) on data (with 120Hz sampling frequency) imported in Pupil Player. 

Thank You all in advance.

Best Regards,

Patrik Pluchino

**Comment by papr** [comment]
Dear @PatrikPluchino 
unfortunately there is no such plugin yet. Follow https://github.com/pupil-labs/pupil/issues/159 to get updated on this issue.
