### ISSUE TITLE
Bug: Sensor settings 200Hz | Pupil Capture 1.6.13

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#1148]
Ubuntu

When starting an eye camera **Sensor Settings** of **Auto Exposure Mode** are set to **manual mode** as default.

- **auto mode** can't get selected from dropdown
- **shutter priority mode** can't get selected
- **aperture priority mode** will end up in a dark screen
- manual **Absolute Exposure Time** is 'weirdly' settable in any mode (actually just in manual mode - somteimes the maximum is just 15 - sometimes 24 - sometimes 31) the slider behaviour doesn't work correct
- **load defaults** will not load defaults from start (it loads **aperture priority mode**, which results in a black /dark screen)

Best Freddy

**Comment by papr** [comment]
The 200Hz cams only support **manual mode**. We will hide the possibility to select a non-working mode in the future.
