### ISSUE TITLE
Errors running Pupil from source in Ubuntu 16.04

### ISSUE THREAD

**Issue by iserranoe** [pupil-labs/pupil#1154]
Hello,

I installed Linux dependencies on Ubuntu 16.04 following the given instructions, but when running 'python3 main.py' I obtained the following message. I am brand new with Linux, so I will appreciate any 'for dummies' explanation. 

Thank you!
...................................................................................................................................................................
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.6.26
world - [INFO] launchables.world: System Info: User: isaatc, Platform: Linux, Machine: sagenia, Release: 4.4.0-119-generic, Version: #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018
world - [INFO] pupil_detectors.build: Building extension modules...
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from detect_2d.hpp:22:0,
                 from detector_2d.cpp:658:
singleeyefitter/ImageProcessing/cvx.h:31:130: error: ‘CV_AA’ was not declared in this scope
 cv::Point2f to, cv::Scalar color, int thickness = 1, int linetype = CV_AA, int 
                                                                     ^
singleeyefitter/ImageProcessing/cvx.h:39:136: error: ‘CV_AA’ was not declared in this scope
 radius, const cv::Scalar& colour, int thickness = 1, int lineType = CV_AA, int 
                                                                     ^
singleeyefitter/ImageProcessing/cvx.h:44:135: error: ‘CV_AA’ was not declared in this scope
 radius, const cv::Scalar& colour, int thickness = 1, int lineType = CV_AA, int 
                                                                     ^
In file included from detector_2d.cpp:658:0:
detect_2d.hpp: In member function ‘std::shared_ptr<singleeyefitter::Detector2DResult> Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)’:
detect_2d.hpp:245:36: error: ‘CV_RETR_LIST’ was not declared in this scope
  cv::findContours(edges, contours, CV_RETR_LIST, CV_CHAIN_APPROX_NONE);
                                    ^
detect_2d.hpp:245:50: error: ‘CV_CHAIN_APPROX_NONE’ was not declared in this scope
  cv::findContours(edges, contours, CV_RETR_LIST, CV_CHAIN_APPROX_NONE);
                                                  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/isaatc/work/pupil/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/home/isaatc/work/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 16, in <module>
    build_cpp_extension()
  File "/home/isaatc/work/pupil/pupil_src/shared_modules/pupil_detectors/build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'install', '--install-lib=/home/isaatc/work/pupil/pupil_src/shared_modules']' returned non-zero exit status 1

**Comment by yves84** [comment]
Same Problem here. Using Ubuntu 17.10.

May you using OpenCV 3.4. `CV_AA` is defined in OpenCV2.4 (in OpenCV3.4 it call LINE_AA). I think you must using OpenCV3 to build the python3 extension (OpenCV2 not support them?).

In OpenCV 3.4 the define of `CV_AA` aleady exists [2], but is disabled by the define `DISABLE_OPENCV_24_COMPATIBILITY` (see [1]).

i try to find a solution/workaround at the moment...

[1] https://github.com/opencv/opencv/blob/3.4/modules/imgproc/include/opencv2/imgproc.hpp#L4910
[2] https://github.com/opencv/opencv/blob/3.4/modules/imgproc/include/opencv2/imgproc/imgproc_c.h#L987

(sorry for my bad english)

**Comment by papr** [comment]
Dear @iserranoe 
@yves84 correctly mentions that you need to install opencv 3. The Pupil software is not compatible with opencv 2.

**Comment by iserranoe** [comment]
I already have Opencv 3.4.0 installed

2018-04-16 8:57 GMT+01:00 Pablo Prietz <notifications@github.com>:

**Comment by iserranoe** [comment]
@yves84

I tried your solutions and it didn't work :( Although I now have less error
lines:

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this
OS version.
service - [INFO] pupil_detectors.build: Building extension modules...
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for
C/ObjC but not for C++
In file included from detector_2d.cpp:658:0:
detect_2d.hpp: In member function
‘std::shared_ptr<singleeyefitter::Detector2DResult>
Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&,
cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)’:
detect_2d.hpp:245:36: error: ‘CV_RETR_LIST’ was not declared in this scope
  cv::findContours(edges, contours, CV_RETR_LIST, CV_CHAIN_APPROX_NONE);
                                    ^
detect_2d.hpp:245:50: error: ‘CV_CHAIN_APPROX_NONE’ was not declared in
this scope
  cv::findContours(edges, contours, CV_RETR_LIST, CV_CHAIN_APPROX_NONE);
                                                  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
service - [ERROR] launchables.service: Process Service crashed with trace:
Traceback (most recent call last):
  File "/home/isaatc/work/pupil/pupil_src/launchables/service.py", line 88,
in service
    import pupil_detectors
  File
"/home/isaatc/work/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py",
line 16, in <module>
    build_cpp_extension()
  File
"/home/isaatc/work/pupil/pupil_src/shared_modules/pupil_detectors/build.py",
line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py',
'install',
'--install-lib=/home/isaatc/work/pupil/pupil_src/shared_modules']' returned
non-zero exit status 1

2018-04-16 9:41 GMT+01:00 INÉS SERRANO ESPARZA <iserrano@ull.edu.es>:

**Comment by iserranoe** [comment]
Checking the docs, threre is this piece of information that may be useful:
"OpenCV is not able to build Python 2 and Python 3 modules at the same
time. OpenCV will build the Python 2 module by default if requirements for
both versions are met. Setting the Python 2 Numpy include directory to an
empty string effectively disables the Python 2 module build."
How can I "set the Python 2 Numpy include directory to an empty string"?
Thank you!


2018-04-16 9:46 GMT+01:00 INÉS SERRANO ESPARZA <iserrano@ull.edu.es>:

**Comment by yves84** [comment]
Hi,

it's similar to the first Problem. Edit the File `pupil/pupil_src/shared_modules/pupil_detectors/detect_2d.hpp` and insert `#define CV_CHIAN_CV_CHAIN_APPROX_NONE cv::CHAIN_APPROX_NONE`.

**Comment by iserranoe** [comment]
Dear @yves84, it seems to work now, thanks a lot!!!
I did it manually, but it worked. Just for other users, I replaced:
In detect_2d.hpp:
- CV_RETR_LIST by cv::RETR_LIST
- CV_APPROX_NONE by cv::_APPROX_NONE
In  cvx.h:
- CV_AA by cv::LINE_AA
I also had some problems with the boost library, so I re-installed them

**Comment by yves84** [comment]
@papr 
Maybe PupilLab should fix this in his Repo?!

**Comment by yves84** [comment]
Hi!

No, the pupil lab source code use defines from the opencv c-api like CV_AA and so on. since the last one or two commits from opencv's master branch, you can not mix the c- and cpp-api.

(it was possible a few mounth ago).

the detect_2d and cvx includes the opencv cpp api `opencv2/imgproc.hpp`, there are no CV_AA, ... are defined (there was moved to `opencv2/imgproc/imgproc_c.h`).

gz

(sorry for my english ;) )

**Comment by papr** [comment]
Ok, I will try to replicate this issue with a fresh copy of opencv then. :)

**Comment by papr** [comment]
I was able to reproduce this issue. Thank you very much @yves84 @iserranoe for providing a solution to this issue!

**Comment by yves84** [comment]
No Problem ;).
