### ISSUE TITLE
Plugin "display_recent_gaze.py"

### ISSUE THREAD

**Issue by iserranoe** [pupil-labs/pupil#1162]
Hello,
I'm trying to build my own plugin and, as recommended in plugin.py, I'm trying to start with 'display_recent_gaze.py', placed at 'shared_modules' folder. However, the plugin is not working, and as I don't receive any error message, I have no idea what's going on. Any idea? I already tried adding def init_ui(self) and def deinit_ui(self).
Thank you!
(Sorry if this is not the correct place to post this)
......................................................................................................................................................................
'''
(*)~---------------------------------------------------------------------------
Pupil - eye tracking platform
Copyright (C) 2012-2018 Pupil Labs

Distributed under the terms of the GNU
Lesser General Public License (LGPL v3.0).
See COPYING and COPYING.LESSER for license details.
---------------------------------------------------------------------------~(*)
'''

from plugin import System_Plugin_Base
from pyglui.cygl.utils import draw_points_norm,RGBA
from pyglui import ui

class Display_Recent_Gaze(System_Plugin_Base):
    """
    DisplayGaze shows the three most
    recent gaze position on the screen
    """
    icon_chr = '^_^'
    icon_font = 'pupil_icons' 

    def __init__(self, g_pool):
        super().__init__(g_pool)
        self.order = .8
        self.pupil_display_list = []

    def init_ui(self):
        # Create a floating menu
        self.add_menu()
        self.menu.label = 'Display_Recent_Gaze'
        # Create a simple info text
        help_str = "Display recent gaze"
        self.menu.append(ui.Info_Text(help_str))

    def recent_events(self,events):
        for pt in events.get('gaze_positions',[]):
            self.pupil_display_list.append((pt['norm_pos'] , pt['confidence']*0.8))
        self.pupil_display_list[:-3] = []

    def gl_display(self):
        for pt,a in self.pupil_display_list:
            #This could be faster if there would be a method to also add multiple colors per point
            draw_points_norm([pt],
                        size=35,
                        color=RGBA(1.,.2,.4,a))
    def deinit_ui(self):
        self.remove_menu()

    def get_init_dict(self):
        return {}

**Comment by cpicanco** [comment]
Hi, @iserranoe ,

It seems you are running Pupil from source and trying to write a new system plugin. If yes, you must add your plugin in the list of plugins of your target launchable app:

https://github.com/pupil-labs/pupil/blob/6b9279c8769f58c3a6ea4fe73df0728a56bd8b9e/pupil_src/launchables/world.py#L193

If you are trying to hack an existing plugin such as `Display_Recent_Gaze`, you should be able to promptly see your modifications, no need to do anything else, just edit and run.

Please, let me ask you... Are you sure you need a system plugin?

**Comment by iserranoe** [comment]
Hello,
Thank you for your advice. I finally solved the problem, it has to do with indexation. Sorry I did not mention before. 
I am not sure if I need plugin or not, so far I don't think so because it is enough with zmq, but maybe in the future I do. In any case, I managed to do the same with both plugin and zmq.
Many thanks!

**Comment by iserranoe** [comment]
Just a quick question: I believe I can't call recent_events in Pupil_Service, can I? Is it there anything similar than recent_events to obtain pupil positions in Pupil_Service?
Thank you!!

**Comment by iserranoe** [comment]
I am sorry, but what is the difference? I though I had to write:

def recent_events(self, events):
            (whatever) 

I doesn't seem to work for Service...

**Comment by papr** [comment]
How do you start the plugin in Service?

**Comment by iserranoe** [comment]
It is started automatically once I push Eye 0 or Eye 1 buttons
