### ISSUE TITLE
Remote Recorder: "Exceed max file size limitation, Capturing will be stopped."

### ISSUE THREAD

**Issue by emolyzr** [pupil-labs/pupil#1167]
Symptom:
Started a remote recording via laptop on a moto z2 play coupled with SD card. After a couple of minutes of recording, the recording stops and gives the following error message on the smartphone:
"Exceed max file size limitation, Capturing will be stopped."

I was not warned by pupil capture from the laptop that this happened, at least it didn't caught my attention.

Maybe then, it's just a technical limitation. 

But: 
- What is the maximum file size?
- Can the maximum file size be increased?
- Is it really the limit?

Workaround: May it be possible to do both at the same time, i.e., saving local on smartphone SD or disk AND (given that preview on laptop via WIFI is activated) saving local on laptop hard disk? So then I'd at least had a backup.

What do you think?

Best!

**Comment by emolyzr** [comment]
EDIT: Never mind. As long as it is almost deterministic that loss of WIFI connection stops recording (while simultaneous publishing), writing to the phone is no viable option at all. sad.

**Comment by mkassner** [comment]
Hi, this error message is unfortunately not correct. The issue is the wifi disconnecting to causing a crash in the Pupil Mobile app. We are working on fixing this issue! In the meantime I highly recommend using a dedeicated 2.4GHZ wifi access point during the experiments!

**Comment by emolyzr** [comment]
As @papr mentioned in another thread (https://github.com/pupil-labs/pupil/issues/1166) a dedicated wifi access point might also be no safe way to record data? Is direct recording on the phone a safe option?

**Comment by papr** [comment]
There is a misunderstanding. Saving to the phone is reliable as long as the wifi does not disconnect. The dedicated wifi access point minimizes the risk of a disconnect.

**Comment by emolyzr** [comment]
Okay, so *direct recording without streaming* is a safe option. And it's currently the only safe option in my point of view, because as you said: It is safe, "as long as the wifi does not interrupt". Unfortunately, under bad circumstances, this happens already if you leave the room and walk a few feet... even with a dedicated wifi access point.

That's why we switched to recording via wifi: If we loose the connection, the recording continues as soon as the connection is re-established. 
With direct recording to the phone: If we loose the connection, the recording stops and all upcoming data is lost. Given that the operator notices at all that wifi connection is lost, he would have to intervene with the data collection session and restart the recording... that's difficult, at least in our setup... We therefore decided for momentary data loss (wifi recording) rather than complete data loss (phone recording while streaming), if wifi connection is momentarily interrupted.

**Comment by emolyzr** [comment]
UPDATE: This bug leads to two symptoms:
1. Recording Button freezes and data cannot be saved. App needs to be closed. Data is lost.
2. App simply aborts recording. Data is lost.

In any case cams continue to be streamed / publish to the laptop.

**Comment by emolyzr** [comment]
@mkassner I don't think your comment is correct here. I strongly believe that indeed max file size is exceeded as all of our recordings  stop when the world cam reaches exactly the 4GB limit. Please note that this is an issue with the Pupil Mobile App not with Pupil Capture - so we might are in the wrong "forum" or "branch" or how does on call this on github? Also note that compared to my initial notification of this issue, this happens with local recordings on the smartphone independent of the remote recorder, also we don't use SD cards but the internal android save disk.

**Comment by emolyzr** [comment]
EDIT: A friend just told me that this is to be expected as SD cards in general, and presumably also the android storage is FAT32 formatted. This means 4GB is the maximum file size. One could try to format the SD card with NTFS and see if the android system is still able to write on the SD card. Another workaround would be to decrease frame rate or resolution of the world cam video.

**Comment by emolyzr** [comment]
That's what I'd suggest too.

**Comment by emolyzr** [comment]
Why ist the world cam sometimes saved as *.mp4 and sometimes saved as *.mjpeg? Looks like the *.mp4 needs less disk space. In ontrast, the eyes are always saved as *.mjpeg. Has it to do with the version number of the pupil mobile app? If we could always save as *.mp4, I guess we could make recordings about an hour without exceeding file size. That would suffice at first.

**Comment by papr** [comment]
The default option is to transcode the world video using the phone's h264 encoder. You can enable and disable it in the settings. You need to turn off streaming in the settings before you can change this.

**Comment by mkassner** [comment]
@emolyzr  we default the eyes to mjpeg and the world to h264/mp4 this should give the best tradeof for size and device load .

**Comment by emolyzr** [comment]
The settings of two of four measurement devices were set to h264 "off" for the world cam. Don't know why the defaults were changed; but that was surly the cause, why we were faced with those error messages. We now set it back to default and I think it should work. Issue solved for now. Thanks for your help!

**Comment by emolyzr** [comment]
I wanted to ask if in the meantime you could fix the issue I started in 2018?
- Pupil App records on local storage.
- Recording is streamed via dedicated WIFI access point to Pupil Capture.
- If WIFI disconnects - say for a couple of seconds or even longer - the local recording on the smartphone becomes an invalid recording.

Put in other words: "Is it safe to record data on the local smartphone storage while streaming via WIFI to Pupil Capture, given that the WIFI disconnects?"

Appreciate your comments.


> Okay, so _direct recording without streaming_ is a safe option. And it's currently the only safe option in my point of view, because as you said: It is safe, "as long as the wifi does not interrupt". Unfortunately, under bad circumstances, this happens already if you leave the room and walk a few feet... even with a dedicated wifi access point.
