### ISSUE TITLE
Pupil Player crashes while "updating recording format"

### ISSUE THREAD

**Issue by PeterPaniPan** [pupil-labs/pupil#1169]
![pupil_player_crash](https://user-images.githubusercontent.com/38856857/39425807-63f6d79c-4c7d-11e8-8e31-63d530d2916a.png)

When dropping a recording directory recorded with pupil mobile onto the pupil player window, it's crashing while "updating the recording format". 

![directory](https://user-images.githubusercontent.com/38856857/39425921-ed44b884-4c7d-11e8-8a45-d1838b22a588.png)

That's the directory. 

Thanks in advance!

**Comment by papr** [comment]
Hey, your path contains utf8 characters ( the ö in your username). Please move the recording to a path that does not contain utf8 characters.

**Comment by PeterPaniPan** [comment]
okay, got it. Thank you!
