### ISSUE TITLE
Pupil Player - rename `rec_dir` to `data_dir`

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#117]
Rename `rec_dir` to `data_dir` -- or pick one and be consistent across plugins. For example `exporter` uses the term `data_dir`. 

In my opinion, it would make more sense to call this variable `data_dir` as it contains more than just recordings.

**Comment by mkassner** [comment]
I think the contrary: it should be rec_dir everywhere. It only contains a recording. 

Most important: consistency. So I went with rec_dir. I only had to change it in the exporter. If you have great pains with it we can change. But I find data dir to be to general.
