### ISSUE TITLE
python3 main.py error

### ISSUE THREAD

**Issue by youngsinpark** [pupil-labs/pupil#1171]
Hello,

I installed Linux dependencies on Ubuntu 16.04 following the given instructions, but when running 'python3 main.py' I obtained the following message. 
How should I solve it?

Thank you!

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.7.42
world - [INFO] launchables.world: System Info: User: song, Platform: Linux, Machine: song-VirtualBox, Release: 4.13.0-39-generic, Version: #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018
world - [INFO] pupil_detectors.build: Building extension modules...
world - [INFO] calibration_routines.optimization_calibration.build: Building extension modules...
world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.

**Comment by mkassner** [comment]
stale.
