### ISSUE TITLE
Pupil Player frame rate

### ISSUE THREAD

**Issue by PCABG** [pupil-labs/pupil#1174]
Hi, I have recorded a pupil labs session at 60 Hz and now I want to replay it in the Pupil Player.
Exporting the data into csv file works fine, I get the full 60Hz temporal resolution, so the data is there. Yet, trying to publish the data via a plugin via zeroMQ, the achieved frame rate drops to ca. 28 fps. The GUI in the Pupil Player also shows 25-35 Fps
Is there a way to obtain the full temporal resolution? I wouldnt mind a bit lag in the playback
thx

**Comment by mkassner** [comment]
Hi,
would you mind sharing what OS you are on?

Have you tried slowing down the playback? (Press play and then left arrow to slow down)

Best,
Moritz

**Comment by mkassner** [comment]
@papr  lets look at solutions for this.

**Comment by PCABG** [comment]
Hi sry for the late reply,
I'm working on a Linux system with the latest checkout I did last Wednesday 9th, May
Thanks for mentioning the option of slowing down the playback, this helped a lot, I succeed in getting all the frames at half the playback speed
Yet, I would expect that the pupil player is able to supply the raw eyetracking data (I limited the video output to 1 fps) in full speed. I think the problem might be the huge world video (my recordings are 45 min ~ 25GB)?

**Comment by PCABG** [comment]
btw would it be possible to start the player completely without the world video playback? i dont need it for my analysis

**Comment by mkassner** [comment]
@papr  @pointcontrols  My guess here is that v-sync is capping the loop at 60fps and our wait logic + cpu load trigger that the 60fps recording skips frame during playback. @pointcontrols I think we should try to skip gl updates and drawing if the loop is too fast. We do the same in eye.py .

Here: https://github.com/pupil-labs/pupil/blob/master/pupil_src/launchables/eye.py#L450-L455 and here https://github.com/pupil-labs/pupil/blob/master/pupil_src/launchables/eye.py#L579

**Comment by mkassner** [comment]
@pointcontrols  what do you think about this?

**Comment by joergsimon** [comment]
so, I also, after calibration would not need any output during recording. Did you find out how to do that?

**Comment by papr** [comment]
If a custom plugin is used, and the frame rate drops to less than 28Hz, then it is likely that the plugin is calling a blocking function that takes too much time. Plugins can store and publish data via built-in mechanism [like this](https://gist.github.com/papr/079a520a1f2a31b1b73963feb7037995). I highly recommend using this mechanism instead of implementing it youself to avoid potentially blocking functions.
