### ISSUE TITLE
Blink Detector filtersize should be even

### ISSUE THREAD

**Issue by k47ha** [pupil-labs/pupil#1175]
In blink_detection.py in L236 we would replace

```        filter_size = round(len(all_pp) * self.history_length / total_time)```

with
```        filter_size = 2*round(len(all_pp) * self.history_length / total_time/2.)```

Else (in the case of odd filter size) the stepfunction filter can have non-zero sum and the resulting blink-confidence-filtered signal has a small dc-shift.

Maybe we missed something.

Best,
 Katha & Bene

**Comment by papr** [comment]
You are right. I will apply your proposed change.
