### ISSUE TITLE
Windows Bundle: crash on open debug window

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#118]
reported by user.

**Comment by mkassner** [comment]
I cannot reproduce this with the bundle. But I have not tested with an eye camera connected.

**Comment by MichaelBarz** [comment]
Reproduced this error:

* Set eye mode to "ROI" or "Camera Image"
* Open debug window

Also happens if these steps are switched!

Might be due to incompatible array formats (eye mode switches from "img" to "grey" frames)?

**Comment by mkassner** [comment]
I fixed the crash earlier today. Please pull.

The overlay not showing has todo with your recent changes to the video backend Consider converting once and then cache the result.
