### ISSUE TITLE
Local Recording: Oops! This was not a valid recording.

### ISSUE THREAD

**Issue by emolyzr** [pupil-labs/pupil#1183]
Hi,

Pupil Player says "Oops", when I drop this recording. I used the local recording function (circle button im pupil mobile app). Local recording on android storage. Why is that not a valid recording? How to produce a valid recording?

https://drive.google.com/open?id=1VYZ-h77hY-P483F_8jhrrC6B3LSNp67q

Best,
Johannes

**Comment by papr** [comment]
In this case the issue is that there is no `info.csv`. Was the recording manually stopped or did the app abort the recording?

**Comment by emolyzr** [comment]
It aborted due to wifi loss. Normal stopping produces healthy recordings. It seems like only the info.csv is missing... a pity. Is the info.csv really necessary for data analysis?

**Comment by papr** [comment]
Even if you insert an info.csv file from a different/fresh recording it will not work because the video files were not closed properly.
```
  File "av/utils.pyx", line 103, in av.utils.err_check (src/av/utils.c:2499)
av.AVError: [Errno 1094995529] Invalid data found when processing input: '../recordings/emolyzr/invalid-rec/Pupil Cam1 ID2.mp4' (libav.mov,mp4,m4a,3gp,3g2,mj2: moov atom not found)
```
The info.csv file is mostly for versioning reasons. We need it to be able upgrade recordings from older Capture versions or mobile recordings to the newest version.

**Comment by emolyzr** [comment]
Cut a long story short: 
During Local Recording while Streaming: As soon as wifi connection is lost, local recording stops, and data is completley irrepairable, because the files were not properly closed. Correct?

I thought about a backup-solution, that is:
Start local recording while streaming and *in addition* start recording in pupil capture. This way I get a recording on smartphone and on the laptop. In case of wifi loss and wifi reconnection, I still have the streming recording, despite the local recording being useless.
However, it seems that the streaming recording is also (at least partly) useless then, e.g. complete eye1 data was not saved.
Is there in your mind a 100% save option to prevent wifi loss?
I have my laptop connected via LAN cable to a dedicated 2,4 GHz router and Motorola Z2 Play is connected via LAN to the same router.

**Comment by papr** [comment]
> During Local Recording while Streaming: As soon as wifi connection is lost, local recording stops, and data is completley irrepairable, because the files were not properly closed. Correct?

Correct. We are working on finding a solution for this issue.

>However, it seems that the streaming recording is also (at least partly) useless then, e.g. complete eye1 data was not saved.

Capture recordings are independent of any wifi issues.

>  Is there in your mind a 100% save option to prevent wifi loss?

Not that I know of.

**Comment by emolyzr** [comment]
Okay, thanks. I'll retry the double backup solution.

Although I do not believe that capture recordings are independent of wifi issues. In the case that the cameras are streamed from the pupil mobile app to pupil capture and wifi connection is lost ("ghost mode"?) there seems to be an error (I already shared data with you).
 
![player log last third including data loss section and afew seconds thereafter](https://user-images.githubusercontent.com/35568338/40179275-392250d6-59e4-11e8-9f2a-59b7f2e869d4.png)
