### ISSUE TITLE
[QUESTION] Could you please tell me what is the first 10 lines from timestamps.npy?

### ISSUE THREAD

**Issue by Hogeang** [pupil-labs/pupil#1184]
I decode timestamps.npy, and it always pops up weird values at first 10 lines.

> 1.87585068940037e-309
1.1711999948023422e+171
5.227416798550298e-37
8.447400968892931e+252
2.651412321034566e+180
9.921526050621047e+247
2.1620996769994603e+233
9.739181090135549e-72
6.013999212447132e-154
6.554909140857642e-260
16074.440306
16074.465506
16074.473906
16074.541106
16074.591506
16074.608306
16074.616706
16074.641906
16074.725906
16074.776306
16074.793106
16074.801506

> 
![image](https://user-images.githubusercontent.com/15939666/40167535-4170f144-59fc-11e8-9344-f3af497dc148.png)

Is this something about data format or junk values?
Thank you.

**Comment by papr** [comment]
Hey @Hogeang 
This is just a different string representation for floats. E.g. `1.3e2 == 1.3 * 10^2 == 130.0`. But these timestamps should be increasing monotonically. Do you see this happening for other recordings as well?

**Comment by mkassner** [comment]
@Hogeang  are you using numpy to load this file? If you are just parsing it raw this may be header info. Please use numpy to read this file.

**Comment by papr** [comment]
For reference: https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html

**Comment by Hogeang** [comment]
Thank you for your help.
This is my code how to decode timestamps.npy to text file.
```
import numpy

worldfilename = "world_timestamps"
timestamps = numpy.fromfile(worldfilename+".npy", dtype="<f8")
timestamps.tofile(worldfilename+".txt", "\n", "%s")
```
Than, It always pops like this format.

> 
![image](https://user-images.githubusercontent.com/15939666/40194139-5ad0d51c-5a44-11e8-8208-ee8c6faac2ad.png)


As you said @papr, using numpy.load is proper way to decode it in this case.
I think this issue is  kind of differences between methods of numpy.
```
timestamps =numpy.load(worldfilename+".npy")
timestamps.tofile(worldfilename+"2.txt", "\n", "%s")
```

> 
![image](https://user-images.githubusercontent.com/15939666/40194169-6a253116-5a44-11e8-8e57-851e3476e4d3.png)
