### ISSUE TITLE
Windows video backend: Implement camera settings

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#119]
The windows backend is still lacking a GUI for uvc controls.

**Comment by MichaelBarz** [comment]
I added the most important ones: resolution and framerate
More to come...

**Comment by mkassner** [comment]
Hi,

please comment out sizes. While this is super nice to have I fear that a
run-time change of the coordinate systems and image size can lead to a host
of bugs and errors.

If we later feel like we want this we can put it back...

**Comment by mkassner** [comment]
will not be implemented. Instead we will use a new unified backend.
