### ISSUE TITLE
Artefacts in the pupil recordings

### ISSUE THREAD

**Issue by PatrycjaPAKS** [pupil-labs/pupil#1199]
Hi, 

In our recent study, we've used Pupil Labs to record the pupil dilation. Recordings contain some artefacts, which we didn't see while using other cameras in past and we believe they may be related to the Pupil Labs.  Namely, we've got recordings with:
-	Unnaturally high estimation of the pupil size,
-	Rapid changes in the pupil size’s estimation,
-	Oscillations present in the recorded pupil traces.

![oscillationsnotremoved3avginfluencemarked](https://user-images.githubusercontent.com/30791911/40548752-e54527ba-6035-11e8-82ad-c1bc1891b77e.png)
![oscillationsnotremoved4avginfluencemarked](https://user-images.githubusercontent.com/30791911/40548753-e56632de-6035-11e8-9f7d-60391d1767f3.png)

In the attachment few examples to show, which artefacts I have in mind. Do you have an idea on what could be causing some of them? And how we could potentially correct them? 
Unfortunately, our signal processing methods (working fine for the other cameras we've used so far) did not remove all the noise.

Looking forward to hearing from you.
Best wishes,
Patrycja

**Comment by cpicanco** [comment]
@PatrycjaPAKS , please, could you mention what is the model of your "Pupil Labs cameras"? Also, may I ask if you have been using Pupil Capture to record pupil data along with other cameras (the ones you said that did not produce artifacts)?

**Comment by cpicanco** [comment]
@PatrycjaPAKS , may I ask you which detection mode you were using? 3d or 2d?

Ps.: There was a discussion, a long time ago, about unexpected pupil diameters in the Pupil google group. Someone was studying "stress" and found out really big diameters correlated to some scenarios. It might not be the case (I am suspecting that your found is related to 3d detection instability).

https://groups.google.com/forum/#!searchin/pupil-discuss/pupil$20diameter$20stress%7Csort:date/pupil-discuss/CDAQf74MBy8/Cn8OyAw8tjMJ

**Comment by behinger** [comment]
One way we debugged pupil diameter issues was to check the eye-cam videos whats going on there with the algorithm/pupil. Blinks could be the case, also low confidence.

**Comment by PatrycjaPAKS** [comment]
@cpicanco, we used 2d estimation due to the 3d detection instability. It was especially difficult with the older participants. 
@behinger While analysing the data, we've taken into account samples with confidence >0.6 as suggested in your documentation. Out theory was also that the camera couldn't focus either after blink or low contrast between the iris and the pupil colour. We've noticed as well that picture from one of the eye cameras got very dark few times. 

To both, do you have any suggestions on how to prevent those artefacts from happening in the future? 

Best,
Patrycja

**Comment by behinger** [comment]
Hey! Not from pupillabs (cpianco neither ;)). I had issues that could go into this direction in the past with the automatic shutter settings. Without seeing the videos accompanying the artefact, its hard. Maybe someone else?

**Comment by PatrycjaPAKS** [comment]
Thanks for your interest anyway :) 

Could anyone from Pupil Labs clarify those artefacts then, please? It's an important observation for us as we're planning to continue using Pupil Labs in our future studies :)

**Comment by papr** [comment]
@PatrycjaPAKS Please be aware that the 2d pupil diameter is measured in pixels and is therefore dependent on the distance between eye and eye camera. Please make also sure to exclude low-confidence pupil-positions.

**Comment by papr** [comment]
@PatrycjaPAKS Could you shortly clarify what the meaning of the two colors?

**Comment by PatrycjaPAKS** [comment]
@papr red and blue colors mark a red and a left eye recorded simultanously during one trial.

**Comment by papr** [comment]
Would it be possible for you to share such a recording with us? Ideally it would include eye video recordings as well. Please share the recording with data@pupil-labs.com

**Comment by papr** [comment]
Related issue #1273 

This issue can be avoided by freezing the 3d eye model, see release v1.15 https://github.com/pupil-labs/pupil/releases/tag/v1.15
