### ISSUE TITLE
Windows Bundle: interface Scaling results in Text not fully showing

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#120]
Reported by user. Need confirmation and fix.

**Comment by mkassner** [comment]
I cannot reproduce this with my windows bundle.

**Comment by MichaelBarz** [comment]
Cannot reproduce this issue. Is there any information about the system used? Especially the display resolution would be interesting...

**Comment by mkassner** [comment]
Please reopen with this issue comes up again.
