### ISSUE TITLE
eye camera fog in two headsets

### ISSUE THREAD

**Issue by emolyzr** [pupil-labs/pupil#1200]
We have some kind of greyish fog on one eye cam, but not on the other (see picture). What can this be related to? Eyes are recorded using pupil mobile. In the preview the fog is already visible. So it's not a wifi issue. Can this be some kind of hardware issue? However, changing USB cable or orientation of USB cable does not help. Changing the brigthness only changes the brightness of the fog, but doesn't remove the fog. It was just in one recording, but disappeared then for the following ones. However, it replicated now with another headset. Quite strange, init?

![unbenannt](https://user-images.githubusercontent.com/35568338/40558671-59c7f3ba-6054-11e8-8cea-319cde856e90.jpg)

Probably related to this issue?
https://github.com/pupil-labs/pupil/issues/1179

**Comment by mkassner** [comment]
@emolyzr  sounds like the contrast was set to a different value. Can you read this field and let us know?

**Comment by Hogeang** [comment]
Try to apply default. If you fail, then it might be hardware issue. So then you might exchange it.

**Comment by li-zemin** [comment]
@emolyzr Hello, I have the same same problem. and my left eye camera works well whereas the right eye camera has some fog like yours. And I received the headset not long ago, I guess this might be hardware issue, can you locate this question?
My sceenshoot is in the issue #1179

**Comment by mkassner** [comment]
@li-zemin  my guess is that the cameras brightness setting is not correct. Can you check in the camera settings?

**Comment by li-zemin** [comment]
@mkassner  I adjust the cameras brightness, but the image is still blurry. How about you? Did you gain a fine image via adjusting the brightness?

**Comment by li-zemin** [comment]
@mkassner here is my screenshoot, similar to the result above.
![image](https://user-images.githubusercontent.com/25366741/41901326-2ec755ca-7963-11e8-8222-7c7e7895e247.png)

**Comment by mkassner** [comment]
This looks like a defocused camera. If this is a 200hz eye camera its a defect and we will replace it. Please get in touch with us via email in this case.
