### ISSUE TITLE
Delete last known Calibration Marker Location after Calibration/Testing

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#1205]
Whenever you do a calibration (or validation/testing) and the marker is at the same spot as in the last calibration, pupil capture does not recognize the marker because it did not move since the last time.

This problem appears if you always want to start the calibration/testing in the center of the screen, but also finish there (as in the default eyelink calibration). Then the first validation target is not found - because pupil capture thinks it has this one already.

Simple solution: Delete the marker location (the yellow dot) after each calibration.

**Comment by papr** [comment]
Just for clarification, you are referring to the Manual Marker Calibration, correct?
