### ISSUE TITLE
Precision Estimate "NAN" 

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#1209]
Sometimes the calibration/accuracy-test precision estimate returns nan. I tracked this problem down to
https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/accuracy_visualizer.py#L208

I'm getting sometimes values as input to np.arccos that are slightly above 1 (i.e. 1.000002). I guess this is due to floating errors.

Proposed fix: Either put a nan-remove in the np mean, or fix the too-large values before putting them into np.arccos

**Comment by papr** [comment]
Thank you very much for tracking this issue down! Turns out that I also forgot to convert the precision value from radians to degrees :man_facepalming:

**Comment by behinger** [comment]
that explains the very low values ;-)
