### ISSUE TITLE
Make rec_path persistent

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#121]
Make the recording path variable persistent? I'm not sure if we really want this. But if users really need to have the recordings somewhere else, we should think about this.

**Comment by MichaelBarz** [comment]
My opinion is to keep the path variable. Think about new laptops that come with an SSD + HDD. Videodata would be stored on the small SSD, instead of the HDD, which would probably be the better choice.

**Comment by mkassner** [comment]
I made it user settable and remembered through sessions.
