### ISSUE TITLE
eye cameras access problem in pupil-capture

### ISSUE THREAD

**Issue by li-zemin** [pupil-labs/pupil#1212]
Hello,
I used pupil on the platform of window7 x64.
My pupil-capture is v1.7
I followed [windows driver install troubleshooting](https://docs.pupil-labs.com/#troubleshooting) to install the newest driver.
I run the pupil-capture.exe with administor authority. And I plugined in pupil. However. in the Backend Manager, the only one Activate Source that was world camera showed and worked.
![default](https://user-images.githubusercontent.com/25366741/41455601-43b245f0-70b0-11e8-90e1-19ace33637c4.PNG)
So I check the Windows Device Manage, fould that in the directory of libusbK Usb Devices, there was only one camera. And the other two cameras(eye cameras) was in the list of "image devices".
![2](https://user-images.githubusercontent.com/25366741/41455692-94e38114-70b0-11e8-997b-9b2f2370db82.PNG)
I concluded that the eye camera driver was not installed correctly, so that I couldn't get eye camera input in the pupil-capture.
Besides, I tried to uninstall the driver in the Devices Manager,  restart computer, reinstall driver.... I did it many times but without effect.
I want to know how could I access eye camera input correctly in pupil-capture. Thanks!

**Comment by papr** [comment]
Please be aware that we do not support Windows 7! Please upgrade to Windows 10 or use macOS or Linux.

**Comment by li-zemin** [comment]
@papr 
Thank you for your reply. 
I found that some of developers use it on win7 in issues. As stated in [Developer Docs](https://docs.pupil-labs.com/#windows-dependencies), the limitation of develop platform has an effect on developers rather than simple users. And my current process is not referred to some develop job, just use it simply to have access to three cameras in pupil-capture.
So could I upgrade to Win10 or use macOS or linux necessarily?
