### ISSUE TITLE
Is there an automatic removing of blink artifacts?

### ISSUE THREAD

**Issue by CobeA527** [pupil-labs/pupil#1213]
When the eyelid closes, it often leads to invalid Values in pupil diameter. Does the software automatically removes those artifacts and interpolates the values ? 

![pupildiameterblink](https://user-images.githubusercontent.com/40291778/41525938-e73f7ec0-72e2-11e8-8fa2-8aaef4d36257.png)

The picture shows a blink including artifacts(yellow area). Pupil diameter was recorded by another eye tracker.

 If you take a look into the Pupildiamter recorded by PupilLabs, you don't see invalid values around a blink.

![pupildiameter](https://user-images.githubusercontent.com/40291778/41526273-fbb056e4-72e3-11e8-9c5a-8a077dbe6f8f.png)

The picture shows missing values caused by a blink.

**Comment by mkassner** [comment]
We don't interpolate values inside the blink. Instead we blank them out. Does this work for you? If you need interpolation I would do that as post-processing.

**Comment by papr** [comment]
This issue seems to be resolved.
