### ISSUE TITLE
3D Calibration problem with Hololens

### ISSUE THREAD

**Issue by minoTrey** [pupil-labs/pupil#1216]
Hello I'm Trey.

I bought a pupil, which is called Hololens Binocular Add-on.
I tried to integrate Hololens and pupil and it worked well.
Thank you for sharing your software and service.

However, I found a problem with unity_pupil_plugin_hololens.
Although I set all the cameras and calibrations well, the gaze did not follow my eyes during looking at a certain point.
It has always the same problem with three type of demos (Calibration.unity, 2D Calibration Demo, 3D Calibration Demo)

I'd like to know what the problem is, what should I fix and how can I improve accuracy.
Also I wonder if I want to use other 3D models instead of the Sharkman, where do I have to look into?

Here is the videos that I've captured.

Eye tracking 3D Calibration Demo
https://youtu.be/diWgPGltExw

Eye Tracking 3D Calibration Demo 2
https://youtu.be/WKYvOJfSU-o

Eye Tracking 2D Calibration Demo
https://youtu.be/YQs1MQg6oD0

Eye Tracking Calibration Demo
https://youtu.be/-8pfqynAnUI

I appreciate your support.
Best regards.

**Comment by papr** [comment]
Please move this issue to the hmd-eyes repository if it is still unresolved.
