### ISSUE TITLE
how to make sure the eye camera is assembled with 120hz lens or 200hz lens

### ISSUE THREAD

**Issue by li-zemin** [pupil-labs/pupil#1220]
Hello, is these a method to make sure the eye camera on my pupil headsets is assembled with 120hz lens or 200hz lens?

**Comment by papr** [comment]
Yes, in the eye window, open the UVC Manager menu on the right. In the "Select to activate" drop down there should be one camera named "Pupil **Cam2** ID0". This indicates a 200hz eye camera. 120hz cameras are listed as **cam1**
