### ISSUE TITLE
Blurry image of eye camera 

### ISSUE THREAD

**Issue by li-zemin** [pupil-labs/pupil#1222]
Hello, I tested my pupil headset, and I found that the image of my left eye camera is clearer than the image of the right eye camera. And the right eye camera image is so blurry that the pupil detection confidence is  lower compared with the other eye camera.
Is there any method to improve the quality of image  captured by left eye camera?  adjusting hardware may help to make the image clear?
![screenshot from 2018-07-03 02-35-07](https://user-images.githubusercontent.com/25366741/42144278-cc267430-7dec-11e8-9304-6dc45b92d636.png)
![screenshot from 2018-07-03 02-35-16](https://user-images.githubusercontent.com/25366741/42144280-ce6af2de-7dec-11e8-91dd-34bfed786169.png)
![screenshot from 2018-07-03 02-35-35](https://user-images.githubusercontent.com/25366741/42144283-d1abcb76-7dec-11e8-8b78-a411ec50cc73.png)
![screenshot from 2018-07-03 02-35-24](https://user-images.githubusercontent.com/25366741/42144288-d7cc502a-7dec-11e8-80ed-704e015a6b45.png)

**Comment by mkassner** [comment]
Hi, please rotate the eye camera lense to focus the camera. Note that only a quote or half rotation should be required.
