### ISSUE TITLE
Test.Build.3D.VR Crashes After Calibration

### ISSUE THREAD

**Issue by BerndtSam** [pupil-labs/pupil#1225]
Hello,

I attended your demo at ETRA 2018 where I was able to load the demo found here: `https://github.com/pupil-labs/hmd-eyes/releases/tag/v0.5.1`

However, after the calibration procedure, when the demo itself loaded, the eye tracking was very sub-par. I'm now attempting to do an evaluation of the pupil-labs HTC Vive add-on data quality before I begin my upcoming research. 

Now, when I attempt to load the demo in order to ensure everything is working properly, after the calibration procedure the demo stops responding. By this, I mean the unity program called "release" will execute through the calibration procedure and then stop. I am still able to hit c and restart the calibration procedure, however, the eye videos at the bottom of the screen have disappeared, the pupil_service application has crashed, and I am not able to go onto the next portion of the demo.

I am using a Windows 10 machine with NVIDIA GeForce GTX 1060 & 16GB RAM

The following is my step-by-step use case:
- Install Pupil-Labs add-on into HTC Vive
- Setup HTC Vive
- Launch Steam
- Launch SteamVR
- Ensure HTC Vive devices all detected
- Launch pupil_service.exe *
- Set detection & mapping mode to 3D
- Select "Detect eye 0" & 1
    - Both "Pupil Capture" windows open. Both eyes modeled with green circle, red dot at center of pupil, red outline of pupil
    - If I minimize Pupil-service, it says "not responding" and does not recover
        - Goes back to * and repeat steps
- Open Test.Build.3D.VR folder which contains "Release" Unity Application
- Use default settings in Unity Application Configuration, click Play!
- Tries to connect to Pupil service
    - Success!
- Sees both eyes very clearly at bottom of screen in HTC Vive display
    - No red or circle highlights -- Issue?
- Hits C to begin calibrating
- Eyes disappear at bottom of screen
- Goes through calibration procedure
    - Dots stay relatively pink but flash frequently
- Completes calibration procedure
- Program seems to be running, but nothing happens. Able to press C to begin calibration but after doing such gets stuck in the same situation. Link provided above says the demo should begin after successful calibration. 
- Check pupil_service.exe. Unresponsive. pupil_capture windows no longer exist -- suspected crash.

I've tried this multiple times using both and either pupil_service and/or pupil_capture, loading them before or after the unity application, etc. etc. etc. all with similar results. I'm really hoping to get this resolved in the near future.

Do you have any idea what the issue is?
Do you require any additional information?

**Comment by ymujammil** [comment]
I've had similar issues like this when I am trying to load MarketScene demo after calibration. For me, Calibration works fine; it even loads the MarketScene. But, When I try to restart the demo by pressing the 'stop' button in unity, unity freezes with no response from pupil service.exe . And then I have to force close both the applications by using task manager. 
Any help would be greatly appreciated.

**Comment by ymujammil** [comment]
Found a way around this issue. If I start pupil capture before starting the calibration application, Unity won't crash. So, the key here is you should always start eye tracking processes before starting Unity/VR application

**Comment by papr** [comment]
Closing since this uses a deprecated hmd-eyes version. Please checkout hmd-eyes 1.x releases and report any issues in the hmd-eyes repository.
