### ISSUE TITLE
dont write debug log into logfile

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#1228]
This creates excessive files. Please write only warning and upward to file.

**Comment by ewolf29** [comment]
```
2018-07-17 20:56:29,608 - eye1 - [ERROR] video_capture.ndsi_backend: Traceback (most recent call last):
File "shared_modules/video_capture/ndsi_backend.py", line 122, in recent_events
File "ndsi/sensor.pyx", line 167, in ndsi.sensor.Sensor.get_newest_data_frame (ndsi/sensor.cpp:7692)
ndsi.sensor.NotDataSubSupportedError: 'This sensor does not support data subscription.'
```

**Comment by papr** [comment]
Can you name an example file size that you would call excessive? Adding debug logs to the log file was an explicit decision in order to easier debug user issues.

**Comment by ewolf29** [comment]
It increased to 500MB within around 8 minutes

**Comment by papr** [comment]
@ewolf29 Please open a separate issue for this. Please note which operating system you are using and if you are running from bundle.

**Comment by papr** [comment]
@ewolf29 could you upload the the log file to https://gist. github.com ? My suggestion would be to selectively disable logs that are excessive. My guess is that the pyre debug logs are excessive.

**Comment by ewolf29** [comment]
500MB seems too big for this. However, I could remove all duplicated messages or just leave ten of it?

**Comment by papr** [comment]
@ewolf29 Please upload the complete file to Google Drive or something comparable if possible. Else remove most of them but make clear which ones are duplicated.

**Comment by ewolf29** [comment]
This logfile is also related to 'Eyecam freezes during recording with pupil capture from pupil mobile via network #1229' - please give me a brief note when you have downloaded the file that I can remove it from the cloud drive. You can then post the essentials.

Link: https://oc.informatik.uni-wuerzburg.de/index.php/s/2WNFc7mQaPb3bYi
Password: pupillabs

**Comment by mkassner** [comment]
@papr  @ewolf29  this log is basically this line 64000 times

```
2018-07-17 21:04:45,282 - eye1 - [ERROR] video_capture.ndsi_backend: Traceback (most recent call last):
  File "shared_modules/video_capture/ndsi_backend.py", line 122, in recent_events
  File "ndsi/sensor.pyx", line 167, in ndsi.sensor.Sensor.get_newest_data_frame (ndsi/sensor.cpp:7692)
ndsi.sensor.NotDataSubSupportedError: 'This sensor does not support data subscription.'
```

**Comment by mkassner** [comment]
reducing the log level will not help. So it looks to me there is no need to reduce the log level. I ll close this now.

**Comment by papr** [comment]
@ewolf29 thank you! You can remove the file.
