### ISSUE TITLE
Capture frame rate

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#123]
I reproduced this issue (#105) with the capture.
![2015-03-19-084120_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6729750/5bd477ee-ce14-11e4-89de-7edfc4472cb2.png)

**Comment by mkassner** [comment]
If you are seeing this in Pupil Capture it means the the app is receiving
frames at that rate. Quite strange. Do you get sustained higher frame-rate?

**Comment by cpicanco** [comment]
I am not sure, but certainly nothing compared to when it gets the 30-31 fps. I was in front of a glass transparent window, and there was a big tree outside giving some shadow (I am in the second floor, so it is a big tree, indeed). The lights of the room was on as well. I was able to increase the chances of 40-45 fps by looking to such a clean surface, like this white wall.

**Comment by mkassner** [comment]
Also strange is you 0% CPU load. What world cam are you using?

**Comment by cpicanco** [comment]
Logitech C615 -> world
Microsoft HD-5000 >- eye

**Comment by cpicanco** [comment]
The CPU load is really strange. Any news about it?

**Comment by cpicanco** [comment]
The last bundle is running ok. Maybe an error was introduced somewhere. Take a look at the pictures:

Bundle.
![2015-03-27-161154_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6875356/9c42cf0e-d49c-11e4-8b41-92af7e864641.png)
 
Latest commit  a798b555299deea39cb36997ba8f62d48f43e6b4
![2015-03-27-161256_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6875376/c3128598-d49c-11e4-9326-96ae86f2fa3e.png)

Hope this helps,
Best
Rafael

**Comment by cpicanco** [comment]
@mkassner and @willpatera 

Take a look at that graph:
![world_timestamps_differences](https://cloud.githubusercontent.com/assets/6511849/6971089/7145b178-d950-11e4-8031-6ecd5437bf93.png)

I think that for some reason the camera feeding (or pupil capture) is unstable. But since I have no parameters to compare, I can conclude nothing. Is that the expected behavior? Please, give some light on this.

Best
Rafael

**Comment by cpicanco** [comment]
An histogram now...
![world_timestamps_hist](https://cloud.githubusercontent.com/assets/6511849/6971249/829b9e32-d951-11e4-902f-fccea5940c71.png)

**Comment by cpicanco** [comment]
This is evidence that I could really be getting 50 fps with a 30 fps camera.

**Comment by cpicanco** [comment]
It is not a camera specific feature.
![eye_timestamps_difference](https://cloud.githubusercontent.com/assets/6511849/6971781/5a8258c4-d955-11e4-975a-c96cc5bd9823.png)
![eye_timestamps_hist](https://cloud.githubusercontent.com/assets/6511849/6971779/5a3c89f2-d955-11e4-9a36-aa28c54c09bc.png)

**Comment by cpicanco** [comment]
For me it is magic. Or elves.

**Comment by willpatera** [comment]
@cpicanco -- Thanks for the comprehensive report. I will have to wait for @mkassner to give an equally comprehensive answer here as he was working on the Linux driver. 

On Linux the timestamps should be generated by the hardware, but not all hardware generates valid timestamps. See notes here: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/uvc_capture/linux_video/__init__.py#L89-L96

So, if you are using `HD-6000`, then it falls back to software timestamps. Do you ever get the logger warning from this line: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/uvc_capture/linux_video/__init__.py#L158 ?

**Comment by cpicanco** [comment]
Yes, software timestamps. Another important thing to note is that the number of frames (12303) and the time (8 min) matches 25-30 frames per second. So, no elves.

> World Process: 2015-04-02 17:47:22,846 - uvc_capture.linux_video - INFO - Capture device: 'HD Webcam C615' is not known to support HW timestamping. Using software timestamps.

> World Process: 2015-04-02 17:47:22,846 - uvc_capture.linux_video - INFO - Capture device: 'Microsoft® LifeCam HD-5000' detected as attached device. Falling back to software timestamps

**Comment by mkassner** [comment]
@cpicanco , no elves, indeed just a camera that send images at irregular intervals.

**Comment by cpicanco** [comment]
So, should I buy another camera? Oh my...

**Comment by cpicanco** [comment]
@mkassner, but why such irregular behavior does not occurs with the bundle??

**Comment by cpicanco** [comment]
@mkassner and @willpatera. Changing from Lubuntu 14.0.4 LTS to Ubuntu 14.0.4 LTS solves the problem. Elves.
![screenshot from 2015-04-15 20 38 37](https://cloud.githubusercontent.com/assets/6511849/7171526/eee55944-e3af-11e4-83d9-2b7b31b1fdbd.png)

**Comment by cpicanco** [comment]
And the CPU load is ok as well. The OS was broken. Somehow. Sorry about that guys.

**Comment by cpicanco** [comment]
I am not using the bandwidth patch, just to be noted.

**Comment by cpicanco** [comment]
@mkassner and @willpatera , please, remove the question label of this issues. Put a "will not fix" or "invalid" or something else. I think it is a concrete issue related with Lubuntu, but I understand that no support is available. Take a look at the world cam deltas on ubuntu:
![world_timestamps_delta](https://cloud.githubusercontent.com/assets/6511849/7286507/dbb51062-e922-11e4-8b72-2e1a416a30fe.png)
