### ISSUE TITLE
Tracking a dynamic object of interest from pupil player

### ISSUE THREAD

**Issue by shivamkalhan** [pupil-labs/pupil#1230]
Hi there, 

Is there a way to track a dynamic object of interest - such as a moving tennis ball from pupil player? This is so that I'm able to get its coordinates.

Thanks,

**Comment by papr** [comment]
Hey @shivamkalhan 
The Pupil software only supports tracking objects using our surface markers. https://docs.pupil-labs.com/#surface-tracking

We do not support appearance-based object tracking.

**Comment by shivamkalhan** [comment]
Hey @papr,
Thanks a lot for your response and the link! It's been quite helpful in planning future experiments.
Thanks, 
Shivam
