### ISSUE TITLE
Not Getting the 3D World camera to work 

### ISSUE THREAD

**Issue by N0v0** [pupil-labs/pupil#1232]
Hi, I just bought the pupil lab glasses with binocular eye cameras and 3D world camera. When I ran the "Pupil_Capture" program the two eye cameras worked fine but the 3D world camera has never worked. I get this message from the cmd every time:

> world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.

I tried reinstalling the drivers but is not working, I'm on a Desktop computer with Windows 10. What shoud I do?

**Comment by ph4nie** [comment]
Hi,
I am having the same issue. I followed the troubleshooting instructions for Windows Driver Setup, but I still find only 2 cams instead of 3 under "libusbK USB Devices" in Devices Manager...

Thanks for any help !

Fanny

**Comment by papr** [comment]
The 3d world camera is a special case and is not affected by libusbK drivers. Please write an email to info@pupil-labs.com concerning this issue. Please, also add your order id as well.
