### ISSUE TITLE
Problem running pupil from source - /usr/lib/libgomp.so.1

### ISSUE THREAD

**Issue by jicont21** [pupil-labs/pupil#1234]
Hi. I'm having trouble trying to run pupil from source.
I've installed all the dependencies. I Get:

```
[aero@aeroboard pupil_src]$ python3 main.py 
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.8.3
world - [INFO] launchables.world: System Info: User: aero, Platform: Linux, Machine: aeroboard, Release: 3.14.79-28-ARCH, Version: #1 SMP PREEMPT Tue Nov 28 20:47:59 MST 2017
world - [INFO] pupil_detectors.build: Building extension modules...
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/aero/pupil/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/home/aero/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 19, in <module>
    from .detector_3d import Detector_3D
ImportError: /usr/lib/libgomp.so.1: cannot allocate memory in static TLS block

world - [INFO] launchables.world: Process shutting down.

```

**Comment by papr** [comment]
@jicont21 on which OS/hardware are you running the source?

**Comment by jicont21** [comment]
Thanks for the answer.

I'm running pupil on a Odroid C2 (64bit ARM), specs and architecture details here:
[Odroid C2 Homepage](https://www.hardkernel.com/main/products/prdt_info.php?g_code=G145457216438)

Te OS I'm using is ArchlinuxARM

For running pupil software I have followed carefully the instructions on the devs documentation, installing every dependency and compiling from source where it was necessary. I've had several problems due to the differences between this SO and the officially supported Ubuntu: sonames, package names, other necessary dependencies not mentioned on the dev docs (pytorch) etc. I was able to solve them all.

As I work on this I'm prepairing a detailed guide on how to run this source on this single board computer with Archlinux. I'll be glad to e-mail it to you when it's done.

I'll appreciate some help with this problem. Please let me know if you need more information.

**Comment by jicont21** [comment]
Hello.
How are you?.

Do we have any comments on this issue?
Thank you!

**Comment by papr** [comment]
I am sorry, I have never come across this error and therefore I cannot comment anything helpful.

**Comment by Prologueyan** [comment]
Have u solved this problem ？

**Comment by jicont21** [comment]
Not yet :(

**Comment by papr** [comment]
Since we use the manylinux image to build the wheels, this should no longer be an issue.
