### ISSUE TITLE
Unable to get gaze position messages despite being subscribed and the pink gaze position dot appearing on pupil capture

### ISSUE THREAD

**Issue by liampeng1** [pupil-labs/pupil#1235]
I am unable to get gaze position messages despite being subscribed and the pink gaze position dot appearing on pupil capture. I can also access the gaze position data in the recorded data. I am able to receive pupil data but not gaze position. I have already calibrated. I am not sure if I have the right word for the gaze position but could not find what it is anywhere. This is on mac OS high sierra. I am connecting to the socket in matlab. Here is the code that works for pupil data but not gaze: 

% Setup zmq context and remote helper
ctx = zmq.core.ctx_new();
req_socket = zmq.core.socket(ctx, 'ZMQ_REQ');

% set timeout to 1000ms in order to not get stuck in a blocking
% mex-call if server is not reachable, see
% http://api.zeromq.org/4-0:zmq-setsockopt#toc19
zmq.core.setsockopt(req_socket, 'ZMQ_RCVTIMEO', 1000);

ip_address = '127.0.0.1';
req_port = '50020';
req_endpoint =  sprintf('tcp://%s:%s', ip_address, req_port);

fprintf('Connecting to REQ: %s\n', req_endpoint);
zmq.core.connect(req_socket, req_endpoint);

% Request sub port
zmq.core.send(req_socket, uint8('SUB_PORT'));
sub_port = char(zmq.core.recv(req_socket));
fprintf('Received sub port: %s\n', sub_port);

% Disconnect req socket
zmq.core.disconnect(req_socket, req_endpoint);
zmq.core.close(req_socket);
fprintf('Disconnected from REQ: %s\n', req_endpoint);

if isequal(sub_port, false)
    warning('No valid sub port received');
    return;  % exit script
end

% Create and connect sub socket
sub_endpoint = sprintf('tcp://%s:%s', ip_address, sub_port);
sub_socket = zmq.core.socket(ctx, 'ZMQ_SUB');

% set timeout to 1000ms in order to not get stuck in a blocking
% mex-call if server is not reachable, see
% http://api.zeromq.org/4-0:zmq-setsockopt#toc19
zmq.core.setsockopt(sub_socket, 'ZMQ_RCVTIMEO', 1000);

fprintf('Connecting to SUB: %s\n', sub_endpoint);
zmq.core.connect(sub_socket, sub_endpoint);

% set subscriptions to topics
% recv just pupil/gaze/notifications
% zmq.core.setsockopt(sub_socket, 'ZMQ_SUBSCRIBE', 'pupil.');
 zmq.core.setsockopt(sub_socket, 'ZMQ_SUBSCRIBE', 'gaze.');
% zmq.core.setsockopt(socket, 'ZMQ_SUBSCRIBE', 'notify.');
% zmq.core.setsockopt(socket, 'ZMQ_SUBSCRIBE', 'logging.');
% or everything else
% zmq.core.setsockopt(socket, 'ZMQ_SUBSCRIBE', '');

for iter = 1:20  % receive the first 5 messages
    % messages that are longer than 1024 bytes will be tuncated
    % and ignored. In this case note is set to false. Increase
    % the buffer size if you experience this issue.
    [topic, note] = recv_message(sub_socket, 1024);
    if ~isequal(note, false)  % test for valid message
        disp([topic, note('norm_pos')]);  % print gaze norm_pos
    end
end

% disconnect sub socket
zmq.core.disconnect(sub_socket, sub_endpoint);
zmq.core.close(sub_socket);
fprintf('Disconnected from SUB: %s\n', sub_endpoint);

zmq.core.ctx_shutdown(ctx);
zmq.core.ctx_term(ctx);

**Comment by papr** [comment]
Unfortunately, I ran into this error as well. This is an error in the msgpack-python parser implementation. It could be one of two issues:
1. There are [different mapping encodings](https://github.com/msgpack/msgpack/blob/master/spec.md#map-format-family) for mappings with different lengths. The parser might only implement the shortest one.
2. The parser might expect the mapping-keys to be strings. In the case of the 3d datum we use ints as keys in special cases (the msgpack spec supports that).

Currently, I do not have the time to look into this further. If I had to guess I would think that issue 1 is at fault.

**Comment by liampeng1** [comment]
So, to clarify, you believe it is in the python code that send out the message or the matlab code that receives it?

**Comment by papr** [comment]
It's the matlab code.

**Comment by liampeng1** [comment]
This is the msgpack parser. It seems like it accounts for it in case 222 and 223

%PARSEMSGPACK parses a msgpack byte buffer into Matlab data structures
% PARSEMSGPACK(BYTES)
%    reads BYTES as msgpack data, and creates Matlab data structures
%    from it.
%    - strings are converted to strings
%    - numbers are converted to appropriate numeric values
%    - true, false are converted to logical 1, 0
%    - nil is converted to []
%    - arrays are converted to cell arrays
%    - maps are converted to containers.Map

% (c) 2016 Bastian Bechtold
% This code is licensed under the BSD 3-clause license

function obj = parsemsgpack(bytes)
    [obj, ~] = parse(uint8(bytes(:)), 1);
end

function [obj, idx] = parse(bytes, idx)
    % masks:
    b10000000 = 128;
    b01111111 = 127;
    b11000000 = 192;
    b00111111 = 63;
    b11100000 = 224;
    b00011111 = 31;
    b11110000 = 240;
    b00001111 = 15;
    % values:
    b00000000 = 0;
    b10010000 = 144;
    b10100000 = 160;

    currentbyte = bytes(idx);

    if bitand(b10000000, currentbyte) == b00000000
        % decode positive fixint
        obj = int8(currentbyte);
        idx = idx + 1;
        return
    elseif bitand(b11100000, currentbyte) == b11100000
        % decode negative fixint
        obj = typecast(currentbyte, 'int8');
        idx = idx + 1;
        return
    elseif bitand(b11110000, currentbyte) == b10000000
        % decode fixmap
        len = double(bitand(b00001111, currentbyte));
        [obj, idx] = parsemap(len, bytes, idx+1);
        return
    elseif bitand(b11110000, currentbyte) == b10010000
        % decode fixarray
        len = double(bitand(b00001111, currentbyte));
        [obj, idx] = parsearray(len, bytes, idx+1);
        return
    elseif bitand(b11100000, currentbyte) == b10100000
        % decode fixstr
        len = double(bitand(b00011111, currentbyte));
        [obj, idx] = parsestring(len, bytes, idx + 1);
        return
    end

    switch currentbyte
        case 192 % nil
            obj = [];
            idx = idx+1;
      % case 193 % unused
        case 194 % false
            obj = false;
            idx = idx+1;
        case 195 % true
            obj = true;
            idx = idx+1;
        case 196 % bin8
            len = double(bytes(idx+1));
            [obj, idx] = parsebytes(len, bytes, idx+2);
        case 197 % bin16
            len = double(bytes2scalar(bytes(idx+1:idx+2), 'uint16'));
            [obj, idx] = parsebytes(len, bytes, idx+3);
        case 198 % bin32
            len = double(bytes2scalar(bytes(idx+1:idx+4), 'uint32'));
            [obj, idx] = parsebytes(len, bytes, idx+5);
        case 199 % ext8
            len = double(bytes(idx+1));
            [obj, idx] = parseext(len, bytes, idx+1);
        case 200 % ext16
            len = double(bytes2scalar(bytes(idx+1:idx+2), 'uint16'));
            [obj, idx] = parseext(len, bytes, idx+3);
        case 201 % ext32
            len = double(bytes2scalar(bytes(idx+1:idx+4), 'uint32'));
            [obj, idx] = parseext(len, bytes, idx+5);
        case 202 % float32
            obj = bytes2scalar(bytes(idx+1:idx+4), 'single');
            idx = idx+5;
        case 203 % float64
            obj = bytes2scalar(bytes(idx+1:idx+8), 'double');
            idx = idx+9;
        case 204 % uint8
            obj = bytes(idx+1);
            idx = idx+2;
        case 205 % uint16
            obj = bytes2scalar(bytes(idx+1:idx+2), 'uint16');
            idx = idx+3;
        case 206 % uint32
            obj = bytes2scalar(bytes(idx+1:idx+4), 'uint32');
            idx = idx+5;
        case 207 % uint64
            obj = bytes2scalar(bytes(idx+1:idx+8), 'uint64');
            idx = idx+9;
        case 208 % int8
            obj = bytes2scalar(bytes(idx+1), 'int8');
            idx = idx+2;
        case 209 % int16
            obj = bytes2scalar(bytes(idx+1:idx+2), 'int16');
            idx = idx+3;
        case 210 % int32
            obj = bytes2scalar(bytes(idx+1:idx+4), 'int32');
            idx = idx+5;
        case 211 % int64
            obj = bytes2scalar(bytes(idx+1:idx+8), 'int64');
            idx = idx+9;
        case 212 % fixext1
            [obj, idx] = parseext(1, bytes, idx+1);
        case 213 % fixext2
            [obj, idx] = parseext(2, bytes, idx+1);
        case 214 % fixext4
            [obj, idx] = parseext(4, bytes, idx+1);
        case 215 % fixext8
            [obj, idx] = parseext(8, bytes, idx+1);
        case 216 % fixext16
            [obj, idx] = parseext(16, bytes, idx+1);
        case 217 % str8
            len = double(bytes(idx+1));
            [obj, idx] = parsestring(len, bytes, idx+2);
        case 218 % str16
            len = double(bytes2scalar(bytes(idx+1:idx+2), 'uint16'));
            [obj, idx] = parsestring(len, bytes, idx+3);
        case 219 % str32
            len = double(bytes2scalar(bytes(idx+1:idx+4), 'uint32'));
            [obj, idx] = parsestring(len, bytes, idx+5);
        case 220 % array16
            len = double(bytes2scalar(bytes(idx+1:idx+2), 'uint16'));
            [obj, idx] = parsearray(len, bytes, idx+3);
        case 221 % array32
            len = double(bytes2scalar(bytes(idx+1:idx+4), 'uint32'));
            [obj, idx] = parsearray(len, bytes, idx+5);
        case 222 % map16
            len = double(bytes2scalar(bytes(idx+1:idx+2), 'uint16'));
            [obj, idx] = parsemap(len, bytes, idx+3);
        case 223 % map32
            len = double(bytes2scalar(bytes(idx+1:idx+4), 'uint32'));
            [obj, idx] = parsemap(len, bytes, idx+5);
        otherwise
            error('transplant:parsemsgpack:unknowntype', ...
                  ['Unknown type "' dec2bin(currentbyte) '"']);
    end
end

function value = bytes2scalar(bytes, type)
    % reverse byte order to convert from little-endian to big-endian
    value = typecast(bytes(end:-1:1), type);
end

function [str, idx] = parsestring(len, bytes, idx)
    str = native2unicode(bytes(idx:idx+len-1)', 'utf-8');
    idx = idx + len;
end

function [out, idx] = parsebytes(len, bytes, idx)
    out = bytes(idx:idx+len-1);
    idx = idx + len;
end

function [out, idx] = parseext(len, bytes, idx)
    obj.type = bytes(idx);
    obj.data = bytes(idx+1:idx+len);
    idx = idx + len + 1;
end

function [out, idx] = parsearray(len, bytes, idx)
    out = cell(1, len);
    for n=1:len
        [out{n}, idx] = parse(bytes, idx);
    end
end

function [out, idx] = parsemap(len, bytes, idx)
    out = containers.Map();
    for n=1:len
        [key, idx] = parse(bytes, idx);
        [out(key), idx] = parse(bytes, idx);
    end
end

**Comment by papr** [comment]
Closing, as this is an issue with the Matlab msgpack decoder.
