### ISSUE TITLE
Set parameter for Raw Data Exporter in Pupil Player

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1239]
I just recognized that you always export all raw data to the export folder. Having long recordings create huge exports when always exporting all data. Wouldn't it be a good idea to select whether you want to export pupil_positions, gaze_position, surfaces, etc. to optimize the export time.

**Comment by papr** [comment]
You are totally right. Did you know that you can trim the recording and only export data that belongs to this section?

**Comment by ewolf29** [comment]
Yes, that's already a nice feature. :) Just see this issue as a feature request to improve your product.

**Comment by papr** [comment]
Ok, I understand. Something that should help already: The surface data is exported by the offline surface tracker and not by the Raw Data Exporter. If you are not interested in exporting surface data, simply disable the surface tracker plugin. To further iterate on that: The raw data exporter only exports pupil and gaze positions. This is comparably fast. Nonetheless, adding ui elements to turn on/off the exports is easy. Thank you for your feedback. We will consider adding this feature to the next release.

**Comment by ewolf29** [comment]
Ah, it already helps a lot to know that all the other "raw"-data is exported by the corresponding plugin. Thanks.

**Comment by papr** [comment]
Closed via #1310
