### ISSUE TITLE
Player: cache offline natural feature calibration, gaze mapping, and fixations between sessions.

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1246]
Self explanatory, I think.  

The 3D pupil detection is cached.  Offline gaze-mapping should be similarly cached.  ...as well as the detected fixations.

**Comment by papr** [comment]
Partially fixed in #1434 

Fixation cache support will be added in [v1.12](https://github.com/pupil-labs/pupil/milestone/19)
