### ISSUE TITLE
Surface marker are not detected until restart of surface tracker plugin

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1247]
System: MacOS
Pupil Capture: V1.8.12
Pupil Player: V1.8.12

After I drag a recording with surfaces into Pupil Player, the Surface Cache is not filled automatically. I have to restart the Surface Tracker Plugin to start the detection of the marker.

Reconding: https://oc.informatik.uni-wuerzburg.de/index.php/s/KyNeyRX66pKgkX5
Password: pupillabs

**Comment by papr** [comment]
Hey, just to clarify, are these the steps to reproduce the issue:

1. Open recording A in Player
2. Load the offline surface tracker
-> Starts filling surface cache
3. Close Player
4. Open recording B in Player
-> offline surface tracker is loaded
-> Surface cache is not being filled

**Comment by ewolf29** [comment]
@papr Yes.

**Comment by papr** [comment]
Fixed in #1268
