### ISSUE TITLE
Natural Feature Calibration

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#125]
Hi everyone,

I have some suggestions to discuss, in order to improve the Natural Feature Calibration. I think it would be good to have the cleanest screen as possible while calibrating in this mode:
- [ ] The Confidence is very useful, it should be keeped on the screen;
- [ ] Auto hide the CPU load;
- [ ] Auto hide the FPS;
- [x] Auto hide the ui panel on the right;
- [ ] Do not show the gaze points from earlier calibration;

What do you think?

**Comment by mkassner** [comment]
Sounds good. I like the idea of hiding the ui panel on the right.

**Comment by mkassner** [comment]
stale
