### ISSUE TITLE
Surface tracking suddenly stopps in the middle of a recording

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1250]
System: MacOS
Pupil Capture: V1.8.12
Pupil Player: V1.8.12
Pupil Mobile: 0.30.0
Wifi: 5Ghz with 850Mbit

The tracking of the surface markers (filling if the surface cache) stops in this recording for some reason suddenly in the middle of the recording.

Steps to reproduce: Open the recording and try to detect surfaces.

It's a different recording than for the other two bugs.

Recording: https://oc.informatik.uni-wuerzburg.de/index.php/s/d8Q6SXfxJozTNRR
Passwort: pupillabs

**Comment by ewolf29** [comment]
Possibly a typo...

Recording: https://oc.informatik.uni-wuerzburg.de/index.php/s/eijkGsxomBJkY8r
Passwort: pupillabs

**Comment by papr** [comment]
This issue was due to a broken video file. Closing since this is not a Pupil software bug.
