### ISSUE TITLE
Eyecameras suddenly stop working during recording via Pupil Capture and Pupil Mobile

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1251]
System: MacOS
Pupil Capture: V1.8.12
Pupil Player: V1.8.12
Pupil Mobile: V0.30.0
Wifi: 5Ghz with 850Mbit

Today, we had a pilot session in the hospital where we tested to record a 20 minute session. At minute 18 and second 21, the first eye camera suddenly turned black and shortly afterwards the second one as well. Restarting Pupil Capture made in working again. Unfortunately, I did not save the capture.log file. I will try to reproduce this but maybe you can already see an issue in the recording.

Recording: https://oc.informatik.uni-wuerzburg.de/index.php/s/bi8jBisRiKMCwj4
Password: pupillabs

The upload of the recording will take a while.

**Comment by ewolf29** [comment]
Related to #1229

**Comment by papr** [comment]
Closing as Pupil Mobile is no longer maintained and this issue is inactive.
