### ISSUE TITLE
The square_marker_cache should be saved after filling it

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1253]
Pupil Player: 1.8.26

The square_marker_cache is just saved when pupil player is closed. Why not save it after it is completely filled to avoid data loss when the application crashes? This btw. would also be for other cases quite useful.

**Comment by cpicanco** [comment]
I agree. It really needs a flush method.

**Comment by papr** [comment]
Fixed in #1268

**Comment by cpicanco** [comment]
Great!
