### ISSUE TITLE
Calculated fixations should be saved when using (Offline) Fixation Detector

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1254]
Pupil Player: 1.8.26

When fixations are calculated via the Offline Fixation Detector plugin, the results should be saved in a file and it should be possible to reload it when opening a recording again. The calculation of the fixations might take far longer as the duration of the actual recording. At the moment, you always have to do this again when either making a change in the parameter of the plugin or when reopening a recording. There also should be a button to start the recalculation like in other plugins to make sure you are not accidentally overriding your calculated fixations.

**Comment by papr** [comment]
Implemented in #1482 which will replace the legacy fixation detector
