### ISSUE TITLE
Boost library name

### ISSUE THREAD

**Issue by arbu** [pupil-labs/pupil#1255]
I managed to run Pupil Labs on Arch Linux and the only problem I faced regarding Pupil Labs itself was that libboost_python-py37.so could not be found. Removing the special case for Linux here https://github.com/pupil-labs/pupil/blob/5fe9bde620e79db63cd5a2de15704fca07210b73/pupil_src/shared_modules/pupil_detectors/setup.py#L78-L80 and here https://github.com/pupil-labs/pupil/blob/5fe9bde620e79db63cd5a2de15704fca07210b73/pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py#L78-L80 resolved that issue.

I did some research and apparently the -pyXY suffix is specific to current Ubuntu and Debian. boost-python recently changed its naming convention and Ubuntu and Debian will probably adapt this convention in future releases: https://github.com/boostorg/python/issues/203#issuecomment-391496332. In Ubuntu cosmic the old naming convention is only available for backward compatibility for python 3.6 but not for python 3.7: https://packages.ubuntu.com/cosmic/amd64/libboost-python1.67-dev/filelist.

I looked at some other distributions and most of them use the name libboost_python3.so and my guess is that they will use the new naming convention once they ship libboost-python >= 1.67.

For the next release of Ubuntu this will need to be adapted anyway but I would appreciate it if you could make it compatible with other Linux distributions. I would suggest to simply try which one is available.

**Comment by papr** [comment]
Hey @arbu Thank you very much for sharing your research results. This is very helpful!

**Comment by papr** [comment]
We have removed the requirement to install boost in #1552
