### ISSUE TITLE
Load surface names and sizes in Player

### ISSUE THREAD

**Issue by marc-tonsen** [pupil-labs/pupil#1261]
When opening a recording with pre-existing surface definitions in Player the surface names and sizes are not loaded but are initialized with default values. These values should be saved and loaded.

**Comment by papr** [comment]
Is this being fixed through #1268 ?

**Comment by marc-tonsen** [comment]
Yes, I think it should be. In Capture this is already solved through #1268 , I'll check if changes to Player are necessary for this to carry over!

**Comment by papr** [comment]
Fixed in #1268
