### ISSUE TITLE
Cannot run from the source

### ISSUE THREAD

**Issue by luswangl2013** [pupil-labs/pupil#1269]
Hello, this is what I got when I tried to start pupil lab from the source. Any fix?
> D:\pupil_v1.8\pupil\pupil_src>python main.py capture
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.8.26
world - [INFO] launchables.world: System Info: User: SSRL, Platform: Windows, Machine: DESKTOP-NA0QML9, Release: 10, Version: 10.0.16299
world - [INFO] pupil_detectors.build: Building extension modules...
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Community\\VC\\Tools\\MSVC\\14.15.26720\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "D:\pupil_v1.8\pupil\pupil_src\launchables\world.py", line 113, in world
    import pupil_detectors
  File "D:\pupil_v1.8\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "D:\pupil_v1.8\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "D:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "D:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:\\Python36\\python.exe', 'setup.py', 'install', '--install-lib=D:\\pupil_v1.8\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.

**Comment by papr** [comment]
For some reasons the `pupil_detectors` fail to build. Follow the [docs on how to debug](https://docs.pupil-labs.com/#modify-pupil-detectors-setup-py) that.

May I ask for your reason to run from source? Often it is not required and especially on Windows it is easier to run the bundle.

**Comment by luswangl2013** [comment]
I know it is easier to run the bundle. However, I want to modify one of the plugin.
Actually, I am trying to connect Microsoft Hololens with pupil  lab. I want to use pupil diameter data in runtime in Unity3D. I noticed there is a plugin named "Hololens Relay" but it only transfers gaze data to Unity3D. So I would like to modify the plugin myself. That is why I had to build the pupil lab from source.
Do you know some better way using pupil data in Unity3D?

**Comment by papr** [comment]
One alternative would be copy the original file into your `pupil_capture_settings\plugins` folder, rename the class and run Capture from bundle. Just treat the copy a if ti was a custom/self-written plugin.

**Comment by luswangl2013** [comment]
Thank you for your advice. I now get on the right way to use it.
