### ISSUE TITLE
Show calibration results on player.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#127]
Would be good to have the show calibration results in the player as well. It is very useful.

**Comment by willpatera** [comment]
Hi @cpicanco -- this could be ported to Player as well. The only module that is not currently available to player are the calibration methods -- which would need to be accessible in order to show the calibration results.

**Comment by cpicanco** [comment]
Thanks will. I will take a look. You have already done something like that by making the "shared_modules" folder visible in the scope of a normal python session from modules inside "capture" and "player".

**Comment by mkassner** [comment]
If just did the necessary legwork for this to work. This should work now.
