### ISSUE TITLE
help to get data

### ISSUE THREAD

**Issue by Jonathanc24** [pupil-labs/pupil#1272]
Hello,

I'm using pupil for a marketing research and I need to get the following data:
• Number of fixings
• Total fixing time
• Total time until the first fixation.

Can you tell me how to get that data please?

I'll look forward for your answer

**Comment by mkassner** [comment]
@Jonathanc24  if you run fixation detection in  Pupil player and then export the fixation data you can use this fixation info to calculate or read the metrics you are interested in.

I hope this helps!
