### ISSUE TITLE
Intermittently losing pupil diameter measurements when eye is not moving

### ISSUE THREAD

**Issue by gmierz** [pupil-labs/pupil#1273]
Hello, I've been conducting event-based research with this eye tracker and for some reason, the pupil diameter data gets really noisy at times because it seems like pupil capture keeps losing the pupils intermittently. I find this very odd though because the subject never moves their eyes, and never blinks during the trials, but as we get further into the trial the pupil diameter is being lost and it results in data that looks like this:

![all_triggers_means_eye1](https://user-images.githubusercontent.com/10966989/44301825-7e03e980-a2eb-11e8-8aeb-b1e8e9b09a59.png)

I am wondering if anyone has seen this problem before? The gaze position data also starts going all over the place whenever the noise seen above is observed. I'm thinking it's my calibration but I don't understand why that would make it fail when the eye (and subject) is motionless.

The problem also gets worse as time goes on, or the longer we have the eye tracker running. It's mainly `eye1` that is problematic. It happens to `eye0` as well, but not as often. Could it be because of the position of the eye cameras? That said, if I can see that the pupil is in full view of the camera with no distortions or noise, and with nothing blocking it, I expect that the capture software will be able to catch it. But I'm not sure if what I'm seeing here is a bug or expected behaviour.

I can work around this problem a bit with a [simple brickwall FFT filter](https://github.com/gmierz/pupil-lib-python/blob/master/pupillib/core/workers/processors/trial_processor.py#L127) from pupil-lib-python:
Before (eye0):
![all_triggers_means_eye0](https://user-images.githubusercontent.com/10966989/44301913-6168b100-a2ed-11e8-8f2f-085f0f044fc7.png)

After (eye1):
![all_triggers_means_eye0_fftfilt_0 7-0_30trials](https://user-images.githubusercontent.com/10966989/44301909-5150d180-a2ed-11e8-9506-71fdedcd2baa.png)

But it would be much better if I didn't have to filter the data. I'll be trying a different calibration method, along with double-checking to ensure pupil capture is up to date - in case this was fixed before.

**Comment by mkassner** [comment]
This looks like the eye model breaking down when the pupil is not moving. Have you tried playing with the 3d model sensitivity slider?

**Comment by gmierz** [comment]
I ran a little experiment and I found that after I brought the 'Pupil Intensity Range' slider down to 4 from it's usual setting, I was no longer losing data.

Previously, on the Pupil Capture displays for each eye, the green circle would decrease in size and get as small as the red circle displayed around the pupil (and even smaller). Once it gets to the size of the red circle around the pupil, the red circle would then start disappearing and causing the intermittent data loss.

I'm going to do a longer experiment soon to make sure this fixes it, and if not, I'll try playing with the model sensitivity slider some more and post what I find. I tried playing with the model sensitivity slider in my little experiment, but I didn't notice any big differences so maybe I need to do this long experiment for that setting to have an affect.

**Comment by gmierz** [comment]
I ran a 2 hour long continuous experiment and found that bringing the `Pupil Intensity Range` down to 4 was not enough after about 8 minutes in. I brought the `3D model sensitivity` slider down to it's lowest level, and from then on, across the whole 2 hours, we never had to reset the 3D model again.

@mkassner thanks for the help! :)

Here's a figure of what it looks like now, the noise at the start and end is blinking but there is no more intermittent data loss occurring:
![fixed_pupild](https://user-images.githubusercontent.com/10966989/45256134-2f80c280-b360-11e8-828c-fa9ab761fac6.png)

**Comment by gmierz** [comment]
@mkassner, unfortunately, after testing this with more subjects, I am still having the same sort of error. These errors were slightly different though because they occurred when the pupil reached it's minimum size through a high-contrast (high luminance) stimulus, and after it happens once, it makes the rest of the recorded data bad as well.

The change in pupil size was in the range of 50%-75% contraction in this case. The subjects that didn't have this issue have a contraction of ~20% for this stimulus.

Here's an example of the data (only 4/100 trials shown here, the rest of the trials are worse):
![bad_data](https://user-images.githubusercontent.com/10966989/46504352-b4de8200-c7fb-11e8-8c47-c8a1838e31d2.png)

This might be related to https://github.com/pupil-labs/pupil/issues/1270 but I don't think it's possible, so I'll do some testing to check that. In any case, I am re-opening this issue.

**Comment by papr** [comment]
This issue can be avoided by freezing the eye model, see release https://github.com/pupil-labs/pupil/releases/tag/v1.15
