### ISSUE TITLE
Fix receiving high frequency notifications

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1275]
Sometimes the mp4 files are not readable (even with VLC) – I understand, that is due to corrupted headers (although I do not understand why it is happening so often) .... what I missed until today, is that the eye*.timestamps file for corrupted videos is missing!

we use windows, 1.8.26.... issue is apparent with both codecs (big and small file) ... world video seems to be always fine. we're using pupil capture, not mobile.

In rare cases only one eye is unreadable, but the other is fine.

ffmpeg says "moov atom not found" for the video files.

So far no clue inside the logs – both eye videos in this recording are damaged and the timestamps are missing. 

[capture.log](https://github.com/pupil-labs/pupil/files/2310431/capture.log)

**Comment by mkassner** [comment]
Locking at the log it seems that you are writing video files into some db?

Can you confirm that this is not a harddrive or PC issue?

**Comment by mattem86** [comment]
No, the path is a bit lengthy, but the files are written on SSD. We experienced this on two different notebooks, either on SSD and HDD. Both running in Windows, maybe this is a hint.

**Comment by mkassner** [comment]
Did any process crash (eye) during the recording. I have not seen this before.

**Comment by mattem86** [comment]
No, everything looked normal. It can be that the signal for stopping the recording was sent twice, but this should not be a problem. 
The duration of the recording is about 5 min, we record in VGA resolution. One eye file is about 1.5 gig large. 
In a hexeditor it is visible that the writing of the mp4 file abruptly stops. 
One „hotfix“ to this problem could be writing of „web-optimized“ videos, where the header is written in the beginning. Additional to that I would highly recommend to either write the timestamp file for the video more robustly or think about of storing some way of frame index in pupil data. We have 20+ recordings with corrupted files.

**Comment by mattem86** [comment]
So... I feel I got a little further. The problem could be, that the recording (Pupil Capture, respectively) is shut down ungracefully. It is totally understandable that the recording is not finished correctly, if the process is terminated. BUT – it seems that sometimes the recording will continue to record, even if the (R) in capture is not red anymore. Is this possible? We have videos which are 1 minute longer than expected where we already put our headset off. I do not supervise every measurement we take, but I'm pretty sure that the recording officially stopped. Maybe (!) something changed from v1.6 to v1.7 that the recording silently continued for several seconds?

**Comment by mattem86** [comment]
(In the meantime I will find the person or code snippet which terminates pupil capture so barbaric)

**Comment by mattem86** [comment]
Ok, that's it, at least a clue: If you look at log above and this one, you can see that in the above log the rows "eye* - INFO launchables.eye: Done Recording" are missing. If you look in the log here closely, you can see, that these rows are 83 seconds later than "world - INFO Saved recording"! 
In the screenshot you can see, that the R is not red anymore.

Second: We use the frame publisher plugin to show the eyes in VR. We turn it off during recording (via network) and on again, if the signal "recording_stopped" is received. We noticed that it takes a long time that the eyes in VR are coming back – today we saw that they come back, when the eye video is written (83 secs late).




![bildschirmfoto 2018-08-24 um 10 09 49](https://user-images.githubusercontent.com/421110/44573045-dde40f80-a785-11e8-8ea2-ba2b1b0ef8fd.png)



[capture (1).log](https://github.com/pupil-labs/pupil/files/2317542/capture.1.log)

**Comment by mkassner** [comment]
Ok. It looks like the eye process did for some obscure reason not receive the recording_stopped notification. Maybe the eye process was terminated early?

**Comment by mattem86** [comment]
no, the processes did run until the eye videos were written and stopped correctly.
maybe it is a problem of getting two "stop recording" notifications shortly after another? we noticed that we have to use a delay of 2 seconds between starting the two eye processes via network because otherwise only one eye process is started.

**Comment by mkassner** [comment]
This could be a timing issue, but I dont know for sure. We would have to make some tests and look at the implementation closely.

**Comment by mattem86** [comment]
Since it is so random, maybe it could be a issue with the garbage collection? Is everything flushed etc?

**Comment by mattem86** [comment]
Update: I can confirm, this issue only exists in v1.8 .... v1.6 and v1.7 are working fine (Videos are written instantly when the signal for recording.should_stop arrives). I tested it under the exact same conditions.
AND: It is only an issue under Windows – I ported my Unity project to Mac and ran it completely on Mac, and the videos are written instantly in v1.8.

**Comment by papr** [comment]
Thank you for the update and your debugging work! This helps us a lot!

**Comment by mattem86** [comment]
I'm not sure about this, but it seems – don't ask me why, it looks very weird – that the issue only appears, if I do some Main-Thread Gameobject stuff in Unity within a running Coroutine. If the Coroutine runs without UI-related stuff (like yield return new Waitforseconds()), it seems to work. But of course this is essentiell for my application. As I said, I'm not sure about this, because I cannot think of a way these things are related.

**Comment by mattem86** [comment]
It's weird, because the world video is written instantly, only the eye videos are delayed. So I thought the signal for terminating the recording is received correctly by pupil capture.

**Comment by papr** [comment]
Aha! So this line is at fault: https://github.com/pupil-labs/pupil/blob/master/pupil_src/launchables/eye.py#L463

It should be `while` instead of `if`!

**Comment by mattem86** [comment]
Maybe, but this wasn't changed since v1.7.
What was changed is this:  
https://github.com/pupil-labs/pupil/blob/ca1a69cbda22c82d046a90863dd1d4e0d600bcd3/pupil_src/shared_modules/zmq_tools.py#L117

The zmq.POLLIN is new.

**Comment by ckbaumann** [comment]
To just copy notes by @papr for documentation:

Rewrite Annotation plugins such that
- annotations are represented as data events instead of notifications
- annotations are received by plugin-owned sub socket
- annotation events are added to recent_events
- annotations are saved to `annotations.pldata` by recorder (follows automatically through previous point)
- annotations are blacklisted from being republished in world process, similar to gaze/pupil/frame
- manual annotations are published directly to the IPC

Goal: Same behavior as pupil_data_relay
