### ISSUE TITLE
Wiki - Update Data Format page 

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#128]
There is still some work to be done for the [Data Format](https://github.com/pupil-labs/pupil/wiki/Data-format#synchronisation) page in the wiki. For example in the [Synchronization](https://github.com/pupil-labs/pupil/wiki/Data-format#synchronisation) section the `correlate_gaze` function no longer exists in `calibrate.py`. If not mistaken, this has been replaced by `preprocess_data`. 

Should we also add an example of an `event` in the Data Format page? For example: 

```python
{'gaze': 
	[{'norm_pos': (0.36025593820607937, 0.59216100668959215), 'confidence': 1.0, 'timestamp': 1428652235.345617}, 
	{'norm_pos': (0.35959096130993407, 0.59271955687520017), 'confidence': 1.0, 'timestamp': 1428652235.378968}], 
'pupil_positions': 
	[{'diameter': 76.8673324584961, 'confidence': 1.0, 'angle': 166.532470703125, 'center': (483.4083557128906, 307.45556640625), 'norm_pos': (0.7553255558013916, 0.35946756998697915), 'axes': (45.96342468261719, 76.8673324584961), 'major': 76.8673324584961, 'ellipse': ((174.40835571289062, 182.45556640625), (45.96342468261719, 76.8673324584961), 166.532470703125), 'roi_center': (174.40835571289062, 182.45556640625), 'timestamp': 1428652235.345617, 'id': 0, 'minor': 45.96342468261719}, 
	{'diameter': 77.35202026367188, 'confidence': 1.0, 'angle': 166.4353790283203, 'center': (483.5624542236328, 307.45802307128906), 'norm_pos': (0.7555663347244262, 0.3594624519348144), 'axes': (46.33626174926758, 77.35202026367188), 'major': 77.35202026367188, 'ellipse': ((174.5624542236328, 180.45802307128906), (46.33626174926758, 77.35202026367188), 166.4353790283203), 'roi_center': (174.5624542236328, 180.45802307128906), 'timestamp': 1428652235.378968, 'id': 0, 'minor': 46.33626174926758}]
}
```

**Comment by cpicanco** [comment]
Hi @willpatera, I think that there is a correlate_gaze function here:

https://github.com/pupil-labs/pupil/blob/master/pupil_src/player/player_methods.py#L18

Is that one you were referring to?

**Comment by cpicanco** [comment]
For instance, can someone confirm to me if this correlate_gaze function is the same as taking the minimum absolute difference like this:


```python
    def frame_index_from_timestamp(self, timestamp):
        """
        timestamp: float

        Uses numpy.argmin to return the nearest World Frame Index
        associated with a given timestamp.         
       
        http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html
        """
        return np.abs(self.timestamps - timestamp).argmin()

    def correlate_gaze(self, world_timestamps):
        '''
        gaze_list: timestamp | confidence | gaze x | gaze y |
        world_timestamps: timestamps to correlate gaze data to

        this takes a gaze positions list and a world_timestamps list and makes a new list
        with the length of the number of recorded frames.
        Each slot contains a list that will have 1 or more associated gaze positions.
        '''
        positions_by_frame = [[] for i in world_timestamps]
        for data_line in self.gaze_positions:
            gaze_timestamp, confidence, x, y, = data_line
            frame_idx = self.frame_index_from_timestamp(gaze_timestamp)
            positions_by_frame[frame_idx].append({'norm_gaze':(x,y), 'confidence':confidence, 'timestamp':ts})

        return positions_by_frame
```

**Comment by willpatera** [comment]
Hi @cpicanco  -- yes the `correlate_gaze` function is in `player_methods.py`, that is correct. My issue here was targeted towards documentation and making sure the docs are consistent and up to date with the source code (e.g. `correlate_gaze` no longer used in `calibrate.py`).

**Comment by cpicanco** [comment]
Can I ask you what is a  "first derivative of gaze"? What is it for?

**Comment by mkassner** [comment]
Thats just an example. I guess you can also call it gaze movement speed.

**Comment by mkassner** [comment]
@willpatera I think the data format page should not cover structures within the apps. Just the data that is saved to disk.

**Comment by willpatera** [comment]
@mkassner - :ok: Data Format will just have data saved to disk. But an example of `events` should be on the wiki somewhere. Developer documentation could be a good place.

**Comment by cpicanco** [comment]
@willpatera For instance, I have suggested to describe the events in the "plugin walk through". Maybe it is a good place for describing and show some concrete examples. I think that a central place describing all the "internal data" and pointing to existing examples would be very useful.
