### ISSUE TITLE
Rework LSL integration

### ISSUE THREAD

**Issue by gmierz** [pupil-labs/pupil#1281]
While trying to figure out the data that comes out of the LSL Relay Plugin, I noticed that it is not very clear what type of `diameter` is being referenced here: https://github.com/sccn/labstreaminglayer/blob/master/Apps/PupilLabs/README.md

It only says that `diameter` is one of the data streams of the Primitive Representation. It would be better for everyone to specify that this `diameter` is the one referenced in data-format under the name `diameter`: [pupil_positionscsv](https://github.com/pupil-labs/pupil-docs/blob/master/user-docs/data-format.md#pupil_positionscsv)

And it would be good to explicitly state that any of the other data fields mentioned here can be found in the Python representation: [pupil_positionscsv](https://github.com/pupil-labs/pupil-docs/blob/master/user-docs/data-format.md#pupil_positionscsv)

I've made a PR request to change it here: https://github.com/sccn/labstreaminglayer/pull/339

**Comment by papr** [comment]
I renamed the issue based on  sccn/labstreaminglayer#339

**Comment by papr** [comment]
That would be great if you could that! You are right about the required changes.

**Comment by gmierz** [comment]
Some of the links in the first post have expired. An issue was made [here] to see if they can be restored. The latest things that I've done can be seen here: https://github.com/gmierz/labstreaminglayer/blob/patch-2/Apps/PupilLabs/pupil_lsl_relay.py

The problem I am stuck at is that msgpack uses bytes for storage and LSL does not. This leads to formatting issues when we try to open the msgpack data during processing. I have yet to find a solution to this but I think that writing out each byte value as a character, then passing that to LSL may work. IMO, that solution would kind of defeat the purpose of msgpack though (saving space). The other solution that I see is making sure that LSL encodes the bytes into a string of ASCII or UTF-8 format, then converting it back to bytes through an ASCII format. The big problem here is that msgpack contains bytes that don't exist in ASCII or UTF-8 making this solution difficult (maybe there is another formatter that could be used).

I don't have much time to hack on this issue for the next little bit so if anyone else is interested, feel free to pick it up. :)

[here]: https://github.com/labstreaminglayer/App-PupilLabs/issues/2

**Comment by papr** [comment]
I have been working on this during the last week. The trick is to use the int8 channel type instead of string.

**Comment by gmierz** [comment]
Ah, that makes sense, excellent! Do you want me to readd the old PR or will you be making a new one?

**Comment by papr** [comment]
I was planning on creating a new one, since I have been restructuring the code as well.

**Comment by gmierz** [comment]
Sounds good, I'll mention that in the issue I made on the labstreaminglayer/app-pupillab repo.

**Comment by papr** [comment]
Turns out, that int8 channels only support fixed length data which the msgpack encoded bytes are not. I created an[ issue over at the pylsl repository](https://github.com/labstreaminglayer/liblsl-Python/issues/7) to get this fixed.

**Comment by gmierz** [comment]
@papr has this issue been solved? I noticed that [pylsl 2.0](https://github.com/labstreaminglayer/App-PupilLabs/releases/tag/v2.0) is now available. Looks great! :) 

I am also wondering if the v1.0 data format is gone now?

**Comment by papr** [comment]
Yes, the v1.0 format has been replaced by the rework.
