### ISSUE TITLE
Unproject & Project do not result in identical points

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#1287]
Hi!
I use the fisheye intrinsics. I expected that when I unproject and project again, I should get the same points again. but this is not the case:

```
from lib.pupil.pupil_src.shared_modules import camera_models as pl_camera_models
intrinsics = pl_camera_models.load_intrinsics('','Pupil Cam1 ID2',"(1920, 1080)")
x,y = np.meshgrid(range(0,1920,100),range(0,1080,100))
p = np.stack([x.flatten(),y.flatten()],axis=1)

p_unproj = intrinsics.unprojectPoints(p,use_distortion=True)
p_proj = intrinsics.projectPoints(p_unproj,use_distortion=True)


plt.figure()
plt.plot(p[:,0],p[:,1],'go')
plt.plot(p_proj[:,0],p_proj[:,1],'bo')
```

![grafik](https://user-images.githubusercontent.com/10183650/44955224-3f0b9180-aeb0-11e8-9ae4-9d3e91b12a13.png)

I thought the green + blue points should overlay (as is the case for most). Am I doing something wrong?

(trying out a bunch of inputs, I thought the input should be in pixels. Hope that is correct).

PS: For the radial model, I get even stranger results, just try it out and replace 1920 with 1280 and 1080 with 720

**Comment by mkassner** [comment]
@marc-tonsen  is working on this. He will investigate! If im not mistaken our fns are just thin wrappers around the cv2 fns.

**Comment by behinger** [comment]
Upon further thinking, it might be that the distorted edge-points are in the "black" part of the fisheye?

**Comment by marc-tonsen** [comment]
@behinger Your thinking is correct. The (un)distortion functions are only well defined in the central part of the image, the part which you would usually crop after undistortion. Distortion and Undistortion only invert each other within that region. You should see similar behavior for radial distortion.
