### ISSUE TITLE
Pupil Player / Pupil Mobile - Offline Fingertip Calibration

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#1288]
Hi there!

Can you add the fingertip calibration as offline calibration method in Pupil Player (for pupil mobile use).

Best
Freddy

**Comment by mkassner** [comment]
@fneitzel  thats a great idea. @papr  can you have a look?

**Comment by papr** [comment]
I agree. I would like to implement this in the calibration section refactor that we planned.

**Comment by fneitzel** [comment]
Btw. since Im testing the mobile version itm.
1)
Idea:
One has to define calibration ranges for offline calibration in case the marker is more visible than the time the calibration took place. 

It would be great if I can set those ranges by other patterns already, which saves manual processing time to export a final video.

A pattern for start calibration range and stop calibration range, so I don't need to set the calibration manual:

eg: five fingers (start calibration range) followed by (manual) calibration marker and again five fingers (calibration range stop)

In case the pattern of five finger + calibration marker + five fingers shows up again, i will automatically get a new calibration section.

2)
I'm testing fingertip with x230, 8GB, RAM, intel core i7-3520@2.9GHz - Intel HD Graphics 4000, shared memory 1.8GB. 

- If I turn on fingertip calibration my world frames drop to 5 and lower with visualtisation (v) turned off
- I have just visible feedback, if the finger was detected - the well known feedback sound from manual and screen marker calibration is missing - at least I'm missing audio here, to be sure a fingertip position was taken
- Sometimes my face / ear was detected as finger 
- one colored background finds the finger easier
- 5 finger detection works better than one finger detection

However - even with 5 frames the calibration was okay/good - but not as good as with manual marker, referring to uncertainty of missing audio. How much is the 5 frames interfering here?

There is no option to postprocess by offline calibration if I record with 5 frames, so I would choose a manual marker detection and make a fingertip calibration within the video (so I dont have 5 frames) - so I can process the fingertip calibration as soo as an offline fingertip calibration is available.

Here you see - This way I already have two calibrations in my video. Setting up sections manually will be really time consuming. Automatic created sections would be a nice feature.

Sorry for the long text ;) ...

**Comment by papr** [comment]
Fingertip detection has been removed in v1.20
