### ISSUE TITLE
Windows bundle crash on 'no updates' selection

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#129]
And it works on my machine, windows 8, i3, b14hm21.

:)

**Comment by mkassner** [comment]
Cannot replicate...

**Comment by MichaelBarz** [comment]
Cannot replicate...

**Comment by mkassner** [comment]
the window will stop updating (as desired but confusing) but it should
remain responsive and the UI still updates...

**Comment by cpicanco** [comment]
So, you replicate it or not???

**Comment by cpicanco** [comment]
Can't reproduce this with the new bundle.
