### ISSUE TITLE
Pupil Player v.1.8.26 | "Set from trim marks" not working

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#1290]
I can't set a calibration range as well as a mapping range with the button "Set from trim marks"
Nothing happens if I click it. No error in terminal.

- I downgraded on one Ubuntu until v1.4-1
- checked on three computers 2x Ubuntu, 1x windows
- I removed pupil_player_settings 
- I checked with a pupil mobile and a pupil capture recording.

What am I doing wrong? I remember it was working.

**Comment by papr** [comment]
v1.4 does not work for you either? or is v1.4 the first downgrade that worked again?

**Comment by fneitzel** [comment]
I just reinstalled v1.4. Nothing happens if I move the timeline slide and click "Set from trim marks"

**Comment by fneitzel** [comment]
I checked every version until v1.4. then i stopped testing, because v1.3 has the old menu for setting ranges. Do I use the feature wrong?

**Comment by papr** [comment]
Could you make a short screen recording where you demonstrate this bug? I cannot reproduce the issue.

**Comment by papr** [comment]
I am afraid that you are moving the seek handle instead of the trim marks. The trim marks are the left and right round handles enclosing the timeline itself.

**Comment by fneitzel** [comment]
(facepalm) Thank you!
