### ISSUE TITLE
No valid dir supplied (C:\Users\...\pupil_player.exe)

### ISSUE THREAD

**Issue by Pushbeat** [pupil-labs/pupil#1292]
Hi,

I've downloaded the 3 Pupil Labs zips. However, it seems that the Player suddenly won't open (yesterday there was no problem with this). I redownloaded the files. This is the error:

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [ERROR] player_methods: No valid dir supplied (C:\Users\...\pupil_player.exe)

Any ideas? I'm running Windows10 Enterprise.

cheers,
Paul

**Comment by willpatera** [comment]
Hi @Pushbeat It looks like Pupil Player is starting up, and then doesn't open a recording as the directory is not a valid recording. What is the path of the Pupil recording that you are trying to load? Are there any non-ascii chars in the path of the recording that you are trying to load by chance?

**Comment by Pushbeat** [comment]
Thanks, I will check that at the university on monday.

**Comment by Pushbeat** [comment]
Hi Will,

The path to the recordings is C:\Users\discp\recordings (as I can see in the setting in Capture). This map does exist and contains recordings. However, Player seems not be able to find it.

**Comment by papr** [comment]
Hi @Pushbeat, you need to drop one of the recording folders instead of the containing folder. The recordings are 3-digit folders that you can find within the folder named after the recording date.

**Comment by Pushbeat** [comment]
Hello Papr, I can see the map structure. I do have 
C:\Users\discp\recordings\2018_09_07\000
C:\Users\discp\recordings\2018_09_06\000
C:\Users\discp\recordings\2018_09_06\001
I cannot drop into Player, as it wouldn't start (i.e. doesn't open the player window). It stops with the error message.

**Comment by fneitzel** [comment]
Hi Pushbeat,

In the past and with earlier pupil versiond I sometimes had problems if the path was a network drive. 

Did you try to put a recording to a another path?
Did you try to load the recording after deleting pupil_player_settings folder? You can find it in your current Users folder.

**Comment by Pushbeat** [comment]
Deleting the pupil_player_settings folder was the right thing to do. Thanks a lot !

**Comment by papr** [comment]
Thanks @fneitzel for helping @Pushbeat out!
