### ISSUE TITLE
make eye video exporter

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#1294]
Add a plugin to  player that does eye video exports

**Comment by papr** [comment]
Goal: Create a plugin that exports eye videos with their original timing, optionally visualizing pupil detection results.

For reference:
- iMotions background export process: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/imotions_exporter.py#L40
- Correct pts calculation: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/imotions_exporter.py#L78
- Background process creation: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/imotions_exporter.py#L177
- pupil icon font: https://github.com/pupil-labs/pupil-icon-font/
- pupil icon font usage: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/recorder.py#L47-L48
