### ISSUE TITLE
rename exported world video

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#1295]
drop the `_viz` suffix form file.

**Comment by papr** [comment]
Some additional information:
- The exported files should follow this naming:
    - video: `<video name>.mp4`
    - timestamps: `<video name>_timestamps.npy`
- `avoid_overwrite` can be removed since each export gets its own folder by now https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_export_launcher.py#L48
