### ISSUE TITLE
Unable to create heatmaps in offline surface tracking

### ISSUE THREAD

**Issue by Tomw111** [pupil-labs/pupil#1297]
I have tried to get the heatmap function to work in offline surface tracking, but haven’t had any succes thusfar. I haven’t been able to find a solution in online documents or video tutorials, so I was hoping that perhaps you guys can take a look at the steps I’ve taken so far to see if I have missed something. 

I’ve placed the fudicial marks on the side of my monitor and have defined the surface. When I try to calibrate with “manual marker”, I get the notification that not enough data is collected for calibration. 
However: I have been able to let the program detect the markers and the defined surfaces. I have also been able to get the defined surface to appear as blue. 

When I open the player to play back the recording, I get a red notification: “no reference marker data to calibrate session 1”. It further says that it cached the offline calibration data to the destination.
After I made the recording and I try to recalculate the gaze distributions it says there is no gaze on any surface for this section. It also mentions that there is no gaze on the distrubtion.

I hope this is enough information for you guys, if not, please let me know and I'll try to provide additional.

**Comment by marc-tonsen** [comment]
Hi @Tomw111 ! Let me clarify a few things that might be the source of the problem:

Manual marker calibration is for calibrating the gaze estimation pipeline. The surface tracking itself is not influenced by this calibration. To perform gaze calibration the calibration marker is needed, not a surface marker. The error message about not enough data collected for a calibration comes if during a calibration the calibration marker can not be detected in sufficiently many frames.

To generate heatmaps with offline surface tracking your recording needs to either contain a calibration procedure so you can perform a offline calibration to obtain gaze data or already contain gaze data based on a calibration you have performed before starting the recording.
Once you have gaze data you can aggregate it on your surfaces to heatmaps.

**Comment by Tomw111** [comment]
Hi Marc, 

Thanks a lot for your answer. After some trial and error approaces, I've been able to get the heatmap function to work. After using the proper calibration I was still left with another problem however: the defined area where the heatmap was supposed to appear was completely white. In the end what fixed this issue, was clicking - back and forth - the options "show heatmaps" and the other ones, such as "show marker IDs" in the pupillabs player. After a few attempts, the white square dissapears and the heatmap is shown.

**Comment by marc-tonsen** [comment]
I am glad to hear that you managed to generate your heatmaps despite the difficulties. Let me know if you have any other problems!
