### ISSUE TITLE
Error after creating Releases from forked repo

### ISSUE THREAD

**Issue by callummole** [pupil-labs/pupil#1298]
Hi Pupil Labs,

Myself and  @oscartgiles have been doing some development on a forked pupil repo. We are researchers, and wanted to save a snapshot of the code used for piloting, so thought that releases and tags were a good way to go.

However, it seems that after creating a release a strange error appears in pupil capture, copied below:

"world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/venlab/Documents/pupil/pupil_src/launchables/world.py", line 270, in world
    if VersionFormat(session_settings.get("version", '0.0')) != g_pool.version:
  File "/usr/lib/python3.6/distutils/version.py", line 46, in __eq__
    c = self._cmp(other)
  File "/usr/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'

world - [INFO] launchables.world: Process shutting down."

It seems strange that the running of pupil-labs from source would interact with creating releases, as I would not have thought that creating releases alters the code in any way. But I've reproduced this error a few times now by creating releases, so there appears to some interaction.

This probably isn't a pupil-labs issue, but I just wanted to check if you guys have came across this sort of thing before? 

Thanks,

Callum

**Comment by papr** [comment]
How do you create releases?

Please be aware that we use git tags to determine the current version. Is it possible that you created a git tag with non-numeric letters? This would explain why g_pool.version is interpreted as string-version instead of int-version.

**Comment by callummole** [comment]
Ah, that would be it. I used the tag 'Trout_Pilot' (our experiment nickname). 

Thank you!
