### ISSUE TITLE
Task Coordination Procedure

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#1299]
#### Goal
Usage of https://github.com/pupil-labs/pupil/projects/2 for coordination of tasks between Pupil contributers.

#### Procedure
1. Issues that represent isolated tasks are added to `Task Coordination` through the "Projects" selector on the right side of the issue interface.
2. _Contributors_ choose/claim an issue by assigning themselves to it.
3. _Contributors_ push their changes to a new branch in their forked Pupil repository.
    - The branch name should start with the issue number that it tries to fix
    - The branch should be based on the current `master`
4. _Contributors_ create a new PR for their branch and add it to `Task Coordination` through the "Projects" selector on the right side of the issue interface.
5. When the PR is ready for review:
     - _Contributors_ move their PR to the [`Needs Review`](https://github.com/pupil-labs/pupil/projects/2#column-3482622) column via drag & drop. _Contributors_ without permissions to do so should ping one of the _maintainers_ via a PR comment.
    - _Contributors_ add at least two reviewers (e.g. @papr, @emredog, @ckbaumann) to their PR.
6. _Reviewers_ either request changes or approve the PR
7. _Contributors_ work on the requested changes and move their PR back to the [`Needs Review`](https://github.com/pupil-labs/pupil/projects/2#column-3482622) column when they are done.
8. _Maintainers_ merge the PR after all requested reviewers approved the PR.

**Comment by papr** [comment]
```diff
- 5. _Contributors_ add at least two reviewers (e.g. @papr, @emredog, @ckbaumann) to their PR.
+ 5. When the PR is ready for review:
+    - _Contributors_ move their PR to the [`Needs Review`](https://github.com/pupil-labs/pupil/projects/2#column-3482622) column
+    - _Contributors_ add at least two reviewers (e.g. @papr, @emredog, @ckbaumann) to their PR.
```

**Comment by papr** [comment]
```diff
-    - _Contributors_ move their PR to the [`Needs Review`](https://github.com/pupil-labs/pupil/projects/2#column-3482622) column
+    - _Contributors_ move their PR to the [`Needs Review`](https://github.com/pupil-labs/pupil/projects/2#column-3482622) column via drag & drop. _Contributors_ without permissions to do so should ping one of the _maintainers_ via a PR comment.
```

**Comment by papr** [comment]
```diff
-7. _Contributors_ make changes as requested
+7. _Contributors_ work on the requested changes and move their PR back to the [`Needs Review`](https://github.com/pupil-labs/pupil/projects/2#column-3482622) when they are done.
```

**Comment by ckbaumann** [comment]
This now moved to https://docs.google.com/document/d/1TD2vW4vuaiasoCwhnE7TN_ze76CqYTHHob5YEiSHU6g/edit?usp=sharing
