### ISSUE TITLE
Linux Bundle - Pupil Player 0.4.2 - Surface Marker - Heatmaps

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#131]
Pupil Capture: 
- no visible surface marker detection/ no surface marker handling ( i need to know/ i need feedback, if the marker was detected)

Pupil Player: 
- heatmap export broken/ capture closes after button click
- some export files missing?

![show_heatmaps_red](https://cloud.githubusercontent.com/assets/10213803/7198549/9e743a40-e4ed-11e4-9665-e9ec6552a67e.png)

**Comment by mkassner** [comment]
The marker does show in the 'show markers' mode?
Export has been fixed in v0.4.4 : https://github.com/pupil-labs/pupil/releases/tag/v0.4.4

**Comment by fneitzel** [comment]
That was fast ;) Now i see the plugin. Thanks. 
I will check out version 0.4.4.
Can be closed!

**Comment by mkassner** [comment]
ok :-)

**Comment by fneitzel** [comment]
Update: I installed Pupil Player 0.4.4. When i export the heatmap, i  got a red rectangle as png and a lot of files ;) 
Are there any wiki-information about the surface marker plugin yet?
What's supposted to be the output?

**Comment by mkassner** [comment]
hi,

please make sure to set correct sizes for the surfaces. Otherwise they are
sizes 1,1 and thats just one pixel....

M

**Comment by cpicanco** [comment]
For a discussion about heatmaps, take a look at this issue #103
