### ISSUE TITLE
pyrealsense2 video backend

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#1311]
Intel deprecated the R200 and librealsense1. It was replaced with the D400 series and librealsense2. librealsense2 comes with its own Python wrapper: pyrealsense2.

This issue is about creating a pupil video backend that is based on pyrealsense2.

The old realsense backend will still be shipped under the name `Realsense 3d Legacy`

**Comment by papr** [comment]
Please create incremental PRs as discussed to this branch: https://github.com/pupil-labs/pupil/tree/realsense2

**Comment by emredog** [comment]
The progress can be monitored under this [PR](https://github.com/pupil-labs/pupil/pull/1350)

**Comment by emredog** [comment]
We decided to create a project to keep track of related issues and PRs. https://github.com/pupil-labs/pupil/projects/4

**Comment by papr** [comment]
Fixed with #1409
