### ISSUE TITLE
World video not recorded correctly

### ISSUE THREAD

**Issue by buschbapti** [pupil-labs/pupil#1313]
Hello,

I have tried to record videos on the following setup:

- eyetracker connected via pupil mobile app
- receiving computer on Ubuntu 18.04

When using pupil capture everything is fine, all cameras are correctly showing. However when trying to play a recorded clip with pupil player it crashes and nothing loads. I went into a recorded folder and tried to open the video files with vlc. Both eyes videos are ok but the world shows no images. Times of the video is correct but vlc shows just a black screen with its own logo.

I tried on a different computer, also on Ubuntu 18.04, and it produces the same result. Tried the same setup on a mac and it works fine. My guess is there is something wrong with Ubuntu 18.04 but I'm not sure what.

Thanks for your help.

**Comment by papr** [comment]
Hey @buschbapti 
Thank you for reporting this issue. I have just tried to reproduce the issue but was not able to.

Please let us know the following things:
1. Pupil Mobile version
2. Pupil Capture version
3. Pupil Player version
4. Streaming options (default or if changed: concrete changes)

**Comment by papr** [comment]
Closing as Pupil Mobile is no longer maintained and this issue is inactive.
