### ISSUE TITLE
The ability to incorporate world camera Intrinsic Matrix into Pupil Player

### ISSUE THREAD

**Issue by RSKothari** [pupil-labs/pupil#1316]
If we record data using an uncalibrated world camera, then the individual gaze normals for the left and right eye are incorrect. Does anyone know how we could incorporate a World camera Intrinsic matrix during offline calibration through the Pupil player?

**Comment by papr** [comment]
Hey @RSKothari 
You can calibrate your world camera in Capture using the `Camera Intrinsics Estimation` plugin. After successful calibration, this will create an `<world cam name>.intrinsics` file in the `pupil_capture_settings` user folder. It is automatically copied to new recordings and renamed to `world.intrinsics`.

If you need to add calibration after the effect, you can manually copy the file above into your recording folder and rename it to `world.intrinsics`.

**Comment by RSKothari** [comment]
@papr For future information, what default intrinsic matrix value does `world.intrinsics` take up if we haven't calibrated the world camera?

**Comment by papr** [comment]
https://github.com/pupil-labs/pupil/blob/387942addcc9b1589c031cb6affd4a2f7d417408/pupil_src/shared_modules/camera_models.py#L24-L59
