### ISSUE TITLE
Pupil Player not opening

### ISSUE THREAD

**Issue by sbotts** [pupil-labs/pupil#1319]
Hi there,
I was trying to export the data from one of my recordings, but Pupil Player will not open even after I have re-downloaded it. I keep getting ERROR player_methods: No valid dir supplied, but the actual player itself will not open. 

Can you please help me?

**Comment by peteratBHVI** [comment]
Hi sbotts, 

i had a similar issue with the player. Reinstalling helped but it happened again.  I found this on discord from  @papr 

papr10/05/2018
Try the following:
1. Make sure Player is not running
2. look for the pupil_player_settings folder in your user/home directory
3. delete the player_user_settings file
4. start Player(edited)

That helped me. cheers

**Comment by papr** [comment]
It seems like @peteratBHVI comment resolved the issue. I will close it. @sbotts if the issue still persists please comment below.
