### ISSUE TITLE
Update plugin "Accuracy Test"

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#132]
- [x] Update marker rendering following `screen_marker_calibration.py`
- [x] Make controls for speed and marker size following `screen_marker_calibration.py`
- [ ] Error in degrees is computed in a wrong way (degree is not linear to pixel offset!)

**Comment by mkassner** [comment]
I made the plugin inherit most of its members from screen_based_calibration.

**Comment by mkassner** [comment]
now only the error calculation is left.

**Comment by mkassner** [comment]
closed with https://github.com/pupil-labs/pupil/pull/812
