### ISSUE TITLE
Player:   Apply the scene camera intrinsic matrix to the imagery and gaze data upon video export.

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1321]
As far as I understand things, the intrinsic matrix of the scene camera is not used during world video export.  I suggest that you apply the scene camera matrix to the imagery and gaze data upon export.

**Comment by romanroibu** [comment]
This functionality has been released in [v1.6](https://github.com/pupil-labs/pupil/releases/tag/v1.6) via the iMotions Export plugin
