### ISSUE TITLE
Pyglui Window Overlay

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#133]
Active/selected Overlays (Windows) are covered by inactive Overlays. Status is not changing to foreground if selected. 

eg: on the appended I'am working on "Gaze Polyline" which is partlywise hidden by "Gaze Circle"
![overlay](https://cloud.githubusercontent.com/assets/10213803/7204672/6da29678-e524-11e4-9e93-a27311f09cd9.png)

**Comment by mkassner** [comment]
Menus have a fixed Z-order. We do not change it based on selection (focus). This is not because we dont want it but its just not implemented...
