### ISSUE TITLE
Changing resolution for DIY camera

### ISSUE THREAD

**Issue by helei0147** [pupil-labs/pupil#1330]
I'm using a DIY eye camera. I can't get some of the listed resolutions in eye process when there are several available resolutions with the same first dimension(such as 1280x720 and 1280x480, I can't select the second one). I found that function frame_size()  in uvc_backed.py only check the first dimension of frame size. Maybe we can check both the first dimension and the second dimension?

in        pupil/pupil_src/shared_modules/video_capture/uvc_backend.py
line 335         sizes = [abs(r[0]-new_size[0]) for r in self.uvc_capture.frame_sizes]

change it to 
                      sizes = [abs(r[0]-new_size[0])+abs(r[1]-new_size[1]) for r in self.uvc_capture.frame_sizes]

it works for me now.

**Comment by mkassner** [comment]
Thanks for the issue. Would you mind making a PR for that? I would love to merge it.
