### ISSUE TITLE
Cannot Compile on Ubuntu detector_2d.cpython-35m-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by Amahmoud1994** [pupil-labs/pupil#1335]
I am trying to install pupil on Ubuntu 16.04 and I have the following problem:
 
`sudo python3 main.py`

`world - [ERROR] launchables.world: Process Capture crashed with trace:`
`Traceback (most recent call last):`
`File "/home/obad/pupil-1.8/pupil_src/launchables/world.py", line 113, in world`
`import pupil_detectors`
`File "/home/obad/pupil-1.8/pupil_src/shared_modules/pupil_detectors/init.py", line 18, in `
`from .detector_2d import Detector_2D`
`ImportError: /home/obad/pupil-1.8/pupil_src/shared_modules/pupil_detectors/detector_2d.cpython-35m-``x86_64-linux-gnu.so: undefined symbol:` `_ZN2cv12findContoursERKNS_17_InputOutputArrayERKNS_12_OutputArrayEiiNS_6Point_IiEE`

`world - [INFO] launchables.world: Process shutting down.`

I followed the [Linux Dependencies documentation](https://github.com/pupil-labs/pupil-docs/blob/master/developer-docs/linux.md) and did the whole process 3 times already.
I tried to fix it with #658 solutions but still the same problem remains.

Any help?

PS:
I had opencv installed for Realsense sensor but it is the same version as the one from the linux dependencies link. It was **not** installed by `apt-get`.

**Comment by Amahmoud1994** [comment]
The problem was with openCV version 4. I should have used version 3 and it works now after downgrading to version 3.

**Comment by soumilchugh** [comment]
I have been getting a similar error but downgrading the opencv version from 4.0 to 3.4 gives the following error. 
ImportError: libopencv_core.so.4.0: cannot open shared object file: No such file or directory
Is there a fix to this issue?

**Comment by eicm** [comment]
> ImportError: libopencv_core.so.4.0: cannot open shared object file: No such file or directory

It shows you had opencv 4.0 installed on your machine and removed it but your /usr/lib/python3.7/site-packages/cv2/ is still referring to that version(or path-you've-used/python3.7/site-packages/cv2/)
