### ISSUE TITLE
no module named zmq

### ISSUE THREAD

**Issue by valvador92** [pupil-labs/pupil#1338]
I have this error when I try to launch python3 main.py from the terminal:

Traceback (most recent call last):
  File "main.py", line 58, in <module>
    import zmq
ImportError: No module named 'zmq'

I have just cloned the git without doing any changes.

Thank you

**Comment by papr** [comment]
Please follow the developer setup instructions if you want to run from source: https://docs.pupil-labs.com/#running-pupil-from-source

Please be aware, that running from source is rarely necessary. We recommend to use the bundled applications: https://github.com/pupil-labs/pupil/releases
