### ISSUE TITLE
Open the world camera with OpenCv

### ISSUE THREAD

**Issue by valvador92** [pupil-labs/pupil#1339]
I am trying to write my own code. But when I am opening the world camera with OpenCv, the image has distortion because of the lens I think.

I have checked in the files but I didn't find any transformation matrix.

Thank You

**Comment by papr** [comment]
@valvador92 The distortion is expected. Be aware that the 1080p resolution has particularly strong distortion. We recommend to use the 720p resolution. This file contains the code that we use to handle distortion, in particular to load the intrinsics: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/camera_models.py#L62

**Comment by valvador92** [comment]
Thank you. Finally I calibrated it by my own to find the intrinsics to have a better image
