### ISSUE TITLE
Windows bundle - hidden titles on app open

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#134]
But double clicking the window border shows the hidden title, as in any Windows window.

:)

**Comment by cpicanco** [comment]
![both-hidden-title-on-open](https://cloud.githubusercontent.com/assets/6511849/7206895/04f82b78-e50c-11e4-9156-fd514d6958a1.jpg)

**Comment by MichaelBarz** [comment]
Yes, that's certainly a point to improve. I'll look into that...

**Comment by mkassner** [comment]
might it be that we just need to move the windows down a bit?

**Comment by cpicanco** [comment]
Yes, @mkassner, just move the window down.

**Comment by mkassner** [comment]
fixed with windows bundle release 3
