### ISSUE TITLE
Can not execute run_capture.bat

### ISSUE THREAD

**Issue by mehranhussain** [pupil-labs/pupil#1340]
C:\work\pupil\pupil_src>python main.py capture
world - [INFO] launchables.world: Application Version: 1.8.108
world - [INFO] launchables.world: System Info: User: mehran, Platform: Windows, Machine: automaton, Release: 10, Version: 10.0.17134
world - [INFO] pupil_detectors.build: Building extension modules...
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
error: command 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\bin\HostX86\x64\cl.exe' failed with exit status 2
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
File "C:\work\pupil\pupil_src\launchables\world.py", line 113, in world
import pupil_detectors
File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors_init_.py", line 16, in
build_cpp_extension()
File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 25, in build_cpp_extension
ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
File "C:\Python36\lib\subprocess.py", line 336, in check_output
**kwargs).stdout
File "C:\Python36\lib\subprocess.py", line 418, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\Python36\python.exe', 'setup.py', 'install', '--install-lib=C:\work\pupil\pupil_src\shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.
@mehranhussain

Attach files by dragging & dropping,

, or pasting from the clipboard.
Styling with Markdown is supported

**Comment by papr** [comment]
@mehranhussain Please see the hint box below this section: https://docs.pupil-labs.com/#modify-pupil-detectors-setup-py

**Comment by mehranhussain** [comment]
I get the following error when I build from pupil_detectors:

C:\work\pupil\pupil_src\shared_modules\pupil_detectors>python setup.py build
running build
running build_ext
building 'pupil_detectors.detector_2d' extension
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -IC:\Python36\lib\site-packages\numpy\core\include -IC:\work\opencv\build\include -IC:\work\ceres-windows\Eigen -IC:\work\ceres-windows\ceres-solver\include -IC:\work\ceres-windows\glog\src\windows -IC:\work\ceres-windows -IC:\work\boost -I../../shared_cpp/include -Isingleeyefitter/ -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tpdetector_2d.cpp /Fobuild\temp.win-amd64-3.6\Release\detector_2d.obj -D_USE_MATH_DEFINES -std=c++11 -w -O2
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
detector_2d.cpp
Unknown compiler version - please run the configure tests and report the results
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1291): note: see reference to class template instantiation 'std::_Aligned<144,16,double,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1298): note: see reference to class template instantiation 'std::_Aligned<144,16,int,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1305): note: see reference to class template instantiation 'std::_Aligned<144,16,short,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1312): note: see reference to class template instantiation 'std::_Aligned<144,16,char,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1320): note: see reference to class template instantiation 'std::aligned_storage<144,16>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1352): note: see reference to alias template instantiation 'std::aligned_storage_t<144,16>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\type_traits(1357): note: see reference to class template instantiation 'std::aligned_union<1,_Ty>' being compiled
        with
        [
            _Ty=singleeyefitter::Detector2DResult
        ]
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\memory(1820): note: see reference to alias template instantiation 'std::aligned_union_t<1,singleeyefitter::Detector2DResult>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.16.26926\include\memory(1866): note: see reference to class template instantiation 'std::_Ref_count_obj<_Ty>' being compiled
        with
        [
            _Ty=singleeyefitter::Detector2DResult
        ]
c:\work\pupil\pupil_src\shared_modules\pupil_detectors\detect_2d.hpp(76): note: see reference to function template instantiation 'std::shared_ptr<singleeyefitter::Detector2DResult> std::make_shared<singleeyefitter::Detector2DResult,>(void)' being compiled
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Community\\VC\\Tools\\MSVC\\14.16.26926\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by papr** [comment]
Hi @mehranhussain 
Sorry for the very delayed answer. This issue has been fixed before: https://github.com/pupil-labs/pupil/issues/1331#issuecomment-430418074
