### ISSUE TITLE
About sensor size and focal length of world camera

### ISSUE THREAD

**Issue by McNicole** [pupil-labs/pupil#1341]
I want to know the sensor size of the world camera in order to obtain the focal length of the world camera. Where is information on the sensor size listed?
Or how can I calculate sensor size or focal length?

I'd appreciate if you could answer these questions.

**Comment by marc-tonsen** [comment]
The focal length of the camera is part of the camera intrinsics matrix. Default values for the camera intrinsics are available in the [camera_models.py](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/camera_models.py#L24) file. 

If the camera is set to e.g. 1280x720 px resolution, the focal length is 829.35 horizontally and 799.57 vertically. If the relationship between focal length and camera intrinsics is unclear, check out [this](http://ksimek.github.io/2013/08/13/intrinsic/) article.

**Comment by McNicole** [comment]
I was wondering whether the default camera matrix written in camera_models.py will adapt to my pupil labs so I asked a question.

Thank you for answering.

**Comment by marc-tonsen** [comment]
The default values should be roughly accurate for every headset. For increased accuracy you can use the camera intrinsics calibration plugin to compute the exact camera intrinsics of your specific headset! See [this](https://docs.pupil-labs.com/#camera-intrinsics-estimation) section of the docs!

**Comment by McNicole** [comment]
I was able to output Pupil_Cam1_ID2.intrinsics using Camera Intrinsic Estimation.
I think that camera matrices are described in this Pupil_Cam1_ID2.intrinsics, but how can I get camera matrix information inside?

**Comment by marc-tonsen** [comment]
Correct, the file `Pupil_Cam1_ID2.intrinsics` contains calibration information for the world camera. 
The file [file_methods.py](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/file_methods.py) contains a function `load_object`. Using this function you can load the `Pupil_Cam1_ID2.intrinsics` file into Python. It contains a dictionary of similar shape as the `pre_recorded_calibrations` in [camera_models.py](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/camera_models.py).
