### ISSUE TITLE
Pupil Detector install.py, do not assume fixed folders

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#1345]
When trying to compile setup.py in pupil detectors it assumes that opencv, eigen3 etc. are at fixed places.
This is not the case for our setup

I have several ideas how to improve this:
- check if the path exists and throw an error otherwise
-  user specified paths
- auto detect the libraries from the LD_LIBRARY_PATH

**Comment by papr** [comment]
Using pkg-config would be an other option

**Comment by papr** [comment]
This issue has been resolved by extracting the pupil detectors into a separate [repository](https://github.com/pupil-labs/pupil-detectors/) with a proper setup.py procedure.
