### ISSUE TITLE
Pupil detection

### ISSUE THREAD

**Issue by valvador92** [pupil-labs/pupil#1349]
I don't find in which script you are doing your pupil detection. I need to have access of the position of the pupils for a project and I wanted to use your algorithm.

Thank you

**Comment by marc-tonsen** [comment]
Pupil detection is done using the algorithms defined in [this](https://github.com/pupil-labs/pupil/tree/master/pupil_src/shared_modules/pupil_detectors) package. See e.g. [this](https://gist.github.com/marc-tonsen/ccbd5aaa296f5032fd2661f4679ecd06) gist on how to use it.

If you want to have access to pupil positions detected in Pupil Capture in real-time from your own code you can use the [IPC backbone](https://docs.pupil-labs.com/#interprocess-and-network-communication).

You can also export pupil positions offline using Pupil Player, see [here](https://docs.pupil-labs.com/#export).
