### ISSUE TITLE
Windows bundle - memory leak on alt-f4

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#135]
![memory-leak-on-alt-f4](https://cloud.githubusercontent.com/assets/6511849/7206944/3b49e068-e50c-11e4-94b9-ff912c5a12c0.jpg)

**Comment by cpicanco** [comment]
I cannot reproduce this after the first execution.

**Comment by MichaelBarz** [comment]
I cannot reproduce this issue either. I also did not experience a memory loss when using Alt+F4:
![memory_consumption](https://cloud.githubusercontent.com/assets/6330614/7252090/d8a87040-e831-11e4-8e80-ffe1fba6bf2f.png)
