### ISSUE TITLE
Windows bundle - world fps loss while recording

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#136]
From 18-21 to 12-15. I don't know if it is an issue or just a Windows 8 performance drop. Just reporting for your knowledge! For instance, I turned the Windows Search indexer off.

![fps-loss-while-recording](https://cloud.githubusercontent.com/assets/6511849/7207559/a19134f8-e510-11e4-9833-810233b3919b.jpg)
![fps-loss-while-recording-2](https://cloud.githubusercontent.com/assets/6511849/7207560/a1e68af2-e510-11e4-926f-4d1fa9c826c6.jpg)

**Comment by cpicanco** [comment]
And such  fps drop does not seems to occur with the Eye process.

**Comment by cpicanco** [comment]
Changing to gray or no update is kind of a work around on this performance drop, as you can see here #138

**Comment by MichaelBarz** [comment]
I just added caching for frames, in case they are used multiple times. Maybe this helps with the fps loss. Currently this is available with the master-branch only, but an enhanced bundle will come soon.

**Comment by cpicanco** [comment]
Maybe some recommendations for windows users on the wiki ( this could be discussed in another issue of course) could be handy as well. They should care about the  services and process running in the background. Windows Update, Windows search and the Windows Defender is some examples that consume a lot of the disc resources.

**Comment by mkassner** [comment]
This behaviour is not related to the windows bundle. It will always happen when the CPU is not fast enough. In this case a the windows video backend took to much CPU time. The new release should fix that.
