### ISSUE TITLE
Windows bundle - linux separator on recording path

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#137]
![image](https://cloud.githubusercontent.com/assets/6511849/7207637/4fb0005a-e511-11e4-947f-f64634ccf053.png)

**Comment by MichaelBarz** [comment]
I see... this probably happens because we join (python uses linux style) the user's base path (having windows style) with the recording directiory. It should work anyway, but we can certainly improve that!

**Comment by cpicanco** [comment]
It worked anyway, I have confirmed it with the default path.
