### ISSUE TITLE
Offline Detection with QVGA much better than with VGA

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1370]
We have some eye videos which we record in VGA resolution (Vive-Addon). If the human inside the headset tends to have large pupils, the coarse ROI feature of the detector seems to miss the whole pupil area and makes the ROI rectangle too small. Hence, the detector doesn't find any ellipses. I learned that you turned off the feature for QVGA resolution, where the detection is much better. 

Maybe you can tweak some parameters so the coarse detection return some bigger rectangles?

I like the ROI detection, because it makes the intensity range setting so much simpler. But for now we don't want to sacrifice the additional pixel information.

Please test the attached recording (videos in both resolutions supplied)
https://drive.google.com/file/d/148m-hUvGBZlHeueg0XD83CnsP7TuexRi/view?usp=sharing

**Comment by papr** [comment]
You will have the possibility to turn on/off coarse detection, as well as settings coarse detection parameters via #1372
