### ISSUE TITLE
Send underlying 2D detector results within 3D detection

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1371]
Since the 3D detector is not deterministic (small variations in each offline detection) some metrics like quality of recording require a steady result. Secondly, the 3D detector fits the ellipse to the model and slightly alters the center of it. So, for various reasons, it would be great to publish the underlying 2D results when working with the 3D detector in a new dictionary inside the 3D result.

**Comment by papr** [comment]
We are currently reworking the pupil detection pipeline. We will check if the issue still persists before publishing the new pipeline.

**Comment by behinger** [comment]
@mattem86 in the meanwhile you could try to redetect pupil offline & recalibrate as we do [in python here](https://github.com/behinger/etcomp/blob/58ddb084ae079986e0ff2aea8b64af1656e79616/code/functions/nbp_pupildetect.py)
([or already included in a workflow](https://github.com/behinger/etcomp/blob/master/code/functions/et_import.py)

**Comment by papr** [comment]
With Pupil v2.0, we run both detectors at the same time. This way you get access to both, 2d and 3d data.
