### ISSUE TITLE
Make detector properties network-accessible

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1372]
I can set the camera settings when starting the eye process remotely via "start_eye_capture". Now, I would like to set the model sensitivity, intensity range and the min or max pupil size via network.

**Comment by mkassner** [comment]
I think this makes lots of sense. I propose 

topic:notify.detector[2/3]d.set_settings
name: name_of_setting
value: new_value_of_settings

@papr  what do you think?

**Comment by papr** [comment]
@mattem86 fyi, we will implement this.
