### ISSUE TITLE
Pupil Capture not recognizing webcams Windows 10

### ISSUE THREAD

**Issue by popgabriela05** [pupil-labs/pupil#1374]
Hello, I wonder is anyone can help. I have a DIY headset with two webcams. 
I don't see how to connect them to Pupil Capture and I only assume it's because they are not recognized or  there is a drive installation problem. I looked at forums and people seem to recommend unistalling everything under libusbk in the Drive Manager, but in my case, LibUSBK doesn not even show. 
I wonder if it is because the webcams don't need installing, their provided CDs only contain an application file which runs the webcam instantly as you plug it in. 
Please let me know if you can help. Thank you!

**Comment by papr** [comment]
Please refer to this documentation in regard to setting up drivers for DIY headset cameras https://github.com/pupil-labs/pyuvc/blob/master/WINDOWS_USER.md
