### ISSUE TITLE
Extend Pupil Remote to relay messages other then notify.

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#1378]
Current Pupil Remote relays notifications to the IPC. There is no reason to not extend this to other messages as well.

https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/pupil_remote.py#L42

This would make sending annotations to Pupil Capture as easy as it was before v1.9.

**Comment by papr** [comment]
Do you mean annotations? I would argue the opposite, no forwarding at all.

**Comment by papr** [comment]
But how would you differentiate between Pupil Remote API messages (e.g. `R`, `r`, `C`, `c`) and messages whose topic start with one of these letters?

**Comment by papr** [comment]
As discussed with @mkassner:
- Pupil Remote specific commands are zmq-messages with a single frame only
- Messages that are supposed to be forwarded have at least two zmq-frames: topic + payload
