### ISSUE TITLE
Fix missing Pupil software system app icons for Ubuntu 18.04

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#1379]
System icons in the application switcher and in the application menu are missing for Pupil software bundles in Ubuntu 18.04. Please refer to the below two images. 

![screenshot from 2018-11-08 14-08-23](https://user-images.githubusercontent.com/1407224/48182981-ccaba780-e35f-11e8-8724-16796e67d5fe.png)
![screenshot from 2018-11-08 14-08-07](https://user-images.githubusercontent.com/1407224/48182982-ccaba780-e35f-11e8-8fbc-2708227240db.png)

**Comment by papr** [comment]
This is only solved for the world/player process, not for the eye windows. For a long term solution use [`glfwWindowHintString()`](https://www.glfw.org/docs/latest/group__window.html#ga8cb2782861c9d997bcf2dea97f363e5f) with [GLFW_X11_CLASS_NAME](https://www.glfw.org/docs/latest/window_guide.html#GLFW_X11_CLASS_NAME_hint)

**Comment by papr** [comment]
Fixed
