### ISSUE TITLE
No UI/black window in Capture

### ISSUE THREAD

**Issue by burknator** [pupil-labs/pupil#1381]
When installing the latest versions of everything in the developer docs and starting Pupil Capture from master, the window stays black, showing no UI, see attached GIF (sorry for the bad quality, but GitHub wants it under 10MB).

What the video doesn't show, because I can't replicate it, is the very slow responding UI I got when the problem first occured. It seems like activatig "Test image" and fake capture fixed that for me, but changing those settings doesn't seem to recreate the problem of slow UI responsivness. The missing UI problem persists.

macOS version is 10.14.1, Python version is 3.7.1 (installed via Homebrew).

Command line output:

```shell
$ python3 pupil_src/main.py
MainProcess - [INFO] os_utils: Disabled idle sleep.
world - [INFO] launchables.world: Application Version: 1.9.7
world - [INFO] launchables.world: System Info: User: patrick, Platform: Darwin, Machine: the-machine.local, Release: 18.2.0, Version: Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
world - [INFO] pupil_detectors.build: Building extension modules...
world - [INFO] calibration_routines.optimization_calibration.build: Building extension modules...
world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
world - [WARNING] launchables.world: Process started.
world - [INFO] launchables.world: Process shutting down.
MainProcess - [INFO] os_utils: Re-enabled idle sleep.
```

![pupil_no_ui](https://user-images.githubusercontent.com/26658/48256891-3b950900-e411-11e8-8f75-bcc0666b1e5e.gif)

**Comment by mkassner** [comment]
Are you using the default settings? What video backend is active before fake capture is active?

**Comment by burknator** [comment]
Yes, that should be the default settings. It could be that they're from an older version of Pupil though.
Thus, the video backend selected before is the default one, which is Local USB I think?

**Comment by papr** [comment]
I can reproduce the issue on my Mac mini running macOS 10.14.1. After moving the window, everything works as expected.

**Comment by papr** [comment]
The current glfw master contains a fix for this. Unfortunately, they have not made a release that contains the fix yet.

Until the fix is published on homebrew, run this to fix the issue:

```bash
brew unlink glfw
git clone git@github.com:glfw/glfw.git
mkdir glfw/build
cd glfw/build
cmake -DBUILD_SHARED_LIBS=ON ..
make
sudo make install
```
