### ISSUE TITLE
HTC Vive cam doesn't work anymore in pupil v1.9 but worked in v1.8.26

### ISSUE THREAD

**Issue by sbalk** [pupil-labs/pupil#1388]
I ran Pupil Capture v1.8.26 and the HTC Vive cam worked but today I updated to v1.9 (great stuff). The cam is detected but after I select it, Capture shuts down. I connected through USB 3.0 and am running Ubuntu 16.04.

I added the log for reference:
`[DEBUG] uvc: Found device that mached uid:'2:23'`
`[DEBUG] plugin: Plugin <video_capture.uvc_backend.UVC_Source object at 0x7fd9ab0e8550> of base class Base_Source will be replaced by UVC_Source.`
`[DEBUG] plugin: Unloaded Plugin: <video_capture.uvc_backend.UVC_Source object at 0x7fd9ab0e8550>`
`[DEBUG] uvc: Found device that mached uid:'2:23'`
`[DEBUG] uvc: Device '2:23' opended.`
`[DEBUG] uvc: avaible video modes: [{'size': (480, 360), 'rates': [120]}]`
`[DEBUG] uvc: Adding "Auto Exposure Mode" control.`
`[DEBUG] uvc: Adding "Absolute Exposure Time" control.`
`[DEBUG] uvc: Adding "Backlight Compensation" control.`
`[DEBUG] uvc: Adding "Brightness" control.`
`[DEBUG] uvc: Adding "Contrast" control.`
`[DEBUG] uvc: Adding "Gain" control.`
`[DEBUG] uvc: Adding "Power Line frequency" control.`
`[DEBUG] uvc: Adding "Hue" control.`
`[DEBUG] uvc: Adding "Saturation" control.`
`[DEBUG] uvc: Adding "Sharpness" control.`
`[DEBUG] uvc: Adding "Gamma" control.`
`[DEBUG] uvc: Adding "White Balance temperature" control.`
`[DEBUG] uvc: Adding "White Balance temperature,Auto" control.`
`[INFO] video_capture.uvc_backend: Hardware timestamps not supported for HTC Vive. Using software timestamps.`
`[WARNING] video_capture.uvc_backend: %s resolution capture mode not available. Selected [1280, 720].`
`[INFO] camera_models: No user calibration found for camera HTC Vive at resolution (480, 360)`
`[INFO] camera_models: No pre-recorded calibration available`
`[WARNING] camera_models: Loading dummy calibration`
`[WARNING] video_capture.uvc_backend: 30fps capture mode not available at ((480, 360)) on 'HTC Vive'. Selected 120fps. `
`[DEBUG] uvc: Setting mode: 480,360,120`
`[DEBUG] uvc: Stream start.`
`[WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.`
`[DEBUG] uvc: Stream stopped`
`[DEBUG] uvc: Stream closed`
`[DEBUG] uvc: Stream stop.`
`[DEBUG] uvc: UVC device closed.`
`[INFO] video_capture.uvc_backend: Found device. HTC Vive.`
`[DEBUG] uvc: Found device that mached uid:'2:23'`
`[DEBUG] uvc: Device '2:23' opended.`
`[DEBUG] uvc: avaible video modes: [{'size': (480, 360), 'rates': [120]}]`
`[DEBUG] uvc: Adding "Auto Exposure Mode" control.`
`[DEBUG] uvc: Adding "Absolute Exposure Time" control.`
`[DEBUG] uvc: Adding "Backlight Compensation" control.`
`[DEBUG] uvc: Adding "Brightness" control.`
`[DEBUG] uvc: Adding "Contrast" control.`
`[DEBUG] uvc: Adding "Gain" control.`
`[DEBUG] uvc: Adding "Power Line frequency" control.`
`[DEBUG] uvc: Adding "Hue" control.`
`[DEBUG] uvc: Adding "Saturation" control.`
`[DEBUG] uvc: Adding "Sharpness" control.`
`[DEBUG] uvc: Adding "Gamma" control.`
`[DEBUG] uvc: Adding "White Balance temperature" control.`
`[DEBUG] uvc: Adding "White Balance temperature,Auto" control.`
`[INFO] video_capture.uvc_backend: Hardware timestamps not supported for HTC Vive. Using software timestamps.`
`[WARNING] video_capture.uvc_backend: %s resolution capture mode not available. Selected [1280, 720].`
`[INFO] camera_models: No user calibration found for camera HTC Vive at resolution (480, 360)`
`[INFO] camera_models: No pre-recorded calibration available`
`[WARNING] camera_models: Loading dummy calibration`
`[WARNING] video_capture.uvc_backend: 30fps capture mode not available at ((480, 360)) on 'HTC Vive'. Selected 120fps. `
`[DEBUG] uvc: Setting mode: 480,360,120`
`[WARNING] uvc: Could not set Value. 'White Balance temperature'.`
`[DEBUG] uvc: Stream start.`

Could you point me in the right direction?
btw the '...%s resolution...' is now fixed by [c7c7c11](https://github.com/pupil-labs/pupil/commit/c7c7c1104469bacbed90e60803990bdba72a17fe)
Editted for formatting

**Comment by papr** [comment]
My apologies for the lack of response. It is possible that the `HTC Vive` camera not behaving 100% UVC conform. Specifically, the UVC backend expects:
1) [UVC compatible](http://www.cajunbot.com/wiki/images/8/85/USB_Video_Class_1.1.pdf) (Chapters below refer to this document)
2) Support `Video Interface Class Code 0x0E CC_VIDEO` (see A.1)
3) Support `Video Subclass Code 0x02 SC_VIDEOSTREAMING` (see A.2)
4) Support for the `UVC_VS_FRAME_MJPEG (0x07)` video streaming interface descriptor subtype (A.6)
5) Support `UVC_FRAME_FORMAT_COMPRESSED` frame format

Not sure what caused the camera to stop working between v1.8 and v1.9. Please let us know if this is still an issue when using Pupil v2.0.

As this issue is very old, I will close it. We can open it, if the isse persists for the latest version of Pupil.
