### ISSUE TITLE
Eyeball size jumps

### ISSUE THREAD

**Issue by spitschan** [pupil-labs/pupil#1397]
Hi,

I'm running the latest release of the Pupil Player software, and it looks like there are some instabilities with respect to the eyeball diameter. Sometimes, when the participant opens and closes their eye, the eyeball size will change drastically in size. Is there any way that the eye ball size can be pegged or to a specific value?

With thanks

**Comment by peteratBHVI** [comment]
Hi there, 
I do focus point distant measurements and have outliers before and after blink events. could you please advise me where do you spot those instabilities. (I understand that the eye ball diameter is a fixed value and they use it for slippage detection of the eye tracking device, is that true? )  I want to check if I have similar observations. 
cheers Peter

**Comment by papr** [comment]
The eye ball jumping in size is the visible effect of the 3d model trying to adjust based on new data. Unfortunately, the new data may result in worse fits than before if the new data is not widespread enough. Starting with [Pupil v1.15](https://github.com/pupil-labs/pupil/releases/v1.15) you can freeze the eye model to avoid any readjustments of the model.
