### ISSUE TITLE
Question. shared_modules/circle_detector.py

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#14]
Hey, guys.

Have you tried this on line 17?

```
edges = cv2.adaptiveThreshold(gray_img, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 5, -3)
```

Instead,
```
edges = cv2.adaptiveThreshold(gray_img, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 7, 7)
```
Don't know exactly why, but I'm getting better detection and better calibration with subtractions in the C constant.

Could you say something about it? Is there a better way than trial and error to determine these two last values?

Love this project :+1: 

Best,

**Comment by mkassner** [comment]
A quick test did show improved results. New params are part of v0.4 release.
