### ISSUE TITLE
Ubuntu source - performance report

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#140]
Closed
A
![closed-a](https://cloud.githubusercontent.com/assets/6511849/7211054/8bc221ba-e52d-11e4-824b-ba437ce5824c.png)
B
![closed-b](https://cloud.githubusercontent.com/assets/6511849/7211055/8bc4566a-e52d-11e4-8e15-18537873040e.png)

Running (color)
A
![running-color-a](https://cloud.githubusercontent.com/assets/6511849/7211142/555139f8-e52e-11e4-8cb5-16273231e7ec.png)

B
![running-color-b](https://cloud.githubusercontent.com/assets/6511849/7211060/8c1cecd0-e52d-11e4-9a8b-0bfe6fa487ee.png)

Running Rec (color)
A
![running-rec-color-a](https://cloud.githubusercontent.com/assets/6511849/7211057/8bc770a2-e52d-11e4-8754-bb2ca6cf7f73.png)
B
![running-rec-color-b](https://cloud.githubusercontent.com/assets/6511849/7211058/8bc9e7ba-e52d-11e4-90b0-99bd7eebae84.png)

**Comment by cpicanco** [comment]
The windows bundle have a more unstable world process and consumes more resources hum? #138

**Comment by cpicanco** [comment]
Pupil Team, you are my tech heroes! :)

**Comment by mkassner** [comment]
@cpicanco thanks for this report! It nicely compares to #138 and shows that the windows video backend is not yet as efficient as the linux version. We will improve on that! A new release is coming soon.
