### ISSUE TITLE
How can I update Pupil Player to pupil 0.3.9 version  

### ISSUE THREAD

**Issue by popgabriela05** [pupil-labs/pupil#1401]
Hi everyone, 
I have been using the Pupil v1.9 version to record videos and export data. I am now trying to create heat maps and to my understanding, PupilPlayer 0.3.9 is the updated version which allows you to play around with markers and export heat maps. So I downloaded it, but it doesn't seem to work. I opened the Update File and this is what comes up 

<img width="1280" alt="screen shot 2018-11-26 at 10 15 45" src="https://user-images.githubusercontent.com/44746355/49008227-3a7c0f80-f165-11e8-82e9-d628b4b9ad3e.png">

On another note, how can you export actual heat maps? so far i only managed to figure out how to play the recordings in PupilPlayer and export them. I created surfaces using the markers at the corners of my screen and the heat maps show up in Pupil Capture, but i don't know how to save them. Please note that I have little to no understanding of coding. Thanks in advance for your help and patience

**Comment by papr** [comment]
Version 0.3.9 is very old. Please be aware that we do not support downgrading recordings. Pupil Player should export the heatmaps as png files for each defined surface.

**Comment by popgabriela05** [comment]
Thank you. I just noticed the heat map in the Surface folder. It is very small though..is this what it's meant to look like or is there anything that can be adjusted? 

<img width="1280" alt="screen shot 2018-11-26 at 12 49 13" src="https://user-images.githubusercontent.com/44746355/49015086-f47d7680-f179-11e8-9347-b0b705369eec.png">

**Comment by papr** [comment]
You can adjust the size in the surface submenu. Next to the text field where you can name you surfaces.
