### ISSUE TITLE
Image Acquisition in .NET

### ISSUE THREAD

**Issue by solarflarefx** [pupil-labs/pupil#1403]
Hi all,

Is it possible to acquire images from the cameras into a .NET environment?  In particular, I am looking to use the Pupil Labs goggles to do eye tracking on software we have developed in C#.  Has anyone tried this before?  If not, would there be anything preventing this from theoretically working?  Any issues relating to drivers?

**Comment by willpatera** [comment]
Hi @solarflarefx Please see this issue: https://github.com/pupil-labs/pupil/issues/1422#issuecomment-453172646
