### ISSUE TITLE
Test msgpack 0.6.0 compatibility

### ISSUE THREAD

**Issue by Windsooon** [pupil-labs/pupil#1419]
We use [check_code](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/file_methods.py#L23)

```
assert (
    msgpack.version[1] == 5
), "msgpack out of date, please upgrade to version (0, 5, 6 ) or later."
```
which doesn't work when msgpack version is 0.6.0

we can use:

```
from distutils.version import LooseVersion, StrictVersion
assert StrictVersion(msgpack.version) >= StrictVersion("0.5.6")
```
instead

**Comment by papr** [comment]
I did not know that there was a new version. From a quick look, there are backwards in compatible changes that might effect us. This needs to be tested thoroughly.

**Comment by papr** [comment]
There are few changes, that might have an effect on how Pupil runs. For now, we will require version 0.5.6.

Use `pip3 install msgpack==0.5.6` to install the correct version.
