### ISSUE TITLE
Windows bundle 3 - camera settings

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#142]
![image](https://cloud.githubusercontent.com/assets/6511849/7282168/852f2caa-e904-11e4-95bf-079d06e27dc6.png)

Hey guys, for instance, performance was much improved but there is some fps loss with colored screen. I really don't mind about it, since the recording will always be in colors, just reporting for your knowledge.

**Comment by mkassner** [comment]
Yes, texture upload is quite slow on windows for some reason, eating up CPU time.  Your cameras report some strange duplicate frame rates...

**Comment by cpicanco** [comment]
Does it means I need to buy another cameras?? Oh my... hehehehe

**Comment by MichaelBarz** [comment]
This is also due to the media backend. I filter to get distinct values only...

**Comment by MichaelBarz** [comment]
Done. Coming with next bundle...
