### ISSUE TITLE
get_frame() function did not raise EndofVideoError

### ISSUE THREAD

**Issue by Windsooon** [pupil-labs/pupil#1420]
I expect [code](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_capture/file_backend.py#L342) will raise EndofVideoError after the end of the video but it did not.

        try:
            frame = frame or self.get_frame()
        except EndofVideoError:
            logger.info("Video has ended.")
            self.g_pool.seek_control.play = False
            frame = frame or self._recent_frame.copy()

The get\_frame() function will for in self.next_frame to get the next frame, 

        def get_frame(self):
            frame = None
            logged = False
            for frame in self.next_frame:
                ...

it should raise EndofVideoError when 

1. self.next_frame return None, this happens when self.buffering is True and [get\_frame](https://github.com/pupil-labs/PyAV/blob/master/av/buffered_decoder.pyx#L291) yield None, **I'm not familiar with cython, but this didn't happen.**

        def get_frame(self):
            cdef Frame  frame = None
            cdef lib.AVFrame * av_frame
            cdef  double time_before_wait, time_wait
            while True:
                #print("get_frame av_frame = {0:x}".format(<unsigned long>av_frame))
                while self.active_buffer.empty():
                    #print("Waiting for frame...")
                    self.active_buffer.frame_event.wait()
                    self.active_buffer.frame_event.clear()
                    #print("Time for thread switch {}s".format(monotonic() - self.time_event))
                    #print("Got frame ={0:x}".format(<unsigned long>av_frame))

                av_frame = self.active_buffer.get()
                if av_frame is not NULL:
                    self.buffering_sem.release()
                    #frame = alloc_video_frame()
                    #frame.ptr = av_frame
                    frame = wrap_video_frame(av_frame)
                    frame._init_user_attributes()
                    self.buffered_stream.codec_context._setup_decoded_frame(frame)
                    yield  frame
                else:
                    print("av_frame is NULL")
                    yield  None

2. self.timestamps[index] raise IndexError, I guess this only happens **when the timestamps file is broken or somehow didn't match the video.**

**Comment by pfaion** [comment]
This is very outdated and most likely solved by now.
Unfortunately the links are not permalinks so they point to wrong sections now.
But from what I see, the issue has been fixed now, since `File_Source.get_frame()` does proper index checks and raises `EndofVideoError`:
https://github.com/pupil-labs/pupil/blob/bcfbf7d2b03bfbae14788d431fd47fe334e9fe4b/pupil_src/shared_modules/video_capture/file_backend.py#L379-L383
