### ISSUE TITLE
How can I access camera image from my app by using pupil camera

### ISSUE THREAD

**Issue by SevkiBekir** [pupil-labs/pupil#1422]
Hello,

I need to get camera image from pupil camera, but I dont understand clearly how to access camera image from my app. Is there anybody to say me solution? 

My external application is based on C# but I can move my application to python. Just I need easier way to solve it.

Thanks,

**Comment by marc-tonsen** [comment]
Hi @SevkiBekir !
In Pupil we use the UVC library to interact with the cameras. We use the python library [pyuvc](https://github.com/pupil-labs/pyuvc) for that. A minimal code version to open the a camera in python would be:
```python
import uvc
devices = uvc.Device_List()

# Open the first device in the list, let's assume it is an eye camera. 
# Otherwise adapt the frame_size accordingly.
uvc_capture = uvc.Capture(devices[0]["uid"])
uvc_capture.frame_size = (192, 192)
uvc_capture.frame_rate = 30
frame = uvc_capture.get_frame_robust()
```
For more details you can check the [UVC video backend](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_capture/uvc_backend.py) in Pupil.

Alternatively you could also use OpenCV or any other library that supports regular webcams. Our cameras follow the video standards of regular webcams and can be used as such.

**Comment by eicm** [comment]
@marc-tonsen, @papr 
How can I setup the alternative where I get the stream of frames from Pupil Capture in my application? (I want to get the original frames from all the cameras plus 3d gaze informations in my app)

**Comment by marc-tonsen** [comment]
Hi @eicm ! All the data Pupil Capture generates, including the eye and world camera images, can be streamed via ZMQ to the local network. For camera images to be published, the frame publisher plugin has to be enabled. See  [this](https://github.com/pupil-labs/pupil-helpers/blob/master/python/recv_world_video_frames.py) example script on how to use it.
