### ISSUE TITLE
Cannot find opencv

### ISSUE THREAD

**Issue by MenosGrandes** [pupil-labs/pupil#1423]
Hi I have problem with running pupil labs from HEAD source.
```
pupil@pupil-OMEN-by-HP-Laptop-15-ce0xx:~/pupilLab/pupil/pupil_src$ python3 main.py 
world - [INFO] launchables.world: Application Version: 1.10.20
world - [INFO] launchables.world: System Info: User: pupil, Platform: Linux, Machine: pupil-OMEN-by-HP-Laptop-15-ce0xx, Release: 4.15.0-43-generic, Version: #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
world - [INFO] pupil_detectors.build: Building extension modules...
detector_2d.cpp:702:10: fatal error: opencv2/core.hpp: No such file or directory
 #include <opencv2/core.hpp>
          ^~~~~~~~~~~~~~~~~~
```

I have tried to change location of 
```
  opencv_library_dir = "/usr/local/ 
  opencv_include_dir = "/usr/local/include/opencv4/opencv2"` inside _setup.py_ .
```
I have all files inside
```
/usr/local/include/opencv4/opencv2/core.hpp
/usr/local/lib/libopencv_core.so
/usr/local/lib/libopencv_core.so.4.0
/usr/local/lib/libopencv_core.so.4.0.1
```
OpenCV was build from source. In other projects using cmake/make it works.

And why it's assumed that the OpenCV will be installed in` /opt` ?

**Comment by MenosGrandes** [comment]
I don't know why but when I removed opencv2 from opencv_include_dir it worked 
 opencv_include_dir = "/usr/local/include/opencv4/<s>opencv2</s>"

**Comment by JamesSeddon** [comment]
Hi, I'm currently having the same problem but I'm a complete novice when it comes to this sort of thing. Where can I find the file to edit 'opencv_include_dir' ?

**Comment by papr** [comment]
Hi @JamesSeddon that depends on your operating system and how you installed opencv.

**Comment by MenosGrandes** [comment]
@JamesSeddon 
pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py
	    opencv_library_dir = "/usr/local/lib/"
	    opencv_include_dir = "/usr/local/include/opencv4/"

 pupil_src/shared_modules/pupil_detectors/setup.py 
	    opencv_library_dir = "/usr/local/lib/"
	    opencv_include_dir = "/usr/local/include/opencv4/"

You must change those files to make it work.  Of course opencv_invlude_dir is based on yours location of openCV installation.

**Comment by JamesSeddon** [comment]
Thank you so much for a quick reply! I sorted it myself shortly after posting.

I copied opencv2 into "/pupil/pupil_src/shared_cpp/include/"
