### ISSUE TITLE
Calibration and Pupil Mobile?

### ISSUE THREAD

**Issue by olliraa** [pupil-labs/pupil#1425]
Recording with the latest Pupil Mobile works fine, except that the Player shows no gaze data whatsoever :/ The camera feed from all the cameras is shown. Logs say I do not have the calibration data for the eye cameras. How can I calibrate the cameras regarding the Pupil Mobile? I cannot find anything related to calibration in the app. With the Pupil Capture everything works as expected and the recordings have the gaze data also.

**Comment by marc-tonsen** [comment]
Hi @olliraa !
Pupil Mobile does not generate any pupil or gaze data by itself, it can only be used to record or stream the camera feeds. You will have to do offline pupil detection and an offline calibration in Pupil Player to get gaze information (see [here](https://docs.pupil-labs.com/#data-source-plugins)). For this you will have to make sure that a calibration procedure is included in your recordings.
A calibration for the eye cameras is not necessary!

**Comment by olliraa** [comment]
Hi marc-tonsen :)

Thank you for your reply. I understand the concept of offline calibration
and the pupil detection, but for the life of me I don't understand how do I
make sure that there is the calibration procedure in the recording, when
I'm recording with the pupil mobile, which does not have the calibration
function. If the calibration for the eye cameras is not necessary, then I
must calibrate the world camera, right? Could you advise me regarding this?
How can I calibrate it, if I'm not using the Pupil Capture?

Sorry, I must be really stupid :/

All the best,

-Olli

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Ei
viruksia. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

to 10. tammik. 2019 klo 18.49 marc-tonsen (notifications@github.com)
kirjoitti:

**Comment by marc-tonsen** [comment]
No worries Olli, this is not impossible to get confused about! :D 

When I say the calibration procedure has to be included in the recording, what I mean is that the recording has to be running while you execute a calibration, i.e. when the calibration markers are being presented and the subject is gazing at them, this has to be included in the recording. If it is, you can use Pupil Player to detect the markers and perform an offline calibration.

You said Pupil Mobile does not have the calibration function. That is correct, Pupil Mobile can not be used to present a calibration marker. But you can print out a marker and perform a manual marker calibration, or a single marker calibration, simply by presenting the marker and executing the according marker or head movement (please see the docs if you do not know these calibration methods yet). 
If it feels weird to you not to get any feedback about the calibration and the procedure, as you would get in Pupil Capture, you can stream the camera feeds to Capture over wifi and execute a regular calibration in Capture. If Pupil Mobile is recording during that, you will be able to use this procedure for an offline calibration.

I hope this is clearing things up for you! Let me know if you have further questions!

Best,
Marc

**Comment by olliraa** [comment]
Hi Marc :)

Thank you sooo much, I finally "nailed" it :D Woo-hoo! Now just to fine
tune the offset and I'm good to go - literally ;)

All the best,

-Olli

pe 11. tammik. 2019 klo 13.40 marc-tonsen (notifications@github.com)
kirjoitti:

**Comment by marc-tonsen** [comment]
I am glad to hear that! All the best to you too!
