### ISSUE TITLE
Missing World Video (no output)

### ISSUE THREAD

**Issue by chendonis** [pupil-labs/pupil#1426]
Hi @papr ,

I am trying to some experiment on the eye tracker with the mobile app.

I did 4 samples on the same day, however, 3 samples have the correct output (world video, eye videos). For the other 1 sample, it only Cam 2 ID1.

My answer to your question above is 

1. Pupil mobile version: 0.31.0-revert.
2. 200hz binocular High-Speed Eye Tracker
3. Phone: Moto Z3 play that was purchased with the mobile bundle. 

Thank you.

Best regards,
Yimeng

<img width="309" alt="screen shot 2019-01-06 at 18 14 35" src="https://user-images.githubusercontent.com/46416468/50734773-14737180-11df-11e9-8a62-043b55041719.png">

**Comment by willpatera** [comment]
@chendonis Are you recording directly onto the MotoZ3 or are you streaming over WiFi (Pupil Mobile --> Pupil Capture running on desktop/laptop)?

**Comment by chendonis** [comment]
Hi @willpatera, 

Thanks for the reply.

We are recording directly onto the Moto Z3. It turns out that sometimes there is World Video (no eye video), or Eye Video (no World video) or Eye Video & world Video (missing another eye Video).

There is a 10-15% chance of this missing video thing happening, the chance of this happening increases to about 50% if the recording is more than 1 hour.

Best regards,
Yimeng

**Comment by papr** [comment]
Closing as Pupil Mobile is no longer maintained and this issue is inactive.
