### ISSUE TITLE
use Pupil Lab world camera as webcam 

### ISSUE THREAD

**Issue by gladys0313** [pupil-labs/pupil#1429]
Hello! Is it possible to use Pupil Lab world camera as the webcam in **Windows system**? I would like to use the pupil lab world camera as the Vuforia AR camera in Unity3D, and I would also like to use the camera in skype meeting....Is there any special driver that should be installed? Thank you.

**Comment by papr** [comment]
This should possible if you uninstall our libusbk driver for the world camera. Please understand, that you won't be able to use the world camera in Pupil Capture while the libusbk drivers are uninstalled.

**Comment by papr** [comment]
I hope this solved your issue. Let me know if the problem persists and I can reopen the issue.

**Comment by gladys0313** [comment]
Hi, sorry for my late reply. I was on a vacation and just came back to work. 
Could you please reopen the issue? I tried following your instruction but it didn't work. However, I'm not sure if I did it very correctly. I tried to uninstall the driver from device manager in Windows system, but there's no option of "uninstall the driver". Instead, there's only "uninstall the device". After I uninstalled the device, the PC cannot recognize the camera anymore, so it's impossible to use the world camera as a normal PC integrated camera (this is what I want to do...) Do you have any idea?
Thanks a lot.

**Comment by gladys0313** [comment]
Hi,

I left comments on GitHub, but I’m not sure whether you can see it because it’s closed issue, so I write here again:

Hi, sorry for my late reply. I was on a vacation and just came back to work.
Could you please reopen the issue? I tried following your instruction but it didn't work. However, I'm not sure if I did it very correctly. I tried to uninstall the driver from device manager in Windows system, but there's no option of "uninstall the driver". Instead, there's only "uninstall the device". After I uninstalled the device, the PC cannot recognize the camera anymore, so it's impossible to use the world camera as a normal PC integrated camera (this is what I want to do...) Do you have any idea?
Thanks a lot.

Best,
Jing

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
