### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by jhs0053** [pupil-labs/pupil#1430]
Hello. I have a problem in Windows 10 as follows:

2019-01-21 17:48:07,263 - MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
2019-01-21 17:48:17,356 - world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\work\pupil\pupil_src\launchables\world.py", line 113, in world
    import pupil_detectors
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\python.exe', 'setup.py', 'install', '--install-lib=C:\\work\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 1.

anyone knows how to solve this problem?

Thank you.

**Comment by papr** [comment]
Please run `python setup build` directly within the `pupil_detectors` directory to get more feedback regarding the build error.

Also, we usually recommend to run the bundle directly instead of going through the source dependency installation.

**Comment by alpc72** [comment]
@jhs0053 Have solved this problem? I have the same problem

**Comment by jhs0053** [comment]
@papr Thank you for your reply.

@alpc72 I have solved the problem based on papr's comment. however, I have been suffering different problem...

**Comment by alpc72** [comment]
@jhs0053 what's your problem?

**Comment by hang-wang-sys** [comment]
> @jhs0053 Have you solved this problem? I have the same problem
> 
> @papr I run 'python setup build', get the imformation :
> 'C:\software\ceres-windows\ceres-solver\include\ceres/internal/port.h(50): fatal error C1189: #error: One of CERES_USE_OPENMP, CERES_USE_CXX11_THREADS or CERES_NO_THREADS must be defined.'
> 
> Thank you for your answer @papr , I solve this problem by your hint.

你好，我也出现了上述问题，请问您，最后怎么解决port.h的问题的？是因为ceres-solver编译错了吗？折腾了很久，希望能够您的帮助！谢谢

**Comment by hang-wang-sys** [comment]
@alpc72 第一次使用，不知道是不是@错了。I have a problem about 'C:\software\ceres-windows\ceres-solver\include\ceres/internal/port.h(50): fatal error C1189: #error: One of CERES_USE_OPENMP, CERES_USE_CXX11_THREADS or CERES_NO_THREADS must be defined.'  how can I solve it. Thanks very much!

**Comment by pfaion** [comment]
Hi @alpc72 and @hang-wang-sys 

did you follow all steps in the documentation on how to setup windows dependencies?
Note that the setup docs moved to GitHub, I'm referring to this specific section:
https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md#ceres-for-windows

Specifically the part
> Open ceres-2015.sln and with Visual Studio 2017 and agree to update to 2017.
And the following points are important. Not following this correctly could explain the error you are having.

**Comment by hang-wang-sys** [comment]
Thank you for your reply.My VS is 2017 ,and I follow all steps in the documentation,but I have know idea about which step wrong.I tried on Ububntu is success,so I  give up win10 now.  Thanks again for your help!




------------------ 原始邮件 ------------------
发件人: "Patrick Faion"<notifications@github.com>;
发送时间: 2019年10月7日(星期一) 下午5:00
收件人: "pupil-labs/pupil"<pupil@noreply.github.com>;
抄送: "王航"<1034086195@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [pupil-labs/pupil] subprocess.CalledProcessError (#1430)




Hi @alpc72 and @hang-wang-sys
 
did you follow all steps in the documentation on how to setup windows dependencies?
 Note that the setup docs moved to GitHub, I'm referring to this specific section:
 https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md#ceres-for-windows
 
Specifically the part
  
Open ceres-2015.sln and with Visual Studio 2017 and agree to update to 2017.
 And the following points are important. Not following this correctly could explain the error you are having.

**Comment by papr** [comment]
I will close the issue since @pfaion 's instructions should fix the issue. @alpc72 Let us know below if this is not the case for you and we can reopen the issue.
