### ISSUE TITLE
Cannot compile on Ubuntu:detector_2d error

### ISSUE THREAD

**Issue by soumilchugh** [pupil-labs/pupil#1433]
![error](https://user-images.githubusercontent.com/5848676/51714985-fb532900-2004-11e9-9595-6285fd91326d.png)
I have followed all the steps required to build the source code but I am getting the error above. I changed the opencv version from 4 to 3 and then I get the following error 
ImportError: libopencv_core.so.4.0: cannot open shared object file: No such file or directory

Is there a way to fix this ?

**Comment by burknator** [comment]
More of a wild guess, but have you tried to delete all .pyc files?

**Comment by soumilchugh** [comment]
Yes, I did try removing all .pyc files but still gives the same error.

**Comment by mikkeyboi** [comment]
Not sure if you solved this, but I was able to reproduce your error.
Navigate to `pupil/pupil_src/shared_modules/pupil_detectors` and build from there `python3 setup.py build`
After successfully building from there, going back to pupil_src and running `python3 main.py` will work, provided you don't have any build errors elsewhere (ie: calibration_routines/optimization_calibration).

**Comment by papr** [comment]
This issue often indicates an incorrect opencv installation. Please make sure to follow the steps in the documentation https://docs.pupil-labs.com/#install-linux-dependencies
