### ISSUE TITLE
Pass video stream to eye camera

### ISSUE THREAD

**Issue by lukaszog** [pupil-labs/pupil#1438]
Hello,
I am trying to pass video stream from url to Pupil Service eye0. I have connected pupil camera on RasbperryPi and I would like to stream video and receive on pupil service. For this I edit `file_backend.py` and replace:
```
source_path = "http://192.168.8.105:8081/"
self.container = av.open(str(source_path))
```
And commented a lot of lines that produces errors. Finally video does not visible. It is possible? How can I do that?

**Comment by papr** [comment]
Hi @lukaszog Sorry for the delay in response. As the name suggest, the file backend only supports video files. Video streams are not supported. Nonetheless, you can stream video via the ndsi backend. Checkout this example that streams a uvc stream via ndsi: https://github.com/pupil-labs/pyndsi/blob/master/examples/uvc-ndsi-bridge-host.py
