### ISSUE TITLE
issues installing dependencies on Ubuntu 14.04.2

### ISSUE THREAD

**Issue by beasfall** [pupil-labs/pupil#144]
Was attempting to install Pupil from source on a fresh instance of Ubuntu 14.04.2. During the first step of [dependency installation](https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Linux-14.xx), some of the apt-get arguments refused to install.

I no longer have the full error, but I believe it concluded with:
```
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

Seemed to be similar problems to those described [here](http://answers.ros.org/question/203610/ubuntu-14042-unmet-dependencies/) and [here](https://bugs.launchpad.net/ubuntu/+source/mesa-lts-utopic/+bug/1424059); however no work-arounds were effective for me. This be may an issue related to the LTS enablement stack, which is turned on by default in 14.04.2 but not in 14.04.1

Wiped the hard drive, installed [Ubuntu 14.04.1](http://old-releases.ubuntu.com/releases/trusty/), and the dependencies installed successfully.

**Comment by cpicanco** [comment]
Hi, welcome to the community. You have tried a fresh instance with or without updates? For instance, I recently moved from Lubuntu 14.0.2 LTS to Ubuntu 14.0.2 LTS. Some troubles with Lubuntu, but Pupil is running smooth and nice with Ubuntu (with updates) from source.

**Comment by beasfall** [comment]
Hi, thanks!

14.04.2 was fully updated using the default configuration before I tried installing the dependencies, and I believe this included LTS enablement stack updates. Perhaps there was something unique about my setup.

**Comment by beasfall** [comment]
Could have been user-error, too. I updated from the GUI, but maybe I needed to run `apt-get update` from the command-line also? I'm relatively new to linux.

**Comment by cpicanco** [comment]
I have used the GUI as well, the `update-manager`. Also checked the "download updates" in the ubuntu-14.04.2-desktop-amd64.iso installation manager.

Best!

**Comment by mkassner** [comment]
whats the status on this? Can we close it?

**Comment by beasfall** [comment]
It seems not consistently reproducible. However if anyone else runs into the issue, perhaps they'll find this ticket helpful.
