### ISSUE TITLE
Pupil data and gaze data generating process

### ISSUE THREAD

**Issue by kk94wang** [pupil-labs/pupil#1445]
Hi,
I'm trying to do some work to improve accuracy on my records.
I find the gaze_producer.py and pupil_producer.py ,but there is no detailed comment about how to use these.
Cloud you please give some instructions on how to use these functions or how pupil capture generate pupil_position/gaze_position data?
Thank you!

**Comment by papr** [comment]
If you just want the data you can export it to csv using the raw data exporter. See the docs for details.

What type of accuracy do you want to improve? The Pupil detection? The calibration? The producer classes are Player plugins to generate pupil and gaze data offline. But they reuse the algorithms run by Capture. Depending on what you want to improve, you would have to look in different places.

**Comment by kk94wang** [comment]
Yes, I’ve export the raw data, and I’m trying to improve calibrations. How can I regenerate the norm_x/y with pupil position data?

**Comment by papr** [comment]
The gaze mapper parameters are fitted her: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/finish_calibration.py

The actual gaze mapping happens here: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/gaze_mappers.py

**Comment by kk94wang** [comment]
Thank you very much!
