### ISSUE TITLE
Windows - run from source in a conda env

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/pupil#1446]
I'm working towards a MUCH easier way to install and run pupil from source on Windows.

Assuming you already have miniconda installed and an Anaconda Prompt window open,

* `conda create -n pupil`
* `conda activate pupil`
* `conda install numpy scipy cython ipython matplotlib opencv pyopengl psutil portaudio pyzmq boost msgpack-python glew glfw ffmpeg eigen win_inet_pton pytorch python=3.6 -c pytorch`
* `pip install pyaudio`
* `pip install git+https://github.com/zeromq/pyre.git`
* `pip install --upgrade https://github.com/pupil-labs/pyglui/releases/download/v1.23/pyglui-1.23-cp36-cp36m-win_amd64.whl`
* `pip install --upgrade https://github.com/pupil-labs/PyAV/releases/download/v0.4.2/av-0.4.2.dev0-cp36-cp36m-win_amd64.whl`
* `pip install --upgrade https://github.com/pupil-labs/pyndsi/releases/download/v0.4/ndsi-0.4-cp36-cp36m-win_amd64.whl`
* `pip install --upgrade https://github.com/pupil-labs/pyuvc/releases/download/v0.13/uvc-0.13-cp36-cp36m-win_amd64.whl`

Some notes:
* ipython and matplotlib are not necessary but I find them useful for debugging.
* The exact versions and URLs for the pupil-labs dependencies is likely to change from what they are now.

By following these instructions, you'll get ALMOST everything pupil needs.
Where `<env>` is your path to the new conda environment, `<env>/Library/include`, `<env>/Library/lib` has your build dependencies. and `<env>/Library/bin` has your DLLs. The `bin` directory is on the PATH when activating the conda environment so there's no need to copy DLLs around.

We still need `ceres-solver` and unfortunately I was unable to find any precompiled binaries. The instructions below follow closely the instructions on the Pupil Docs, except we use Eigen that was downloaded with conda, and we copy the libs and includes into the conda env. The good news about the below instructions is that if anyone ever decides to make a ceres-solver conda package for Windows then we can simply delete these instructions and add ceres-solver to the list of installed packages above.

* `git clone --recursive https://github.com/tbennun/ceres-windows.git`
* `copy ceres-windows\ceres-solver\config\ceres\internal\config.h ceres-windows\ceres-solver\include\ceres\internal\`
* From file explorer, rt-click on ceres-windows\ceres-2015.sln and open with visual studio 2017
    * Click OK to upgrade if prompted
* Change the deploy target to `Release` `x64` using the dropdown menus at the top.
* Right-click on the `ceres_static` project and choose properties
* under `Configuration Properties > C/C++ > General`, edit the `Additional Include Directories`.
    * Modify the Eigen folder and find the root in your conda environment.
    For me this was `C:\Users\Chad\.conda\envs\pupil\Library\include\eigen3`. (Hint:
    you can find your conda environment with `conda info --envs`).
* Right-click on `ceres_static` again and choose build.
* Copy the .lib files from ceres-windows\x64\Release to the `<conda_env>\Library\lib` folder.
* Copy the `ceres` folder from `ceres-windows\ceres-solver\include` to `<conda_env>\Library\include`
* Copy the `glog` folder from `ceres-windows\glog\src\windows` to `<conda_env>\Library\include` 

I also had to follow the fix described [here](https://github.com/pupil-labs/pupil/issues/1331#issuecomment-430418074).

**Comment by cboulay** [comment]
The above instructions are now complete and I made a pull request with the required changes to setup.py to enable building with these instructions.

**Comment by cboulay** [comment]
It turns out that vcpkg has ceres (`vcpkg install ceres:x64-windows-static`). Great!

But I'm running into some new problems that I didn't encounter on my home computer. i.e. it's trying to link against boost-vc141 even though vcpkg and conda install 140. I guess this didn't happen at home.

After I have instructions that work on both computers then I'll update here.

**Comment by cboulay** [comment]
Closing in favor of #1455

**Comment by XandeUlsonQMedia** [comment]
Hello @cboulay ,

I have followed all the steps but Pupil Capture is throwing the error: throwing

world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.

I don't know if i have skipped any step or if is a problem with something else. Did you have the same problem or know where can i beggin fixing it?

Thanks,
Alexandre

**Comment by cboulay** [comment]
Hi @XandeUlsonQMedia , please use the instructions in #1455 . This issue is outdated.
