### ISSUE TITLE
Linux Bundle - allow * on server address

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#145]
Hi, I am having difficulties trying to insert a `*` in the address, to broadcast over the lan (in my case between computers), for example

    tcp://*:5020

It keeps returning the local host `127.0.0.1` instead.

Best.

**Comment by mkassner** [comment]
Hi,

I can do:

`tcp://*:5000` on both linux and mac.

if ftp a typo?

**Comment by cpicanco** [comment]
yes!! it is a typo

**Comment by mkassner** [comment]
since it works on my machine and not on yours it must have to do with network setup. Is that port already bound? Does the log say anything?

**Comment by cpicanco** [comment]
So, just exchange to `5000` should work?

**Comment by cpicanco** [comment]
Well, it works!! Why not with `5020`? I was using it from source, with no problems, but can't do it in runtime.

**Comment by cpicanco** [comment]
Here is the log, not much informative though.
```
World Process: 2015-04-24 14:18:18,781 - video_capture - WARNING - Found ['HD Webcam C615'] as devices that match the src string pattern Using the first match.
World Process: 2015-04-24 14:18:18,785 - video_capture.linux_video - INFO - Capture device: 'HD Webcam C615' is not known to support HW timestamping. Using software timestamps.
World Process: 2015-04-24 14:18:18,785 - video_capture.linux_video - INFO - Capture device: 'Microsoft® LifeCam HD-5000' detected as attached device. Falling back to software timestamps
World Process: 2015-04-24 14:18:18,907 - video_capture - INFO - Camera selected: HD Webcam C615  with id: 0
World Process: 2015-04-24 14:18:19,148 - plugin - INFO - Loading plugin: Dummy_Gaze_Mapper with settings {}
World Process: 2015-04-24 14:18:19,149 - plugin - INFO - Loading plugin: Screen_Marker_Calibration with settings {'fullscreen': True, 'menu_conf': {'collapsed': True, 'pos': (0.0, 0.0), 'size': [0.0, 0]}, 'marker_scale': 1.0}
World Process: 2015-04-24 14:18:19,151 - plugin - INFO - Loading plugin: Display_Recent_Gaze with settings {}
World Process: 2015-04-24 14:18:19,151 - plugin - INFO - Loading plugin: Recorder with settings {'menu_conf': {'collapsed': False, 'pos': (0.0, 0.0), 'size': [0.0, 0]}, 'info_menu_conf': {}, 'record_eye': 1, 'user_info': {'name': '', 'additional_field': 'change_me'}, 'audio_src': 'C615 [HD Webcam C615]', 'session_name': '2015_04_23', 'show_info_menu': 1}
World Process: 2015-04-24 14:18:19,168 - plugin - INFO - Loading plugin: Pupil_Server with settings {'menu_conf': {'collapsed': False, 'pos': (0.0, 0.0), 'size': [0.0, 0]}, 'address': 'tcp://127.0.0.1:5020'}
World Process: 2015-04-24 14:22:15,873 - pupil_server - ERROR - Could not set Socket: tcp://*:5020
World Process: 2015-04-24 14:22:25,926 - world - INFO - Process closing from window
World Process: 2015-04-24 14:22:25,959 - video_capture.linux_video - INFO - Capture released
```

**Comment by mkassner** [comment]
World Process: 2015-04-24 14:22:15,873 - pupil_server - ERROR - Could not set Socket: tcp://*:5020


indicates that ZMQ cannot set the socket. Is it already used?

**Comment by cpicanco** [comment]
Well, how can I check if it is in use? As you can see, the socket was setup to `127.0.0.1:5020` at first, maybe pupil it self was using it. I remember that I was able to change to `*:5000` but not to `*:5020`.  I need to test again.

**Comment by cpicanco** [comment]
The logger will not log a socket successfully changed, only errors, is that right?

**Comment by mkassner** [comment]
Yes that's right.

**Comment by mkassner** [comment]
so * refers to localhost which is often also 127.0.0.1 from what I know. 

Going from 127.0.0.1:5000 to *:5000 and receiving a cannot open port message makes sense then, right?

M

**Comment by cpicanco** [comment]
Yep, its behaving exactly like this. 

     [host]:[port]

 If you already created a socket, then you must change the port number first, before changing the host to * . So a better implementation should free the socket before trying to create a new socket.

**Comment by mkassner** [comment]
agreed and fixed.
