### ISSUE TITLE
Any reason that HMD_Calibration 2D,2-eye uses Dual_Monocular_Gaze_Mapper instead of Binocular_Gaze_Mapper?

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/pupil#1451]
Is there any reason that HMD_Calibration (2D, 2-eye) uses Dual_Monocular_Gaze_Mapper instead of Binocular_Gaze_Mapper?

Even when Dual_Monocular_Gaze_Mapper is used, in hmd-eyes the individual eyes are averaged to get the gaze position [here](https://github.com/pupil-labs/hmd-eyes/blob/master/unity_pupil_plugin_vr/Assets/pupil_plugin/Scripts/Networking/PupilData.cs#L215-L218). This is approximately equivalent to the `Binocular_Gaze_Mapper multivariate=False` mapper.

But what about the Binocular - multivariate version?
Even outside of the HMD context, do you have any intuition as to whether the Binocular - multivariate version (default) is better than the Binocular - mean-of-eyes version?

Wouldn't it be better to let pupil service handle the gaze-calculation than to have hmd-eyes default to taking the mean of the fetched mono-eye positions?

**Comment by papr** [comment]
At that time, the idea was to map pupil data for each eye separately for each of the two VR-screens. This idea has been revised during the hmd-eyes rework. hmd-eyes 1.0 uses binocular 3d mapping by default.
