### ISSUE TITLE
Lost eye0 Recording

### ISSUE THREAD

**Issue by husathap** [pupil-labs/pupil#1454]
I currently have an issue of obtaining video from eye0. First, I have to install the drivers multiple times using all of the methods (including resetting pupil) in order to get the both cameras working. However, when I testing out the device yesterday with the pupil-hmd plugin on Unity, eye0's driver is simply gone during the test. I checked Pupil Capture and found that the driver was replaced with "unknown."

My device is installed on Windows 10.

**Comment by papr** [comment]
Hi. Windows Updates are known for resetting the camera drivers to their default, effectively reverting the installed Pupil Labs drivers. You will have to repeat the driver installation.

**Comment by husathap** [comment]
This is not Windows 10 issue, because I attempted the re-installation for numerous times. I tried to reinstall the driver about 4-5 times yesterday. There was also the issue of the driver disappearing while the device was being used.

**Comment by papr** [comment]
OK, I misunderstood your initial post. Do I understand correctly that you do not have any issues with eye1?

**Comment by husathap** [comment]
There doesn't seem to be any issue with eye1. My supervisor suspects that there might be issues with the cable. However, I find many people also have issues with eye0, so I wonder if this could be a software problem as well.

**Comment by papr** [comment]
To be honest, a problem with the cable is my suspicion as well. Please contact info@pupil-labs.com referring this issue for hardware support.
