### ISSUE TITLE
Capture: Mac OS Crash on startup; ImporterError pyglui

### ISSUE THREAD

**Issue by JamesSeddon** [pupil-labs/pupil#1457]
HI, this morning I loaded Pupil Capture from source for the first time and got it up and running. I then followed the plugin tutorial for hacking a copy of vis_circle.

I then attempted to boot up capture again and I receive an import error of:

"cannot import name 'ui' from 'pyglui' (unknown location)" on line 113 of world.py

I have attempted re-cloning and reinstalling pyglui, but that also fails which I have raised in a separate issue in the pyglui repo. 

Any help would be greatly appreciated, thanks!

**Comment by papr** [comment]
Hi @JamesSeddon 
You do not need to run from source to develop a plugin. Just use the bundled application until https://github.com/pupil-labs/pyglui/issues/104 is fixed. You can find the bundled applications here: https://github.com/pupil-labs/pupil/releases

Place your plugins in `~/pupil_player_settings/plugins`.
