### ISSUE TITLE
Menu opens when sending remote commands

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1459]
I like to have the menus closed, but when I send remote controls like detection mode or camera settings the menu keeps popping up. Is there an easy way to „fix“ this?

**Comment by papr** [comment]
What happens here is that a new plugin instance is started and their menus are opened by default. You can fix it by modify the source code and setting `menu.collapsed = True` after initializing the menu. This would need to be repeated for all plugin menus.
