### ISSUE TITLE
plugin failed to load in bundled version of pupil capture

### ISSUE THREAD

**Issue by sonny07** [pupil-labs/pupil#1464]
I created a plugin and ran it with bundled version of Pupil Capture, but it failed to load it. The warning said that my opencv doesn't have dnn, but that is not true. I have opencv4 which should have dnn on it. I also ran the same plugin in the source and it worked perfectly. So, I'm just wondering if there is a way to fix this warning while running it on the bundled version.

> world - [WARNING] plugin: Failed to load 'Object_Detection'. Reason: 'module 'cv2' has no attribute 'dnn''

**Comment by papr** [comment]
Hi @sonny07 
The bundle runs in an isolated environment with a copy of all needed libraries and modules. It includes opencv3. Therefore, the `cv2` that you load in the bundle is a different one than when running from source. We are planning on transitioning to opencv4 in the future: https://github.com/pupil-labs/pupil/issues/1437
