### ISSUE TITLE
AttributeError: 'Global_Container' object has no attribute 'min_calibration_confidence'

### ISSUE THREAD

**Issue by jhs0053** [pupil-labs/pupil#1471]
Hello. I have a problem in Windows 10 as follows:

world - [ERROR] launchables.world: Process Capture crashed with trace:
 Traceback (most recent call last):
   File "C:\work\pupil\pupil_src\launchables\world.py", line 383, in world
     g_pool.plugins = Plugin_List(g_pool, session_settings.get('loaded_plugins', default_plugins))
   File "C:\work\pupil\pupil_src\shared_modules\plugin.py", line 294, in __init__
     self.add(plugin_by_name[name], args)
   File "C:\work\pupil\pupil_src\shared_modules\plugin.py", line 330, in add
     plugin_instance.init_ui()
   File "C:\work\pupil\pupil_src\shared_modules\calibration_routines\screen_marker_calibration.py", line 114, in init_ui
     super().init_ui()
   File "C:\work\pupil\pupil_src\shared_modules\calibration_routines\calibration_plugin_base.py", line 100, in init_ui
     self.add_menu()
   File "C:\work\pupil\pupil_src\shared_modules\calibration_routines\calibration_plugin_base.py", line 57, in add_menu
     label='Minimum calibration confidence'))
   File "pyglui\ui_elements.pxi", line 90, in pyglui.ui.Slider.__cinit__
   File "pyglui\ui_elements.pxi", line 508, in pyglui.ui.Text_Input.__cinit__
   File "pyglui\ui.pyx", line 327, in pyglui.ui.Synced_Value.__init__
 AttributeError: 'Global_Container' object has no attribute 'min_calibration_confidence'

anyone knows how to solve this problem?

Thank you.

**Comment by papr** [comment]
Please run `git describe --long` and `git diff` within your pupil repository and paste the output. Also, do you have any custom plugins running?

**Comment by jhs0053** [comment]
@papr my output is as:

C:\work\pupil>git diff
 warning: LF will be replaced by CRLF in pupil_src/launchables/world.py.
 The file will have its original line endings in your working directory.
 diff --git a/pupil_src/launchables/world.py b/pupil_src/launchables/world.py
 index 5bd5e309..72eb772f 100644
 --- a/pupil_src/launchables/world.py
 +++ b/pupil_src/launchables/world.py
 @@ -1,7 +1,7 @@
  '''
  (*)~---------------------------------------------------------------------------
 Pupil - eye tracking platform
 -Copyright (C) 2012-2018 Pupil Labs
 +Copyright (C) 2012-2017  Pupil Labs

 Distributed under the terms of the GNU
  Lesser General Public License (LGPL v3.0).
 @@ -66,7 +66,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
      logging.getLogger("OpenGL").setLevel(logging.ERROR)
      logger = logging.getLogger()
      logger.handlers = []
 -    logger.setLevel(logging.NOTSET)
 +    # logger.setLevel(logging.DEBUG)
      logger.addHandler(zmq_tools.ZMQ_handler(zmq_ctx, ipc_push_url))
      # create logger for the context of this function
      logger = logging.getLogger(__name__)
 @@ -96,7 +96,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          import glfw
          from version_utils import VersionFormat
          from pyglui import ui, cygl, __version__ as pyglui_version
 -        assert VersionFormat(pyglui_version) >= VersionFormat('1.21'), 'pyglui out of date, please upgrade to newest ve:...skipping...
 warning: LF will be replaced by CRLF in pupil_src/launchables/world.py.
 The file will have its original line endings in your working directory.
 diff --git a/pupil_src/launchables/world.py b/pupil_src/launchables/world.py
 index 5bd5e309..72eb772f 100644
 --- a/pupil_src/launchables/world.py
 +++ b/pupil_src/launchables/world.py
 @@ -1,7 +1,7 @@
  '''
  (*)~---------------------------------------------------------------------------
 Pupil - eye tracking platform
 -Copyright (C) 2012-2018 Pupil Labs
 +Copyright (C) 2012-2017  Pupil Labs

 Distributed under the terms of the GNU
  Lesser General Public License (LGPL v3.0).
 @@ -66,7 +66,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
      logging.getLogger("OpenGL").setLevel(logging.ERROR)
      logger = logging.getLogger()
      logger.handlers = []
 -    logger.setLevel(logging.NOTSET)
 +    # logger.setLevel(logging.DEBUG)
      logger.addHandler(zmq_tools.ZMQ_handler(zmq_ctx, ipc_push_url))
      # create logger for the context of this function
      logger = logging.getLogger(__name__)
 @@ -96,7 +96,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          import glfw
          from version_utils import VersionFormat
          from pyglui import ui, cygl, __version__ as pyglui_version
 -        assert VersionFormat(pyglui_version) >= VersionFormat('1.21'), 'pyglui out of date, please upgrade to newest version'
 +        assert VersionFormat(pyglui_version) >= VersionFormat('1.9'), 'pyglui out of date, please upgrade to newest version'
          from pyglui.cygl.utils import Named_Texture
          import gl_utils

@@ -116,10 +116,13 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          # Plug-ins
          from plugin import Plugin, System_Plugin_Base, Plugin_List, import_runtime_plugins
          from plugin_manager import Plugin_Manager
 +
          from calibration_routines import calibration_plugins, gaze_mapping_plugins, Calibration_Plugin, Gaze_Mapping_Plugin
 +        from object_detector_app import Object_Detection
 +
          from fixation_detector import Fixation_Detector
          from recorder import Recorder
 -        from display_recent_gaze import Display_Recent_Gaze
 +        from display_recent_gaze_2 import Display_Recent_Gaze
          from time_sync import Time_Sync
          from pupil_remote import Pupil_Remote
          from pupil_groups import Pupil_Groups
 @@ -134,10 +137,11 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          from remote_recorder import Remote_Recorder
          from audio_capture import Audio_Capture
          from accuracy_visualizer import Accuracy_Visualizer
 +        #from vis_circle import Vis_Circle  #custom plugin
 +
          # from saccade_detector import Saccade_Detector
          from system_graphs import System_Graphs
          from camera_intrinsics_estimation import Camera_Intrinsics_Estimation
 -        from hololens_relay import Hololens_Relay

         # UI Platform tweaks
          if platform.system() == 'Linux':
 @@ -145,7 +149,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
              window_position_default = (30, 30)
          elif platform.system() == 'Windows':
              scroll_factor = 10.0
 -            window_position_default = (8, 90)
 +            window_position_default = (8, 31)
          else:
              scroll_factor = 1.0
              window_position_default = (0, 0)

I have added object_detection_app and world.py in the code provided by the site below to original pupil repository provided by the pupil labs and executed run_caputure_bat in my pupil repository.
I have modified several errors and got above error.

**Comment by jhs0053** [comment]
@papr my output is as:

C:\work\pupil>git diff
 warning: LF will be replaced by CRLF in pupil_src/launchables/world.py.
 The file will have its original line endings in your working directory.
 diff --git a/pupil_src/launchables/world.py b/pupil_src/launchables/world.py
 index 5bd5e309..72eb772f 100644
 --- a/pupil_src/launchables/world.py
 +++ b/pupil_src/launchables/world.py
 @@ -1,7 +1,7 @@
  '''
  (*)~---------------------------------------------------------------------------
 Pupil - eye tracking platform
 -Copyright (C) 2012-2018 Pupil Labs
 +Copyright (C) 2012-2017  Pupil Labs

 Distributed under the terms of the GNU
  Lesser General Public License (LGPL v3.0).
 @@ -66,7 +66,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
      logging.getLogger("OpenGL").setLevel(logging.ERROR)
      logger = logging.getLogger()
      logger.handlers = []
 -    logger.setLevel(logging.NOTSET)
 +    # logger.setLevel(logging.DEBUG)
      logger.addHandler(zmq_tools.ZMQ_handler(zmq_ctx, ipc_push_url))
      # create logger for the context of this function
      logger = logging.getLogger(__name__)
 @@ -96,7 +96,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          import glfw
          from version_utils import VersionFormat
          from pyglui import ui, cygl, __version__ as pyglui_version
 -        assert VersionFormat(pyglui_version) >= VersionFormat('1.21'), 'pyglui out of date, please upgrade to newest ve:...skipping...
 warning: LF will be replaced by CRLF in pupil_src/launchables/world.py.
 The file will have its original line endings in your working directory.
 diff --git a/pupil_src/launchables/world.py b/pupil_src/launchables/world.py
 index 5bd5e309..72eb772f 100644
 --- a/pupil_src/launchables/world.py
 +++ b/pupil_src/launchables/world.py
 @@ -1,7 +1,7 @@
  '''
  (*)~---------------------------------------------------------------------------
 Pupil - eye tracking platform
 -Copyright (C) 2012-2018 Pupil Labs
 +Copyright (C) 2012-2017  Pupil Labs

 Distributed under the terms of the GNU
  Lesser General Public License (LGPL v3.0).
 @@ -66,7 +66,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
      logging.getLogger("OpenGL").setLevel(logging.ERROR)
      logger = logging.getLogger()
      logger.handlers = []
 -    logger.setLevel(logging.NOTSET)
 +    # logger.setLevel(logging.DEBUG)
      logger.addHandler(zmq_tools.ZMQ_handler(zmq_ctx, ipc_push_url))
      # create logger for the context of this function
      logger = logging.getLogger(__name__)
 @@ -96,7 +96,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          import glfw
          from version_utils import VersionFormat
          from pyglui import ui, cygl, __version__ as pyglui_version
 -        assert VersionFormat(pyglui_version) >= VersionFormat('1.21'), 'pyglui out of date, please upgrade to newest version'
 +        assert VersionFormat(pyglui_version) >= VersionFormat('1.9'), 'pyglui out of date, please upgrade to newest version'
          from pyglui.cygl.utils import Named_Texture
          import gl_utils

@@ -116,10 +116,13 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          # Plug-ins
          from plugin import Plugin, System_Plugin_Base, Plugin_List, import_runtime_plugins
          from plugin_manager import Plugin_Manager
 +
          from calibration_routines import calibration_plugins, gaze_mapping_plugins, Calibration_Plugin, Gaze_Mapping_Plugin
 +        from object_detector_app import Object_Detection
 +
          from fixation_detector import Fixation_Detector
          from recorder import Recorder
 -        from display_recent_gaze import Display_Recent_Gaze
 +        from display_recent_gaze_2 import Display_Recent_Gaze
          from time_sync import Time_Sync
          from pupil_remote import Pupil_Remote
          from pupil_groups import Pupil_Groups
 @@ -134,10 +137,11 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
          from remote_recorder import Remote_Recorder
          from audio_capture import Audio_Capture
          from accuracy_visualizer import Accuracy_Visualizer
 +        #from vis_circle import Vis_Circle  #custom plugin
 +
          # from saccade_detector import Saccade_Detector
          from system_graphs import System_Graphs
          from camera_intrinsics_estimation import Camera_Intrinsics_Estimation
 -        from hololens_relay import Hololens_Relay

         # UI Platform tweaks
          if platform.system() == 'Linux':
 @@ -145,7 +149,7 @@ def world(timebase, eyes_are_alive, ipc_pub_url, ipc_sub_url,
              window_position_default = (30, 30)
          elif platform.system() == 'Windows':
              scroll_factor = 10.0
 -            window_position_default = (8, 90)
 +            window_position_default = (8, 31)
          else:
              scroll_factor = 1.0
              window_position_default = (0, 0)


I have added object_detection_app and world.py in the code provided by the site below to original pupil repository provided by the pupil labs and executed run_caputure_bat in my pupil repository.
I have modified several errors and got above error.

Thank you.

**Comment by papr** [comment]
Sorry, but I am not sure what you mean by
> provided by the site below to original pupil repository 

The issue is that you are trying to make an old version of `world.py` work with the current source code. Your version seems to miss a series of recent changes, including [the commit setting the `min_calibration_confidence` attribute](https://github.com/pupil-labs/pupil/commit/210098c46d47ed4987c9d51543f907bf722b5bea) which now triggers the above described issue.

I suggest to check why you would need a custom version of `world.py` in the first place. I am very sure that your object detection code could be run from a plugin instead of modifying `world.py`.

Alternatively, checkout older revisions of the pupil and companion repositories, e.g. pyglui, which are compatible with your modified version of `world.py`.

Please understand that our support is limited in cases where the source code has been modified by the user.

**Comment by jhs0053** [comment]
@papr Thank you for your reply.

I have solved the problem. However, I am suffering different error..

So, I will open new issue soon.

Thank you.
