### ISSUE TITLE
cannot work after calibration - Pupil Capture v1.11 - Windows 10 

### ISSUE THREAD

**Issue by ssarayoon** [pupil-labs/pupil#1474]
After calibration, the program is freezing. 
![1](https://user-images.githubusercontent.com/49235640/55475152-17e78f00-564e-11e9-8172-bbd6ffe706b9.png)
![2](https://user-images.githubusercontent.com/49235640/55475170-2170f700-564e-11e9-9fc4-41af3798b642.png)

**Comment by ssarayoon** [comment]
The same thing happens in v1.10.

**Comment by papr** [comment]
Hi @ssarayoon 
It looks like you are running Capture from a path that includes non-ascii characters. Please try to copy the extracted folders with the pupil exe files to a path that only includes ascii-characters, e.g. `C://work`

**Comment by ssarayoon** [comment]
Hello @papr 
Unfortunately, I already did it what you said,  e.g. C://work. My file is in C folder. I do not know why stopped after calibration.

**Comment by papr** [comment]
@ssarayoon Can you please reproduce the error while runnning from `C://work` and share the `player.log` file in the `pupil_player_settings` folder after the app has crashed?

**Comment by papr** [comment]
@ssarayoon Is this issue still present? If yes, please send us the `player.log` file.

**Comment by willpatera** [comment]
@ssarayoon I will close this issue as there has been no response since early April. If this is still an issue, please feel free to comment/re-open.
