### ISSUE TITLE
fatal error: boost/iterator_adaptors.hpp:No such file or directory

### ISSUE THREAD

**Issue by jhs0053** [pupil-labs/pupil#1477]
Hello.

I have installed and run pupil software in ubuntu 18.04.

I have got an error as:

jhs@jhs-desktop:~/pupil/pupil_src$ python3 main.py
 world - [INFO] launchables.world: Application Version: 1.11.37
 world - [INFO] launchables.world: System Info: User: jhs, Platform: Linux, Machine: jhs-desktop, Release: 4.15.0-29-generic, Version: #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018
 world - [INFO] pupil_detectors.build: Building extension modules...
 In file included from detect_2d.hpp:20:0,
                  from detector_2d.cpp:685:
 singleeyefitter/fun.h:9:10: fatal error: boost/iterator_adaptors.hpp: No such file or directory
  #include <boost/iterator_adaptors.hpp>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 compilation terminated.
 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
 world - [ERROR] launchables.world: Process Capture crashed with trace:
 Traceback (most recent call last):
   File "/home/jhs/pupil/pupil_src/launchables/world.py", line 132, in world
     import pupil_detectors
   File "/home/jhs/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 18, in <module>
     build_cpp_extension()
   File "/home/jhs/pupil/pupil_src/shared_modules/pupil_detectors/build.py", line 32, in build_cpp_extension
     ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
   File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
     **kwargs).stdout
   File "/usr/lib/python3.6/subprocess.py", line 418, in run
     output=stdout, stderr=stderr)
 subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'install', '--install-lib=/home/jhs/pupil/pupil_src/shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.

Anyone knows how to solve this error?

Thank you.

**Comment by papr** [comment]
It looks like boost was not properly installed. Please follow the install instructions on how to install boost.

**Comment by jhs0053** [comment]
@papr Thank you for your reply.

**Comment by papr** [comment]
@jhs0053 Were you able to solve this problem?

**Comment by papr** [comment]
We have removed the requirement to install boost in #1552
