### ISSUE TITLE
Updating from such a repository can't be done securely.

### ISSUE THREAD

**Issue by jhs0053** [pupil-labs/pupil#1478]
Hello. I have installed and run pupil software in ubuntu 18.04.

I have copy and paste following command into terminal as: sudo add-apt-repository ppa:jonathonf/ffmpeg-3

I have got the error as:

jhs@jhs-desktop:~$ sudo add-apt-repository ppa:jonathonf/ffmpeg-3
 [sudo] password for jhs:
  Backport and/or package of FFMPEG 3 and key libraries

***

Cumulative downloads at 2017-12-20: 68,504 (based on ffmpeg)

Total downloads of 3.4: 24,113
 Total downloads of 3.3.2: 2,814

***

Find PPAs useful? Consider a donation to those you use.
  More info: https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-3
 Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://kr.archive.ubuntu.com/ubuntu bionic InRelease
 Hit:2 http://kr.archive.ubuntu.com/ubuntu bionic-updates InRelease             
 Hit:3 http://kr.archive.ubuntu.com/ubuntu bionic-backports InRelease           
 Ign:4 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu804/x86_64  InRelease
 Get:5 https://packages.microsoft.com/repos/vscode stable InRelease [3,181 B]   
 Get:6 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages [109 kB]
 Ign:7 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu804/x86_64  InRelease
 Get:8 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
 Hit:9 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease    
 Ign:10 http://ppa.launchpad.net/jonathonf/ffmpeg-3/ubuntu bionic InRelease     
 Err:11 http://ppa.launchpad.net/jonathonf/ffmpeg-3/ubuntu bionic Release       
   404  Not Found [IP: 91.189.95.83 80]
 Err:12 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu804/x86_64  Release
   404  Not Found [IP: 192.229.232.112 80]
 Err:13 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu804/x86_64  Release
   404  Not Found [IP: 192.229.232.112 80]
 Reading package lists... Done
 E: The repository 'http://ppa.launchpad.net/jonathonf/ffmpeg-3/ubuntu bionic Release' does not have a Release file.
 N: Updating from such a repository can't be done securely, and is therefore disabled by default.
 N: See apt-secure(8) manpage for repository creation and user configuration details.
 E: The repository 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu804/x86_64  Release' does not have a Release file.
 N: Updating from such a repository can't be done securely, and is therefore disabled by default.
 N: See apt-secure(8) manpage for repository creation and user configuration details.
 E: The repository 'http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu804/x86_64  Release' does not have a Release file.
 N: Updating from such a repository can't be done securely, and is therefore disabled by default.
 N: See apt-secure(8) manpage for repository creation and user configuration details.

Anyone knows how to solve this problem?

**Comment by papr** [comment]
You only need to run `sudo add-apt-repository ppa:jonathonf/ffmpeg-3` on earlier releases than 18.04
