### ISSUE TITLE
Trouble building pupil from source on Ubuntu 16.04

### ISSUE THREAD

**Issue by Gutesnacht** [pupil-labs/pupil#1483]
Hi there,

I tried to setup pupil from source for a while now, but unfortunately cant get my head around one error. First of, I had trouble when it came to the right path dependencies regarding a fresh install from source of opencv besides ros kinetic which comes along with an older opencv version and wants to be treated as the main opencv on the os. I got that resolved using #1423 . After that, it starts building when i call python3 main.py, but fails with the following error:

>  world - [INFO] launchables.world: Application Version: 1.11.9
world - [INFO] launchables.world: System Info: User: lwoehle, Platform: Linux, Machine: lwoehle, Release: 4.4.0-145-generic, Version: #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019
world - [INFO] pupil_detectors.build: Building extension modules...
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
world - [INFO] calibration_routines.optimization_calibration.build: Building extension modules...
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/lwoehle/pupil/pupil/pupil_src/launchables/world.py", line 143, in world
    from plugin_manager import Plugin_Manager
  File "/home/lwoehle/pupil/pupil/pupil_src/shared_modules/plugin_manager.py", line 15, in <module>
    from video_capture import Base_Manager, Base_Source
  File "/home/lwoehle/pupil/pupil/pupil_src/shared_modules/video_capture/__init__.py", line 37, in <module>
    from .file_backend import FileSeekError
  File "/home/lwoehle/pupil/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 197
    **kwargs,
            ^
SyntaxError: invalid syntax

world - [INFO] launchables.world: Process shutting down.
<

I tried to fix that by going into the file_backend and delete the "invalid syntax" causing comma, but that just causes another invalid syntax error in another file, so that doesnt really sound like a solution.

Any Idea how to get around this?

The bundled version is running without any problems, even using a realsense and running this inside the pupil capture program is possible.

Thanks in advance

**Comment by papr** [comment]
@Gutesnacht Which Python version do you use (`$ python -V`)? We require Python 3.5 or higher.

**Comment by Gutesnacht** [comment]
Hi there,

I got multiple versions installed, but the one i am using to launch the main.py is python3 in the Version python 3.5.2.

Best Regards

**Comment by papr** [comment]
@Gutesnacht If it is available to you, could you please try to use Python 3.6 or newer?

**Comment by IsabelFunke** [comment]
The latest version of Pupil code uses python syntax that requires Python 3.6 or newer. Maybe clarify this at docs.pupil-labs.com (Developer Setup section) ?
