### ISSUE TITLE
Assertion failed -215 How to resolve this error.

### ISSUE THREAD

**Issue by guptaridhima** [pupil-labs/pupil#1485]
import cv2
import numpy as nm
hand= cv2.imread('hand.jpg',0)
#When we need to convert an image into a gray scale or we can use cvt color function
ret, thres = cv2.threshold(hand,70,255,cv2.THRESH_BINARY)
_,contours= cv2.findContours(thres.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
for c in contours:
    hull = cv2.convexHull(c)
hull = [cv2.convexHull(c) for c in contours]
final = cv2.drawContours(hand,hull,-1,(255,0,0))

cv2.imshow('Original image',hand)
cv2.imshow('threshold',thres)
#cv2.imshow('countors',final)
cv2.waitKey(0)
cv2.destroyAllWindow()

Above is the code and this is the error i m getting

  File "C:/Users/Ridhima/Desktop/Machine learning/Machine Learning A-Z Template Folder/Hand_Ges/hand_Gesture.py", line 14, in <module>
    hull = cv2.convexHull(c)

error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\convhull.cpp:137: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::convexHull'

**Comment by papr** [comment]
Not sure how this is related to this repository but `c` is not of the correct type. Please consider the cv2 documentation on the expected input type.

**Comment by guptaridhima** [comment]
which thread  is authered
as i m really new to python and this environment. so please help me to
configure it step by step.
