### ISSUE TITLE
Calibrate without world camera

### ISSUE THREAD

**Issue by nadinagomez** [pupil-labs/pupil#1491]
Hi, we didn't buy the world camera. What calibration method should be recommended for this case?

**Comment by papr** [comment]
> The calibration is only necessary to map from eye to world coordinates. Without a world coordinate system, a calibration is neither possible nor useful.

You could use the HMD Calibration, if you have a virtual environment in which the user is moving.

**Comment by nadinagomez** [comment]
We don't have a virtual enviorment, we're just interested in measuring the pupil diameter. So what should we do to ensure that pupil diameter is properly registered along the experiment?

**Comment by papr** [comment]
@nadinagomez In this case, you do not need a calibration. Please follow the documentation on good pupil detection. In the `System Graphs` menu on the right, you can enable a preview of the recent pupil diameter history.

**Comment by nadinagomez** [comment]
Thanks, for your response, the system Graphs looked already like this, does it have to display anything else? Is this sufficient to proper capture the pupil diameter or should I add the "Diameter History 
![Image Graphs](https://user-images.githubusercontent.com/50023478/56818310-a7e0b900-6847-11e9-9b7a-49e2aa0eab33.jpg)
plugin"? In case I should, were could I download it from? Thanks in advance

**Comment by papr** [comment]
That is already correct. You should see the graph in the top left. I would suggest to make a sample recording and check it out in Player. Player visualizes the diameter for the whole recording as a timeline as well as allows to export the data. Afterwards, you can post-process the exported pupil data as necessary.

**Comment by nadinagomez** [comment]
Hi, thanks for your response, we made a sample recording and confidence Interval didn't keep constant across the experiment, this result in a 44% data loss ( in a 2 minuts task) which is not ok for the experiment. We have checked all the pupil detection parameters and they were into a high confidence Interval. What could we do to ensure a good pupil diameter recording over the experiment? 
Also, what program do you suggest when exporting data? (Excel, Numbers, etc)

Thanks
