### ISSUE TITLE
Pupil Capture Data Loss - Screen freezing - Reinit every 5 sec

### ISSUE THREAD

**Issue by MeiYingLau** [pupil-labs/pupil#1496]
Hi,

We ran pupil capture version 1.11.4 on a 64-bits window 10 computer and lately encountered many eyetracker issues during experiment. The cameras froze whenever
 our participants put on glasses and reinit every 5 sec or less. The screen will just freeze whenever that occurs, making data collection nearly impossible. 

The following set of messages occur in an endless loop (sample log file attached)
[Issuefile1.txt](https://github.com/pupil-labs/pupil/files/3139188/Issuefile1.txt):
world - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID2.
world - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution (1280, 720)
world - [INFO] camera_models: Loading pre-recorded calibration
Estimated / selected altsetting bandwith : 904 / 1600.
!!!!Packets per transfer = 32 frameInterval = 327868
eye1 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye0 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
world - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye1 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam2 ID1.
eye0 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam2 ID0.
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID1 at resolution (192, 192)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID0 at resolution (192, 192)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye1 - [WARNING] uvc: Could not set Value. 'Backlight Compensation'.
eye0 - [WARNING] uvc: Could not set Value. 'Backlight Compensation'.
Estimated / selected altsetting bandwith : 151 / 256.
Estimated / selected altsetting bandwith : 151 / 256.
!!!!Packets per transfer = 32 frameInterval = 82712
!!!!Packets per transfer = 32 frameInterval = 82712

I tried disconnecting the headset and reconnect it, restarting software, restarting the computer, restarting computer with headset disconnected and reconnect afterward, restarting software after a few days, and even reinstalling the software (version is most recent). None of above worked. I know it worked once upon a time but not anymore and I don't know what went wrong. 

Any advice?

**Comment by papr** [comment]
Since all cameras disconnect at the same time, it looks like a loose connection around the hub. Make sure the USB c cable is really in the hub. You might need more force than expected. If this does not solve the problem, please contact info@pupil-labs.com
