### ISSUE TITLE
Unable to create heatmaps in offline surface tracking windows_x64_v1.12-17

### ISSUE THREAD

**Issue by JiaLiu000** [pupil-labs/pupil#1505]
Hi, I am trying to get heatmap in offline surface tracking, but there is nothing happening after selecting "show heatmap".  I clicked the "re-calculate gaze distributions" but the player keeps saying "No gaze on any surface in this section". I have defined the surface (A4 sheet paper). The screenshot is attached. Could you guys help me with my problem? Please let me know if you need more information. Thank you.
![SurfaceTracker](https://user-images.githubusercontent.com/50436239/57498156-25172e00-731e-11e9-9cc4-30d1bce1a284.png)

**Comment by papr** [comment]
Please share the recording with `data [at] pupil-labs.com`

**Comment by JiaLiu000** [comment]
hi @papr , please find the recording with the link. Thank you.
https://drive.google.com/drive/folders/1BCgzMln7XxeRGLmk6DAVWLYgoZQ3Wix4?usp=sharing

**Comment by willpatera** [comment]
@JiaLiu000 You do not have any markers included in your scene. You need to include square markers in order to (1) define a surface, (2) track a surface, and (3) visualize a heatmap of gaze positions. 

Please refer to docs: https://docs.pupil-labs.com/#surface-tracking
