### ISSUE TITLE
World camera coordinate system

### ISSUE THREAD

**Issue by phausamann** [pupil-labs/pupil#1506]
Hi,

the documentation does not explicitly state how the axes of the world camera coordinate system are oriented. The z-axis seems to be pointing in the direction of the optical axis, so I assume this is the coordinate system being used?

![grafik](https://user-images.githubusercontent.com/4687996/57700334-11d7cb80-765a-11e9-84ca-1322f4eab4bc.png)

Thanks!

**Comment by papr** [comment]
Yes, this is the undistorted camera coordinate space.

**Comment by phausamann** [comment]
Great, thanks! I'd be happy to submit a PR to pupil-docs ([here](https://github.com/pupil-labs/pupil-docs/blob/master/user-docs/data-format.md)) if that's desired.

**Comment by papr** [comment]
That would be helpful, yes. Please make sure that any media added to the documentation is properly licensed (ideally public domain).
