### ISSUE TITLE
use surface tracker with input from tensor flow...

### ISSUE THREAD

**Issue by johnspenceruea** [pupil-labs/pupil#1507]
We are using tensor flow to ID objects and surfaces in our video data. I was wondering if the surface tracker plug-in could use input from tensor flow (since we did not use pupil markers in our study). Would be nice to use the features of the surface tracker (including the reports) but to define the surface via input from another source...

**Comment by papr** [comment]
The current implementation is not designed to take input from tensorflow.

To my knowledge, most object detection algorithms either give you a bounding box or a pixel mask. You can test if gaze data intersects your detected objects by converting the gaze "norm_pos" field to a pixel coordinate and checking if it is within the object boundary.

The surface tracker operates differently. It assumes the surface to be flat, calculating its [homography](https://en.wikipedia.org/wiki/Homography_(computer_vision)), and using it to map gaze to an undistorted version of the surface.

**Comment by johnspenceruea** [comment]
Thanks for the feedback. We'll tackle this in concert with our other work with tensor flow.
