### ISSUE TITLE
World camera stream with Pupil Service

### ISSUE THREAD

**Issue by HCl-not-HCi** [pupil-labs/pupil#1509]
Hi,

I worked with Pupil Service and Pupil Capture for a while now and it seems like it's impossible to get the world video stream on the ipc without pupil capture.
That's because the Service doesn't retrieve the camera data and the frame publisher can't work because there is no real loop (```recent_events``` in plugins gets called on gaze data only).
The first issue could be resolved by writing an own plugin that does the same stuff like pupil capture. But the second issue can't be solved like that.
So why isn't it possible to use Pupil Service for the same things as Pupil Capture? When you write a separate application for processing the data including camera streams from pupil, it's impossible to do that without the pupil UI (at least without ugly solutions).

By looking at the code it seems like it would be possible to implement this (but you would have to make big changes). Is this something you have thought about? It would open many more possibilities with pupil.

**Comment by papr** [comment]
The main functionality of the ui is to provide feedback about camera positioning and pupil detection quality to the user. Ideally, one would split the image processing and ui into different processes, s.t. the ui can be turned off on demand. This comes with the disadvantage, that the image data needs to be copied between the processes, which decreases performance. As you said, @HCl-not-HCi, this will require a lot of changes for which we currently do not have the resources.

**Comment by HCl-not-HCi** [comment]
Thank you for your answer. I can understand both points you mentioned. But maybe you have the possibility to change this someday. It wouldn't be relevant to my project anymore but it could open more possibilities for other people working with pupil in future. Additionally, it would give Pupil Service the same features as Pupil Capture and create less confusion about the possibilities you have with Pupil Service (at least to me).
