### ISSUE TITLE
Offline Surface Tracker works better in v1.12 than in v1.13 (Pupil Player)

### ISSUE THREAD

**Issue by frank-drebin** [pupil-labs/pupil#1542]
Hello, 
I am having some issues with the current Pupil Play version (PC). I use the pupil core tracker to record visual stimuli that are presented through a projector. The markers are included in the projected video itself.

After upgrading to Pupil Play v1.13 I realised that the offline surface detection did not work as well as before. The surfaces are now shaking and the marker detection worsened to a degree that made working with this usually very useful tool almost impossible. 

To check, I opened the very same prerecorded file in Pupil Play v1.12 and v1.13 and the result was as described as above. In v1.13 the surfaces were not stable and moved a lot, while the surfaces worked perfectly under v1.12. Should I downgrade to v1.12 again or is this a known problem that will be fixed in the near future?

Thank you very much in advance for your help,
Ben

**Comment by papr** [comment]
Hi @frank-drebin 
Did you create the surfaces from scratch in v1.13 or were they imported from a previous version?

**Comment by frank-drebin** [comment]
@papr 
I created them from scratch

**Comment by frank-drebin** [comment]
(the old surfaces from v1.12 didn't show up in v1.13, so I had to rebuild them)

**Comment by papr** [comment]
@frank-drebin This is not a known issue. Please share the recording with data@pupil-labs.com such that we can debug the issue. I would recommend to downgrade if the current version is not working for you.

**Comment by frank-drebin** [comment]
@papr Thank you for your quick reply. What kind of data do you need? I could export a small video part from each version using the same prerecorded file so you can see the difference. Or do you need all the raw data?

**Comment by papr** [comment]
I would need the raw recording please.

**Comment by frank-drebin** [comment]
👍

**Comment by papr** [comment]
Dear @frank-drebin 
Thank you for providing the data. Did you make sure that both versions use the same "Minimum marker perimeter" parameter? It is used to remove false positives, but if set to big, can lead to false negative detections.

In our next release, we will support a new type of markers, april-tags, which are much more robust and should resolve your issue.

**Comment by frank-drebin** [comment]
Dear Pablo,

 

Yes, the minimum marker perimeter was set to the same value. I will just continue using version 1.12 and switch to your next update using april-tags as soon as it is available.

 

Thank you :)

Ben

 

Von: Pablo Prietz <notifications@github.com> 
Gesendet: Dienstag, 16. Juli 2019 13:14
An: pupil-labs/pupil <pupil@noreply.github.com>
Cc: frank-drebin <blues-fuss@unitybox.de>; Mention <mention@noreply.github.com>
Betreff: Re: [pupil-labs/pupil] Offline Surface Tracker works better in v1.12 than in v1.13 (Pupil Player) (#1542)

 

Dear @frank-drebin <https://github.com/frank-drebin> 
Thank you for providing the data. Did you make sure that both versions use the same "Minimum marker perimeter" parameter? It is used to remove false positives, but if set to big, can lead to false negative detections.

In our next release, we will support a new type of markers, april-tags, which are much more robust and should resolve your issue.

**Comment by papr** [comment]
Fixed in #1555
