### ISSUE TITLE
Player v1.13 - Surface Tracker crashes program when adding new surface

### ISSUE THREAD

**Issue by VisionResearchBlog** [pupil-labs/pupil#1544]
I have files I am analysing in Pupil player v1.13 (on a windows 10 system). After loading the files and enabling the surface tracker plugin, it seems to scan through the video ok and find the markers. However, when I try to add a new surface the program hangs with an error in the ods terminal window mentioning an error in opencv with convhull.cpp - apparently related to drawing the polygon & finding intersection with the gaze? I've tried on multiple videos with no predefined surfaces and the same occurs each time, the window becomes unresponsive and the error (will attach below) appears and I must force quit

**Comment by VisionResearchBlog** [comment]
Screenshot of error
![surface_crash_v1 13](https://user-images.githubusercontent.com/17455592/60893751-68781500-a259-11e9-9b44-d5710716bca0.PNG)

**Comment by papr** [comment]
@romanroibu Could you please try to reproduce this issue?

**Comment by VisionResearchBlog** [comment]
I tried on a mac running OS 10.14.5 and the same problem occurs - the program becomes unresponsive and needs to be force quit - I've tried this on files from several different recording sessions using v1.12 capture data - Does the update break backwards compatibility to older versions of pupil capture?

**Comment by papr** [comment]
This is a bug, not an intended change. We will update the bundles as soon as it is fixed.

**Comment by VisionResearchBlog** [comment]
Ok thanks - I've uploaded an example recording where the bug occurs here: https://uob-my.sharepoint.com/:u:/g/personal/bs16044_bristol_ac_uk/EV-RDpJSEj9HnYn2jj0tQOEB8K2cFJf0-y-VLfRg7nsN0g?e=qBVQLf
