### ISSUE TITLE
pupil diameter estimation and correction

### ISSUE THREAD

**Issue by BCIstorm** [pupil-labs/pupil#1545]
Hello all,
 I want to assess the pupil diameter over time. At the moment I'm trying to figure out the best practices and facing some problems. Can anyone help?

1) Looking at the "Pupil Capture - World" window, on top there are: id0 conf, id0 dia, id1 conf, id1 dia. These indicators are different from the "Debug Visualizer" window associated with each "Pupil Capture - eye". I think the "World" window indicates the 2D pupil diameter estimation and the "Debug visualizer" the 3D, right?

2) When adjusting focus on the lens of each eye camera, if I focus on the Iris (meaning, I can see detail in the Iris) it is more difficult for the "id confidence" to reach 1.0 than when it is slightly out of focus. This is strange and not good accordingly to the tutorial section on Pupil Docs. But if the iris/pupil are out of focus is the "find edges" algorithm output reliable? Is it reporting a bigger than actually is Pupil diameter?

3) When looking to the camera axis, the pupil geometry seen by that camera is approximately circular. Looking away it will become ellipsoidal (the major axis?). So, looking at different points on a screen, the apparent pupil diameter is changing, nevertheless, the real pupil diameter is the same. I guess this is not being corrected. Am I right? Is there a way to correct it?

To better illustrate what I wrote, next are 2 screen captures. The first one, the user is looking up:
![capture-20190709-up](https://user-images.githubusercontent.com/33836942/60903594-86e60c80-a269-11e9-9559-7aabbaac6b88.PNG)

And second one, looking down:
![capture-20190709-down](https://user-images.githubusercontent.com/33836942/60903607-8c435700-a269-11e9-9f2c-3474e387940f.PNG)

I need to get the best estimation of how pupil diameter change over 15min duration tests for different users. What would be your advice on how to accomplish that?

Kind Regards

**Comment by papr** [comment]
1. That is correct.
2. It is recommended to focus on the pupil, not the iris. Sharper pupil edges usually result in higher confidence (if the edges are found correctly).
3. The 3d diameter is automatically corrected for rotation by the 3d model. The 2d diameter is not corrected for rotation since its definition is the size of the detected ellipsis's major axis in pixels.

Please be aware that the 3d model does not correct for corneal refraction which has an impact on pupil size estimation. See [A novel approach to single camera, glint-free3D eye model fitting including corneal refraction](https://perceptual.mpi-inf.mpg.de/files/2018/04/dierkes18_etra.pdf).

**Comment by papr** [comment]
> I need to get the best estimation of how pupil diameter change over 15min duration tests for different users. What would be your advice on how to accomplish that?

Currently, the best option is to use the 3d model. We are planning on releasing an improved model that implements the refraction correction. You will be able to apply this method after-the-effect in Pupil Player, as soon as it is released.

**Comment by juliusverrel** [comment]
@papr, thank you for the helpful information. Could you give an estimate of the error induced by corneal refraction? Any news on the improved model? Would it also be possible to apply the model script-based (without invoking PupilPlayer)?

**Comment by papr** [comment]
@juliusverrel The estimated error is about 5% across the field of view. We are currently in the last phase (setting up deployment and testing) before integrating the project into Pupil.

**Comment by juliusverrel** [comment]
thank you!
