### ISSUE TITLE
Error - when running run_capture.bat

### ISSUE THREAD

**Issue by jaeseon0909** [pupil-labs/pupil#1546]
Hi, 
I have installed all the windows dependencies as written in the instruction. I use Windows 10 and Pycharm as an editor.
But when running main.py or run_capture.bat, I get the following error. 
-------------------------------------------------------------------------------------------------
C:\Users\JS\PycharmProjects\pic\venv\Scripts\python.exe C:/Users/JS/PycharmProjects/pic/venv/Lib/site-packages/pupil/pupil_src/main.py

world - [INFO] launchables.world: Application Version: 1.13.30
world - [INFO] launchables.world: System Info: User: JS, Platform: Windows, Machine: DESKTOP-GKBHS3M, Release: 10, Version: 10.0.17134
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\Users\JS\PycharmProjects\pic\venv\Lib\site-packages\pupil\pupil_src\launchables\world.py", line 147, in world
    from plugin_manager import Plugin_Manager
  File "C:\Users\JS\PycharmProjects\pic\venv\Lib\site-packages\pupil\pupil_src\shared_modules\plugin_manager.py", line 14, in <module>
    from calibration_routines import Calibration_Plugin, Gaze_Mapping_Plugin
  File "C:\Users\JS\PycharmProjects\pic\venv\Lib\site-packages\pupil\pupil_src\shared_modules\calibration_routines\__init__.py", line 13, in <module>
    from .screen_marker_calibration import Screen_Marker_Calibration
  File "C:\Users\JS\PycharmProjects\pic\venv\Lib\site-packages\pupil\pupil_src\shared_modules\calibration_routines\screen_marker_calibration.py", line 27, in <module>
    from .calibration_plugin_base import Calibration_Plugin
  File "C:\Users\JS\PycharmProjects\pic\venv\Lib\site-packages\pupil\pupil_src\shared_modules\calibration_routines\calibration_plugin_base.py", line 13, in <module>
    from plugin import Plugin, Experimental_Plugin_Base
ImportError: cannot import name 'Experimental_Plugin_Base'

world - [INFO] launchables.world: Process shutting down.

Process finished with exit code 0
-----------------------------------------------------------------------------------------------------
Any ideas to solve this issue?

**Comment by mikkeyboi** [comment]
Have you tried following these instructions? #1455 
You’ll likely have to clean up the source repository before you can checkout `cboulay/win_vcpkg_build` branch.

**Comment by jaeseon0909** [comment]
Thank you, mikkeyboi. I've installed Anaconda (Python 3.7 ver.), git, and visual studio 2017. But I came across this issue below, entering the first one in the Anaconda Prompt. Could you give me any advice on this? 
-------------------------------------------------------
(base) C:\Users\JS>conda create -n pupil python=3.6 opencv boost eigen ceres-solver ffmpeg glfw glew
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ffmpeg
  - glew
  - glfw
  - ceres-solver

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by jaeseon0909** [comment]
Thank you, mikkeyboi! I'm glad that there is a simpler way. But this time I came across this issue below. Could you give me any advice on this? 


(base) C:\WINDOWS\system32>conda create -n pupil python=3.6 ceres-solver
WARNING: A directory already exists at the target location 'C:\Users\JS\Anaconda3\envs\pupil'
but it is not a conda environment.
Continue creating environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ceres-solver

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by mikkeyboi** [comment]
Hi @jaeseon0909, try running this `conda config --add channels conda-forge` and re-run the script.

**Comment by jaeseon0909** [comment]
Hi @mikkeyboi, now I could run 'run_capture.bat' using anaconda prompt. But when I tried to run main.py from Pycharm (with anaconda plugin), I got this error message: 

C:\Users\JS\Anaconda3\envs\jaeseon\python.exe C:/Users/JS/PycharmProjects/jaeseon_eye/main.py
Traceback (most recent call last):
  File "C:/Users/JS/PycharmProjects/jaeseon_eye/main.py", line 20, in <module>
    import launchable_args
ModuleNotFoundError: No module named 'launchable_args'

Thank you so much!

**Comment by mikkeyboi** [comment]
Hi @jaeseon0909, glad it works out. 
In anaconda prompt, activate your `np` environment and try running `python main.py`.  If you get the same error, try adding `pupil/pupil_external` to your PATH (either via environment variables or some PATH/PYTHONPATH variable in PyCharm).
Alternatively, you can place `PupilDrvInst.exe` from `pupil/pupil_external` in some folder in your PATH dirs.

**Comment by jaeseon0909** [comment]
I have created a Pycharm project in this folder 'C:\Users\JS\Anaconda3\envs\pupil' and it works.
I appreciate your help!

**Comment by mikkeyboi** [comment]
You may want to avoid making changes in a conda environment.
Setting your interpreter to your conda environment would achieve the same fix; even if there's something in there you made you can add the folder in your Project Structure (PyCharm- Settings/Preferences > Project > Project Structure).
Just like you shouldn't paste custom packages or scripts in your interpreter, but instead tell the program where to find these scripts (ie: append to temp path, init files, symbolic links, etc.).
