### ISSUE TITLE
Can we access the uvc eye camera settings in the hmd-eyes project (unity3d)?

### ISSUE THREAD

**Issue by soumilchugh** [pupil-labs/pupil#1548]
Is there a way of accessing and changing the eye camera settings using a plugin in unity3d?

**Comment by papr** [comment]
Currently, the camera's uvc settings are not accessible via the network api. This would either require modifications of the uvc backend code or a custom Capture plugin that implements the api. The former will not be implemented in the near future. Therefore, I recommend the development of a custom plugin. You can contact me on our public Discord channel if you run into problems with the implementation. 👍
