### ISSUE TITLE
How can we calculate the offset using distance to the display?

### ISSUE THREAD

**Issue by JoeyJing** [pupil-labs/pupil#1549]
Hi!

I am trying to do the calibration. And with several methods, I think it's hard to get "a best calibration" because aspects like pupil vergence and pupil size may be different from time to time . (Or if you can provide any ways to adjust the calibration without changing your algorithm) 

So I want to calculate the offset of the gaze point and the screen. Then I learn from your previous question where said
"If your gaze accuracy is ~1-2 degrees then, depending on your distance to the display, you can calculate how large your offset is. An offset of up to 1-2 cm when sitting right in front of the display is what you can expect at 1-2 degrees gaze accuracy."

Can you tell me how to do that?

Thank you so much.

**Comment by papr** [comment]
Apologies for the delayed response. Please see the explanation below.

This is a trigonometry problem. Please see the attached graphic for the meaning of the variables.

Example:
```python
In [1]: import numpy as np 
   ...:  
   ...: alpha_deg = 1.5  # 1.5 degrees of error 
   ...: alpha_rad = np.deg2rad(alpha_deg)  # np.tan expects the input to be in radians 
   ...:  
   ...: distance_cm = 50  # distance to SCREEN in cm 
   ...:  
   ...: # calculate error on SCREEN in cm 
   ...: error_cm = np.tan(alpha_rad) * distance_cm

In [2]: error_cm  # print result
Out[2]: 1.3092960784593464
```

![photo_2019-09-09 12 02 18](https://user-images.githubusercontent.com/168390/64522192-c37dc500-d2f9-11e9-97a9-80cd5eef7f73.jpeg)
