### ISSUE TITLE
Dependencies Installation MacOS error

### ISSUE THREAD

**Issue by guowenbin90** [pupil-labs/pupil#155]
I met a error when I installed it. 
The following is the error line in the last line: 

error: command 'llvm-gcc-4.2' failed with exit status 1

Who could help me to figure out it?
Thank you so much!

**Comment by mkassner** [comment]
Did you install the command line tool for MacOS?

**Comment by mkassner** [comment]
I tested this on a new VM. I cannot reproduce this error. please let me know if you fixed this or not.

**Comment by guowenbin90** [comment]
I used the Xcode-select --install method, does it mean I have installed the
command line? But it still has error.

**Comment by guowenbin90** [comment]
Can you show me the detailed command line? Thank you!

**Comment by mkassner** [comment]
We do not use Xcode. Please install the `command line tools for MacOS`. 

Everything is explained and linked here:
https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-MacOS

simple install the command line tools for your MacOS version.
then open terminal and copy&paste from the wiki pages linked above.

**Comment by guowenbin90** [comment]
I installed the command line, but I don't know why I still have this problem. 

graph.c:3688: error: ‘GL_LINES’ undeclared (first use in this function)
graph.c:3708: warning: implicit declaration of function ‘glVertex3f’
graph.c:3797: warning: implicit declaration of function ‘glEnd’
graph.c: In function ‘__pyx_pf_6pyglui_5graph_10Line_Graph_8draw’:
graph.c:5758: error: ‘GL_MODELVIEW’ undeclared (first use in this function)
graph.c:5849: error: ‘GL_LINE_STRIP’ undeclared (first use in this function)
graph.c: In function ‘__pyx_pf_6pyglui_5graph_14Averaged_Value_10draw’:
graph.c:8040: error: ‘GL_MODELVIEW’ undeclared (first use in this function)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: /var/folders/z_/y53b40657pvdyqbbnplw8byh0000gn/T//ccE89JLT.out
error: command 'gcc-4.2' failed with exit status 1

And sometimes it has another error:
error: no module named cv2

How to run the pupil program? Does it type 'cd ~/capture python main.py' to run this program? Thank you so much!

**Comment by toshikurauchi** [comment]
Have you installed the other dependencies? It is not finding OpenGL and
OpenCV.

**Comment by guowenbin90** [comment]
I installed them.

Last login: Thu Jun 18 15:48:36 on console
Administrators-Mac-mini:~ Administrator$ pip install PyOpenGL
Requirement already satisfied (use --upgrade to upgrade): PyOpenGL in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Administrators-Mac-mini:~ Administrator$ pip install pyzmq==13.1
Requirement already satisfied (use --upgrade to upgrade): pyzmq==13.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Administrators-Mac-mini:~ Administrator$ pip install numexpr

**Comment by mkassner** [comment]
please make sure your pythonpath is correct.

**Comment by mkassner** [comment]
please reopen if this is not solved.

**Comment by guowenbin90** [comment]
I try to restall again. Thanks.
