### ISSUE TITLE
Saccade Vs Fixation Gaze

### ISSUE THREAD

**Issue by graceshaib** [pupil-labs/pupil#1556]
Hello,

I would like to know what is the minimum/maximum degrees per second that makes a saccade become a fixation on Pupil Player. In addition, is there a specific distance the gaze should move to in order to be registered as a saccade and not white noise? any help is highly appreciated.

Thank you very much!

**Comment by papr** [comment]
Pupil's fixation detector is no velocity based but uses a minimum duration/maximum dispersion approach.  Both parameters can be customized by the user depending on their needs. See the [documentation](https://docs.pupil-labs.com/#fixation-detector174) for details.

Additionally, we introduced a NSLR-based eye movement detector that classifies any gaze data into fixations, smooth persuit, saccades and post-saccadic oscillations. More information can be found [here](https://docs.pupil-labs.com/#eye-movement-detector-main).

**Comment by MLT-SEP** [comment]
I searched in pupil player the eye movement detector in order to obtain fixations, smooth pursuit and saccades. I searched the NSLR-based eye movement detector in your link but I did not find it. Could I find that in Pupil Player when I did an export or must I use Python or Matlab like I saw in #1482 ? Thank you for your answer.

**Comment by pfaion** [comment]
Hi @MLT-SEP 
we have removed the NSLR-based eye movement detector from Pupil in version v1.17 as the algorithm did not produce satisfying results overall. Currently Pupil does not offer an eye-movement detector.

**Comment by MLT-SEP** [comment]
Thank you very much for your answer ! In the future, I hope it will be possible !
