### ISSUE TITLE
Pupil player doesn't work

### ISSUE THREAD

**Issue by aopichugina** [pupil-labs/pupil#1558]
For some reason pupil player has stopped opening the gray window. It opens only the black one. What can I do? Thanks in advance!

![Untitled-1](https://user-images.githubusercontent.com/53140778/61589893-47001d00-abb9-11e9-8979-846de79d5f47.jpg)

**Comment by papr** [comment]
@aopichugina Please close the window, delete the `user_settings_*` files in the `pupil_player_settings` folder, and try again.

**Comment by aopichugina** [comment]
@parp thank you! It works now.

**Comment by papr** [comment]
great!
