### ISSUE TITLE
Feature request - Offline Surface Tracker Surface Definition Persistency

### ISSUE THREAD

**Issue by pefortin** [pupil-labs/pupil#1574]
As the issue's title suggest, I think it would be extremely helpful to have a process to carry over surface definitions generated in pupil player with the offline surface tracker between session. 

For example:
1. I have a recording where I can define the surfaces offline. 
2. I define the surfaces
3. I save some kind of file, or surface profile. 
4. Later, I can select that file directly to avoid to have to redefine all surfaces.

**Comment by romanroibu** [comment]
Hi @pefortin, you could accomplish this (use surfaces defined in one recording with another recording) by copying over the surface definitions files (`surface_definitions`, `surface_definitions_v01`, etc).
