### ISSUE TITLE
'Video not found' - player

### ISSUE THREAD

**Issue by kwisiecka** [pupil-labs/pupil#1579]
Hi,

When I'm trying to open the recording on different computer than I recorded it,
the player is showing fixations and eyes overlays without world video, although the video is in the folder, the background is grey.
On computer on which I recorded it everthing is fine.

I would be grateful for any suggestion what could happened.

Thanks in advance!

**Comment by romanroibu** [comment]
Hi @kwisiecka, could you please share the `player.log`?

**Comment by papr** [comment]
This issue seems to be stale. Closing.
