### ISSUE TITLE
Pupil Player crash when loading recording

### ISSUE THREAD

**Issue by toddrjen** [pupil-labs/pupil#1580]
Pupil Player is crashing every time I load particular recordings.  Strangely, it is always the first recording when we record two right after each other.  It happens with Pupil versions 1.13, 1.14, and 1.15.  Here is the error message:

```
.\pupil_player.exe : player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
At line:1 char:1
+ .\pupil_player.exe C:\Users\experimenter\recordings\recording_3\000 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (player - [INFO]...alSense backend:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [INFO] launchables.player: Starting new session with 'C:\Users\experimenter\recordings\recording_3\000'
player - [INFO] update_methods: Updating meta info
player - [INFO] update_methods: Checking for world-less recording
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
player - [INFO] plugin: Added: <class 'export_angles.Angle_Exporter'>
player - [INFO] launchables.player: Application Version: 1.14.6
player - [INFO] launchables.player: System Info: User: experimenter, Platform: Windows, Machine: MYBOX, Release: 10, Version: 10.0.17763
player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "shared_modules\video_capture\utils.py", line 309, in load_or_build_lookup
  File "shared_modules\video_capture\utils.py", line 305, in load_lookup
  File "numpy\lib\npyio.py", line 370, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\experimenter\\recordings\\recording_3\\000\\world_lookup.npy'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "launchables\player.py", line 264, in player
  File "shared_modules\video_capture\file_backend.py", line 213, in __init__
  File "shared_modules\video_capture\utils.py", line 311, in load_or_build_lookup
  File "shared_modules\video_capture\utils.py", line 289, in build_lookup
  File "shared_modules\video_capture\utils.py", line 354, in _fill_gaps
MemoryError
player - [INFO] launchables.player: Process shutting down.
C:\Programs\pupil\pupil_latest\pupil_player\numpy\core\fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
C:\Programs\pupil\pupil_latest\pupil_player\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
```

Looking at the directory, `world_lookup.npy` is indeed missing.  Here are all the files in the recording directory:

```
annotation_player.pldata
annotation_player_timestamps.npy
annotation.pldata
annotation_timestamps.npy
eye1.mp4
eye1_timestamps.npy
gaze.pldata
gaze_timestamps.npy
info.csv
notify.pldata
notify_timestamps.npy
pupil.pldata
pupil_timestamps.npy
square_marker_cache
surface_definitions
user_info.csv
world.intrinsics
world.mp4
world_timestamps.npy
```

**Comment by romanroibu** [comment]
Hi @toddrjen,

From the logs it looks like the underlying problem is a [`MemoryError`](https://docs.python.org/3.6/library/exceptions.html#MemoryError).

Could you please share more information about the system you're running on?

**Comment by toddrjen** [comment]
@romanroibu It is a brand new core i7-8700 tower with 32 GB of RAM running Windows 10.  

And the error isn't related to the size of the recording, in this case the first recording was much smaller and has the error, while the much larger second recording was fine.

**Comment by toddrme2178** [comment]
This is becoming really serious.  Most recordings we make are unusable at this point.  We are trying to run an experiment but can't because we can't access the data.

**Comment by toddrjen** [comment]
This is becoming really serious. Most recordings we make are unusable at this point. We are trying to run an experiment but can't because we can't access the data.

**Comment by papr** [comment]
@toddrjen please share the timestamp files (ideally from multiple recordings) with us such that we can debug what is going on while creating the lookup file.

Please let us also know how your experiment is setup, e.g. do you have the headset directly connected to the computer running Capture, or do you stream via Pupil Mobile, is there any other software running on the same computer, etc. This should help us in case we find issues with the original timestamp files.

**Comment by toddrme2178** [comment]
@papr:  How do I send the files to you?  Which specific files do you want?

The eye tracker is connected directly to the computer via a USB cable.  The only other program running is MATLAB, which we use to communicate with pupil using the ZMQ API.  We only use the API for starting/stopping the recording, setting the timestamp, and recording annotations.

**Comment by toddrjen** [comment]
@papr: How do I send the files to you? Which specific files do you want?

The eye tracker is connected directly to the computer via a USB cable. The only other program running is MATLAB, which we use to communicate with pupil using the ZMQ API. We only use the API for starting/stopping the recording, setting the timestamp, and recording annotations.

**Comment by papr** [comment]
Please send the *_timestamps.npy files. Just zip them and attach them to a github comment below.

**Comment by papr** [comment]
Alternatively, send the zip file to data@pupil-labs.com

**Comment by toddrjen** [comment]
@papr 

I have attached it as `timestamps.zip`.  In the `bad` subdirectory are some examples of recordings that cause the crash.  In the `good` subdirectory are some examples of recordings that don't.

[timestamps.zip](https://github.com/pupil-labs/pupil/files/3516998/timestamps.zip)

**Comment by romanroibu** [comment]
@toddrjen After investigating this, we found that in some of the timestamps file have a few entries at the beginning which are drastically smaller than the rest of the timestamps.

Is it possible that the MATLAB script is setting the timestamps after the recording has started? If so, please make sure that the timestamps are set before recording begins, and let us know if you still experience this issue.

**Comment by toddrjen** [comment]
Yes, it was setting timestamps during the recording.  I didn't realize that was an issue.  I have changed the code to not do that and to raise an error if we try.  I will let you know if that solves the issue.

**Comment by papr** [comment]
Great. if this is the case, we can reopen the recording.
