### ISSUE TITLE
Win10 blue screen after unplug the pupil glasses

### ISSUE THREAD

**Issue by FeiyangWang1996** [pupil-labs/pupil#1581]
![DSC_0443](https://user-images.githubusercontent.com/46497399/62882016-03538b80-bcff-11e9-9c24-00ecaf8add1c.JPG)

**Comment by FeiyangWang1996** [comment]
while using the pupil capture, some times I unplug the glasses the PC will turn to blue screen. Some times I play around with the dashboard in pupil capture this problem also happened.

**Comment by FeiyangWang1996** [comment]
It's not very frequent, but still annoying.

**Comment by papr** [comment]
Apologies for the delayed response. Given this [error code description](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x44--multiple-irp-complete-requests), it looks like there might be a setup issue with your drivers. Please try the following steps:
1. Open the device manager
2. From the `View` menu, enable "Show hidden devices"
3. Remove/delete/uninstall all devices listed in the `libUSBk` category. You might need to repeat this multiple times for the same device.
4. Restart your computer and verify that no devices are listed in the `libUSBk` category.
5. [Download and use the latest version of Pupil Capture](https://github.com/pupil-labs/pupil/releases/latest#user-content-downloads).
