### ISSUE TITLE
calibration_routines.finish_calibration: Not enough ref point or pupil data available for calibration

### ISSUE THREAD

**Issue by Shalva-A-Kohen** [pupil-labs/pupil#1582]
Both left and right eye cameras seem to be tracking the eyes, the red dot and red circle are where they are supposed to be. However, when i run calibration I get the error: calibration_routines.finish_calibration: Not enough ref point or pupil data available for calibration
I tried capture alone, and running service then capture but nothing works. What could be causing this?

**Comment by papr** [comment]
@Shalva-A-Kohen Apologies for the delayed response. In order for the calibration to work, Capture tries to detect our circular calibration markers. Please make sure that they are clearly visible in the scene camera during the calibration. If this was already the case this might be a technical issue. In this case I need information about the Pupil Capture version and the operating system that you are using.

**Comment by hjbbyw** [comment]
I met the same problem. Pupil Capture version is v1.16, and my operating system is windows 10 (I tried in both proffesinal and educational version).

**Comment by papr** [comment]
@hjbbyw which calibration routine are you performing?

**Comment by hjbbyw** [comment]
I use pupil core., and I try to perform Screen Marker Calibration.

**Comment by papr** [comment]
OK, great. Could you start a Capture recording and perform a calibration, and share the recording with data@pupil-labs.com? This would help us to check if there is an issue with the underlying timing.

**Comment by hjbbyw** [comment]
sure. I have just sent all my recording. But there seems to be another problem, when I start recording, the red dot keeps still all the time  though I move my eyes.

**Comment by papr** [comment]
@hjbbyw Hi, I had a look at the data that you send me. First of all, I have only received the timestamp files instead of the whole recording. Was this intentional?

Also, the pupil timestamp file does not contain any pupil data. This should not be the case if the following is true:
> Both left and right eye cameras seem to be tracking the eyes, the red dot and red circle are where they are supposed to be. 

Please share a complete recording, including world and eye videos, for further debugging.

**Comment by hjbbyw** [comment]
thanks. I have sent another email. this time I met other problems that I write in the email.

**Comment by papr** [comment]
@hjbbyw closing the eye windows actually stops the eye tracking. Either leave the eye windows open or minimize them, but please do not close them entirely. Regarding your other issue, please create a new issue and attach the `capture.log` file after Capture crashes.

You can find it in the `pupil_capture_settings` directory of your user's home folder.
