### ISSUE TITLE
Exported video file type is unsupported 

### ISSUE THREAD

**Issue by aopichugina** [pupil-labs/pupil#1583]
Eyes and world camera’s videos when separated are alright. But after video export (where I add gaze point to the video) I can’t open a file, it says “This file isn’t playable. That might be because file type is unsupported, the file extension is incorrect, or the file is corrupt”. 
I had renewed all video codecs on my computer, but it didn’t help. Other video players say it’s invalid frame rate. What can I do?
Thanks in advance!

**Comment by AOrps** [comment]
Hi, @aopichugina, I had the same problem. Be sure to download pupil player and run that first then drag the recording directory. You should be able to see a new video window with your eye data now!

**Comment by papr** [comment]
Also, please make sure that the videos were finished exporting successfully. You can track the export progress in the `Eye Video Exporter` and `World Video Exporter` menus after starting a new export.

**Comment by aopichugina** [comment]
@papr hello! Yes, that was my problem, I didn't notice the progress icon. Thank you!
