### ISSUE TITLE
Pupil Saccade detector

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#159]
We need a saccade detector plugin.

It should be very similar to the fixation detector.
1.  Duration of saccade (in milliseconds or other suitable unit of measure)
2.  Velocity of saccade (degrees/second or other suitable unit of measure)
3.  Length of saccade (in degrees or other suitable unit of measure)

**Comment by cwimsatt** [comment]
Naively, would the SACLAB toolbox on Matlab file exchange be a good starting point?
Here's the link to the source on Matlab File Exchange
https://www.mathworks.com/matlabcentral/fileexchange/60491-saclab?focused=7129591&tab=function

**Comment by papr** [comment]
To be replaced with https://www.nature.com/articles/s41598-017-17983-x

**Comment by papr** [comment]
Closed in favor of #1482
