### ISSUE TITLE
Surface tracker: fix edit mode vertices stuck to mouse pointer

### ISSUE THREAD

**Issue by romanroibu** [pupil-labs/pupil#1590]
When moving surface vertices in edit mode the release click would sometimes be ignored and the vertex was stuck on the mouse pointer for ever. This was not the case before and needs to be fixed.

(reported by @mkassner)

**Comment by romanroibu** [comment]
One way to reproduce:
- enable surface editing
- left-click and hold a corner
- move the mouse fast while holding the click
- while moving - release the click

Very often this results in the corner being stuck to the mouse. If there is an offset between the corner position and the mouse pointer position, it is impossible to pin the corner to a location.

**Comment by papr** [comment]
Fixed via #1591
