### ISSUE TITLE
Static noise/garbage audio recording on macOS

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#1593]
When recording audio from USB microphones on macOS, it is often the case that it records static noise/garbage audio. This might be related to #1592 but this could also be due to incorrectly setting up the audio device.

**Comment by anshvarts** [comment]
+1 
without USB mic sound recording is not possible, as it says "audio format is not supported". Connecting USB mic leads to noice (I also noticed that audio.mp4 seems to have double length after such a recording, so perhaps it is related for framerate somehow)
