### ISSUE TITLE
question - taking advantage of the surface implementation

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#160]
Hi everyone,

Right now, out of the box, the `reference_surface` is an exclusive feature of the marker detector. I would appreciate any advice in order to take advantage of the surface functionality.

In my current setup, I have a well iluminated screen in front of the participants and they are always looking straight forward to the screen. In a scenario like that, the contrast and brightness of the world camera will be automatically adjusted resulting in a darker background and a clean screen. It is easy to detect the screen with that light condition.

I would like to have an alternative to my current approach based on detecting the stimulus on screen. It is much simpler to detect the screen and deduce by homographic transformation the stimuli points. I would appreciate any comments, and alternative approachs if any.

Why not use markers? Markers are not well detected if placed on such a darker background. Further, markers may interfer in participant's attention. Furthermore, avoiding markers may be necessary due spatial constraints, and so on.

**Comment by MichaelBarz** [comment]
Hi,
detecting the screen by difference in luminance is a feasible approach. There is also recent [research](http://dl.acm.org/citation.cfm?id=1983304). Nevertheless, for some scenarios you'll better go with marker detection, e.g. if you consider a website with a dark header bar. The bar will probably not be recognized as part of the display. A solution could be on-screen markers. The only disadvantage is the necessary space you have to cut from your target application.

Hope I could help you ;)

**Comment by cpicanco** [comment]
Thank you @MichaelBarz , I will take a look :)
