### ISSUE TITLE
Tracking text on an A4 size paper

### ISSUE THREAD

**Issue by judomarshall** [pupil-labs/pupil#1608]
Dear all, thanks for this resource! I have no prior experience with pupil labs or programming, but am learning a lot from this site. 

I am currently stuck on a project and would really appreciate some help solving a problem I am having. 

As the title of this thread states, I want to track my students' eye movements when reading text on a A4 paper. I can't seem to get the level of accuracy I am hoping for. Here is what I am currently doing:

1) Tracking in 3d mode
2) Utilizing a chin rest so students reduce head movement during reading
3) Using the computer screen calibration (5 points)
4) Positioning the students eyes approximately 50 cm away from the middle of the A4 paper containing text, which students will be reading. 
5) Using surface markers on the 4 corners of the A4 sized paper

equipment: Windows 10, most current Pupil Capture version, monocular pupil headset

It seems I can get a somewhat accurate setup, but heatmaps don't seem to work unless a student looks at a certain area for at least 1 second. Also, while I can get close, the calibration is always slightly off.

My guess is that the paper and 12 font text is simply to small for this eye tracker to handle, but I thought I would ask here for some advice.

Thank you in advance!

**Comment by papr** [comment]
@judomarshall Your setup sounds reasonable, although I agree that 12pt font is probably too small. Since you use a chin rest, I would recommend to give the 2D mode a try. It can be more accurate than 3D, but is usually more sensible to slippage. You can use the Accuracy Visualizer in Capture or the Offline Calibration in Player to calculate the accuracy of a calibration. Usually, 1 degree of error is considered accurate.

>  but heatmaps don't seem to work unless a student looks at a certain area for at least 1 second

Is this in Capture or in Player?

**Comment by judomarshall** [comment]
Thank you for the quick response!
I will try the experiment again in 2d mode. 

I am no longer at work, but I believe it is in player mode. 
I tried to reduce the time to 0.5 seconds, but the shortest I was allowed was 1 second. 
I will confirm when I get back to my office. 

Thank you!

**Comment by judomarshall** [comment]
If I may add one more thing. 
Specifically, what I am trying to find out is the order in which students read a portion of a reading test, which is made up of a short text, followed by several multiple choice questions. I want to know the process that students go through in order to come to their chosen answers.

If you have any advice on plugins or procedures that might be beneficial for this type of study, your input would be greatly appreciated.

**Comment by papr** [comment]
@judomarshall I think you are referring to the heatmap gaze history length in Capture. Capture uses a sliding window approach to aggregate the heatmaps' gaze. If you use Player, gaze  will be aggregated over the whole recording. Afterwards, you can export the data and use it for this tutorial: https://github.com/pupil-labs/pupil-tutorials/blob/master/03_visualize_scan_path_on_surface.ipynb

**Comment by judomarshall** [comment]
Thanks again for the advice. 
The images shown in that tutorial are exactly what I am hoping to be able to utilize for my study. 
Unfortunately, I have no experience in using Python.

Do you have any suggestions on how I might output something similar just using the Pupil Player software?

**Comment by papr** [comment]
@judomarshall Player does currently not output this kind of high level analysis.

**Comment by judomarshall** [comment]
@papr Thank you for the help. Really appreciate it. After trying your suggestions, I am still having problem getting the tracker dialed in. Here are the photos of my process:

Calibration:
![IMG_20190829_132707235_HDR](https://user-images.githubusercontent.com/54617864/63913499-57829d80-ca6b-11e9-841b-0fac59af4bde.jpg)

Chin Rest:

![IMG_20190829_131129058_HDR](https://user-images.githubusercontent.com/54617864/63913515-62d5c900-ca6b-11e9-8060-a87a0cfd3107.jpg)

Marker in relation to the actual viewpoint:

![vlcsnap-2019-08-29-14h39m59s539](https://user-images.githubusercontent.com/54617864/63913528-708b4e80-ca6b-11e9-8a01-ecc242ac5f89.png)


The marker always seems to be situated slightly higher than it should be.
What am I doing wrong?

**Comment by papr** [comment]
I do not think you are doing something particularly wrong. Based on your last screenshot, your calibration was pretty decent but I also see that it does not provide the necessary accuracy in this case. I would change two things:
1. Larger text, as you proposed above
2. Do not do the calibration on screen but on the table. Ask the subject to place the head in the chin rest and perform the manual marker calibration. This way you calibrate in the exact same context as you do the gaze estimation in.

**Comment by papr** [comment]
Looks like your questions were sufficiently answered. Please let me if this is not the case and we can reopen the issue. If you have new questions please create a new issue.

**Comment by judomarshall** [comment]
Thank you for following up on this.
I will put future questions in a new thread.
