### ISSUE TITLE
Pupil Capture - no video from the Pupil Headset (Manjaro).

### ISSUE THREAD

**Issue by tylnesh** [pupil-labs/pupil#1617]
Happens both when installed from AUR with yay and running from source:

`world - [INFO] launchables.world: Application Version: 1.15.65
world - [INFO] launchables.world: System Info: User: tylnesh, Platform: Linux, Machine: isabella-X1, Release: 4.19.66-1-MANJARO, Version: #1 SMP PREEMPT Fri Aug 9 18:01:53 UTC 2019
world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
world - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [1280, 720]
world - [INFO] camera_models: No pre-recorded calibration available
world - [WARNING] camera_models: Loading dummy calibration
world - [WARNING] launchables.world: Process started.
`

**Comment by papr** [comment]
@tylnesh Please check if the UVC Manager lists the cameras as `unknown`. If this is the case you need to add your user to the `plugdev` group

**Comment by tylnesh** [comment]
Not sure how to do that, but I've got the cameras running in guvcview. In Manjaro, there is no plugdev group (as it's depreciated in Arch based distros), but I've created one and added my user to it. 

The full terminal output is:

world - [INFO] launchables.world: Application Version: 1.15.65
world - [INFO] launchables.world: System Info: User: tylnesh, Platform: Linux, Machine: isabella-X1, Release: 4.19.66-1-MANJARO, Version: #1 SMP PREEMPT Fri Aug 9 18:01:53 UTC 2019
world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
world - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [1280, 720]
world - [INFO] camera_models: No pre-recorded calibration available
world - [WARNING] camera_models: Loading dummy calibration
world - [WARNING] launchables.world: Process started.
eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye0 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
eye0 - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [320, 240]
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] launchables.eye: Process started.
eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye1 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
eye1 - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [320, 240]
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye1 - [WARNING] launchables.eye: Process started.

**Comment by papr** [comment]
Did you reboot afterwards?

**Comment by tylnesh** [comment]
Yeah, I did, but didn't work. Finally fixed it with this:
      

echo 'SUBSYSTEM=="usb",  ENV{DEVTYPE}=="usb_device", GROUP="plugdev", MODE="0664"' | sudo tee /etc/udev/rules.d/10-libuvc.rules > /dev/null && sudo udevadm trigger

Source: https://github.com/pupil-labs/pupil-docs/blob/master/developer-docs/linux.md
