### ISSUE TITLE
Pupil Player: offline pupil detector does not finish correctly

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil#1618]
This happened with a pupil mobile recording.
The process will finish and the pupil data is there, but the UI does not finish:
![image](https://user-images.githubusercontent.com/7101194/64258279-416f5400-cf27-11e9-93f2-2dc412825578.png)

I had a quick look and there seems to be a mismatch between the numbers of frames processed by the detector and the number of frames present in the eye video. This needs to be investigated at some point, but probably low priority.

**Comment by papr** [comment]
Should be fixed with out changes to progress calculation in cbb65ff
