### ISSUE TITLE
Monocular visualization from binocular recording

### ISSUE THREAD

**Issue by aopichugina** [pupil-labs/pupil#1622]
Hello!
I have data with binocular recording. One eye was recorded badly, so I don't want to make visualizations on the world video with it. Is there a function to delete one eye and make the visualization only form another one eye? Could't find it...
Thanks in advance!

**Comment by papr** [comment]
Hey, usually, if one eye has bad detection, the gaze mapping (which is what is being visualized) is done monocularly already. But to do it explicitly, you can delete the corresponding eye video and rerun the offline pupil detection and offline calibration (if a calibration procedure is part of the recording).

**Comment by aopichugina** [comment]
@papr ok, I'll try it, thank you!

**Comment by papr** [comment]
OK, great. Let us know if it does not work out for you. Then we can reopen this issue.
