### ISSUE TITLE
Surface marker detector fails on fragmented videos

### ISSUE THREAD

**Issue by romanroibu** [pupil-labs/pupil#1626]
If the video is fragmented (is missing some frames in the middle), the marker detector will only correctly detect the markers on the first continuous part, from the current seek position up to the missing frames.

One possible explanation is that robust marker detection causes the failure, since there are no previous detections for the missing frames.

**Comment by pfaion** [comment]
@romanroibu This did not happen on current master anymore, correct?

**Comment by papr** [comment]
Correct

**Comment by papr** [comment]
Issue is fixed in v1.16
