### ISSUE TITLE
Pupil Player crashes when loading recordings

### ISSUE THREAD

**Issue by aklostermann** [pupil-labs/pupil#1634]
![grafik](https://user-images.githubusercontent.com/55283194/64863844-10cd9f80-d636-11e9-9c34-52a60fc04451.png)

I receive the error above when trying to load two of my 40 recordings. The remaining worked. I also tried the most recent player. Is it possible to rescue those data sets?

**Comment by papr** [comment]
That the pupil_data file is missing is an indication that the recording was not correctly terminated. Please share the recordings with data@pupil-labs.com such that we can have a look.

I will close this issue since it is not directly related to the code base.
