### ISSUE TITLE
Driver installation fails on Windows with unicode characters

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil#1635]
There was a report of driver installation failing on Windows where the username was written in Hebrew characters.

I have been able to reproduce this issue with a new user account on my machine:

I deleted all installed drivers.
Then I created a new user account on my machine with only hebrew characters in the name.
When trying to run the bundle, the driver installation starts twice (as expected) with requiring admin permissions.
There is no indication of the installation failing, no error messages, nothing.
After the installation finished, the cameras do not work.
Re-opening the bundle would trigger the driver installation again, indicating once more that it apparently failed.
Repeatedly I was not able to get it to work.

On my other user-account opening the bundle would re-install the drivers successfully and the cameras were working again.

**Comment by papr** [comment]
This should be fixed by #1833
