### ISSUE TITLE
Can't see my recordings

### ISSUE THREAD

**Issue by mariachristofi** [pupil-labs/pupil#1646]
I am using eye-tracking glasses connected with the pupil lab's mobile. While I am starting my recordings everything looks ok. The cameras works and the location is activated so I proceeded to my recordings but at the end of those no videos played. Although the time of recording is correct the screen of videos is black. The data from the folder of mobile recording is attached as picture below.
![exporting data](https://user-images.githubusercontent.com/54776343/65060868-5ca77e00-d981-11e9-8f48-2c56adc399b8.jpg)

**Comment by papr** [comment]
@mariachristofi It looks like you did not open the recording in Pupil Player yet. Please download it from [here](https://github.com/pupil-labs/pupil/releases) and use it to open the recording. I can also recommend our [video tutorials on Offline Pupil Detection and Offline Calibration](https://www.youtube.com/watch?v=_Jnxi1OMMTc&list=PLi20Yl1k_57rlznaEfrXyqiF0sUtZMMLh).

You can also use Pupil Player to export a video that is playable by all common video players.

**Comment by mariachristofi** [comment]
@papr thank you. I will check about it.
