### ISSUE TITLE
Pupil Player stopped working

### ISSUE THREAD

**Issue by mariachristofi** [pupil-labs/pupil#1647]
Dear all my pupil player for some reason stopped working. When I am trying to open it the black screen appears with the message: player - [INFO] video_capture: "Install pyrealsense to use the Intel RealSense bankend", and after that, the program stopped working and the 2nd screen it does not appear at all. Trying to close and reopen it, restart my pc but nothing of all that work out. Please let me know what I have to do

**Comment by papr** [comment]
Please try deleting the user_settings_player file in the pupil_player_settings folder.

**Comment by mariachristofi** [comment]
Thank you sir that's working. Thank you!
