### ISSUE TITLE
Cannot open World video

### ISSUE THREAD

**Issue by MLT-SEP** [pupil-labs/pupil#1654]
When I export data, I cannot open the file world.mp4.

Could someone help me please because I cannot work without this file.

Thank you,

**Comment by papr** [comment]
Please provide further information about which Pupil Player version and operating system you are using.

**Comment by papr** [comment]
Please also make sure that the world video exporter plugin has finished the export process before attempting to open the video.

**Comment by MLT-SEP** [comment]
I use Windows_x64_v1.15-65 in Intel core i5 Dell Computer and I opened the video after complete export process. Moreover pupil player crashed with this recordings when I wanted to organize gaze mappers offline calibration.
I have no problem with other data and world videos.

**Comment by papr** [comment]
Please try to reproduce the issue with the newest v1.16-43 bundle. If it still crashes, please share the player.log file in the pupil_player_settings folder.

**Comment by MLT-SEP** [comment]
Thank you for your reply. It seems it works.

Thank you again,
