### ISSUE TITLE
[KDE] Pupil Capture World Video Window freeze after locking and unlocking the screen

### ISSUE THREAD

**Issue by marhkb** [pupil-labs/pupil#1655]
When Pupil Capture is running on KDE Plasma locking the the screen with CTRL+ALT+L and unlocking it afterwards makes the world video window freeze whereas the eye windows are still running.

OS: Arch Linux
Plasma Verison: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.13.1
Kernel: 5.3.1-zen1-zen
Pupil Versions: 1.16 and before

**Comment by papr** [comment]
@marhkb Could you share the `~/pupil_capture_settings/capture.log` file after reproducing the freeze?

**Comment by marhkb** [comment]
Sure.
I started Capture and it logged until 2019-09-25 10:52:48,341.
Then I locked the screen. When I then looked at the log file, nothing new got logged.
Then I closed the still running eye video as one can see in the log.
Afterwards I killed the world process.
I don't know if this log file reveals something useful.

[capture.log](https://github.com/pupil-labs/pupil/files/3651547/capture.log)
