### ISSUE TITLE
Player will not create/ allow edits on new calibrations

### ISSUE THREAD

**Issue by emjohns32** [pupil-labs/pupil#1656]
I cannot edit the name or trim markers of a calibration. Even when I create a new calibration I am not allowed to edit the name or the trim markers. It says that I cannot do this because it's not the original recording. The issue is that it is the original recording from Capture. I have attached two screenshots from when I select a calibration I had already done and when I try to create a new one to see if I can edit that one. 

<img width="411" alt="Screen Shot 2019-09-25 at 2 33 53 PM" src="https://user-images.githubusercontent.com/53273512/65631327-52026f80-dfa5-11e9-93ad-e55686e7c298.png">
<img width="481" alt="Screen Shot 2019-09-25 at 2 47 38 PM" src="https://user-images.githubusercontent.com/53273512/65631345-5b8bd780-dfa5-11e9-88bf-47d86d4e01a7.png">

**Comment by linussun** [comment]
I also have this problem with 1.16.  And it appears that without New Calibrations, we can't calculate any New Gaze Mappers either, I always get the error: 'You first need to calculate calibration 'Default Calibration' before calculating the mapper 'Default Gaze Mapper 2'.

**Comment by papr** [comment]
Thank you for reporting this issue. Apologies for the inconvenience this bug is causing. We expect to release a fix for this issue on Monday.

**Comment by emjohns32** [comment]
Thank you very much for the update.

Emily Johns
Project Manager
Indiana University | Psychological and Brain Sciences
Cognitive Development Lab | A140B
