### ISSUE TITLE
Increasing fps pre-recorded video

### ISSUE THREAD

**Issue by nestorcgk** [pupil-labs/pupil#166]
When the input video source is a pre-recorded mkv video even if the frame rate is set to 30 it increases the fps during the execution of the program without limit even until 200 fps.

**Comment by mkassner** [comment]
The video source is free running. But we can make it run slower. I ll add an option for that.

**Comment by mkassner** [comment]
fixed with: 4d37d8cff78e673327bdfe0a64d5282047d93c46
