### ISSUE TITLE
"dll load failed" pupil player error

### ISSUE THREAD

**Issue by mahmoudgaber1992** [pupil-labs/pupil#1661]
I am using windows 10 and after dragging the captured folder, I get the error "dll load file failed"  and after the player will shut down. how can i resolve this problem?

**Comment by papr** [comment]
Please download and run the `vc_redist.x64.exe` file from the [official Microsoft support page](https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads). Afterwards, Pupil should start up as expected.

**Comment by papr** [comment]
Since there has not been any feedback, I will assume that the issue has been resolved and I will close the issue. If this was not the case, please comment below. Then I can reopen the issue and we can discuss further steps to debug the issue.
