### ISSUE TITLE
Pupil capture collapses when try to detect both eyes

### ISSUE THREAD

**Issue by aopichugina** [pupil-labs/pupil#1664]
I had no problems with this for months. But recently the eye-tracker began to detect only eye 0, and when I click on "detect eye 1" the program freezes and doesn't respond. What can be the problem of that?
Thanks in advance!

**Comment by papr** [comment]
This is probably due to an issue with the hardware. Please contact info@pupil-labs.com with a reference to this issue. Our support team will determine the next steps to get this problem fixed.
