### ISSUE TITLE
Exporting annotations

### ISSUE THREAD

**Issue by VicWalDK** [pupil-labs/pupil#1665]
Hi
When I export my annotations from pupil player to excel, the data is in one column instead of separate ones. Can i change that so the data will be easier to work with?
Best regards

**Comment by papr** [comment]
Hi @VicWalDK Excel makes assumptions about the separation of the columns. Please check which separator is used for the csv import. It should be `, `.

**Comment by papr** [comment]
Since there has not been any feedback, I will assume that the issue has been resolved and I will close the issue. Please comment below if my assumption was wrong. Then I can reopen the issue and we can discuss further steps.
