### ISSUE TITLE
Right camera is always upside down.

### ISSUE THREAD

**Issue by iPsych** [pupil-labs/pupil#1671]
In my pupil core, Right camera is always upside down.
It can corrected via UI in Capture App, it's not possible in mobile app.
Also, I am worry about it's possible effect on tracking.

**Comment by papr** [comment]
Hi, yes, this is due to the right camera being physically flipped. In Capture, flipping only has an effect on the display image, not the processed or stored image.

The image being flipped does not have an effect on the eye tracking quality.
