### ISSUE TITLE
Missing debug window on Mac

### ISSUE THREAD

**Issue by VicWalDK** [pupil-labs/pupil#1676]
Hello
We are a couple of people working with pupil core on our macbooks, unfortunately we miss the debug window that can show the data about a recent calibration. On windows computers this window just appears when opening pupil capture. How can I find this window?
Best Regards

**Comment by papr** [comment]
Dear @VicWalDK 
This window is usually not opened automatically. It is possible, that you opened it manually once on Windows, and it is being reopened by Pupil Capture for persistency reasons.

You can open it after an initial 3d calibration through the 3d Detector, see attached screenshot.

![Screenshot 2019-10-08 at 14 33 05](https://user-images.githubusercontent.com/168390/66398178-9d714080-e9dd-11e9-9101-eb77fa765e0c.png)
  
Please let me know if this is not the window you were talking about. In this case, please post a screenshot of the given Window below and I can reopen the issue.

**Comment by VicWalDK** [comment]
That is not the Window I am refering to. The Window I am Looking for does
open up as a second Window when opening pupil capture on my collegaues
Windows computers. The Window I am Looking for is Black With text. when I
do my calibrations, text  appears letting me Know how accurate my
calibration Was, that information quickly disapears in my primary Window,
but Should remain in the secondary black Window With text. to my knowledge
the bug Window you are refering to does not Tell me how accurate my
calibration Was.
Best regards Victoria

tir. 8. okt. 2019 15.10 skrev Pablo Prietz <notifications@github.com>:

**Comment by papr** [comment]
My apologies, I misunderstood. Yes, this window is indeed only available on Windows and is a result how the app is bundled on windows.

You multiple options, of which this is the recommended one for your use case:

Open the Accuracy Visualizer menu on the right of the world window. It includes two text fields with the information that you seek.

**Comment by VicWalDK** [comment]
thank you so much, I Will try to figure it Out.
Best regards

tir. 8. okt. 2019 15.25 skrev Pablo Prietz <notifications@github.com>:
