### ISSUE TITLE
Export video timestamp in addition to frame number

### ISSUE THREAD

**Issue by HeyFlash** [pupil-labs/pupil#1680]
Currently, when exporting from pupil player, the frame number of the video is referenced. However, some video APIs allow random access to video frames only via a video timestamp and not via frame numbers (I assume because of streaming scenarios in which frames can be dropped?).

Therefore it would be very helpful to export the video time in addition to the frame number, since a simple conversion between those two is not possible due to the non-equidistant frames used in the videos.

**Comment by papr** [comment]
Yes, we can add this to the next release.

**Comment by HeyFlash** [comment]
I would really appreciate it, thanks.
