### ISSUE TITLE
Not getting image from camera on MacOS

### ISSUE THREAD

**Issue by guhshia** [pupil-labs/pupil#1683]
So I used a logitech C525 and was hoping to upgrade it to C920
I had no problem with C525 at all,
but somehow when I switched to C920 there's no image (blank white screen).
I tried the camera with other apps and they all worked fine, so I guess its not a hardware issue.
I've tried deleting the capture and recordings folders, didn't work.

I'm using Mac 10.12.5 and here are the message I got:
world - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
world - [INFO] video_capture.uvc_backend: Found device. HD Pro Webcam C920.
world - [INFO] video_capture.uvc_backend: Hardware timestamps not supported for HD Pro Webcam C920. Using software timestamps.
world - [INFO] camera_models: Previously recorded calibration found and loaded!
world - [WARNING] uvc: Could not set Value. 'Absolute Exposure Time'.
Estimated / selected altsetting bandwith : 904 / 944. 
!!!!Packets per transfer = 32 frameInterval = 333333

Could anyone please help me with this?
Thank you!

**Comment by papr** [comment]
>  world - [WARNING] uvc: Could not set Value. 'Absolute Exposure Time'.

Usually, Capture adjusts exposure time automatically. This fails due to the camera not supporting this specific UVC control. Please adjust the exposure time manually in the "UVC Source" menu.
