### ISSUE TITLE
Similar to Issue #1558

### ISSUE THREAD

**Issue by ouzieq123** [pupil-labs/pupil#1685]
I have a similar problem where I can't find my pupil player window. I can't find a user settings file. (on windows)

**Comment by papr** [comment]
Please look for the pupil_player_settings folder in your home directory. Searching for it in the file explorer should work, too. It includes the files that you need to delete in order to reset the application.

**Comment by papr** [comment]
Closing this as duplicate. Please let us know if you are still having issues finding the `pupil_player_settings` folder.
