### ISSUE TITLE
Eye camera doesn't work

### ISSUE THREAD

**Issue by karliell** [pupil-labs/pupil#1688]
The camera for eye always couldn't launch. The messages look like this:
```
world - [WARNING] launchables.world: Process started.
Estimated / selected altsetting bandwith : 904 / 1600.
!!!!Packets per transfer = 32 frameInterval = 327868
world - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
```

![image](https://user-images.githubusercontent.com/36145675/66862612-416b6680-ef5f-11e9-87e6-ac9940bcb255.png)

The only thing I can do is reboot it again and again. Would you please help me with this?

Thank you so much for your help.

**Comment by papr** [comment]
Please check the general settings menu in the top right. Turn on the toggles for the eye processes. You should see two new windows previewing the eye camera feed.
