### ISSUE TITLE
Algorithm view: pupil size indicators not centered for coarse detection

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil#1690]
The size indicator circles are not centered in the coarse detection scenario. E.g. when selecting the 400x400 resolution for the pupil cameras. This results in them easily overlapping with the image borders.

See 192x192 resolution:
![image](https://user-images.githubusercontent.com/7101194/66986286-e6e91c00-f0be-11e9-9354-72e33c593f7f.png)

See 400x400 resolution:
![image](https://user-images.githubusercontent.com/7101194/66986324-fff1cd00-f0be-11e9-8666-6a0c57e99143.png)

**Comment by papr** [comment]
I do not think these were ever meant to be centered. Given that the partial occlusion does not affect the use case of the visualization (the majority of the circles is still visible), I will close this with a `wontfix`
