### ISSUE TITLE
[License Nit] Consider relicensing to a FOSS approved license. 

### ISSUE THREAD

**Issue by MrTomWhite** [pupil-labs/pupil#170]
This is an exciting looking project with a seemingly straightforward license... 

>"All source code written by us is open source according to CC BY-NC-SA license < http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode >. We want you to change and improve the code. All software is distributed in the hope that it will be useful, but without any warranty. Just make sure to credit us, and we hope that you will share your work with the Pupil community."

... Wait. That's not a license for code. :crying_cat_face: 
The creative commons wiki is very clear about this: 

>"Make sure the material is appropriate for CC licensing.
CC licenses are appropriate for all types of content you want to share publicly, except software and hardware."
https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees

OSI Approved licenses are a very easy way to make sure you can share your code and protect everyone's intellectual property. http://opensource.org/licenses 

Since you want no commercial use, you can pick a license that better protects you, such as a flavor of the GPL. (Most companies are scared of any GPL work, and any company willing to do that work knowing it is under the GPL is worth working with probably.) 

EDIT: Wikipedia also has a great comparison chart: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by mkassner** [comment]
Thanks for raising this clear and concise issue. 

A transition to one of the big OS licences has been something we have been talking about internally for a while now. 

We will talk to our user community about this a try to move our source code to a different licence.

Once we move to a OS code license I ll close this issue.

**Comment by MrTomWhite** [comment]
you're welcome! 

license changes can be a arduous project for an open source project; this issue will probably be open for a while 😎

 I think it's fortunate that you have the license you have because the argument for changing is more straight forward. You don't have to convince people that a change is needed because your project is using a patently inappropriate license. 

The hard part I think is picking a license that matches the values of your community; fortunately that can be worked out.

**Comment by willpatera** [comment]
@MrTomWhite -- the proposed license transition has been posted in our [community forum](https://groups.google.com/d/msg/pupil-discuss/OdaLM-QtcWo/YTuybNEzBwAJ) and is open for discussion. 

Thanks again for raising this issue :smile:

**Comment by mkassner** [comment]
@MrTomWhite -- We changed the license to GPL. 

Thanks for pointing us to this by opening the issue!
