### ISSUE TITLE
Cannot start capture 

### ISSUE THREAD

**Issue by thomasf4231** [pupil-labs/pupil#1707]
Hi, 
I just installed Pupil labs, I can open the Player but I cannot open capture.
I have no experience in coding so I hope to get some help here because i could not find the same issue on the internet.

When I try to open it, it is written:

world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
   File "launchables\world.py", line 136 in world
   File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
   File: "shared_modules\pupil_detectors\__init__.py", in line 21, in <module>
ImportError: DLL load failed

I hope someone can help me to get the program running.
Thank You!

<img width="960" alt="fehlermeldung" src="https://user-images.githubusercontent.com/57033745/67617851-a472be00-f7e7-11e9-819e-326f77e617db.png">

**Comment by pfaion** [comment]
Hi @thomasf4231
this is a known issue, please download and run the vc_redist.x64.exe file from the official Microsoft support page:
https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads
Afterwards, Pupil should start up as expected.

I'm going to close the issue now. If this does not fix your problem, please report back and we will reopen the isse!
