### ISSUE TITLE
linux - flickering when in fullscreen mode

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#171]
Flicker on move a dot in the seek bar or trim marks. Just reporting guys.

Edit.: Player issue.

**Comment by mkassner** [comment]
I can't re-create this. What OS+Hardware?

**Comment by cpicanco** [comment]
ubuntu 14.04.x, 64-bit, 3.7 GiB (RAM)
processor Intel® Core™ i3 CPU M 370 @ 2.40GHz × 4
graphics Intel® Ironlake Mobile (integrated intel graphics)

**Comment by cpicanco** [comment]
I think I should noted the Pupil version (v0.5). So, need test this again.

**Comment by cpicanco** [comment]
I could not replicate this in 0.6x.
