### ISSUE TITLE
Word and Pupil Capture cash after 20min~ of use

### ISSUE THREAD

**Issue by ngohoanganh96** [pupil-labs/pupil#1726]
After around a few minutes of use (10~20min), Word and Pupil Capture eye 1 suddenly cash with "pupil_capture.exe has stopped working" error. When I opened pupil_capture.exe again, it still happened after a couple of minutes even when i didn't recode.
Do someone know what the problem is ?
Thank you in advance.

The specs I use:
pupil_capture_windows_x64_v1.8-4-gbb3bf29
Window 7 Professional 64 bit
Intel Core i7 975
RAM 12GB

![ERROR](https://user-images.githubusercontent.com/52792147/68495842-5e603480-0294-11ea-9b74-163b641dd854.PNG)

![ERROR2](https://user-images.githubusercontent.com/52792147/68495904-76d04f00-0294-11ea-9947-65f649ae01e7.png)

**Comment by papr** [comment]
Officially, we do not support Windows 7. Only windows 10, Ubuntu >16.04, and macos >10.12

**Comment by papr** [comment]
Let us know if the issue persists when using any of the supported platforms.
