### ISSUE TITLE
World Camera not working.

### ISSUE THREAD

**Issue by sparshbaluni07** [pupil-labs/pupil#1732]
Greetings,

Pupil capture is not able to recognize the world camera, when i try to use camera in Real sense viewer it works.
the eye-tracking cameras are working and showing results in pupil capture.
The methods that I have tried;
-Updating the firmware of the camera
-Downloading the latest version of pupil camera and intel realsense viewer sdk.
-replugging the camera

I get this error;
world - [ERROR] video_capture.realsense2_backend: Cannot start pipeline! Flush failed-1072875854

Thanks,

**Comment by pfaion** [comment]
Hi @sparshbaluni07 
I see you closed the issue already again, so I assume your problem is fixed?
Would you mind sharing the solution, so others with the same problems can find this issue for reference?

**Comment by sparshbaluni07** [comment]
Hey there,
After the update I simply replugged the camera and restarted my computer and it started working.
