### ISSUE TITLE
Integrate new cameras to capture the eye

### ISSUE THREAD

**Issue by CobeA527** [pupil-labs/pupil#1734]
Hi everyone, 
Currently my task is to integrate two Basler Ace cameras to capture the pupil/gaze. Can anyone give me an advice where to start ? At which point in the code the cameras are integrated ? Is there something like a programmers guide which provides information on every  .py file ? 

I'm looking forward to your advice 

Cobe

**Comment by papr** [comment]
Hey, if your camera is detected by pyuvc, you can select the camera in the uvc source menus of the eye process windows.

If these cameras do not support uvc you will have to write your own backend. If the lather is the case, let me know.

**Comment by CobeA527** [comment]
The cameras are Gigabit Ethernet Vision cameras, so there's no uvc support. 
Thanks for the fast response :)

**Comment by papr** [comment]
You can use this as a template for a new backend: https://gist.github.com/papr/22ac1d4658166dd8559125ee9b72a1e0

Sorry, it is not well documented. You basically need to implement these classes:
- `Manager`: Plugin that lists available cameras and initialises a `Source` on demand
- `Source`: Plugin instance responsible for fetching `Frame`s from a selected camera
- `Frame`: Represents a single frame and requires a few specific attributes in order to work with Capture

**Comment by CobeA527** [comment]
Ok thank you ! I will work on this !:)

**Comment by CobeA527** [comment]
Hi Papr, 

at the moment my None_UVC_Source initializes the first available camera, but I would prefer that cameras with a specific given ID are initialized. (like its done in  UVC_Source with "uid") 

In which part of the code does the manager passes the parameter "uid" to the source ? I added an entry in the 'settings' dictionary  (function: _activate_source() in None_UVC_Manager) but it seems like it is not passed to my None_UVC_Source.

Best regards,
Cobe

**Comment by CobeA527** [comment]
Hi Papr, 

I integrated the Cameras with the given Backend but it only works in the world process. Any Ideas why it doesn't work in the eye-process ?  Here is my .log File and Code
[none_uvc_backend.zip](https://github.com/pupil-labs/pupil/files/4082858/none_uvc_backend.zip)


[capture_19_01_20_Fail_eye.log](https://github.com/pupil-labs/pupil/files/4082855/capture_19_01_20_Fail_eye.log)

**Comment by papr** [comment]
Hi @CobeA527 Apologies for the delayed response.

User plugins are currently only available in the world process. If you want to run them in the eye process you will to run Capture from source and manually import the plugin in the eye process.
