### ISSUE TITLE
error in open pupil capture[windows]

### ISSUE THREAD

**Issue by BLUEHL** [pupil-labs/pupil#1764]
Hello there,
when I try to directly open pupil capture I get this error;
world - [WARNING] video_capture.uvc_backend: Updating drivers, please wait...
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables\world.py", line 560, in world
  File "shared_modules\plugin.py", line 319, in __init__
  File "shared_modules\plugin.py", line 352, in add
  File "shared_modules\video_capture\uvc_backend.py", line 53, in __init__
  File "shared_modules\video_capture\uvc_backend.py", line 174, in verify_drivers
  File "subprocess.py", line 707, in __init__
  File "subprocess.py", line 990, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

world - [INFO] launchables.world: Process shutting down.
And I have tried to download and run the file vc_redist.x64.exe file from the official Microsoft support page. then the error still exist, and I don't know how to fix it
thank u all~

**Comment by pfaion** [comment]
Hi @BLUEHL 
unfortunately we have an issue with the driver installation for Pupil hardware.
The installation will fail if your downloaded version of Pupil is stored in a folder with non-unicode symbols in it's path. As I assume from you error log that you are working on a chinese system, please make sure that you store Pupil in a place where there's no chinese characters in the full path. Commonly the problem will be your username containing chinese symbols. In this case, please create another folder somewhere on your hard-drive, e.g. directly at `C:\Pupil` where you store Pupil. From there you should be able to execute Pupil and the hardware driver installation should proceed without errors.

**Comment by BLUEHL** [comment]
yes, I have created a folder where there's no Chinese characters, but when I run the bundled software named pupil_capture.exe directly, I still find this error: 
C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268>pupil_capture.exe
world - [INFO] launchables.world: Application Version: 1.19.2
world - [INFO] launchables.world: System Info: User: USER, Platform: Windows, Machine: LAPTOP-HGVIT427, Release: 10, Version: 10.0.18362
world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
Running  PupilDrvInst.exe --vid 1443 --pid 37425
OPT: VID number 1443
OPT: PID number 37425
Running  PupilDrvInst.exe --vid 1443 --pid 37426
OPT: VID number 1443
OPT: PID number 37426
Running  PupilDrvInst.exe --vid 1133 --pid 2115
OPT: VID number 1133
OPT: PID number 2115
Running  PupilDrvInst.exe --vid 6127 --pid 18447
OPT: VID number 6127
OPT: PID number 18447
Running  PupilDrvInst.exe --vid 3141 --pid 25771
OPT: VID number 3141
OPT: PID number 25771
powershell.exe -version 5 -Command "Remove-Item C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\win_drv -recurse -Force;Start-Process PupilDrvInst.exe -Wait -WorkingDirectory \"C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\"  -ArgumentList '--vid 1443 --pid 37426 --desc \"Pupil Cam1 ID2\" --vendor \"Pupil Labs\" --inst' -Verb runas;Remove-Item C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\win_drv -recurse -Force;Start-Process PupilDrvInst.exe -Wait -WorkingDirectory \"C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\"  -ArgumentList '--vid 3141 --pid 25771 --desc \"Pupil Cam2 ID0\" --vendor \"Pupil Labs\" --inst' -Verb runas;"
world - [WARNING] video_capture.uvc_backend: Updating drivers, please wait...
world - [ERROR] launchables.world: Process Capture crashed with trace:

I am not sure Is there a problem with the computer driver because I can run pump_capture.exe from the bundled software on my colleague's computer. Thank you very much for answering my question, I hope you help me to see where the problem is.

**Comment by pfaion** [comment]
Please follow the troubleshoot instructions for Windows:
https://docs.pupil-labs.com/core/software/pupil-capture/#windows
Please ignore step **8.** and instead right-click the file `PupilDrvInst.exe` in the Pupil Capture bundle folder and *Run as Administrator*.
Then try running Pupil Capture again.

**Comment by BLUEHL** [comment]
When I plug my eye-tracking device into my computer, the device manager of the system cannot find libUSBK Usb Devices, which is already showing hidden devices. The device manager only recognizes the three eye-tracking cameras.
![image](https://user-images.githubusercontent.com/47234086/70974763-7c1a8800-20e3-11ea-9c77-9fa796915222.png)
I do n’t know if this error Related to my computer model and driver
my computer is lenovo thinkpad T480, and it's driver is Intel UHD Graphics 620
![image](https://user-images.githubusercontent.com/47234086/70974929-e03d4c00-20e3-11ea-863c-a7d61669dbf6.png)
hoping for your reply, thanks a lot!

**Comment by papr** [comment]
This shows that the driver is installed correctly. Please check if you can select the Pupil Cam ID2 in the uvc manager menu when running Pupil Capture.

Please be aware that the drivers have also been installed for your integrated camera, such that you won't be able to use it with other programs until you uninstall the driver for this specific Device Manager entry.

**Comment by pfaion** [comment]
@BLUEHL 
is Pupil starting now, or do you still get the same error as in the beginning?
As **papr** said, the drivers appear to be correctly installed now.

**Comment by BLUEHL** [comment]
![image](https://user-images.githubusercontent.com/47234086/70994861-0f66b400-210a-11ea-8d86-097bc4f0e9ab.png)
i have uninstall my intergret camera and right-click administrator mode to open PupilDrvInst driver and run pump_capture.exe, but I still get the same error
C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268>pupil_capture.exe
world - [INFO] launchables.world: Application Version: 1.19.2
world - [INFO] launchables.world: System Info: User: USER, Platform: Windows, Machine: LAPTOP-HGVIT427, Release: 10, Version: 10.0.18362
world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
Running  PupilDrvInst.exe --vid 1443 --pid 37425
OPT: VID number 1443
OPT: PID number 37425
Running  PupilDrvInst.exe --vid 1443 --pid 37426
OPT: VID number 1443
OPT: PID number 37426
Running  PupilDrvInst.exe --vid 1133 --pid 2115
OPT: VID number 1133
OPT: PID number 2115
Running  PupilDrvInst.exe --vid 6127 --pid 18447
OPT: VID number 6127
OPT: PID number 18447
Running  PupilDrvInst.exe --vid 3141 --pid 25771
OPT: VID number 3141
OPT: PID number 25771
powershell.exe -version 5 -Command "Remove-Item C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\win_drv -recurse -Force;Start-Process PupilDrvInst.exe -Wait -WorkingDirectory \"C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\"  -ArgumentList '--vid 1443 --pid 37426 --desc \"Pupil Cam1 ID2\" --vendor \"Pupil Labs\" --inst' -Verb runas;Remove-Item C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\win_drv -recurse -Force;Start-Process PupilDrvInst.exe -Wait -WorkingDirectory \"C:\work\pupil_v1.19-2-g4e38268_windows_x64\pupil_capture_windows_x64_v1.19-2-g4e38268\"  -ArgumentList '--vid 3141 --pid 25771 --desc \"Pupil Cam2 ID0\" --vendor \"Pupil Labs\" --inst' -Verb runas;"
world - [WARNING] video_capture.uvc_backend: Updating drivers, please wait...
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables\world.py", line 573, in world
  File "shared_modules\plugin.py", line 341, in __init__
  File "shared_modules\plugin.py", line 374, in add
  File "shared_modules\video_capture\uvc_backend.py", line 72, in __init__
  File "shared_modules\video_capture\uvc_backend.py", line 193, in verify_drivers
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1017, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

world - [INFO] launchables.world: Process shutting down.

until now, i have never use the pupil labs successufully in my computer, i have no idea, and one thing is that the capture interface has been successfully opened for the first time on my colleague's computer.
![image](https://user-images.githubusercontent.com/47234086/70995200-f3afdd80-210a-11ea-95fd-73b7698286ac.png)
My device manager does not pop up a separate libusbk usb device
thank u all for answering my question, now i have no idea...

**Comment by pfaion** [comment]
@BLUEHL 
I have another idea: can you try creating a new user account on your computer that does not use chinese characters in the user name and try opening capture while logged into that user?
It could be that the drivers installation still has problems with your username, even though you are starting it from a different location now.

**Comment by pfaion** [comment]
Also: what version of Windows are you using?

**Comment by BLUEHL** [comment]
![image](https://user-images.githubusercontent.com/47234086/70998543-8d2ebd80-2112-11ea-98e2-2b8227f0e40d.png)
win10,thanks u for answering, and my current user account has already in no chinese, and i will take your suggestions to creat a new nonchinese user account, if it helps, i will be very appreciated, thanks~

**Comment by pfaion** [comment]
Can you try running the whole application as administrator?

**Comment by BLUEHL** [comment]
![image](https://user-images.githubusercontent.com/47234086/71069105-0a117400-21b3-11ea-9476-75b84834f4f9.png)
I have newly created an administrator user account with no Chinese characters in HU. Place the downloaded pump v1.19 on the desktop (it will not work even if you try v1.12), right-click the administrator mode and open the driver PupilDrvInst.exe, Make sure that the device manager has recognized the three cameras and uninstalled the computer ’s own camera. Enter command line mode and run pump_caprure.exe, and still have the previous error.
![image](https://user-images.githubusercontent.com/47234086/71069616-121de380-21b4-11ea-9827-9dafdc19ca22.png)

 I want to have a remote operation with you to solve my problem. It ’s weird. My colleague's computer can run normally. I hope this problem can be solved well. Thanks again, and I hope to get your reply.

**Comment by BLUEHL** [comment]
I have newly created an administrator user account with no Chinese characters in HU. Place the downloaded pump v1.19 on the desktop (it will not work even if you try v1.12), right-click the administrator mode and open the driver PupilDrvInst.exe, Make sure that the device manager has recognized the three cameras and uninstalled the computer ’s own camera. Enter command line mode and run pump_caprure.exe, and still have the previous error. I want to have a remote operation with you to solve my problem. It ’s weird. My colleague&#39;s computer can run normally. I hope this problem can be solved well. Thanks again, and I hope to get your reply. I explained my problem on the github Q &amp; A,  email you again that  whether a remote operation can be performed at a time to determine where the problem occurs...hoping to get your reply.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pablo&nbsp;Prietz"; 
发送时间: 2019年12月17日(星期二) 下午3:50
收件人: "pupil-labs/pupil";
抄送: "BLUEHL"<1264476105@qq.com>;"Mention";
主题: Re: [pupil-labs/pupil] error in open pupil capture[windows] (#1764)




This shows that the driver is installed correctly. Please check if you can select the Pupil Cam ID2 in the uvc manager menu when running Pupil Capture.
 
Please be aware that the drivers have also been installed for your integrated camera, such that you won't be able to use it with other programs until you uninstall the driver for this specific Device Manager entry.
 
&mdash;

**Comment by pfaion** [comment]
@BLUEHL 
I am very sorry for the problems you are experiencing. I tried running Pupil on a clean machine without drivers and had no problems with the installation process. I suspect it might be something specific about your setup that causes the problems.

Just to be clear: you tried running `pupil_capture.exe` as Administrator as well, correct?

Also: we had cases in the past where a very restrictive anti-virus software could mess up the driver installation procedure. Can you try disabling your anti-virus software and run `pupil_capture.exe` as Administrator again?

**Comment by BLUEHL** [comment]
Yes, on my newly created administrator account named HU, I first quit all hardware protection programs such as Computer Manager and Master Lu, and then uninstalled the device manager and scanned to three cameras. Right-click the administrator to open PupilDrvInst.exe , Right-click the administrator mode to open pump_capture.exe, while the previous error exist, I successfully run the same operation on a colleague's computer, I was wondering if it is related to your computer model and driver, thank you for your reply

**Comment by willpatera** [comment]
@BLUEHL Questions and notes:
1. Hardware: It looks like all cameras are working from what we can see in the device manager, so this is not a hardware problem. :heavy_check_mark: 
2. Drivers: It looks like all drivers are installed successfully for Pupil Cam* cameras under libusbK category, so this not a driver problem. :heavy_check_mark: 
3. Windows and permissions:
    1. Can you confirm that you ran Pupil Capture on a colleague's **Windows 10** computer and that all cameras were being shown in Pupil Capture UI? 
    2. 系统找不到指定的文件 --> The system can not find the file specified -- this very much looks like a file/permissions issue with Windows. You noted that you ran as administrator, but it very much seems like this is related to your version/installation of Windows 10. If this is indeed the case, then we will not be able to help you unfortunately. 

Looking forward to your response!

**Comment by BLUEHL** [comment]
thank u for your reply.
1. The picture showing libusbK normally runs on my colleague home version win10 computer. My own win10 home version computer is inserted into the pump labs device manager. There is no directory of libusbK. This is very strange. I do n’t know if it is a driver issue. , But there are three cameras displayed normally under the camera.
2. My win10 home edition is provided on the official website and is also genuine. I also determined that the pump_capture.exe file opened in administrator mode

**Comment by willpatera** [comment]
@BLUEHL thanks for the clarification. The reason there is no `libusbK` category and no devices in `libusbK` category in your Device Manager is likely due to a permission error. Your Win 10 system seems to be blocking driver installation and/or access to other files needed to verify driver installation.  

Here is what I would recommend that you try:
1. Download [Zadig](https://zadig.akeo.ie/) and manually install libusbK drivers for each Pupil Cam* device. 
2. Check Device manager. Pupil Cam* devices should appear under libusbK category. 
3. Start pupil_capture.exe as administrator. This _might_ still fail due to permissions errors that are specific to your OS setup.

**Comment by BLUEHL** [comment]
I successfully driven the three cameras to form a libusbk directory under the device manager through your solution, but the administrator still has problems running pump_capture.exe, even though I have closed all hardware protection programs and windows security protection center.

world - [INFO] launchables.world: Application Version: 1.19.2
world - [INFO] launchables.world: System Info: User: USER, Platform: Windows, Machine: LAPTOP-HGVIT427, Release: 10, Version: 10.0.18362
world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.

 the error shows This message in the message also seems to remind the version of the problem, can you please help me remotely check if it is a version problem, if you can, thank you very much, because I really want to know where the problem is, if it is true It ’s a version issue. I want to ask if reinstalling the system can help. I look forward to your reply.

**Comment by BLUEHL** [comment]
![image](https://user-images.githubusercontent.com/47234086/71387741-4f5cf800-2630-11ea-8ff3-ae00f76c62ad.png)
I found another problem. Even if I drive three cameras in the libusbk directory, the interface displays (interface 0) behind the camera, which indicates that the driver is still incorrect.

**Comment by papr** [comment]
@BLUEHL Hey, I have a short question. I would like to make sure that the following is just a spelling mistake:
> pump_capture.exe

The correct file to run is `pupil_capture.exe`. Can you confirm that you were using `pupil_capture.exe` and not `pump_capture.exe`?

**Comment by papr** [comment]
#1833 should have fixed this issue. Please give Pupil Capture [v1.23-4 or later](https://github.com/pupil-labs/pupil/releases/latest) a try.
