### ISSUE TITLE
run captrue.bat from source code, launchables.world: Process shutting down.

### ISSUE THREAD

**Issue by BLUEHL** [pupil-labs/pupil#1765]
hi, everyone, When I run captrue.bat from source code, there are some error occured

C:\Users\44346\pupil\pupil_src>python main.py capture
world - [INFO] numexpr.utils: NumExpr defaulting to 8 threads.
world - [INFO] launchables.world: Application Version: 1.19.7
world - [INFO] launchables.world: System Info: User: USER, Platform: Windows, Machine: LAPTOP-HGVIT427, Release: 10, Version: 10.0.18362
world - [INFO] pupil_detectors.build: Building extension modules...
cl: 命令行 warning D9025 :正在重写“/W3”(用“/w”)
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
error: command 'D:\\VS community2017\\data\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\Users\44346\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 13, in <module>
    from pupil_detectors.detector_2d import Detector_2D
ModuleNotFoundError: No module named 'pupil_detectors.detector_2d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\44346\pupil\pupil_src\launchables\world.py", line 138, in world
    import pupil_detectors
  File "C:\Users\44346\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 18, in <module>
    build_cpp_extension()
  File "C:\Users\44346\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 32, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "E:\Anaconda3\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "E:\Anaconda3\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['E:\\Anaconda3\\python.exe', 'setup.py', 'install', '--install-lib=C:\\Users\\44346\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.

I referenced the solution in the problem, but it was not successful, I do n’t know if the problem I encountered is a duplicate, I hope to get a definite solution, if anyone can help me, thank you very much

**Comment by pfaion** [comment]
Hi @BLUEHL

first: do you need to run Pupil from source for your use case? Setting this up correctly on Windows needs a bit of work. If you don't need to modify the source code, I'd highly recommend just using our pre-built bundles for Windows. If this is an option for you, please ignore the rest of this message!

Regarding your problem:
You are getting an error when Pupil is trying to build the internal Pupil Detectors module. With the last release (v1.20) we externalized this module into a separate python package that you can install via pip. Unfortuantely we have not yet updated the documentation, but I recommend you try downloading the latest version of Pupil from GitHub and install all necessary dependency setup for windows **except the section `Modify pupil_detectors setup.py`** from this document: https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md
Then afterwards you will have to install the new pupil detectors python package with
```bash
pip install pupil-detectors
```

After this you *should* be good to go. I'll close this issue for now. Please give this a try and report back if you are still having issues.
