### ISSUE TITLE
Cannot modify ROI

### ISSUE THREAD

**Issue by bpinsard** [pupil-labs/pupil#1777]
I am running from the most recent sources on master branch, and the blue handles of the ROI box in the eye window cannot be moved anymore. Is it only with my setup?
It seems that it happened in the past : https://github.com/pupil-labs/pupil/issues/563 

Thanks

**Comment by pfaion** [comment]
Thanks for reporting this issue, this is indeed an unfortunate regression.
I have prepared a quick fix for this problem, see PR #1778 

You can either check this out directly, or wait until it is merged.
Please note that the active development takes place on the **develop** branch. This is where this fix will get merged into. On **master** you will always find the latest released version.

**Comment by papr** [comment]
The fix has been release in v1.21
