### ISSUE TITLE
Freezing pupil_player_0.5.5-1_Linux_X64.deb - Not working

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#178]
Hi there,

i noticed a heavy bug in PupilPlayer v.0.5.5 for Linux
While exporting a video the memory usage raises until the system crashes because of full memory.
If you use small videos to export you will not notice the issue.

Everything is working fine with the prior version.

Regards

**Comment by mkassner** [comment]
I can reproduce this bug on my virtual machine. This bug does not happen on MacOS.

**Comment by mkassner** [comment]
I see this bug in v5.5 and v5.4 it is related to PyAV the lib we use to write videos.

**Comment by mkassner** [comment]
I will bundle a new version of player using a newer version of libav tomorrow morning.

**Comment by mkassner** [comment]
I think I just fixed this here: f6aeb2ceecefaa5a165155a31dc0dc8862174f2e

It was not related to pyav/avlib at all but rather a deepcopy call in scan_path.py.

**Comment by fneitzel** [comment]
I'd like to confirm that previous unexportable videos are exportable now with the latest version.
