### ISSUE TITLE
How to convert time? 

### ISSUE THREAD

**Issue by karliell** [pupil-labs/pupil#1780]
Hi! I'm hoping to convert between several "time" in these files. 
My question is:
How to convert the `pupil_timestamp`  in `pupil_position.cvs` to the real time such as:
**01:23.453
(if the Relative Time Range is 00:00.000 -   02:33.069)**

I found someone did the similar thing but I didn't find `info.cvs` and these data. 
May I ask how can I get these data? Would you please elaborate on these?
```
start_time_system = 1533197768.2805 # unix epoch timestamp
start_time_synced = 674439.5502 # pupil epoch timestamp
```

and 
```example_timestamp = 674439.4695 ``` is :

![image](https://user-images.githubusercontent.com/36145675/71646186-e28dd180-2cb1-11ea-8828-c7db38433a23.png)
 in `pupil_position.cvs` is that right?
Thank you so much!!! I‘m totally confused by the timeframe.

_Originally posted by @karliell in https://github.com/pupil-labs/pupil/issues/1500#issuecomment-570084141_

**Comment by pfaion** [comment]
Hi @karliell
The script that you need can be found already in the other issue you found (#1500)
```python
import datetime
start_time_system = 1533197768.2805 # unix epoch timestamp
start_time_synced = 674439.5502 # pupil epoch timestamp
offset = start_time_system - start_time_synced
example_timestamp = 674439.4695
wall_time = datetime.datetime.fromtimestamp(example_timestamp + offset).strftime("%Y-%m-%d %H:%M:%S.%f")
print(wall_time)
# example output: '2018-08-02 15:16:08.199800' 
```
This script needs the `start_time_system` and `start_time_synced` time information. You can find these in the recording info file in the folder of your recording. For newer versions of Pupil this file is called **info.player.json**.

The `example_timestamp` is the one that you took from `pupil_positions.csv` and that you want to convert to a readable format.

**Comment by karliell** [comment]
Thank you so much!!! You are so supportive. Just a quick question. May I ask can I get this kind of time directly? 
**01:23.453
(if the Relative Time Range is 00:00.000 - 02:33.069)**
Or I have to do subtraction to get this time period.

**Comment by pfaion** [comment]
Ah ok, if you just want the relative time, you don't need the `start_time_system`. Sorry I did not read your question clearly :sweat_smile:. You can just do:

```python
import datetime
start_time_synced = 674439.5502  # read from info file
example_timestamp = 674456.4695  # read from export
duration = example_timestamp - start_time_synced

duration_string = datetime.datetime.fromtimestamp(duration).strftime("%M:%S.%f")
print(duration_string)
```
This example will print **00:16.919300**
