### ISSUE TITLE
ERROR in carlibration

### ISSUE THREAD

**Issue by 11gan6** [pupil-labs/pupil#1791]
Hi,
I'm trying to use the Pupil Capture to show the calibration result of the scene named 'GazeDemoScene' and I find that the trajectory of the red dot is opposite to the trajectory of the calibration eye movement.

So how can I adjust the settings in the Pupil Capture?
Thanks
![1](https://user-images.githubusercontent.com/50435482/72660470-88a73e80-3a09-11ea-9df0-2f157b15cdf0.png)
![2](https://user-images.githubusercontent.com/50435482/72660473-8e9d1f80-3a09-11ea-9a6e-e20a608e7136.png)

**Comment by papr** [comment]
Please be aware that the gaze (red dot in World window) is not calibrated by default. In this case, the gaze point does not match the actual gaze movement of the subject. This only changes once the calibration has been performed successfully. With other words, the observed behavior is expected during a calibration. Please let us know if this behavior continues to exist after the calibration has finished. In this case, please share the `capture.log` file (`Home directory -> pupil_capture_settings`) below. Then we can reopen the issue and look into potential issues of the unexpected behavior.
