### ISSUE TITLE
fixations report inconsistency

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#180]
There is inconsistency between the data generated by the `Dispersion_Duration_Fixation_Detector. export_fixations` method and the data generated by the `Offline_Marker_Detector.save_surface_statistics_to_file` method, for example:

**Dispersion_Duration_Fixation_Detector. export_fixations**
id
86
87
88
89
90

**Offline_Marker_Detector.save_surface_statistics_to_file**
id
85
86
87
88
89
90
91

**Comment by cpicanco** [comment]
Missing data on **Dispersion_Duration_Fixation_Detector. export_fixations**, problem may be there.

**Comment by cpicanco** [comment]
Problem occurs when using sections.

**Comment by cpicanco** [comment]
I am not sure why, but the following tweak worked:
```python
            if out_mark == frame_count:
                last_f = last_fixation['id']+1
            elif out_mark < frame_count:
                last_f = last_fixation['id']+2

            if in_mark == 0:
                first_f = first_fixation['id']
            elif in_mark > 0:
                first_f = first_fixation['id']-1

```

**Comment by cpicanco** [comment]
No, I am wrong, it did not work. Lets see if the **Offline_Marker_Detector.save_surface_statistics_to_file** is returning duplicates from section to section. For example:

100-200
201-300
301-400

**Comment by cpicanco** [comment]
Section logic of the fixation_detector.py

```python
            for f in self.fixations:
                if f['start_frame_index'] >= in_mark:
                    first_fixation = f
                    break
            for f in self.fixations[::-1]:
                if f['end_frame_index'] <= out_mark:
                    last_fixation = f
                    break
```

**metrics_36-365/fixation.cvs**

id   | first frame | last frame
--- | ----- | -----
4  | 47   | 58
21 | 225 | 312

**metrics_366-845/fixation.cvs**

id   | first frame | last frame
--- | ----- | -----
23 | 380 | 445
50 | 823 | 834

**missing fixations**

id   | first frame | last frame | delta | frames within section 1* | frames within section 2*
--- | ----- | ----- | ---- | ---- | ----
22 | 317 | 379 | 62 | 48 | 14

frame | world_timestamp | gaze_timestamp (fixation)
---- | ---- | ----
317 | 4603.1353121820002 | 4603.1412797989997
365 | 4604.7353279709996 | 
366 | 4604.7672219509996|
379 | 4605.2032691149998 | 4605.2092276670001

As you can see fixation with id 22 is not being captured by the fixation detector logic because it is distributed along two sections; its first frame (317) within 36-365 and its last frame (379) within 366-845. I would include the fixation 22 in the first section, since the fixation stays longer in this section.

No problem in discard some data, but one should do it consistently. So, the problem is that the marker detector is following another logic:

```python

    fixations_on_surface = []
    for idx,ref_srf_data in zip(range(len(self.g_pool.timestamps)),s.cache):
        if in_mark <= idx <= out_mark:
            if ref_srf_data is not None and ref_srf_data is not False:
                for f in s.fixations_on_srf_by_frame_idx(idx,ref_srf_data['m_from_screen']):
                    fixations_on_surface.append(f)

    removed_dublicates = dict([(f['base']['id'],f) for f in fixations_on_surface]).values()
    # logger.debug("fixation range to export %s - %s"%(removed_dublicates[0]['base']['id'],removed_dublicates[-1]['base']['id']))
    
```
The exporter of the marker detector will include the fixation 22 in the second section, and will report all fixations even with very close sections  (100-200, 201-202...).

**Comment by mkassner** [comment]
Hi I'll have a look at this.

**Comment by cpicanco** [comment]
Thank you Moritz!

**Comment by cpicanco** [comment]
I think this issue is the last thing remaining before a bug free multi section functionality.

**Comment by mkassner** [comment]
I think this should be fixed now.
