### ISSUE TITLE
run Pupil from command line on WIN 10

### ISSUE THREAD

**Issue by stino78** [pupil-labs/pupil#1808]
Hi, I am trying to run Pupil Capture from code, but I have (at least) one error.

**Here's my configuration:**
- Windows 10 64 bit
- Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

**The error is:**
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\work\pupil\pupil_src\launchables\world.py", line 119, in world
    from pyglui import ui, cygl, __version__ as pyglui_version
ImportError: DLL load failed: %1 is not a valid Win32 application.

**The wheels for the dependencies were not installing, all with the same error:** 
ERROR: XXX.whl is not a supported wheel on this platform.
So I build and installed them from source. I can tell you that pyglui is built as 64 bit, so it is not a Win32 application for sure...

**My question are:**
- why the wheels are not installing?
- what architecture should I compile for? 32 or 64 bits?
- is the python version ok, or should I downgrade to 3.6?

Thank you,

Agostino

**Comment by papr** [comment]
Hi @stino78 
1) As you noted, the wheels are compiled for 64bit only and you have installed a 32 bit Python version. These are incompatible.
2) Please install a 64bit Python version
3) The Python version should be ok as it is.

Generally, we recommend to run from source though. Nearly everything can be implemented either as a plugin or via our network API. Neither requires to run from source (with only very specific exceptions). See our documentation here: https://docs.pupil-labs.com/developer/core/overview/

**Comment by stino78** [comment]
Hi @papr 

thank you for the quick reply!!

Where it say: MSC v.1915 **64 bit (AMD64)**

doesn't it mean that it is a 64 bit version?

I am asking because I installed the 64 bit version of Anaconda, so that's what should be.


What I am doing is to implement a new calibration procedure, and my understanding is that I need to run Pupil from source to be able to do it. Is it right?

THank you again,

Agostino

**Comment by pfaion** [comment]
Hi @stino78 
can you run the following line in the Python shell:
```python
import struct; print(struct.calcsize('P')*8)"
```
Or run this in the shell:
```bash
python -c "import struct; print(struct.calcsize('P')*8)"
```
This will print either **32** or **64**, indicating your installed Python architecture.

**Comment by pfaion** [comment]
Besides that:
if you do not modify existing source code, you do not need to build from source. We have a plugin load mechanism, which allows you to load custom plugin code even when running from the compiled bundle. All you need to do is putting your plugin code in:
```
HOME > pupil_capture_settings > plugins
```
When developing plugins for Player, use the folder `pupil_player_settings`.
All Python classes that inherit from our `Plugin` class https://github.com/pupil-labs/pupil/blob/f3a48dfa38d706c09c1cdb571b4d578e8d1b5528/pupil_src/shared_modules/plugin.py#L25
will be loaded into Pupil Capture upon start. You can enable your custom plugin like any other plugin in the PluginManager menu.

As you can see, our calibration procedures are also only Plugins, so you can try to mimic how they work.

**Comment by stino78** [comment]
Hi @pfaion 

Thanks for the help, this is very interesting!

I guess that just as I can do a plugin for the calibration, I can do the same thing for using a different world camera, or for modifying an existing one.

Specifically for this last thing, I want to make a very simple change, that is to use the Realsense D435, but configuring the IR camera as world camera.

Wolud his bea new plugin? Do you want me to open a new issue for this?

Thank you,

Agostino

**Comment by pfaion** [comment]
Making a new plugin (from copying an existing one) will make it easier as you don't modfiy Pupil source code and can thus very simple pull updates from us. Otherwise you will have to merge your modifications and our updates, which might be tedious.

As a side-node: If you want to support a new camera, you will have to implement a backend Plugin. The logic of backend plugins has been refactored quite a bit recently in order to make it more user friendly. The new code has not yet been released, so it's not yet on the master branch. But we already merged it into develop and will release it with the next release.

**Comment by stino78** [comment]
Hi @pfaion 

That's great news, thank you!

Considering the backend plugin for a possible new camera, if this camera is a Realsense D400, does it work if I modify the realsense_backend.py file that is already in the Pupil Capture folder?

**Comment by PWaRoo** [comment]
Hi @pfaion, 
could you estimate for me if the refactoring of the backend plugins will effect the picoflexx plugin? 
cheers Peter

**Comment by papr** [comment]
All previous backends are effected since the `Base_Source` class has changed. You can still run all previous backends as plugins by including the code of the previous `Base_Source` in your plugin file. @pfaion maybe, we can make a short example that shows that?

**Comment by PWaRoo** [comment]
Ah thank @papr, 
I have seen you started to work on integration of other pupil detection methods, do you? I have a nice test setup and would like to test them concurrently. But using the picoflexx, Will that be possible with the old backends?

**Comment by pfaion** [comment]
@papr yes we should make sure to give a few examples when releasing. Maybe in the release notes?

**Comment by pfaion** [comment]
@PWaRoo The backends are independent of the pupil-detectors. It should be no problem to mix-and-match as you like.
