### ISSUE TITLE
Linux UVC Bandwidth - Patch doesn't apply 

### ISSUE THREAD

**Issue by rokigeorg** [pupil-labs/pupil#181]
Hey, 

I found an issue while trying to modify the UVC driver on a RaspberryPi 2 (Ubuntu 14.4).
Everything went fine until I typed in the following command:

`git apply --ignore-space-change --ignore-whitespace mjepg_bandwidth.patch `

It accord the following error message:
```
error: patch failed: drivers/media/usb/uvc_video.c119
error: drivers/media/usb/uvc/uvc_video.c: patch doesn't apply
 ```

I raised this issue because it was written to do so if your patch doesn't apply for you.

Thanks in advance ...

**Comment by mkassner** [comment]
Hi,

We don't use v4l2 anymore. Patching is no longer required.

Is there a reason you are still using this?

M

**Comment by mkassner** [comment]
I have removed the patch instructions and will close this issue. As it no longer applies.
