### ISSUE TITLE
How to relate audio events to timestamps

### ISSUE THREAD

**Issue by d-arzounian** [pupil-labs/pupil#1815]
I am trying to compare the timings of recorded annotations and of audio events recorded with the audio capture plugin. However, the audio_timestamps.npy file contains way less timestamps than there are audio samples in the audio.mp4, so I am not sure how to interpret and use those audio timestamps. Could you please suggest how to proceed?
Thanks in advance for any assistance.

**Comment by papr** [comment]
Hi @d-arzounian 
Apologies for the very delayed response.

Pupil Capture/Mobile save a timestamp for each audio *frame*. Each audio frame usually consists of a fixed number of evenly spaced audio *samples* (temporal space between samples depends on audio sampling frequency). Combining both pieces of information, audio frame start and sample position within the frame, you can calculate the timestamp of each sample.
