### ISSUE TITLE
What does it mean "Gaze timestamps are not unique"?

### ISSUE THREAD

**Issue by aopichugina** [pupil-labs/pupil#1819]
It says "Gaze timestamps are not unique. If you are using offline calibration, please disable all but one gaze mapping section". Still don't understand what I should do.
![image](https://user-images.githubusercontent.com/53140778/75319735-4251c480-587e-11ea-9d89-465cc881216b.png)

**Comment by romanroibu** [comment]
Hi @aopichugina 

Could you please make a recording reproducing this issue and send it to `data@pupil-labs.com`? Thank you!

**Comment by gponsr** [comment]
Hi @aopichugina 

I have the same problem. Did you find a solution for this?

Thanks!
