### ISSUE TITLE
Delete annotations

### ISSUE THREAD

**Issue by mihaelataranu** [pupil-labs/pupil#1820]
Hi, 
We need to code some videos in Pupil Player and we have lots of behavioral codes (more than 30). The error rate when coding the behaviors is very high (i.e, pressing on the wrong code).  We need to delete a lot of annotations from the annotations.csv file after the export. We would like to find a way to delete permanently the wrong codes and when launch the video again to have only the right annotations on the pupil player video. Is there a way to do this?
Thank you very much in advance!
mihaela

**Comment by papr** [comment]
Hi @mihaelataranu 
Thank you very much for your detailed description of your workflow.

Unfortunately, currently, there is no way to delete annotations from within the Pupil Player application.

We will consider your feedback and look into options on how the situation can be improved.

**Comment by mihaelataranu** [comment]
Dear Pablo, 
Thank you so much for the very speedy response. We know that it is not possible from within the Pupil Player application. What we would like to know if there is any possibilty to delete them from outside of the application and then when played again in the application to have a video only with the annotations we want to keep.
Thank you again.

**Comment by papr** [comment]
@mihaelataranu Ah, apologies. I misunderstood the question. Technically it is possible but will require you to write code that modifies the annotation cache.

On shutdown, Pupil Player caches all annotations to the `annotation_player` file within the recording. You can modify the file and reopen the recording in Player afterward.

This is how you can read the file:
```py
annotations = fm.load_pldata_file(recording_dir, "annotation_player")
annotations.timestamps  # list of all timestamps
annotations.data  # list of actual annotation objects
```
Both lists need to be kept in sync, i.e. if you remove an entry from `annotations.timestamps` then the same entry in `annotations.data` needs to be removed, too.

This is how you can write the file:
```py
with fm.PLData_Writer(recording_dir "annotation_player") as writer:
    for ts, annotation in zip(annotations.timestamps, annotations.data):
        writer.append_serialized(ts, "annotation", annotation.serialized)
```

`fm` refers to this module: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/file_methods.py
```py
import file_methods as fm
```

**Comment by mihaelataranu** [comment]
Thank you for the response, Pablo. This is what I wanted to find out.
