### ISSUE TITLE
Python install dependencies

### ISSUE THREAD

**Issue by MenosGrandes** [pupil-labs/pupil#1821]
Hi,
Why there is no requirements.txt (https://pip.pypa.io/en/stable/user_guide/) for all dependencies for new versions for PupilLabs? Or even the installation script which will install all dependencies, either C++/Python/Cython or whatever it is?

MG.

**Comment by pfaion** [comment]
Hi @MenosGrandes 

we're actively working on making running Pupil from source easier. The biggest problem is that there are a lot of differences in installation between platforms. Particularly the Windows has been rather complex. The plan is to get to a fully automated installation / dependency-setup at some point, but we are not there yet.

Your idea with a requirements.txt file would make the situation a bit better, agreed. However, it would only account for Python dependencies for now. We'll consider adding that.

**Comment by MenosGrandes** [comment]
Thanks for answer.
But why to bother to do only one installation script? Couldn't be easier to do the platform dependence script? One for Linux based in APT, one for YUM/DNF and other for Windows using Anaconda or any other package manager?

**Comment by pfaion** [comment]
We are extracting parts of Pupil into separate Python libraries. This makes it easier to re-use code for future projects and also for our R&D team to work on those parts outside of Pupil. When this is done, Pupil should have become a pure Python application, removing the need to do any platform-specific setup at all. Currently we focus rather on getting rid of the platform-specific parts than on spending time on making them easier to setup.
