### ISSUE TITLE
Iterative Calibration / Online Learning ?

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/pupil#1822]
In our experiments we have periods of data where we are reasonably confident that the user is fixating at a particular location. We would like to use these data to _update_ the calibration. One implementation that I'm thinking about is writing a plugin named something like `HMD_Calibration_3D_Iterative` with the following features:
* maintain a FIFO buffer of pupil data of X seconds
* response to `calibration.add_ref_data` draws from the above buffer
* respond to a new notification: `calibration.should_update`  uses the ref_data to fit or update the model.

It's up to my task to know when are good periods of data worth sending for calibration.

If I can linearize the model, then there are some intuitive tools like `sklearn.linear_model.SGDRegressor` that would handle this problem easily, but I think linearizing the model is rather tricky.

I can try continuing to use scipy.optimize.least_squares, saving the output of the (t-1)'th iteration and using it as the initial_guess for the t'th iteration. But I feel like this is missing something (e.g. weighting the residuals?). Can anyone who has more experience with scipy.optimize.least_squares offer any insights?

Alternatively, I could keep a record of all the calibration data then recalibrate using the whole thing on `should_update` notification. (Other details: can drop old samples if based on age, residual value, and spatial extent).

Anyway, before I dive into that, I was hoping that someone could comment on the whole Choreography and Gazer thing. If the calibration routines and gaze mapping are about to change drastically then I'll wait until after that is done.

**Comment by papr** [comment]
Hey @cboulay,
I would highly recommend to wait until the chroeography/gazer rework is through. It will simplify your work by a lot!

**Comment by 962557346** [comment]
> Hey @cboulay,
> I would highly recommend to wait until the chroeography/gazer rework is through. It will simplify your work by a lot!

Well, I think new pupil_detectors was packaged perfectly, which reduces the coupling of different modules. I want to know when the calibration module and gaze mapping module can be also packaged completely.

**Comment by peteratBHVI** [comment]
> Hey @cboulay,
> I would highly recommend to wait until the chroeography/gazer rework is through. It will simplify your work by a lot!

please keep me in the loop! or hast this been finalized?

**Comment by papr** [comment]
@cboulay @peteratBHVI We are getting closer to being finished with #1802 The gazer api is pretty much finished. You should be able to run custom gazers in Capture and Player by placing the code into the user plugin folder. You can use [`gazer_2d`](https://github.com/pupil-labs/pupil/blob/restructured-gaze-calibration-and-mapping/pupil_src/shared_modules/gaze_mapping/gazer_2d.py) as an example implementation.

**Comment by 962557346** [comment]
> @cboulay @peteratBHVI We are getting closer to being finished with #1802 The gazer api is pretty much finished. You should be able to run custom gazers in Capture and Player by placing the code into the user plugin folder. You can use [`gazer_2d`](https://github.com/pupil-labs/pupil/blob/restructured-gaze-calibration-and-mapping/pupil_src/shared_modules/gaze_mapping/gazer_2d.py) as an example implementation.

Hey, did you remove the #1802 and gazer_2d ? I can't find it. So has the gazer api been finished?

**Comment by papr** [comment]
@962557346 We have merged into the develop branch. Therefore, it became part of #1867

**Comment by papr** [comment]
With #1867, the gazer rework became part of the released software. We highly recommend building custom gazer ideas as sharable user plugins. This makes it easy to extend the existing software and does not require people to use a specific version.
