### ISSUE TITLE
Frame rates and timespan comparison between Pupil Player and BORIS

### ISSUE THREAD

**Issue by mihaelataranu** [pupil-labs/pupil#1824]
Hi, 
I would really appreciate your help with this issue. We want to use a behavioral software to make annotations on the recordings made with Pupil Capture (unfortunately Pupil Player is not ideal for our experiment).
So we export the world.mp4 videos and play them in BORIS to make the annotations. When fixations on new objects occur we'll make new annotations. Now, I am having a difficult time understanding why there are differences in the timing of the frames when I play the recordings in BORIS and in Pupil Player. 
I have a recording that lasts 03.05 minutes, at a frame rate of 23.28. The recording has 4312 frames is both software. However, the exact time (in seconds/milliseconds) for each frame is very different across the two software. As I want to merge the annotated data from BORIS with durations from the fixation file, I would need to make the two software to play the video and show me the same times. Do you have any suggestions for how shall I approach this problem?

**Comment by papr** [comment]
Hi @mihaelataranu 

Unfortunately, I do not know the BORIS software and how it calculates the timestamps. But I might be able to help you with the Player timestamps. Could you specify which timestamps you are referring to and how you compare them? Ideally, attach a screenshot or a csv file of the timestamps. Also, could you please share the `info.csv`/`info.player.json` file of your recording with us?

**Comment by mihaelataranu** [comment]
Hi @papr,
Please see for comparison a series of screenshots of the frames/timing when scrolling through the same video in Pupil labs and Boris.  I made a red drawing for comparison of the same frame in the two software. The timing of the scrolling differs at different frames, as well as the fixation number.
<img width="720" alt="1 Boris_frame0" src="https://user-images.githubusercontent.com/7983736/76206679-c56b0700-61fc-11ea-94bd-3fd68725d81f.png">
<img width="955" alt="2 PupilLabs_frame0" src="https://user-images.githubusercontent.com/7983736/76206680-c6039d80-61fc-11ea-8b13-390757f83445.png">
<img width="720" alt="3 Boris_frame1" src="https://user-images.githubusercontent.com/7983736/76206682-c69c3400-61fc-11ea-9a49-112a5d64e6dc.png">
<img width="955" alt="4 pupilLabs_frame1" src="https://user-images.githubusercontent.com/7983736/76206683-c69c3400-61fc-11ea-89c8-2c44fad826e9.png">
<img width="955" alt="5 PupilLabs_frame2" src="https://user-images.githubusercontent.com/7983736/76206686-c734ca80-61fc-11ea-8ac4-e863f3d71ecd.png">
<img width="720" alt="6 Boris_frame2" src="https://user-images.githubusercontent.com/7983736/76206687-c734ca80-61fc-11ea-927b-c87423e09b7d.png">
<img width="939" alt="7 Boris_frame1094_fixation226" src="https://user-images.githubusercontent.com/7983736/76206689-c7cd6100-61fc-11ea-995d-29b206587765.png">
<img width="960" alt="8 PupilLabs_frame1094_fixation231" src="https://user-images.githubusercontent.com/7983736/76206690-c7cd6100-61fc-11ea-8dc4-896a088f5899.png">
<img width="939" alt="9 Boris_frame2141_fixation435" src="https://user-images.githubusercontent.com/7983736/76206691-c7cd6100-61fc-11ea-9454-c56b009fa8f8.png">
<img width="960" alt="10 PupilLabs_frame2141_fixation448" src="https://user-images.githubusercontent.com/7983736/76206692-c865f780-61fc-11ea-96dc-c31bb499a125.png">

the info.player.json file zipped here:

[info.player.zip](https://github.com/pupil-labs/pupil/files/4306198/info.player.zip)

**Comment by papr** [comment]
@mihaelataranu Hi, apologies for the delayed response.

Please keep in mind that Player previews the world video from the intermediate recording format while BORIS is working on the exported video. These videos are not guaranteed to have the same amount of frames due to the transcoding happening during the export.

Please use the relative timestamp to find corresponding frame pairs instead of the frame number.

**Comment by papr** [comment]
[Here](https://gist.github.com/papr/c123d1ef1009126248713f302cd9fac3) you can find a small plugin that renders the current Pupil Player frame index into the exported video. I hope this helps you to identify the correct frames in BORIS.

Copy the file into `Home directory -> pupil_player_settings -> plugins`, start Pupil Player, and enable the "Frame Index" plugin from the Plugin Manager menu.
