### ISSUE TITLE
[v1.22.7] crash when screencasting (Non-monotonic timestamps)

### ISSUE THREAD

**Issue by bastianilso** [pupil-labs/pupil#1826]
I am trying to screencast the sample scene from Unity, but it seems like the timestamps of eye1 and eye0 causes pupil capture to crash.
![image](https://user-images.githubusercontent.com/3967945/76614255-fb232f00-651f-11ea-9ab1-91e35a0fe357.png)

The crash happens when I activate the recording in pupil capture either manually or if i activate it remotely from unity. Previewing the unity screencast and eyes prior to recording works fine. 

Might be related to the fix in 2bd90070ab2054b62291cb5688d87cf1e66ef817 but given that this is with Pupil labs v1.22.7, i guess its a different issue somehow.

**Comment by papr** [comment]
@bastianilso Hi, thank you for reporting this issue. It looks like the [hmd-eyes time sync](https://github.com/pupil-labs/hmd-eyes/blob/master/docs/Developer.md#time-conversion) adjusted the "unity clock" by such a high amount that the `i`th timestamp was larger than the `i+1`th timestamp.

We are looking into options for handling this kind of edge case.

**Comment by papr** [comment]
@bastianilso After further looking into this issue, it looks like `TimeSync` has been triggered during the recording. Have you triggered it manually? Or was there a disconnect? Also, how much time passed between the connection event and the recording start?

**Comment by bastianilso** [comment]
@papr can't tell - I was just running the example called _ScreenCastDemoScene.unity_ from the _Hmd-Eyes.VR.v1.1.unitypackage_ in [hmd-eyes](https://github.com/pupil-labs/hmd-eyes/releases/tag/v1.1) and this was the result. Today I tried importing the _ScreenCast Camera.prefab_ into a new Unity scene and that worked fine. So I guess it is something in the _ScreenCastDemoScene.unity_ that is causing it.

**Comment by papr** [comment]
https://github.com/pupil-labs/pupil/pull/1829 will handle this issue gracefully and stop the recording. Please let us know if you are able to replicate the issue with the imported prefab.
