### ISSUE TITLE
Pupil Capture v0.5 for Windows

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#183]
Hi. Small Annotation.

I tested the installation on Windows 8.1.
Everything was working good, but i couldn't change the camera in the camera-settings.
So PupilCapture is using the wrong camera for eye-cam.

Best

**Comment by mkassner** [comment]
@MichaelBarz Do we have a capture device selector in the windows backend?

**Comment by MichaelBarz** [comment]
I'll have a look into that tomorrow. I'm not quite sure about that...

**Comment by MichaelBarz** [comment]
Thanks for reporting this issue @fneitzel. Since we concentrate on getting the platform independent pyuvc to run, we just provided a basic version of the windows only backend. Hopefully solving your issue goes together with introducing pyuvc for windows... ;) We'll keep you up-to-date.

**Comment by mkassner** [comment]
Here is another user that does not see his eye cam show up: (Microsoft HD-6000).
@MichaelBarz any progress on libUVC for windows?
