### ISSUE TITLE
ValueError: int is not allowed for map key when using msgpack 1.0.0

### ISSUE THREAD

**Issue by sven-mayer** [pupil-labs/pupil#1830]
**Bug:**
"ValueError: int is not allowed for map key" will be raised when using msgpack 1.0.0 and you want to load data recorded with two eye cameras.

**Explanation:**
This is to the fact that they changed their default setting for msgpack.unpackb see: https://github.com/msgpack/msgpack-python/issues/411 which they also discuss as major braking points in https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10

**Solution:** 
adding `strict_map_key=False` as argument whenever `msgpack.unpackb` or `msgpack.loads` is called

**Comment by papr** [comment]
Fixed in https://github.com/pupil-labs/pupil/pull/2068
