### ISSUE TITLE
Record menu has disappeared in Pupil Capture

### ISSUE THREAD

**Issue by ben24o** [pupil-labs/pupil#184]
Hi, after upgrading to the latest version in Linux everything seemed to be working fine. After a few hours the Record menu and "R" button have disappeared on the World window.

**Comment by ben24o** [comment]
solved the issue by removing all of the files in Pupil Capture Setting Folder

**Comment by mkassner** [comment]
This issue has been fixed with 9053f8e829f7b9e6abc611f9d5120d2e283035c7
