### ISSUE TITLE
Capture:  Allow the addition of an annotations without rendering to screen 

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1866]
The intention here is to facilitate writing out time-synchronized data programmatically from Unity. The issue is that large annotations including the positions, matrices, of several objects will tax the GPU and clutter the experimental screen.  This seems a nice alternative to writing out my own data in my own format from Unity, only to have to later deal with issues related to synchrony.

Please, correct me if I am making oversimplifying assumptions about synchrony.  I assume that every annotation would have an accompanying unity timestamp, and the conversion/synchronization with gaze data (and PLabs timestamps) would have to occur offline.

Or, perhaps PL team has already imagined a better path forward for the annotation of data captured in VR.

**Comment by papr** [comment]
@performlabrit My apologies for this very delayed response. Yes, using annotations is a good way to store custom data within a Pupil Core recording. Based on [our motivation for Pupil Core v2](https://github.com/pupil-labs/pupil/releases/v2.0), we will not change any features in the near future. Instead, I would recommend using [this custom plugin](https://gist.github.com/papr/7b940b2c02e05135f59d599a6a90c5f6) that does not log the incoming annotations.

**Comment by performlabrit** [comment]
Thanks very much, Pablo!  I'll be sure to have a look once I get 2.1 working on my machine.


----------------------

Gabriel J. Diaz, Ph.D.
Associate Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

Founder of PerForM Labs
Click for demos.<https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215<tel:(585)%20475-6215>
gabriel.diaz@rit.edu<mailto:gabriel.diaz@rit.edu>
________________________________
