### ISSUE TITLE
Pupil Player mjpeg recording not playing correctly.

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#187]
A bug in older versions of libav garbels some mjpeg recordings.

We use ppa versions of ffmpeg/opencv on linux and need to update the install instructions for this.

**Comment by mkassner** [comment]
The latest bundle release uses newer ffmpeg binaries and does not show this error.

**Comment by Sijben** [comment]
Issue continues when running from source even after following new installation instructions.

**Comment by mkassner** [comment]
Ok. Then OpenCV must still use the OS supplied libav version. Can you contact me so we can debug via video?

**Comment by mkassner** [comment]
One more way to solve this for you is to send me the videos and I ll transcode them so they work with your older version of libav. Future recordings you can record with `smaller file and more CPU` this will play regardless of libav version.

**Comment by Sijben** [comment]
Smaller file/more CPU versions do indeed work as intended. I'll get you a dropbox link with some old recordings tomorrow. Are .tar.gz files ok? 

Dropbox doesn't appear to be friendly towards one of the files (worldtimestamp, which is why it was missing last time I uploaded a recording).

**Comment by mkassner** [comment]
Hi,

yes, I just need the .mp4 file.

**Comment by mkassner** [comment]
I have updated the backend so with the right ffmpeg binaries this should work now.
