### ISSUE TITLE
Errors When opening Pupil Player and Pupil Capture from source

### ISSUE THREAD

**Issue by fiza09** [pupil-labs/pupil#1872]
**When running python main.py capture or run capture.bat, I get the following errors:**
```
>>>run_capture.bat
world - [INFO] numexpr.utils: NumExpr defaulting to 4 threads.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "D:\Sensory_Immersion\pupil\pupil_src\launchables\world.py", line 130, in world
    from uvc import get_time_monotonic
ImportError: DLL load failed: The specified module could not be found.

world - [INFO] launchables.world: Process shutting down.
```
**When trying to open player from source, I get the following errors:**
```
>>>run_player.bat
player - [INFO] numexpr.utils: NumExpr defaulting to 4 threads.
player - [ERROR] launchables.player: Process player_drop crashed with trace:
Traceback (most recent call last):
  File "D:\Sensory_Immersion\pupil\pupil_src\launchables\player.py", line 730, in player_drop
    from pupil_recording.update import update_recording
  File "D:\Sensory_Immersion\pupil\pupil_src\shared_modules\pupil_recording\update\__init__.py", line 15, in <module>
    from video_capture.file_backend import File_Source
  File "D:\Sensory_Immersion\pupil\pupil_src\shared_modules\video_capture\__init__.py", line 42, in <module>
    from .uvc_backend import UVC_Manager, UVC_Source
  File "D:\Sensory_Immersion\pupil\pupil_src\shared_modules\video_capture\uvc_backend.py", line 25, in <module>
    import uvc
ImportError: DLL load failed: The specified module could not be found.
```
**Note:*** I do have the uvc.dll in the exports folder. I also have microsoft C++ redistributable (64-bit version, 2015) downloaded. I installed and uninstalled this several times and it won't work. In this process, I ended up uninstalling the vs redistributables version 2010 and 2013 that were already on my pc. The error persists!

I created pupil labs in a sub-folder within a pycharm project so the other modules are in the venv folder. I have also already added this PATH to advanced systems in Windows.

**Comment by fiza09** [comment]
Update: I re-installed everything from scratch after deleting the old binaries and files. 

I am getting new errors this time around: 

```
(Sensory_Immersion) D:\Sensory_Immersion\pupil\pupil_src>python main.py capture
Error calling git: "Command '['git', 'describe', '--tags', '--long']' returned non-zero exit status 128."
 output: "b'fatal: No names found, cannot describe anything.\n'"
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    app_version = get_version()
  File "D:\Sensory_Immersion\pupil\pupil_src\shared_modules\version_utils.py", line 63, in get_version
    version = pupil_version()
  File "D:\Sensory_Immersion\pupil\pupil_src\shared_modules\version_utils.py", line 46, in pupil_version
    raise ValueError("Version Error")
ValueError: Version Error

(Sensory_Immersion) D:\Sensory_Immersion\pupil\pupil_src>run_player.bat

(Sensory_Immersion) D:\Sensory_Immersion\pupil\pupil_src>python main.py player
Error calling git: "Command '['git', 'describe', '--tags', '--long']' returned non-zero exit status 128."
 output: "b'fatal: No names found, cannot describe anything.\n'"
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    app_version = get_version()
  File "D:\Sensory_Immersion\pupil\pupil_src\shared_modules\version_utils.py", line 63, in get_version
    version = pupil_version()
  File "D:\Sensory_Immersion\pupil\pupil_src\shared_modules\version_utils.py", line 46, in pupil_version
    raise ValueError("Version Error")
ValueError: Version Error
```
How can I fix the error calling git? I did clone the git repository. I re-checked to confirm.

**Comment by pfaion** [comment]
Hi @fiza09 
can you try running `git fetch --all --tags` in the cloned repository and try again?

When running from source, Pupil does version checks based on the last git tag. If for some reason you cloned the repository without tags, this check will fail.

**Comment by pfaion** [comment]
Also, just to be sure, you are following the instructions from https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md for how to run from source, correct? :)

**Comment by fiza09** [comment]
I don't get any output out of that code. I did clone the repository and follow the instructions as is. What I did end up doing was changing the folder(s) structure afterwards to organize things differently.

**Comment by fiza09** [comment]
Update: okay, so I ended up fixing the github error but now I am now back to square one with my errors. Unfortunately, in trying to fix git and pycharm gui (and other applications that I broke when troubleshooting), I am now back to: 1) not being able to change python interpreter to 3.6.8 despite the project folder showing the my python.exe is indeed 3.6.8; and 2) I get errors with different modules.

**Comment by pfaion** [comment]
@fiza09 I am very sorry but I cannot follow you completely. Do you have to run Pupil from source for your use case? I highly recommend using the pre-built bundles otherwise, which require no special setup. Running from source is only required (and recommended) for people who want to actually modify Pupil source code, therefore we assume some level of familiarity with setting up a system like this. Note that you can even implement and load custom plugins when running Pupil from bundle!

Here are some further notes regarding your comments:

> What I did end up doing was changing the folder(s) structure afterwards to organize things differently.

Please be aware that any modifications that you make to the Pupil repository structure might end up  breaking the codebase.

> Unfortunately, in trying to fix git and pycharm gui (and other applications that I broke when troubleshooting) I am now back to:
> - Not being able to change python interpreter to 3.6.8 despite the project folder showing the my python.exe is indeed 3.6.8

Also be aware that I cannot know what changes you made to your git and Python setup. Your system might not be properly set up to continue from this point. If you have little experience with setting up a Python development environment on Windows (which can be tricky, I admit), I recommend reading up on this first and potentially resetting your system. Additionally, I cannot offer any support on PyCharm, since it's setup will most likely be different from the tools I'm using (Visual Studio Code as IDE).

> - I get errors with different modules, related to zmq_tools for both capture and player.

Please share the error messages, so I can take a look.

**Comment by fiza09** [comment]
@pfaion: I apologize for the confusion! I am learning to working in a virtual environment and using github so just some hurdles on the way.

> I had been using the pre-built wheels so not absolutely from scratch. It is easier for me understand how it works by working on it from the bottom-up. As of yet, I am not required to use pupil from source for my current project. But I am learning on-the-go and I am having fun doing this tbh (despite the frustration). I don't want to be limited by my lack of knowledge of how the program works during processing and analysis (in case I need to dig in further during  or future projects using pupil labs). I am also going to be running this from a terminal so I'd have to set up a proper environment anyway (which was the problem here).

> I am aware of it breaking codebase. I didn't change the structure within the primary cloned folder, but the format and location of the base folder after cloning to optimize space, which gave me errors for whatever reason. I found a mid-solution!

>**So I have successfully downloaded pupil from source. The app opens and the sample recording exports well.**

>^The problem was in anaconda3. _Last year's version is buggy on my end_. I downloaded the updated 2020 version. So this one is better able to identify and work with python 3.6.8 in a conda env on pycharm. _A higher version of python does not read the modules and will get you all sorts of import errors related to uvc (as the guide says)_.

> Warning Note for future users: uninstalling the 2013 visual redistributable will lead to errors in opening some applications (even if you have the newer 2015 version). For example, pycharm gui won't work (although it still will from command line).

**Comment by pfaion** [comment]
Ok, happy to hear that you managed to fix your problems! :)
