### ISSUE TITLE
pupil capture - GLFW Error on raspberry pi4 + official display

### ISSUE THREAD

**Issue by jjsapido** [pupil-labs/pupil#1880]
I tried configuring/compiling everything from scratches following windows tutorial in order to properly compile required libraries.
I currently can run `python3 main.py capture` from CLI with all dependencies met.
Unfortunately, I'm facing a `GLFW window failed to create`error.

No idea if this is a hardware limit, e.g., the raspberry official display has not enough resolution,  or there are problems related with current mesa driver, or... 
Any hint or help?

Error log
```
> python3 main.py capture --hide-ui

world - [INFO] numexpr.utils: NumExpr defaulting to 4 threads.
world - [INFO] launchables.world: Application Version: 1.23.10
world - [INFO] launchables.world: System Info: User: pi, Platform: Linux, Machine: raspberrypi, Release: 4.19.97-v7l+, Version: #1294 SMP Thu Jan 30 13:21:14 GMT 2020
world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/pi/pupil/pupil_src/launchables/world.py", line 459, in world
    main_window = glfw.glfwCreateWindow(width, height, "Pupil Capture - World")
  File "/home/pi/pupil/pupil_src/shared_modules/glfw.py", line 566, in glfwCreateWindow
    raise Exception(f"GLFW window failed to create:")
Exception: GLFW window failed to create:

world - [INFO] launchables.world: Process shutting down.
```

**Comment by pfaion** [comment]
Hi @jjsapido, which operating system are you using on the pi4?

This error might indicate that your graphics driver currently does not support OpenGL... I found [this post](https://www.raspberrypi.org/forums/viewtopic.php?t=222264) on how to enable GL support on a pi. Not sure if this will work out of the box, but please give it a try.

**Comment by jjsapido** [comment]
I'm on pi4 with the latest (February 2020) raspbian buster OS with mesa driver.
I read that post that mostly applies to rpi3 with fullKMS. The last thread's post is indeed for rpi4 and I tried implementing suggestion from that post. In particular I added
```
        glfw.glfwWindowHint(glfw.GLFW_CLIENT_API, glfw.GLFW_OPENGL_ES_API);
        glfw.glfwWindowHint(glfw.GLFW_CONTEXT_VERSION_MAJOR, 4);
        glfw.glfwWindowHint(glfw.GLFW_CONTEXT_VERSION_MINOR, 3);
        glfw.glfwWindowHint(glfw.GLFW_OPENGL_PROFILE, glfw.GLFW_OPENGL_CORE_PROFILE);
```
right after
```
        glfw.glfwInit()
```
in
` launchables/world.py`

not sure how to implement in python, nor if it really helps since I'm not sure pupil needs vertex shader, the remaining part 

```
Around line 51 replace the #version line (vertex shader) with the following line:

"#version 310 es\n"

Around line 63 replace the #version line (fragment shader) with the following 2 lines:

"#version 310 es\n"
"precision mediump float;\n"
```

I'm not so much into glfw tbh.

**Comment by pfaion** [comment]
@jjsapido oh, I did not mean to use any of the code from the post, but was rather referring just to [the first answer](https://www.raspberrypi.org/forums/viewtopic.php?p=1363227&sid=ee8187ff83bfce1aeb79dd4a0fe50384#p1363227):
> Yes, just turn it on by using ‘sudo raspi-config’. Select Advanced Options, GL Driver, Full KMS. Then reboot.

I did not realize that this might not be applicable to the rpi4?

Please note that Pupil is officially only supported for 64-bit versions of Ubuntu 16+. Unfortunately, since you are using a different OS, I cannot offer any support for this. If enabling GL Driver support does not solve the problem for you, you will have to investigate why the GLFW window creation fails on your side, maybe that helps you with finding the underlying issue. Probably a call to `glfwGetError()` after `glfwCreateWindow()` can give some insights, see [this](https://www.glfw.org/docs/3.3/intro_guide.html#error_handling) for reference.

**Comment by jjsapido** [comment]
Thanks for pointing me out... I am not that much aware about GLFW.
I will perform further tests on a NUC with ubuntu as soon as I get one. 

However, my idea was to build a simple(r) CLI approach for data acquisition and basic processing. Kind of similar to the phone app, with some plugin availability.
Basically providing some kind of configuration (e.g., text/file with a list of plugin enabled and/or cameras selection, etc..) and a simple way to check cam output to just confirm that the field of view is correct (e.g.,  image-based, jpeg-stream, video ...).
I know this would be a less configurable/manageable/friendly setup, but it would be way less limiting in terms of overall device requirements and GL compatibility, especially when you wanna just capture data and process afterward.
So I'm actually verifying if not-gui code can be un-wrapped out of the GLFW container and rewrapped into a CLI/simpler container, or flask/web container to provide a more general way to access it. 
Since it requires a big effort, do you have any hint about its overall feasibility, just to avoid wasting a lot of time to eventually discover that the result can not be achieved because of some obvious (?? :) ) reasons.
Thank you

**Comment by pfaion** [comment]
Hi @jjsapido 
there's no obvious reason for why this should not be possible.

Good news are that we are not using the GLFW event loop, but have our own event loop, which might make it a bit easier to decouple.

Bad news is obviously that a lot of the core codebase is still tightly coupled with GLFW and I assume it will require a lot (!) of effort to untangle this. For some parts of the codebase we have already tried to do this when refactoring in the past, but many many old parts are still working this way. We have repeatedly evaluated if we want to do this ourselves, but have decided it's currently not worth the effort.

Please also be aware that we cannot offer any support for custom modified versions of Pupil.

If you don't mind I'll close this issue for now.
Feel free to open new issues when you have more problems/questions.
