### ISSUE TITLE
WebUSB platform support?

### ISSUE THREAD

**Issue by gcatto** [pupil-labs/pupil#1883]
Does Pupil have WebUSB platform support? See https://wicg.github.io/webusb/#webusb-descriptors-and-requests

**Comment by pfaion** [comment]
We don't have any explicit support for this. Internally we use libusbk to communicate with the USB interface. I have no knowledge about WebUSB, if it needs explicit built-in support, then it probably won't work with Pupil. If it can communicate with libusbk somehow, it might work. Again, we have no experience with WebUSB here at Pupil Labs.

**Comment by gcatto** [comment]
@pfaion thank you for the prompt response! Learning about it myself, still finding my way a bit. Does Pupil have a (USB) vendor/manufacturer id? I haven't been able to find one thus far. Thank you!

**Comment by pfaion** [comment]
@gcatto We have this list of hardware IDs for the different cameras that we use on different headsets:
```python
[
    # VID, PID, CamName
    (0x05A3, 0x9230, "Pupil Cam1 ID0"),
    (0x05A3, 0x9231, "Pupil Cam1 ID1"),
    (0x05A3, 0x9232, "Pupil Cam1 ID2"),
    (0x046D, 0x0843, "Logitech Webcam C930e"),
    (0x17EF, 0x480F, "Lenovo Integrated Camera"),
    (0x0C45, 0x64AB, "Pupil Cam2 ID0"),
]
```
