### ISSUE TITLE
Saccades 

### ISSUE THREAD

**Issue by MLT-SEP** [pupil-labs/pupil#1884]
I would like to obtain or calculate saccades but I do not find the right way with my data.  
I do not have two same fixed points for all my participants. I just have one calibration point at the beginning and then a recording in ecological environment. 
I found script in code but I do not know how to use it and if it is what I need (/saccade_detector.py).

Is it possible to help me to find a solution ?

Thank you in advance,

**Comment by pfaion** [comment]
Hi @MLT-SEP 

Pupil currently does not offer any way of calculating saccades.

The script you found is a remnant of previous experiments and was never working, we just forgot to remove it.

We used to have an Eye-Movement detector in Pupil that also classified saccades, using the [NLSR-HMM](https://www.nature.com/articles/s41598-017-17983-x) algorithm. However, we realized that it performed too poorly to be of practical use in most cases and removed it again in version v1.17. If you want to give it a try you can checkout Pupil v1.16.

**Comment by MLT-SEP** [comment]
Hi pfaion,

Thank you very much for your complete answer.
