### ISSUE TITLE
Problem with Heat-maps across surface

### ISSUE THREAD

**Issue by Robin2202** [pupil-labs/pupil#1898]
Hello, I don't know why, but the fonctionnality "heats maps across surfaces" seem to not work for me (you could see the screenshot attached to this message). Have I made something wrong ? Or this fonctionnality has a problem ?

Than you, 

Hope to read you
![Capture d’écran (255)_LI](https://user-images.githubusercontent.com/66313729/83522498-09f6fd80-a4e1-11ea-8dae-ee84f1909633.jpg)

**Comment by romanroibu** [comment]
Hi @Robin2202,

The heatmaps for gaze across different surfaces is currently not working in Pupil Capture. I will update this issue once we have a release where this is fixed.

In the meantime, you can use this feature in Pupil Player.

**Comment by Robin2202** [comment]
Hello, thank you for your quick answer !

**Comment by papr** [comment]
Hi @Robin2202 

Apologies for the delayed response.

Given [our roadmap/motivation for v2.0](https://github.com/pupil-labs/pupil/releases/v2.0), we will not be adding new features to Pupil Core in the near future. Given the limited use case of real-time across-surface heatmaps, we have decided to disable the selector for the heatmap mode in Pupil Capture in our upcoming v2.1 release to clarify that this feature is not available. The per-surface heatmap mode continues to be available in Pupil Capture. Also, you can continue using both modes in Pupil Player. Thank you for your understanding.
