### ISSUE TITLE
Screen marker calibration circles not appearing correctly on large monitor

### ISSUE THREAD

**Issue by elmorg** [pupil-labs/pupil#190]
I'm trying to run the screen marker calibration on a large Mac monitor (2560 x 1440) and the circular markers are only appearing with a single ring, rather than the usual two. It's working fine on my Macbook retina display.

**Comment by mkassner** [comment]
Interesting, can you post a picture? Also, there is a slider in the advance
settings to scale up the marker. Did you try that?

**Comment by elmorg** [comment]
![screen shot 2015-08-30 at 22 31 57](https://cloud.githubusercontent.com/assets/1218452/9569558/fa138c00-4f66-11e5-96b6-0192572e8f7a.png)

Thanks for the quick response. I used the slider to scale the marker down so that it has 2 rings, but the overall diameter is still the same. If I scale up then it just starts to make the single ring smaller. It's like there's a fixed circular window size for the marker to occupy, so the size of that window doesn't change when I scale.

**Comment by elmorg** [comment]
scaled to 1.3 - 
![screen shot 2015-08-30 at 22 34 40](https://cloud.githubusercontent.com/assets/1218452/9569592/b3717496-4f67-11e5-92b7-2aa09f642776.png)

scaled to 0.5 - 
![screen shot 2015-08-30 at 22 38 13](https://cloud.githubusercontent.com/assets/1218452/9569603/cae245e2-4f67-11e5-95fa-553025f2a116.png)

**Comment by mkassner** [comment]
Could you let us know what OS and hardware you are using?

**Comment by mkassner** [comment]
I tried to replicate this but without pointer to OS and hardware its hard to know where to look.

**Comment by elmorg** [comment]
I can't tell you exactly at the moment, as I'm not able to access the computer I was using. However I know that it is an iMac 27-inch running Mavericks. I'm using a pupil headset with high-res world camera and 30Hz eye camera.

**Comment by mkassner** [comment]
Alright, I ll have a look and report back.

**Comment by mkassner** [comment]
I m pretty sure this is a gl driver limitation. We are using gl points to draw the marker and the point size seems to be capped on your machine. I'll implement a version using a texture.

**Comment by mkassner** [comment]
we are solving this with a new shader. Expect a fix today/tomorrow.

**Comment by mkassner** [comment]
Fixed with 574592b2754107fe75bfdfb47bc354c5fdf9851a . Please don't forget to update pyuvc and pyglui (including submodules).
