### ISSUE TITLE
Error about  run main.py directly from my IDE 

### ISSUE THREAD

**Issue by hz-pupil** [pupil-labs/pupil#1909]
when I run main.py directly from my IDE,  there are these errors:
-------------------------------------------------------------------------------
main.py: error: the following arguments are required: <app>
usage: main.py [-h] <app> ...

positional arguments:
  <app>       which application to start
    capture   real-time processing and recording
    player    process, visualize, and export recordings
    service   low latency real-time processing with constrained feature set

optional arguments:
  -h, --help  show this help message and exit
-----------------------------------------------------------------------------------------
How do I do next?
I am a fresher of python.

**Comment by romanroibu** [comment]
Hi @hz-pupil, you need to configure your IDE to pass the name of the application you want to run (`capture`, `player` or `service`) as an argument to `main.py`.

**Comment by pfaion** [comment]
Hi @hz-pupil,

you cannot run main.py without specifying the app to start as a command-line argument.

E.g. for starting Pupil Capture, you have to run
```
python main.py capture
```

Specifying startup options works differently in every IDE.
Maybe I can help you when you tell me which IDE you are using.

May I also ask why you intend to run Pupil from source?
This will only be necessary if you need to modify Pupil's source code or develop custom plugins.
Otherwise I'd recommend you download one of our pre-built bundles for your operating system.

**Comment by hz-pupil** [comment]
@pfaion Thank you for your reply. I can use the cmd to run "python main.py capture". And It runs OK. My IDE is the IDLE 3.6 of python 3.6 64 bit.
I want to modify Pupil's source code to change the color of the PC screen and to add some pictures showing at the PC screen while testing.  And I am studying the python now. Can you tell me what kind of information to study? Is there some web site I can get the relevant information? And which part source code to modify?

**Comment by hz-pupil** [comment]
@romanroibu Thank you for your reply.  How do I configure my IDE to pass the name of the application I want to run (capture, player or service) as an argument to main.py.

**Comment by pfaion** [comment]
@hz-pupil Do I understand correctly that you want to create an experiment on the screen? Pupil does not offer any capability of doing this, normally you would use other software to run your experiments and use Pupil's network API to synchronize your experiment with Pupil Capture while recording.

Can you elaborate on your specific use case / idea / experiment? Maybe then I can give you tips on how to set things up.

I would also recommend you familiarize yourself a bit with our documentation on https://docs.pupil-labs.com/

**Comment by papr** [comment]
I think the relevant question has been answered here: https://github.com/pupil-labs/pupil/issues/1909#issuecomment-642462830

**Comment by lubai1013** [comment]
Help: what should I do if I want to add a new function button in the main operation interface
