### ISSUE TITLE
Missing world camera feed

### ISSUE THREAD

**Issue by Sijben** [pupil-labs/pupil#191]
I'm attempting to use the Pupil Pro (Eye + World camera) with the Pupil windows app (either 64 or 32 bit). While both cameras work (verified using Debut Video Capture Software), opening pupil will only display the Eye-camera feed while the World screen shows the standard static cubes. I've read multiple posts mentioning extra USB module cards however the Pupil Pro system uses a single USB connection for 2 cameras.

What would be the optimal solutions here (beside running the Linux source version)?

**Comment by billycysung** [comment]
I confirm this issue, I ordered the new hardware and tried it tonight on both my PC (Window 7) and Mac (OS Yosemite). I can get the eye camera working but cannot get the world camera working (it displays colour boxes). Upon investigation, Window cannot recognise one of the hardware (presumably, the world camera). I tried to use different version of capture but had no luck.

**Comment by mkassner** [comment]
I m pretty sure this is a software issue. Pupil Capture detects and assigns cameras based on their names. With any recent headset we use a new world camera and its name is not yet registered in that release version. We will release a new version asap.

**Comment by billycysung** [comment]
Thanks mkassner! Sorry, I have no background in programming. I would appreciate it if you can release the patch asap as I am hoping to use the equipment next week. Thank you very much!

**Comment by MichaelBarz** [comment]
Hi @billycysung, I'm working on that right now. If everything works as intended there will be a new bundle with the new camera list and some new features today.

**Comment by mkassner** [comment]
@MichaelBarz has published a new release: https://github.com/pupil-labs/pupil/releases/tag/v0.5.7.45

Please check it out and reopen if the issue persists.

**Comment by billycysung** [comment]
Hi Michael,


Appreciate the quick response for this and the patch. However, the new version of Capture crashes in Window. When I turn Capture on, eye camera display works fine, but world camera display shows "not responding". Can you please look into this?


Cheers,

Billy


________________________________

**Comment by adlinfakhriana** [comment]
i'm having almost the same problem. i'm a student n totally new to this thing. the world window does not show real-time video feed. it shows boxes of colors. what should i do..? any help would be very nice of you :')

**Comment by billycysung** [comment]
Try deleting the pupil camera folder and the recording folder that are generated once you launch the software. This should resolve the problem (just need to do this every time you boot up the software).




On 3 Jan 2017, at 4:24 PM, adlinfakhriana <notifications@github.com<mailto:notifications@github.com>> wrote:


i'm having almost the same problem. i'm a student n totally new to this thing. the world window does not show real-time video feed. it shows boxes of colors. what should i do..? any help would be very nice of you :')

**Comment by adlinfakhriana** [comment]
sorry for bothering, but where do i find the pupil camera folder n recording folder..? anywy thnks for the help :)))))

**Comment by billycysung** [comment]
It is normally under your “My Document” or your root drive. When you load up the software, on the left, you will find an option to choose where you save your recording - that is the location of the two folders. Hope this helps!



On 3 Jan 2017, at 4:42 PM, adlinfakhriana <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry for bothering, but where do i find the pupil camera folder n recording folder..? anywy thnks for the help :)))))

**Comment by willpatera** [comment]
@adlinfakhriana - here is a bit more feedback

## Test pattern
If you see the test pattern (multicolor pattern) on startup of Pupil Capture then:

1. You need to select the cameras as the capture source **or**
2. You do not have cameras connected or Pupil software does not recognize the cameras used

## Capture Selection
Select your camera from the `Capture Selection` menu.
![pupil_capture_selection](https://cloud.githubusercontent.com/assets/1407224/21602988/44ee6536-d1cc-11e6-8761-2b2bc2fabaf5.gif)

## Resetting pupil_capture_settings
You can, as @billycysung notes, delete the pupil_capture_settings folder. This folder will be re created when Pupil Capture starts. It is located in your home directory on macOS this is `Users/YOURUSERNAME/pupil_capture_settings`. However, it is advisable to select the cameras via the GUI in Capture Selection.

**Comment by adlinfakhriana** [comment]
![15894713_1272056326192236_899563756393118864_n](https://cloud.githubusercontent.com/assets/24889527/21634473/7d55eb4e-d292-11e6-95ad-8d4b9f5824e9.jpg)

we keep on getting this. we used windows 10, after installing driver and still didnt manage to. :(

**Comment by willpatera** [comment]
@adlinfakhriana - a few questions:

1. Can you confirm that you have installed drivers correctly according to the [wiki page](https://github.com/pupil-labs/pupil/wiki/Windows-Driver-Setup) - **Note** that when windows does a system update you will have to re-install drivers following the instructions on the wiki page.
1. Can you share specs of your machine/hardware?

**Comment by adlinfakhriana** [comment]
yes we have followed those required steps. we did the same thing to another laptop (mac) and it could run properly. 
this is the laptop spec which used windows 10.
thanks in advance ! :))
![asus spec](https://cloud.githubusercontent.com/assets/24889527/21636157/83492e76-d29c-11e6-9edb-8c910c8e9f59.PNG)

**Comment by adlinfakhriana** [comment]
this is the result we got using mac

![whatsapp image 2017-01-04 at 3 44 27 pm](https://cloud.githubusercontent.com/assets/24889527/21636291/072ba5b6-d29d-11e6-86e5-00105b6de322.jpeg)

**Comment by willpatera** [comment]
Hi @adlinfakhriana - According to your specs you are using Windows 8. The bundle is only supported on Windows 10.

**Comment by mkassner** [comment]
@adlinfakhriana  thats not a mac. What OS are you running here?

**Comment by willpatera** [comment]
@adlinfakhriana - your Acer machine also appears to be running Ubuntu not macOS.

**Comment by adlinfakhriana** [comment]
yep but the laptop has been updated to windows 10. 
does tht mean i need to install ubuntu too..? or the updated laptop should be fine..?

sorry im not a tech savvy at all >,<

**Comment by willpatera** [comment]
@adlinfakhriana - If you are running Windows 10 with an Intel `i` series CPU then Pupil Capture should be working.  

The information you have posted in this issue somewhat confusing for me as a reader. Some follow-up points:
 
- You state in [this response](https://github.com/pupil-labs/pupil/issues/191#issuecomment-270320704) that you are using Windows 10, but the system information shows that your `Asus VivoBook S200E` is actually running `Windows 8`. Additionally your system information shows a confusing mix of processors... Is this a screenshot from your system? If you just updated to Windows 10 please try Pupil Capture again. 
- You state in [this response](https://github.com/pupil-labs/pupil/issues/191#issuecomment-270321213) that you are using `macOS` but the image clearly shows non macOS hardware `asus` laptop that (from what I can see in the screenshot) is running Linux (possibly Ubuntu).

**Comment by adlinfakhriana** [comment]
we did this on my friend's laptop, and the acer red is from our doctor's friend. my bad, he stated tht it was linux im sorry ^^ 

this morning i tried installing pupil labs in my laptop, which has been upgraded to windows 10. it could run well but may i know, what should i do if the sidebar for eye window cannot be expanded after it was collapsed? it got stucked and eventually the world window turned to be not responding. 

thank you for your helps :D 
![whatsapp image 2017-01-05 at 4 16 27 pm](https://cloud.githubusercontent.com/assets/24889527/21673192/7d61bbce-d362-11e6-9407-703ebaae6dd2.jpeg)

**Comment by willpatera** [comment]
Hi @adlinfakhriana - thanks for the update. 

There is no need to use the ROI mode. The ROI mode is a known issue https://github.com/pupil-labs/pupil/issues/563 and will be fixed in a future release.

**Comment by adlinfakhriana** [comment]
thank you too ^^
