### ISSUE TITLE
Pupil Core 2.0.161 - Windows 10 - Pyav out-of-date error

### ISSUE THREAD

**Issue by VisionResearchBlog** [pupil-labs/pupil#1910]
Just installed the Core 2.0 release on Windows 10 pc. Both capture and player generate the following error in screenshot  when I try to run them and then exit mentioning  pyav being out-of-date. The paths also reference c:\python36 but I do not have python installed there.

![Capture](https://user-images.githubusercontent.com/17455592/84371567-61742800-abc9-11ea-8423-ad4d96e97a1d.JPG)

**Comment by VisionResearchBlog** [comment]
I see in the developer notes this message about updating a Pyav wheel (not sure what this is) but I installed from the .msi binary - so I assume this would only apply if I were trying to compile on my own.

![Annotation 2020-06-11 105749](https://user-images.githubusercontent.com/17455592/84372114-2d4d3700-abca-11ea-814a-32749b2a0d1a.jpg)

**Comment by papr** [comment]
Thank you for letting us know. I am making a new bundle right now.

**Comment by papr** [comment]
The Windows has been updated to include the correct version of PyAV. Sorry for the inconvenience. Please re-download the Windows bundle from the [release page](https://github.com/pupil-labs/pupil/releases/latest#user-content-downloads).
