### ISSUE TITLE
Automatic Bundle Update

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#192]
Due to recent changes in hardware design some errors occurred concerning the predefined camera IDs and names. An update function to automatically load the newest camera list as well as similar other configuration files would be a nice feature to prevent such issues in future.
Of course, this feature should not require a connection to the internet in case there is none.

A solution based on HTTP to request a JSON or XML formatted configuration file should be suitable.

**Comment by mkassner** [comment]
What about a auto updater for the whole software package instead?

**Comment by MichaelBarz** [comment]
Ok, renamed the issue to "Automatic Bundle Update". The question is, if this works with the bundles as we have them now. One idea would be to use `git` with special tags for update versions. The updater could easily merge the local version with updated remote scripts and thereby reduce network traffic. A list of update tags could be provided as mentioned in my first post via HTTP and JSON or XML or plain text list.

Another option would be to download a whole new release and to provide an update script. This script should be capable of performing additional actions, if, for example, the settings folder has to be upgraded to a new structure. This seems to happen regularly as well...

**Comment by mkassner** [comment]
I know that for ubuntu we'll just make a ppa and all it taken care of.

For Mac and Windows a small script that downloads&replaces the whole pupil-dir would be best.

**Comment by willpatera** [comment]
overlaps with: #342
