### ISSUE TITLE
Duration information in info.json file

### ISSUE THREAD

**Issue by toruhitomi** [pupil-labs/pupil#1920]
Hi, 

Hi, I have a recording of about **8-min long**. Output files all look good. Loading the files to Player was successful and additional files (e.g., info.player.json, world.mp4) are all properly made. But subsequent "info.player.json" file says the duration of the recording is only "0.411" seconds. I wonder why, and checked the "info.invisible.json" file, in which the duration of the recording is "411000000".

**Comment by papr** [comment]
Hi @toruhitomi 
The duration in `info.invisible.json` uses nanoseconds as unit. Pupil Player uses seconds. 411000000 nanoseconds correspond to 0.411 seconds. These values are therefore consistent. 

Does this answer your question or is there something else that caught your attention, e.g. is the recording longer than 0.4 seconds?

**Comment by toruhitomi** [comment]
Hi @papr 
Thanks. Yes, even though the recording is 8.35 min long, the json file indicates a duration far from the mp4 file length, which is what I meant. As a follow-up, for the other files, the duration was correctly recognized and I found no big discrepancies between json duration and mp4 durations. Let me know if you have a look at actual files. I'll share them upon request. Cheers

**Comment by papr** [comment]
Closing as this is not Pupil Core issue. Please contact info@pupil-labs.com should this issue to continue to appear for new recordings.
