### ISSUE TITLE
Waves of bad detection indice, high ratio of invalid data, and a possible visibility of annotations ?

### ISSUE THREAD

**Issue by Robin2202** [pupil-labs/pupil#1929]
Hello, I am currently working with the pupil core to monitor gaze position in an airplane cockpit. 

I have two questions to which I have not found an answer : 
- After adjusting the eye cameras, even if the pupil detection confidence indices are good, it often happens that "waves" of detection scores ~ 0 arrive (excluding blinking). Do you know what it could be due to?
Also, and probably due to what I just mentioned, we regularly have ~ 30% of invalid data during the calibration (but the value of the accuracy is good (<2.5 °)). Is there a minimum percentage of valid data that we need to obtain during calibration?

- Is there a way to visualize the time position of the tags in the graphs at the bottom of the window?

Thank you

**Comment by papr** [comment]
Hi,

Would you mind sharing an example of these "waves" with `data@pupil-labs.com`. Ideally, you specify the time range of such a wave.

Could you please elaborate on what you mean by
> visualize the time position of the tags in the graphs at the bottom of the window

? Which tags and which window are you referring to?

**Comment by Robin2202** [comment]
Hello, thank you for your really quick answer

About the "waves", I don't have the data now, I will put the video when I will have it

About the annotation : Yes, it is exactly this : annotations by tags on the timelines in the pupil player window

What do you think about the maximum invalid data we could have fo an OK calibration ? (30 % could be ok ?)

Thank you

**Comment by papr** [comment]
Hey, apologies for the delayed response.
- annotation timeline - We will not be adding new features to Pupil Core in the near future as we are concentrating on stabilizing the product. You can simply create a custom user plugin that subclasses the annotation plugin and draws annotations similar to [the reference locations](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/gaze_producer/ui/reference_location_timeline.py).
- low confidence pupil data - There is some expected amount of low confidence pupil data during calibration, especially if you are calibrating a large calibration area, i.e. the eyes turn a lot to the left/right. Generally, 30% looks like a good threshold. A definitive number cannot be given as it depends on how much extreme-angled data is collected.

**Comment by Robin2202** [comment]
Hello, thank you very much for your answer !

**Comment by papr** [comment]
I will close the issue until we have the data regarding the "waves of bad detection". Please reference this issue when sending the data and we will reopen it.
