### ISSUE TITLE
Norm_pos and camera in gaze_positions

### ISSUE THREAD

**Issue by MLT-SEP** [pupil-labs/pupil#1950]
Good afternoon,

I wanted to use norm_pos x and y in my file gaze_positions.csv. However I am not sure about measure. 
Does 0 correspond for x to the left of the camera (and 1 the right) or is it another connection ? 
I have the same question about y (0 =lower part of the camera and 1 = upper part of the camera)

Moreover, I wanted to know the angle of recording of the world camera and I do not find it in docs-pupil-labs.

Thank you in advance for your answer,

**Comment by papr** [comment]
Hi @MLT-SEP, you can read more about [coordinate systems in general here](https://docs.pupil-labs.com/core/terminology/#coordinate-system). Could you please specify what you mean by "angle of recording of the world camera"?

**Comment by MLT-SEP** [comment]
Thank you very much, I did not find it before, sorry for the question. 

Yes of course, I wanted to know the viewing angle of the world camera, i.e.: degrees of the picture angle. Does it make sense ?

**Comment by papr** [comment]
Sorry, I am not sure if I can follow. Do you refer to the gaze location within the scene image in terms of degrees to the image center? You can calculate these based on the `gaze_point_3d` and the `(0, 0, 1)` (orthogonal vector to camera image plane).

**Comment by pfaion** [comment]
@MLT-SEP an angle always exists between two directions. What are the directions you are referring to? One seems to be the viewing direction of the world camera? What is the other direction?

**Comment by MLT-SEP** [comment]
Yes I understand. I will try to explain. I refer myself to the world camera. The directions are the maximum on the left and the maximum on the right (side to side). I would like to know the angle created by these two directions, i.e.: the horizontal viewing angle. Is it clear or must I found another explanation ? 
Sorry for the disturbance, and thank you for your help,

**Comment by pfaion** [comment]
@MLT-SEP I assume you are referring to the [field of view (FOV)](https://en.wikipedia.org/wiki/Field_of_view) of the camera?

As you can find in our [tech specs](https://pupil-labs.com/products/core/tech-specs/), our world camera has a 100° _diagonal_ FOV in its highest resolution and also ships with an additional 60° lens. Please note that cropping to a lower resolution will also reduce the FOV.

**Comment by MLT-SEP** [comment]
Thank you so much !

Sorry for the wrong word. It is field of view ! Thank you for your advice about FOV !
