### ISSUE TITLE
hi, how about normal camera in the car and real-time problem?

### ISSUE THREAD

**Issue by l35633** [pupil-labs/pupil#1969]
So great to know this code. Now I have two questions.
1. Does this soure code can use to normal camera, not head device or in-glass? for example, monitor in the car?
2.how about the real-time performance, for 800*600 resolution, can it be 25 frame/s to eye track?
Thank you very much!

**Comment by papr** [comment]
@l35633 Hi! Pupil is only usable with head-mounted eye-tracking devices. It seems to me that you are looking for remote eye-tracking software. This functionality is not available in Pupil. For an eye camera resolution of 192x192, Pupil Capture can run the pupil detection at more than 200Hz given sufficient CPU resources. I hope this has answered your question to your satisfaction.
