### ISSUE TITLE
Pupil Capture 0.5.4-1 crashes at start-up on Ubuntu 14.04 64-bit

### ISSUE THREAD

**Issue by Sijben** [pupil-labs/pupil#197]
Terminal error message:
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast 

A quick google of the issue results in lot of questions and solutions posted by Steam users (who apparantly have a similar issue).

**Comment by mkassner** [comment]
This simply means that no opengl driver is installed. Please check what graphics card you have and install the binary drivers. Have a look at Software & Updates -> ‘Additional Drivers’ : http://askubuntu.com/questions/47506/how-do-i-install-additional-drivers

I will close this as it is a commend error related to Ubuntu setups. Please reopen if you should no be able to resolve it. I'll gladly assist.
