### ISSUE TITLE
Load existing viedeos in PupilCapture

### ISSUE THREAD

**Issue by artpetro** [pupil-labs/pupil#1982]
Hi, pupil labs team,

I'm a PhD student at the University Osnabrueck. I'm currently working on an algorithm that will be used to optimize pupil-detectors parameters.
To test the algorithm, I created videos with ground truth positions of pupils. There is one .mp4 file per eye and one file with the ground truth data for the pupil, for example the ellipse.

My goal is to detect the pupil of these videos with optimized parameters using PupilCapture. The result should be compared with the ground truth data to evaluate the algorithm.
Unfortunately I have not found a way to use existing videos as a source in PupilCapture. One possibility would be to simulate a UVC camera. However, this involves considerable effort.

Is it possible to use the existing videos as an input source? Is there a plugin for this? What needs to be adjusted in the PupilCapture code?

Best regards
Artem Petrov

**Comment by papr** [comment]
Hi @artpetro 
This is Pablo from the software development team at Pupil Labs.

I suggest using our `pupil-detectors` Python module in this case: https://github.com/pupil-labs/pupil-detectors/

This way you can control and use the detectors without Pupil Capture.

Best,
Pablo
