### ISSUE TITLE
issue in converting timestamps to wall clock time

### ISSUE THREAD

**Issue by gaiaspicciarelli** [pupil-labs/pupil#1985]
Hi all, 

I write here because I'm having issues trying converting timestamps to wall clock time. 
I already followed your past instructions (that I copy down here) but I'm still having troubles. 
My question is: is this script valid if I want to use Matlab instead of Python in order to covert timestamps into wall clock time?
If not, can you help me in writing another script that can be used for Matlab?
I'm not a programmer so it is very difficult for me to understand Python. I already tried this script with Matlab and gave me errors, and I really need to convert timestamps into wall clock time. 

Thanks a lot in advance!!

> You can convert timestamps to wall time with some quick conversions. Here is an example on how to do this with Python using the start times in the info.csv file and an example first timestamp in the exported gaze_positions file:
> 
> import datetime
> start_time_system = 1533197768.2805 # unix epoch timestamp
> start_time_synced = 674439.5502 # pupil epoch timestamp
> offset = start_time_system - start_time_synced
> example_timestamp = 674439.4695
> wall_time = datetime.datetime.fromtimestamp(example_timestamp + offset).strftime("%Y-%m-%d %H:%M:%S.%f")
> print(wall_time)
> # example output: '2018-08-02 15:16:08.199800' 
>

**Comment by papr** [comment]
Hi @gaiaspicciarelli 
Apologies for the delayed response. Unfortunately, we are not able to help you writing custom MATLAB scripts. The general logic of calculating the offset between Pupil and Unix time is valid in any language. The code above is specific to Python in regards to datetime formatting. Matlab has its own datetime formatting functions. A quick search yielded [this solution](https://stackoverflow.com/a/31837813/5859392).
