### ISSUE TITLE
Wrong layout of calibration "C" and record "R" buttons

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#199]
The "C" and "R" button are shifted to the top and even disappear when decreasing the window size. The wrong layout persists when restarting Pupil Capture.
The shift appeares after minimizing the window and recovering it again. Maybe this is related to #139 then, but I'm not quite sure.
Anyhow, deleting the settings folder solves this issue...
![error](https://cloud.githubusercontent.com/assets/6330614/9759125/33565caa-56eb-11e5-9c63-607bec6899e4.png)

**Comment by mkassner** [comment]
I have seen this before and it was related to window_resize callbacks not working as expected on Linux.

Could you put a print in window_resize in world.py?

**Comment by mkassner** [comment]
Ok I made a fix for this as discussed. @MichaelBarz can you test again and close?

**Comment by MichaelBarz** [comment]
solved ;)
