### ISSUE TITLE
Question about the Pupil 1.0 Release: Binocular_Gaze_Mapper_Base

### ISSUE THREAD

**Issue by 962557346** [pupil-labs/pupil#1991]
Hello,
I feel confused about the `on_pupil_datum` function in the `Binocular_Gaze_Mapper_Base` of the Pupil 1.0 Release. I don't know why we choose the `self.caches[0]` instead of `self.caches[1]` to compute the gaze when the ` self._caches[0][0]['confidence'] < self.min_pupil_confidence`. Because I think the higher confidence may be more reliable. The lower confidence such as `self.caches[0]` is untrustworthy. Looking forward to your reply.

The function codes are as follows:
```python
def on_pupil_datum(self, p):
        self._caches[p['id']].append(p)

        # map low confidence pupil data monocularly 
        if self._caches[0] and self._caches[0][0]['confidence'] < self.min_pupil_confidence:
            p = self._caches[0].popleft()
            gaze_datum = self._map_monocular(p) 
        elif self._caches[1] and self._caches[1][0]['confidence'] < self.min_pupil_confidence:
            p = self._caches[1].popleft()
            gaze_datum = self._map_monocular(p)
        # map high confidence data binocularly if available
        elif self._caches[0] and self._caches[1]:
            # we have binocular data
            if self._caches[0][0]['timestamp'] < self._caches[1][0]['timestamp']:
                p0 = self._caches[0].popleft()
                p1 = self._caches[1][0]
                older_pt = p0
            else:
                p0 = self._caches[0][0]
                p1 = self._caches[1].popleft()
                older_pt = p1

            if abs(p0['timestamp'] - p1['timestamp']) < self.temportal_cutoff:
                gaze_datum = self._map_binocular(p0, p1)
            else:
                gaze_datum = self._map_monocular(older_pt)

        elif len(self._caches[0]) > self.sample_cutoff:
            p = self._caches[0].popleft()
            gaze_datum = self._map_monocular(p)
        elif len(self._caches[1]) > self.sample_cutoff:
            p = self._caches[1].popleft()
            gaze_datum = self._map_monocular(p)
        else:
            gaze_datum = None

        if gaze_datum:
            return [gaze_datum]
        else:
            return []
```

**Comment by papr** [comment]
Hi,
> The lower confidence such as self.caches[0] is untrustworthy.

This is 100% correct and the reason why we map these data points monocularly and not binocularly. We map the datum nonetheless because we do not want to drop it. This way the data is accessible after-the-effect.

The matching algorithm has evolved slightly since 1.0. Here you can find the v2.2 version:
https://github.com/pupil-labs/pupil/blob/aec6a18f5fd4caf83948ce8f27f002c3adae53bf/pupil_src/shared_modules/gaze_mapping/matching.py#L58-L102

**Comment by 962557346** [comment]
@papr Thank you for your reply. But I still feel confused about it. Should we put the `self._caches[1][0]` into the `_map_monocular` function, if the `self._caches[0][0]['confidence'] < self.min_pupil_confidence` but `self._caches[1][0]['confidence'] > self.min_pupil_confidence`? In this section, The `self._caches[1][0]` isn't considerd whether it is bigger than `self.min_pupil_confidence`.
```python
if self._caches[0] and self._caches[0][0]['confidence'] < self.min_pupil_confidence:
            p = self._caches[0].popleft()
            gaze_datum = self._map_monocular(p) 
```
And the `popleft()` operation also seems to drop the `self._caches[0][0]` when the `self._caches[0][0]['confidence'] < self.min_pupil_confidence`. So the data is not accessible after-the-effect.

**Comment by papr** [comment]
Correct, `popleft` returns and drops the first element from the corresponding list/cache. This is on purpose, as the returned datum is mapped monocularly afterward and should not be considered for further mapping anymore. Please be aware that the caches contain the pupil data only temporarily until it is either mapped monocularly (low confidence or large temporal difference) or binocularly (both pupil datums are of high confidence and are close in time).

Only pupil data that is deleted before being passed to `_map_monocular` or `_map_binocular` is considered dropped/lost. The algorithm is designed such that it maps all data either monocularly or binocularly. At no point, it drops or looses data. During a recording, pupil data is stored to disk independently of result of this matching algorithm.

You can find an evaluation of the matching algorithm [here](https://nbviewer.jupyter.org/github/pupil-labs/pupil-matching-evaluation/blob/master/gaze_mapper_evaluation.ipynb).

**Comment by 962557346** [comment]
@papr Thank you for your detailed explanation. I understand. The algorithm maps all data regardless of its confidence. It is a great idea. 
But I have another question. Why the `p` may recv more than one pupil data once? Is it because of possible blocking? In my opinion, the `p` should recv only one pupil data in the 1/30 s when the fps is 30Hz.
Thank you for your help.
