### ISSUE TITLE
ImportError: cannot import name Named_Texture

### ISSUE THREAD

**Issue by Sijben** [pupil-labs/pupil#200]
Hello,

We're trying to run pupil from source (Ubuntu) and face a problem at the end. We used the install dependencies guide and then we finished the process with the other guide.
When we re trying to run the capture or even the player from the terminal we re facing this issue:

  File "'main.py", line 82, in <module>
    from eye import eye
  File "/home/eyetracker/PUPILINSTALL/pupil/pupil_src/capture/eye.py'', line 24, in <module> 
    from pyglui.cygl.utils import Named_Texture
ImportError: cannot import name Named_Texture

We blamed it on some kind of issues with the pyglui library. So we did reinstall it. While installing it begins with

  missing cimport in module 'pyglui.cygl':pyglui/ui.pyx
  missing cimport in module 'pyglui.cyg': pyglui/graph.pyx

But it does continue installing. Maybe this is the source of the problem, or is it normal?

Thanks for any help!

**Comment by mkassner** [comment]
Hi,

please make sure to git pull pyglui's sub repositories cygl and pyfontstash. 

```shell
cd pyglui
git pull --recurse-submodules
git submodule update --recursive
python setup.py install
```

then it should work. We have been adding some new gl fn in cygl recently.

**Comment by jadsk** [comment]
The git pull does not work. What exactly are we to replace?

**Comment by mkassner** [comment]
If this does not work simply remove the pyglui directory and then re-clone it with:

```
cd ~/
git clone http://github.com/pupil-labs/pyglui --recursive
cd pyglui
sudo python setup.py install
```

**Comment by jadsk** [comment]
Hi,
I tried what you said and it says
Error: unable to find vcvarsall.bat

Help?

**Comment by mkassner** [comment]
Ah ok, on windows its all very different. @MichaelBarz, can you update the pyglui wheel? 

Once we have this updated. You should be able to install it as shown in the windows install instructions.

**Comment by MichaelBarz** [comment]
Hi, yes of course. I need the master branch to be merged into the win_wheel branch for that. Maybe we should concern to merge win_wheel into master for better maintenance.

**Comment by mkassner** [comment]
I have just merged win_wheel to master. Could you give it a try @MichaelBarz ?

**Comment by MichaelBarz** [comment]
Ok, thanks! I just uploaded a new wheel for version 0.6 of pyglui. For me installing the new wheel works. @jadsk can you confirm that the wheel works for you?

**Comment by jadsk** [comment]
I successfully installed the wheel, but now this error:

Traceback (most recent call last):
  File "main.py", line 82, in <module>
    from eye import eye
  File "C:\Users\L\Pupil\pupil\pupil_src\capture\eye.py", line 38, in <module>
    from video_capture import autoCreateCapture, FileCaptureError, EndofVideoFil
eError, CameraCaptureError
  File "C:\Users\L\Pupil\pupil\pupil_src\shared_modules\video_capture\__init__.p
y", line 41, in <module>
    from win_video import Camera_Capture,device_list,CameraCaptureError
  File "C:\Users\L\Pupil\pupil\pupil_src\shared_modules\video_capture\win_video.
py", line 10, in <module>
    import videoInput as vi
  File "C:\Python27\lib\site-packages\videoInput.py", line 28, in <module>
    _videoInput = swig_import_helper()
  File "C:\Python27\lib\site-packages\videoInput.py", line 20, in swig_import_he
lper
    import _videoInput
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by MichaelBarz** [comment]
Hi, can you tell me your Python version and architecture? The videoInput wheel is for 32-bit only...

**Comment by mkassner** [comment]
closed due to inactivity.
