### ISSUE TITLE
there is only one camera I can use there is no other camera 

### ISSUE THREAD

**Issue by zohaibhassan122** [pupil-labs/pupil#2001]
in my device manager, under  libusbk USB Device, I can only see one camera and other one I can see in regular camera but I can't use it. Please help me to fix it. 
![image](https://user-images.githubusercontent.com/8872102/91840687-60dfb080-ec51-11ea-8caa-3c44ba0ba9df.png)
![image](https://user-images.githubusercontent.com/8872102/91840742-781e9e00-ec51-11ea-985a-09ec467c7b7d.png)

**Comment by pfaion** [comment]
Hi @zohaibhassan122, do I understand correctly, that you want to use the **Sonix Technology Co., Ltd.** camera with the Pupil Software?

**Comment by zohaibhassan122** [comment]
@pfaion  I want to use it with Pupil Capture 2.3

**Comment by pfaion** [comment]
@zohaibhassan122 I'm sorry I'm still not 100% sure if I understand you correctly, can you explain a bit more what's going on?

Do you want to use the **Sonix Technology** as world camera?
Are you having trouble with an eye camera?
What camera stopped working?
What type of headset are you using and in which configuration?
Are you using only a monocular headset?

Could you share the log file with us? If you run Pupil from bundle, you can find it in your home folder > pupil_capture_settings > capture.log

**Comment by zohaibhassan122** [comment]
@pfaion I can't find the log files but this is the error that I get in console cmd.  I am using HTC Vive and eye tracker is HTC Vive Binocular Add-on.  https://pupil-labs.com/products/vr-ar/.  as you can see in the screenshot I can see the video feed from EYE0 BUT  I Can't see video feed from EYE1. 
eye1 - [ERROR] video_capture.uvc_backend: Could not connect to device! No images will be supplied.
eye1 - [INFO] camera_models: No recorded intrinsics found for camera (disconnected) at resolution [192, 192]
eye1 - [WARNING] camera_models: No default intrinsics available! Loading dummy intrinsics!
eye1 - [WARNING] launchables.eye: Process started.

![image](https://user-images.githubusercontent.com/8872102/91856642-1e28d300-ec67-11ea-8797-c7d682e78bf8.png)
![image](https://user-images.githubusercontent.com/8872102/91856662-241eb400-ec67-11ea-9add-5f1ba38e00ec.png)

**Comment by pfaion** [comment]
@zohaibhassan122
This looks like a hardware failure, e.g. a faulty cable or connection.
Please send an email to info@pupil-labs.com and describe the issue.
Please specifically mention the error "EYE1: Could not connect to device! No images will be supplied" and that it worked before.
Our hardware team will then respond to you.

**Comment by kripso** [comment]
Hi. I'm having the same issue. 
Was it a hardware failure?

**Comment by papr** [comment]
@kripso Please contact info@pupil-labs.com in this regard.
