### ISSUE TITLE
Cannot view world camera

### ISSUE THREAD

**Issue by fig8studio** [pupil-labs/pupil#2017]
Even though the Android app works well, I can't seem to get my Invisible to work with Pupil Capture. Any ideas as to why I cannot access my World Camera? To clarify, left and right 'internal' cameras seem to work.
![pupil](https://user-images.githubusercontent.com/62810712/94371910-eaa36200-00c7-11eb-832f-fa333e486914.jpg)

**Comment by flora36** [comment]
Hey,
I had the same issue. You need to install properly two drivers. 

Download and install libusbk 3.0.7.0.(uncheck first and last option)
Download and install Zadig. (when the window appears plug in the headset)
Plugin your Pupil headset.
Start ZadiG. From the options menu, uncheck hide composite devices, and check display all devices.
Locate your Pupil headset composite device. It is very important that you select the composite parent and not one of the interfaces. (select only the pupil world. No need to replace the eyes cameras)
Set the driver replacement to libusbK (v3.0.7.0) and click Replace driver
Verify the driver is correctly replaced. Open device manager. Your Pupil headset cameras should be listed under a new category titled: libusbK USB Devices.

When I followed these steps, the world camera issue was fixed. Please note that I am using windows 10.

Also see : https://docs.pupil-labs.com/core/software/pupil-capture/#video-source-selection
https://zenodo.org/record/201933

Hopefully, it will work for you.

**Comment by papr** [comment]
@fig8studio Pupil Capture does not ship drivers for the Pupil Invisible scene camera. @flora36 is correct taht you will need to install the drivers manually.

Please be aware that Pupil Capture will not work properly with Pupil Invisible glasses due to the eye camera angle. Please use the Companion app instead.
