### ISSUE TITLE
marker_detector.py: can't use 3D localization - dist_coef typo

### ISSUE THREAD

**Issue by Rewasvat** [pupil-labs/pupil#202]
In marker_detector's __init__, the try/except block that loads camera intrinsics does:

dist_coef = np.load(os.path.join(self.g_pool.user_dir,"dist_coefs.npy"))
and then
self.camera_intrinsics = K, dist_coefs, img_size

There's a typo there that prevents camera intrinsics loading and therefore the use of 3D localization.

**Comment by mkassner** [comment]
Thanks for spotting those. We have not used 3d localisation for a bit so. Ill fix all three issues #201 #202 #203 tomorrow.
