### ISSUE TITLE
TypeError: unpackb() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by CyrilAUCLAIR-UnivEiffel** [pupil-labs/pupil#2020]
Good afternoon everyone,

 I (user name on my OS = "AUCLAIR") tried today to lauch Pupil Capture from sources using "run_capture.bat" in "pupil_src", but I had the followind error messages : 

_C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src>run_capture.bat

C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src>SET PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\AUCLAIR\AppData\Local\Programs\Python\Python38;C:\Users\AUCLAIR\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\AUCLAIR\AppData\Local\Microsoft\WindowsApps;C:\Users\AUCLAIR\AppData\Local\GitHubDesktop\bin;C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src\..\pupil_external;C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src\..\pupil_external;C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src\..\pupil_external

C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src>python main.py capture
Traceback (most recent call last):
  File "main.py", line 395, in <module>
    launcher()
  File "main.py", line 260, in launcher
    cmd_sub.recv()
  File "C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src\shared_modules\zmq_tools.py", line 112, in recv
    payload = self.deserialize_payload(*remaining_frames)
  File "C:\Users\AUCLAIR\Documents\GitHub\pupil\pupil_src\shared_modules\zmq_tools.py", line 123, in deserialize_payload
    payload = serializer.loads(payload_serialized, encoding="utf-8")
  File "msgpack\_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'_

Can someone please help me to solve my problem ?

Thank you in advance,
Cyril

**Comment by pfaion** [comment]
Hi, it seems you are using Python 3.8 on Windows to run Pupil?
Unfortunately we currently only support Python 3.6 on Windows, please try again with Python 3.6.

**Comment by papr** [comment]
Also, make sure to install the correct version of msgpack with `pip install msgpack==0.5.6`

**Comment by pfaion** [comment]
In general, please follow the docs for setting up running Pupil from source on Windows very closely:
https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md
