### ISSUE TITLE
Pupil labs crashes when I start recording

### ISSUE THREAD

**Issue by thomasf4231** [pupil-labs/pupil#2031]
Hi,
Until today I had no problems using pupil capture when after 2 normal recordings pupil capture always started crashing after I started the recording with the following note:

world - [INFO] file_methods: C:\Users\thoma\pupil_capture_settings\user_calibration_data has a deprecated format: Will be updated on save

world - [ERROR] launchables.world: Process Capture crashed with trace:

Traceback (most recent call last):

  File "shared_modules\file_methods.py", line 80, in load_object

  File "site-packages\msgpack\__init__.py", line 58, in unpack

  File "msgpack\_unpacker.pyx", line 211, in msgpack._unpacker.unpackb

msgpack.exceptions.UnpackValueError: Unpack failed: error = 0

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "launchables\world.py", line 632, in world

  File "shared_modules\recorder.py", line 258, in on_notify

  File "shared_modules\recorder.py", line 352, in start

  File "shared_modules\file_methods.py", line 90, in load_object

  File "shared_modules\file_methods.py", line 69, in _load_object_legacy

EOFError: Ran out of input

 

world - [INFO] launchables.world: Process shutting down.

eye0 - [INFO] launchables.eye: Process shutting down.

eye1 - [INFO] launchables.eye: Process shutting down.

Has anyone experienced this before or does anyone have an idea how I could fix that?

Many thanks in advance!

**Comment by papr** [comment]
@thomasf4231 Hi 👋 

Could you please share this file and let us know which version of Capture you are using?
> C:\Users\thoma\pupil_capture_settings\user_calibration_data

Afterward, delete the file. This should fix the issue.

**Comment by thomasf4231** [comment]
@papr 
Thank you so much for the quick reply! It worked!

I am using version 1.23-4 (because I need the audio capture).
Somehow the file was empty (maybe because I set pupil capture to default settings in the application before as it was my initial approach to solve the problem).
I tried to attach the file anyways but it seems like the file type is not supported.

**Comment by papr** [comment]
@thomasf4231 This file is not supposed to be empty. Let us know if you run into the issue again.
