### ISSUE TITLE
Fixations/gaze missing from the screen

### ISSUE THREAD

**Issue by mihaelataranu** [pupil-labs/pupil#2032]
Hi, 
I use the latest version of the Pupil Capture to record some sessions with children (around 20 minutes/child) and for a full day I had recordings of 4 children where I couldn't see any fixations/gaze on the screen. When I upload the videos in Pupil Player a message says No data available to find fixations. The Annotation plug-in is uploaded, the confidence is ok (it drops many times, but there are periods where is higher than .8 for both eyes or just one eye). What do you suggest I might do wrong/it might go wrong? Was thinking it could be the light (but using the same room/light I can open Pupil Player and the eye trackers can record the fixations almost instantly). What do you think I should check/be aware of?

Thanks!!

**Comment by papr** [comment]
Hi @mihaelataranu Fixations require gaze data. Since Pupil 2.0, gaze will only be visualized and recorded after calibrating successfully. Feel free to share a recording with `data@pupil-labs.com` for us to review.

**Comment by mihaelataranu** [comment]
I undertand what you say, but sometimes I can put the eye-tracking on, open the Pupil Capture and I can see the fixations on the screen instantly, without needing to the calibration first. 
I would like to send a recoding and get your feedback on what went wrong. Thank you!

**Comment by papr** [comment]
This is because Pupil Capture stores the last calibration in the session settings and restores them when you start a new session. Nonetheless, it is recommended to recalibrate if you put down the headset between sessions or when switching subjects.
