### ISSUE TITLE
Using adapter to charge and use Pupil labs invisible companion simultaneously.

### ISSUE THREAD

**Issue by flora36** [pupil-labs/pupil#2034]
Hello,

I am running an experiment with Pupil Labs Invisible. My study last more than 1 hour. I am also using the wi-fi to stream my experiment via the Pupil Invisible Monitor. As a result, the battery from the mobile phone drops quite fast.

So i was wondering if i can use a usb adapter that will allow me to charge the phone and run the eye tracker at the same time. 
Is there any potential danger to damage the eye tracker's electronics if i do this? 

Many thanks

**Comment by papr** [comment]
Hi @flora36 

With Pupil Invisible, we are working at the edge of what is possible given the phone's hardware. We have not tested any such adapters and also do not recommend using them. Instead, we recommend a dual-phone setup, where you switch devices during breaks. This allows one phone to record and the other to charge and start uploading the recording to Pupil Cloud.

As an alternative, we will be supporting the OnePlus 8 soon, which will allow for much longer recording times.

**Comment by flora36** [comment]
Thank you so much for the quick response and suggestions. 

Looking forward to using the OnePlus8.
