### ISSUE TITLE
Player error (linux) libav.mjpeg ?

### ISSUE THREAD

**Issue by Sijben** [pupil-labs/pupil#204]
Trying to play a recording grants to following screen:
![player_screenshot](https://cloud.githubusercontent.com/assets/14055306/10017750/5b46d06e-6131-11e5-8bd9-42fc6f593703.png)

Terminal log starting at opening player:

eyetracker@ubuntuOLF:~/PUPILINSTALL/pupil/pupil_src/player$ python main.py
Player [WARNING] __main__ : You did not supply a data directory when you called this script!
Player [ERROR] player_methods : No valid dir supplied
Player [INFO] plugin : Loaded: Trim_Marks
Player [INFO] plugin : Loaded: Seek_Bar
Player [INFO] plugin : Loaded: Log_Display
Player [INFO] video_capture.file_capture : Filecapture is not a realtime source. -NOW- will be the current timestamp
Player [ERROR] libav.mjpeg : overread 8
Player [ERROR] libav.mjpeg : error count: 70
Player [ERROR] libav.mjpeg : error y=1 x=0
Player [ERROR] libav.mjpeg : error count: 64
Player [ERROR] libav.mjpeg : error y=43 x=0
Player [ERROR] libav.mjpeg : error count: 65
Player [ERROR] libav.mjpeg : error y=13 x=3
Player [ERROR] libav.mjpeg : error count: 65
Player [ERROR] libav.mjpeg : error y=26 x=0
Player [ERROR] libav.mjpeg : error count: 69
Player [ERROR] libav.mjpeg : error y=2 x=0
Player [ERROR] libav.mjpeg : error count: 65
Player [ERROR] libav.mjpeg : error y=3 x=0
Player [ERROR] libav.mjpeg : error count: 72
Player [ERROR] libav.mjpeg : error y=1 x=0
Player [ERROR] libav.mjpeg : error count: 64
Player [ERROR] libav.mjpeg : error y=5 x=1
Player [ERROR] libav.mjpeg : error count: 72
Player [ERROR] libav.mjpeg : error y=1 x=1
Player [ERROR] libav.mjpeg : error count: 64
Player [ERROR] libav.mjpeg : error y=53 x=11
Player [ERROR] libav.mjpeg : error count: 64
Player [ERROR] libav.mjpeg : error y=2 x=1
Player [ERROR] libav.mjpeg : error count: 72
Player [ERROR] libav.mjpeg : error y=16 x=4

Video files are not corrupted (work just fine in normal video player), running as sudo didn't change anything. Running with plugins closed doesn't help either.

Interesting is that the eye recording appears to be just fine.

**Comment by mkassner** [comment]
This is a perfect example of #187 

If you try the bundled player it will be fine. 

I need to update the install instructions to use the real version of ffmpeg not the old one that comes with ubuntu.

**Comment by Sijben** [comment]
Is there an ETA on the install instructions update? The bundled player still suffers from issue #200

**Comment by mkassner** [comment]
The instructions have been updated. 

But are you sure the player bundle has an import problem? Or do you mean the recording does not play back correctly? I have just tested the bundle version 0.6 and it worked fine. Please send a screenshot or log for the bundle player error.

Thanks!

**Comment by Sijben** [comment]
My apologies, I got the issues mixed up. The bundled player (latest tested = 0.6.11) didn't display the markers/frames correctly as fixed here (https://groups.google.com/forum/#!topic/pupil-discuss/0gPXg9wID14) which is why I switched to the source version.

**Comment by mkassner** [comment]
Ah Ok. I just uploaded the player bundle with the latest set of changes to here:  https://github.com/pupil-labs/pupil/releases/tag/v0.6.10
