### ISSUE TITLE
ROI mode rendering and inputs processed at sub-fps (flashing)

### ISSUE THREAD

**Issue by bpinsard** [pupil-labs/pupil#2042]
When activating the ROI or algorithm mode in eye process, the ROI/algorithm is rendered irregularly resulting in flashing.
Activating one of the corner only works intermittently (can activate it by clicking repeatedly fast, same for deactivating).

This is not with pupil headset so it might only occur when the NDSI backend is not used. The latter might introduce some constant run time of the event loop due to network polling.
Without that plugin, even in the absence of frames, the event loop uses 100% CPU on my setup (it is expected: it runs as fast as possible).
It results in calling plugins recent_events at higher frequency, in the case of ROI plugin it sets `self.has_frame=False` most of the time:
https://github.com/pupil-labs/pupil/blob/300a75efcd5621413d6ec973f02fbecf074c0dfa/pupil_src/shared_modules/roi.py#L285
and thus skips rendering most of time when screen is updated:
https://github.com/pupil-labs/pupil/blob/300a75efcd5621413d6ec973f02fbecf074c0dfa/pupil_src/shared_modules/roi.py#L306-L308
and also skips event processing as well:
https://github.com/pupil-labs/pupil/blob/300a75efcd5621413d6ec973f02fbecf074c0dfa/pupil_src/shared_modules/roi.py#L291-L293
https://github.com/pupil-labs/pupil/blob/300a75efcd5621413d6ec973f02fbecf074c0dfa/pupil_src/shared_modules/roi.py#L352-L354

I am not sure what is the best way to correct this.
Was there was a specific reason for skipping `gl_display` and `on_click` if no frame was received right before screen refresh/input.
Thanks!

**Comment by papr** [comment]
Hi,

The world and eye processes' event loops are meant to be timed by the video source, i.e. if the video source provides frames at 200Hz, the event loop will run at 200Hz. If there is a timeout/no frame, the application assumes that the camera is disconnected.

It looks like your video source does not wait for a frame but return `None` immediately if no frame is ready. This is not the intended use. If you find a way to block until a timeout, e.g. 1/30 seconds, or a frame is available, you should see these issues disappear and also see your CPU usage go down considerably.

Let me know if my assumption is correct and if this response was helpful.

**Comment by bpinsard** [comment]
You are right, my mistake, I am returning None if no frame is available.
I changed the code to make it wait for a frame before returning (unless camera is disconnected/stopped).
Thanks a lot for your help.

**Comment by bpinsard** [comment]
It also explains why the #2040 #2041 should not make much difference in terms of performance now that the event loop rate is capped. They should still be slightly beneficial if camera's framerate is greater than screen refresh rate as with our camera.

**Comment by papr** [comment]
@bpinsard I agree that #2040 and #2041 are useful changes nonetheless!
