### ISSUE TITLE
Pupil Mobile - No detection of eye-tracker

### ISSUE THREAD

**Issue by MLT-SEP** [pupil-labs/pupil#2056]
I have no detection of the three cameras of the eye-tracker on the phone and it occurred sometimes with no explanation.
For more information, I used Pupil Mobile with Version 1.2.1, Android Version 9, I connected OTG setting on my phone, I used a proper USB-C to USB-C cable and I tried with and without Wifi.
I needed to connect eye tracker on the computer to have detection on the phone after. 

Could you help me to fix this problem please because I do not understand the problem with the Pupil Mobile ? 

Thank you in advance,

**Comment by papr** [comment]
@MLT-SEP Hi, do I understand correctly that the eye tracker works correctly on the computer running Pupil Capture but not when connecting it to mobile phone?

**Comment by papr** [comment]
@MLT-SEP Please be aware that OTG turns off after having no device connected for a while. Could this be an explanation?

**Comment by MLT-SEP** [comment]
@papr Unfortunately not because I was aware about that.

**Comment by papr** [comment]
@MLT-SEP Ok. Could you clarify if the cameras stopped being detected during an active session, or if they are correctly detected for complete sessions and sometimes not at all?

**Comment by MLT-SEP** [comment]
It is the second option described : sometimes it was not detected at all so I had no possibility to record session.

**Comment by papr** [comment]
@MLT-SEP Ok, this means we can exclude a loose contact as a possible cause. I am not aware of any reason for Pupil Mobile not to recognize the headset other than:
- The headset is not properly connected
- OTG is disabled

If there was a hardware failure it usually shows as temporary disconnects during a session.

**Comment by MLT-SEP** [comment]
@papr 
Thank you for your help. I checked the headset and the OTG, I think it is not that. I already tried with another USB-C cable just in case.
Could you explain me the hardware failure ? I could try.

**Comment by papr** [comment]
If there was a loose connection between one of the cameras and the headset, you would see that video stream stop temporarily. The other cameras would remain connected.

**Comment by papr** [comment]
Given Pupil Mobile is not longer being maintained and this issue seems to be stale, I will close it. Please let us know if there is new information regarding this issue.

**Comment by MLT-SEP** [comment]
Yes you can close it, thank you.
However, why Pupil Mobile is not maintained ? Where can I find information about it and how can we use eye-tracking system with Android without Pupil Mobile app ? (sorry it is not in the perfect issue).

**Comment by papr** [comment]
Please see https://github.com/pupil-labs/pupil-mobile-app/#depreciation-warning
