### ISSUE TITLE
Camera choice

### ISSUE THREAD

**Issue by souravrs999** [pupil-labs/pupil#2057]
Why did pupil capture software recommend logitech C525/C512 and Microsoft HD-6000 and why does it crash when used with other cameras

Thanks in advance

**Comment by papr** [comment]
Hi @souravrs999. The DIY Kit was developed a few years ago and these cameras were the best fit at the time. We support all cameras that fulfill these requirements:
1) UVC 1.1 [1] (Chapters below refer to this document)
2) Support Video Interface Class Code `0x0E CC_VIDEO` (see A.1)
3) Support Video Subclass Code `0x02 SC_VIDEOSTREAMING` (see A.2)
4) Support for the `UVC_VS_FRAME_MJPEG (0x07)` video streaming interface descriptor subtype (A.6)
5) Support `UVC_FRAME_FORMAT_COMPRESSED` frame format

[1] http://www.cajunbot.com/wiki/images/8/85/USB_Video_Class_1.1.pdf

Currently, we do not support UVC 1.5 cameras. See this [active issue for reference](https://github.com/pupil-labs/pupil/issues/1878).

**Comment by souravrs999** [comment]
> Hi @souravrs999. The DIY Kit was developed a few years ago and these cameras were the best fit at the time. We support all cameras that fulfill these requirements:
> 
> 1. UVC 1.1 [1] (Chapters below refer to this document)
> 2. Support Video Interface Class Code `0x0E CC_VIDEO` (see A.1)
> 3. Support Video Subclass Code `0x02 SC_VIDEOSTREAMING` (see A.2)
> 4. Support for the `UVC_VS_FRAME_MJPEG (0x07)` video streaming interface descriptor subtype (A.6)
> 5. Support `UVC_FRAME_FORMAT_COMPRESSED` frame format
> 
> [1] http://www.cajunbot.com/wiki/images/8/85/USB_Video_Class_1.1.pdf
> 
> Currently, we do not support UVC 1.5 cameras. See this [active issue for reference](https://github.com/pupil-labs/pupil/issues/1878).

Thanks for the reply and proper explanations
