### ISSUE TITLE
Retrieve gaze position

### ISSUE THREAD

**Issue by Zumbalamambo** [pupil-labs/pupil#2078]
I have recorded a session with the Pupil recorder. It has got the `world.mp4` as well as many other files. How do I retrieve the gaze position in every individual frame of the video? Is there any sample?

**Comment by papr** [comment]
You can find several examples of how to use the exported data [here](https://github.com/pupil-labs/pupil-tutorials). The `gaze_positions.csv` file has a column `world_index` which indicates to which world frame it belongs. There is also a tutorial on how to extract frames from the video file.
