### ISSUE TITLE
d435 plugin 

### ISSUE THREAD

**Issue by templeside** [pupil-labs/pupil#2080]
Hi, I want to connect intel realesense d435 on my pupil core.
The insturction about RealSense2 Backend for Pupil Capture v1.22+: "Now you need to get pyrealsense2 into the plugin folder as well, such that the realsense backend can import pyrealsense2. For this you can either try installing it into the plugins folder, or install it in a local python installation/environment and symlink the library into the plugins folder."
Just like the instruction, I want to install the plugin of d435 on local PATH, and want to install the pyrealsense under my pupil_capture_settings.
What i've done is 
 - installed pip pyrealsense2
    $pip install pyrealsense2
 - downloaded realsense2_backend(from gist at: https://gist.github.com/romanroibu/c10634d150996b3c96be4cf90dd6fe29 ) on location at: C:\Users.........\pupil_capture_settings\plugins
 - installed source file under the plugins direction
    $pip install -t .\plugins\pyrealsense2\ pyrealsense2

when i turn on the pupil capture 2.6.19, I can see the Realsense2 Source toggle under the Plugin Manager. However, when I click the toggle, the program is freezed and have no response.

the error code that I've got is "AttributeError: module 'pyrealsense2' has no attribute 'context'"

file directory i've got is under:
└─plugins
    └─pyrealsense2
        ├─bin
        │  └─__pycache__
        ├─pyrealsense2
        │  └─__pycache__
        └─pyrealsense2-2.41.0.2666.dist-info
please let me know the error that I've got.

Thanks.

**Comment by papr** [comment]
Hi,

Since we have been in contact via Discord already, I suggest we continue the discussion about this issue on Discord.

Best,
Pablo
