### ISSUE TITLE
Pupil capture world camera doesn’t work

### ISSUE THREAD

**Issue by hychen-naza** [pupil-labs/pupil#2081]
Hi, I am using Pupil Core binocular eye tracker in Ubuntu 18.04 ( kernel 4.15). And I meet the same problem described in issue 767 (https://github.com/pupil-labs/pupil/issues/767), the world camera keeps grey.
In issue 767, it said world camera uses Intel RealSense R200 RGBD camera, however, I find that R200 is only supported in Ubuntu 14 and 16. Does it mean I can not use it in Ubuntu 18.04? Or Pupil Core has used another version of Intel RealSense? 
Appreciate any help, thanks!

**Comment by papr** [comment]
Please see [my response to your question on Discord](https://discord.com/channels/285728493612957698/285728493612957698/798164469300723723).
