### ISSUE TITLE
Batch export fixations and post-hoc pupil detection

### ISSUE THREAD

**Issue by JelleVE** [pupil-labs/pupil#2097]
I have a large set of recordings for which I want to generate the fixations, as well as do the post-hoc pupil detection. Is there a plugin or a script available for doing this type of (batch) post-processing? Or is it maybe possible to do this through the command line instead of using the application's GUI?
If not, does anyone have some recommendations on how to create such a script?

**Comment by papr** [comment]
Hey,
Unfortunately, there is no such functionality built-in. I recommend having a look at our [community](https://github.com/pupil-labs/pupil-community) repository. There are some related projects which you might be able to make use of.
