### ISSUE TITLE
Fresh Installation Pupil Capture Exception 

### ISSUE THREAD

**Issue by linussun** [pupil-labs/pupil#2098]
Even after a fresh installation, Pupil-Capture throws the following exception, and freezes on launching the pupil-capture world camera window due to the exception below.  Searched for this, doesn't seem like a previous bug that was discussed.   Wondering if someone has experienced similar and can make a suggestion to help resolve this. 

```
world - [INFO] numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
world - [INFO] numexpr.utils: NumExpr defaulting to 8 threads.
world - [INFO] launchables.world: Application Version: 3.1.16
world - [INFO] launchables.world: System Info: User: Psychophys, Platform: Windows, Machine: PsychophysSC4, Release: 10, Version: 10.0.18362
world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "pyre\zactor.py", line 59, in run
  File "pyre\zbeacon.py", line 66, in __init__
  File "pyre\zbeacon.py", line 303, in run
  File "pyre\zbeacon.py", line 218, in handle_pipe
  File "pyre\zbeacon.py", line 201, in configure
  File "pyre\zbeacon.py", line 73, in prepare_udp
  File "pyre\zbeacon.py", line 137, in _prepare_socket
  File "pyre\zhelper.py", line 113, in get_ifaddrs
  File "pyre\zhelper.py", line 527, in get_win_ifaddrs
ValueError: NULL pointer access
```

Solutions attempted that did not work:
1. Delete the Pupil-Capture settings folder in User directory
2. Try older version of Pupil-Capture (1.6.x and 2.2.x), crashes with same exception.
3. Upgrade python dependencies (python 3.6 in Windows)
4. Try installation on a different PC running same version of Windows does work! (What is it about some Windows 10 installations that make it impossible to install a fresh working version of pupil capture?)

System information:
Windows 10 Enterprise
Version 10.0.18363 
Memory: 32G
Free space on C: >16 Gigs free

**Comment by papr** [comment]
Hey,
this issue is not directly related to this repository but to one of our dependencies. See https://github.com/zeromq/pyre/issues/137 reports the same exact issue.

Are you using Windows 10 Enterprise in all of your cases? Is it possible that your PCs have different permission/administrator setups?

**Comment by linussun** [comment]
Thanks for getting back so quickly. 

I am using W10 Enterprise same build in all of my cases. As far as permissions go, it's straight forward  admin access for all the accounts that are used that launched pupil_capture.

Other solutions I've tried:
1. Checked properties of pupil_capture.exe, python.exe and confirmed in the security tab that Administrators have Full control permissions.
2. Install Python 3.8 (does this matter at all, I wonder does pupil-labs comes with its own python installation?) and step #1.
3. Uninstalled various software packages .NET (National instruments), VPN etc, that were installed after last time Pupil_capture worked, restarted the PC, tried pupil_capture again. 

I'm a bit of a loss here and don't really want to reinstall Windows 10 just yet. Any other suggestions? 

I see that this part of zeromq is where it parses out the ipaddress on the PCs,

```
def get_win_ifaddrs():
    """
    A method for retrieving info of the network
    interfaces. Returns a nested dictionary of
    interfaces in Windows.
```

Thanks again!

**Comment by linussun** [comment]
@papr  We found a quick fix and that was to uninstalling Cisco VPN specifically the Cisco AnyConnect Secure Mobility Client Virtual Miniport Adaptor for Windows x64 from the Windows 10 machine that was having trouble. We surmise that the VPN network adaptor was being enumerated improperly by zhelper.py returning a NULL POINTER within in the code at some point; this may or may not have been due to an update in Windows 10, but don't really want to spend the time to figure out why.

@playaspec describes it more in detail here: 
https://github.com/zeromq/pyre/issues/137#issuecomment-785979706
