### ISSUE TITLE
redefine recording data format

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#21]
* pupil_positons should only hold pupil positions (add field to indicate left/right eye), use np.rec_array
* add gaze_positons.npy file with gaze positions
* use mp4 instead of avi container
* update documentation

**Comment by mkassner** [comment]
Gaze and pupil pos are now separated.
Need to decide and test video file container and codec

**Comment by mkassner** [comment]
Video Format: Matroska: http://matroska.org/technical/whatis/index.html

Pros:
+ open source
+ modern
+ supported by Windows10, Android and Ubuntu
+ Everywhere else it will play with VLC

Cons:
+ does not play on Apple Quicktime player.

**Comment by mkassner** [comment]
Codec should be left unspecified but all used codecs should be supported by our media backend.

**Comment by mkassner** [comment]
timestamps should be called world_timestamps

**Comment by cpicanco** [comment]
For instance, about the cons, this is from the matroska FAQ list:

> Q: How can i play Matroska files on my PC ?
> A: On the download page you will always find the link to the very latest DirectShow parser filter, that way you will be able to play your .mkv files on a DirectShow based player such as Windows Mediaplayer. For Linux PCs, as well as for MacOSX and the X-Box emulation you have to get the newest version of VLC or mplayer. On OS X you can also install Perian which will add Matroska support in Quicktime.

**Comment by willpatera** [comment]
@cpicanco according to [recent news](http://www.theverge.com/2014/12/9/7359277/windows-8-1-mkv-file-support-features) `.mkv` files will be natively supported on Windows 8.1. So to me the only 'con' regarding non-native playback would be on MacOS as @mkassner listed above - which can be worked around by using VLC. See also this [wikipedia page](http://en.wikipedia.org/wiki/Comparison_of_container_formats) comparing container formats.

**Comment by mkassner** [comment]
I would also like to use something more widespread and common as .mp4 the problem is however that its not open and ill supported by gstreamer (which is used by opencv).

**Comment by mkassner** [comment]
The format as it stands now is:
* info.csv
* pupil_positions.npy
* gaze_positions.npy
* world.mkv
* world_timestamps.npy
* eye.mkv (optional)
* eye_timestamps.mkv (optional)

If there are issues and requests please re-open this issue or raise a new one with reference to #21

**Comment by cpicanco** [comment]
Hey, I think it is eye_timestamps.npy... ;), please, delete this post after edit.
