### ISSUE TITLE
Development Questions

### ISSUE THREAD

**Issue by mhuzai** [pupil-labs/pupil#2102]
I had two questions regarding doing development with Pupil Labs software.

1. Is there, or are there plans to create, a C++ API?
2. The documentation link in the README is broken. It gives a 403 error. Where can I find documentation on the code (file structure, which features are where, etc.)?

Thank you!

**Comment by papr** [comment]
Hi,

1. No, there is no plan for a C++ API. The recommended way to interact with Pupil Capture in real-time is to use the [Network API](https://docs.pupil-labs.com/developer/core/network-api/).
2. Could you please specify which link you are referring to?

Best,
Pablo

**Comment by mhuzai** [comment]
Thanks for the confirmation on the C++ API.

This is the line from the README that I was talking about. The linked URL does not work for me.

_All setup and dependency installation instructions are contained in this repo. All other developer documentation is [here](https://docs.pupil-labs.com/developer/core/)._

**Comment by papr** [comment]
@mhuzai Thank you! This is the correct link: https://docs.pupil-labs.com/developer/core/overview/
