### ISSUE TITLE
Pupil Labs invisible - Pupil detection with Pupil Player.

### ISSUE THREAD

**Issue by flora36** [pupil-labs/pupil#2104]
Hello,

I have an issue with the data recorded with the Pupil labs Invisible. 

When exploring the recordings with the Pupil labs player there is a consistent problem with the left side eye camera. The pupil detector almost always fails to properly track the pupil, leading to very low confidence. Therefore it is very difficult for me to analyze these data as it is not clear where my participants are looking at (or to better say I cannot trust the gaze detection the model provides). This problem is more prominent and occasionally appears on the other eye camera (right side eye camera), when participants are looking straight ahead which I think has to do with the design of the eye tracker.
One thing I noticed is that the angle of the eye cameras is not the same (please see images). I have tried the glasses with different people, but the difference between these two cameras is consistent. 

Any advice on how to improve pupil detection and in general the overall quality of my recordings (even post - hoc)?  

![example1](https://user-images.githubusercontent.com/72200619/109149191-2453c400-775f-11eb-97af-f30eb71d77b1.jpg)

![example2](https://user-images.githubusercontent.com/72200619/109149221-2d449580-775f-11eb-9838-a39ba9e9d9f9.jpg)

Many thanks,

Flora

**Comment by papr** [comment]
Hi,

Please understand that Pupil Player does not officially support post-hoc pupil detection and calibration. Pupil Invisible has a camera angle that requires special software for gaze estimation. If you are having issues with the provided gaze estimation by Pupil Invisible Companion or Pupil Cloud, please contact `info@pupil-labs.com`. Please also note, that none of our products does currently provide pupillometry data for Pupil Invisible data.
