### ISSUE TITLE
How to use "Cam ID2" with openCV and "Cam ID0" with Pupil Capture?

### ISSUE THREAD

**Issue by willybtt** [pupil-labs/pupil#2105]
Hello everyone! Actually, I am doing a project with Pupil Core and I need to open the world camera (Cam ID2) with openCV (to do an image processing), but at the same time, I need to open pupil camera (Cam ID0) with Pupil Capture (to get the pupil data).

I managed to open Cam ID2 with openCV thanks to a post on this forum, in which I had to uninstall the official driver in "Device Manager" until py PC recognized it as a camera. 

The problem is that when I want to open the World Camera (Cam ID2) with openCV and pupil camera (Cam ID0) with Pupil Capture at the same time, Pupil Capture crashes, and it is impossible to get the pupil data, or reinstall the official world camera driver (Cam ID2) and it is impossible to open Cam ID2 with openCV.

So, would there be any way to open both cameras separately without any problem?

Thank you.

**Comment by papr** [comment]
Hey, you can use the Network API to receive the scene camera images in an external script. Check out this example for reference: https://github.com/pupil-labs/pupil-helpers/blob/master/python/recv_world_video_frames_with_visualization.py

**Comment by willybtt** [comment]
Thanks for the quick response, Pablo. That code helps me, but there is a problem. 
As the connection is TCP, all data must arrive in order, and new data will not be received until the previous one has been received.
This includes a very large lag in the video.
Also, the video shown by openCV is not very fluent

A solution to the lag is to create a connection for each frame, but this does not solve the fluidity problem (I have measured the time it takes to display 100 frames and the result is about 14 fps).

The video setting in Pupil Capture is 720p 30 fps.
Would it be possible to increase fluency?
