### ISSUE TITLE
Distorted markers in screen calibration

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#211]
Linux. I was used to circles, not ellipses. Just reporting. 
![screenshot from 2015-10-04 22 08 54](https://cloud.githubusercontent.com/assets/6511849/10271429/ee067a0a-6ae4-11e5-8c81-26aed5aa4e85.png)

**Comment by cpicanco** [comment]
I think the calculations and the actual drawing should be done after resizing the window. Image is being stretched. It will tend to become uglier with larger screens.

**Comment by mkassner** [comment]
Thanks for catching this!

**Comment by cpicanco** [comment]
Fixed.
