### ISSUE TITLE
How to increase the video transfer rate through the TCP socket?

### ISSUE THREAD

**Issue by willybtt** [pupil-labs/pupil#2116]
Hello everyone! Thanks to the post [recv_world_video_frames.py](https://github.com/willybtt/pupil-helpers/blob/master/python/recv_world_video_frames.py) I can receive the video frames from pupil core. 

But there is a problem. The video has a lot of lag and little fluency (few fps). This happens because the connection is TCP, and it is necessary to send the confirmation message (ACK) of each frame received in order to receive the next one.

The lag is solved by creating a new connection for each frame that you want to receive, but the little fluidity is not solved like that.
So, how could fluency be increased? I have two questions that could solve it:

1) Would it be possible to receive the video by UDP connection?

2) Can the data that I want to receive for each TCP connection (or UDP if it possible) be configured in some way? That is, if I only want to receive the frames, configure in some way that the pupil data is not received (and vice versa).

Thanks in advance.

**Comment by papr** [comment]
Would you mind sharing the code that you use to receive the data? The IPC backend is tcp based. If you wanted a udp transfer you would have to recreate the frame publisher with a udp socket.

**Comment by willybtt** [comment]
Thanks for the quick response Pablo. I share the code (I also attach a .zip with the code in case it cannot be copied correctly from my message). It is practically what is in the help code of [recv_world_video_frames.py](https://github.com/willybtt/pupil-helpers/blob/master/python/recv_world_video_frames.py) but rerunning it every "cont" loop iterations "while (end_loop == 0)". There are also some math operations, but they are only for printing fps and average fps.


`import zmq
from msgpack import unpackb, packb
import numpy as np
import cv2
from time import time




recent_world = None
recent_eye0 = None
recent_eye1 = None


FRAME_FORMAT = 'bgr'

end_loop = 0
counter = 0



mean = 0
iterations = 0
summation_ratio_fps = 0

time_start = time()
try:
    while end_loop == 0:

        if counter == 0 or counter >= 2:
            time_finish = time()
            dif = time_finish - time_start
            if dif == 0: # so that it is not divided by 0
                dif = 1 
            
            ratio_fps = counter/dif           
            print("In " + str(dif) + "seconds, there are " + str(counter) +
                   "frames. Ratio = " + str(ratio_fps))
            time_start = time()
            counter = 1
            iterations = iterations + 1
            summation_ratio_fps = summation_ratio_fps + ratio_fps
            
            mean_acumulate = summation_ratio_fps/iterations
            
            print("mean = ", mean)
            print ("summation acumulate = ", summation_ratio_fps, 
                   "  iterac= ", iterations)
            print("mean acumulate = ", mean_acumulate)
            
            addr = '127.0.0.1'  # remote ip or localhost
            req_port = "50020"  # same as in the pupil remote gui
            context = zmq.Context()
            req = context.socket(zmq.REQ)
            req.connect("tcp://{}:{}".format(addr, req_port))
            req.send_string('SUB_PORT')
            
            sub_port = req.recv_string()
            
            sub = context.socket(zmq.SUB)
            sub.connect("tcp://{}:{}".format(addr, sub_port))
            sub.setsockopt_string(zmq.SUBSCRIBE, 'frame.')
            
        topic = sub.recv_string()
        payload = unpackb(sub.recv(), encoding='utf-8')
        
        
        extra_frames = []
        while sub.get(zmq.RCVMORE):
            extra_frames.append(sub.recv())
        if extra_frames:
            payload['__raw_data__'] = extra_frames
        
        
        msg = payload    
        
    
            
        if topic.startswith('frame.') and msg['format'] != FRAME_FORMAT:
                print(f"different frame format ({msg['format']}); skipping frame from {topic}")
    #             continue
        
        
        # Adapt code for gray (only 1 pixel matrix) or BGR (3 pixels matrix)
        if msg['format'] == 'gray':
            depth = 1   
        elif msg['format'] == 'bgr':
            depth = 3    
        
        if topic == 'frame.world':
            recent_world = np.frombuffer(msg['__raw_data__'][0], dtype=np.uint8).reshape(msg['height'], msg['width'], depth)
    
        elif topic == 'frame.eye.0':
            recent_eye0 = np.frombuffer(msg['__raw_data__'][0], dtype=np.uint8).reshape(msg['height'], msg['width'], depth)
    
        
        if recent_world  is not None and recent_eye0 is not None:
            cv2.imshow("world", recent_world)
            cv2.imshow("eye0", recent_eye0)
            
            if (cv2.waitKey(1) and 0xFF == ord('s')) or cv2.waitKey(30) == ord('s') or cv2.waitKey(30) == ord('S'):
                end_loop = 1
                
                print("End Loop")
                    
    
        counter = counter + 1



    

        
except KeyboardInterrupt:
    pass
finally:
    cv2.destroyAllWindows()


`

About recreate the frame publisher with a udp socket, is there any example (in any language) in which it is done?

 
[Conection_video_pupil.zip](https://github.com/pupil-labs/pupil/files/6133724/Conection_video_pupil.zip)

**Comment by papr** [comment]
Apologies for the delayed response. The while loop will only run as quickly as its slowest component. cv2.imshow and cv2.waitKey are slowing down your script in this case. This is why you are seeing dropped frames. Because zmq drops data at the end of the queue---when it is full---you are seeing the delay. The trick is to process all queued data first and then draw the most recent frame. We will need to update [this example](https://github.com/pupil-labs/pupil-helpers/blob/master/python/recv_world_video_frames_with_visualization.py) to follow this recommendation. I will leave the issue open until then.

**Comment by papr** [comment]
The scripts were not following the best practices on high-frequency data processing yet. I updated the scripts accordingly. See [this section](https://github.com/pupil-labs/pupil-helpers/blob/master/python/recv_world_video_frames_with_visualization.py#L77-L118) in particular.

**Comment by WilliamBTT** [comment]
Thank you so much Pablo!!
