### ISSUE TITLE
Windows dependencies slightly out of date - bad link and missing file

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#2127]
https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md

The ffmpeg link is broken, and postproc-55.dll is no longer a part of the latest builds.  This does not appear to cause pupil to craash when run from source.

**Comment by papr** [comment]
Unfortunately, https://ffmpeg.org/download.html only offers two sources:
- https://www.gyan.dev/ffmpeg/builds/ and
- https://github.com/BtbN/FFmpeg-Builds/releases

The former does not provide the required DLL files. The latter has the following Release Retention Policy:
>    The last build of each month is kept for two years.
>    The last 14 daily builds are kept.

I guess we linked to a daily build.

@performlabrit could you please check if this build works for you? https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-03-31-12-39

**Comment by performlabrit** [comment]
Yes, that linked worked.  You might also point out that they should get the lgpl shared binaries, and not vulkan or gpl binaries, if that matters. I don't believe that information was not explicitly provided in the instructions, but was evident if one inspected the dead link.


- gD


----------------------

Gabriel J. Diaz, Ph.D.
Associate Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

Founder of PerForM Labs
Click for demos.<https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215<tel:(585)%20475-6215>
***@***.******@***.***>
________________________________
