### ISSUE TITLE
Improve the log system.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#213]
I just can't read fast enough to make any sense of the log messages fading in and out of the screen. There is no point in a log system that gives you no time to read. Alternatives:

- turn on and off a fixed on screen messages, say... in the bottom/left of the screen (would work for capture and player;
- show the log in a plugin window;

**Comment by mkassner** [comment]
I see your point but I also try not to crowd the screen with log messages. With 2260ccc74d522cd1a1f05cac61bd1ba118cd4e8c I have tweaked the duration. For more I think either a new plugin or simple open the log file. I contains the same info permanently.

What do you think?

**Comment by willpatera** [comment]
@mkassner - Just tested. New duration is much better than before. There is enough time to read the longer messages now. 

I also agree that if one wants to step through log messages, they should open the log file. I think there are other plugins that would be more beneficial to spend development time on at current :smile:

**Comment by cpicanco** [comment]
Agreed, much better now! The txt log is all that one needs to further investigation, indeed. I think This one should be closed.
