### ISSUE TITLE
lunching issue with "Could not connect to device!"

### ISSUE THREAD

**Issue by Myzhencai** [pupil-labs/pupil#2130]
Hi ,I Just want to hava a test with this project with a simple camera ,well this is the result :(I used the latested pupil capture software)
![企业微信截图_16179451988073](https://user-images.githubusercontent.com/21084423/114354936-76cb3180-9ba1-11eb-939c-0400ac4c95d4.png)
![企业微信截图_16179452944716](https://user-images.githubusercontent.com/21084423/114354948-79c62200-9ba1-11eb-8d04-6da74d9eb0ca.png)
![image](https://user-images.githubusercontent.com/21084423/114355101-a7ab6680-9ba1-11eb-8bc3-a4c353fed465.png)

**Comment by papr** [comment]
Hi, could you let me know which of the framed cameras you want to use in Capture? Also, could you let me know the translation of the `USB ...` category name of the first marked camera?

You need to install the libusbK drivers for your custom camera as indicated [here](https://github.com/pupil-labs/pyuvc/blob/master/WINDOWS_USER.md) and then elect it in Capture by:
1. Open Video Source menu on the right
2. Enable manual camera selection
3. Select your camera from the "Activate Device" selector. If your camera is not listed, the drivers were not installed correctly.

**Comment by Myzhencai** [comment]
@papr ，thanks for help ,the issue is solved with your guide. Really appreciate for your time :-). Have a nice day .
