### ISSUE TITLE
Eye camera appears not plugged in

### ISSUE THREAD

**Issue by fwalker89** [pupil-labs/pupil#215]
I just plugged in my new Pupil Pro: high resolution world camera, 120hz eye camera.

When starting Pupil Capture, the Eye window appears with gray squares, as if the camera was not plugged it. World camera works fine.
![eye_screenshot](https://cloud.githubusercontent.com/assets/15033364/10367875/13493c12-6dd3-11e5-8a70-a45ad590293d.png)

Any suggestions?

**Comment by cpicanco** [comment]
- Hi, the camera appears in the device dropbox?
- I can see you are running on mac, did you try to list the attached devices? -> http://www.tekkie.ro/mobile-development/osx-list-usb-devices-lsusb-equivalent/

**Comment by mkassner** [comment]
Hi please make sure to use the latest version of the software.

**Comment by fwalker89** [comment]
Works with latest version of the software! thanks

**Comment by willpatera** [comment]
This can be closed now I believe :smile:
