### ISSUE TITLE
Network API - ndsi ValueError: numpy.ndarray size changed, Mac, python 3.7, Anaconda3

### ISSUE THREAD

**Issue by bhouDTU** [pupil-labs/pupil#2153]
Hi, 

I am trying to remote control Pupil Invisible Companion App recording and send event timestamps, for example, when user presses a key on the computer keyboard, recording should toggle, and pressing the space key would send a timestamp that mark the keypress event.

I first tried to install NDSI.  I did ''pip install ndsi''. I try to test it by "python import ndsi". And I got the following error message.
I have python 3.7, Anaconda3, MacBook Pro m1.

(PINetwork1) baoho@jamess-mbp ~ % python
Python 3.7.10 (default, Feb 26 2021, 10:16:00) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ndsi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.7/site-packages/ndsi/__init__.py", line 24, in <module>
    from ndsi.formatter import DataFormat
  File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.7/site-packages/ndsi/formatter.py", line 10, in <module>
    from ndsi.frame import JPEGFrame, H264Frame, FrameFactory
  File "ndsi/frame.pyx", line 1, in init ndsi.frame
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

I would appreciate your help.

Thanks,
James

**Comment by papr** [comment]
Hi @bhouDTU, please update your numpy version and try again.

**Comment by bhouDTU** [comment]
Thanks @papr, I now have python 3.9.5 and numpy 1.20.2, ndsi was imported successfully. Much appreciated!
