### ISSUE TITLE
Ubuntu16.04， error

### ISSUE THREAD

**Issue by Y-pandaman** [pupil-labs/pupil#2155]
I installed it on Ubuntu 16.04 and tried it both locally (python version 3.7) and on anaconda (python version 3.6.13), but both report errors. The main problem is that the av,pyglui,uvc,pye3d libraries don't install.

`Building wheel for uvc (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/zhangzjn/anaconda3/bin/python /home/zhangzjn/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpxuhajh5a
       cwd: /tmp/pip-install-76hmqeeb/uvc_808d833f3d974a8bb4d89ed9d4c9fef7
  Complete output (83 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'uvc' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -B /home/zhangzjn/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-build-env-p3qsw4v5/overlay/lib/python3.7/site-packages/numpy/core/include -I/home/zhangzjn/anaconda3/include/python3.7m -c uvc.c -o build/temp.linux-x86_64-3.7/uvc.o
  In file included from /tmp/pip-build-env-p3qsw4v5/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:0,
                   from /tmp/pip-build-env-p3qsw4v5/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /tmp/pip-build-env-p3qsw4v5/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from uvc.c:645:
  /tmp/pip-build-env-p3qsw4v5/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^
  uvc.c: In function ‘__pyx_pf_3uvc_7Capture_8get_frame’:
  uvc.c:16836:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_7 = ((__pyx_v_uvc_frame->width == __pyx_v_j_width) != 0);
                                            ^
  uvc.c:16842:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_7 = ((__pyx_v_uvc_frame->height == __pyx_v_j_height) != 0);
                                             ^
  uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_controls’:
  uvc.c:17018:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     __pyx_v_input_terminal = uvc_get_input_terminals(__pyx_v_self->devh);
                            ^
  uvc.c:17027:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     __pyx_v_output_terminal = uvc_get_output_terminals(__pyx_v_self->devh);
                             ^
  uvc.c:17036:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                             ^
  uvc.c:17045:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                            ^
  uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_formats’:
  uvc.c:17620:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
                         ^
  uvc.c: At top level:
  uvc.c:20023:13: warning: ‘__pyx_f_3uvc_on_status_update’ defined but not used [-Wunused-function]
   static void __pyx_f_3uvc_on_status_update(CYTHON_UNUSED enum uvc_status_class __pyx_v_status_class, CYTHON_UNUSED int __pyx_v_event, CYTHON_UNUSED int __pyx_v_selector, CYTHON_UNUSED enum uvc_status_attribute __pyx_v_status_attribute, CYTHON_UNUSED void *__pyx_v_data, CYTHON_UNUSED size_t __pyx_v_data_len, CYTHON_UNUSED void *__pyx_v_user_ptr) {
               ^
  creating build/lib.linux-x86_64-3.7
  gcc -pthread -shared -B /home/zhangzjn/anaconda3/compiler_compat -L/home/zhangzjn/anaconda3/lib -Wl,-rpath=/home/zhangzjn/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/uvc.o -lrt -luvc -lturbojpeg -o build/lib.linux-x86_64-3.7/uvc.cpython-37m-x86_64-linux-gnu.so
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-transupp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdatadst-tj.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdatasrc-tj.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcapimin.o): relocation R_X86_64_32S against symbol `jpeg_natural_order' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jccolor.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcmainct.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcmarker.o): relocation R_X86_64_32 against symbol `jpeg_natural_order' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcmaster.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcparam.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcphuff.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcprepct.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcsample.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jctrans.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdapimin.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdinput.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdmarker.o): relocation R_X86_64_32S against symbol `jpeg_natural_order' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdmaster.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdmerge.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdphuff.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdpostct.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdsample.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jerror.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jquant1.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jquant2.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jmemmgr.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcarith.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdarith.o): relocation R_X86_64_32S against symbol `jpeg_aritab' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jccoefct.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jcdctmgr.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jchuff.o): relocation R_X86_64_32 against symbol `jpeg_natural_order' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdcoefct.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdcolor.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jddctmgr.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdhuff.o): relocation R_X86_64_32S against symbol `jpeg_natural_order' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-jdmainct.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
  /home/zhangzjn/anaconda3/compiler_compat/ld: final link failed: nonrepresentable section on output
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for uvc
  Building wheel for pyglui (PEP 517) ... done
  Created wheel for pyglui: filename=pyglui-1.29-cp37-cp37m-linux_x86_64.whl size=3352184 sha256=c6b4400c20fb8a6b49dbfe9756d9086a2337334ddfa66ecebcd95cc35ecb2b4c
  Stored in directory: /tmp/pip-ephem-wheel-cache-whvb6625/wheels/8f/27/b0/5741c6c4a1eb9229042c677c348bb8002b1bce6bfb71eabb14
  Building wheel for pye3d (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/zhangzjn/anaconda3/bin/python /home/zhangzjn/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp3xz2mlhc
       cwd: /tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d
  Complete output (93 lines):
  Not searching for unused variables given on the command line.
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- The C compiler identification is GNU 5.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 5.4.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/_cmake_test_compile/build
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is GNU 5.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/zhangzjn/anaconda3/bin/python (found version "3.7.1")
  -- Found PythonLibs: /home/zhangzjn/anaconda3/lib/libpython3.7m.so (found version "3.7.1")
  -- Found Cython: /home/zhangzjn/anaconda3/bin/cython
  -- Found NumPy: /usr/include (found version "1.21.0")
  CMake Error at CMakeLists.txt:21 (find_package):
    Could not find a configuration file for package "Eigen3" that is compatible
    with requested version "3.3".
  
    The following configuration files were considered but not accepted:
  
      /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown
  
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
    File "/tmp/pip-build-env-czl37nvd/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
      languages=cmake_languages
    File "/tmp/pip-build-env-czl37nvd/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 240, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/_skbuild/linux-x86_64-3.7/cmake-build
    Command:
      cmake /tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/pye3d/cpp -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/_skbuild/linux-x86_64-3.7/cmake-install/pye3d/cpp -DPYTHON_EXECUTABLE:FILEPATH=/home/zhangzjn/anaconda3/bin/python -DPYTHON_VERSION_STRING:STRING=3.7.1 -DPYTHON_INCLUDE_DIR:PATH=/home/zhangzjn/anaconda3/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/home/zhangzjn/anaconda3/lib/libpython3.7m.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-czl37nvd/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
  
  Traceback (most recent call last):
  
  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/pye3d/cpp -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/_skbuild/linux-x86_64-3.7/cmake-install/pye3d/cpp -DPYTHON_EXECUTABLE:FILEPATH=/home/zhangzjn/anaconda3/bin/python -DPYTHON_VERSION_STRING:STRING=3.7.1 -DPYTHON_INCLUDE_DIR:PATH=/home/zhangzjn/anaconda3/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/home/zhangzjn/anaconda3/lib/libpython3.7m.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-czl37nvd/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/pye3d/cpp
    Working directory:
      /tmp/pip-install-76hmqeeb/pye3d_2c599fc143754c41905271551e98359d/_skbuild/linux-x86_64-3.7/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for pye3d
Successfully built av pyglui
Failed to build uvc pye3d
ERROR: Could not build wheels for uvc, pye3d which use PEP 517 and cannot be installed directly

`

**Comment by papr** [comment]
Hi,

You need to install the dependencies if you want to run from source. See https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-ubuntu17.md

Are you aware that we also offer a bundled application that does not require you to install the dependencies manually? Check out https://github.com/pupil-labs/pupil/releases/latest#user-content-downloads

Nearly all development work can be done using our Network API or as a custom plugin. See https://docs.pupil-labs.com/developer/core/overview/#overview

**Comment by Y-pandaman** [comment]
> 你好，
> 
> 如果要从源代码运行，则需要安装依赖项。见https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-ubuntu17.md
> 
> 您是否知道我们还提供了不需要您手动安装依赖项的捆绑应用程序？查看https://github.com/pupil-labs/pupil/releases/latest#user-content-downloads
> 
> 几乎所有的开发工作都可以使用我们的网络 API 或作为自定义插件来完成。请参阅https://docs.pupil-labs.com/developer/core/overview/#overview

I run "pip install -r requirements.txt",it shows errors.

**Comment by papr** [comment]
I understand, but in order for this to work, you need install further dependencies, as it is outlined in the documentation linked above.

**Comment by Y-pandaman** [comment]
> 我理解，但为了使其正常工作，您需要安装更多依赖项，如上面链接的文档中所述。

I have installed all the dependencies locally.

**Comment by papr** [comment]
> /home/zhangzjn/anaconda3/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a

This file must not be present. Please be aware of the `--enable-static=no` during the libjpeg-turbo configuration.

Regarding pye3d, please see https://github.com/pupil-labs/pye3d-detector/#build-and-install-from-source Alternatively, you can wait a few days. We will soon update the pupil code to support pye3d >= 0.0.8, which has pre-built wheels for Linux.

**Comment by Y-pandaman** [comment]
Installing pye3d directly will also report an error.
ERROR: Failed building wheel for pye3d
Failed to build pye3d
ERROR: Could not build wheels for pye3d which use PEP 517 and cannot be installed directly

**Comment by papr** [comment]
Regarding pye3d, the error seems to be with your eigen installation. Please follow the pye3d-specific instructions to build eigen
> Could not find a configuration file for package "Eigen3" that is compatible
with requested version "3.3".
The following configuration files were considered but not accepted:
  /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown

**Comment by Y-pandaman** [comment]
I tried to install it on Ubuntu 18.04 and only one error was reported, pyglui does not satisfies the requirements.

**Comment by papr** [comment]
> pyglui does not satisfies the requirements.

This information is insufficient for me to help you. Is there a specific reason why you try to run from source instead of using the bundled application? https://github.com/pupil-labs/pupil/releases/latest#user-content-downloads

**Comment by Y-pandaman** [comment]
I want to connect an eye-tracking device to my Ubuntu system to capture information, and also to capture information from other sensors, and to synchronise the time between them via NTP.

**Comment by papr** [comment]
This can be done by running an user plugin within the bundled application. There is no need for running from source. https://docs.pupil-labs.com/developer/core/plugin-api/#plugin-api

**Comment by Y-pandaman** [comment]
Can this device send a topic like ROS?

**Comment by papr** [comment]
Check out this third party script. It uses the network api to relay the Capture data to ROS https://github.com/qian256/pupil_ros_plugin/blob/master/scripts/pupil_zmq_ros_pub.py

I do not know if it is up-to-date, though.

**Comment by Y-pandaman** [comment]
thank you ,I will try it

**Comment by Y-pandaman** [comment]
> Check out this third party script. It uses the network api to relay the Capture data to ROS https://github.com/qian256/pupil_ros_plugin/blob/master/scripts/pupil_zmq_ros_pub.py
> 
> I do not know if it is up-to-date, though.

Thanks for the link, but this doesn't work, is there another way please?

**Comment by papr** [comment]
I don't know any other implementation.

**Comment by Y-pandaman** [comment]
Thank you anyway
