### ISSUE TITLE
could not connect to device! No image will be supplied.

### ISSUE THREAD

**Issue by Y-pandaman** [pupil-labs/pupil#2156]
hello，I have installed Pupil Capture, Pupil Service and Pupil Player， v3.3 on Ubuntu 16.04, and when I open Pupil Capture, it says that it could not connect to device.
![image](https://user-images.githubusercontent.com/45302972/123728330-a72f8b80-d8c5-11eb-8323-ab9ec9beeb87.png)

I use the command `ls /dev/video*`, it will show` /dev/video0  /dev/video1  /dev/video2  /dev/video3 /dev/video4`, then open the `cheese` software, you can select PI world v1, which is normal to display the image, but select PI left v1 or PI right v1 can not display the image.

**Comment by papr** [comment]
On Ubuntu, the user needs to be part of the plugdev group. To add your user to the group run `sudo usermod -a -G plugdev $USER` and reboot. In the video source menu, after enabling manual camera selection, the cameras should no longer be listed as "unknown" but as "Pupil Cam*".

**Comment by Y-pandaman** [comment]
thanks，it's work.This picture is a screenshot from someone else, which I copied over.
