### ISSUE TITLE
Manual Marker Calibration does not work for v0.6.9

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#218]
Pupil Capture crashes upon detection of a marker for manual calibration.

**Comment by MichaelBarz** [comment]
... there is no log message and no error. It just freezes.

**Comment by cpicanco** [comment]
Could it be related to the audio module? I remember that I was experiencing something like this, but Moritz already fixed it.

**Comment by MichaelBarz** [comment]
I made a new bundle for testing just a few hours ago. This fix should already be contained. :/
