### ISSUE TITLE
How to calibrate

### ISSUE THREAD

**Issue by Y-pandaman** [pupil-labs/pupil#2180]
hello，how do I calibrate my glasses, I am nearsighted, the screen will appear in the center, four corners of the five circles, I can move my head to see each circle? Or do I keep my head still and turn my eyes to see each circle?

**Comment by N-M-T** [comment]
@Y-pandaman when performing the 5-point screen-based calibration, you should keep your head still and follow the calibration marker with your eyes only. I would definitely recommend that you read the [Getting Started Guide](https://docs.pupil-labs.com/core/#getting-started) section of our documentation. It details how to set up, calibrate, and make recordings. When you are ready to learn more, check out the other sections, such as the [Pupil Capture docs](https://docs.pupil-labs.com/core/software/pupil-capture/#pupil-capture).
