### ISSUE TITLE
Detection stuck at 93%

### ISSUE THREAD

**Issue by sk-england** [pupil-labs/pupil#2181]
This has happen on two separate occasions. Pupil cannot complete detection for the eye1 video file and gets stuck at 93% of total Offline Pupil Detection. I cannot see anything majorly different between the video files both within this specific session or compared to different sessions where the offline pupil detection works.

**Comment by papr** [comment]
Hi, would it be possible for you to share one of these recordings with `data@pupil-labs.com`? It is likely that the video is somehow corrupted, causing the detection to stop early. I would like to confirm this by looking at the raw recording.

**Comment by sk-england** [comment]
Unfortunately I cannot as the file is too large to attach in an email (even when I compress it).

**Comment by papr** [comment]
Feel free to use file sharing services, e.g. Google Drive, https://wetransfer.com/ etc

**Comment by papr** [comment]
@sk-england Thank you for sharing the video. It looks like it is not corrupted. Could you share the `eye1_timestamps.npy` file from the same recording as well as the `Home directory -> pupil_player_settings -> player.log` file after reattempting the post-hoc pupil detection?

**Comment by papr** [comment]
@sk-england Thank you for sharing the files. From the files, I cannot see a reason for the incomplete detection. Could you try using a newer version of Pupil Player? You can find the latest version here https://github.com/pupil-labs/pupil/releases/latest I recommend backing up the recording before opening it in the new version. Player upgrades the recording format in-place to accommodate for new features.

**Comment by sk-england** [comment]
I have downloaded the newer version of Pupil Player but it seems to crash whenever I try to select post hoc pupil detection.

**Comment by papr** [comment]
OK, could you share the player.log file again after reproducing the crash?

**Comment by papr** [comment]
Please delete the `offline_data` folder in your recording and try again. It looks like there is an incompatibility when attempting to load the cached post-hoc pupil detection result.

**Comment by sk-england** [comment]
It seems to work now. Thank you for your help.
