### ISSUE TITLE
Camera cannot open in ubuntu 20.02

### ISSUE THREAD

**Issue by sibo001** [pupil-labs/pupil#2182]
The pupil capture cannot open the cameras: 
The errors show that EYE0:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS"not set, so enforcing
EYE0: could not connect to device! NO images will be supplied

**Comment by papr** [comment]
Please see https://github.com/pupil-labs/pupil/issues/2156#issuecomment-870380316
