### ISSUE TITLE
Synchronization of cameras

### ISSUE THREAD

**Issue by jampekka** [pupil-labs/pupil#2183]
I've encountered situations where the cameras (different eye cameras and the world camera) are not in sync when viewed in pupil_player. Does this reflect the synchronization of the datastreams as well? Is there a way to verify the synchronization and/or resynchronize the videos using timestamps? What is the expected synchronization accuracy?

I noticed the CPU usage for pupil detection surpassed 100% at times, can this cause dropped frames and/or desynchronization of the streams?

In [this example](https://drive.google.com/file/d/1-xg9aSHaqxAeyp1yi7xEI31Ds5TsAQzO/view?usp=sharing) the two eyes are off-sync by approximately 3 (world camera?) frames.

In [this example](https://drive.google.com/file/d/1fWTrx7ak4sKemvioctuZfkkwre5QQW0X/view?usp=sharing) the eye cameras are in sync, but are wildly off sync with the world camera.

**Comment by papr** [comment]
Hi @jampekka 

Apologies for the very delayed response.

On Linux, Pupil Capture uses the camera hardware clocks to timestamp the video frames. My best guess is that these are not in sync in your recording. Unfortunately, this desync cannot be detected via software, only by looking at events that should be happening at the same time, e.g. blinks, lights turn on/off.

You can use this [user plugin](https://gist.github.com/papr/ad8298ccd1c955dfafb21c3cbce130c8) to overlay the eye videos with a manual temporal offset.
