### ISSUE TITLE
SUBSCRIBE MULTIPLE TOPICS

### ISSUE THREAD

**Issue by Neptune-Y** [pupil-labs/pupil#2203]
Hello,

I have a question about pupil labs. Can i subscribe multiple topics using IPC Backbone at the same time? Because i need to get surface, gaze and blink data for each moment to visualise or analysis them. But i didn't find any example to use it like what i say, so can you give me some any suggestions please? 

Thank you.

**Comment by papr** [comment]
Hi, yes, simply call `.subscribe(topic)` multiple times on the same SUB socket.
