### ISSUE TITLE
Calibration method selection for v0.6.9

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#221]
There's an option for the dropdown "\<type 'NoneType'\>" that causes a crash upon selection.

**Comment by mkassner** [comment]
can you post the exception? I cant reproduce this on Mac/Linux. (Thus the labels?)

**Comment by MichaelBarz** [comment]
For a more recent test bundle (v0.6.121) this error is solved. There is no such option anymore. Closed...
