### ISSUE TITLE
cannot import name 'get_time_monotonic'

### ISSUE THREAD

**Issue by eshaanraj25** [pupil-labs/pupil#2216]
![image](https://user-images.githubusercontent.com/60806141/143575253-39af22bc-7ef8-483c-a418-42013c2a95ae.png)

**Comment by papr** [comment]
Hi, could you please try running `python -c "import uvc"` and let us know if this generates an import error, too?

**Comment by eshaanraj25** [comment]
nah it runs perfectly fine.
![image](https://user-images.githubusercontent.com/60806141/143586541-32e4d3e5-dc88-4766-afa9-37ae623f3d5c.png)

**Comment by papr** [comment]
Mmh, I am wondering if you have installed the correct version. Could you please run `python -c "import uvc; print(uvc.__version__)"` and let us know the output?

**Comment by eshaanraj25** [comment]
![image](https://user-images.githubusercontent.com/60806141/143587817-dccb7264-3d36-4549-b704-9779a43438ef.png)

**Comment by papr** [comment]
Ok, could you elaborate on the steps that you took to install pyuvc? Is it possible that you ran `pip install uvc`?

**Comment by eshaanraj25** [comment]
yup i did ran pip install uvc

**Comment by papr** [comment]
Unfortunately, this installs the incorrect version of pyuvc. Please download and install the wheel from our [release page](https://github.com/pupil-labs/pyuvc/releases). Before, please uninstall the incorrect version using `pip uninstall uvc`.
