### ISSUE TITLE
Why is my lens guving a circular view. Earlier it was rectangular like a normal camera 

### ISSUE THREAD

**Issue by eshaan2501** [pupil-labs/pupil#2218]
![image](https://user-images.githubusercontent.com/95204353/144170140-851741e3-597d-4e89-9177-50501bddea5c.png)

**Comment by papr** [comment]
Hi, this is typical for the 1920x1080 resolution of our scene camera. You can return to the previous field of view by changing to the 1280x720 resolution in the Video Source menu.
