### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by karitanunes** [pupil-labs/pupil#2223]
Could someone provide me with plugins that can give me:
. the fixation time on each object
. path (path) made over the image in order, and if the gaze returns to something already focused on before

Are heatmaps and paths in order done by the program itself, or is it necessary to do this in another place, like photoshop, for example?

I need final results like these that Ann Sussman does

![WhatsApp Image 2022-02-13 at 13 28 05](https://user-images.githubusercontent.com/99567475/153768860-c6f9cbcf-b220-4009-ac0e-6640c182966b.jpeg)
![WhatsApp Image 2022-02-13 at 13 28 28](https://user-images.githubusercontent.com/99567475/153768868-7fdddbe8-902d-4f99-ab50-d46e0157f3b4.jpeg)
![WhatsApp Image 2022-02-13 at 13 29 05](https://user-images.githubusercontent.com/99567475/153768871-07d9858b-9bdb-49a0-ba82-49a23b7f9919.jpeg)

**Comment by karitanunes** [comment]
And, please, how i install this plugins in my software (pupil eyes)?

**Comment by N-M-T** [comment]
To determine the relationship between the headset wearer's gaze and images in the scene, you can add fiducial markers to the images and use our [Surface Tracker](https://docs.pupil-labs.com/core/software/pupil-capture/#surface-tracking) plugin. Once enabled, this plugin automatically detects markers and you can define surfaces and obtain gaze positions relative to these surfaces. You can also [generate heatmaps](https://docs.pupil-labs.com/core/software/pupil-player/#analysis-plugins).

Read the linked docs for instructions.

Once you have created individual areas of interest _via_ the surface tracker, you can manually calculate metrics such as fixation time on objects using the exported surface data.

For further visualisations such as scan paths, have a look at our [tutorials repository](https://github.com/pupil-labs/pupil-tutorials), and specifically [at this tutorial](https://github.com/pupil-labs/pupil-tutorials/blob/master/03_visualize_scan_path_on_surface.ipynb)

Our official partner, [iMotions](https://imotions.com/), also offers turnkey solutions to generate visualisations and outcome metrics such as those shown/described above.

**Comment by papr** [comment]
Seems like the issue was resolved. @karitanunes Please let us know if this is not the case and we can reopen the issue.
