### ISSUE TITLE
List of compatible cameras

### ISSUE THREAD

**Issue by secco88** [pupil-labs/pupil#2224]
Hello everyone, I would create a new device and I need a list of compatible cameras. Who can help me?

Thanks

**Comment by papr** [comment]
Hi, unfortunately, it is very hard to maintain a comprehensive list of compatible cameras. Instead, we have documented the exact requirements [here](https://gist.github.com/papr/b258e0e944604375752eae502b4ad3d5#third-party-camera-requirements-for-pupil-capture).
