### ISSUE TITLE
How can I enable my laptop's integrated webcam for eye tracking?

### ISSUE THREAD

**Issue by gak97** [pupil-labs/pupil#2228]

**Comment by papr** [comment]
@gak97 Hi :)

> Video-based eye-tracking systems can be classified into remote (stationary) and wearable (head-mounted) eye trackers.

See also https://pupil-labs.com/blog/news/what-is-eye-tracking/

Pupil Core software is designed for wearable/head-mounted eye trackers. It does not work for remote eye trackers. Your laptop's integrated webcam would be considered such a remote eye tracker and is therefore not supported by our software.
