### ISSUE TITLE
Tooltips for Buttonbar

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#223]
The buttons on the left side, that contain one letter only are not self-explaining. It would be helpful to add a tooltip that appears on mouse over and at least shows the function in one word.

E.g. "C" could have a tooltip that states "start calibration" or "calibrate".

**Comment by mkassner** [comment]
I see the problem. But we wont implements tooltips as they don't work for touch.

We could add a question mark button that extends the menu globally to add extra info. 

Will and I will prototype this.

**Comment by MichaelBarz** [comment]
Maybe the button bar could be extendible such that the user can open a larger bar with additional info. For that you could use the same "pull out" image than for the menu bar on the right.

**Comment by mkassner** [comment]
Thats a nice idea but how would you communicate that the bar can be pulled out?

**Comment by MichaelBarz** [comment]
The sidebar menu can be hidden. Then an icon is shown that shows that the sidebar can be shown again. Maybe you can overload the meaning of this icon, i.e. add the meaning of a trigger for the button menu...
![unbenannt](https://cloud.githubusercontent.com/assets/6330614/10642248/0bb975b2-781d-11e5-9c2b-0a89cfc7e035.PNG)

**Comment by cpicanco** [comment]
A legend in the main window would be enough for me.

**Comment by willpatera** [comment]
Hi All -- some thoughts on this topic:

I would argue that the circular "hot key" buttons remain as simple as possible - just a push button with no extra tooltips or slide-outs. 

But, I also realize that the circular buttons could be confusing for a first time user. Better documentation is required both in the wiki and in the main settings window. An alternate idea would be to have a long press on the button open and scroll to the point in the settings menu (however this might not be so elegant/intuitive either).

**Comment by MichaelBarz** [comment]
Hi. There's another possible strategy.

Usually shortcuts are made for expert users with a high skill level, such that they can use the software faster than a novice or intermediate user. Since we have to cover several skill levels, the Pupil UI should support all of them.
You might know from other software that there is something called "tutorial-tooltips" that appear when starting for the first time. This enables a novice user to learn the expert features faster.

This might be an option keeping the UI as simple as it is just now.

**Comment by willpatera** [comment]
Good input -- but I think that tutorial tooltips are not sustainable given the rate new versions are released and could be an annoyance for existing users when updating or when deleting pupil capture/player settings. 

I would really prefer to devote energy to keeping documentation on the wiki up to date and maybe even making a series of short screen capture videos for each major milestone release, or when major UI changes/features are introduced. 

I vote to close this issue for now.

**Comment by MichaelBarz** [comment]
Ok. Maybe adding a "help" button in Capture and Player could be a solution then?
