### ISSUE TITLE
How to use code for pupil location

### ISSUE THREAD

**Issue by ProfessorJMLiu** [pupil-labs/pupil#2233]
After I downloaded the ”pupil_detectors（pip install）“, I did a pupil location on an eye image in Python and found that it didn't work.

**Comment by papr** [comment]
Hi @ProfessorJMLiu 

I am sorry to hear that this did not work out of the box for you.

Could you please specify what you mean by "it didn't work"? Did the software throw an error or was the resulting result inaccurate? Could you please also provide the image that you used?

Best,
Pablo

**Comment by papr** [comment]
Closing due to being stale.
