### ISSUE TITLE
Normalized coordinations

### ISSUE THREAD

**Issue by maaike14** [pupil-labs/pupil#2235]
Hi, for my project I want to add the head positions (pitch) and the gaze positions (norm_pos_y), in order to do so my variables need to be the same. But right now my head position is defined angular and my gaze position is a normalized coordinate. Does anyone know how I transform my normalized coordinations to angels? I can't find it on the pupil labs site anywhere. Thanks!

**Comment by papr** [comment]
Hi @maaike14
Great timing! We got a tutorial on that yesterday! https://github.com/pupil-labs/pupil-tutorials/blob/master/11_undistortion_and_unprojection.ipynb

To convert from norm values to pixel values use:
```py
pixel_x = norm_pos_x * width
pixel_y = (1.0 - norm_pos_x) * height
```

**Comment by maaike14** [comment]
Thanks for your reaction, unfortunately I still don't really get it. If I want to convert my gaze position (norm_pos_y) to pixel values I can use your formula. But how do I transform the outcome to the angular position? I am not familiar with python, using Matlab for my project. Is there someone who knows how to do this in Matlab?

**Comment by papr** [comment]
Matlab has corresponding [functions to handle camera intrinsics/unprojection/undistortion](https://de.mathworks.com/help/vision/camera-calibration.html). Alternatively, Matlab can [use OpenCV directly](https://de.mathworks.com/discovery/matlab-opencv.html), too.

While the functions might be called slightly different, I believe that it should be possible to use the Python tutorial as a template to develop a corresponding Matlab version. Unfortunately, this is not something we can provide ourselves in the near future.

To reach out to members of our community, please join our Discord server: https://pupil-labs.com/chat
