### ISSUE TITLE
External devices capabilites 

### ISSUE THREAD

**Issue by MenosGrandes** [pupil-labs/pupil#2243]
Hi,
I was working over extending PupilLab possibility to use external devices such as Luxometers which will be internally part of the PupilLab Core itself.

Because my project have ended, and I have results that I wanted I was wondering if any of my work can be used in this project.

Here is a code:
https://gitlab.com/MenosGrandes/pupillabupgrades

I was successfully use it to combine external luxometer with the PPLabCore itself.

Luxometer was just a AdafruitTSL2591 board implemented on Arduino.
Communication between PupilLab and Arduino was done using Serial communication (https://gitlab.com/MenosGrandes/pupillabluxometer_board and using https://github.com/nanopb/nanopb as ProtocolBuffer)

In general I have created two additional processes that will handle internal and external communications from and too PPLab.

**Comment by papr** [comment]
Hi,

Unfortunately, we won't be able to integrate these changes into the main repository. Pupil Core software is a cross-platform application and your changes seem to have been developed specifically for Ubuntu.

Nonetheless, I think your work should be linked in our [community project index](https://github.com/pupil-labs/pupil-community). I have created a corresponding entry for you: https://github.com/pupil-labs/pupil-community/commit/522a1b7e8266e26350191df04ea44c4c081588fd
