### ISSUE TITLE
how to get surface_norm_pos

### ISSUE THREAD

**Issue by ChiwoongLEE** [pupil-labs/pupil#2246]
hello

I am working on a plugin that gets the norm_pos value for gaze_on_surfaces that can be obtained through surface_tracker in real time without exporting the recorded image.
------------------------------------------------
{
    "topic": "surfaces.surface_name",
    "name": "surface_name",
    "surf_to_img_trans": (
        (-394.2704714040225, 62.996680859974035, 833.0782341017057),
        (24.939461954010476, 264.1698344383364, 171.09768247735033),
        (-0.0031580300961504023, 0.07378146751738948, 1.0),
    ),
    "img_to_surf_trans": (
        (-0.002552357406770253, 1.5534025217146223e-05, 2.1236555655143734),
        (0.00025853538051076233, 0.003973842600569134, -0.8952954577358644),
        (-2.71355412859636e-05, -0.00029314688183396006, 1.0727627809231568),
    ),
    "gaze_on_surfaces": (
        {
            "topic": "gaze.3d.1._on_surface",
            "norm_pos": (-0.6709809899330139, 0.41052111983299255),
            "confidence": 0.5594810076623645,
            "on_surf": False,
            "base_data": ("gaze.3d.1.", 714040.132285),
            "timestamp": 714040.132285,
        },
        ...,
    ),
    # list of fixations associated with
    "fixations_on_surfaces": (
        {
            "topic": "fixations_on_surface",
            "norm_pos": (-0.9006409049034119, 0.7738968133926392),
            "confidence": 0.8663407531808505,
            "on_surf": False,
            "base_data": ("fixations", 714039.771958),
            "timestamp": 714039.771958,
            "id": 27,
            "duration": 306.62299995310605,  # in milliseconds
            "dispersion": 1.4730711610581475,  # in degrees
        },
        ...,
    ),
    # timestamp of the world video frame in which the surface was detected
    "timestamp": 714040.103912,
}
--------------------------------------------

With surface_tracker turned off, the general gaze_point_3d and norm_pos values could be obtained through the following code, but I am curious how to get the values for the surface.
The code below is part of the plugin code I made.

    def recent_events(self, events): 

        gaze_point_3d = [0.0, 0.0, 0.0]
        norm_pos = [0.0, 0.0] 
        max_confidence = 0.0
        max_confidence_index = 0
        try:
            if self.gaze_flag:
                for i in range(len(events["gaze"])):
                    if float(events["gaze"][i].get("confidence")) > max_confidence:
                        max_confidence_index = i
                
                gaze_point_3d = list(events["gaze"][i].get("gaze_point_3d"))              
                norm_pos = list(events["gaze"][i].get("norm_pos"))
                           
                self.pub_socket.send("ROS_gaze:gaze_point_3d:".encode() + ":".join(str(e) for e in gaze_point_3d).encode())
                self.pub_socket.send("ROS_gaze:norm_pos:".encode() + ":".join(str(e) for e in norm_pos).encode())
--------------------------

Is it impossible to simply do "events[surfaces]" ?

**Comment by papr** [comment]
Hi! Surface data is available via `events["surfaces"]`. Note that your plugin requires an `order` value higher than 0.5 to get access to this data. To read more about that, see https://docs.pupil-labs.com/developer/core/plugin-api/#plugin-class-attributes

**Comment by ChiwoongLEE** [comment]
thanks. 
I changed "events['gaze']" to " events['surface'] " in the code I asked in the first question, but there is no data.
-------
def recent_events(self, events):    
    norm_pos = [0.0, 0.0]    
    try:
        if self.gaze_flag:
            for i in range(len(events["surfaces"])):
                if float(events["surfaces"][i].get("confidence")) > max_confidence:
                    max_confidence_index = i
                                   
            a = events["surfaces"][i].get("gaze_on_surfaces")
            norm_pos=list(a.get("norm_pos"))
                                   
            self.pub_socket.send("ROS_gaze:norm_pos:".encode() + ":".join(str(e) for e in norm_pos).encode())
-------------

Are there any modules I need to import?.. 
I don't know how to get the norm_pos value with events['surfaces'].

**Comment by papr** [comment]
`events` will always contain Python objects, i.e. you are able to print its content should you now know what's inside. :)

See [this example](https://github.com/pupil-labs/pupil-helpers/blob/master/python/filter_gaze_on_surface.py#L32-L39) to access the surface gaze norm pos.

**Comment by ChiwoongLEE** [comment]
What is the publisher in the filter_gaze_on_surface.py you showed as an example?

I don't know what the problem is with the code I showed above...

**Comment by ChiwoongLEE** [comment]
I was able to get norm_pos and gaze_point_3d of gaze datamn by simply writing events['gaze'] . I found that events['pupil'] and events['gaze'] were defined in world.py.
Is there a simple way to get events['surfaces'] like this?

**Comment by ChiwoongLEE** [comment]
Oh, I solved it myself. Thank you for your care
