### ISSUE TITLE
blink detection duration

### ISSUE THREAD

**Issue by ChiwoongLEE** [pupil-labs/pupil#2255]
Hi.

I extracted the blink type in real time using the blink detection

I want to get duration when my eyes are closed continuously.

Do you have any ideas?

**Comment by papr** [comment]
The realtime blink detector collects pupil data and tries to estimate the blink state for every scene video frame. The state can either be: None, eye closing (blink "onset"), eye opening (blink "offset"). You will get consecutive onset and offset events, e.g. onset, onset, onset, offset, offset. You can calculate the duration based on the difference between the timestamps of the first onset and the last offset.

**Comment by ChiwoongLEE** [comment]
To calculate duration in blink_detection.py

I am correcting the "def recent_events" part of 'class Blink_Detection(Plugin)'.

As you said, I'm extracting the blinking type and checking if it's blinking.

I don't want to calculate a specific event, but when I close my eyes, that is, I want to create an infinite offset state, so I want to find a time that consists only of offset without onset.
