### ISSUE TITLE
3d to 2d gaze

### ISSUE THREAD

**Issue by ChiwoongLEE** [pupil-labs/pupil#2256]
While studying the pupil coordinate system,
One of the data items that we can get from the pupil core is the normal_pos and the 3d gaze vector, and I was curious about the relationship between the two.

Is there a reference example for a theory that can be converted to 2d via a 3d gaze vector?

**Comment by papr** [comment]
Please see https://docs.pupil-labs.com/core/terminology/#coordinate-system

@ChiwoongLEE Please refrain from using Github issues to ask this kind of general question in the future. Please use our [Discord channel](https://pupil-labs.com/chat/) instead to ask questions. I would like to use Github issues for reporting actual errors/problems with the Core software.

**Comment by ChiwoongLEE** [comment]
oh, sorry .. i delete it
