### ISSUE TITLE
Logitech C615 failing with "the selected camera is already in use or blocked"

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#2257]
Hi @papr , I am receiving this red error message saying that "the selected camera is already in use or blocked" with my Logitech C615 as world camera. I am returning to the code and I am a little bit lost. A lot has changed. Can you shed some light on this, please?

**Comment by papr** [comment]
Hey, welcome back! Is it listed as unknown in the manual device selection menu? If so, the drivers are not installed correctly. See https://github.com/pupil-labs/pyuvc/blob/master/WINDOWS_USER.md#how-to-prepare-your-system-for-uvc-on-windows-8-and-later

**Comment by cpicanco** [comment]
Thanks @papr , 

Yes, the camera is listed as unknown. So, it seems that the resolution in #1011 is still up-to-date. Sorry if this is a duplicate.

Here are some instructions for me on Windows:

I am installing libusbk 3.0.7.0 cheking every checkbox:
![2257](https://user-images.githubusercontent.com/6511849/186974288-afedb873-cea9-43a0-acf4-b40ecc8f5ccd.png)

After installing, an InfWizard is poping up. Then, I am selecting the following option:
![2257-InfWizard](https://user-images.githubusercontent.com/6511849/186978148-3c726f5c-2b9d-4ee7-966a-af3f435a5856.png)

After selecting the target driver, the InfWizard will ask for a target camera. So, I am chosing my camera.

Then I am opening Zadig, an checking some options, as mentioned in the docs:
![2257-Zadig-Options](https://user-images.githubusercontent.com/6511849/186978691-c148901c-8581-4057-99a0-ab085c740562.png)

Now, I am clicking in "Reinstall Driver", making sure that the `ccgn` driver is substituted to `libusbk`:

![2257-Zadig-Reinstall](https://user-images.githubusercontent.com/6511849/186978819-e424ef60-3a9b-4c36-8bf9-3767246132cf.png)

Install Python 3x (https://www.python.org/downloads/) and remember to check "add python to PATH";

Now,  I am trying to update uvc, as mentioned in the docs: 
```
pip install --upgrade .\uvc-0.14-cp36-cp36m-win_amd64.whl
```

I am getting the following error message:
```
ERROR: uvc-0.14-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

Regardless of the previous error, now I have a working system, up and running.
![2257-done](https://user-images.githubusercontent.com/6511849/186979579-865b478c-cfe2-4b41-9524-0f986316e081.png)

**Comment by papr** [comment]
The uvc python module part is not necessary for the driver installation / usage in Capture. That said, I am working on wheels for every active python version.
