### ISSUE TITLE
Sporadically Erroneous Labels for Player v0.6.9 

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#226]
After starting the player once there were many typos, e.g. "annual Gaze Correction" instead of "Manual Gaze Correction" in the "Open plugin" dropdown. After restarting the Player there were no errors...

**Comment by mkassner** [comment]
This is a windows pyfontstash problem. Not related to plugins.

**Comment by MichaelBarz** [comment]
Ok, shall we close this issue then? It only appeared once to me...

**Comment by mkassner** [comment]
no way to reproduce this?

**Comment by MichaelBarz** [comment]
The reasons for this issue can be manifold. Do you think this is a pyfontstash or rather a fontstash problem with Windows?

**Comment by mkassner** [comment]
I think fontstash. We simply make a binding and this issue looks gl related.

**Comment by mkassner** [comment]
outdated.
