### ISSUE TITLE
High idle cpu load for Player

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#227]
Seems that the player's main loop causes a 100% cpu load when paused. Adding a sleep(250ms), when playback is paused should solve that.

**Comment by mkassner** [comment]
We will solve this differently.

**Comment by mkassner** [comment]
Can you measure the refresh rate on Pupil Player in pause mode?

**Comment by cpicanco** [comment]
I could replicate this. Paused increased the CPU load from ~55 to ~75.

**Comment by cpicanco** [comment]
On linux.

**Comment by MichaelBarz** [comment]
Hi, I just added a logger output for fps. The values are measured and averaged over 5s.

```
Player [INFO] __main__ : pause | 41.9510241189 fps
Player [INFO] __main__ : pause | 57.3590890254 fps
Player [INFO] __main__ : playback | 23.4609984528 fps
Player [INFO] __main__ : playback | 18.0448142532 fps
```

**Comment by mkassner** [comment]
since I don't think adding a sleep is the way to go here. We need a greater rethinking of the refresh logic to do this right. I ll close this issue for now.
