### ISSUE TITLE
Player does not close on ESC

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#228]
Capture closes on pressing ESC, the Player does not. We should be consistent about that...

**Comment by mkassner** [comment]
This is by design.

**Comment by cpicanco** [comment]
What was the design motifs that sustain the difference @mkassner ?

**Comment by mkassner** [comment]
Well, I actually think the app should never close on `ESC` rather use the normal `CMD+Q`, `ALT-F4`. What about removing the `ESC` quitting from Pupil Capture as well?

**Comment by MichaelBarz** [comment]
Removing `ESC` would indeed increase consistency. It might also protect from closing the app unintentionally. I'm for it.

**Comment by mkassner** [comment]
If @willpatera agrees I would go ahead and make the change.

**Comment by willpatera** [comment]
Let's remove `ESC` to quit the application -- we should really be using standard OS patterns to quit the program. 

While I almost always use `ESC` to exit Pupil Capture, it really is a "vestigial tail" that remains from the earliest versions.

**Comment by cpicanco** [comment]
I would like to note that it is related to #84.

**Comment by MichaelBarz** [comment]
Nice ;)
Didn't know that one, when I raised the issue...

Finally we are more consistent now and do not collide with your issue. Seems to be a good solution :)
