### ISSUE TITLE
Vis Watermark crashes when loading large images

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#229]
RGBA watermark causes a crash on load.

Edit: crash is caused by image being larger than video stream...

**Comment by mkassner** [comment]
Please post the exception that's thrown.

**Comment by MichaelBarz** [comment]
Seems that large images break the plugin. We might scale the images before copying it to the frame buffer.

```
Player [INFO] plugin : Loaded: Vis_Watermark
Traceback (most recent call last):
  File "<string>", line 526, in <module>
  File "<string>", line 393, in session
  File "C:\Users\mb\Documents\pupil\deploy_player\build\bundle\out00-PYZ.pyz\vis_watermark", line 78, in update
ValueError: operands could not be broadcast together with shapes (509,544,3) (509,1824,3)
```
(seems to be a general problem, not just Windows -> removed `Windows` and `Bundle` labels)

**Comment by MichaelBarz** [comment]
Confirmed: rescaling the png-file solves the issue. It#s all about the file size.
