### ISSUE TITLE
No Video feed on Windows 11 on HP EliteBook 845

### ISSUE THREAD

**Issue by oddwatcher** [pupil-labs/pupil#2295]
Using a usb uvc camera. Which is *Driver Free* I can immediately find this webcam in settings and view it from the windows camera app. the computer also comes with a cam. However i tried to run the program in admin and install the python dependencies while i reinstall the driver of the usb cam to change it to libusbK which from that moment i cannot use it from the windows camera app . the pupil can find this camera but still report the camera is "blocked or disconnected"
![image](https://user-images.githubusercontent.com/55705026/207238865-0bbd79d5-5947-48af-8dd1-ff01900c1c0b.png)
![image](https://user-images.githubusercontent.com/55705026/207239086-ce714942-77b3-4f4e-bcf6-05804fea9635.png)
![image](https://user-images.githubusercontent.com/55705026/207239219-d57ce872-8f1e-4ffb-af06-ee6d215e68e0.png)
![image](https://user-images.githubusercontent.com/55705026/207239248-b2363455-2c72-40d9-b359-267dda3e31a2.png)
![image](https://user-images.githubusercontent.com/55705026/207239357-3624dec5-0d53-4fd4-b568-1b5aa51f2cd9.png)
![image](https://user-images.githubusercontent.com/55705026/207239470-52e21ea8-163d-44b3-bed7-5aabe7f1f61c.png)
![image](https://user-images.githubusercontent.com/55705026/207239500-5296449b-6805-40be-9460-8adf4f1692f9.png)
![image](https://user-images.githubusercontent.com/55705026/207239541-41335226-be4f-426a-8ffe-0a8b92ad4b69.png)

**Comment by oddwatcher** [comment]
![WIN_20221213_14_14_33_Pro](https://user-images.githubusercontent.com/55705026/207240760-9dba270a-30b5-4634-8445-22ba40b23954.jpg)
This is what the camera looks, i get it from aliexpress and the factory removed the IR fliter for me, this module is usb2.0 and with automatic focus

**Comment by oddwatcher** [comment]
i have checked up the former issues regarding the uvc version problem, this camera after plug in and returned it's driver date as 2006 and nowhere to find anything about the newer uvc version.

**Comment by oddwatcher** [comment]
obs can get the video feed. Any suggestions on how to use a video feed to the program like an api?

**Comment by papr** [comment]
To install libusbk drivers manually, follow [these instructions](https://github.com/pupil-labs/pyuvc/blob/ga-build/WINDOWS_USER.md). Note step 5:
> It is crucial you select the composite parent and **not one of the interfaces**

In the [screenshot above](https://user-images.githubusercontent.com/55705026/207239470-52e21ea8-163d-44b3-bed7-5aabe7f1f61c.png) you have selected the interface.

Once it is installed correctly, and assuming the camera provides a mjpeg stream, you should be able to use it within Pupil Capture.
