### ISSUE TITLE
Live video output

### ISSUE THREAD

**Issue by lizha0yan** [pupil-labs/pupil#2296]
Hi,
I'm trying to get live stream output from Pupil Core, just the video frames in three cameras. Is that possible?

**Comment by lizha0yan** [comment]
Thanks for replying.
Actually, I only need the original eyes and the world's video output so that I can try on my own model.

**Comment by lizha0yan** [comment]
> Yes, you can use `zmq` to stream them.
> 
> Do you plan to open it in Pupil Capture on another device? Here you have an [implementation ](https://github.com/Lifestohack/pupil-video-backend) Kindly note this implementation does not stream the full intrinsics and is less accurate than connecting the device directly.

Is there any way to use Pupil Core as a webcam?  I want to do something like:
```
import cv2
vid = cv2.VideoCapture(0)
while(True):
    ret, frame = vid.read()
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```
Instead of using "0" for the laptop webcam, I want to use pupil core.

**Comment by papr** [comment]
Hi, Pupil Capture installs the libusbk driver to gain full access the cameras' capabilities. To use OpenCV to read frames from the camera, you will need to deinstall this driver ([steps 1-5 from here](https://docs.pupil-labs.com/core/software/pupil-capture/#windows)).

Alternatively, you can use [pyuvc](https://github.com/pupil-labs/pyuvc/tree/ga-build) to get frames from the camera. 

Note: With the approaches above, you would not be able to access the camera via Pupil Capture in parallel to your own script. To do that, you can either receive the camera images via [Pupil Capture's realtime API](https://github.com/pupil-labs/pupil-helpers/blob/master/python/recv_world_video_frames_with_visualization.py) or build a custom [Pupil Detector plugin](https://docs.pupil-labs.com/developer/core/plugin-api/#pupil-detection-plugins) that runs within Pupil Capture.
