### ISSUE TITLE
Plugin whitelist for working Windows Plugins

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#230]
We should provide a whitelist for Windows bundles to allow approved Plugins only. This should enhance UX significantly.

**Comment by mkassner** [comment]
I vote against this. Why add a list? Rather just make all plugins work on
windows as they to on Mac/Linux .

**Comment by cpicanco** [comment]
I think the list could be included as a `todo:` list, as a commentary in the main.py. People (if any) should know beforehand about this things.

**Comment by MichaelBarz** [comment]
I close this for now as we rather want to solve the issues...
