### ISSUE TITLE
During the calibration large amount of pupil data was dismissed due to the low confidence

### ISSUE THREAD

**Issue by fattyalan** [pupil-labs/pupil#2325]
When I do the calibration, it raises a warning that " **An unexpectedly large amount of pupil data (>20%) was dismissed due the low confidence**". (btw. I find the amount of dismissed pupil data is often between 20% to 35%). This results to some unprecise pupil to gaze mapping. Especially in the areas with large angle in the image. 
In my calibration results, the Angular accuracy is 2.088 degrees, and the angular precision is 0.097 degrees. The process of calibration is strictly followed the official user guide. I wonder if this have something to do with the device or I can solve it by revising source code. 
I would be **really** appreciated if you can help me.

**Comment by mikelgg93** [comment]
Hi  @fattyalan 👋🏽 ! Could you share an example recording with [data@pupil-labs.com](mailto:data@pupil-labs.com)? This way we wil be able to provide you with more feedback on how to improve your recordings. 
Please on that email include which system you are using, such as Core, VR/AR, etc. and a reference to this issue. 
Best,
Miguel
