### ISSUE TITLE
Neon support for Player

### ISSUE THREAD

**Issue by dcnieho** [pupil-labs/pupil#2329]
Hi @papr.

Is support for Neon recordings planned for pupil player? Right now when running from source i get:
player - launchables.player: InvalidRecordingException: Neon Companion app recordings are not supported in Pupil Player. You can view them in Pupil Cloud instead

Cheers and thanks!

**Comment by dcnieho** [comment]
I'll also work to implement support for Cloud exports in my project https://github.com/dcnieho/glassesValidator, that would be the sensible workflow for most users. But it would be good to know if the Pupil Player route is available only for Invisible and earlier or will also be supported for the Neon. This would be important since the cloud may not be usable without having some data processing agreements in place in some cases, as far as i know, so it may not be available to some users, and player would then be the only route. (I'm looking into this for us.)

**Comment by mikelgg93** [comment]
Hi @dcnieho 

Support for Neon recordings in Pupil Player is not planned. We do plan to release a new standalone tool for offline work. 
For now, we recommend going through our GDPR-compliant Cloud or using the RAW Android recordings.
