### ISSUE TITLE
camera donot work!

### ISSUE THREAD

**Issue by lizilei2020** [pupil-labs/pupil#2348]
Inserting the camera can locate the device, but cannot display the image：
eye0 - [INFO] video_capture.uvc_backend: Found device. USB Camera.
eye0 - [WARNING] camera_models: No camera intrinsics available for camera USB Camera at resolution (640, 480)!
eye0 - [WARNING] camera_models: Loading dummy intrinsics, which might decrease accuracy!
eye0 - [WARNING] camera_models: Consider selecting a different resolution, or running the Camera Instrinsics Estimation!
eye0 - [WARNING] uvc: Could not set Value. 'Absolute Exposure Time'.
eye0 - [WARNING] uvc: Could not set Value. 'White Balance temperature'.

please help!!Thanks

**Comment by rennis250** [comment]
Hi @lizilei2020 ,
This issues section is for software issues with the Pupil ecosystem.
It sounds instead like you have a hardware issue.
Could you please send an email to info@pupil-labs.com with the full error message and the following details:

- Operating System
- Pupil Capture version
- Do the eye cameras work? Does the world camera work?
    - That is, which image is not displayed?

Thanks,
Rob
