### ISSUE TITLE
Do not override last accuracy test.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#239]
Sorry, but I am not 100% sure about the accuracy test workflow. Could you confirm if the tests are being overriden? If so, I think the files should be incremental instead.

**Comment by cpicanco** [comment]
The test data is being saved at `capture_settings/accuracy_test_pt_cloud.npy`, that is overridden every time a new test is made.

What about:
- rename `accuracy_test_pt_cloud.npy` to `last_accuracy_test_pt_cloud.npy`
- create a copy, and save incrementally at `recordings/tests/pupil-accuracy/yyyy-mm-dd-begin-end.npy`, where begin and end is `hh-mm-ss`;

**Comment by papr** [comment]
Fixed with 2761a87
