### ISSUE TITLE
windows videoinput wrapper

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#24]
* write a wrapper for https://github.com/ofTheo/videoInput 
* it should implement as much of stuff done in the Linux version as possible.

**Comment by mkassner** [comment]
Moving to Windows more recent Media Framework

**Comment by hookdump** [comment]
Hey! Any news about this? Any way I can help with it?

**Comment by MichaelBarz** [comment]
Hi, we'll be working on that topic this week. We faced several problems concerning compiler incompatabilities (VS2008, cython vs. VS2012 compiler, video lib). Now, we try some alternatives to get the video backend running. As soon as we had success we'd appreciate, if you could test our solution.

**Comment by hookdump** [comment]
Absolutely!

**Comment by mkassner** [comment]
@MichaelBarz when you have time: Test the lib on a different machine and make sure that the .lib/.dll s are in the repo. Developers should have two ways of installing the lib:
1) just do `(python) setup.py install` to have the module and its precompiled libs installed.
2) additionally follow a guide on how to build the .lib/.dll yourself (using VS)

@hookdump once this is done, if you can, please check and see if you can run test.py on your machine.

In our v0.4 branch @MichaelBarz has already begun interfacing this new lib so we hope to have a full featured windows video capture backend very soon. 

Once done we will move to creating windows bundles. Very much along the lines of what we do for Mac/Linux already now. It will also use `PyInstaller`.  Our toolchain and settings are found in `deploy_player` and `deploy_capture`.

**Comment by MichaelBarz** [comment]
Finally there's a first version running on windows with the new backend. @hookdump, could you please test, if this solution works for you? I collected some instructions to get pupil running with the windows backend:

**Install pyvideoinput**
- clone git repo "MediaFoundation" branch
- open command line and navigate to local git folder
- run "setup.py install"
- should finish with sth. like "Writing <path>.egg-info

**Install pyglui**
- clone git repo "master" branch (with submodules!)
- open command line and navigate to local git folder
- run "setup.py install"
- should finish with sth. like "Writing <path>.egg-info

**Install psutil**
- open command line
- run "pip install psutil"
- (make sure folder containing "pip.exe" is in your path environment variable)

**Setting up Pupil Capture**
- clone git repo "v0.4_restruct" branch

**Add glfw library**
- download 64-bit binaries from http://www.glfw.org/download.html
- extract it
- search folder containing "glfw3.dll", "glfw3.lib" and "glfw3dll.lib"
- rename containing folder to "external"
- copy "external" folder to local pupil folder such that "pupil_src/shared_modules/external/"

**Run Pupil Capture main.py**

**Comment by hookdump** [comment]
Great!!! I'm on it.

**Comment by cpicanco** [comment]
Preparing to windows invasion in 5..4..3..2..1
:P

**Comment by mkassner** [comment]
I m closing this. Any issues related to pyvideoinput should be raised there.
