### ISSUE TITLE
Search recursively for runtime plugins (allow subfoldering)

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#242]
Hi, right now one is required to put all runtime plugins inside: 

`player-settings/plugins`

or 

`capture-settings/plugins`

Subfoldering inside `<...>/plugins/` is not allowed, which makes harder the git integration, as far as I know.

Would good to have something like:

`<...>/plugins/git-folder-of-third-party-1/`
`<...>/plugins/git-folder-of-third-party-2/`
`<...>/plugins/git-folder-of-third-party-3/`

**Comment by mkassner** [comment]
This already works. Simply add a __init__.py file in your sub dir 

in my case the file contains:
```python
from example_plugin import *
```

We simply treat each subdir as a modules tthis way and it just works :-)
