### ISSUE TITLE
pupil player plugin list is getting very big

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#246]
Bottom plugins are being hidden outside of the user clickable area. Also, it is not possible to roll down the dropdown list as usual.

![screenshot from 2015-11-16 16 50 12](https://cloud.githubusercontent.com/assets/6511849/11192891/474dbf2e-8c82-11e5-86c9-3de2a77a31e5.png)

**Comment by mkassner** [comment]
I agree. would splitting the lists make sense?

M

**Comment by cpicanco** [comment]
Putting plugins in a growing menu as buttons makes sense?

**Comment by willpatera** [comment]
Restructuring the plugin list is still needed. 

Splitting plugin lists into categories/topics might be a good first step. Plugins should also be sorted in some way (alphabetical?). Here is a proposal for splitting the list based on existing plugins:

  1. Visualization
    1. Vis Circle
    1. Vis Polyline
    1. Vis Lightpoints
    1. Vis Crosshair
    1. Vis Watermark
    1. Eye Video Overlay
    1. Scan Path
  2. Analysis  
    2. Fixation Detector
    2. Manual Gaze Correction
    2. Video Export Launcher
    2. Offline Marker Detector
    2. Raw Data Exporter
    2. Batch Exporter
    2. Annotation Player
3. Other
    3. Show Calibration
    3. Pupil Server

Once plugins are in separate categories/topics, then we can remove the prefix `Vis` for visualization plugins such that `Vis Circle` would just become `Circle`.

**Comment by cpicanco** [comment]
Show Calibration should be included in the visualization category, shouldn't it?

**Comment by mkassner** [comment]
implemented.
