### ISSUE TITLE
Run time plugins and persistence

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#249]
I have some plugins that will not load in a persistent style due the following warning/error. 
```
Player [WARNING] plugin : Plugin 'Offline_Screen_Detector' failed to load from settings file. Because of Error:'Global_Container' object has no attribute 'plugins'
```
It is a little bit confusing warning, since the error message is not related with the plugin it self, but with the container holding it. Any advice on this would be appreciated.

**Comment by mkassner** [comment]
Hi,

could you post the source of the failing plugin?

**Comment by cpicanco** [comment]
Please, note the inheritance:

```
class Offline_Screen_Detector(Offline_Marker_Detector,Screen_Detector)
```

https://github.com/cpicanco/player_plugins/blob/master/screen_offline_detector.py

**Comment by cpicanco** [comment]
I am afraid I forgot to override something.

**Comment by mkassner** [comment]
Hi,

the problem comes from:
```python
for p in g_pool.plugins:
            if p.class_name == 'Marker_Detector':
                p.alive = False
                break
```

in case the plugin is loaded from settings this call will fail because g_pool does not yet have a plugins list. As it is being created as the fn is called.

I just made a fix. Can you test it?

**Comment by cpicanco** [comment]
Sure, will see this in the next few hours.

**Comment by cpicanco** [comment]
It is working. :+1:
