### ISSUE TITLE
Turn ON two eye cameras

### ISSUE THREAD

**Issue by ravitchad** [pupil-labs/pupil#251]
Hello,
Can you help me with how I can use both the eye cameras? I couldn't find any options in the menu to turn on both the eye cameras and at the moment only left eye camera is working.

**Comment by mkassner** [comment]
Hi,

sorry thats not properly documented. We are improving this in the upcoming release.

As of right now simply do this:

1) open terminal
2) copy/paste: `/Applications/Pupil\ Capture.app/Contents/MacOS/pupil_capture binocular`

This will start the app in binocular mode.

M

**Comment by mkassner** [comment]
I will close this when runtime eye process launching is implemented.

**Comment by ravitchad** [comment]
Could you also tell me what I should do for Ubuntu?

**Comment by mkassner** [comment]
Hi on ubuntu its easy.

Right click on the launcher icon and select binocular.

Best,

Moritz

**Comment by ravitchad** [comment]
Hello Moritz,

I cannot see that option.
![img_0082](https://cloud.githubusercontent.com/assets/16101344/11528475/4a53c922-98e7-11e5-98bd-a574365ca71b.JPG)

**Comment by mkassner** [comment]
Hi,

please drag the app into the sidebar. The menu with have the option then.

Best,

Moritz

**Comment by ravitchad** [comment]
Hey,
Thanks it worked. The right eye is inverted as shown in the pic. Is this the way it is supposed to be?

**Comment by mkassner** [comment]
Hi,

There is a button in the ui to flip the image.

M

**Comment by ravitchad** [comment]
ok :)

**Comment by mkassner** [comment]
BTW: You need to recalibrate after switching to binocular. Flipping the eye image is only for cosmetic reasons.

**Comment by JihadOsakaUniversity** [comment]
Hello 
On Windows, whenever I run the binocular mode, the world window won't run the scene camera.
While in the monocular mode it is working. 

Any suggestions?

Thanks
Jihad
