### ISSUE TITLE
3D Eye Model: ignore circular pupils for performance check

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#258]
getModelSupport should:

1) report goodness and confidence of goodness 
2) use 2d confidence
3) check if sphere dot normal > INTO_CAM_THRESHOLD

**Comment by patrickFuerst** [comment]
Maybe it's better to not use 2d confidence, rather then just let the confidence depend on the angle between normal and sphere to camera direction. As of now we never reach this point if the 2d confidence is below 0.8. Which should be good enough to calculate the right performance.
