### ISSUE TITLE
Win bundles for v0.4

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#26]
* make a pyinstaller bundle for pupil player
* make a pyinstaller bundle for pupil capture

**Comment by hookdump** [comment]
@mkassner Sorry, just saw this! Do you know what are the issues and limits of the OpenCV backend on Windows? Would it be a possible solution to research solutions/workarounds for those issues?

**Comment by mkassner** [comment]
@MichaelBarz any updates on this?

**Comment by MichaelBarz** [comment]
I already installed pyinstaller and read some lines of the documentation. I'll further review how it is used for linux/mac and transfer the settings to windows.

**Comment by mkassner** [comment]
Test release for capture can be found here: https://github.com/pupil-labs/pupil/releases/tag/v0.4.3
