### ISSUE TITLE
3D Eye Model: model lifecycle

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#260]
create new model if avg performance slope is negative by (threshold) or performance below THRESHOLD.

replace model if performance is better and maturity is above threshold

if active model performance is back to above good_threshold:
   kill other models

**Comment by patrickFuerst** [comment]
rename performance slope , performance gradient
we kill all models not only if the performance is back above threshold but also if it's gradient is positive. 

There are some value tweaking left TODO.

**Comment by patrickFuerst** [comment]
Also in order to work properly with all framerates we need to know the current framerate.
How about passing the framerate to the detector everytime we call `self.detector3DPtr.updateAndDetect` in `detector_3d.pyx`?

**Comment by mkassner** [comment]
the set framerate is not always the actual frame rate. Since we are using a runnig avg. Could we simply get the average timestamp distance?

**Comment by patrickFuerst** [comment]
Oh ok. Yeah that's probably even better, since it's not always guaranteed we reach the target framerate.

**Comment by patrickFuerst** [comment]
I did some testing with this now. Looks pretty good with my eye.

**Comment by mkassner** [comment]
''We kill all models not only if the performance is back above threshold but also if it's gradient is positive.''

I m not sure about this. I tested it and it keeps a bad model dominant for too long.  Can we try without this?
