### ISSUE TITLE
install instructions for new dependencies - 3d eye model, calibration

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#272]
It seems you already have a working branch with new dependencies. For example, ceres (from google?) and eigen (http://eigen.tuxfamily.org/index.php?title=Main_Page). Anything else?

**Comment by mkassner** [comment]
Yes Ceres and Eigen. I ll add instructions for linux and mac tomorrow.

**Comment by mkassner** [comment]
I added instructions for Mac. On linux I m still working on getting the cpp source to compile there seem to be some issue taken by gcc with our source code.

**Comment by cpicanco** [comment]
Since you already created an issue for the compile errors on linux, i think this issue can be closed
