### ISSUE TITLE
Pupil Labs UI (pyglui) not working?

### ISSUE THREAD

**Issue by csuh0115** [pupil-labs/pupil#279]
Even after installing glew and cloning `https://github.com/pupil-labs/pyglui --recursive`, python setup.py install does not work for MacOS. 
I am having two problems:

1. 
>missing cimport in module 'pyglui.cygl': pyglui/ui.pyx
>missing cimport in module 'pyglui.cygl': pyglui/graph.pyx`

2. It can't find the gl.h file?

>pyglui/ui.c:264:10: fatal error: 'gl.h' file not found
>#include "gl.h"
>          ^
>1 error generated.
>error: command 'clang' failed with exit status 1`

**Comment by willpatera** [comment]
Hi @csuh0115 I will migrate this issue to [`pyglui` repo](https://github.com/pupil-labs/pyglui) as the issue is directly related to setting up and running `pyglui`, and will respond there.
