### ISSUE TITLE
missing binocular var in capture

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#282]
The `g_pool.binocular` var is missing leading to errors in calibration. Introduced at the recent refactoring [9995ffc07fd71f327464f28082634ea30e97c8c3] .

```
if 'binocular' in sys.argv:
    binocular = True
    logger.debug("Starting in binocular mode")
else:
    binocular = False
    logger.debug("Starting in single eye cam mode")

...

 g_pool.binocular = binocular

```

**Comment by mkassner** [comment]
This will be fixed with the merge of cpp_2d_3d_detector into master.
