### ISSUE TITLE
stresstest pyv4l2 backend

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#29]
make sure it works with various software

**Comment by mkassner** [comment]
Its seems fine to me. Especially since we added the fix timestamps script to the recorder. I would say push to release.

**Comment by mkassner** [comment]
we should add a auto recovery for stopped captures.

**Comment by fneitzel** [comment]
what about auto-saving in general? Like every 5 Minutes, or if there is a certain amount of data?

**Comment by mkassner** [comment]
The backend can now recover even if the device goes into an error state. Tests show that this makes capture possible even with faulty cameras. I will close this issue for now.
