### ISSUE TITLE
Eye Advanced control duplicates

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#296]
Changing from 2d-3d on the world process creates duplicates of the advanced control in the eye window.
![screenshot from 2016-01-23 04 47 35](https://cloud.githubusercontent.com/assets/6511849/12529145/cfce5d88-c18c-11e5-83e8-9dc41a431338.png)

**Comment by mkassner** [comment]
You see two menues because the 3d detector uses the 2d detector. So this is no bug. Only a misleading ui. (Which we will revise.)

**Comment by cpicanco** [comment]
Actually, there were three menus.
