### ISSUE TITLE
question: how to load (run time) system plugin on initialization

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#298]
Hi everyone,

Just wondering if it is possible, how should I proceed? In my specific case, I am trying to do this with:
https://github.com/cpicanco/player_plugins/blob/master/trim_marks_patch.py

**Comment by mkassner** [comment]
Do you mean how to force loading a plugin automatically on startup even when the settings file is cleared?

In this case that s a good question. I ll add a feature for this.

M

**Comment by cpicanco** [comment]
Good!

**Comment by cpicanco** [comment]
Right now using this hack:

```
        super(Segmentation, self).__init__(g_pool)
        Trim_Marks_Extended_Exist = False
        for p in g_pool.plugins:
            if p.class_name == 'Trim_Marks_Extended':
                Trim_Marks_Extended_Exist = True
                break

        if not Trim_Marks_Extended_Exist:
            from trim_marks_patch import Trim_Marks_Extended
            g_pool.plugins.add(Trim_Marks_Extended)
            del Trim_Marks_Extended

```
- Segmentation plugin will open if it exists in the settings
- No repetition in the plugins list

**Comment by papr** [comment]
I think this issue can be closed.

1. There are user plugins which Capture lists as possible plugins.
2. The `start_plugin` notification can start a plugin from remote.

**Comment by cpicanco** [comment]
Hi @papr , the point here is another one. I was trying to load a system plugin during runtime automatically. Right now there is no way of creating a runtime plugin that will always load.

**Comment by papr** [comment]
Wait. I would like to get the terms straight:
- *system plugin*: is always loaded, cannot be turned off (e.g. recorder)
- *runtime plugin*: plugin that can be loaded and unloaded during runtime (e.g. the fixation detector)
- *default plugin*: runtime plugin that is loaded every time until you unload it explicitly (e.g. Pupil Remote)
- *user plugin*: runtime plugin that is located in a specific folder in the user settings.

The only way to create a *system plugin* is to modify `world.py` and to add the according plugin to the list of *system plugins*.

**Comment by cpicanco** [comment]
This is exactly right:

> system plugin: is always loaded, cannot be turned off (e.g. recorder)

However, they can be deleted during runtime. So, I would appreciate a way to extend or modify system plugins (like the Trim Marks) during runtime without the above mentioned hack:

        super(Segmentation, self).__init__(g_pool)
        Trim_Marks_Extended_Exist = False
        for p in g_pool.plugins:
            if p.class_name == 'Trim_Marks_Extended':
                Trim_Marks_Extended_Exist = True
                break

        if not Trim_Marks_Extended_Exist:
            from trim_marks_patch import Trim_Marks_Extended
            g_pool.plugins.add(Trim_Marks_Extended)
            del Trim_Marks_Extended

**Comment by cpicanco** [comment]
Keep in mind that right now this is not a priority at all for me @papr! Stuff is running.

**Comment by cpicanco** [comment]
Just for the recording, this is related to #217.
