### ISSUE TITLE
use pyav as media backend

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#30]

**Comment by mkassner** [comment]
At least the video exporter should use PyAV for v0.4. We need to merge with the PyAV branch.

**Comment by mkassner** [comment]
This is done and for now good enough. We can in the next round completely remove OpenCV.highgui with our own code.

**Comment by cpicanco** [comment]
Hey Moritz, I could not find the record button on the Capture v0.4, it is related to this issue?

**Comment by mkassner** [comment]
Hi Can you send a screenshot of your capture window? The record button
should be there. Pyav is only needed for player at this time.
