### ISSUE TITLE
How to configure the pupil development environment for windows?

### ISSUE THREAD

**Issue by greatproduct** [pupil-labs/pupil#303]
Hello,

I am trying to configure the pupil development environment for windows, but it seems pyuvc does not have support for Windows yet. Can you let me know how to configure the pupil development environment for windows? Thanks

If the latest version of pupil does not work for Windows, can you let me know which version of pupil code work in Windows? Thanks!

Do I need to install libturbojpeg for the windows to get pyuvc to get it work?

.pyuvc/setup.py at master · pupil-labs/pyuvc
    https://github.com/pupil-labs/pyuvc/blob/master/setup.py
...
elif platform.system() == 'Windows':
    raise NotImplementedError("please fix me.")

**Comment by cpicanco** [comment]
Hi developer, welcome to the Pupil Community. Though enhancements for the Windows OS would be extremely welcomed by the community, please note that the main development is being done in the Linux/Mac platforms. If the Windows OS is mandatory for you, please follow the instructions in the wiki (https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Windows) to setup your system and contribute.

**Comment by MichaelBarz** [comment]
Hi. I might add that pyuvc is currently not used for the Windows version as video backend. This lib is currently used: https://github.com/pupil-labs/pyvideoinput

**Comment by mkassner** [comment]
But it should also be noted that this lib will fail to grab more than one camera stream from a single usb controller in many cases... Thus the need for libuvc in windows.

**Comment by mkassner** [comment]
We are working on this right now. I will close this. Please wait for the immanent windows release.
