### ISSUE TITLE
3D Eye Model: visual feedback

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#306]
draw eye sphere either 2d or 3d in the eye window.

**Comment by patrickFuerst** [comment]
draw sphere in eye window https://github.com/pupil-labs/pupil/tree/sphere_in_eye_window

**Comment by mkassner** [comment]
@patrickFuerst  Can we add some smoothing the the sphere. The edge is really not pretty right now.

**Comment by patrickFuerst** [comment]
replace with smoothed circle in eye window
