### ISSUE TITLE
Export not working with sound enabled - Player Version: 0.7.1.1 (Recording Version 0.7.3)

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#307]
Hi!

If 'world.wav' is in the recording folder, the export will not start.

Best

![screen](https://cloud.githubusercontent.com/assets/10213803/12810553/331ffcc2-cb27-11e5-937c-8022011bca76.png)

**Comment by mkassner** [comment]
Thank you for catching that. Fixed.

**Comment by fneitzel** [comment]
Issue still exists in current download version.
