### ISSUE TITLE
Decide on the logging strategy for c++ 

### ISSUE THREAD

**Issue by patrickFuerst** [pupil-labs/pupil#309]
Would be good to have the same logging functions for c++ as in python. 
Probably best to just use a small Logging wrapper.

**Comment by mkassner** [comment]
Yes. I agree. Maybe a callback to python for that. The python fn would then call logging.logger.info/warn/error(args)

**Comment by patrickFuerst** [comment]
That's what I thought too. But not sure if there could be some potential issues with this. 
But let's have a look into this.

**Comment by mkassner** [comment]
its will not work for mutlithreaded stuff, or might require extra work. It will also me slower that simple print. From my understanding it will acquire the GIL which will happen automatically.

**Comment by mkassner** [comment]
@patrickFuerst  please close when merged.

**Comment by patrickFuerst** [comment]
close with bcda532e4dd24cbc137eca1bc10c1e09f7a05aca
