### ISSUE TITLE
Update wiki - Pupil Server message format 

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#312]
Documentation is needed to explain the meaning and format of gaze event attribute `base` added by gaze mapping plugins [gaze_mappers.py](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/gaze_mappers.py). The format (at least) should be documented in the [Pupil Server message format](https://github.com/pupil-labs/pupil/wiki/Pupil-Capture#message-format-for-pupil-server).

**Comment by cpicanco** [comment]
So, just to make it clear, there is a new `base` attribute? Right now the wiki have an example of a `base` attribute, indeed, in the Server Message example:
```
base:[{'diameter': 68.22367858886719, 'confidence': 0.98742361331807926, 'angle': 27.150636672973633, 'center': (277.85926818847656, 237.52635955810547), 'norm_pos': (0.43415510654449463, 0.5051534175872803), 'axes': (54.99845504760742, 68.22367858886719), 'major': 68.22367858886719, 'ellipse': ((59.85926818847656, 67.52635955810547), (54.99845504760742, 68.22367858886719), 27.150636672973633), 'roi_center': (59.85926818847656, 67.52635955810547), 'timestamp': 311752.189135336, 'id': 0, 'minor': 54.99845504760742}]
```

Side note: there is inconsistence the Filtering Messages description. The comment `# only 'norm_pos', and nothing more` does not apply anymore:
https://github.com/pupil-labs/pupil/wiki/Pupil-Capture#filtering-messages-broadcast-by-pupil-server

**Comment by willpatera** [comment]
I updated the `Filtering Messages` text - thanks for pointing this out.

**Comment by mkassner** [comment]
Done. Reworked pupil server format and updated wiki
