### ISSUE TITLE
Feedback: Pupil Player Bundle on Debian

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#318]
I had a problem with my mean computer where pupil is running from source. Right now running the Player Bundle on Debian. Specs of the machine: 2gb (1,71 available), Intel Celeron processor, Sis chipset.

**Comment by cpicanco** [comment]
Debian 8

**Comment by mkassner** [comment]
so this means it run on Debian 8? Thats good to know!

**Comment by cpicanco** [comment]
Yep!
