### ISSUE TITLE
Missing notifications for Manual_Marker_Calibration

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#324]
I would like to draw the markers with my own software and would like to get a plugin notification when the state of the Manual_Marker_Calibration changes. I am particularly interested in the following events:
- Steady marker found.
- Marker moved to quickly.
- Stopping to sample. Looking for steady marker again.

These events happen in l.185 to l.208 in Manual_Marker_Calibration.py
I would appreciate it if you could add the appropriate notifications to it.

**Comment by mkassner** [comment]
Yes. Will do!

**Comment by mkassner** [comment]
Done.
