### ISSUE TITLE
GitHub Pull resquests, Issue templates

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#331]
I think this should help the people that want to help. :)

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by willpatera** [comment]
@cpicanco - I am working on a branch https://github.com/pupil-labs/pupil/commit/58b7e9a34f5cd803f57f546a56e4432a43a474f9 where we can create guidelines for contributing. Just a WIP right now, but its a start :smile:

**Comment by cpicanco** [comment]
Encourage people to showcase their projects. I am not sure how to do this. I really like autolink functionality throughout issues, pull requests, commits and projects. Since contributor projects must be inside the plataform, an idea is to use a reserved, always open issue to this. Is there a "pin" functionality for issues???

**Comment by mkassner** [comment]
I ll close this. I m nore we can maintain all this extra structure.
