### ISSUE TITLE
Pupil Capture 0.7.3: Missing Function - Auto Update Display off

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#336]
Hi,

i tried to run the Pupil Software on Intel Core 2 Duo CPU P8600 @2.40Ghz x2.

To save CPU i searched for the function which turns off the camera display image,
since it needs too much CPU while recording.

Could you please implement it again or tell me how to enable the option?

Thanks

**Comment by mkassner** [comment]
Its still there. Just minimize the window.
