### ISSUE TITLE
[Mac] Eye Window doesn't open

### ISSUE THREAD

**Issue by JihadOsakaUniversity** [pupil-labs/pupil#339]
I am trying to run the Pupil Labs software on Mac, and for some reason only the world window opens while the eye window doesn't open at all.
I am working on iMac with OS X 10.11.3 version.

Any suggestions?
Thank you
Jihad

**Comment by willpatera** [comment]
Hi @JihadOsakaUniversity - I believe that you just need to launch the eye process. 

When you open Pupil Capture for the first time, you may need to open the general settings menu in the `World` window and launch the eye process(es). You can do this once, and your settings will be saved to `capture_settings` so that the next time you open Pupil Capture the selected eye processes will also start and the eye window(s) will open. 

See screenshots below:
![screen shot 2016-03-08 at 17 30 55](https://cloud.githubusercontent.com/assets/1407224/13599085/d86944ea-e553-11e5-9908-441bd5fb0704.png)
_No eye video process started_

![screen shot 2016-03-08 at 17 31 07](https://cloud.githubusercontent.com/assets/1407224/13599086/d86c23e0-e553-11e5-8c33-3fb7b4e14129.png)
__eye0 process started__

**Comment by JihadOsakaUniversity** [comment]
Hello Again
I have activated the eye 0 process, a message appears indicating that an eye process has been launched but no window opens.
When I try restarting it again, the pupil capture crashes even before opening.

**Comment by mkassner** [comment]
Hi,

please do what you wrote again and paste the world and eye log files in this issue.

M

**Comment by JihadOsakaUniversity** [comment]
Hi
Attached is the log files. 

Jihad
[Untitled.zip](https://github.com/pupil-labs/pupil/files/187487/Untitled.zip)

**Comment by mkassner** [comment]
these files dont show any error. can you contact me so we can debug this via video?

**Comment by JihadOsakaUniversity** [comment]
Hello Will
Is Sunday suitable for you?

Jihad

On Fri, Apr 8, 2016 at 9:32 PM, mkassner <notifications@github.com> wrote:

> these files dont show any error. can you contact me so we can debug this
> via video?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pupil-labs/pupil/issues/339#issuecomment-207413213>
>



-- 
*Jihad Fahmi Mahmoud*




*大阪大学情報科学研究科情報システム工学博士1年 竹村研究室配属Ph.D. Candidate, Prof Takemura
Laboratory,Information Systems Engineering Department,Graduate School of
Information Sciences and Technology,Osaka University*

**Comment by JihadOsakaUniversity** [comment]
Hello

The Pupil Labs still crashes whenever I try to run it on iMac even with the
latest version.

Attached is a copy of the problem details message.

Can you tell me what seems to be the problem?


Thank you
Jihad

On Wed, Apr 13, 2016 at 10:58 AM, Jihad Mahmoud <jihad.mahmoud85@gmail.com>
wrote:

> Hello Will
> Is Sunday suitable for you?
>
> Jihad
>
> On Fri, Apr 8, 2016 at 9:32 PM, mkassner <notifications@github.com> wrote:
>
>> these files dont show any error. can you contact me so we can debug this
>> via video?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pupil-labs/pupil/issues/339#issuecomment-207413213>
>>
>
>
>
> --
> *Jihad Fahmi Mahmoud*
>
>
>
>
> *大阪大学情報科学研究科情報システム工学博士1年 竹村研究室配属Ph.D. Candidate, Prof Takemura
> Laboratory,Information Systems Engineering Department,Graduate School of
> Information Sciences and Technology,Osaka University*
>



-- 
*Jihad Fahmi Mahmoud*




*大阪大学情報科学研究科情報システム工学博士2年 竹村研究室配属Ph.D. Candidate, Prof Takemura
Laboratory,Information Systems Engineering Department,Graduate School of
Information Sciences and Technology,Osaka University*

**Comment by mkassner** [comment]
Sorry no attachment....

**Comment by JihadOsakaUniversity** [comment]
Hello

May you check again?

The email has an attachment.

Thanks
Jihad

On Fri, May 13, 2016 at 7:28 PM, mkassner <notifications@github.com> wrote:

> Sorry no attachment....
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pupil-labs/pupil/issues/339#issuecomment-219007698>
>



-- 
*Jihad Fahmi Mahmoud*




*大阪大学情報科学研究科情報システム工学博士2年 竹村研究室配属Ph.D. Candidate, Prof Takemura
Laboratory,Information Systems Engineering Department,Graduate School of
Information Sciences and Technology,Osaka University*

**Comment by mkassner** [comment]
If you want to attach something please use the github website issue window instead of email. Attachments are stripped when using email.

**Comment by mkassner** [comment]
I ll close this due to inactivity.
