### ISSUE TITLE
[Binocular] high resolution in both eye cam crashes one of the eye window

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil#344]
When both eye windows are opened, changing the resolution for both eyes from 640x480 to 1280x720 
causes one of the eye window to close. Changing back to lower resolution works again.

Pupil Capture - `v0.7.4` bundle.

Tested with Intel NUC 
Processor : Intel® Core™ i5-6260U CPU @ 1.80GHz × 4 
Graphic : Intel® Skylake ULT GT3 
OS : Ubuntu 15.10 64-Bit
Memory: 7.7GB

**Comment by mkassner** [comment]
Im quite sure that we are asking for to much bandwidth. Better feedback from pyuvc would help in this case.
