### ISSUE TITLE
More structure in the releases docs and communication

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#346]
* first draft then release the notes and files
 * all info originates from the release page
 * we will tweet with link
 * we will send a link via pupil-discuss
 * files names of bundles need to be standardised
 * add convenience links to downloads section if release notes are too long (or always add `<a name='downloads'></a>` at the bottom of the release notes.

**Comment by willpatera** [comment]
The source of all release documentation will be Github. If any images needed, place them in the release notes. The blog pulls from the github release. 

This workflow is implemented. Therefore closing.
