### ISSUE TITLE
What about an update to the 'developer guide - plugins'?

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#35]
Hey guys,

What about an update to the "plugins" section of the developer guide, including basic information about how to make a "player" plugin? Please, sorry for that if it is not about time to do it for some reason.

Right now, it states that "To run your plugin all you need to do is import and add it to the plugins list in world.py". So, you could give some tips on how interact with some (standard) player plugins. I'm saying that because I was a little bit lost when trying to make my player plugin works with the exporter.py. After some time trying to understand the whole thing, and receiving "[Warning] Plugin X could not be loaded in exporter", I imported and added it to the player.py and exporter.py plugin lists and everything works just fine.

Best!

**Comment by cpicanco** [comment]
@willpatera 

I think I can help you on this, take a look:

https://github.com/pupil-labs/pupil/wiki/Plugin-Guide

**Comment by willpatera** [comment]
@cpicanco 

Excellent! I'll have a look at the commits tomorrow early and make edits.

**Comment by cpicanco** [comment]
It is on the run.
