### ISSUE TITLE
UX improvement: SeekBar not visible enough

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#351]
- add drop shadow 
- make the lines thicker.
- trimm marks should display the frame no during drag.

**Comment by cpicanco** [comment]
> trimm marks should display the frame no during drag.

Please, consider showing the frame number with "immediate feedback"; on-mouse-down/on-begin-dragging instead of on-mouse-up/on-end-dragging event. It would allow fine control over the frames through the seek bar ball.

**Comment by willpatera** [comment]
@cpicanco -- Yes, agreed. Better immediate feedback of frame numbers is needed. Should be a separate issue.

**Comment by papr** [comment]
Fixed with #513
