### ISSUE TITLE
Start and stop recording with ZeroMQ requests

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pupil#352]
There was the pupil_remote plugin to easily start and stop the recording in Pupil Capture, with ZeroMQ requests. So an external program could start and stop the recording programmatically, and easily.

With commit cb667e87da640d768b6a18493aacfd5280b20fc2 the plugin has been removed, with no explanations on what to use instead. But it seems that the pupil_sync plugin is supposed to replace the functionality of pupil_remote.

But in the code of pupil_sync I don't see where it starts and stops the recording. If it is possible with pupil_sync, it would be nice to document how. At least have an example in pupil-helpers. But pupil_sync looks more complicated to use than pupil_remote.

For the use-case in the lab where I works (for neuroscience research), there is a Matlab program that runs the [Psychtoolbox](http://psychtoolbox.org/). When the experiment starts, the Pupil recording should start at the same time. The Matlab program runs on another computer, and communicates with the Pupil with ZeroMQ.

**Comment by mkassner** [comment]
We replaced Pupil remote with Pupil Sync. 

I have added 4 convenience functions to Pupil Sync just now: https://github.com/pupil-labs/pupil-helpers/commit/fa6427cf612183e54a1e30a43b19d41b3a3155d9

With those it should work. Have a look at the bottom of the source file. It shows how to use the sync_node_class.

**Comment by swilmet-ucl** [comment]
Thanks, I'll have a look.

**Comment by swilmet-ucl** [comment]
Using Pupil Sync outside Python is quite complicated though. A ZeroMQ request was much more simpler and can be used in a lot of languages.

For just starting and stopping the recording or calibration of one Pupil Capture, Pupil Sync is over-engineered IMHO.

**Comment by mkassner** [comment]
Thanks for this feedback. You are right in this regard. I have update the old pupil remote plugin to work agains the current master branch. (I will push a release later this week).

if you drop the following file as `pupil_remote.py` into `capture_setting/plugins` you have the old plugin back. (I did change the control pattern a bit please look at the docstring):

```python
'''
(*)~----------------------------------------------------------------------------------
 Pupil - eye tracking platform
 Copyright (C) 2012-2015  Pupil Labs

 Distributed under the terms of the CC BY-NC-SA License.
 License details are in the file license.txt, distributed as part of this software.
----------------------------------------------------------------------------------~(*)
'''


from plugin import Plugin
from pyglui import ui
import zmq

import logging
logger = logging.getLogger(__name__)



class Pupil_Remote(Plugin):
    """pupil remote plugin
    send messages to control Pupil Capture functions:

    'R' start recording with auto generated session name
    'R rec_name' start recording and name new session name: rec_name
    'r' stop recording
    'C' start currently selected calibration
    'c' stop currently selected calibration
    """
    def __init__(self, g_pool,address="tcp://*:50020"):
        super(Pupil_Remote, self).__init__(g_pool)
        self.order = .01 #excecute first
        self.context = zmq.Context()
        self.socket = self.context.socket(zmq.REP)
        self.address = 'not set'
        self.set_server(address)


    def set_server(self,new_address):
        try:
            self.socket.unbind(self.address)
            logger.debug('Detached from %s'%self.address)
        except:
            pass
        try:
            self.socket.bind(new_address)
            self.address = new_address
            logger.debug('Bound to %s'%self.address)

        except zmq.ZMQError as e:
            logger.error("Could not set Socket: %s. Reason: %s"%(new_address,e))

    def init_gui(self):

        def close():
            self.alive = False

        help_str = 'Pupil Remote using REQ RREP schemme'
        self.menu = ui.Growing_Menu('Pupil Remote')
        self.menu.append(ui.Button('Close',close))
        self.menu.append(ui.Info_Text(help_str))
        self.menu.append(ui.Text_Input('address',self,setter=self.set_server,label='Address'))
        self.g_pool.sidebar.append(self.menu)

    def deinit_gui(self):
        if self.menu:
            self.g_pool.sidebar.remove(self.menu)
            self.menu = None


    def update(self,frame,events):
        try:
            msg = self.socket.recv(flags=zmq.NOBLOCK)
        except zmq.ZMQError :
            msg = None
        if msg:
            if msg[0] == 'R':
                logger.warning(msg[2:])
                self.notify_all({'subject':'should_start_recording','session_name':msg[2:],'source':'pupil_remote'})
                confirmation = 'started recording'
            elif msg[0] == 'r':
                self.notify_all({'subject':'should_stop_recording','source':'pupil_remote'})
                confirmation = 'stopped recording'
            elif msg == 'C':
                self.notify_all({'subject':'should_start_calibration','source':'pupil_remote'})
                confirmation = 'started calibration'
            elif msg == 'c':
                self.notify_all({'subject':'should_stop_calibration','source':'pupil_remote'})
                confirmation = 'stopped calibration'
            else:
                confirmation = 'Unknown command.'
            self.socket.send(confirmation)


    def get_init_dict(self):
        return {'address':self.address}


    def cleanup(self):
        """gets called when the plugin get terminated.
           This happens either volunatily or forced.
        """
        self.deinit_gui()
        self.context.destroy()

```

this is the script I used to test it:
```python
import zmq
from time import sleep
context =  zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect('tcp://192.168.1.100:50020')
socket.send('C')
print socket.recv()
sleep(5)
socket.send('c')
print socket.recv()
sleep(1)
```

**Comment by swilmet-ucl** [comment]
Thanks a lot, it works fine. Any chance this can be included upstream?

**Comment by mkassner** [comment]
Yes. I will reopen this issue and add it to the v0.8 milestone.

**Comment by swilmet-ucl** [comment]
Cool, I'm sure it'll be useful for other users as well.

**Comment by cpicanco** [comment]
Hi @mkassner , what do you recommend to send and to receive data? I have a program the receive timestamps and I want to update it to Start/Stop recordings too. I'm not involved to time critical experiments. So what would you recommend? Pupil Sync or adapt the Pupil server?

**Comment by mkassner** [comment]
@cpicanco I would definitely use Pupil sync for that!

**Comment by cpicanco** [comment]
If you are doing stuff in python, I would like to note that https://github.com/papr/Pupil-Research-Plugin-Suite/ is pretty advanced on this topic. Could it be quickly adapted to the Pychotoolbox workflow?

Unfortunately, I am not doing stuff in python (yet?). The program I want to update is written in Free Pascal. As expected, I am using ZeroMQ (3.2.5) to receive the timestamps. If I understood correctly the Pupil wiki and helpers, a program like mine must register itself as a Pupil Node to take advantage of the goodies. Hopefully, it will be an achievable task, quickly, without Pyre, by means of a suitable substitute in Free Pascal. Am I a dreamer? rsrsrs

**Comment by swilmet-ucl** [comment]
> Could it be quickly adapted to the Pychotoolbox workflow?

Do you mean the [Psychtoolbox](http://psychtoolbox.org/) or something else? For the Psychtoolbox (which runs in Matlab), I have written some basic ZeroMQ bindings for Matlab, that I'll publish [here](https://github.com/UCL-CATL) soon.

There is not a lot of documentation for [Pupil-Research-Plugin-Suite](https://github.com/papr/Pupil-Research-Plugin-Suite).

**Comment by papr** [comment]
Hey guys, thanks for mentioning my project ```Pupil Interface```. It is part of my Bachelor thesis. A lot of detailed documentation (also for the Pupil software itself) is in work. Deadline is end of May.

The difference to the current implementation is that ```Pupil Interface``` supports feedback. This means that you can define callbacks or wait e.g. for  the recording actually to start. It also implements subscription to the pupil server plugin.

**Comment by mkassner** [comment]
Should be resolved with #370

**Comment by willpatera** [comment]
Added pupil-helpers example here: https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/pupil_remote_controls.py

**Comment by swilmet-ucl** [comment]
Thanks!
