### ISSUE TITLE
Move confidence filter from Capture to Player

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#357]
Move the confidence filter from Pupil Capture to Pupil Player. 

Remove the slider from the general menu. Filtering by confidence should be the responsibility of the plugin or the consumer of the raw data.

**Comment by mkassner** [comment]
Is gone from Capture. Adding it in player is still todo.

**Comment by papr** [comment]
Move threshold to visualisation plugins. Threshold should not be applied to export.

**Comment by mkassner** [comment]
implemented with 7f4deb2b55e63b2d6887956dca04887483145257
