### ISSUE TITLE
Autofocus problem - Eye camera

### ISSUE THREAD

**Issue by csuh0115** [pupil-labs/pupil#358]
I have built a DIY glasses by following the instructions but I have encountered a problem with the Microsoft HD-6000 eye camera. Even when I try to focus the camera in the program, even the highest setting of 40 is not enough - the image is still very blurry. How can I fix this?

**Comment by cpicanco** [comment]
Hi, manually adjusting the camera lens is an option. The rounded plastic support might be glued. You should be careful while removing the glue.

**Comment by willpatera** [comment]
@csuh0115 - as @cpicanco said, I think manually focusing the camera first is necessary, then you can fine tune with the auto-focus via software. Please update or close if the issue is resolved.

**Comment by mkassner** [comment]
closed due to inactivity.
