### ISSUE TITLE
Ubuntu 14.04 start from source issues

### ISSUE THREAD

**Issue by Aeefire** [pupil-labs/pupil#359]
After doing the whole setup process as described in the wiki and explicitly also purging any previous ffmpeg versions before installing the required one, I am still not able to start e.g. the capture module from source.

> ImportError: /usr/local/lib/python2.7/dist-packages/av-0.2.5-py2.7-linux-x86_64.egg/av/frame.so: undefined symbol: av_frame_unref

is the error message. I've seen 2 google Groups posts about this issue but a) it said the wiki is supposed to be updated or b) the proposed solution is not working / having an effect.

Also, a friend of mine also gets reported that he has av-0.2.5 too, but experiences no issue in starting the capture moduel from source.

Any tips / solutions?

**Comment by cpicanco** [comment]
Hi, have you tried to manually follow the instructions contained in the link of the "curl" command? Worked for me...

https://gist.githubusercontent.com/mkassner/1caa1b45c19521c884d5/raw/b5ce332808b8e26406af0db78115761ea605441c/install_ffmpeg_ubuntu.sh

**Comment by Aeefire** [comment]
not as of now, but I downloaded the file separately and manually executed it too, once and it didn't help me out.  

for now using the docker and the command "xhost  +" to give it access rights to my xserver (which also isnt mentioned anywhere) did the job for me. I'll try to follow your proposed way too though, when I find some time.

**Comment by cpicanco** [comment]
For some reason (that I did not investigate any further) the 'curl' command did not worked on my terminal, resulting in a "bad installation" of the dependencies. If you are sure that the command did worked for you, then I would not recommend doing it manually.

Another problem I had was related to the installation of the 3d-model itself. I think the wiki contains only the dependencies. Unfortunately, I can't help you any further on this.

**Comment by fneitzel** [comment]
Hi there!

Slightly changed:

curl https://gist.githubusercontent.com/mkassner/1caa1b45c19521c884d5/raw/b5ce332808b8e26406af0db78115761ea605441c/install_ffmpeg_ubuntu.sh | **sh**

works for me.
