### ISSUE TITLE
Ubuntu - Setup - instructions to build from source

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#362]
I tried to build pupil capture from source, but i am missing a correct library.
So far i added:

```
pip install pyinstaller
pip install version_utils
```

I stuck in 'finalize_bundle' line 13:
```
from version import write_version_file, dpkg_deb_version
ImportError: cannot import name write_version_file
```

I tried:
`pip install version `
without success

I couldn't find dependency instructions in the wiki.

**Comment by mkassner** [comment]
bundeling is quick tricky and giving support not really feasible for us. We are going into 14 day realy cycles now and I will upload a bundle in a few hours. I hope that helps!
