### ISSUE TITLE
UX improvements: bring-to-front window on click.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#363]
Bring to front a window on click, changing the window stack order. It is called "focus" sometimes. Please, close it if not a priority for 8.0.

**Comment by willpatera** [comment]
@cpicanco I am not sure I understand your proposal. 

Where are you proposing that this "click" event happens (in the GUI)? And what window or windows would become focused with this proposal?

**Comment by cpicanco** [comment]
Hi @willpatera take a look at the image below. The user must drag and drop the desired (at the back) window or minimize all other (at the front) windows.

The "click" refers to any clickable area of an window. The clicked window should get focused.

![screenshot - 04142016 - 02 28 13 pm](https://cloud.githubusercontent.com/assets/6511849/14537393/33474522-024d-11e6-9f06-2fcc4646e806.png)

**Comment by mkassner** [comment]
This will require changing some low level stuff in pyglui. I will have a look at the feasibility of that.

**Comment by cpicanco** [comment]
It is just a suggestion I was considering for quite some time. Keep it for your own knowledge at first place and, since I was not considering the feasibility, fell free to close it as you wish.
