### ISSUE TITLE
PyGlui Issue with Recent OSX OpenGL Header relocation

### ISSUE THREAD

**Issue by tstavropoulos** [pupil-labs/pupil#369]
For OSX:

The setup.py for PyGlui expects to find the OpenGL headers in:

/System/Library/Frameworks/OpenGL.framework/Headers

They seem to have been moved in a (somewhat) recent OS/Xcode updates to:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers

After updating setup.py the install instructions worked properly.  I'm running El Capitan with Xcode 5 installed.

By the gods, I hate Apple

**Comment by willpatera** [comment]
Hi @tstavropoulos -- could you please migrate this issue to the [pyglui repo](https://github.com/pupil-labs/pyglui)?

**Comment by tstavropoulos** [comment]
Good point.  I originally put it here because it housed the setup instructions, but might as well fix the root issue. Thanks.
