### ISSUE TITLE
Pup_Player

### ISSUE THREAD

**Issue by ZCalus** [pupil-labs/pupil#374]
Hello everybody!
Recently i have met some displeasure thing. After my trying to just drop recording directories/videos (no matter) onto pp window - nothing going to be. Honestly, i have no more idea how to fix this.
When I’m try to start pupil player from terminal here what do we have:

Player [WARNING] __main__ : You did not supply a data directory when you called this script!
Player [ERROR] player_methods : No valid dir supplied

Can anybody explain me how to fix this?
Thank you.

**Comment by cpicanco** [comment]
Hi, could you say what files are inside the directory? Recordings were made with Pupil Capture? Are you running the program from source or from the stand alone executable?

**Comment by ZCalus** [comment]
I set rec directory in pupil capture /home/***/REC, and i can not find the
way how to see this folder from pupil player program. Like a i said, simple
way to just "drop recording directory onto this window" does not make
anything. I have already found pupil_player_settings folder and 2 files
with in: player.log and user_settings. But have no idea what to do next. Do
you have any suggestions?


2016-05-07 10:53 GMT+03:00 Rafael Picanço <notifications@github.com>:

**Comment by ZCalus** [comment]
By the way, I'm Kubuntu 14.04 LTS user. Also I'm using both of pupil app
0.62 version. Because i have had some trouble with
the latest version of capture, and the only one solution that i found in
pupil- discuss, and by myself was choose 0.62 (this probably could be
useful). Now capture works not bad, but player make me sad. I got to move
on in my researches and this delay is quiet uncomfortable.
Could you share any useful suggestions?

2016-05-07 17:39 GMT+03:00 youngpadavan <youngpadavan@gmail.com>:

**Comment by cpicanco** [comment]
Hi,

- Suggestion 1: I would strongly recommend you to use the last version of Pupil Capture and Pupil Player.

- Suggestion 2: With the last version in hands recording goes to: `/home/<username>/recordings/`. For example, a specific folder that you are supposed to drag and drop would be `/home/<username>/recordings/2016_05_07/003/' (at least on Debian 8 and Ubuntu 14.04 LTS).

- Suggestion 3: You may find useful to use catfish to search for pupil specific files like `pupil_data` or `*timestamps.npy`.

Hope this helps,
Best

**Comment by ZCalus** [comment]
For 1: OK. When i'm started latest Pupil Capture (0.75) i met the following
in terminal:

WORLD Process [ERROR] uvc : Turbojpeg jpeg2yuv error: Corrupt JPEG data 4
extraneous bytes before marker 0xd1
WORLD Process [ERROR] uvc : Turbojpeg jpeg2yuv error: Corrupt JPEG data: 3
extraneous bytes before marker 0xd3
WORLD Process [ERROR] uvc : Turbojpeg jpeg2yuv error: Corrupt JPEG data: 2
extraneous bytes before marker 0xd2
WORLD Process [ERROR] uvc : Turbojpeg jpeg2yuv error: Corrupt JPEG data: 2
extraneous bytes before marker 0xd4
WORLD Process [ERROR] uvc : Turbojpeg jpeg2yuv error: Corrupt JPEG data: 9
extraneous bytes before marker 0xd2


And this message is repeating with different ending of it until you will
shut down the app. What it could be? Because the only solution that i have
found was instalation of 0.62.

For 2: I have tried to drop actually directory like you said. But nothing
is looks like the window of player are going to react somehow

For 3: Ok, and what is next?

2016-05-07 21:43 GMT+03:00 Rafael Picanço <notifications@github.com>:

**Comment by mkassner** [comment]
Hi thanks for posting this error. This is the camera not sending good jpegs. Please try the new release we make this week. 

I m not sure if I understand your other quesiton. You have made a recording with Pupil capture?

please do this in terminal:
```shell
pupil-player ~/pupil-recording/your-recording-path/000
```

**Comment by ZCalus** [comment]
Ok, I will try the new one as soon, as it will be published.
And BLESS! Now player does work!
Thank you a lot! This command was exactly what i need!

**Comment by ZCalus** [comment]
Ohh, i have a few more bugs for tasting!

WORLD Process [WARNING] uvc : Could not set Value. 'Absolute Exposure Time'
must be read only
WORLD Process [WARNING] uvc : Could not set Value. 'White Balance
temperature' must be read only
and
WORLD Process [ERROR] world : Could not retrieve image from capture

Why does it happened? Could you explain me please?

2016-05-07 23:04 GMT+03:00 youngpadavan <youngpadavan@gmail.com>:

> Ok, I will try the new one as soon, as it will be published.
> And BLESS! Now player does work!
> Thank you a lot! This command was exactly what i need!
>

**Comment by mkassner** [comment]
Thats good to hear. 

The warnings can be ignored. Those are the uvc backend trying to set read-only values.
The error means that the camera could not be read. Please make an issue for the new problems. I will close this one.

**Comment by ZCalus** [comment]
And once again... New release does not fix any of this issues( Due to i
dont know

2016-05-08 13:12 GMT+03:00 mkassner <notifications@github.com>:

**Comment by mkassner** [comment]
Hi,

please attach the log file to your post or be more specifi about the error. Otherwise we cannot help.

The new release should give some better error messages.

**Comment by mkassner** [comment]
I m closing this die to inactivity.
