### ISSUE TITLE
Pupil capture crashing OS X El Capitan 10.11.4 

### ISSUE THREAD

**Issue by hmvandermeulen** [pupil-labs/pupil#375]
Pupil capture seems to be very unstable on several OSX (Macbook air & pro) machines and with several 120hz binocular recorders. Mostly during initial startup the capture software immediately stops again without any error notification, sometimes during recording itself.

Switching MacBooks or recording devices sometimes helps but all systems and recording devices eventually have this error. 

Problem occurs with older releases (since March) and the newest release.

Logs:

11:47:25 AM Kernel: 146531.788605 Pupil Cam1 ID0@14130000: AppleUSBDevice::ResetDevice: <software attempt to RESET>

World Process: 2016-05-07 11:47:24,441 - plugin - INFO - Loaded: Log_Display
World Process: 2016-05-07 11:47:24,441 - plugin - INFO - Loaded: Dummy_Gaze_Mapper
World Process: 2016-05-07 11:47:24,443 - plugin - INFO - Loaded: Screen_Marker_Calibration
World Process: 2016-05-07 11:47:24,443 - plugin - INFO - Loaded: Display_Recent_Gaze
World Process: 2016-05-07 11:47:24,444 - plugin - INFO - Loaded: Recorder
World Process: 2016-05-07 11:47:24,453 - world - WARNING - Eye 0 process started.
World Process: 2016-05-07 11:47:26,772 - uvc - WARNING - Could not grab frame. Restarting device
World Process: 2016-05-07 11:47:26,773 - world - ERROR - Capture from camera failed. Stopping.
World Process: 2016-05-07 11:47:26,788 - video_capture.uvc_capture - INFO - Capture released

Eye0 Process: 2016-05-07 11:47:25,767 - eye - ERROR - Could not retrieve image from capture
Eye0 Process: 2016-05-07 11:47:26,772 - video_capture.uvc_capture - INFO - Capture released

**Comment by mkassner** [comment]
Hi, 

thanks for posting this. We will release a new version that is more verbose and more robust to errors of this kind. Please try this version (I ll post a link in this issue when we release.) and report your results.

If the problem persists we need to look at the hardware (both macbook and Pupil Eye trackers) you are using in detail.

Best,

Moritz

**Comment by mkassner** [comment]
Please try with this version: https://github.com/pupil-labs/pupil/releases/tag/v0.7.6

**Comment by mkassner** [comment]
Hi,

any updates? I d love to get this fixed for you.

**Comment by hmvandermeulen** [comment]
I've attached two log files of two attempts. The first time the world camera seemed to be working for a while until I try to enable one of the pupil cameras. There's a lot of failed attempts to start the camera and then the world camera crashes too.

On attempt two (log 2) I enabled a pupil camera again but there seem to be a lot of missing frames (which luckily don't crash the software in this version). I think you can see this happening in the logs too. 

This is just with one eye tracker which might be faulty. I will ask if my colleagues still have problems with other trackers and this capture version. Since the crashes sometimes happened once a day or once every few days it can take some time to completely rule out the problem.

[capture logs.zip](https://github.com/pupil-labs/pupil/files/266132/capture.logs.zip)

**Comment by mkassner** [comment]
@hmvandermeulen thanks for the logs the the detailed description. The logs indicate that we do have a problem with the combination of headset and laptop.

We have also noticed similar behaviour on some new Macbook Air models before. (Though not for all variants.) It appears that some USB controllers do not play well with the current USB hub we build into the Pupil headset. We will release a new USB collar clip with USB3.0 and USB C connector soon and you will be able to retro fit the existing hardware with that. Please contact us via email for more details.

We also found that as a temporary fix the issue ca be circumvented by using a USB3.0 hub in between the laptop and headset. It is important that it is a USB3.0 version. This one is known to work: http://www.amazon.com/Cable-Matters-4-Port-Ultra-Mini-SuperSpeed/dp/B00PHPWLPA/ref=sr_1_1?ie=UTF8&qid=1463470698&sr=8-1-spons&keywords=usb+3.0+hub&psc=1

Let me know if that helps!

**Comment by mkassner** [comment]
I ll close this due to inactivity.
