### ISSUE TITLE
Use manual marker v3.0 for screen marker calibration

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#379]
### Description
Enhancement proposal: use the (new) [manual marker v3.0](https://github.com/pupil-labs/pupil/wiki/Pupil-Capture#manual-marker-calibration) for the marker in the screen marker calibration routine.

**Comment by mkassner** [comment]
The screen marker currently requires 5 rings so that a manual marker thats laying around does not break the calibration.

**Comment by willpatera** [comment]
Yes, that is true. But the new marker is quite robust and might improve the screen based calibration experience.

**Comment by mkassner** [comment]
ok. this is implemented.
