### ISSUE TITLE
OSX Yosemite compatiblity

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#38]
User feedback: Pupil capture is crashing in Yosemite OSX.

Needs to be investigated.

**Comment by mkassner** [comment]
Will ran the bundle on his 10.10 machine and it worked. So this problem is not 10.10 related but the know issue of some mac hardware to liking to run the bundles.

Please install from source.

M

**Comment by willpatera** [comment]
@MobilitylabPatchs I am running OSX Yosemite (10.10.1) on a MacBook Air 6,1 (Intel Core i5 1.4GHz, Intel HD Graphics 5000). As @mkassner stated, I confirm that I am running the [v0.3.9 bundle](https://github.com/pupil-labs/pupil/releases/tag/v0.3.9) with no errors.
