### ISSUE TITLE
0.7.5 Ubuntu Eye Cam General Mode ROI Bug

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#380]
If you define a 'Region of Interest' in the eye camera settings and switch back to 'Camera Image' afterwards then the 'ROI' is still active. 

You have to align the ROI edges to screen edges to process the 'Camera Image' again.

Check: I defined half of the screen as my ROI, so while the eye changes from left to right it is just detected within the ROI. This persists if I change to 'Camera Image'

**Comment by mkassner** [comment]
Thats not really a bug. The idea of the roi mode it that you use it to set the ROI. If you leave the mode the ROI should still be persistent. I made a change to make this more apparent.
