### ISSUE TITLE
Opencv2/core.hpp: no such file or directory

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#383]
I'm running PupilLabs on Ubuntu16.04. I installed all dependencies you suggested online.

When I run pupil from the source code I get the world camera working fine but the application crashes when i start the eye camera - I got the following

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from singleeyefitter/ImageProcessing/cvx.cpp:2:0:
singleeyefitter/ImageProcessing/cvx.h:4:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from singleeyefitter/detectorUtils.cpp:2:0:
singleeyefitter/detectorUtils.h:5:33: fatal error: opencv2/core/core.hpp: No such file or directory
compilation terminated.
detector_2d.cpp:345:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/username/Desktop/PupilLabs/pupil_src/capture/eye.py", line 94, in eye
    from pupil_detectors import Detector_2D, Detector_3D
  File "/home/useername/Desktop/PupilLabs/pupil_src/capture/pupil_detectors/__init__.py", line 18, in <module>
    from detector_2d import Detector_2D
ImportError: /home/mothman/Desktop/PupilLabs/pupil_src/capture/pupil_detectors/detector_2d.so: invalid ELF header
In file included from singleeyefitter/utils.cpp:2:0:
singleeyefitter/utils.h:20:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.

**Comment by mkassner** [comment]
When running Pupil from source, we compile certains cpp modules on demand. During this compilation it seems that the opencv header files could not be located. Please make sure you have opencv properly installed and the paths are correct.

Then it should work.

**Comment by mothman1** [comment]
Thanks mkassner for your quick response, as usual :)
However, I reinstalled OpenCV and when I open Python console in PyCharm I confirm that i can use it. After the new install I no longer get the error above but I receive a new one which seems to be related:

building 'detector_2d' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/local/opt/opencv3/include -I/usr/include/python2.7 -c detector_2d.cpp -o build/temp.linux-x86_64-2.7/detector_2d.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/local/opt/opencv3/include -I/usr/include/python2.7 -c singleeyefitter/ImageProcessing/cvx.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/ImageProcessing/cvx.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/local/opt/opencv3/include -I/usr/include/python2.7 -c singleeyefitter/utils.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/utils.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/local/opt/opencv3/include -I/usr/include/python2.7 -c singleeyefitter/detectorUtils.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/detectorUtils.o -std=c++11 -w -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from singleeyefitter/ImageProcessing/cvx.cpp:2:0:
singleeyefitter/ImageProcessing/cvx.h:4:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
detector_2d.cpp:345:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mothman/Desktop/PupilLabs/pupil_src/capture/eye.py", line 94, in eye
    from pupil_detectors import Detector_2D, Detector_3D
  File "/home/mothman/Desktop/PupilLabs/pupil_src/capture/pupil_detectors/__init__.py", line 18, in <module>
    from detector_2d import Detector_2D
ImportError: /home/mothman/Desktop/PupilLabs/pupil_src/capture/pupil_detectors/detector_2d.so: invalid ELF header
In file included from singleeyefitter/utils.cpp:2:0:
singleeyefitter/utils.h:20:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.
In file included from singleeyefitter/detectorUtils.cpp:4:0:
singleeyefitter/utils.h:20:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.

**Comment by mkassner** [comment]
I think your opencv python bindings are working. in addition to that we also need the c++ header files for compilation. Usually theses or symlinks of them can be found in /usr/local/include do you see opencv headers there?

**Comment by mothman1** [comment]
I dont have any opencv files in that directory. But, I have two hpp files in /usr/include folder

/usr/include/opencv2/opencv.hpp
and
/usr/include/opencv2/opencv_modules.hpp

**Comment by mothman1** [comment]
mkassner, I did as you suggested. I managed to reinstall opencv manually into usr/local/include and now I get no related issues. However, now I get other issues related to 

sp.call("cd %s && python setup.py build_ext --inplace && cd %s"%(src_loc,cwd),shell=True)

in the pupil_detectors/build.py file

As soon as that line of code is called I get the following errors and nothing happen - The world camera always runs but the eye camera is the problem

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/local/opt/opencv3/include -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c detector_3d.cpp -o build/temp.linux-x86_64-2.7/detector_3d.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/local/opt/opencv3/include -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/ImageProcessing/cvx.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/ImageProcessing/cvx.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/local/opt/opencv3/include -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/utils.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/utils.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/local/opt/opencv3/include -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/detectorUtils.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/detectorUtils.o -std=c++11 -w -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/local/opt/opencv3/include -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/EyeModelFitter.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/EyeModelFitter.o -std=c++11 -w -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/local/opt/opencv3/include -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/EyeModel.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/EyeModel.o -std=c++11 -w -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

**Comment by cpicanco** [comment]
Hi @mothman1 , quick tip: what about using gist to the logs?

**Comment by mkassner** [comment]
@mothman1  I dont see an errors in your last paste. Just warnings... Can you paste the part with the error?
