### ISSUE TITLE
Manual gaze correction not showing in exported data

### ISSUE THREAD

**Issue by hmvandermeulen** [pupil-labs/pupil#384]
It seems that adjusting the manual gaze correction, quite a bit in this case (0.93), doesn't reflect in both fixations and gaze data. Particularly in the on_srf data. While playing the video in pupil player the corrected gaze is clearly in the drawn surface but when I click 'Recalculate gaze distributions' there's a notification: "No gaze on any surface for this section"

Also in exported data the columns 'on_srf' are all false. 

Player 0.7.5

**Comment by mkassner** [comment]
I just tried what you described and could not recreate the problem. Can you share a recording of yours so I can try?

**Comment by mkassner** [comment]
I ll close this due to inactivity. Please make a new issue if this error persist.
