### ISSUE TITLE
export csv data format

### ISSUE THREAD

**Issue by paranoidandroid0815** [pupil-labs/pupil#386]
It would be nice if the export function for raw data eport would be more configureable and the data formats be more conform.
e.g.
If you read the data from the server plugin, it's json
If you export data from the player, it's comma separated (with mixed data-types strings and numbers, so you've to deal with format strings and stuff for data processing in matlab)
If you export the fixations it's tabulator separated

thanks and kind regards

**Comment by mkassner** [comment]
Yes. all player cvs exports should have the same format. 

since the interaction with the server is a bit different I think we should stick with json there.

**Comment by mkassner** [comment]
This is being worked on in #437

**Comment by mkassner** [comment]
Done.
