### ISSUE TITLE
Correct screen resolution for high ppi screens - eg Macbook Pro Retina

### ISSUE THREAD

**Issue by kevsink** [pupil-labs/pupil#388]
At the moment the Screen looks pixelated on a MBP Retina display. The menu items are pixelated and fonts do not appear smooth. 

Lots of monitors are still fairly low ppi but as time goes on more machines will become higher.

**Comment by papr** [comment]
Problem: Menu font rendering acts weird with a scaling of `2.5`

<img width="1392" alt="pupil_capture" src="https://cloud.githubusercontent.com/assets/168390/16515856/cec1fbb4-3f74-11e6-8ee7-32c48c5512a4.png">

Screenshot source: MBP 13", Early 2015, Retina Display.

**Comment by mkassner** [comment]
This is an odd fontstash bug. I m not sure how to get rid of it.

**Comment by papr** [comment]
ScreenMarkerCalibration on retina displays is also broken.

**Comment by mkassner** [comment]
@papr  can you investigate?

**Comment by papr** [comment]
[GLFW docs](http://www.glfw.org/docs/latest/group__window.html#ga5c336fddf2cbb5b92f65f10fb6043344) say under `Remarks`:
> OS X: On `OS X 10.10` and later the window frame will not be rendered at full resolution on Retina displays unless the `NSHighResolutionCapable` key is enabled in the application bundle's Info.plist. For more information, see High Resolution Guidelines for OS X in the Mac Developer Library. The GLFW test and example programs use a custom Info.plist template for this, which can be found as [`CMake/MacOSXBundleInfo.plist.in`](https://github.com/glfw/glfw/blob/master/CMake/MacOSXBundleInfo.plist.in) in the source tree.

**Comment by mkassner** [comment]
@papr this is where we deal with the screen size: https://github.com/pupil-labs/pupil/blob/master/pupil_src/capture/world.py#L369

When using retina macs - if you cut this size in half - you should be able to fix the UI. Another option is looking into http://www.glfw.org/docs/latest/group__window.html#gaeea7cbc03373a41fb51cfbf9f2a5d4c6

and use that instead. However its important to make sure this works across platforms and hardware setups.

Also note that we might want to use window_size here: 
https://github.com/pupil-labs/pupil/blob/master/pupil_src/capture/world.py#L177-L179

But frame_buffer_size here: 
https://github.com/pupil-labs/pupil/blob/master/pupil_src/capture/world.py#L180-L182

**Comment by mkassner** [comment]
fixed.
