### ISSUE TITLE
Ubuntu 16.4 - No module named detector_2d

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#390]
Following your instructions regarding dependencies on Linux. The world camera runs fine but not the eye camera. When I run the eye camera I get some warning related to cclplus compiler and other errors. Note, I have gcc installed as well as all other dependencies but I still get the following:

/usr/bin/python2.7 /home/mothman/Desktop/PupilCrowdEyes/pupil-0.7.6/pupil_src/capture/main.py
running build_ext
world - [ERROR] video_capture : No accessible device found that matched ['Pupil Cam1 ID2', 'Logitech Camera', '(046d:081d)', 'C510', 'B525', 'C525', 'C615', 'C920', 'C930e']
world - [WARNING] video_capture : Starting with Fake_Capture.
arecord: device_list:268: no soundcards found...
world - [WARNING] world : Eye 0 process started.
running build_ext
building 'detector_2d' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c detector_2d.cpp -o build/temp.linux-x86_64-2.7/detector_2d.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/ImageProcessing/cvx.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/ImageProcessing/cvx.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/utils.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/utils.o -std=c++11 -w -O2
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c singleeyefitter/detectorUtils.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/detectorUtils.o -std=c++11 -w -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from detector_2d.cpp:331:0:
/usr/local/include/opencv2/core/core_c.h:97:1: error: ‘IplImage’ does not name a type
 CVAPI(IplImage*)  cvCreateImageHeader( CvSize size, int depth, int channels );
 ^
/usr/local/include/opencv2/core/core_c.h:109:1: error: ‘IplImage’ does not name a type
 CVAPI(IplImage*) cvInitImageHeader( IplImage* image, CvSize size, int depth,
 ^
/usr/local/include/opencv2/core/core_c.h:125:1: error: ‘IplImage’ does not name a type
 CVAPI(IplImage*)  cvCreateImage( CvSize size, int depth, int channels );
 ^
In file included from /usr/local/include/opencv2/core/utility.hpp:890:0,
                 from /usr/local/include/opencv2/core.hpp:3176,
                 from /usr/local/include/opencv2/core/types_c.h:101,
                 from detector_2d.cpp:331:
/usr/local/include/opencv2/core/core_c.h:140:36: error: variable or field ‘cvReleaseImageHeader’ declared void
 CVAPI(void)  cvReleaseImageHeader( IplImage** image );
                                    ^
/usr/local/include/opencv2/core/core_c.h:140:36: error: ‘IplImage’ was not declared in this scope
/usr/local/include/opencv2/core/core_c.h:140:47: error: ‘image’ was not declared in this scope
 CVAPI(void)  cvReleaseImageHeader( IplImage** image );
                                               ^
/usr/local/include/opencv2/core/core_c.h:154:30: error: variable or field ‘cvReleaseImage’ declared void
 CVAPI(void)  cvReleaseImage( IplImage** image );
                              ^
/usr/local/include/opencv2/core/core_c.h:154:30: error: ‘IplImage’ was not declared in this scope
/usr/local/include/opencv2/core/core_c.h:154:41: error: ‘image’ was not declared in this scope
 CVAPI(void)  cvReleaseImage( IplImage** image );
                                         ^
In file included from detector_2d.cpp:331:0:
/usr/local/include/opencv2/core/core_c.h:157:1: error: ‘IplImage’ does not name a type
 CVAPI(IplImage*) cvCloneImage( const IplImage* image );
 ^
In file included from /usr/local/include/opencv2/core/utility.hpp:890:0,
                 from /usr/local/include/opencv2/core.hpp:3176,
                 from /usr/local/include/opencv2/core/types_c.h:101,
                 from detector_2d.cpp:331:
/usr/local/include/opencv2/core/core_c.h:169:29: error: variable or field ‘cvSetImageCOI’ declared void
 CVAPI(void)  cvSetImageCOI( IplImage* image, int coi );
                             ^
/usr/local/include/opencv2/core/core_c.h:169:29: error: ‘IplImage’ was not declared in this scope
/usr/local/include/opencv2/core/core_c.h:169:39: error: ‘image’ was not declared in this scope
 CVAPI(void)  cvSetImageCOI( IplImage* image, int coi );
                                       ^
/usr/local/include/opencv2/core/core_c.h:169:46: error: expected primary-expression before ‘int’
 CVAPI(void)  cvSetImageCOI( IplImage* image, int coi );
                                              ^
/usr/local/include/opencv2/core/core_c.h:177:34: error: ‘IplImage’ does not name a type
 CVAPI(int)  cvGetImageCOI( const IplImage* image );
                                  ^
/usr/local/include/opencv2/core/core_c.h:190:29: error: variable or field ‘cvSetImageROI’ declared void
 CVAPI(void)  cvSetImageROI( IplImage* image, CvRect rect );
                             ^
/usr/local/include/opencv2/core/core_c.h:190:29: error: ‘IplImage’ was not declared in this scope
/usr/local/include/opencv2/core/core_c.h:190:39: error: ‘image’ was not declared in this scope
 CVAPI(void)  cvSetImageROI( IplImage* image, CvRect rect );
                                       ^
/usr/local/include/opencv2/core/core_c.h:190:46: error: ‘CvRect’ was not declared in this scope
 CVAPI(void)  cvSetImageROI( IplImage* image, CvRect rect );
                                              ^
/usr/local/include/opencv2/core/core_c.h:201:31: error: variable or field ‘cvResetImageROI’ declared void
 CVAPI(void)  cvResetImageROI( IplImage* image );
                               ^
/usr/local/include/opencv2/core/core_c.h:201:31: error: ‘IplImage’ was not declared in this scope
/usr/local/include/opencv2/core/core_c.h:201:41: error: ‘image’ was not declared in this scope
 CVAPI(void)  cvResetImageROI( IplImage* image );
                                         ^
In file included from detector_2d.cpp:331:0:
/usr/local/include/opencv2/core/core_c.h:208:1: error: ‘CvRect’ does not name a type
 CVAPI(CvRect) cvGetImageROI( const IplImage* image );
 ^
/usr/local/include/opencv2/core/core_c.h:218:1: error: ‘CvMat’ does not name a type
 CVAPI(CvMat*)  cvCreateMatHeader( int rows, int cols, int type );
 ^
/usr/local/include/opencv2/core/core_c.h:254:1: error: ‘CvMat’ does not name a type
 CVAPI(CvMat*) cvInitMatHeader( CvMat* mat, int rows, int cols,
 ^
/usr/local/include/opencv2/core/core_c.h:272:1: error: ‘CvMat’ does not name a type
 CVAPI(CvMat*)  cvCreateMat( int rows, int cols, int type );
 ^
In file included from /usr/local/include/opencv2/core/utility.hpp:890:0,
                 from /usr/local/include/opencv2/core.hpp:3176,
                 from /usr/local/include/opencv2/core/types_c.h:101,
                 from detector_2d.cpp:331:
/usr/local/include/opencv2/core/core_c.h:285:28: error: variable or field ‘cvReleaseMat’ declared void
 CVAPI(void)  cvReleaseMat( CvMat** mat );
                            ^
/usr/local/include/opencv2/core/core_c.h:285:28: error: ‘CvMat’ was not declared in this scope
/usr/local/include/opencv2/core/core_c.h:285:36: error: ‘mat’ was not declared in this scope
 CVAPI(void)  cvReleaseMat( CvMat** mat );
                                    ^
/usr/local/include/opencv2/core/core_c.h:298:32: error: variable or field ‘cvDecRefData’ declared void
 CV_INLINE  void  cvDecRefData( CvArr* arr )
                                ^
/usr/local/include/opencv2/core/core_c.h:298:32: error: ‘CvArr’ was not declared in this scope
/usr/local/include/opencv2/core/core_c.h:298:39: error: ‘arr’ was not declared in this scope
 CV_INLINE  void  cvDecRefData( CvArr* arr )
                                       ^
In file included from /usr/include/eigen3/Eigen/Core:318:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /usr/include/eigen3/Eigen/Eigen:1,
                 from detector_2d.cpp:333:
/usr/include/eigen3/Eigen/src/Core/arch/SSE/Complex.h:101:30: error: expected ‘}’ before end of line
/usr/include/eigen3/Eigen/src/Core/arch/SSE/Complex.h:101:30: error: expected declaration before end of line
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Process eye0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mothman/Desktop/PupilCrowdEyes/pupil-0.7.6/pupil_src/capture/eye.py", line 88, in eye
    from pupil_detectors import Detector_2D, Detector_3D
  File "/home/mothman/Desktop/PupilCrowdEyes/pupil-0.7.6/pupil_src/capture/pupil_detectors/__init__.py", line 18, in <module>
    from detector_2d import Detector_2D
ImportError: No module named detector_2d

Process finished with exit code 0

**Comment by cpicanco** [comment]
Hi, please, consider using gist to the logs.

**Comment by mkassner** [comment]
Hi @mothman1 , Something is wring with your compiler toolchain. We are seeing errors when its trying to compile opencv parts. 

Its very hard to debug this from remote. Please try to follow the instructions on a clean system.

**Comment by fingolfin500** [comment]
Try installing OpenCV2 if you haven't already.

**Comment by mkassner** [comment]
doing apt-get install libopencv-dev will fix this
