### ISSUE TITLE
How to use other time server?

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#392]
Hi all,
I am wondering how I can best synchronize with an existing library which provides a time (ROS). The time is given as `float`, so it is very similar to the `get_time_monotonic` used within pupil. However, there is a huge offset.
I found https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_sync/network_time_sync.py which synchronizes between different hosts. Can I somehow trick this script such that my ROS time is used as master, and the sync plugin within the capture application uses this master?
It would be great if you give me a hint to the proper way of doing this. I prefer not to touch the pupil source code (i.e. I don't want to just replace `uvc.get_time_monotonic()` with `rospy.get_time()` for all occurrences.

Thanks a lot,
Tobias

**Comment by mkassner** [comment]
Hi Tobias,

yes this is quite easy to do, here are some options:

1) use Pupil Remote and set the pupil time base to the ROS time. (docs are in the source: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/pupil_remote.py#L23-L54)
2) Write a little plugin that does the same: (howto here: https://github.com/pupil-labs/pupil/wiki/Plugin-Guide), in the plugin have access to self.g_pool.timebase.value : set this to adjust the time base of all clocks used in the Pupil App.

**Comment by Tobias-Fischer** [comment]
Hi, great, that will do the job. Thanks a lot!

**Comment by evaaa10** [comment]
For further help:

Option 1: Edit https://github.com/pupil-labs/pupil/blob/edb52370e8ed5d3f72489fe19bce992c06eb9791/pupil_src/shared_modules/pupil_remote.py#L247 by target = time.time() if you want the systemtime (unix)
Option 2: write a little plugin with edited lines (https://github.com/pupil-labs/pupil/blob/edb52370e8ed5d3f72489fe19bce992c06eb9791/pupil_src/shared_modules/pupil_remote.py#L247-L253) once or repetitive
