### ISSUE TITLE
Integration of Pupil Sync and the IPC Backbone

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#396]
We need to think about how to integrate `Pupil Sync` with the upcoming `IPC Backbone`.

- `Pupil Sync` should have the possibility to gather pub/sub addresses of the other nodes.
- Notifications are already published to the network. Does `Pupil Sync` have to duplicate feature?
- Duplicated notifications need to be avoided

**Comment by mkassner** [comment]
@papr yes totally agree on this. Pupil Sync and the IPC backbone are overlapping and we need to be careful not be to redundant. I feel that pupil sync should not expose an API, instead its just used to sync capture app instances. Developers should really look at pupil remote and the IPC backbone to interface with capture/service. 

However this is totally up for discussion lets talk more about this in detail.

**Comment by papr** [comment]
@mkassner I agree on the point that `Pupil Sync` should not expose an API—at least not as plugin to the local software. Although there should be an `Sync API` such that remote software is able to sync as well. The question is what features this `Sync API` should sync. Time is the first thing which comes to my mind here.

A spontaneous solution for the 'notification duplication problem' would be to make all clock followers subscribe to the clockmaster's `Backbone`. Then we would not have duplicated functionality and would also avoid single duplicated notifications.

I am looking forward to discuss more details.

**Comment by papr** [comment]
Introducing `discovery.py` at papr/pupil@6ed606568

TODO:

- Discuss default groups
- Discuss user options (name + group changes through UI)
- Discuss dev options  (name + group changes through notifications)

- `Time Sync` implementation

**Comment by mkassner** [comment]
This has been done with #439 and #434
