### ISSUE TITLE
Turbojpeg jpeg2yuv error

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#399]
Hi, using the last bundle, everything is working just fine, but I am getting a lot of red messages:

https://gist.github.com/cpicanco/80f7f5ce9033ff3ad6099b4408935a06

![screenshot from 2016-06-17 15 04 38](https://cloud.githubusercontent.com/assets/6511849/16160139/da11ba0a-349c-11e6-9117-671525169a5e.png)

**Comment by mkassner** [comment]
thanks for this. What world camera are you using?

**Comment by cpicanco** [comment]
Logitech C615.

Recordings and eye movements are being saved normally, afaik. I am not sure
about the implications of this error beyond a screen full of red messages.

**Comment by mkassner** [comment]
I hope this change will fix your problem.

**Comment by cpicanco** [comment]
Will install from source today and test this.

**Comment by cpicanco** [comment]
Is there some way controlling the verbose  (no warnings)?? 

So far so good, no problems with the recordings at all. Playing them normally.

![screenshot from 2016-06-29 11 29 45](https://cloud.githubusercontent.com/assets/6511849/16456062/f39175a2-3dec-11e6-99d2-b068b228f1ad.png)

**Comment by elmorg** [comment]
Hi, I'm having this issue with the latest release - pupil_capture_mac_os_x64_v0.8.6-1. Also using the C615 camera.

**Comment by cpicanco** [comment]
@papr @mkassner , is there a way to disable the warnings from inside a runtime plugin?

**Comment by cpicanco** [comment]
To disable all warnings
```
logging.disable(logging.WARNING)
```

**Comment by mkassner** [comment]
Even better would be something like:

```pyhton
        logging.getLogger("uvc_backend"). disable(logging.WARNING)
```

though not tested.

**Comment by cpicanco** [comment]
```
world - [WARNING] plugin: Failed to load 'screen_tracker'. Reason: ''Logger' object has no attribute 'disable'' 
```
:cry:

**Comment by mkassner** [comment]
```
        logging.getLogger("uvc_backend").set_level(logging.CRITICAL)
```

**Comment by dznet** [comment]
i added plugin to ``` ~/pupil_capture_settings/plugins/ ```

plugin code: 
```
import logging
logging.disable(logging.WARNING)
```


thanks!
