### ISSUE TITLE
Probleme installing on Windows

### ISSUE THREAD

**Issue by icomfred** [pupil-labs/pupil#40]
Hi !

After installing, many errors occurs. I'v been trying debugging with some "print" in the code.

First : gcc (unrecognized option)

gcc: unrecognized option `-shared'
cc1.exe: Invalid option `64'
methods.c: In function `filter':
methods.c:151: parse error before `window_lower'
methods.c:92: warning: unused variable `min_h'
methods.c:94: warning: `h' might be used uninitialized in this function
methods.c:94: warning: `i' might be used uninitialized in this function
methods.c:94: warning: `j' might be used uninitialized in this function
methods.c:103: warning: `h' might be used uninitialized in this function
methods.c:156: warning: `h' might be used uninitialized in this function
methods.c: In function `ring_filter':
methods.c:218: parse error before `window_lower'
make: [methods.so] Error 1 (ignored)

Second : the file "pupil\pupil_src\shared_modules\c_methods\__init__.py" can't compile "methods.so".

Traceback (most recent call last):
  File "main.py", line 80, in <module>
    from eye import eye
  File "c:\Users\Admin\Documents\DEV\eye-tracking\pupil\pupil_src\capture\eye.py
", line 23, in <module>
    from pupil_detectors import Canny_Detector,MSER_Detector,Blob_Detector
  File "c:\Users\Admin\Documents\DEV\eye-tracking\pupil\pupil_src\capture\pupil_
detectors\__init__.py", line 27, in <module>
    from canny_detector import Canny_Detector
  File "c:\Users\Admin\Documents\DEV\eye-tracking\pupil\pupil_src\capture\pupil_
detectors\canny_detector.py", line 27, in <module>
    from c_methods import eye_filter
  File "c:\Users\Admin\Documents\DEV\eye-tracking\pupil\pupil_src\shared_modules
\c_methods\__init__.py", line 61, in <module>
    raise Exception("c-methods Error could not compile binary.")
Exception: c-methods Error could not compile binary.

Thanks

**Comment by mkassner** [comment]
Hi,

the error I see here that c_methods does not compile on your machine. This should be a ming_gw problem.

Other that that everything seems ok!

**Comment by icomfred** [comment]
Hi mkassner,

Thanks for the answer. Before your answer, I solved parse error in the file
"methods.c" by rewriting some parts of the code.

For example, I changed :


*    window_lower = {MAX(0,best_pos.r-step+1),MAX(0,best_pos.c-step+1)};
window_upper =
{MIN(img_size.r,best_pos.r+step),MIN(img_size.c,best_pos.c+step)};*

by :

    window_lower.r = MAX(0,best_pos.r-step+1);
    window_lower.c = MAX(0,best_pos.c-step+1);

    window_upper.r = MIN(img_size.r,best_pos.r+step);
    window_upper.c = MIN(img_size.c,best_pos.c+step);

So no more parse errors but the "methods.so" can't compile.
I will follow your advice and search solutions for "ming_gw".
I send you my modified "methods.c".
Perhaps my corrections will give you an idea of how to solve my problem.

Have a nice day.

Icomfred

2015-01-08 12:49 GMT+01:00 mkassner <notifications@github.com>:

**Comment by mkassner** [comment]
any updates on this issue?

**Comment by icomfred** [comment]
Hi,

Not yet. I'm working on many projects simultaneously.
I'm finalizing some others more advanced. I will work again on pupils
as soon as possible.

Thank you.



2015-01-28 19:46 GMT+01:00 mkassner <notifications@github.com>:

**Comment by mkassner** [comment]
We are updated our install guide with v0.4 so I m closing this for now
