### ISSUE TITLE
Be able to compile the C++ code on an older computer

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pupil#405]
With 2GB of RAM, running `pupil_src/capture/pupil_detectors/build.py` makes the OS to swap, on Linux. 4GB are required.

It's because there are 4 compilations in parallel, as hardcoded in setup.py.

Compiling C++ code can take a lot of RAM.

It would be nice to be able to run Pupil Capture on less powerful, older computers. With 2GB of RAM, Pupil Capture runs fine if the code is already compiled.

**Comment by mkassner** [comment]
I noticed this on my build vm's as well. Should be fixed now.

**Comment by swilmet-ucl** [comment]
Sorry for the late reply, I'm now back at my day job.

Thanks for the commit, it should resolve my issue.
