### ISSUE TITLE
Pupil Capture 0.8: Pupil Server plugin not listed

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pupil#406]
It worked fine with version 0.7.6, so it's a recent regression.

With Pupil Capture 0.8, the Pupil Server plugin (broadcasting messages with a ZeroMQ publisher) is not listed in the `Open plugin` list. So the plugin cannot be loaded.

**Comment by cpicanco** [comment]
Pupil Capture introduced a new IPC backbone, it deprecated Pupil Server.

Please, take a look: https://github.com/pupil-labs/pupil/pull/385

**Comment by mkassner** [comment]
Whats missing is docs on this topic!

**Comment by mkassner** [comment]
here we go: https://github.com/pupil-labs/pupil/wiki/Pupil-Interprocess-and-Network-Communication

**Comment by mkassner** [comment]
also new helpers: https://github.com/pupil-labs/pupil-helpers/tree/master/pupil_remote

**Comment by swilmet-ucl** [comment]
Ok thanks, I'll take a look soon, now that I'm back at my day job (sorry for the late reply).

**Comment by swilmet-ucl** [comment]
The following wiki page needs to be updated too:
https://github.com/pupil-labs/pupil/wiki/Pupil-Capture

There is still the "Pupil Broadcast Server" section. But for those that still use the version <= 0.7, that information is useful. So it could be moved to an "archive" wiki page.
