### ISSUE TITLE
uvc: Could not get Frame. Error: "Operation timed out.".

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pupil#407]
When I launch Pupil Capture 0.8, I get the following messages:

```
world - [INFO] uvc: Could not get Frame. Error: "Operation timed out.". Attempt:1/3
[...]
eye0 - [INFO] uvc: Could not get Frame. Error: "Operation timed out.". Attempt:1/3
```

I don't have those messages with version 0.7.6, so it's a recent regression. (I didn't change the versions of the installed dependencies, the only thing that changes is the `pupil` version, i.e. this repo).

**Comment by mkassner** [comment]
I changed the warning to debug on the first occasion of this error as a single occurrence is non critical.
