### ISSUE TITLE
uvc: Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pupil#408]
With Pupil Capture, when I close the world or eye window, I have the following error:

```
[ERROR] uvc: Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
```

It's not a recent regression, I have this error with both 0.8 and 0.7.6 (and earlier too I think).

**Comment by mkassner** [comment]
its a non critical error in the backend. I demoted the level to warning.
