### ISSUE TITLE
Pupil positions being dragged by moving world (Player)

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#41]
Hey guys, 

I have noticed that with scan-path opened, all pupil positions are dragged in accord with and as the world camera image moves. I think that this behavior could be useful to tracking the world image for past pupils in some range. Please, could you confirm this behavior? Did I describe it correctly or is there no such a thing?

If yes, I think that some kind of distinction should be created between current pupils and past pupils, to avoid artifacts. For example, despite the fact one were fixedly looking at a cellphone, his fingers will cross over his gaze positions with some chance. If, for some reason, there was a high chance of a such thing, an analysis of his behavior might led to think that he was looking a lot to his fingers. But he was not.

Hope this helps,

Best,
Rafael

**Comment by mkassner** [comment]
Hi,

yes your observation is correct. 

The plugin `scan path` 'sticks' past gaze onto the image pixels. The underlying idea being that what matters is the context that you fixate on, not the gaze position relative to the head orientation.

While this method does not take into account local changes in the scene (objects moving and occluding the fixed point etc.) and is also failing when the optical flow algorithm does not have enough local feature to estimate any transformation we still find it better than just creating a static trail of gaze points.

Your concern is very valid. I m not sure what would be the best approach to prevent such misbehaviour.

Best,

Moritz

**Comment by cpicanco** [comment]
Well, a threshold is not a good idea? It will not prevent any misbehaviour for past gaze, but It should give better visual feedback I think. At least, a threshold gives a way to balance and to compare. For current gaze positions (say, x = 500 ms), do static, else do dynamic.

**Comment by mkassner** [comment]
Hi,

have you tried this? I m curious to see if the result is better.

**Comment by cpicanco** [comment]
No, I have not. But I will, soon. I think that the "current time" for gaze positions are too short right now (one frame if I am right, please could you confirm this?). It kind of overrides the vis_circle feedback. I am not sure how is the best way to implement it, but since 200 ms is the mean response time for humans, I expect better visual feedback.
