### ISSUE TITLE
Head Position Inquiry

### ISSUE THREAD

**Issue by ablx** [pupil-labs/pupil#410]
Is it possible to get the head position in space with respect to the surface ( using surface tracker?) ... if yes, which json tuple should I use? Thank you very much!

**Comment by mkassner** [comment]
hi, I just added the field for 3d poses from markers. the field is called `camera_pose_3d`

Once the surface tracker runs and 3d localisation is on, this field will display the homogenous transformation matrix describing the camera pose as a list of lists. Using numpy.matrix() on this object will construct the required matrix. 

A use example can be found in the reference surface debug window implementation: https://github.com/pupil-labs/pupil/blob/8ca4580dbd024f67223db5250092fed04cda4913/pupil_src/shared_modules/reference_surface.py#L564-L571

Please let me know if this works for you.

**Comment by mkassner** [comment]
this is now part of the latest release v0.8. closing the issue.

**Comment by Saftophobia** [comment]
Thank you very much for the fast response. But it is still seem that the translation part is still affected by the rotation of the camera. Also we have difficulties converting the homogenous matrix to absolute values in our tracking space. 

``` python
homo_matrix = np.matrix(s.camera_pose_3d.tolist())
translation = homo_matrix[0:3, 3:4]
rotation = homo_matrix[0:3,0:3]
```
