### ISSUE TITLE
Improve documentation for Pupil data sent over Pupil Server/IPC

### ISSUE THREAD

**Issue by SGBon** [pupil-labs/pupil#411]
Unless I've missed it somewhere, there appears to be no information on the makeup of the zmq data which clients can extract, or even the topics they can get. The only info that I found comes from random examples spread around the wiki that demonstrates specific uses of the Pupil Server addon. There should be a single page that describes the IPC data.

**Comment by mkassner** [comment]
Hi,
we added some docs: https://github.com/pupil-labs/pupil/wiki/Pupil-Interprocess-and-Network-Communication 

Feel free to give feedback via issues or edit yourself.
