### ISSUE TITLE
Deploy my version of Pupil Labs

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#412]
I made some modification to Pupil labs and would like to deploy it and use it on Ubuntu - Would you guide me on how to do it? or, should I send you the source code and you make the deployment files?

Thanks in advance

**Comment by mkassner** [comment]
Hi,

just send me a link to your repo and branch, I can bundle for you.

**Comment by mothman1** [comment]
Thanks a lot - Here is the link 
https://github.com/mothman1/pupil

I might need to do it a few more times, is there a procedure to follow so I do it by my self later?

**Comment by mkassner** [comment]
Sorry for the late reply. Before I bundle. Any added dependencies?

**Comment by mothman1** [comment]
Please don't bundle now, I'm doing more changes and will let you know when ready.

One question though, is it possible that I bundle it myself whenever needed? Is there any reason not to do it myself?

**Comment by cpicanco** [comment]
Hi @mothman1 , in accord with the Pupil-Labs team, the bundle process is challenging for common users and, now it is me talking, even for developers. Regardless of it, you are not the first to ask such a thing; please, take a look at the README in the following link for a brief explanation about why offering support for the bundle process is not maintainable:

https://github.com/pupil-labs/pupil/tree/master/deployment

**Comment by mkassner** [comment]
@mothman1  after installing all dependencies you can give the bundle scripts as shot with a bit of luck it will just work :-)

**Comment by swilmet-ucl** [comment]
I have written a Docker container for Pupil:
https://github.com/UCL-CATL/docker-pupil

It's maybe easier to modify. But I'm myself a developer and a long-time Linux user.
