### ISSUE TITLE
Problems with opencv path running from source

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#413]
Trying to find out how to solve this on Ubuntu.

```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I../../shared_cpp/include -Isingleeyefitter/ -I/usr/include/python2.7 -c detector_2d.cpp -o build/temp.linux-x86_64-2.7/detector_2d.o -std=c++11 -w -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
detector_2d.cpp:331:34: fatal error: opencv2/core/types_c.h: No such file or directory
 #include <opencv2/core/types_c.h>

```

**Comment by cpicanco** [comment]
Installing `python-opencv` is not enough. Should the official opencv installation be included as a dependency? Or you have your own procedure?

**Comment by mkassner** [comment]
if think doing 
```
apt-get install libopencv-dev
```

should fix this problem.

**Comment by cpicanco** [comment]
Much better

**Comment by cpicanco** [comment]
I am expecting this will need to change with OpenCV3, because the current (Ubuntu 14.04) version of the repository is `2.4.8` (http://packages.ubuntu.com/trusty/libopencv-dev) and the most up-to-date (Ubuntu 16x) is `2.4.9` (https://launchpad.net/ubuntu/xenial/+package/libopencv-dev)
