### ISSUE TITLE
Keep OS X alive - pupil capture

### ISSUE THREAD

**Issue by hmvandermeulen** [pupil-labs/pupil#414]
Would it be possible to prevent OS X from going to sleep mode while recording instead of changing the OS power settings manually for the recording? It could have saved me from data loss unfortunately. Other software has the ability to keep the system alive during certain processes (eg. full screen video)

**Comment by papr** [comment]
Hey @hmvandermeulen, you can try `Caffeine` (https://itunes.apple.com/en/app/caffeine/id411246225?mt=12) as a temporal solution.

**Comment by mkassner** [comment]
@hmvandermeulen we will add a way of doing this. In the meantime I recommend changin power settings. BTW: if you need to close the lid use: https://github.com/integralpro/nosleep/releases

**Comment by papr** [comment]
With 8857db976, we support disabling idle sleep on Mac OS X 10.11 and higher.
