### ISSUE TITLE
Pupil Lab Server

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#418]
In my research I need to use Pupil Lab on a mini PC. However, all mini PC are not powerful enough to accommodate Pupil Lab processing requirements. So, I want to record (only record and no detection) and later upload my recordings to pupil lab for full processing. I know that I can pass the world and eye recorded videos to pupil labs but I noticed a delay in playing the eye recordings which causes an issue in calculating the right gaze position at the right time. The eye recorded video seems to always be one second longer than the world.

As you guys are pupil lab's gurus I would like to ask you for advice - How can I use pupil lab to just record the eye and world scenes and later pass them to Pupil lab to complete the process without any delay?

**Comment by papr** [comment]
Hey @mothman1!
The pupil detection is currently bound to the `eye` process. That means that you cannot record the eye video without pupil detection, yet. We will be releasing an Android app with the purpose of just recording video streams from Pupil headsets.

Although, this is a feature we are working on. In the future, `Pupil Player` will also include an `offline pupil detection` plugin.

**Comment by mkassner** [comment]
I have made an issue for the missing part: https://github.com/pupil-labs/pupil/issues/432
