### ISSUE TITLE
Scan_path climbing pupils bug

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#42]
Hey guys,

Please, take a look at the following pictures:

![screenshot from 2015-01-08 21 46 45](https://cloud.githubusercontent.com/assets/6511849/5673903/fb210210-9780-11e4-9779-65d5075f2267.png)
![screenshot from 2015-01-08 21 47 02](https://cloud.githubusercontent.com/assets/6511849/5673904/fb25b4d6-9780-11e4-90ce-bdf721362d42.png)
![screenshot from 2015-01-08 21 47 15](https://cloud.githubusercontent.com/assets/6511849/5673905/fb2b201a-9780-11e4-8214-215a047585f6.png)
![screenshot from 2015-01-08 21 47 30](https://cloud.githubusercontent.com/assets/6511849/5673906/fb354298-9780-11e4-935a-4572742f794b.png)
![screenshot from 2015-01-08 21 47 44](https://cloud.githubusercontent.com/assets/6511849/5673907/fb38f62c-9780-11e4-8dd3-6213eb2ae3fe.png)
![screenshot from 2015-01-08 21 48 02](https://cloud.githubusercontent.com/assets/6511849/5673908/fb3c55d8-9780-11e4-884c-8f1fcb166a91.png)
![screenshot from 2015-01-08 21 48 15](https://cloud.githubusercontent.com/assets/6511849/5673909/fb453da6-9780-11e4-87f4-671c4b156c82.png)
![screenshot from 2015-01-08 21 48 27](https://cloud.githubusercontent.com/assets/6511849/5673910/fb4a5c28-9780-11e4-87f4-fade82c7f35f.png)
![screenshot from 2015-01-08 21 48 40](https://cloud.githubusercontent.com/assets/6511849/5673911/fb4f4f94-9780-11e4-94bf-694ca45f32f2.png)
![screenshot from 2015-01-08 21 48 52](https://cloud.githubusercontent.com/assets/6511849/5673912/fb558404-9780-11e4-8240-6b410ee4a012.png)
![screenshot from 2015-01-08 21 49 04](https://cloud.githubusercontent.com/assets/6511849/5673913/fb5a86a2-9780-11e4-9a08-459d8f29a28e.png)
![screenshot from 2015-01-08 21 49 18](https://cloud.githubusercontent.com/assets/6511849/5673915/fb5f9516-9780-11e4-8cb8-5447a400d4d0.png)
![screenshot from 2015-01-08 21 49 31](https://cloud.githubusercontent.com/assets/6511849/5673916/fb65f9ec-9780-11e4-907a-c36f8887da3b.png)

Past pupils are climbing the image.

You can replicate this incremental behavior of past pupil positions by successive seeking the to an earlier frame.

EDIT 1: Player version 0.3.7.4, scan_path code unchanged.

**Comment by mkassner** [comment]
Do I understand correctly that you are using `scan path` with a 20 sec timeframe? I believe our 'pixel-sticking' is only stable when we have strong features and for a limited amount of frames.

If you want to accumulate gaze data over time a recommend using markers and save gaze data relative to registered surfaces as done in the plugin `offline marker tracker`

BTW Whats than nice visualisation in the seek bar?

**Comment by cpicanco** [comment]
Yep, 20s. But it is just a test. I am aware of the assumptions for a good "pixel sticking" (Optical Flow). What I did not understand was that in the first execution everything looks nice and pretty (for longer times too), but the more you seek for past frames (by draging and droping the blue circle), the higher will be pupil positions. Such a regular incremental behavior seems like a bug. Why everything works fine on the first run?

PS.: I am using your nice gl methods in the code for the experiment event visualization, will commit them soon:

>        def gl_display(self):
>            glMatrixMode(GL_PROJECTION)
>            glPushMatrix()
>            glLoadIdentity()
>            width,height = glfwGetWindowSize(glfwGetCurrentContext())
>            h_pad = self.padding / width
>            v_pad = self.padding / height
>            gluOrtho2D(-h_pad, 1 + h_pad, -v_pad, 1 + v_pad) # gl coord convention
>            glMatrixMode(GL_MODELVIEW)
>            glPushMatrix()
>            glLoadIdentity()
>        # Draw...............................................................................
>         
>            for pos_to_draw in self.pos_begin_trial:   
>                draw_gl_point((pos_to_draw, 0), size = 5, color = (.5, .5, .5, .5))
>                draw_gl_polyline( [(pos_to_draw,.05),(pos_to_draw,0)], color = (.5, .5, .5, .5))
>            for pos_to_draw in self.pos_first_response:
>                draw_gl_point((pos_to_draw, 0), size = 5, color = (.0, .0, .5, 1.))    
>                draw_gl_polyline( [(pos_to_draw,.025),(pos_to_draw,0)], color = (.0, .0, .7, 1.))
>            for pos_to_draw in self.pos_end_limited_hold:
>                draw_gl_point((pos_to_draw, 0), size = 5, color = (.5, .0, .0, 1.)) 
>                draw_gl_polyline( [(pos_to_draw,.025),(pos_to_draw,0)], color = (.7, .0, .0, 1.))
>        
>            for x in xrange(len(self.pos_first_response)):
>                draw_gl_polyline( [(self.pos_end_limited_hold[x],.025),(self.pos_first_response[x],.025)], color = (1., .5, .0, 1.))    
>        #End Draw...............................................................................
>            glMatrixMode(GL_PROJECTION)
>            glPopMatrix()
>            glMatrixMode(GL_MODELVIEW)
>            glPopMatrix()

**Comment by mkassner** [comment]
Yes this does seem to be a bug. I bet the plugin does not know how to deal with discontinuous frame sequences.

**Comment by cpicanco** [comment]
Hi @mkassner and @willpatera, and everyone.

I was not able to replicate this with the current version v4x (50da49758fa7cf711cb6e6626cd46902754c2246).

Even with 19s. :)

Long time makes easier to find good features to track.

**Comment by cpicanco** [comment]
![2015-03-11-192144_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6608354/f1c460ca-c824-11e4-843f-8184e013a118.png)
