### ISSUE TITLE
Surface tracker: gaze_on_srf not being published anymore

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#429]
Hi,
the surface tracker does not publish the normalized coordinates of the gaze in respect to the surface anymore. Right now, the message looks as follows:
```
surface {'name': 'screen2', 'timestamp': 1035067.369892373, 'm_from_screen': [[1.6239931466442163, 0.11208869313015046, -0.5401214135772228], [0.0666842672062444, 2.8398753319265566, -1.4524355443097376], [-0.13860814629205484, 0.24893115201544636, 1.0]], 'uid': '1465914957.39', 'm_to_screen': [[0.6952887711036143, -0.05354407469069683, 0.29777103662490867], [0.02924013416485871, 0.33644048012498534, 0.5044513344764712], [0.08909390741761086, -0.09117216123994194, 1.0]], 'camera_pose_3d': [[0.9931480288505554, 0.04084985330700874, 0.10949128121137619, 421.6736755371094], [-0.03263336047530174, -0.8027052283287048, 0.5954825282096863, -870.3245849609375], [-0.112214595079422, 0.5949753522872925, 0.7958719730377197, -981.7881469726562], [0.0, 0.0, 0.0, 1.0]]}
```

Previously the `gaze_on_srf` was published by pupil server, and one was able to get this information straight away. It would be great if this could be added again.

Thanks a lot,
Tobias
PS: Sorry for all the requests today, I am trying to get my code working with the new version of pupil and there were quite a few changes in v0.8 ..

**Comment by Tobias-Fischer** [comment]
Hi,
Thanks for the fix :).
There is a small typo and an unnecessary line:
```
diff --git a/pupil_src/shared_modules/surface_tracker.py b/pupil_src/shared_modules/surface_tracker.py
index 43c2803..dd09fe1 100644
--- a/pupil_src/shared_modules/surface_tracker.py
+++ b/pupil_src/shared_modules/surface_tracker.py
@@ -212,9 +212,8 @@ class Surface_Tracker(Plugin):
         for s in self.surfaces:
             if s.detected:
                 s.gaze_on_srf = []
-                for p in events.get('gaze',[]):
+                for p in events.get('gaze_positions',[]):
                     gp_on_s = tuple(s.img_to_ref_surface(np.array(p['norm_pos'])))
-                    p['realtime gaze on ' + s.name] = gp_on_s
                     s.gaze_on_srf.append(gp_on_s)
 
         events['surface'] = []
```

Also, now several gaze positions are published. Do you know which one the most recent one is? The first one or the last one?

Thanks, Tobi

**Comment by mkassner** [comment]
You can also go the other way around and listen to gaze data, if they are on a surface they will carry the `realime_gaze_on_srf_name` key.

**Comment by Tobias-Fischer** [comment]
Ahhh cool, thanks. However, I still think `gaze` should be changed in `gaze_positions`, otherwise no data is being published.

**Comment by Tobias-Fischer** [comment]
Hi @mkassner, the change from `gaze` to `gaze_positions` should still be done on the `master` branch.
Thanks, Tobias
