### ISSUE TITLE
Log pupil diameter by default

### ISSUE THREAD

**Issue by andyknownasabu** [pupil-labs/pupil#43]
Hi,

it seems at the moment pupil diameter is not logged by default. I suggest to do so given that this may be important for an increasing number of users and applications.

**Comment by mkassner** [comment]
Fully agreed. I think we now do this on v0.4

M

**Comment by fneitzel** [comment]
It would be great if the pupil diameter would be shown in the menu, again. It is missing in v0.4. There are just sliders for Pupil min. and Pupil max. in the 'Pupil Detector' Tab .

**Comment by willpatera** [comment]
I can add apparent pupil diameter as a readonly field in the Pupil Detector area of the GUI. It was omitted as I thought it might be more intuitive to see the values represented graphically as circles in the `Algorithm View.`

**Comment by mkassner** [comment]
I would advise agains using the GUI for this. It will force redraws on
every frame. Rather print the text onto the screen using pyfonstash.

Even better: Use a pyglui.graph for that. (could be hidden using a switch)

As for logging. We now write it into pupil-positions.py by default.

M

**Comment by willpatera** [comment]
Hi @fneitzel,

I added a pupil diameter graph as suggested by @mkassner that can be turned on/off in the Pupil Detector menu. At current the diameter graph only updates when confidence is > 0 and updates at the same rate as the FPS and CPU graph. Please have a look and let me know what you think. See changes in the code, and take a look at my commit notes here: https://github.com/pupil-labs/pupil/commit/8af47fe0dfff574a173e862a6fea784e10205782

Also, here's a screenshot that shows the pupil diameter graph in `Algorithm View` mode:

![screen shot 2015-02-16 at 11 19 57](https://cloud.githubusercontent.com/assets/1407224/6207174/db58c27c-b5cd-11e4-98b7-37430bc03010.png)

Let me know what you think.

**Comment by cpicanco** [comment]
For instance, what is the red/green circles in the bottom-left corner?

**Comment by willpatera** [comment]
Hi @cpicanco, 

The red circles represent pupil min and max diameter as set within the GUI. The green circle is the detected pupil diameter. This allows one to graphically/visually determine the min/max settings.

**Comment by cpicanco** [comment]
Nice. So the green circle should correspond to the current diameter as shown in the caption of the top right diameter graph? Why not just put the diameter in the center of the circles and overlay the history? For example: 
![hc_gimp_diameter](https://cloud.githubusercontent.com/assets/6511849/6235670/e2ed64b6-b6c2-11e4-9ff7-1031f530be33.png)

(dont know how to control the alpha on gimp but think the blue rectangle as the history)

**Comment by mkassner** [comment]
I think just putting the value in the center would be great and all thats
needed.

**Comment by cpicanco** [comment]
Would work for me. :)

**Comment by mkassner** [comment]
Done

**Comment by willpatera** [comment]
Screenshot of current implementation

![screen shot 2015-02-18 at 18 17 11](https://cloud.githubusercontent.com/assets/1407224/6246344/791849f6-b79a-11e4-8888-b711f59f5e11.png)

**Comment by cpicanco** [comment]
@mkassner @willpatera 
![screenshot from 2015-02-20 07 37 05](https://cloud.githubusercontent.com/assets/6511849/6284846/cca06b78-b8d3-11e4-874d-4b16ac98fda6.png)

**Comment by mkassner** [comment]
Should be fixed now.
