### ISSUE TITLE
World and Eye default fps.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#44]
Hi everyone, hereby I will argue against the 24-30 fps default. Why not 30-30 fps as a default?

Currently, the default for world camera is 24 fps while the eye is 30 fps. With out-of-the-box configurations (v0.3.9.6) and good pupil detection, these fps's defaults gives us approximately 1-2 gaze positions for each world frame. Indeed, this 24-30 default provides a nice visualization, for example, the vis_circle plugin generates 1-2 circles with a non appealing flickering behavior, and when color alpha blend is set to 255, no flicker at all.

On the other hand, a 30-30 fps gives us 0-1 gaze positions, hence increased flickering. Despite of it, a 30-30 fps would reduce data loss, as well as avoid one to make additional filtering in order to, for example a) decide which gaze point is the most precise point for a particular frame b) if precision is not a concern, decide if you take both points, the first, the second, a relative mean, and so on.

So, why not 30-30 fps as a default?

Best,
Rafael

**Comment by mkassner** [comment]
Hi Rafael,

We did this mostly to reduce cpu load, some users where struggling with
their hardware. I think we should make this setting session persistent.
So users set it once and leave it in the preferred state.

M

**Comment by cpicanco** [comment]
Sounds good Moritz!
