### ISSUE TITLE
Why is the start option binocular removed?

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#448]
Hi,
why is the starting parameter binocular removed?

I added this in main.py before the while True loop to add it again.

    if 'binocular' in sys.argv:
            print("Starting in Binocular!")
            for i in range(2):
                eye_id = i
                if not eyes_are_alive[eye_id].value:
                        Process(target=eye,
                                    name='eye%s'%eye_id,
                                    args=(timebase,
                                        eyes_are_alive[eye_id],
                                        ipc_pub_url,
                                        ipc_sub_url,
                                        ipc_push_url,
                                        user_dir,
                                        app_version,
                                        eye_id,
                                        video_sources['eye%s'%eye_id] )).start()**

**Comment by papr** [comment]
Dear @PolynomialDivision 
Sorry, that it took so long to respond. This parameter was a relic from the time when there was no possibilities to start the eye processes manually. Nowadays you are able to start and stop the eye processes dynamically and separate from each other using one of the following methods:

1. Send a notification with the topic `eye_process.should_start` or `eye_process.should_stop` and the eye id as the value for the notification dictionary entry `eye_id`. An example can be found in [`world.py`, line 225](https://github.com/pupil-labs/pupil/blob/master/pupil_src/capture/world.py#L225)

2. Use the main user interface to manually start and stop single eye processes (see screenshot below). This actually uses method 1. from above.

![screenshot 2016-08-29 14 31 32](https://cloud.githubusercontent.com/assets/168390/18051560/9f9ec02e-6df5-11e6-9aae-995ad9e7fdf6.png)

Capture will remember which eye processes were active during a session, store the corresponding information in the *capture session settings* and will try to activate the eye processes with the same settings on the next session start up. Therefore, you should only have to configure this setting once.

Does this answer your question sufficiently? If yes, please tell us so and we can close this issue.
