### ISSUE TITLE
v0.4.0 - Simple gaze mapper can't pickle mapping function

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#45]
When attempting to save session settings for plugins in [world.py](https://github.com/pupil-labs/pupil/blob/v0.4_restruct/pupil_src/capture/world.py#L371) after a successful calibration with Screen Marker Calibration, I get a `PicklingError : Can't pickle <type 'function'>` and session settings for world is therefore not saved. 

It appears that this bug originates in the Simple_Gaze_Mapper plugin [get_init_dict](https://github.com/pupil-labs/pupil/blob/v0.4_restruct/pupil_src/capture/calibration_routines/gaze_mappers.py#L49-L50) because of passing a function `map_fn` which is not pickelable.

**Comment by willpatera** [comment]
If we still want to go the route of saving the map_fn, then we could use Python's built-in [marshal](https://docs.python.org/2/library/marshal.html) module to serialize the `map_fn`. 

Another project that looks intriguing is called [Dill](http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill) that allows one to pickle functions, lambdas, and more. However, this would be an extra dependency -- and is probably not necessary.

**Comment by willpatera** [comment]
Added the `dill` module in v0.4.0 branch to pickle the `map_fn` at this commit: https://github.com/pupil-labs/pupil/commit/027290051863745afaa31335af37a49b8745094f

This adds a dependency to the project, which is not so desirable, but maintains the capacity to save the mapping function. 

Leaving this issue open because the question remains: Is it required to to save the mapping function?

**Comment by mkassner** [comment]
Let's not do it like that. Rather pass mapping fn params to the class
instead. Or make the mapping fn pickalabe.

M

**Comment by willpatera** [comment]
Removed `dill` module and am now saving the params used by `make_map_function`. See changes at this commit: https://github.com/pupil-labs/pupil/commit/75eeae0cb5817b682423ccbe64626db079566452
