### ISSUE TITLE
Inquiry Regarding real_world_size

### ISSUE THREAD

**Issue by Saftophobia** [pupil-labs/pupil#450]
I wanted to know what scale and measure should I use for the real_world_size when capturing a surface.

It's not very clear in https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/reference_surface.py#L289 . 

Is it mm,cm, or m? and Is it the marker width/height ... or the whole surface width/height? 

Thanks!

**Comment by cpicanco** [comment]
Hi, you could use any measure you want. The important stuff to keep in mind is:

- Try to keep the same aspect ratio of the real object
- The absolute value will end up in a pixel matrix (for example, 1280 cm X 764 cm will give you a 1280 px X 764 px matrix)
