### ISSUE TITLE
error when trying to make accuracy test

### ISSUE THREAD

**Issue by yemu** [pupil-labs/pupil#451]
Hi,

after installing new version of pupil capture (0.8.1) on a fresh Ubuntu 16.04, I'm unable to run "Accuracy Test" after calibration, i get this error:

"AttributeError: 'Global_Container' object has no attribute 'pupil_confidence_threshhold',

and World window crashes.

Same thing happens on a Mac with fresh install.

I'd be glad for any suggestions.

Cezary

**Comment by papr** [comment]
Hello @yemu.

We moved the `pupil_confidence_threshhold ` property from the global container to the calibration plugin itself. Unfortunately we did not apply this change to all calibration plugins (including "Accuracy Test").

Thanks for pointing this out. It has been fixed. Please pull the newest version from `master` and try it again. Let us know if there are any other problems. :)

**Comment by cpicanco** [comment]
Accuracy test is an important feature. A bundle release would be great.

**Comment by mkassner** [comment]
New release with this change: https://github.com/pupil-labs/pupil/releases/tag/v0.8.4
