### ISSUE TITLE
[question] Fixation detector algorithm

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#457]
Hi,

What reference or set of references should I use for the fixation detector algorithm? Is it new/original in some degree?

[Salvucci & Goldberg (2000)](http://dl.acm.org/citation.cfm?doid=355017.355028) will do?

**Comment by willpatera** [comment]
@cpicanco -- yes Salvucci & Goldberg's publication should be cited and is referred to in the code comments. You might also want to take a look at [Blignaut, Fixation identification: The optimum threshold for a dispersion algorithm, 2009](http://link.springer.com/article/10.3758/APP.71.4.881)

**Comment by cpicanco** [comment]
I am afraid It isn't referred in the code comments (except you had Goldberg's et al in mind, i. e., Goldberg and collaborators).

Can you confirm if the Pupil implementation applies the "optimum threshold" notion as described by Blignaut or if the implementation allow optimum threshold inquiries?

**Comment by papr** [comment]
#460 does not use an optimum threshold. The dispersion threshold is settable by the user.
