### ISSUE TITLE
v0.4.x Screenmarker Calibration not cancelable

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#46]
This is an issue if you use a touchscreen without a keyboard.
It is not possible to press 'escape'. 

You have to unplug the Pupil from the USB and restart PupilCapture.

**Comment by willpatera** [comment]
Good point. This calibration routine should be more 'touch friendly.'

I am working on Screen Marker Calibration plugin for v0.4.0 currently, and will implement a 'touch friendly' way to cancel calibration from the calibration window. I will leave this issue open until it is implemented.

**Comment by mkassner** [comment]
we will add a way to exit. basically touch anywhere and hold to exit.

**Comment by mkassner** [comment]
Done
