### ISSUE TITLE
Thumbnail Grid Icons / Font Icons

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#461]
UI thumbnails will not display a letter but a 10-by-10 binary grid instead. This grid can be defined as a Python multi-line string. It will be `strip()`ed before converting it into a texture. This is done once.

```python
icon = """
xxx    xxx
xxx    xxx
xxx    xxx
xxx    xxx
xxx    xxx
xxx    xxx
xxx    xxx
xxx    xxx
xxx    xxx
"""

icon = icon.strip()
convert_icon_string_to_texture(icon)
```

This allows plugins to have custom thumbnail icon while keeping control over the rendered appearance. Kudos to @mkassner for the idea.

**Comment by papr** [comment]
@willpatera suggested to use an icon font instead of the grid. The suggested icon fonts were:

- https://design.google.com/icons/
- http://fontawesome.io/icons/

**Comment by snleu** [comment]
I have added a few lines to pyglui such that a button can be given an icon label (in unicode), the default is still a letter ie r button for record. However, fontstash needs a string and unicode creates an error. I'll have to find a way of getting around this. Any suggestions?

**Comment by papr** [comment]
As @snleu and I found out, fontstash supports utf8 decoding. [source](https://github.com/akrinke/Font-Stash/blob/8e9fd2f2d946deb6d4c3842579003729b07451e5/fontstash.c#L686)

@snleu will look into adding a unicode compatible python binding tomorrow.

**Comment by mkassner** [comment]
we have gone with an icon font. So this can be closed.

**Comment by papr** [comment]
Reference pull requests:
- pupil-labs/pupil#467
- pupil-labs/pyglui#39
