### ISSUE TITLE
Simplify Pupil Groups plugin

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#464]
There is no necessity for a background loop. Fetching Zyre events can be done on the main thread. See [`ndsi.network.handle_event()`](https://github.com/papr/pyndsi/blob/master/ndsi/network.pyx#L50) and `has_events()`. It can be called automatically in `update()`.

**Comment by cpicanco** [comment]
Would be awesome to integrate my pascal program to pupil sync. Unfortunately, Zyre does not have pascal bindings. So.. Is there any alternative? I would appreciate any comments on the matter!

**Comment by mkassner** [comment]
We cant do this because we need instant forwarding of messages.

**Comment by papr** [comment]
Messages are forwarded directly. Pyre has a [`ZActor` in place](https://github.com/zeromq/pyre/blob/master/pyre/pyre.py#L44) that sends messages in the background. E.g.: [pyre_node.py#L189](https://github.com/zeromq/pyre/blob/master/pyre/pyre_node.py#L189)

**Comment by mkassner** [comment]
If we use the update loop we would still have the problem of incoming messages being dealt with at the world camera refresh rate, no? that means a zyre message arrives, is queued and waits at worst for 1/30s until it is forwarded as a notification on the IPC. Or am I missing something here?

**Comment by papr** [comment]
I misread the _forwarding_ part of your previous post. I thought you were talking outgoing messages. I forgot about the responsibility of forwarding incoming messages...
