### ISSUE TITLE
blink detector

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#465]
When we have binocular data we can look at confidence over time as a signal. Sharp drops in both left and right can be a good indicator for a blink event.

calculate a sliding average of the first derivative of the confidence per eye
look for a negative spike in the signal that appears in both eyes simultaneously.

**Comment by mkassner** [comment]
Made an edit to the issue above.

**Comment by cpicanco** [comment]
May I ask if the blink detector will be a binocular only functionality?

**Comment by papr** [comment]
The current implementation idea does only make sense with binocular data. The results would be too noisy in case of monocular data. Each confidence loss would result in a blink classification. In case of the binocular version we can at least correlate it with the other eye.

The right way to do blink detection is to implement eye lid detection. This would allow precise blink predictions and maybe even classification into further subcategories.
