### ISSUE TITLE
Improvement of closest_matches_monocular/binocular?

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#469]
Hi,
I'm thinking about options to improve the calibration.
So that's why I looked at your closest_matches_monocular/binocular function.
As I see you are selecting the points to calibrate only by the timestamp. I think it would be more precisely if you would take more Pupil-Samples around this timestamp and caculate the mean or variance or something like this. In which frequency are you saving Pupil-Samples? Currently it's possible that outliers disturb the calibration?
So what's your opinion on this? :)

**Comment by papr** [comment]
Hey @PolynomialDivision!

The  `closest_matches_monocular/binocular` function is part of the gaze mapper as method of merging the two separate eye data streams into the world event loop. Nothing more. It is not supposed to make assumptions about the data.

These assumptions should be made (if made at all) by the calibration procedure. The 2d polynomial calibration procedure already filters outliers: [`calibrate.py#L34`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/calibrate.py#L34). The 3d procedure does that implicitly during the bundle adjustment.

The moment #460 provides online fixation detection. This will be used to improve calibration by providing outlier-free data to the calibration procedure. The idea here is that the calibration has to constraints:
1. a fixation happend
2. the calibration marker had a stable position during the fixation

This will (hopefully) lead to more precise and faster calibrations.

**Comment by PolynomialDivision** [comment]
Thanks for your explanations :)
