### ISSUE TITLE
Videos in PupilPlayer just with Spacebar startable?

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#47]
How to start and stop recordings if there is no keyboard available?

**Comment by willpatera** [comment]
Yes, this is an important enhancement so that Player can be 'touch friendly.' 

We can implement a play/pause button, similar to the hotkey 'thumb' buttons in Pupil Capture v0.4.0. There is lots of work to be done on Pupil Player for the v0.4.0 release :)

**Comment by mkassner** [comment]
Fixed in v0.4 branch
