### ISSUE TITLE
[discussion] Pupil Player as a learning tool

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#472]
The point here is to take advantage of the plugin system (specially the update method) and increase the chances of people using Pupil Player as a standard way to explore and learn on computer vision. Some points for your consideration:

1. one may benefit from being able to load static images, not only videos.
2. right now one needs to download huge (300mb +) data just to take a glance at the Player or do a fake recording, and so on. Being able to promptly generate some random eye tracking data or to have a built in example dataset would be great.

PS.:

Some time ago I was using Pupil for learning the basics on OpenCV and computer vision. To this end, I have written a plugin to explore threshhold functions.

**Comment by cpicanco** [comment]
PS. 2: The sample dataset currently available at the site is 30mb. :sweat_smile:

**Comment by papr** [comment]
PS. 1. This could be easily integrated into fake source

**Comment by cpicanco** [comment]
Is it possible to pass an image to the fake source?

**Comment by papr** [comment]
Not yet. Currently it generates a random rgb image. This could be replaced with any other image from your hard disk. I will have a look at this on Monday.

**Comment by papr** [comment]
Hey @cpicanco 
We feel like `Fake_Source` should stay what it is: A fallback mechanism. We suggest to use `File Source` if you want to use synthetic content.
