### ISSUE TITLE
Unable to use two eyetrackers with pupil capture

### ISSUE THREAD

**Issue by SGBon** [pupil-labs/pupil#476]
I've got a pair of pupil eye trackers, I can run one fine, I have trouble running two. My setup is I run two instances of pupil capture, one for each eyetracker, pupil can detect all cameras but the final camera it detects always crashes (usually the eye camera of the second tracker). If I switch one of the captures to a fake capture, I can then run the other camera, so at most I can only have 3 cameras running.

My console output is as follows
```
eye0 - [INFO] video_capture.uvc_capture: Found device.Integrated Camera.
Estimated / selected altsetting bandwith : 458 / 1936. 
eye0 - [ERROR] eye: Capture from Camera Failed. Stopping.
eye0 - [INFO] eye: Process shutting down.
```
I am running from the source on Fedora 24 if that helps

**Comment by mkassner** [comment]
Hi,

make sure that each eye tracker is connected on a separate usb controller.
(Often one per laptop side).

Best,

M

**Comment by cpicanco** [comment]
Also, make sure that your laptop/computer have two usb controllers (Often they do).

**Comment by mkassner** [comment]
I ll close this
