### ISSUE TITLE
macOS `v10.12` Sierra - no patch in version string. only `10.12` causes `os_utils` error 

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#477]
### Overview
Just updated to `macOs 10.12` *Sierra*. This version contains no patch in the version string.

```python
print platform.mac_ver()
('10.12', ('', '', ''), 'x86_64')
```

### Problem
Current implementation of `os_utils` expects version strings to follow the pattern `major.minor.patch`. When trying to unpack version string that only contains `major` and `minor` to 3 variables, `ValueError` is thrown, and Pupil Capture will fail to start. 

This happens on [`os_utils.py L20`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/os_utils.py#L20)

```python
mac_version = platform.mac_ver()
mac_major,mac_minor,mac_patch = map(int,mac_version[0].split('.'))
ValueError: need more than 2 values to unpack
``` 

### Proposed Solution
- Wrap this in `try... except` and log the error 
- parse the version string in a more elegant manner - we can lift a snippet of code from [distutils.version.py](http://svn.python.org/projects/python/tags/r32rc1/Lib/distutils/version.py) - like so:

```python
# use regex to parse the version string
import re
import platform

mac_version = platform.mac_ver()
mac_version_str = mac_version[0]

version_re = re.compile(r'^(\d+) \. (\d+) (\. (\d+))? ([ab](\d+))?$', re.VERBOSE)
(major, minor, patch, prerelease, prerelease_num) = match.group(1,2,4,5,6)
```

For version string `10.12` , `prerelease = None`

**Comment by mkassner** [comment]
@willpatera  where did you lift the code snippet from?

**Comment by willpatera** [comment]
@mkassner - see link above (no line numbers in the linked code of `distutils.version.py`)

**Comment by mkassner** [comment]
Ah thanks i should have searched the file!

**Comment by mkassner** [comment]
@willpatera  can you test this? https://github.com/pupil-labs/pupil/pull/478

**Comment by mkassner** [comment]
Done
