### ISSUE TITLE
macOS `v10.12` Sierra - Pupil Capture fails to run and build from source

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#481]
## Overview
- Pupil Capture bundled application fails to run on macOS `v10.12` _Sierra_  🙅 
- Pupil Capture running from source fails to build `c++` libs on macOS `v10.12` _Sierra_  🙅 
- Pupil Player is working 👍 

### Possible reasons
- `QTKit` and `OpenCV` - Apple has removed most of `QTKit` components in macOS `10.12` (with command line tools for `10.12` or Xcode `v8.x`).  On macOS, `OpenCV 2.x` depends on `QTKit` and therefore `OpenCV 2.x` is broken. Pupil Capture depends heavily on `OpenCV` and therefore critical components are not functional and leads to a crash. 
  - There are a number of open issues that document this problem on OpenCV's repo and the `brew` repo. Here is one for reference - https://github.com/opencv/opencv/issues/6913
- `multiprocessing` `forking_enable` and `glfw3` 

## Possible Solutions
Transition to `OpenCV 3.x` and abandon support for `OpenCV 2.x` - some of the work has already been done by @Tobias-Fischer -- see #329 -- I am currently working on transitioning to OpenCV3 based on @Tobias-Fischer's prior work in this [fork](https://github.com/willpatera/pupil)

### Building OpenCV 3 with `brew`
Right now the `stable` version of `opencv3` on brew will fail. But, devs are hard at work and have already resolved the issue in the master branch of opencv3 for brew. You can successfully install `opencv` with:
 
`brew install opencv3 --HEAD --with-contrib`

**Comment by mkassner** [comment]
Turns out this was not related to OpenCV but to glfw and forking. Latest bundle fixed this issue: `v0.8.5`
