### ISSUE TITLE
LICENSE.md vs COPYING.md

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#482]
This is a response to #403 and reaction to a [new github feature](https://github.com/blog/2252-license-now-displayed-on-repository-overview) to display licenses.

I understand that it is convention/recommended to name the GPL file `COPYING.md` and the `LGPL` as `COPYING.lesser.md` but it would be nice to leverage github's features to display the license in the repo overview. I believe this requires us to have a file named `LICENSE` in top level of the repo.

**Comment by cpicanco** [comment]
Redundancy is an alternative? The LICENSE file could have the desired license template to show on GitHub.

**Comment by willpatera** [comment]
@cpicanco - I would prefer to stick with one or the other but not both. It makes sense to conform to [GNU's documentation](https://www.gnu.org/licenses/gpl-howto.html). I guess github's  [Licensee](https://github.com/benbalter/licensee) should be more flexible and support GNU's standards instead of forcing all repos to use the filename _LICENSE_ in order to access this feature.

**Comment by willpatera** [comment]
Looks like COPYING as a file name is already supported in github's [Licensee source](https://github.com/benbalter/licensee/blob/dc079ede1a71b593a1b29f9ffa55017f1464148c/lib/licensee/project_files/license_file.rb#L24) - I'm closing this issue.

**Comment by cpicanco** [comment]
I would say this. Tested here: https://github.com/cpicanco/stimulus_control

**Comment by cpicanco** [comment]
But I think you must choose a template.

**Comment by willpatera** [comment]
Or maybe the markdown in our file is throwing off the script. Because the filename patterns seem to be supported.

**Comment by cpicanco** [comment]
Hum... I am testing this write now. Give me some minutes.

**Comment by cpicanco** [comment]
1. The `*.md` ext. does not prevented showing github license icon when `COPYING` was used as a filename.
2. The `*.md` ext. *does prevented* the icon when `COPYING.LESSER` was used as a filename.

Tested here
https://github.com/cpicanco/player_plugins/blob/master/COPYING.md

**Comment by willpatera** [comment]
@cpicanco - nice discovery 👍 

@mkassner - I think we should also consider removing the `license.txt` file and the `/license` directory since we now include the entire `GPLv3` and `LGPLv3` in the repo. Some of the text that is contained within the `license.txt` file could be moved into `README`. 

`update_license_header.py could be moved out of the `license` dir and become top level or moved into or put into a new folder with a name like `repo_utils` or a `.folder` - as it is really not essential to the repo for those aside from maintainers.

**Comment by mkassner** [comment]
sounds good.

**Comment by willpatera** [comment]
I have made PR #492 - I will close this issue and we can migrate discussion directly to the PR.
