### ISSUE TITLE
Export annotation file

### ISSUE THREAD

**Issue by uncflorians** [pupil-labs/pupil#484]
Is there any possible way to export the annotation informations? In order to imort them into excel or matlab?

**Comment by papr** [comment]
Hello @uncflorians!
Annotations are stored in your in the `annotations` file in your recording directory. The data is stored as pickled Python list. In case, you created annotations in Capture but do not see such file, you can run the Annotation plugin in Player which will generate it.

Once you have this file, you can use the following script to export it to csv:

https://gist.github.com/papr/6a9f0517534811e6844a27a1909483e2

This should be built directly into the Player Annotations plugin though. I will look into that possibility.

**Comment by snleu** [comment]
Export to csv has been added to the player annotations plugin, pull request #487
