### ISSUE TITLE
v0.4.x WorldCamMenu - Recorder: Set path + Session name

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#49]
'Path to Recrodings' and 'Recording Session Name' is not correct changeable:

1.) Missing visual feedback (enhancement?)
2.) I can add new chars, but not delete the default input

**Comment by willpatera** [comment]
I just checked this in MacOS (issue should not be machine specific so did not test everywhere -- unless this has to do with GLFW -- You are using Ubuntu?) 
  - `Path to Recordings` and `Recording Session Name` are able to be changed. 
  - `Path to Recordings` must be supplied with a valid *existing* directory. If you do not supply a valid directory, then the text will revert to the previous valid directory or default directory. You must press "enter" or "return" to confirm the new string. 
  - `Recording Session Name` can be anything you like, does *not* need to be an existing directory.
  - The default input can be deleted, but can not be left blank. 

I agree that changes need to be made here. I would suggest:
  - Ideal scenario - drag & drop a folder into the world window, the path gets copied to recording dir. GLFW 3.1 has drag & drop as well as copy and paste. We would need to update our GLFW bindings. This might also help make the interface more "touch friendly." 
  - Short term fix - visual feedback (as suggested) either an info text string with explanation gets added when invalid input is added, or the text box box becomes red to demonstrate invalid input.

There are other issues with text input that need to be resolved, I'll note them here, but should be migrated to [pyglui](https://github.com/pupil-labs/pyglui):
  - Double click to highlight all text in the textfield. 
  - Save text when focus leaves the text input box. We don't always want to have to be pressing "enter."
  - Delete selected text on new key other than delete. Currently text is just added at at end of selection.

**Comment by mkassner** [comment]
Maybe a bit confusing: to confirm the input click on the text or hit `enter` to abort click anywhere else.

**Comment by mkassner** [comment]
Behaviour of text input should now be more intuitive. But there are issues with key constants on Linux it seems

**Comment by mkassner** [comment]
This was a bug in Pyglui. Its fixed now
