### ISSUE TITLE
Pupil Player - Make fixation detector on by default

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil#493]
In release v0.8.5 when the plugin is selected, 2D and 3D fixation detector`is off by default. I suggest making it be on by default.

Took bit of time to realize that i had to activate it in the plugin. So this might be a problem for new users using this plugin also.

**Comment by papr** [comment]
@nathakits @mkassner Fixation detection is currently run in the main thread and might slow down Player startup time significantly (depending on recording length) if turned on by default.

Should we still turn it on by default?

**Comment by papr** [comment]
@mkassner and I decided to let it turned off for Player because of the issue mentioned above. But we will turn it on by default for Capture. See #496

**Comment by willpatera** [comment]
@papr if off by default, then documentation must be improved.

**Comment by papr** [comment]
Agree. Do you think that an wiki entry is enough?

**Comment by willpatera** [comment]
@papr - yes, we should document this in the wiki with screenshot of the GUI. Another thought - why not run the plugin in a separate process?

**Comment by papr** [comment]
@willpatera The implementation in the main thread happend mainly out of convenience. Ideally, there is a common api for Player plugins to calculate stuff in the background, etc. See #462 

I will start by documenting it in the wiki. Currently, it behaves the same way as the old fixation detector did. One had to load it manually as well.

**Comment by willpatera** [comment]
Sounds good thanks @papr
