### ISSUE TITLE
add scanpath visualtion to surface tracker

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#499]
on top of each surface similar to heatmap looking like this:

https://www.google.de/search?q=scanpath&source=lnms&tbm=isch&sa=X&ved=0ahUKEwih0-Dsu9fPAhUqDsAKHaVvDHgQ_AUICCgB&biw=1246&bih=747

**Comment by papr** [comment]
Instead of integrating this functionality directly into Player, we have created a [tutorial](https://github.com/pupil-labs/pupil-tutorials/blob/master/03_visualize_scan_path_on_surface.ipynb) that implements this functionality based on the surface tracker export files.
