### ISSUE TITLE
Cannot import name GLFW_PRESS

### ISSUE THREAD

**Issue by JosephP91** [pupil-labs/pupil#502]
After following the OSX install instructions (without errors), rI get the following error running python main.py, in the pupil_src directory:

ImportError: cannot import name GLFW_PRESS

I have macOS Sierra.

**Comment by mkassner** [comment]
Could you post your version of GLFW?

**Comment by JosephP91** [comment]
Hi, don't worry, problem solved. I was having a permission problem. Thank you!

**Comment by shahramdj** [comment]
Why do you close a topic without posting the solution? I am having the same problem but I cannot fix it :/

**Comment by JosephP91** [comment]
Sorry @shahramdj, competely forgot XD
I had chown to my user my /usr/local directory. Hope it can help you!

**Comment by shahramdj** [comment]
My problem was not solved by chown to my user. I just inserted the address of the libglfw.3.3.dylib manually into the glfw.py file in the shared module folder and it worked for me. I guess the library finder function in the glfw.py code cannot find the glfw library for some reason.

**Comment by PolynomialDivision** [comment]
This error can appear under windows too. I think the problem is that you have glfw python library installed.

To fix this just uninstall glfw python...
To be sure:

    python -m pip uninstall glfw
