### ISSUE TITLE
About OGAMA data import assistant.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#503]
Hi, I was exploring OGAMA data import assistant and would like to document the process. Here are some notes.
### What is OGAMA?

[OGAMA](http://www.ogama.net/) is an open source software (windows only) for designing, presentation, recording and analysis of eye tracking experiments. 
### Is it possible to import PUPIL data into OGAMA?

Yes, with limitations. OGAMA will not run the data interactively with video files like in PUPIL Player. OGAMA can run the data by means of static pictures (each picture representing a "trial").
### What is the file format expected by OGAMA's data import assistant?
1. It expects a single highly redundant input file (tsv, csv, txt, ... ).
2. The user, optionally, can use a settings (.xml) file to automate the process of importing specific files (for example a settings file to import data generated by the [ASL504 device](http://www.ogama.net/sites/default/files/downloads/asl504.ois)). 
3. The redundant file **must not** have duplicated timestamps and have at least one column containing either pupil diameter or gaze position or mouse position data;
4. The file to be imported may include columns for;
   - time
   - gaze x
   - gaze y
   - pupil diameter x
   - pupil diameter y
   - mouse position x
   - mouse position y
   - name of participants
   - trial ID
   - trial category
   - trials presentation sequence
   - image associated with the trial
5. Optionally, the user can import/export Areas of Interest from/to tab delimited files (.txt). This file have the following columns:
   - ID
   - TrialID
   - SlideNr
   - ShapeName
   - ShapeType
   - ShapeNumPts
   - ShapePts
   - ShapeGroup
   - AOI Area Size %
### Is there something that OGAMA will not do but PUPIL will do?
1. 3d surfaces and homographic transformations.
2. Fiducial marker tracking.

### Why OGAMA?
1. To take advantage of data analysis tools that Pupil Player does not have (yet?). It includes, for example:
   - scanpath tools (Levenshtein, 1966; difference/edit distance);
   - tools to analyze data of groups of participants;
   - area of interest drawing tools including circles and custom shapes
   - pupil diameter tools

---

The following is not related to the data import assistant
### Is it possible to use PUPIL Pro eye tracker with OGAMA capture module (taking advantage of the designing, presentation and capturing tools)?

As far as I know, yes, by means of the  GazeTracker or ITU Haytham integrations. Is also possible to adapt the PUPIL world camera (with some external IR lights) to do remote eye tracking by means of the GazeTracker integration.

**Comment by willpatera** [comment]
@cpicanco - I am happy to see this issue and would love to see more integrations with existing tools with Pupil. 

I think at some point you might want to consider moving these notes to the wiki so that the community can have a persistent reference point and can collectively edit the notes. Ideally this would be in the form of a concise guide with steps listed - e.g. `Using Pupil with OGAMA` or `Import Pupil Data to Ogama`. 

Question - do all of the methods listed in the `why OGAMA` section depend on the participant not moving their head? I ask because defining AOIs when the stimulus and/or participant is moving would be challenging without markers in the scene or other detection methods. This question also applies to multi-participant analysis and scanpath tools.

**Comment by cpicanco** [comment]
Hi @willpatera , thank you for your kind words. For sure, when this notes gets more mature, I can move them to the wiki.

As far as I am undertanding the system, no, it does not depends on participants with static heads. But I would say that it is not intuitive, and as noted. Please, let me explain why.

OGAMA allows only static images to be imported, not videos. Each image can be associated with a `trial ID`, in turn each `trial ID` can be associated with one or more AOI's. In PUPIL we would say that each world frame is associated with a `surface`, and a set of frames may be associated to PUPIL annotations or custom annotations to indicate beginnings and endings of `trials` in a PUPIL recording. Static images may be redundant in OGAMA, i.e., be the same for different timestamps, or non redundant, be different up to the limit of timestamps. So, a video may be "simulated" if a different image is associated to each timestamp. This means that the PUPIL surfaces can be imported into OGAMA, as each frame can have its own set of AOI (surfaces). However, as noted, no perspective transformation could be done inside OGAMA. It complicates things for the scanpath auto image segmentation tools, but, in principle, does not prevent the analytical tools that requires only a valid segmentation.

An alternative to use the scanpath autosegmentation tools  is to do the perpective transformation in pupil. Importing the surface data is also possible, and I would say recommendend in some cases.

**Comment by papr** [comment]
closed because issue is stale

**Comment by phauly** [comment]
I'm interested in this as well!

**Comment by cpicanco** [comment]
Hi, @phauly , I have lost interest in OGAMA (at least for now). Feel free to contribute to this issue!
