### ISSUE TITLE
How to export videos with user added visualization plugins?

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#507]
How to export videos with user added visualization plugins? I am trying to do this right now.

**Comment by papr** [comment]
Hey @cpicanco. Sorry for the delayed answer!

There are two steps needed for this to work.

1. Your plugin needs to implement `get_init_dict()` (called in [video_export_launcher.py#L144](https://github.com/pupil-labs/pupil/blob/master/pupil_src/player/video_export_launcher.py#L144))
2. We need to extend the import process of the exporter to include user plugins. I will be working on that.

**Comment by cpicanco** [comment]
Number one is done [here](https://github.com/cpicanco/player_plugins/blob/bc7c65f85f3f1955adfef008066a6041cb905a73/vis_circle_on_contours.py#L328).

**Comment by willpatera** [comment]
See #513
