### ISSUE TITLE
v0.4.x Request for old 'Calibration Debug View' ?

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#51]
In version 0.3.x has been a checkbox in the WorldCamMenu for an overlay that showed the calibration points relating to the screensize. So you could see, in which area the calibration was good and bad. 

I can't find that in 0.4. Is it possible to reimplement it?

**Comment by mkassner** [comment]
Yes. We will do that!

**Comment by mkassner** [comment]
Done
