### ISSUE TITLE
Pupil Player `v0.8.6` - `vis_light_points` crashes app

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#511]
## Observed Behavior
When using Pupil Player app bundle `v0.8.6`, loading `vis_light_points` will lead to an application crash on macOS (10.12.1) and Ubuntu (16.04 LTS). No log messages in `player.log` after `plugin - INFO - Loaded: Vis_Light_Points`

**Comment by papr** [comment]
Fixed with 2067c58
