### ISSUE TITLE
Export File Size

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#516]
How can I export world video into a much smaller video size using Export plugin? I mean, I have 18 minutes video (4.5 GB) and I would like to export all of it but onto a video that do not exceed 500 MB, is this possible? Currently when I export the file I get a file of 2 GB.

**Comment by papr** [comment]
Hello @mothman1 
Currently, there is no way to change the export file size in Pupil Player. But you can use
>`ffmpeg -i input_file.mp4 output_file.mp4`

to convert your exported video file from `mpeg4` to `h264`.

**Comment by mothman1** [comment]
fair enough. Thanks
