### ISSUE TITLE
No module named detector_3d on macos Sierra

### ISSUE THREAD

**Issue by kevinbai0** [pupil-labs/pupil#522]
I am running pupil from source. I installed everything per instructions. When I run python main.py, I get this many errors. The last one is:
File "/Users/kbai/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 19, in <module> from detector_3d import Detector_3D
ImportError: No module named detector_3d

I am not sure how to fix this problem. Any help would be greatly appreciated.

**Comment by willpatera** [comment]
Hi @kevinbai0 can you make a gist with the full output of the terminal when you run `python main.py` and link it here? If `detector_3d` fails to build, then it is likely an issue related to dependencies required for the build process: `ceres-solver` and/or `eigen`

**Comment by willpatera** [comment]
@kevinbai0 - can you also list what version of `eigen` is installed? You can find this with:

`brew info eigen`

and the version of `ceres-solver`:

`brew info ceres-solver`

**Comment by kevinbai0** [comment]
Hi @willpatera My version of `ceres-solver` is v1.11.0 and `eigen` is v3.3.0

Here is the link to the output from terminal: [https://gist.github.com/kevinbai0/dba10aa417d3d18ae3cf219acb22a554](url)

**Comment by willpatera** [comment]
Hi @kevinbai0 

I was able to replicate your issue on macOS `10.12.1`with `eigen v3.3.0`. 

It appears that there is a dependency issue between `ceres-solver` and `eigen v3.3.0`. 

I was able to resolve build issues with the following workaround:

`brew install ceres-solver --devel`

Please give this a try. I will close this issue for now, as it appears to be related directly to `ceres-solver` and `eigen` and not pupil source code.

**Comment by kevinbai0** [comment]
Thank you, it is now working now. 
In the file: 
`pupil/pupil_src/shared_modules/video_capture/fake_backend.py`, an error is thrown on line 161: 

```
@property
    def frame_rates(self):
        return range(30,60 90,120)
```

I deleted one of the values and it is now working, not sure if it is a mistake?

**Comment by kevinbai0** [comment]
@willpatera Thank you, it is now working now. 
In the file: 
`pupil/pupil_src/shared_modules/video_capture/fake_backend.py`, an error is thrown on line 161:

```
@property
    def frame_rates(self):
        return range(30,60 90,120)
```
I deleted one of the values in range and it is now working, not sure if it is a mistake?
