### ISSUE TITLE
Extension name warnings

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#523]
When I'm starting pupil I get this warnings:

> Warning: Extension name 'detector_2d' does not match fully qualified name 'pupil_detectors.detector_2d' of 'detector_2d.pyx'
> Warning: Extension name 'detector_3d' does not match fully qualified name 'pupil_detectors.detector_3d' of 'detector_3d.pyx'
> running build_ext
> Warning: Extension name 'calibration_methods' does not match fully qualified name 'calibration_routines.optimization_calibration.calibration_methods' of 'calibration_methods.pyx'

It doesn't have any effect while runtime but I'm just wondering why I get this errors.

Version:
Newest (17. November 2016)

OS:
Lubuntu 16.10 (64-Bit)

**Comment by willpatera** [comment]
@PolynomialDivision - what version of `cython` and what version of `python` are you using?

**Comment by mkassner** [comment]
I m seeing the same of Ubuntu 16.04.

It doesn't break anything but I m also curious what they mean and how they
can be prevented.

M

**Comment by PolynomialDivision** [comment]
The versions:

    Python 2.7.12+
    Cython==0.25.1

**Comment by swilmet-ucl** [comment]
Since this cython commit:
https://github.com/cython/cython/commit/9f9174b206088d2c993f53679128515be8fd675a

"Warn about module name missmatch"

**Comment by papr** [comment]
This issue needs some low-priority attention. This occurs on macOS under Python 3 as well.

**Comment by papr** [comment]
Fixed with c2b49537f3cdafa6e061b9d0fdd4f4e7cf2b9d39 in #601
