### ISSUE TITLE
No module named detector_2d

### ISSUE THREAD

**Issue by Tank1400** [pupil-labs/pupil#527]
Hello,
I want to launch pupil pro, but it can't launch.
I installed dependencies like this instruction(https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Linux).
OS of using PC is Ubuntu 16.04(64bit). 
Error messages bellow:

File "setup.py", line 31, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
Process world:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Username/pupil/pupil_src/capture/world.py", line 98, in world
    import pupil_detectors
  File "/home/Username/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 18, in <module>
    from detector_2d import Detector_2D
ImportError: No module named detector_2d

In pupil_detector folder(pupil/pupil_src/capture/pupil_detector), there is detector_2d.pyx file.
I can't find why pupil pro can't launch.

**Comment by Tank1400** [comment]
When I'm running "python main.py",these error messages appeared.

**Comment by willpatera** [comment]
@Tank1400 did you check to make sure Cython is installed?

**Comment by mkassner** [comment]
Hi,

also have you tried just using the bundles? The dependency installation is only needed when you want to make changes to the code.

**Comment by Tank1400** [comment]
@willpatera Yes. I installed Cython.

@mkassner What are bundles? I watched instruction because I will change pupil source code.

**Comment by cpicanco** [comment]
Hi @Tank1400 , have you tried the plugin system using the bundles? It is a lot more easier to implement some features using it.

**Comment by Tank1400** [comment]
@cpicanco 
Thanks for your information,I will try it.
