### ISSUE TITLE
Pupil Player - update marker detector plugin for v0.4.0

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#53]
Offline marker detector plugin needs to be updated for v0.4.0:
  - [x] replace `atb` menus and any `atb` calls with `pyglui`
  - [x] replace ctypes `c_bool` and `c_int` with standard int and bools - were required by `atb` but are no longer required by `pyglui`    
  - [x] use standard python type for `cacher_seek_idx` and `cacher_run` vars (remove c_types)
  - [x] remove `Pipe` and `Event` from offline_marker_detector multiprocessing/billiard import (not used)

**Comment by mkassner** [comment]
Done
