### ISSUE TITLE
OverflowError while exporting or playing Video in pupil player!

### ISSUE THREAD

**Issue by zoenUKS** [pupil-labs/pupil#533]
When i try to export my files in pupil player my whole operating system crashed and this sentence is showing up in console

**OverflowError: Python int too large to convert to C long main returned**

I've tried to use the latest patch and even the older one, this still happens.. maybe someone can help me? 
The only corrupted file is still the video.

I'm using a PC running with Linux Ubuntu, latest version of pupil capture and pupil player.

**Comment by zoenUKS** [comment]
ao@ao-ZBOX ~ $ 
pupil_player
Player [WARNING] __main__ : You did not supply a data directory when you called this script!

Player [ERROR] player_methods : No valid dir supplied
Player [INFO] __main__ : 
Application Version: 0.8.6.4
Player [INFO] __main__ : 
System Info: User: ao, 
Platform: Linux, Machine: ao-ZBOX, Release: 3.19.0-32-generic, 
Version: #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015

Player [INFO] plugin : 
Loaded: Trim_Marks
Player [INFO] 
plugin : Loaded: Seek_Bar
Player [INFO] 
plugin : Loaded: Log_Display
Player [INFO] 
plugin : Loaded: Video_Export_Launcher
Player [INFO] 
plugin : Loaded: Vis_Circle
Player [INFO] 
plugin : Loaded: Vis_Cross
Player [INFO] 
plugin : Loaded: Vis_Cross
Player [INFO] 
plugin : Loaded: Vis_Cross
Traceback (most recent call last):
  
File "<string>", line 579, in <module>
  
File "<string>", line 446, in session
  
File "vis_cross.py", line 38, in update

OverflowError: Python int too large to convert to C long
main returned 
-1
ao@ao-ZBOX ~ $

**Comment by mkassner** [comment]
Thanks for posting this issue. It should be fixed now.
