### ISSUE TITLE
Pupil as a web service

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#535]
I'm thinking about developing a web service of Pupil so users can collect world and eye videos (with timestamps) and upload online to be processed. Is this possible with the current Pupil source code? Should I worry about threads? would you point out anything that I should be aware of while developing this? Is there anyone else than me interested in building this?

the reason behind my request is to make Pupil more mobile, not dependant on the processing unit, and  version independent too. It will also allow us performing extra data processing without any user intervention.

**Comment by fosterseth** [comment]
Perhaps a straightforward way is to build a Capture plugin that will upload the files to the server once recording if finished (you may wish to prompt the user first, for security reasons). Is the overall idea to have an public repository of real-world eye tracking videos? If so, I think that could be pretty neat.

**Comment by mkassner** [comment]
I will close this. I think its a great idea but not necessarily in the scope of this repository's project.
