### ISSUE TITLE
Update OSX installation docs

### ISSUE THREAD

**Issue by JosephP91** [pupil-labs/pupil#538]
I have updated the OSX installation docs, because when you run python main.py in capture directory, it says:

Import Error: No module named ndsi

This solves the problem:

```
git clone https://github.com/pupil-labs/pyndsi
cd pyndsi
python setup.py install
```

**Comment by willpatera** [comment]
Hi @JosephP91 - `pip install git+https://github.com/pupil-labs/pyndsi` is listed in the [macOS Dependencies Installation](https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-MacOS#python-packages-with-pip) page on the wiki. Did this not work for you?

**Comment by JosephP91** [comment]
Hi,
thank you for the reply! Unfortunately no. That’s why I have added those instructions in the osx installation docs.

**Comment by willpatera** [comment]
@JosephP91 - what errors or messages are shown when you try to install via pip?

**Comment by JosephP91** [comment]
I retried the command listed in the osx installation docs and now it works (obviously I have removed the one manually installed before). It turned out to be a permission problem. Should I remove the lines I have added in the osx docs?

**Comment by willpatera** [comment]
Hi @JosephP91 - I can revert the wiki. Thanks for confirming. I will close this issue now.
