### ISSUE TITLE
v0.4 linux dependency

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#54]
Trying to run capture after:

Glew
```bash
sudo apt-get install libglew-dev
```
Cython
```bash
sudo pip install cython
```
Cygl
```bash
rename 'cygl-master' folder to 'cygl'
cd /cygl
sudo python setup.py install
```
Pyglui
```bash
git clone --recursive (pyglui link)
```

Finally
```bash
$ python /pupil/0.4.0/pupil_src/capture/main.py
Traceback (most recent call last):
  File "/home/rafael/bin/pupil-0.4.0.1/pupil_src/capture/main.py", line 77, in <module>
    from eye import eye
  File "/home/rafael/bin/pupil-0.4.0.1/pupil_src/capture/eye.py", line 31, in <module>
    import psutil
ImportError: No module named psutil
```

**Comment by cpicanco** [comment]
trying:
```bash
sudo pip install psuti
```

**Comment by cpicanco** [comment]
trying to install [pyv4I2](https://github.com/pupil-labs/pyv4l2):

**Comment by cpicanco** [comment]
Running!

**Comment by cpicanco** [comment]
~30-35% of CPU.
![screenshot from 2015-02-19 10 07 44](https://cloud.githubusercontent.com/assets/6511849/6267043/4325efd0-b81f-11e4-9c6e-500219722748.png)

**Comment by mkassner** [comment]
What do you think? Like the new interface?

**Comment by mkassner** [comment]
And thanks for waling though all dependencies. Great stating point for updating the wiki.

**Comment by mkassner** [comment]
Re-opended until I have the wiki updated.

**Comment by cpicanco** [comment]
I did like the new interface, visually speaking. Specially the caption with usage descriptions of some controls (Maybe for advanced users it gets boring, but I like it always there). But keyboard shortcuts tips are missing, or I just was not able to find it? I think I will create a new issue to describe my experience. Well done folks!

**Comment by willpatera** [comment]
Hi @cpicanco -- thanks for documenting your process. We will need to do a major revision of the wiki soon in order to make sure everything aligns with v0.4.0. As @mkassner said, your notes will be super useful :smiley_cat: 

Keyboard shortcuts now show up as circular buttons (pyglui thumb ui elements) in the left hand side of the window. The keyboard shortcut is the the character in the circle. In your screenshot `C` for calibration.

**Comment by mkassner** [comment]
Updated the wiki

**Comment by hookdump** [comment]
Oh, this looks awesome. Why haven't I tried 0.4 before? Is this "production-ready" yet? (i.e. as stable as the prev version). I'll try it right now!

**Comment by willpatera** [comment]
@hookdump At this point v0.4.0 should be as stable as master -- give it a try :smile:
