### ISSUE TITLE
Is PUPIL EPOCH recorded anywhere after the recording?

### ISSUE THREAD

**Issue by gmierz** [pupil-labs/pupil#541]
I am wondering if the pupil epoch is saved anywhere after doing a recording? It looks to me as if it is saved in the 'System Info' but I'd like to make sure before I continue my work.

If it is, is there a reason there is not an extra field that gives only the epoch for the sake of clarity?

**Comment by gmierz** [comment]
So the 'System Info' doesn't seem to contain PUPIL_EPOCH. I suggest that the epoch at which timestamps start from should be recorded somewhere. It is extremely important in my opinion if you want to use the pupil data with other data. I need the epoch to synchronize data from multiple instruments together and the only way I found requires epochs from each of the different datasets.

Is there is some other way to synchronize data from two different measurement tools that doesn't require the epoch?

**Comment by cpicanco** [comment]
You can try to communicate to pupil synch/groups. Then all "instruments" will be auto/detected and auto synchronized. If you are a Python guy, then PUPIL has examples for you. Take a look:

https://github.com/pupil-labs/pupil-helpers/tree/master/pupil_sync

**Comment by cpicanco** [comment]
PUPIL EPOCH is the first line of the `world_timestamps.npy` file. I guess you can read it like this:

```
import numpy as np

timestamps = np.load('world_timestamps.npy')
PUPIL_EPOCH = timestamps[0][0]
```

**Comment by gmierz** [comment]
Thanks for the help yet again @cpicanco! :) 

When I do that I get the number of seconds since the pupil epoch and I have the latest version so this is kind of odd. I think I'm going to make a plug-in for myself that sets the timestamp (time since capture was launched or something like that) or just use ZMQ in my program to set it.

**Comment by gmierz** [comment]
`'''
(*)~----------------------------------------------------------------------------------
 Pupil - eye tracking platform
 Copyright (C) 2012-2016  Pupil Labs
 Distributed under the terms of the GNU Lesser General Public License (LGPL v3.0).
 License details are in the file license.txt, distributed as part of this software.
----------------------------------------------------------------------------------~(*)
'''
import sys
import zmq
import calendar
import time
from plugin import Plugin
from pyglui.cygl.utils import draw_points_norm,RGBA
from pyglui import ui

def timestampChange(ip, port):
    ctx = zmq.Context()
    requester = ctx.socket(zmq.REQ)
    requester.connect('tcp://%s:%s'%(ip,port))

    requester.send('t')
    t = requester.recv()
    print('time:',t)

    tmp = 'T ';
    tmp += "{:.7f}".format(calendar.timegm(time.gmtime()))

    requester.send(tmp)
    resp = requester.recv()
    print('resp:',resp)

    requester.send('t')
    t = requester.recv()
    print('time:',t)

class Synch_Epochs(Plugin):
    """
    Change pupil epoch to UNIX timestamp for the sake of clarity.
    Make the change by loading this through the plugin list.
    """

    def __init__(self, g_pool):
        super(Synch_Epochs, self).__init__(g_pool)
        timestampChange('127.0.1.1', 50020);`

Here's a quick plug-in I wrote up that changes the timestamp to the UNIX standard that can be easily converted to a date with `time.gmtime(float(<time-in-seconds-since-epoch>))`.

**Comment by zhangyy985** [comment]
Could you update the program with 'normal' timestamp?

**Comment by cpicanco** [comment]
hi @zhangyy985 , what do you mean by 'normal' timestamp?

**Comment by gmierz** [comment]
Hi @zhangyy985, in comment 5 you'll find a plugin that you can place in a folder called 'plugins' - it needs to be created - in your 'pupil_capture_settings' folder. Start up pupil capture then select 'Synch Epochs' in the plugins list and from then on, all your timestamps will be UNIX standard timestamps with a UNIX epoch time. If you want to get an actual date out of these timestamps use the python call 'time.gmtime(<TIMESTAMP>)' to convert them.

**Comment by gmierz** [comment]
I am closing this now since my question was pretty much answered.
