### ISSUE TITLE
[Windows Version] Installation instruction unclear

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#546]
Hi,
I want to install the Windows Version for the Oculus Rift 2.

What do I have to select at point 5?

>  Locate your Pupil headset composite device. It is very important that you select the composite parent and not one of the interfaces.

**Comment by willpatera** [comment]
Hi @PolynomialDivision - Thanks for the feedback. We will make a wiki page with screenshots of this process tomorrow morning when back at the Windows development machine. I realize now that it may not be so clear from written instructions, so we will add screenshots to the wiki page and update this issue after making the wiki page. 

While more text will not necessarily help at this point here are some notes: After you have launched Zadig, and you should see `Pupil Cam1 ID 0`, and `Pupil Cam1 ID 1` listed under a composite parent device (a hub). Select the composite parent device and then replace the driver with `libusbK` within the Zadig GUI.

**Comment by PolynomialDivision** [comment]
Sry I think I was to quick.

I forgot to **uncheck** the option "Ignore Hubs and Composite Parents". When you do this everything is clear. You have to select name Pupil Cam ID1 (composite parent)

After destroying my keyboard driver everything works now fine. ^^

[https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it](This) is very helpful if accidentally replace the wrong usb device. :)

**Comment by willpatera** [comment]
Hi @PolynomialDivision - thanks for the update and sorry to hear about your keyboard driver 😓  - also thanks for the link to the article on fixing drivers 😃 

I have added a wiki page with screenshots, and updated the release notes linking to the wiki page to assist in this process. The wiki page is [here](https://github.com/pupil-labs/pupil/wiki/Windows-Driver-Setup).

I am going to close this issue now - but feel free to continue the conversation if you think anything is not clear in the docs.
