### ISSUE TITLE
Windows Camera Driver Installation

### ISSUE THREAD

**Issue by marc-tonsen** [pupil-labs/pupil#551]
When installing the camera drivers for windows I had to deviate from what the installation guide sais. The guide sais I have to replace the driver for one of any of the entries starting with "Pupil Cam 1", but for me replacing one was not enough. When selecting other entries in Zadig starting with "Pupil Cam 1" the displayed current driver was indeed not libusbK and I had to make a couple of replacements until libusbK was displayed as the current driver for all entries starting with "Pupil Cam 1". Also the names of the devices in the hardware manager were different from what is stated in the guide  (see screenshot).

![screenshot](https://cloud.githubusercontent.com/assets/22236733/21218921/e26f7f80-c2b2-11e6-9286-9b9e7f06f083.PNG)

**Comment by willpatera** [comment]
@marc-tonsen - Did you uncheck `Ignore Hubs or Composite Parents`?

**Comment by marc-tonsen** [comment]
Yes I did!

**Comment by willpatera** [comment]
@marc-tonsen - OK - please update the install instructions on the wiki with changes.
