### ISSUE TITLE
scan_path.py should be renamed vis_scan_path.py

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#560]
Current scan path player plugin should be renamed as such because it is for visualization only. There is no extra data included when exporting data. There is no other purpose, as far as I know.

**Comment by mkassner** [comment]
I think this is a good. Idea @cpicanco  can you make a PR?

**Comment by cpicanco** [comment]
Yes. Will do it.

**Comment by cpicanco** [comment]
#565
