### ISSUE TITLE
Pupil player takes 1 - 100% CPU

### ISSUE THREAD

**Issue by Lahorde** [pupil-labs/pupil#562]
When I run pupil-player with [example record](https://docs.google.com/uc?id=0Byap58sXjMVfQnAteVlQUlBJRjA&export=download)
it is very slow, 
In htop I can see player runs at 100% CPU and goes never above (irix mode in top is on)

![capture_htop](https://cloud.githubusercontent.com/assets/5982137/21459612/0dce2738-c940-11e6-81a1-74d096ef888a.png)

Why player cannot take more than 100% CPU?

**Comment by papr** [comment]
Unfortunately, a lot of calculations (e.g. fixation detector) in `Pupil Player` are executed in the main thread. This makes the application unresponsive and slow. We are aware of this issue and are planning on making it asynchronous and responsive.
