### ISSUE TITLE
ROI blue cirles do not respond to click-and-drag

### ISSUE THREAD

**Issue by ogik13** [pupil-labs/pupil#563]
This bug happens on Windows 10 Capture software bundle 0.8.7-w-19 and also on 0.8.7-w

**Comment by willpatera** [comment]
@ogik13 - thanks for the report. I will look into this within the next few days.

**Comment by papr** [comment]
This bug was introduced with recent capture source handling changes. We are resetting the ROI with every frame and therefore it looks like it would not move. We are changing the code such that will reset the ROI if necessary.

**Comment by mkassner** [comment]
This. Is already fixed in the non blocking capture branch.

Will close when merging the PR.

M

**Comment by mkassner** [comment]
#570 closed this issue

**Comment by cpicanco** [comment]
I replicated this one on ubuntu. v.0.8.7

**Comment by ogik13** [comment]
I do not have this issue in Ubuntu, actually. (I'm not using it any more,
anyway.) I have it on Windows 10.
