### ISSUE TITLE
Notes on v0.4

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#57]
Selecting items Camera intrinsic and Accuracy Test on Calibration Menu dropdown changes the order of C and R buttons... What is it for? rsrsrs

...

fixed

**Comment by cpicanco** [comment]
Open Plugin dropdown is fully functional? What I should expect when selecting an item? Maybe a brief caption description to each item would be great...

**Comment by cpicanco** [comment]
Mouse keeps visible while Screen Calibration. Should be invisible.

**Comment by cpicanco** [comment]
I will take this week to test the marker detector, since I am planning to use it. Unfortunately I need to print all the stuff, so I will pass it and other that requires printing things.

**Comment by mkassner** [comment]
your first note is fixed.

**Comment by cpicanco** [comment]
General settings is not affected (of course) by the Camera Settings load defaults. General will persist? If yes, I think that is not bad "a load default" button. (And I will safely messing with all the stuff) :)

**Comment by cpicanco** [comment]
I found a bug when clicking on settings when Update Display is off. Options that would crash while Update Display = False should be Disabled.

**Comment by cpicanco** [comment]
Confidence is impressively at 1.0 a lot. It's something here or you are really good on that hum? I love this project.

**Comment by cpicanco** [comment]
Do you ever think about a 'Hint' functionality? Would be great and could clean up a little bit some controls.

**Comment by cpicanco** [comment]
There is an empty space at the bottom of the Calibration -> Controls -> Advanced Menu.

**Comment by cpicanco** [comment]
Since 0.3.6, I was not able to change the IP of Pupil Server. I had to hardcode it. I was clicking on the IP but all I got was a blue underline :(

Better create a separate issue for that, or not? I was using tcp://*:5000 as publisher and getting the publisher IP from another computer and works fine without any gui.

**Comment by cpicanco** [comment]
Is not possible to define a ROI closest to the borders.

**Comment by mkassner** [comment]
@cpicanco can you be specific about what settings cause the crash?
'
I found a bug when clicking on settings when Update Display is off. Options that would crash while Update Display = False should be Disabled.
'

**Comment by cpicanco** [comment]
Sorry @mkassner , but I think I was wrong on that "Update Display = False". Please take a look:

Open the Marker Plugin and Clicking on Robust detection leads to:

```bash
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    main()
  File "main.py", line 136, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/bin/pupil/pupil_src/capture/world.py", line 316, in world
    p.update(frame,events)
  File "/home/rafael/bin/pupil/pupil_src/shared_modules/marker_detector.py", line 182, in update
    visualize=0)
  File "/home/rafael/bin/pupil/pupil_src/shared_modules/square_marker_detect.py", line 237, in detect_markers_simple
    gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.error: /home/rafael/OpenCV/opencv-2.4.6.1/modules/imgproc/src/color.cpp:3402: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

**Comment by cpicanco** [comment]
World
Camera settings Menu
- use hardware timestamps toggle is non responsive
- expose auto priority toggle is non responsive
- load defaults (and refresh) becomes non responsive after click
- clicking on load defaults make Pan and Tilt non responsive at maximum values.

- clicking on Pan and tilt drag and drop circles cause an error:
```bash
WORLD Process [ERROR] v4l2 : Could not set control
```

**Comment by mkassner** [comment]
I fixed the marker detector error. Thanks for spotting that. 

The camera controls being unresponsive is out of our control. Its really driver and firmware related.

**Comment by cpicanco** [comment]
So the "use hardware timestamps" is functional only in some cameras?

**Comment by cpicanco** [comment]
What about hid the controls that are, for some reason, out of control? rsrsrs

**Comment by cpicanco** [comment]
Problems with the autofocus feature. Will clone again as the load default does not work yet.

**Comment by mkassner** [comment]
Hi,

one way to load software defaults is to just delete the `capture settings`
dir.

Yes, hardware timestamps are not supported by all hardware (notably MacOS
backend and Pupil Dev eye camera :-( )

Best,

Moritz

**Comment by cpicanco** [comment]
Well, I want to buy a Pupil Pro as well as mount another Pupil Dev (to reduce the cables weight, but it is very risk now since I just have one! so...). I will wait until the Germany travel though.

Autofocus was not working because the camera was tape trapped.

Focus(absolute) is out of control as well?? 
```bash
WORLD Process [ERROR] v4l2 : Could not set control
```

**Comment by mkassner** [comment]
Focus absolute should work if you disable Focus_Auto.

**Comment by cpicanco** [comment]
Clicking (maybe touching) over C (calibration) button when Natural Features Calibration is running starts data sampling resulting in poor calibration. (I need to test if the problem is in my mouse pad, but a delay to insure mistakes would be great)

**Comment by cpicanco** [comment]
I should take a look at the player? Or better wait?

**Comment by cpicanco** [comment]
Why not a "Plugins Menu" with a button for each plugin? Is kind of strange open something by a drop down item.

**Comment by cpicanco** [comment]
I GOT IT!!! THE BLUE UNDERLINE IS THE "YOU CAN EDIT DUDE" FEEDBACK!!!!!

Where is the ' | ' twinkling??

**Comment by mkassner** [comment]
I would agree for Pupil Capture, in Pupil Player there are to many plugins
for that.

M

**Comment by cpicanco** [comment]
But @mkassner, when you have an interface that just goes up and down and is full since the beginning (with other menus) is not bad a long list always showing... Remenber that one will still need to click on the menu to show the plugin button list.

**Comment by cpicanco** [comment]
After adding a new marker, clicking on 3d localization.
```bash
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    main()
  File "main.py", line 136, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/bin/pupil/pupil_src/capture/world.py", line 316, in world
    p.update(frame,events)
  File "/home/rafael/bin/pupil/pupil_src/shared_modules/marker_detector.py", line 191, in update
    s.locate(self.markers, self.locate_3d,self.camera_intrinsics)
  File "/home/rafael/bin/pupil/pupil_src/shared_modules/reference_surface.py", line 230, in locate
    K,dist_coef,img_size = camera_intrinsics
TypeError: 'NoneType' object is not iterable
```

**Comment by cpicanco** [comment]
Another idea is to reserve a tab for each plugin instead pulling them to the bottom.

**Comment by cpicanco** [comment]
CPU graph is overflowing the maximun cap.
![screenshot from 2015-02-20 14 10 37](https://cloud.githubusercontent.com/assets/6511849/6305491/629e3692-b90a-11e4-9627-40affe711122.png)

**Comment by cpicanco** [comment]
Show marker ID is not showing the marker ID.

**Comment by cpicanco** [comment]
@mkassner, please, make me know if I should create separated issues from now.

**Comment by mkassner** [comment]
@cpicanco, yes one `issue` per issue would be great!

**Comment by cpicanco** [comment]
Everything important for me was moved or solved. Time to close.
