### ISSUE TITLE
Pupil service v0.8.7-w unable to restart

### ISSUE THREAD

**Issue by qian256** [pupil-labs/pupil#572]
It seems that pupil service is not shutdown clean on windows. The windows task manager shows that it is still running, and I am not able to start the application again unless I manually terminate the Pupil service process. Pupil capture and Pupil player do not have the problem.
I am running v0.8.7-w on Windows 10 64bits.

**Comment by willpatera** [comment]
Hi @qian256 - This is not a bug, but rather the behavior of Pupil Service. 

Have you tried sending a stop message to Pupil Service: `{'subject':'service_process.should_stop'}` ?

**Comment by qian256** [comment]
Hi Will,
I haven't tried that. But I mean, for **pupil_service.exe**, it would be nice for users (non-programmers) to shut it down cleanly by simply clicking 'X' on the eye window, maybe by sending out a stop message from the GUI callback?

**Comment by willpatera** [comment]
Hi @qian256 - I agree. I think Pupil Service needs a small control window so that it can be stopped/started cleanly. I have discussed this already with @mkassner - however this is a separate issue (or multiple separate issues :smile:)

**Comment by qian256** [comment]
OK, I see. I am looking forward to the update of that ;)
