### ISSUE TITLE
Windows: Problems when running from source

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#575]
Hi,
I have some problems when I want to start pupil from the source:

    Process world:
    Traceback (most recent call last):
      File "C:\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
        self.run()
      File "C:\Python35\lib\multiprocessing\process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Users\xxx\pupil\pupil_src\capture\world.py", line 99, in world
        import pupil_detectors
      File "C:\Users\xxx\pupil\pupil_src\capture\pupil_detectors\__init__.py", line 19, in <module>
        from . detector_3d import Detector_3D
    ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

When I'm running the setup script for building the detector_3d there is no error:

    running install_lib
    copying build\lib.win-amd64-3.5\detector_2d.cp35-win_amd64.pyd -> C:\Python35\Lib\site-packages
    copying build\lib.win-amd64-3.5\detector_3d.cp35-win_amd64.pyd -> C:\Python35\Lib\site-packages
    running install_egg_info
    Writing C:\Python35\Lib\site-packages\eye_model_3d-0.1-py3.5.egg-info

But I don't find an dll modul.
Where is this dll created?

**Comment by mkassner** [comment]
@willpatera  I m not familiar with the windows dll process? Do you have an idea?

**Comment by qian256** [comment]
I also run into this issue. I looked at the dependencies of detector_3d.cp35-win_amd64.pyd, it shows that it depends on BOOST_PYTHON3-VC140-MT_1_59.DLL like this:
![depends_detector_3d](https://cloud.githubusercontent.com/assets/8185982/21731952/07dc551c-d425-11e6-883b-3fbae21adf50.PNG)

I can only find `boost_python-vc140-mt-1_59.dll` in the directory `boost_1_59_0/lib64-msvc-14.0`. I copied it to the path of `pupil\pupil_src\capture\pupil_detectors`, and rename to `boost_python3-vc140-mt-1_59.dll` (adding a '3'). It is working now.
But apparently boost-python binaries is in turn depending on python2. I am not sure how to build boost-python3 cleanly on python3.

**Comment by PolynomialDivision** [comment]
This isn't working for me... :(

For starting pupil with 2d detection I'm using a workaround... ^^

In `eye.py` change the line 111 to

    from pupil_detectors import Detector_2D#, Detector_3D

and add under this line

    from pupil_detectors import Detector_2D as Detector_3D

Then it's possible to start pupil.

**Comment by PolynomialDivision** [comment]
Finally it works!

You have to build boost against pyrhon3 with VS 2015!

**Comment by qian256** [comment]
Thank you for the link. I will try building boost with python3. For me, the trick enables detector_2d but not detector_3d.

**Comment by PolynomialDivision** [comment]
It's not fixed... ^^

I tried it again and suddenly it gives me the same error...

Maybe you can just take `boost_python3-vc140-mt-1_59.dll `from the source bundle? :P

**Comment by qian256** [comment]
Actually there is `boost_python3-vc140-mt-1_59.dll` in the release ~.7z of v0.8.7-w. It's built using VS2015 and Python3. I am using that.

**Comment by willpatera** [comment]
@PolynomialDivision, @qian256 - According to windows dependency docs you need to install boost for python3 [see this section]. 
>- Open boost_1_59_0\boost\python\detail\config.hpp
>- Change the macro definition "#define BOOST_LIB_NAME boost_python" to "#define BOOST_LIB_NAME boost_python3" and save the file

And you need to make sure that the paths in the `setup.py` files for *both* pupil detectors and `calibration_routines/optimization_calibration` are pointing to the correct locations.

Additionally, please make sure that you follow instructions for re-building ceres with `Eigen3.2`

**Comment by willpatera** [comment]
@PolynomialDivision @qian256 - please take a look at my comment above ☝️ . I'd like to get some feedback so that we can either close the issue or revise the installation instructions.

**Comment by PolynomialDivision** [comment]
Sorry. I had no time to resposne.

Suddenly it's working. :) Somehow I overwrote this line `#define BOOST_LIB_NAME boost_python3`... After changing this again everything compiles fine. But I still have to use #574  (I will comment your review after writing this post)

# Some comments to your installation instructions

Just suggestions. :)

## Precompiled boost version
I think in your tutorial the precombiled boost version (https://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/boost_1_59_0-msvc-14.0-64.exe/download) is wrong. You have to build boost with python 3. This version was compiled with python2 and so the `boost_python3-vc140-mt-1_59.dl` is missing.

## pyuvc
I would link to the release page or directly to the wheels. For me it first seemed that I have to compile it on my own.

## pyav
I would link to the tutorial at the bottom on your wikipage.

Thanks! :)

**Comment by PolynomialDivision** [comment]
Suddenly the error appears again after playing around with #574 ...

**Comment by PolynomialDivision** [comment]
Everything works now. :) So I'm going to close this issue.

I forgot to add the -d parameter when something went wrong.

    git clean -d -f
