### ISSUE TITLE
Symbol not found: _PyInt_Type

### ISSUE THREAD

**Issue by JosephP91** [pupil-labs/pupil#579]
Following the osx installation instructions for python3, I have this error:

ImportError: dlopen(/Users/giuseppepersico/Documents/pupil/pupil_src/capture/pupil_detectors/detector_2d.so, 2): Symbol not found: _PyInt_Type

**Comment by papr** [comment]
Dear @JosephP91 
could you tell us which Python and Cython versions you are using?

**Comment by JosephP91** [comment]
Hi @papr 
Python version: 3.6.0
Cython version 0.25.2

**Comment by papr** [comment]
Ok, that are the same versions as I use them. Could you create a [gist](gist.github.com) with the whole output (if you start from terminal) or upload the log file (if you use the bundle) including the error?

**Comment by JosephP91** [comment]
I can paste the log error here:

`Process world:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/giuseppepersico/Documents/pupil/pupil_src/capture/world.py", line 99, in world
    import pupil_detectors
  File "/Users/giuseppepersico/Documents/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 19, in <module>
    from . detector_2d import Detector_2D
ImportError: dlopen(/Users/giuseppepersico/Documents/pupil/pupil_src/capture/pupil_detectors/detector_2d.so, 2): Symbol not found: _PyInt_Type
  Referenced from: /Users/giuseppepersico/Documents/pupil/pupil_src/capture/pupil_detectors/detector_2d.so
  Expected in: flat namespace
 in /Users/giuseppepersico/Documents/pupil/pupil_src/capture/pupil_detectors/detector_2d.so`

**Comment by mkassner** [comment]
Hi,

this error might also be because python is not properly linked in the cython extension.

**Comment by JosephP91** [comment]
Hi @mkassner 
and how could I solve this?

**Comment by papr** [comment]
@JosephP91 Sorry for the radio silence. Could you elaborate on how you have installed Python 3.6 and Cython on your OS and specify which OS you are actually using?

**Comment by JosephP91** [comment]
Hi @rapr, thank you for reply
I am installing the dependencies following the macOS instructions reported at:

https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-MacOS

I am using the latest macOS Sierra version, which is 10.12.

**Comment by papr** [comment]
I recommend to set up a virtual Python environment for Python 3.6 and reinstalling all Python dependencies in it. This is to make sure that everything is linked correctly and not influenced by external factors (like other Python installations).

**Comment by JosephP91** [comment]
Ok, thank you. @papr Do you recommend to use the pupil version compatible with python3 or python2.7?

**Comment by papr** [comment]
Definitely the one with 3.6. The 2.7 version is deprecated and will not receive any new features.

**Comment by papr** [comment]
@JosephP91 Did you make any progress concerning this issue?

**Comment by JosephP91** [comment]
@papr Sure, creating a virtual environment solves the issue. Thank you! You can close the issue

**Comment by papr** [comment]
Great to hear! 👍
