### ISSUE TITLE
Make mouse cursor invisible in fullscreen calibration

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#58]
Issue raised by @cpicanco in #57

**Comment by willpatera** [comment]
implemented at https://github.com/pupil-labs/pupil/commit/b54779e5d0b61c95fc7bfb26b5c2dddc516b824c -- @cpicanco, please let me know if this works for you on Linux and I will close.

**Comment by cpicanco** [comment]
Mouse keeps visible.

**Comment by hookdump** [comment]
It might be worth it to try GLFW_CURSOR_DISABLED instead of GLFW_CURSOR_HIDDEN, although it could be problematic: It hides and locks the cursor for the entire desktop, not just the specified window.

Perhaps instantly moving the cursor to 0,0 could be a better quick solution?

**Comment by mkassner** [comment]
I don't like these fixes especially because hiding the curser in mostly for aesthetics. 
As it turn out this is a glfw bug that should get fixed soon. So I guess we just wait.

**Comment by cpicanco** [comment]
Well, I am not sure if it is most for aesthetics @mkassner. Redardless of the cursor be such a very tiny form and does not interfere in the circle_detector, it can be extremely appealing for some users. So, leading to poor calibration results.

**Comment by mkassner** [comment]
Agreed! Its more than aesthetics.

Pushing for a fix on glfw is the best way to go I would say. I don't like
writing hacks for bugs.

M

**Comment by mkassner** [comment]
All our work here is done. Lets wait for glfw to fix their bug.
