### ISSUE TITLE
Player - surfaces defined in Capture not being loaded in Player 

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#583]
## Overview
Surfaces defined in Pupil Capture are not being loaded in Pupil Player. 

Tested on macOS `v10.12.2` with Pupil Capture bundle `v0.8.7` and latest source after python3 merge. 

## Steps to reproduce the issue
1. Start Pupil Capture
1. Load `Surface Tracker` plugin
1. Add a surface (optionally name the surface and define other parameters)
1. Make a recording 

1. Start Pupil Player
1. Load `Offline Surface Tracker` plugin (error message from offline surface tracker `WARNING - No surfaces defined.`

**Comment by papr** [comment]
@willpatera Can you test 7c103a6 and confirm that the issue is fixed?
