### ISSUE TITLE
Problem: glfw3 brew install location changed

### ISSUE THREAD

**Issue by darksipu** [pupil-labs/pupil#585]
Hi there, 

I followed a thread about a similar issue on an old Mac and did exactly what it was specified.

I am running into 2 problems that I can't figure out.

First, when I:
cd pupil
git clone https://github.com/pupil-labs/pupil.git
git fetch
git checkout opencv3

I get:

error: pathspec 'opencv3' did not match any file(s) known to git

Second, when I try to run the main.py, I get:
File "main.py", line 49, in <module>
from multiprocessing import Process, Value, active_children, freeze_support, set_start_method
ImportError: cannot import name set_start_method

The reason why I'm actually trying to run the source code is that on my late 2013 MacBook Pro, the Pupil Capture crashes when I'm recording an experiment session (although I only have one other browser tab open).

Any ideas on how to deal with this?

**Comment by willpatera** [comment]
Hi @darksipu.  

## Opencv3 branch
The first error you get is because the `opencv3` branch no longer exists. You can take a look at [opencv3_rebase](https://github.com/pupil-labs/pupil/tree/opencv3_rebase). However, please note that the last update was in October. We have since moved on to supporting python3 and opencv3. 

## python3_opencv3
The second error you get is due to the fact that you are using python2 and trying to call a python3 method. 

The current `master` branch now uses `python3` and `opencv3`. I would suggest you `brew update` and `brew install python3`. This will install python `v3.6`. And follow macOS [dependency installation instructions](https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-MacOS). 

I would recommend creating a virtual environment for python3 modules.

## Pupil on 2013 MacBook Pro
I am no sure we can support this hardware. Out of curiosity, what version of `macOS` is running on the late 2013 MBP?

**Comment by darksipu** [comment]
it's a Sierra 10.12.2

So, the best way to go would be to update to python3?

Thanks for the help, 
Florin

**Comment by darksipu** [comment]
Sorry, I'm a bit confused about switching to the python3 environment.

I've got python3 installed on the machine, but how do I change to using that? Do I have to change the PYTHONPATH?

Sorry, I'm not very well versed in messing around with the Unix

**Comment by darksipu** [comment]
Hi Will, 

Thanks for the help. I've managed to play around a bit, but I'm still facing an issue.
First, the 2013 MBP is running on Sierra 10.12 and the iMac I'm trying to run the source code off is running El Capitan 10.11.

Now, I've switched to python3 and when I run the main.py, I get:


MainProcess - [INFO] os_utils: Disabled idle sleep.
Process world:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dcr/Pupil/pupil/pupil_src/capture/world.py", line 76, in world
    import glfw
  File "/Users/dcr/Pupil/pupil/pupil_src/shared_modules/glfw.py", line 73, in <module>
    raise RuntimeError('GLFW library not found')
RuntimeError: GLFW library not found
^CMainProcess - [INFO] os_utils: Re-enabled idle sleep.
Traceback (most recent call last):
  File "main.py", line 253, in <module>
    launcher()
  File "main.py", line 225, in launcher
    topic,n = cmd_sub.recv()
  File "/Users/dcr/Pupil/pupil/pupil_src/shared_modules/zmq_tools.py", line 84, in recv
    topic = self.socket.recv_string()
  File "/usr/local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 457, in recv_string
    msg = self.recv(flags=flags)
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)


Any ideas?

**Comment by willpatera** [comment]
@darksipu some notes:

The error you are seeing means that the `glfw3` library is not found. Can you confirm that  `glfw3` is installed? You can check with `brew info glfw3` and if not installed then `brew install glfw3`.

**Comment by darksipu** [comment]
Yes, I uninstalled and installed it a couple of times, just to make sure. I see a --HEAD version here. Is that relevant? Or should I install the static build for glfw3?

**Comment by willpatera** [comment]
@darksipu can you run the following lines from a python in the terminal:

```python
from ctypes.util import find_library
find_library('glfw3')
```

And share the resulting path?

**Comment by darksipu** [comment]
I assumed you mean to run it from a .py file?

woland:~ dcr$ from ctypes.util import find_library
from: can't read /var/mail/ctypes.util
woland:~ dcr$ find_library('glfw3')
-bash: syntax error near unexpected token `'glfw3''
woland:~ dcr$ python test.py
  File "test.py", line 1
    {\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
                                                      ^
SyntaxError: unexpected character after line continuation character

**Comment by papr** [comment]
> from python interactive session 

@darksipu When you execute `python` in your terminal you will enter the _python interactive mode_. Paste the lines that @willpatera mentioned above.

**Comment by darksipu** [comment]
Oh, I did that, but it doesn't do anything:

woland:~ dcr$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('glfw3')
>>>

**Comment by papr** [comment]
Ok, could you try the following:

```python
from ctypes.util import find_library
result = find_library('glfw3')
print(result)
print('-----')
```

**Comment by darksipu** [comment]
it prints None

**Comment by papr** [comment]
Ok, this helps already. Could you run `brew info glfw3` in your terminal and paste the output?

**Comment by darksipu** [comment]
woland:~ dcr$ brew info glfw3
glfw: stable 3.2.1 (bottled), HEAD
Multi-platform library for OpenGL applications
http://www.glfw.org/
/usr/local/Cellar/glfw/3.2.1 (14 files, 286.5K) *
  Poured from bottle on 2017-01-16 at 14:07:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/glfw.rb
==> Dependencies
Build: cmake ✔
==> Options
--universal
	Build a universal binary
--with-examples
	Build examples
--with-test
	Build test programs
--without-shared-library
	Build static library only (defaults to building dylib only)
--HEAD
	Install HEAD version

**Comment by papr** [comment]
If you could run `brew doctor` for me, that would be great. I am looking specifically for information about brew not linking glfw3.

**Comment by darksipu** [comment]
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libuvc.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libuvc/libuvc.h
  /usr/local/include/libuvc/libuvc_config.h



Thank you so much for the help!

**Comment by papr** [comment]
We were able to replicate the issue. Apparently the brew formular for glfw changed. Our code needs to use `find_library('glfw')` instead of `find_library('glfw3')`. This will be fixed with the next release. Changing issue title appropriately.

**Comment by papr** [comment]
Closed with #587

**Comment by darksipu** [comment]
I see, so would I be able to change something in the source code to get it working?

I need to use Pupil Capture tomorrow, so I was wondering what you would recommend. Would running the source code on the late 2013 MBP Sierra OX 10.12 work without crashing?

**Comment by papr** [comment]
Yes, this is possible. Just look at 15d87a1 to see the necessary changes.

**Comment by darksipu** [comment]
Thanks, that works.

Sorry to be a pain, but now I'm running into another error when running the main.py:
woland:capture dcr$ python main.py
MainProcess - [INFO] os_utils: Disabled idle sleep.
Process world:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dcr/Pupil/pupil/pupil_src/capture/world.py", line 88, in world
    from methods import normalize, denormalize, delta_t, get_system_info
  File "/Users/dcr/Pupil/pupil/pupil_src/shared_modules/methods.py", line 19, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
^CMainProcess - [INFO] os_utils: Re-enabled idle sleep.
Traceback (most recent call last):
  File "main.py", line 253, in <module>
    launcher()
  File "main.py", line 225, in launcher
    topic,n = cmd_sub.recv()
  File "/Users/dcr/Pupil/pupil/pupil_src/shared_modules/zmq_tools.py", line 84, in recv
    topic = self.socket.recv_string()
  File "/usr/local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 457, in recv_string
    msg = self.recv(flags=flags)
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
KeyboardInterrupt



I then tried:
python
import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'

But then, you said that the thing works on opencv3?

**Comment by papr** [comment]
See the wiki for the correct dependency installations. Yes, the new version uses Opencv 3 but the python module is still called cv2.

**Comment by darksipu** [comment]
Hi, 

Yes, I've moved on from that. I've been installing quite a few things and now it's giving me this:
MainProcess - [INFO] os_utils: Disabled idle sleep.
Process world:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dcr/Pupil/pupil/pupil_src/capture/world.py", line 89, in world
    from uvc import get_time_monotonic
ImportError: cannot import name 'get_time_monotonic'


uvc is installed

**Comment by papr** [comment]
Please be aware that you need to install our custom version of libuvc, pyuvc, and pyav,  as noted on the wiki.

**Comment by darksipu** [comment]
Yes, sorry, I was running a Python virtual environment and forgot to install these on there. 

Just to let you know, in python 3 urlparse is urllib.parse and I had to change this (I can't remember what file I changed, sorry about this) to make it work.

Thanks a lot for the help, 
Florin

**Comment by papr** [comment]
OK, thanks for the hint. We will look into it.

**Comment by darksipu** [comment]
This might already be somewhere on the pupil wiki and I can't find it, but I think it would be useful to provide a list of the machines that run Pupil Capture properly. 

At the moment, the mid-2010 iMac (Intel Core 2 Duo, 4GB RAM) runs Pupil Capture fine, but when I load the Online Surface tracker with 4 markers and I try to record, it crashes after about 1 minute. Also, the Offline Surface Tracker in the Player crashes.

Same issue with a late 2013 MBP Retina, i5, 8GB RAM, running Sierra 10.12 about the Online Surface Tracker and it also crashes just by trying to record without using Online Surface Tracker after about 1 minute (running the GUI version, not the source code).
