### ISSUE TITLE
Index out of bound error during HMD Calibration

### ISSUE THREAD

**Issue by camcse** [pupil-labs/pupil#588]
Index out of bounds error during HMD calibration in calibration.py (line 46).

logger.info('used {} data points out of the full dataset {}: subset is {} percent'.format(
            (cal_pt_cloud[err_dist <= threshold].shape[0], cal_pt_cloud.shape[0],
             100*float(cal_pt_cloud[err_dist <= threshold].shape[0])/cal_pt_cloud.shape[0])))

*It happens 100% times with my setup.

However, I have commented the above lines of codes and the HMD calibration works just fine. This is just for your information. I am not blocked due to this issue. Thanks.

**Comment by PolynomialDivision** [comment]
> However, I have commented the above lines of codes and the HMD calibration works just fine. This is just for your information. I am not blocked due to this issue. Thanks.

I had this problem too and I just did the same. :)
