### ISSUE TITLE
ROI handles never reach window bounds

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#59]
Issue raised by @cpicanco in #57 

Currently the ROI handles are offset from the window edges by 20 pixels. See where this is hardcoded in `eye.py` [L401-L404](https://github.com/pupil-labs/pupil/blob/v0.4_restruct/pupil_src/capture/eye.py#L401-L404). The offset was defined so that the user can actually select the ROI handle and not resize the window as window resizing. 

One solution would be to ask GLFW to disable window resizing when we enter ROI mode. However it seems that you can only set GLFW_RESIZABLE to GL_FALSE on window creation. 

Another option would be to increase the ROI handle target area so that the handle is still able to be selected when at the window edge.

**Comment by willpatera** [comment]
@cpicanco -- I went with the second option, and increased the ROI handle target and size of the circle. Let me know if this works well for you on Linux. If so I can close the issue.

**Comment by cpicanco** [comment]
Top right and Top left drag and drop circles are ok. Bottom circles are getting out of bounds.
![screenshot from 2015-02-20 07 26 13](https://cloud.githubusercontent.com/assets/6511849/6284737/30aac35e-b8d2-11e4-83f1-087a1d88d567.png)

**Comment by willpatera** [comment]
@cpicanco Thanks for testing... working on it now.

**Comment by mkassner** [comment]
This happens when using old capture settings.

**Comment by mkassner** [comment]
I m closing this because the error only happens with old capture settings.
