### ISSUE TITLE
Recent changes from b/nonblock broke uvc support for me

### ISSUE THREAD

**Issue by florianbussmann** [pupil-labs/pupil#593]
Since the latest commits regarding "non blocking capture" I am no longer able to run pupil capture from source on Windows. I had to update ndsi to 0.2.14 and uvc to 0.91 which has worked out for me without any hassle, but now I get the error messages attached below. If i go back to a2c449a everything is working as normal. Are you aware of this or is this a problem on my end?

world - [INFO] video_capture.uvc_backend: Camera stopped providing frames. Reinitialising camera.
world - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID2.
world - [ERROR] uvc: Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
Estimated / selected altsetting bandwith : 904 / 1600.
world - [INFO] video_capture.uvc_backend: Camera stopped providing frames. Reinitialising camera.
world - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID2.
world - [ERROR] uvc: Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.

**Comment by papr** [comment]
Hey @florianbussmann,
does this issue persist with the current master branch version?

Did you try disconnecting the headset for at least 5 seconds?

**Comment by mkassner** [comment]
@papr  @florianbussmann  this issue is specific to the libuvc implementation of timeouts in windows and requires fixing of libuvc. https://github.com/pupil-labs/pyuvc/issues/23

**Comment by mkassner** [comment]
Also happens on linux :-(.

**Comment by camcse** [comment]
Same issue at my end as well. For my purposes I am creating the EXE and running that without errors.

**Comment by willpatera** [comment]
Hi @camcse - as @mkassner notes in his comment above, a fix is needed for `libuvc` for timing in Windows and Linux in order for non-blocking capture to work.

**Comment by florianbussmann** [comment]
Timeouts no longer occur after the changes in [libuvc](https://github.com/pupil-labs/libuvc/tree/ebacefa2a4d00970e00414b2e52b3f1511d83389) from @mkassner
