### ISSUE TITLE
Windows bundle tool?

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#597]
Hi,
can u please explain what tool u are using for building your windows bundles?

If u use pyinstaller can you give me your .spec-file? :)

**Comment by willpatera** [comment]
Hi @PolynomialDivision - Yes, we are using `pyinstaller` you can find all `.spec` files within the [deployment](https://github.com/pupil-labs/pupil/tree/master/deployment) directory. Take a look at `bundle.sh` for the commands that you will need to run to make a bundle.

**Comment by PolynomialDivision** [comment]
Hey,
thanks a lot!
I just used MinGW. :P

Works perfectly. :)
