### ISSUE TITLE
Failed to compile pyuvc

### ISSUE THREAD

**Issue by madtulip** [pupil-labs/pupil#599]
On a fresh Ubuntu 16.04 installation i went through the steps detailed here.:

https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Linux

step

$ sudo pip install git+https://github.com/pupil-labs/pyuvc

fails with the following console out.: http://pastebin.com/U51bSHvm

i cant find "luvc.0.0.5" on my system.

It seams that libuvc was build successfully using above instructions though.

**Comment by mkassner** [comment]
I just fixed this. Please to git pull on pyuvc.

**Comment by madtulip** [comment]
Excelent! nominated for the fastest remote bug fix in history.
