### ISSUE TITLE
Missing feed from world camera

### ISSUE THREAD

**Issue by lad211** [pupil-labs/pupil#603]
Hi all,

Sorry to be a nuisance, I know there have been a few students on here recently who have had trouble setting up their software and this must be a pain to keep responding to these. I am however another student in need to help. 

I have managed to get my pupil capture software to open and start, however I cannot get the world camera to detect anything. The eye-camera is working perfectly well, however my computer cannot find the other camera and simply gives me a list of cameras that are all unknown and which the pupil capture software cannot open. 

I am running windows 10 on a Lenovo B50-50, I5 processer. 

Any help would be appreciated, 
Thank you
Lucas

**Comment by mkassner** [comment]
This is for sure a libusbK issue. Please make sure all cameras have the libusb-k driver assigned.

**Comment by lad211** [comment]
I believe I have managed to do this already. It seems to however not show the other camera when I load Zadig, it only gives me the Pupil Cam1 IDO
![eye-tracking driver](https://cloud.githubusercontent.com/assets/25368195/22335829/10abeb54-e3d8-11e6-82b7-385a6135e70f.JPG)

**Comment by lad211** [comment]
To add to this, looking into the processing happening with the software I am getting an error reading:
world - [ERROR] world: Error getting frame. Falling back to Fake source.

Hope this might be of some help,
Thank you

**Comment by mkassner** [comment]
This could be a hardware issue after all. Lets do a quick support call to solve this.

**Comment by iangarnerh** [comment]
Hi All,

I am having almost exactly the same problem as lad211 except I can only see the world camera and I cannot see the eye camera. Can you please let me know if his problem was a hardware problem?

Thanks.

**Comment by mkassner** [comment]
Hi,

so far it turned out every time that this issue come from windows messing around with the drivers. Best is to remove all drivers attached to Pupil Cameras and redo the libusbk driver installation.
