### ISSUE TITLE
How to load saved surface 

### ISSUE THREAD

**Issue by adlinfakhriana** [pupil-labs/pupil#607]
Hi. Before this we have saved surface using plugin offline surface tracker but when we try to load it back in pupil player, it doesnt show up. Is there any steps to be taken to load the surface back in pupil player? :innocent:

**Comment by willpatera** [comment]
Hi @adlinfakhriana - this is a [known issue](https://github.com/pupil-labs/pupil/issues/583) and has been fixed in the master branch and will be incorporated in the `v0.8.8` release. I will close this issue because it has already been raised and resolved.

**Comment by papr** [comment]
Related issues are #583 and #598

**Comment by adlinfakhriana** [comment]
alright thnks ^^
