### ISSUE TITLE
cannot import name set_start_method

### ISSUE THREAD

**Issue by madtulip** [pupil-labs/pupil#608]
Using a fresh installation of Ubuntu 16.04 and following these steps.:

https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Linux
https://github.com/pupil-labs/pupil/wiki/Developer-Setup

the capture software does not start with this error.:

pupil@PupilEyetracker2:~/pupil/pupil_src/capture$ python main.py 
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    from multiprocessing import Process, Value,active_children,freeze_support,set_start_method
ImportError: cannot import name set_start_method

**Comment by papr** [comment]
Dear @madtulip 
You are probably not running python 3. You can confirm this by running `python -V`.

**Comment by madtulip** [comment]
It states "Python 2.7.12". How can i switch to 3?

**Comment by papr** [comment]
Try running `python3 main.py`

**Comment by madtulip** [comment]
thank you very much.

$ python3 main.py

solved it.

have a nice day!
