### ISSUE TITLE
[Windows] Unbearably extensive installation process for Dev-Setup

### ISSUE THREAD

**Issue by Aeefire** [pupil-labs/pupil#612]
When trying to install the dev-setup on windows, in order to build custom plugins, there is a huge dependency-list with a tedious installation process. 

Especially the routines around setting up PyAv require a self-compiled ffmpeg library (which in itself is already a hard-todo process) etc. E.g., PyAv for example, provides python 2.7 wheels but pupil-labs exclusively uses python 3.5 ? 

Is there no way to make this setup easier  / less error prone and tedious ?

**Comment by papr** [comment]
Dear @Aeefire that is not exactly true. :) You can run custom plugins with the pre-compiled bundle as well. The place to put your plugin will be `<home>/capture_settings/plugins/`. The bundle will try to autoload plugins from there.

**Comment by cpicanco** [comment]
@Aeefire have you tried running the bundled app as @papr mentioned?

**Comment by Aeefire** [comment]
Hey, I am aware of this and would thank you for your fast response.

However, if you need additional data e.g. from the eye camera or somehow modify the original source, then the build-setup is really tedious. This should, in no way be a critique to you (as I know how hard is it to setup a cross-platform build environment) but rather a pointer to improve the situation and potentially gain more attention/support by other developers due to an easier developer setup.

**Comment by papr** [comment]
Dear @Aeefire we are aware that the install process is not optimal. This is why we opted for bundles. The next release will include a feature called _non-blocking capture_. It builds on the fact that captures got changed to be plugins as well. This means that you can subclass them in your custom plugin and should be able to load them instead of the default capture.

I am not sure though if the behaviour is as expected. Easiest way to modify the apps is still to run from source.

---

Could you elaborate on the extra eye cam data that you need? maybe this information is already there and I can point you to it.

**Comment by Aeefire** [comment]
> Dear @Aeefire we are aware that the install process is not optimal. This is why we opted for bundles. The next release will include a feature called non-blocking capture. 

While this sounds really nice, I seemingly have found one bad side of it. You can't use non-bundled python modules in your modules, right? I have not gotten it to work (always getting "No module named... found") sadly. Might this be due to the "shipped" python (+dependencies) in the bundle, instead of resolving for installed dependency on the host itself? Or is there a way to direct the bundle to resolve dependencies, which are not shipped with the bundle?

**Comment by papr** [comment]
You can extend your Python path on runtime

```python
import sys
sys.path.append(your_python_path) 
```

**Comment by Aeefire** [comment]
> You can extend your Python path on runtime

Thanks! This made it work... Of course you could define your own windows environment variable pointing to the python install location (which would be the cleaner solution)

`
import os
import sys
sys.path.insert(0, os.getenv('LOCALAPPDATA')+"\\Programs\\Python\\Python35\\Lib\\site-packages") `

**Comment by praneethc** [comment]
Can someone tell me how you guys got around installing PyAV (ffmpeg, etc.)? I'm finding it difficult to figure out how to go about it @Aeefire @papr @cpicanco

**Comment by PolynomialDivision** [comment]
It's written at the bottom of [this page](https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Windows) how you install PyAV.

**Comment by papr** [comment]
Continue windows-install discussion from #598 to keep the issues separated.

-----

@Aeefire Did you make sure that you installed _exactly_ `Visual Studio 2015 Community Update 3`? My intuition says that the screenshot shows symptoms of a broken compiler installation.

**Comment by Aeefire** [comment]
![image](https://cloud.githubusercontent.com/assets/1909527/23559092/3445319a-0036-11e7-985d-b01e49b8efd6.png)
This would basically say it's Update 3, if I am not wrong?

I fixed the last issue by actually building glog/ceres as Release version (which then fits the paths in the setup.py's), which in turn lead me (after more of the above "..is ignored" messages [i.e. i guess successfully compiled modules]) to :
![image](https://cloud.githubusercontent.com/assets/1909527/23559625/de4a4878-0037-11e7-83ae-7516d32f4985.png)

Sadly you don't get the full compiler messages :/

**Comment by papr** [comment]
@Aeefire Oh, my bad. I did not know that `Visual Studio 2015 Community` would have the version number `14.xx` :man_facepalming: 

---

The issue above is encoding related. See https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character
> Consider a text file containing the German word "für" in the ISO-8859-1 encoding (0x66 0xFC 0x72). This file is now opened with a text editor that assumes the input is UTF-8. The first and last byte are valid UTF-8 encodings of ASCII, but the middle byte (0xFC) is not a valid byte in UTF-8.

This should be fixed with #659

**Comment by Aeefire** [comment]
So I applied your fixes, but now I am stuck at the following:
![image](https://cloud.githubusercontent.com/assets/1909527/23578690/187b460a-00dd-11e7-9579-1cdd5a7cf272.png)
So the interesting thing is, that I looked up the packaged installation and could not find any (imho) relevant dlls. Also the .pyd for detector 2d and detector3d are built. Any idea what could not be working?

**Comment by cpicanco** [comment]
Hi, have you tried deleting the build folder?

**Comment by Aeefire** [comment]
Yes, on every run. However, I got it running using https://github.com/pupil-labs/pupil/issues/653#issuecomment-284350165 's *dirty* approach. I guess it should suffice for now.

**Comment by willpatera** [comment]
Hello Windows devs - I have updated windows development instructions for Pupil with Python36 and VS 2017 preview. I have verified that these instructions work on a clean machine (VM). Please see: https://docs.pupil-labs.com/master/#windows-dependencies
