### ISSUE TITLE
'float' object cannot be interpreted as integer

### ISSUE THREAD

**Issue by fosterseth** [pupil-labs/pupil#617]
Windows 10
Capture build 0.8.7.w.20

This happens when enabling video compression. Upon hitting Record, all windows crash except the terminal. When I disable video compression, this error does not occur.

![capture](https://cloud.githubusercontent.com/assets/8745776/22762786/1ae0fdb0-ee2f-11e6-9600-93972a85e252.PNG)

**Comment by willpatera** [comment]
@fosterseth - thanks for the report. I was able to replicate your issue. We will fix this for the upcoming release.
