### ISSUE TITLE
Cannot export videos - "Operation not permitted"

### ISSUE THREAD

**Issue by ogik13** [pupil-labs/pupil#619]
Hey everyone,

Did this happen to anyone? It seems to be happening only on some of the files I try to export. I am not sure why exactly, the error is not specific. The export stops soon after starting so the exported video file is too small and unplayable, and I really need it! 
I am using 0.8.7.w.12 on Windows 10.  The files might have been recorded on the previous Win10 release. Could this be the issue?

This is the error message I get:

Process Export_Process-5:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "exporter.py", line 182, in export
  File "av_writer.py", line 142, in write_video_frame
  File "av\video\stream.pyx", line 86, in av.video.stream.VideoStream.encode (src\av\video\stream.c:2806)
  File "av\video\stream.pyx", line 147, in av.video.stream.VideoStream.encode (src\av\video\stream.c:2496)
  File "av\utils.pyx", line 78, in av.utils.err_check (src\av\utils.c:1539)
av.AVError: [Errno 1] Operation not permitted

Any help is much appreciated!
Ogi

**Comment by mkassner** [comment]
Hi,

I think this has to do with a bug in the previous version of our windows bundle. Some timestamps are repeating. 

The  remedy for this is to fix the `world_timestamps.npy` file. The fix is to write a small script that runs through the timestamps and makes sure that no number repeats. If a number repeated it should be increased by a tiny bit.

**Comment by ogik13** [comment]
Thanks!
Do you have that script, by any chance?

**Comment by papr** [comment]
Dear @ogik13,
yes, we have such a script: https://gist.github.com/papr/92d9cf729ff130e500dfa53bb595f31b

Please be aware that this script overwrites your recording. **Please back up the `world_timestamps.npy` file before using the script.**

This script requires a Python and numpy. You can either execute the script from within your recording directory or you can change the `timestamp_file_path` variable such that it points to the correct file.

**Comment by ogik13** [comment]
Thank you very much, Pablo!

**Comment by mkassner** [comment]
This seems to be resolved. Closing...
