### ISSUE TITLE
[OS X 10.11.6] fatal error: 'type_traits' file not found

### ISSUE THREAD

**Issue by tunazhao** [pupil-labs/pupil#620]
I have installed all the libraries following the guide, and when I was running main.py , the error says,

> `In file included from detector_2d.cpp:515:
In file included from /usr/local/include/eigen3/Eigen/Eigen:1:
In file included from /usr/local/include/eigen3/Eigen/Dense:1:
/usr/local/include/eigen3/Eigen/Core:274:10: fatal error: 'type_traits' file not
      found
#include <type_traits>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1`

I searched the internet and there are instructions telling you to add '-stdlib=libc++' flags to the compiler, but in this case with command lines, how am I going to figure this out?

**Comment by mkassner** [comment]
Could you give some info to your setup? OS, python version? Did you follow the install instructions? My guess is that your setup is slightly differently.

**Comment by mkassner** [comment]
This issue is not codebase related and stale. I will close it. Please make a new issue if required.
