### ISSUE TITLE
[Question] Saving synced Raw Videos

### ISSUE THREAD

**Issue by fosterseth** [pupil-labs/pupil#621]
I noticed the raw eye and world videos are not synchronized, and the software has it's own internal way of doing to synchronization (using the _timestamps.npy files).

Is there a way to get raw synced eye and world videos?

If not, how easy would it be to extend the Video Exporter plugin to output both world and eye videos separately? Would those two videos be synched?

Thanks in advance for taking the time to address my question

**Comment by fosterseth** [comment]
I think I found a solution for myself.

I extracted all images from eye0.mp4 and world.mp4 into separate folders,
`ffmpeg -i world.mp4 -f image2 world_folder/%d.jpg`

I opened the world_timestamps.npy, looped through each timestamp, and found the closest timestamp in eye0_timestamps.npy. I find the corresponding image frame for that eye timestamp, and copy that image to another folder. E.g. image 5 in world_folder/ may be closest to image 10 in eye_folder/

By the end,, we have two folders, world_folder/ and eye_folder_new/ with the same number of frames. We can then just recombine the images into a video using ffmpeg
`ffmpeg -r 62 -f image2 -s 1280x720 -i world_folder/%d.jpg -vcodec mpeg4 world_new.mp4`

This seemed to work -- both videos were synchronized.

I looked into the code a bit. I'm guessing the encoder doesn't provide an accurate PTS (presentation timestamp) when encoding the video.
in av_write.py

```
 #we are setting the packet pts manually this uses a different timebase av.frame!
        packet.dts = int(self.frame_count/self.video_stream.time_base/self.fps)
        packet.pts = int(self.frame_count/self.video_stream.time_base/self.fps)
```

I don't think that is using the system timeclock-derived timestamps at all, but just writes a static timing into the container?

**Comment by mkassner** [comment]
Yes. This is correct. We dont use true PTS during recording but rely on the timestamps.npy files. You can transcode the videos using the timestamps as PTS and the videos will align.
