### ISSUE TITLE
UWP Windows Store Application

### ISSUE THREAD

**Issue by rooi** [pupil-labs/pupil#625]
Hi,

I need to use pupil with a windows store application. The plugin dlls (AsyncIO, MsgPack and NetMQ) in the unity_integration_calibration project do not seem to support UWP/Windows Store Applications.

The unity_integration_calibration project does connect easily with the Pupil Service and I would like to use the same functionality in my UWP/Windows Store Application.

Is UWP support planned, or can someone recommend what the best way forward is for me?

Thanks!

Roy

**Comment by willpatera** [comment]
@rooi UWP support is not a priority for the Pupil project. The [hmd-eyes](https://github.com/pupil-labs/hmd-eyes) project is working on a Unity3d application that will be able to run on HoloLens (UWP constrained environment). I suggest discussing this issue in the hmd-eyes repo.
