### ISSUE TITLE
[Question] DIY Kit -- using Logitech C615 as eye camera

### ISSUE THREAD

**Issue by fosterseth** [pupil-labs/pupil#627]
Bills of materials [link](https://docs.google.com/spreadsheets/u/1/d/1NRv2WixyXNINiq1WQQVs5upn20jakKyEl1R8NObrTgU/pub?single=true&gid=0&output=html) recommends the Logitech C615 for the world camera, but the Microsoft HD-6000 for the eye camera. The C615 is still pretty cheap on amazon, but the HD-6000 is $100+ (I can't buy from ebay unfortunately).

Can I use the C615 for the eye camera as well? Is it too bulky? Is it too difficult to replace the IR blocking filter? Any information would be appreciated, thanks!

**Comment by cpicanco** [comment]
I did not test it. I am using C615 as World Camera and [ELP-USBFHD01M-L21](https://github.com/pupil-labs/pyuvc/issues/10) as Eye Camera. Note: C615 has some annoying [warnings](https://github.com/pupil-labs/pupil/issues/399).

**Comment by papr** [comment]
closed because issue is stale
