### ISSUE TITLE
investigate A/V syncing

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#629]
Run tests on how good A/V syncing is with pupil capture.

Propose fixes if required.

**Comment by lchukoskie** [comment]
Hello! Any progress here?  The engineering team would love to integrate audio triggers into our analyses.  Thanks!

**Comment by mkassner** [comment]
@papr  I know you have been working on this recently. Can you give an update or make a PR?

**Comment by papr** [comment]
If I can remember correctly, I ran into problems with pyAV. We talked about using `libav` directly using Cython. The project has been a bit on the sideline since then. The current state can be found here:
https://github.com/papr/pupil/tree/audio_sampler

**Comment by papr** [comment]
Fixed with #719 See https://docs.pupil-labs.com/master/#audio-capture for more information
