### ISSUE TITLE
Marker Detector - 3D Localization switch triggers crash  

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#63]
Marker Detector `3D localization` toggle triggers a crash when pressed without calibrating the camera. Obviously, `3D localization` requires a calibrated camera, but the switch `locate_3d` should be set to `read_only` if the user has not yet calibrated the camera (if `self.camera_intrinsics` is `None`).

**Comment by willpatera** [comment]
Quick fix here https://github.com/pupil-labs/pupil/commit/91ed5c6e713ee491b49b182013ff034e7b9a0916

Made the toggle read only if no intrinsics on load.

**Comment by mkassner** [comment]
good.

**Comment by cpicanco** [comment]
hey guys, it is related to it:
```bash
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    main()
  File "main.py", line 136, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/bin/pupil/pupil_src/capture/world.py", line 316, in world
    p.update(frame,events)
  File "/home/rafael/bin/pupil/pupil_src/shared_modules/marker_detector.py", line 191, in update
    s.locate(self.markers, self.locate_3d,self.camera_intrinsics)
  File "/home/rafael/bin/pupil/pupil_src/shared_modules/reference_surface.py", line 230, in locate
    K,dist_coef,img_size = camera_intrinsics
TypeError: 'NoneType' object is not iterable
```

**Comment by willpatera** [comment]
@cpicanco - Yes, this error is raised when `camera_intrinsics` is `None` -- it should be fixed at the above listed commit -- see changes in the diff.
