### ISSUE TITLE
Question: Pupil Detector 2d - Parameter Optimization extends to Calibration algorithms?

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#633]
Hi, I was reading the v0.9.0  ( ac5cbcc ) release notes and I am wondering if the circle detection during calibration procedure could also be optimized folowing the approach used to pupil detector 2d.

PS.: Congratulations for the release! You are awesome!

**Comment by mkassner** [comment]
Hi,

It would if we have a dataset of hand labeled circle images :-).

**Comment by cpicanco** [comment]
Thank you!
