### ISSUE TITLE
error when running run_capture.bat for the first time after installation (OS: Windows 10)

### ISSUE THREAD

**Issue by joohwankim** [pupil-labs/pupil#635]
Hi,

I am so glad that pupil-labs now supports Windows 10 and I have installed all the dependencies as written in the instruction. When running for the first time, I get the following error. Any idea on how to resolve it?

E:\pupil-labs\pupil\pupil_src\capture>python main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.0.13
world - [INFO] world: System Info: User: sckim, Platform: Windows, Machine: SCKIM-DT1, Release: 10, Version: 10.0.10586
world - [INFO] pupil_detectors.build: Building extention modules...
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
cl : Command line warning D9002 : ignoring unknown option '-O3'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
Process world:
Traceback (most recent call last):
  File "C:\Users\sckim\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\sckim\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pupil-labs\pupil\pupil_src\capture\world.py", line 94, in world
    import pupil_detectors
  File "E:\pupil-labs\pupil\pupil_src\capture\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "E:\pupil-labs\pupil\pupil_src\capture\pupil_detectors\build.py", line 24, in build_cpp_extension
    ret = sp.check_output(build_cmd.format(sys.executable, install_loc), shell=True).decode()
  File "C:\Users\sckim\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\sckim\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'C:\Users\sckim\AppData\Local\Programs\Python\Python35\python.exe setup.py install --install-lib=E:\pupil-labs\pupil\pupil_src\capture' returned non-zero exit status 1

Thanks.

**Comment by willpatera** [comment]
@joohwankim It appears that the pupil detectors did not build. This issue is related to one or more of the following:

- Cython version - What version of `Cython` do you have installed? 
- Ceres and OpenCV - Dependencies like Ceres, Eigen, and OpenCV not being properly built or paths not correctly specified.
- External Dependencies - Do you have all required external dependencies included in the `pupil_external` directory. You should have:
  - `avcodec-57.dll`
  - `avdevice-57`
  - `avfilter-6.dll`
  - `avformat-57`
  - `avutil-55.dll`
  - `glew32.dll`
  - `glfw3.dll`
  - `opencv_world300.dll`
  - `postproc-54.dll`
  - swresample-2.dll`
  - `swscale-4.dll`

**Comment by joohwankim** [comment]
@willpatera Thanks for the reply. I am checking...

**Comment by joohwankim** [comment]
Versions of cython and opencv, I am copying the command and responses from the system below:

>>> import cython
>>> cython.__version__
'0.24.1'
>>> cv2.__version__
'3.2.0'

For Ceres, I followed the instruction as in the Dependency page and the paths are correctly set. Is there any way for me to test it? Looks like ceres is not a python module and I can't test it as with openCV.

For external dependencies, I followed all the instructions in the 'dependency for windows' page but I only have glfw3.dll and opencv_world310.dll (it is not 300, but I was thinking it is fine). For all other dll files, where should I locate them?

**Comment by joohwankim** [comment]
We were able to build the detector. Now the error is different.

E:\pupil-labs\pupil\pupil_src\capture>python main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.0.13
world - [INFO] world: System Info: User: sckim, Platform: Windows, Machine: SCKIM-DT1, Release: 10, Version: 10.0.10586
E:\pupil-labs\pupil\pupil_src\capture\pupil_detectors
C:\Users\sckim\AppData\Local\Programs\Python\Python35\python.exe setup.py install --install-lib=E:\pupil-labs\pupil\pupil_src\capture
world - [INFO] pupil_detectors.build: Building extention modules...
Process world:
Traceback (most recent call last):
  File "C:\Users\sckim\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\sckim\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pupil-labs\pupil\pupil_src\capture\world.py", line 94, in world
    import pupil_detectors
  File "E:\pupil-labs\pupil\pupil_src\capture\pupil_detectors\__init__.py", line 19, in <module>
    from .detector_3d import Detector_3D
ImportError: DLL load failed: The specified module could not be found.

Could you help us by giving any advices?

**Comment by joohwankim** [comment]
We found some dlls, but they are (strangely) all different in version number by 1. Here I list them.

◦ avcodec-56.dll 
◦ avdevice-56.dll 
◦ avfilter-5.dll 
◦ avformat-56.dll
◦ avutil-54.dll 
◦ glew32.dll 
◦ glfw3.dll 
◦ opencv_world310.dll 
◦ postproc-53.dll 
◦ swresample-1.dll 
◦ swscale-3.dll 


Can it cause problem? When I run run_capture.bat it complains about dlls.

**Comment by joohwankim** [comment]
In the release page there is pyuvc 0.9, but the code tries to assert version 0.91. When we get around that assertion error by changing 0.91 to 0.9 in the code, it can not access to the camera, complaining about error in libuvc. So I wonder whether you can create a wheel for pyuvc 0.91, which seems to be necessary?

**Comment by PolynomialDivision** [comment]
I have the same problem.
After merging the newest changes in my fork I'm getting the same error

    Process world:
    Traceback (most recent call last):
      File "C:\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
        self.run()
      File "C:\Python35\lib\multiprocessing\process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Users\xxx\pupil_windows_fork\pupil_src\capture\world.py", line 94, in world
        import pupil_detectors
      File "C:\Users\xxx\pupil_windows_fork\pupil_src\capture\pupil_detectors\__init__.py", line 16, in <module>
        build_cpp_extension()
      File "C:\Users\xxx\pupil_windows_fork\pupil_src\capture\pupil_detectors\build.py", line 24, in build_cpp_extension
        ret = sp.check_output(build_cmd.format(sys.executable, install_loc), shell=True).decode()
      File "C:\Python35\lib\subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "C:\Python35\lib\subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'C:\Python35\python.exe setup.py install --install-lib=C:\Users\xxx\pupil_windows_fork\pupil_src\capture' returned non-zero exit     status 1

Cython:
Version: 0.25.2

I copied all the dlls to pupil_external.

**Comment by willpatera** [comment]
@joohwankim - I will upload the wheel for `pyuvc` later today - but before making an official release I want to resolve this issue: https://github.com/pupil-labs/pyuvc/issues/28

Therefore I will attach the wheel here (contained within a .zip folder for purposes of upload to this issue) so that you can use it without waiting for the above issue to be resolved. 

[uvc-0.91.zip](https://github.com/pupil-labs/pupil/files/809721/uvc-0.91.zip)

**Comment by willpatera** [comment]
Hi @joohwankim - updated `pyuvc` version and wheel. Wheel is available here: https://github.com/pupil-labs/pyuvc/releases/tag/v0.10

**Comment by joohwankim** [comment]
@willpatera Thanks! Now I am not suffering from libuvc error any more. However, there still is a problem, probably further down the road (hopefully this is very close to the end!). Now the message in the command prompt is like the following.

eye1 - [INFO] pupil_detectors.build: Building extention modules...
eye1 - [INFO] eye: Session setting are from older version of this app. I will not use those.
eye1 - [WARNING] eye: Process started.
eye1 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye1 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID1.
eye1 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye1 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID1.

And then it repeats the warning and info infinitely. Any insight on what's going on and how to resolve it?

@PolynomialDivision From the message you pasted it is not clear whether you are suffering from the same problem as I did... And it is fading away in my head regarding what we had done. Two things I remember though are, 1. We had to ignore 3d modeling, and 2. We had to change the pyuvc version requirement in shared_modules/video_capture/uvc_backend.py

**Comment by itayse** [comment]
Hi @joohwankim 
 
Any luck with this issue?
I'm experiencing the same issue of - 
video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
while trying to work with Logitech c920 camera for the world view

Thanks in advance

Itay

**Comment by kktheballer** [comment]
Hi Joohwankim,

   I am consistently getting the same error; error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2                         when I try to run run_capture.bat. I am not sure what to do about this at all. How did you eventually fix this? can you please let me know? Thank you.

**Comment by willpatera** [comment]
Hello Windows devs - I have updated windows development instructions for Pupil with Python36 and VS 2017 preview. I have verified that these instructions work by installing everything from zero on a clean machine (VM). Please see: https://docs.pupil-labs.com/master/#windows-dependencies
