### ISSUE TITLE
sample_threshold in fixation detection

### ISSUE THREAD

**Issue by anligert** [pupil-labs/pupil#637]
There is a bug in In **fixation_detector.py** :

For this example we define *min_duration* as 0.15 [in seconds] through the GUI.

l. 171
```python
 sample_threshold = self.min_duration * 3 *.3 #lets assume we need data for at least 30% of the duration
```
will give a 90% of min_duration. This is not what is stated in the comment. 
Nevertheless this seems not sufficient: It will give us the sample_threshold in sec, eg. 0.15sec\*3\*.3 = 0.135 sec. But a sample threshold should be in samples.

l. 198  
```python
 [...] and len(fixation_support) > sample_threshold
```
will therefore always be true, as the number of samples will be at least 1 (as it is a list of samples belonging to fixation).

-> The problem is, that the sample_threshold is given in sec, not in samples. If it was given in samples, it would have to be dependent on the (current? variable?) sampling frequency.

**Comment by papr** [comment]
Dear @anligert 
Sorry for the delayed response. You are right. The `3` in l. 171 was supposed to be a `30` (and therefore assume a frame rate of 30 Hz). The correct way to solve this is to ask the current capture for its frame rate and use it to calculate the minimal amount of samples from that.
