### ISSUE TITLE
Hint Documentation

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#64]
Do you ever think about a 'Hint' functionality? (stay over 2.0s and the hint show up until user exits the control) Would be great and could clean up a little bit some controls.

...
Enhancement
from: #57

**Comment by willpatera** [comment]
@cpicanco "hints" or "tooltips" would be a feature request for [pyglui](https://github.com/pupil-labs/pyglui). 

One problem with your suggestion - hovering assumes you have a mouse. For touch there is no real hover - so this wouldn't be an ideal pattern for the future. 

Another option is just to create a button with a question mark `?` or info `i` mark where needed to show/hide the help text within the bar. Or to use this button to trigger a pop-over text box with help text. 

Let's move this discussion to pyglui though.

**Comment by cpicanco** [comment]
Ok, @willpatera. Indeed, hovering is not good for touching devices. I will just close this issue since I hadn't had a better idea.
