### ISSUE TITLE
Extracting Data

### ISSUE THREAD

**Issue by kamiartik** [pupil-labs/pupil#640]
I cannot find the pupil_positions.csv file in the recordings folder. How can I see the data?

**Comment by papr** [comment]
Dear @kamiartik, did you export the recording with Pupil Player?

**Comment by kamiartik** [comment]
Yes. I have a video inside the export folder.

**Comment by mkassner** [comment]
Make sure to have a raw data exporter plugin open in player

**Comment by kamiartik** [comment]
I can't see that plugin. How can I get it?

**Comment by cpicanco** [comment]
Raw data exporter->
![screenshot from 2017-02-22 11-27-09](https://cloud.githubusercontent.com/assets/6511849/23215740/2cd7bd1a-f8f2-11e6-8099-ff94669a8c47.png)

**Comment by kamiartik** [comment]
Okay. Thank you very much

**Comment by chalwanna** [comment]
thank you
