### ISSUE TITLE
FFMPEG does not seek properly.

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#641]
When seeking backwards, the seek indicator moves forward.

**Comment by mkassner** [comment]
@papr  please try this on your machine.

**Comment by papr** [comment]
Can confirm improvement.

**Comment by papr** [comment]
Problem: Current position jumps around after seeking.
Pupil Recording: Sample dataset from pupil-labs.com/pupil
Screen recording of the problem: [Google Drive](https://drive.google.com/file/d/0B_Y6kGV4Sb5bbUV3TlBzQTI5MjQ/view?usp=sharing)
Player Version: 0.9.2

**Comment by mkassner** [comment]
This is because seeking /mjpeg is easy. Seeking h264 is hard. The demo recording is h264. I m not sure what the best way do this for all media types is.

**Comment by papr** [comment]
Ideally Player would look for the closest key frame that is before the target timestamp and apply diff frames until the target is reached

**Comment by mkassner** [comment]
all this is taken care of by ffmpeg. We just need to use it right.

**Comment by papr** [comment]
[`av.InputContainer.seek`](http://mikeboers.github.io/PyAV/api.html#av.container.InputContainer.seek) has the `any_frame` kwarg that sets [`AVSEEK_FLAG_ANY`](https://ffmpeg.org/doxygen/3.0/avformat_8h.html#a998c3af80d050fd3d4f6a209fd5a87bc):
> seek to any frame, even non-keyframes

Setting `any_frame` to `True` will result in following error messages during seeking:

```log
Player [ERROR] libav.h264 : decode_slice_header error
Player [ERROR] libav.h264 : decode_slice_header error
Player [ERROR] libav.h264 : decode_slice_header error
Player [ERROR] libav.h264 : mmco: unref short failure
Player [ERROR] libav.h264 : Missing reference picture, default is 65510
Player [ERROR] libav.h264 : mmco: unref short failure
Player [ERROR] video_capture.file_backend : Frame index not consistent.
Player [ERROR] video_capture.file_backend : Frame index not consistent.
Player [ERROR] libav.h264 : co located POCs unavailable
Player [ERROR] libav.h264 : co located POCs unavailable
Player [ERROR] libav.h264 : mmco: unref short failure
Player [ERROR] video_capture.file_backend : Frame index not consistent.
```

Maybe `File_Source.idx_to_pts()` is not working correctly. Maybe we should try to change the seek mode from `time` to `frame`.

**Comment by mkassner** [comment]
I can set any_frame to true and it works on the sample data for me. 

seek mode frame is much slower for me. 
idx_to_pts is trivially computed and should be fine.

seeking is non trivial I suggest we test this in the office and compare ffmepg versions and video file.

**Comment by mkassner** [comment]
Fixed for mjpeg videos. Still an issue for h.264 but this is really  a pyav/ libav issue.

**Comment by camenduru** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210922172914.17914-4-cus@passwd.hu/
