### ISSUE TITLE
pupil plugin dependencis with ubuntu package

### ISSUE THREAD

**Issue by Lahorde** [pupil-labs/pupil#646]
How can I add some dependencies to a pupil plugin?
On machine where I installed pupil from sources I did not have any issue. I could install a python specific package and use it in my plugin.
On another machine, I installed pupil from ubuntu package. I copied my plugin to `~/pupil_capture_setting/plugins` and I installed required specific python dependencies using pip. But my plugin does not load, required python dependency is not found. Python package is correclty installed to `/usr/local/lib/python2.7/dist-packages/` as pyglui . I can load it manually using python shell, but pupil plugins can't.

**Comment by cpicanco** [comment]
Hi, are you running bundles or from source? Bundles is it right? So Try:

```
import sys
sys.path.append('/usr/local/lib/python2.7/dist-packages/')

# import your dependencies
```

**Comment by Lahorde** [comment]
I'm running from bundle. Your suggestions solved partially my problem. Plugin can be loaded but I cannot  call anymore some functions from `pkg_resources` package 
When I call `pkg_resources.get_distribution(my_package').version` I get `DistributionNotFound: my_package`

**Comment by mkassner** [comment]
Hi,

you need to append the sys.path in your plugin to include local site
packeges. Then this should work.

Best,
Moritz

**Comment by Lahorde** [comment]
Now, package can be imported but after, in plugin code, when I call `pkg_resources.get_distribution(my_package').version` I get `DistributionNotFound: my_package` 
With this solution I cannot get during runtime package revision for packages in path added using `sys.path.append('/usr/local/lib/python2.7/dist-packages/')`

**Comment by willpatera** [comment]
@Lahorde, what package or packages are you trying to use in your plugin? Can you share a gist with sample plugin code so that others can give you concrete feedback?

**Comment by Lahorde** [comment]
[Here is plugin code](https://github.com/Lahorde/pupil-labs-usybus-controller/blob/master/pupil_usybus_controller.py)

**Comment by mkassner** [comment]
Ah ok,

you are querying pkg_resources which does not point to the one on your system but the pupil bundle. Can you call this in system python and copy/paste the output into the plugin. Would that work?

**Comment by Lahorde** [comment]
I got __version__ attribute from my packager. Issue with pkg_resources was minor.
Thanks for your help.
