### ISSUE TITLE
0.9.1 release links NOT working

### ISSUE THREAD

**Issue by matiarj** [pupil-labs/pupil#648]
the release links for v0.9.1 are not working and are down...

**Comment by willpatera** [comment]
@matiarj - I can not replicate this issue. Releases are here: https://github.com/pupil-labs/pupil/releases/tag/v0.9.1

**Comment by matiarj** [comment]
s3.amazonaws was down earlier today that's what it was

**Comment by willpatera** [comment]
@matiarj - Yes, I also thought that could be a cause of the problem. However, github's status report does not report any downtime: status.github.com
