### ISSUE TITLE
user_calibration_data should not be overwritten

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#649]
**Disclaimer**: It is very well possible that I missunderstood many things of how the pupillabs code work, simply correct me then, thanks :). We are mainly using 2D detection due to backwards compatibility with older data. I did not see if 3D works differently, but I did not check that.

Whenever you record your data, the function `on_pupil_datum` (gaze_mapper) applies the calibration to the sample. It also directly combines both eyes. At the end, the samples used for the calibration are saved to 'user_calibration_data'.

Unfortunately it is very common to have multiple calibrations. But currently `user_calibration_data` is overwritten whenever you make a calibration.

What I would like to have from pupil-labs: either append calibration data with a calibration ID (or alternatively one could work backwards from the timestamps, but it is more difficult) or simply write multiple files and don't overwrite the calibrations.
I can then write a custom function to do the offline re-calibration.

Our main goal is to apply the calibration by ourselves, because we want to have the data of both eyes separated (even though recorded in binocular mode).

**Comment by papr** [comment]
Hey @behinger 👋 
You could write a simple plugin that copies the `user_calibration_data` file as needed on receiving the `calibration.should_start` notification.

But you need to keep in mind that the 2D calibration is very sensible to slippage. Therefore, you should always calibrate the headset after putting it on.

Warm regards to you and the other Coxis :)
Pablo

**Comment by behinger** [comment]
Hey @papr!
Thanks for the fast response! We had performance issues with 3D calibration in the past but will check it out again. 

The plugin will solve **my** specific problem. But why keep the latest user calibration data in the first place? I think you should really keep ALL calibration data available somehow. In the past we had to manually change the calibration (with an eyelink though) in an experiment and we were very glad to have the necessary matrices available.

**Comment by papr** [comment]
There is no way to automatically detect who is wearing the headset. Therefore we cannot know which calibration data to load. And therefore it does not make sense to store them.

Could you explain with a specific example where this would be useful? And how would you know whose calibration data it is?

**Comment by behinger** [comment]
There is a simple missunderstanding. We (and most experiments) use a scenario with just a single observer. In an one hour experiment you calibrate multiple times (usually every ~5min depending on slippage etc.). 
Thus there are multiple calibrations in the same recording file with the same observer.
Of course one could also start/stop the recording before every calibration, but again, why keep a single calibration if it is not necessarily the same for the whole recording?


To the auto-load: This is simple, check the timestamps when your data was recorded and when the calibration was saved, use the calibration for all timestamps after the last calibration-timestamp.
in your scenario you do not care who wore the headset, just what calibration to apply at what time.

**Comment by papr** [comment]
@behinger Ah, thank you for the clarification! So your actual feature request is that _during a recording_ the user calibrations should be stored separately, correct?

**Comment by behinger** [comment]
Yes exactly. Sorry for the confusion, one shouldn't write issues so late in the evening ;)

**Comment by papr** [comment]
Ok, great. :)

**Comment by behinger** [comment]
Hey! That is great. I do have one question to the solution: Does the recording need to be running during the calibration so that the calibration is saved?

**Comment by papr** [comment]
Dear @behinger 
After each successful calibration, the calibration point cloud will be published within a `calibration.calibration_data` notification which will be stored automatically by the recorder in the `pupil_data`.

If you want to access all point clouds, you need to open `pupil_data` (Python pickled dictionary, look at `load_object` in `file_methods.py` for more information), access the `notifications` field, and filter by `subject` `calibration.calibration_data`.

This feature is available with 7039ead and following

**Comment by cpicanco** [comment]
This sounds great!

**Comment by papr** [comment]
With f26dca5d12d9e30a5a3443b2ac1dc93bb85f04df the recorder also creates an initial `calibration.calibration_data` notification (if a previous calibration could be found) when starting a recording.

This way you can calibrate outside of a recording or inside a recording.

**Comment by cpicanco** [comment]
@papr, as far as I am understanding, after a successful calibration during a recording, the cloud points inside `calibration.calibration_data` will be  stored automatically by the recorder inside `pupil_data`. So why pupil player is not looking inside `pupil_data` before saying that "no calibration was found"?

**Comment by papr** [comment]
Are we talking about user calibration or camera calibration. Secondary is copied into `world.intrinsics`

**Comment by cpicanco** [comment]
User calibration

**Comment by papr** [comment]
Would you mind to provide the log messages? As far as I know, the Player does not load user calibration data.

**Comment by cpicanco** [comment]
> As far as I know, the Player does not load user calibration data.

Humm.. So I think I have wrongly interpreted your previous comment:

> After each successful calibration, the calibration point cloud will be published within a calibration.calibration_data notification which will be stored automatically by the recorder in the pupil_data.

**Comment by cpicanco** [comment]
@papr , so it is for capture only. The Player will not load calibration data (by design?), users must load a plugin for that.... May ask if "Pupil from recording" and "Gaze from recording" plugins will also load calibration data?
