### ISSUE TITLE
Missing unknown .dll while starting capture

### ISSUE THREAD

**Issue by madtulip** [pupil-labs/pupil#653]
After walking through the dependency installation for windows ( https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Windows )

im stuck with this missing dll (see below). It did compile so i guess i miss the PATH to some .dll. The error doesnt state which .dll is missing. How can i track down which .dll was not found? The extra_objects from detector_3d.cpp are all in my PATH.:
`        "extra_objects": [
            "",
            "C:\\Program Files\\opencv\\build\\x64\\vc14\\lib\\opencv_world310.lib",
            "",
            "C:\\Program Files\\ceres-windows\\x64\\Release\\ceres_static.lib",
            "C:\\Program Files\\ceres-windows\\x64\\Release\\libglog_static.lib",
            "",
            ""
        ],`

`Process world:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\pupil\pupil_src\capture\world.py", line 94, in world
    import pupil_detectors
  File "C:\pupil\pupil_src\capture\pupil_detectors\__init__.py", line 19, in <module>
    from .detector_3d import Detector_3D
ImportError: DLL load failed: The specified module could not be found.`

**Comment by Aeefire** [comment]
Have you checked that you actually built the ceres / glog as "Release" and not "Debug" ? This would explain missing libraries. 

Other than that, I repeatedly had this error message after not building modules successfully and not cleaning the build directory (the build script does NOT do that for you)! So you might want to remove the build directories from pupil detectors first, to reveal the real issue.

**Comment by madtulip** [comment]
Thanks for the input. I solved it before the weekend in a very elegant way.

I just ductaped over all the .lib, .dll and .pyd from the compiled pupil release (all in one folder and set that folder in the PATH). That elegant approach worked at once and i didnt take the time to go through what was actually missing.

See my final sophisticated and elaborated construction here.:
https://thumbs.dreamstime.com/z/bretterbude-15062097.jpg

Anyway, i would like to suggest a 3rd intermediate compilation status release of the pupil code.
I would contain all the dlls and wheels but uncompiled .py scripts for the capture and recording programm. That would be much faster to install and still be flexible for modification (of the main programm code) for most users. IF someone realy wants to modify the source of the dependencies than thouse wheels and dlls could be rebuild on a "as required" basis - its described in the source code version anyway. I believe that to be a good tradeoff between flexibility and useability. my 2 cents afte messing with this for 2 days.

**Comment by Aeefire** [comment]
Hey,

I am basically now suffering from a similar issue as you. Could you take a screenshot of which dlls/pyds you exactly added to PATH?

Would be very much appreciated.

Thanks!

**Comment by madtulip** [comment]
**Below approach is extremly dirty and not a recommended solution!**

I checked again, and you dont need anything added to your system path. I moved all files from C:\pupil_v091_windows_x64\pupil_capture_v091 (my installation of the precompiled pupil code version) to C:\pupil\pupil_external (my installation of the pupil source code). This pupil_external directory is added to the temporary path when C:\pupil\pupil_src\capture\run_capture.bat is executed automatically.

I uploaded my installation of the source code directory C:\pupil\ to dropbox. It already contains the precompiled low level pupil software python functions.:

https://www.dropbox.com/s/r3qn6eu109zykkc/pupil.zip?dl=0

This should run if you have installed the pupil camera drivers, python and all required python wheels.

If you need to recompile the lower level functions like pupil eye detector again, you have to install the dependencies as described here.: https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Windows

You can edit some of the higher level functions like eye.py and world.py in C:\pupil\pupil_src\capture though.

I think there should be a code version of the pupil software which contains the camera driver, the required libraries, theire precompiled form, and all python wheels so that you can right out of the box run C:\pupil\pupil_src\capture\run_capture.bat . It would install all wheels if not detected, compile the pupil code if not already compiled and then run the programm. This toolchain and its instructions are imo a severe mess.

**Comment by papr** [comment]
@willpatera Were you able to fix this issue?

**Comment by mkassner** [comment]
stale
