### ISSUE TITLE
Windows drivers do not support audio recording with LT C930e

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#655]

**Comment by mkassner** [comment]
This must be because we are replacing the driver on the PID level. We have to replace the driver at the subdevice level or mark this as wont_fix.

**Comment by papr** [comment]
The actual reason is that audio capture is not implemented on Windows. Closed in favor of #726

**Comment by papr** [comment]
My previous comment is wrong. Our drivers remove dshow support.
