### ISSUE TITLE
Cannot Compile on Ubuntu Xenial: detector_2d.

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#658]
We are currently trying to run pupil capture from source. We have a fresh ubuntu with python3 in an virtual env. 
If I remove the pupil detectors from their respective `__init__.py` capture runs (player runs as well). 

**The Problem:**
At compiling the pupil detectors we get the following error:
```
ImportError: /home/experiment/Desktop/pupil/pupil_src/capture/pupil_detectors/detector_2d.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7ellipseERKNS_17_InputOutputArrayERKNS_11RotatedRectERKNS_7Scalar_IdEEii
```

We tried searching here & in the google group. 

We deleted the `*.so` and the build folder and recompiled. I had a look at setup.py, the opencv paths are non-existing folders if that is important,  we compiled opencv3.2 as in the instructions.

There was one problem with installation was when trying to add the bugfix for `suitesparse` (for the 3D-detector)

```
sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687
```
When we run `sudo apt-get update` we get:
```
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

As this package is only used for the 3D detector, we could live without it for a start. The trouble we are running into is already at the 2D detector level.

Thanks a lot for your help. We feel we are very close.
Best,
Benedikt

**Comment by mkassner** [comment]
Hi,

I think you still have opencv2 installed and our detector is using that
instead of opencv3. Please remove opencv2 as well as the detector.so files
and try again

Best,
Moritz

**Comment by behinger** [comment]
Hi Moritz,
indeed deinstalling all open-cv applications using:
```
sudo apt-get autoremove opencv-doc opencv-data libopencv-dev libopencv2.4-java libopencv2.4-jni python-opencv libopencv-core2.4 libopencv-gpu2.4 libopencv-ts2.4 libopencv-photo2.4 libopencv-contrib2.4 libopencv-imgproc2.4 libopencv-superres2.4 libopencv-stitching2.4 libopencv-ocl2.4 libopencv-legacy2.4 libopencv-ml2.4 libopencv-video2.4 libopencv-videostab2.4 libopencv-objdetect2.4 libopencv-calib3d2.4 
```
worked for this error.

Is it possible to get a compiler warning if a wrong opencv version is found? That could be very helpful.

-----
Not sure if I should open a new issue for this error, but it is related to our setup.

We are struggeling a bit with UVC now.  The errors are a bit opaque. 

Starting capture only with world camera seems to work kind of ok. At first it usually gives some errors:
```
world - [ERROR] uvc: Could not init 'Hue'! Error: Error: No such device.
world - [ERROR] uvc: Could not init 'Saturation'! Error: Error: No such device.
world - [ERROR] uvc: Could not init 'Sharpness'! Error: Error: No such device.
world - [ERROR] uvc: Could not init 'Gamma'! Error: Error: No such device.
world - [ERROR] uvc: Could not init 'White Balance temperature'! Error: Error: No such device.
world - [ERROR] uvc: Could not init 'White Balance temperature,Auto'! Error: Error: No such device.
```
After restarting the uvc-plugin (klicking on 'local usb'). World seems to run ok.

But after starting an eye processes usually the worldcam freezes. Sometimes the worldcam gets lost, reconnects and then the complete eye-window is frozen. 
```
eye0 - [INFO] pupil_detectors.build: Building extention modules...
world - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye0 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
eye0 - [WARNING] eye: Process started.
eye0 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID0.

```

Any thoughts?

If I manually select cameras, I also often get this error: 
```
  File "pyglui/ui.pyx", line 169, in pyglui.ui.UI.update (pyglui/ui.cpp:9233)
  File "pyglui/ui.pyx", line 137, in pyglui.ui.UI.handle_input (pyglui/ui.cpp:8730)
  File "pyglui/menus.pxi", line 525, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.cpp:43091)
  File "pyglui/menus.pxi", line 542, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.cpp:42872)
  File "pyglui/menus.pxi", line 360, in pyglui.ui.Growing_Menu.handle_input (pyglui/ui.cpp:39985)
  File "pyglui/menus.pxi", line 370, in pyglui.ui.Growing_Menu.handle_input (pyglui/ui.cpp:39844)
  File "pyglui/ui_elements.pxi", line 409, in pyglui.ui.Selector.handle_input (pyglui/ui.cpp:20253)
  File "pyglui/ui_elements.pxi", line 420, in pyglui.ui.Selector.handle_input (pyglui/ui.cpp:20095)
  File "pyglui/ui_elements.pxi", line 439, in pyglui.ui.Selector.finish_selection (pyglui/ui.cpp:20549)
  File "pyglui/ui.pyx", line 332, in pyglui.ui.Synced_Value.value.__set__ (pyglui/ui.cpp:45324)
  File "/root/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 390, in activate
    if not uvc.is_accessible(source_uid):
  File "uvc.pyx", line 823, in uvc.is_accessible (uvc.c:20373)
ValueError: Device with uid: '3:77' not found
```
This is why I suspect uvc to be problematic.

I reinstalled pyuvc and it did not help.

**Comment by mkassner** [comment]
Hi,

these errors are a bit strange and seem hardware related. What computer are you using? What resolutions are the cameras running?

Also does the bundle work for you?

**Comment by behinger** [comment]
Hi!
Its an Dell e6440 (i5-4300M,Intel® Haswell Mobile). I was just now running the world at 640x480@30fps, one eye at 320x240@30fps (to get CPU load to a minimum). Surprisingly this worked. As soon as I get the second camera into play, it crashes:
```
world - [WARNING] plugin: Fixation_Detector_3D: Update will be deprecated soon. Use 'recent_events instead.'
eye0 - [INFO] pupil_detectors.build: Building extention modules...
eye0 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 205 / 256. 
eye0 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye0 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID0.
Estimated / selected altsetting bandwith : 205 / 256. 
eye1 - [INFO] pupil_detectors.build: Building extention modules...
eye1 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 579 / 800. 
world - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye1 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye0 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye1 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID1.
eye0 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID0.
world - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID2.
Estimated / selected altsetting bandwith : 579 / 800. 
Estimated / selected altsetting bandwith : 205 / 256. 
Estimated / selected altsetting bandwith : 302 / 800. 
```

**Comment by mkassner** [comment]
What Pupil hardware are you using?

**Comment by mkassner** [comment]
more specifically what usb connection?

**Comment by behinger** [comment]
Pupil hardware should be the first version after the developers version. We use a USB3.0 connector 
(maybe it helps to mention that these are the tracker of the Institute of Cognitive Science)

**Comment by mkassner** [comment]
Hi,

so the eye tracker has a USB-C or a micro-usb port?

**Comment by behinger** [comment]
micro-usb

**Comment by mkassner** [comment]
Ah ok. In that case it is a USB2.0 power issue. You have two options:

1) Upgrade your headset with this: https://pupil-labs.com/cart/?0_product=usbcupgrade&0_qty=1
2) Get a usb3.0 hub and connect that in between.

That should solve your issue.

**Comment by IngaIbs** [comment]
Hi! 
@behinger and I found out that adjusting the paths
opencv_library_dir & opencv_include_dir to the right locations (.../opencv/build/lib,.../opencv/build/include) in pupil_src/capture/pupil_detectors/setup.py also solves  the issue with the detector2d import error.

**Comment by Amahmoud1994** [comment]
> We are currently trying to run pupil capture from source. We have a fresh ubuntu with python3 in an virtual env.
> If I remove the pupil detectors from their respective `__init__.py` capture runs (player runs as well).
> 
> **The Problem:**
> At compiling the pupil detectors we get the following error:
> 
> ```
> ImportError: /home/experiment/Desktop/pupil/pupil_src/capture/pupil_detectors/detector_2d.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7ellipseERKNS_17_InputOutputArrayERKNS_11RotatedRectERKNS_7Scalar_IdEEii
> ```
> We tried searching here & in the google group.
> 
> We deleted the `*.so` and the build folder and recompiled. I had a look at setup.py, the opencv paths are non-existing folders if that is important, we compiled opencv3.2 as in the instructions.
> 
> There was one problem with installation was when trying to add the bugfix for `suitesparse` (for the 3D-detector)
> 
> ```
> sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687
> ```
> When we run `sudo apt-get update` we get:
> 
> ```
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ```
> As this package is only used for the 3D detector, we could live without it for a start. The trouble we are running into is already at the 2D detector level.
> 
> Thanks a lot for your help. We feel we are very close.
> Best,
> Benedikt


I still have the same problem even after following the answers. I have this message when I try to run the main.py file

`sudo python3 main.py`

`world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/obad/pupil-1.8/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/home/obad/pupil-1.8/pupil_src/shared_modules/pupil_detectors/__init__.py", line 18, in <module>
    from .detector_2d import Detector_2D
ImportError: /home/obad/pupil-1.8/pupil_src/shared_modules/pupil_detectors/detector_2d.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv12findContoursERKNS_17_InputOutputArrayERKNS_12_OutputArrayEiiNS_6Point_IiEE

world - [INFO] launchables.world: Process shutting down.` 

I did this [tutorial] (https://github.com/pupil-labs/pupil-docs/blob/master/developer-docs/linux.md) 3 times already 
Any help?
