### ISSUE TITLE
Add a "Plugins Menu"

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#66]
Why not a "Plugins Menu" with a button for each plugin? Is kind of strange open something by a drop down item. Too much clicks (two... hehehehehehe)

#57 

@mkassner didn't like... :(

**Comment by mkassner** [comment]
I see that the current design (drop down) is inappropriate, I would not a better idea. I just dont know if a bunch of buttons is going to be the better answer. (It might be, though.)
 

m

**Comment by cpicanco** [comment]
Well, with an outside container it becomes a tool palette, a fancy name to a bunch of buttons and a nice metaphor specially for the Player/Exporter, since some of them are truly painting tools.

**Comment by cpicanco** [comment]
Reopen if (or when) it becomes a priority.
