### ISSUE TITLE
Problem with streaming data

### ISSUE THREAD

**Issue by kamiartik** [pupil-labs/pupil#663]
Hello,

I want to receive the gaze position data in real time.

I pasted the code below but there were no results. Also I didn't encounter with any error.

```python
"""
Receive data from Pupil server broadcast over TCP
test script to see what the stream looks like
and for debugging
"""
import zmq
import json

#network setup
port = "50020"
context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.connect("tcp://127.0.0.1:"+port)


socket.setsockopt(zmq.SUBSCRIBE, 'gaze_positions')


while True:
    topic,msg =  socket.recv_multipart()
    msg = json.loads(msg)
    print  "\n\n",topic,":\n",msg

```

**Comment by papr** [comment]
Dear @kamiartik 
This script is very outdated.

1. Pupil Capture does not use json anymore but msgpack
2. You are subscribing on the Pupil Remote port. But Pupil Remote is a Reply socket, not a Publish socket. This means It will only send data if you ask for it using a Request socket.

Please refer to this Pupil Helper script for a current example for how to subscribe to Pupil Capture data:
https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/filter_messages.py

Make sure to uncomment [line 24](https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/filter_messages.py#L24) to receive gaze data.

**Comment by kamiartik** [comment]
Thank you. It is working now
