### ISSUE TITLE
video export function not working

### ISSUE THREAD

**Issue by yemu** [pupil-labs/pupil#664]
When I try to export video, Pupil Player, only exports data, and heatmap pngs for the surfaces, but it doesn't export any video. progress indicator on the export plugin doesn't move and Pupil Player becomes irresponsive. I'm using fresh install of Ubuntu 16.04 and Pupil 0.8.7, I tried 0.9.2 but it doesn't even open my recording dirs and crashes.

**Comment by mkassner** [comment]
Hi,

this is related to opencv . Please rebuild and reinstall opencv using the updated flags:

cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_TBB=ON -D WITH_TBB=ON ..


best,

Moritz

**Comment by yemu** [comment]
i'm using prepackaged Pupil, I wasn't building from source, what can I do?

**Comment by mkassner** [comment]
Ha ok. Please start pupil player v0.9.2 from terminal (type pupil_player) and drag your recording into the window. Please post the output.

Thanks!

**Comment by yemu** [comment]
recordings were made using pupil 0.8.7, this is the error:

Player [WARNING] __main__ : You did not supply a data directory when you called this script!
Player [ERROR] player_methods : No valid dir supplied
Player [INFO] __main__ : Session setting are from older version of this app. I will not use those.
Player [INFO] player_methods : Updating meta info
Player [INFO] __main__ : Application Version: 0.9.2.3
Player [INFO] __main__ : System Info: User: aniedzielska, Platform: Linux, Machine: anutka, Release: 4.8.0-41-generic, Version: #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017
Traceback (most recent call last):
  File "main.py", line 625, in <module>
  File "main.py", line 241, in session
KeyError: 'pupil_positions'
Failed to execute script main

**Comment by mkassner** [comment]
Hi,

please paste the content of info.scv here.

I think with that info I can tell you how to fix the problem.

Best,
Moritz

**Comment by yemu** [comment]
key,value
Recording Name,2016_12_15
Start Date,15.12.2016
Start Time,14:10:23
System Info,"User: yemu, Platform: Linux, Machine: e6410, Release: 4.2.0-36-generic, Version: #41-Ubuntu SMP Mon Apr 18 15:49:10 UTC 2016"
World Camera Frames,41215
World Camera Resolution,1280x720
Duration Time,00:26:50
Capture Software Version,0.8.7

**Comment by yemu** [comment]
key,value
Recording Name,2016_12_15
Start Date,15.12.2016
Start Time,14:10:23
System Info,"User: yemu, Platform: Linux, Machine: e6410, Release: 4.2.0-36-generic, Version: #41-Ubuntu SMP Mon Apr 18 15:49:10 UTC 2016"
World Camera Frames,41215
World Camera Resolution,1280x720
Duration Time,00:26:50
Capture Software Version,0.8.7

**Comment by mkassner** [comment]
Could you upload the recording (without the video files) and share that with me? (you can email info[at]pupil-labs.com)

**Comment by yemu** [comment]
Thanks, I sent you an email with the data

**Comment by mkassner** [comment]
Hi,

I just got your recording. I fixed the issue by opening info.csv

```
key,value
Recording Name,2016_12_15
Start Date,15.12.2016
Start Time,14:10:23
System Info,"User: cbiele, Platform: Linux, Machine: e6410, Release: 4.2.0-36-generic, Version: #41-Ubuntu SMP Mon Apr 18 15:49:10 UTC 2016"
World Camera Frames,41215
World Camera Resolution,1280x720
Duration Time,00:26:50
Capture Software Version,0.8.7
Data Format Version,v0.9.2
```

I then replaced the last line to:
```
Data Format Version,v0.8.7
```

this triggers a reconversion. I took 4 mins on my machine. Please be patient. After this it worked for me.

**Comment by yemu** [comment]
thanks, now I'm able to import my data to pupil player 0.9.2, but still I'm unable to export video.
any help would be appreciated

**Comment by papr** [comment]
@yemu just to be sure, is the video export plugin activated?

**Comment by yemu** [comment]
yes, when I press export, progress indicator is gray and doesn't move - exactly the same situation as in 0.8.7

**Comment by mkassner** [comment]
@yemu  please run from terminal again and paste output. I cannot recreate your issue with the bundle here.

**Comment by yemu** [comment]
I was finally able to export video, but the export is extremely slow, in terminal the reported speed is 0.74 frames per second. after the export the system becomes totally unresponsive. I had to reboot.

**Comment by yemu** [comment]
so currently the pupil player is still unusable for me, with export speeds I have right now it would take me about 10 hours to export one person data. any help would be appreciated.

**Comment by mkassner** [comment]
Please run from terminal and make sure to use the latest version. 

I tested your recording and it was fine except that the exporter required 1.4gb of ram. Please make sure that your machine at 4gb or so. Ill look into make the exporter more efficient!

**Comment by mkassner** [comment]
your super slow performance must come form the OS using swap when you are out of memory

**Comment by mkassner** [comment]
Ok. I improved pupil player to avoid duplication of some memory this should cut the memory footprint of the exporter in half and help you!

We will release a bundle in the next days!

**Comment by mkassner** [comment]
ok this should be fixed (improved) in the latest bundle .

**Comment by yemu** [comment]
ok, I managed to export video on a machine with 8gb ram using the latest 0.9.3

**Comment by mkassner** [comment]
Hi Yemu, fyi I was able to export your recording on a 2gb machine using v0.9.3.

**Comment by mkassner** [comment]
Hi Yemu, fyi I was able to export your recording on a 2gb machine using v0.9.3.
