### ISSUE TITLE
Timestamps going back in time

### ISSUE THREAD

**Issue by anligert** [pupil-labs/pupil#665]
The timestamps in `gaze_data` are not in strictly ascending order. Although this happens rarely (on average in .28%, but up to.5% of the data), it is present in all our recordings. We are not sure why this is. Does this depend on the communication between eye and main process? 
Please note that we are not using the newest release (we are currently working with release 0.7.4 and the 2D algorithm).

**Comment by cpicanco** [comment]
Hi,

How are you reading the `gaze_data` file? Binocular or monocular? Could you post some code? Could you post some data in gist and link here? What is the fps of the cameras used to record?

Eye and world process run in parallel. Frames are processed as soon as each of them (from eye or world cameras) becomes available to pupil software. Duplicated timestamps might happen if you compare eye and world timestamps. Duplicates may happen if you compare eye 1 and eye 2 timestamps. Redundancy might happen if you have cameras running at different speeds (eye running at 120 and world at 30 fps, will generate redundancy for world frames for example).

**Comment by cpicanco** [comment]
So, what I was trying to say is that if any redundancy occurs, it does not mean "back in time".

**Comment by mkassner** [comment]
Hi,

I guess this is for binocular data?

The code that fuses monocular samples into pairs looks like this:

https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/gaze_mappers.py#L71-L104

My guess is that in some rare cases gaze data is created with source data in the past.

**Comment by anligert** [comment]
Hi,

thanks for the quick responses. Yes, we are recording binocularly. 

@cpicanco : The recording is done at 60Hz (world cam) and 120Hz (eye cams). I am unpickling the data provided by the recording and then use the `timestamp` given in `gaze_positions.` I am not looking at the `timestamp` in `gaze_positions['base_data']` (which would be the timestamp of the pupil position). So I do not have duplicates, but in some cases timestamp[y]<timestamp[x]. You can find an exemplary dataset here: https://www.dropbox.com/s/e07yi05a4s2txx1/pupil_data?dl=0


@mkassner: The timestamp for each gaze position is generated in https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/gaze_mappers.py#L179. If timestamp[y]<timestamp[x], this would mean that the underlying pupil samples in gaze[y] would both have to be recorded before the samples in gaze[x] (or am I missing something?).

**Comment by anligert** [comment]
You can find the code I used to extract the data here: https://gist.github.com/anligert/c56c16caea6fb6d70f97ed0ace9478f4

@mkassner: While I was on it, I checked how often one or two samples went into each `gaze_positions`. Although we recorded the data binocularly, about 10% of the `gaze_positions` only have data from one eye. This means that the mapping jumped to monocular, right?

**Comment by mkassner** [comment]
Yes it does jump to monocular. Our merging approach favors low latency over maximizing binocular matches. 

There are different approaches I would like to explode and a relevant issue: #537

**Comment by mkassner** [comment]
I think this issue is sufficiently explored and explained. I will close this issue to refer to #537
