### ISSUE TITLE
Export Pupil Player Video recorded with Pupil Mobile

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#666]
I recorded a video with Huawei P6 Pupil Mobile Version.
Pupil Mobile finds the Pupil Cameras and Pupil Capture finds via NDSI both mobile cam sources.
The video stream of eye Cam and world cam works well.  

"EYE0 - Received corrupted frame" and
"WORLD - Received courrpted frame" are warnings in Pupil Capture on the screen all the time.

![screenshot from 2017-03-15 13-27-55](https://cloud.githubusercontent.com/assets/10213803/23948579/f548441c-0983-11e7-8b62-ea7607b7437f.png)

After recording with pupil capture i try to open the recording:

pupil_player '/home/testing/recordings/2017_03_15/002' 
Player [INFO] player_methods : Updating meta info
Player [INFO] __main__ : Application Version: 0.9.2.3
Player [INFO] __main__ : System Info: User: testing, Platform: Linux, Machine: belin, Release: 4.4.0-66-generic, Version: #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017
Player [CRITICAL] libav.mjpeg : No JPEG data found in image
Player [INFO] __main__ : Session setting are from older version of this app. I will not use those.
Traceback (most recent call last):
  File "main.py", line 625, in <module>
  File "main.py", line 231, in session
  File "video_capture/file_backend.py", line 160, in run_func
  File "video_capture/file_backend.py", line 175, in frame_size
AttributeError: 'NoneType' object has no attribute 'width'
Failed to execute script main

I will send you the recording via mail.
Best regards,

**Comment by mkassner** [comment]
thanks for the report. We will look at the data and come back to you in the next day!

**Comment by mkassner** [comment]
This is still work in progress. I will close this issue since it will be resolved when we release offline calibration and detection.
