### ISSUE TITLE
Pupil Capture crashes at end of calibration (macOS without administrator session)

### ISSUE THREAD

**Issue by jambonf** [pupil-labs/pupil#667]
Issue: the Pupil Capture application crashes just at the end of the calibration process, for example, when one presses the (C) button
OS: macOS Sierra 10.12.3
Pupil Capture: 0.8.7
Workaround: use a session with administrator rights

**Comment by mkassner** [comment]
My guess is a file write to disc? Could you start pupil capture form terminal and paste the output?
I have never run Capture as a restricted user.

**Comment by jambonf** [comment]
Hello,

I’ve done more deep testing and my first assertion was wrong. The issue has nothing to deal with the administrator session.

Method : I use two computers (Apple MacBook Pro 13" (late 2011) and Apple MacBook Pro 13" Retina (early 2015), both with the same macOS version (Sierra 10.12.3) and Pupil Capture versions (0.8.7). The first computer have only USB 2.0 ports, so I also made tests with a Kanex KTU10 Thunderbolt to USB 3.0 adapter. For the second computer I use a USB 3.0 hub or direct connection to the USB 3.0 computer port. I have use a fresh install of Pupil Capture, and remove before each test the « pupil_capture_settings » folder.

The issue is the same in all the configurations. The Pupil World process crash after a while when the Surface Tracker plugin is used with at least on surface tracked. The crash is more frequent (usually just after calibration) with the older computer with two eyes used and the built-in USB 2.0 ports. At the opposite, the crash is less frequent with the most recent computer using the built-in USB 3.0 port. Moreover, using both eyes increase crash occurrences whereas reducing eyes sensor frequency to 30Hz reduce these occurence.

In all case, I have this error :

OpenCV Error: Assertion failed (scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F)) in perspectiveTransform, file /tmp/opencv20150906-42178-3d0iam/opencv-2.4.12/modules/core/src/matmul.cpp, line 1943
Process world:
Traceback (most recent call last):
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/billiard.process", line 287, in _bootstrap
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/billiard.process", line 121, in run
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/world", line 477, in world
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/surface_tracker", line 207, in update
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/reference_surface", line 412, in map_data_to_surface
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/reference_surface", line 406, in map_datum_to_surface
error: /tmp/opencv20150906-42178-3d0iam/opencv-2.4.12/modules/core/src/matmul.cpp:1943: error: (-215) scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F) in function perspectiveTransform

Hope it helps,

Francis

**Comment by mkassner** [comment]
this is a bug from an older version of Pupil. We have fixed this since v0.9.1. However we are blocked on a issue to make the mac bundle of this new version.

If you run pupil from source you will find that this error does not happen.

I will close this issue and make a new one urging to mac the mac bundle :-)
