### ISSUE TITLE
OpenCV Error: Assertion failed (scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F)) in perspectiveTransform, file /home/pupil-labs/opencv-2.4.9/modules/core/src/matmul.cpp, line 1936

### ISSUE THREAD

**Issue by Philippmeyer91** [pupil-labs/pupil#668]
Hey,

everytime I am using the Offline Surface Tracker in Pupil Player v. 0.9.2 on Linux ubuntu, i receive the following Error while editing or surfaces in the video or exporting data with the Raw Data Exporter:

OpenCV Error: Assertion failed (scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F)) in perspectiveTransform, file /home/pupil-labs/opencv-2.4.9/modules/core/src/matmul.cpp, line 1936
Traceback (most recent call last):
  File "<string>", line 581, in <module>
  File "<string>", line 444, in session
  File "offline_surface_tracker.py", line 164, in on_notify
  File "offline_surface_tracker.py", line 425, in save_surface_statsics_to_file
  File "offline_reference_surface.py", line 261, in gaze_on_srf_in_section
  File "offline_reference_surface.py", line 131, in gaze_on_srf_by_frame_idx
  File "reference_surface.py", line 412, in map_data_to_surface
  File "reference_surface.py", line 406, in map_datum_to_surface
cv2.error: /home/pupil-labs/opencv-2.4.9/modules/core/src/matmul.cpp:1936: error: (-215) scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F) in function perspectiveTransform

main returned -1

The machine I am using is a Intel® Core™ i7-6700 CPU @ 3.40GHz × 8 with 32 GB RAM
The videos I have captured are for academic work, so I can not upload any of them because of privacy terms. The lengths of the videos are between 5 and 60 minutes, but the Error occures independent from the lengths of the video.

I would be very happy about any help concerning this problem.

Best Regards 

Philipp

**Comment by papr** [comment]
Dear @Philippmeyer91 
This is very likely related to #598 and #662. v0.9.2 already includes the fix for #598. We will investigate if the fix needs to be applied to other parts of the software.

**Comment by mkassner** [comment]
Actually my suspicion is that this is the exact same error. We have ints in the gaze data. The bug is gone in version 0.9.2 but the recording was made with a buggy version so the data is still bad. 

What we need is an additional converter in player_methods to convert the wrongly typed data in the pupil_data file.

**Comment by Philippmeyer91** [comment]
Thank you for your quick and helpful response, so far.

Do you have any idea how long it will take to add this converter to the plugin?

**Comment by mkassner** [comment]
Ok this is fixed. Do you run Pupil from source?

**Comment by Philippmeyer91** [comment]
I am running it from the normal GUI

**Comment by cpicanco** [comment]
@Philippmeyer91 , are you using the bundles or running from source?

**Comment by Philippmeyer91** [comment]
I think it is from the bundles

**Comment by mkassner** [comment]
OK. We will release a new bundle with this fix included in the next days!

**Comment by Philippmeyer91** [comment]
Thanks a lot for your help :)

**Comment by Philippmeyer91** [comment]
After updating Pupil Software the error does not appear anymore. Thanks alot
