### ISSUE TITLE
Binocular gaze off of monocular gaze

### ISSUE THREAD

**Issue by anligert** [pupil-labs/pupil#669]
We are interested in both the binocular as well as the monocular gaze position. We are recording binocularly and calibrate with a manual marker. 
In order to get the monocular positions, we run the monocular mapping algorithm on the `pupil_positions` offline. For completeness sake, we also rerun the binocular mapping (this will give us the bino gaze without the jumps to a single eye). This means that we end up with four data sets: bino provided by capture, recalibrated bino, and recalibrated mono for left and right eye. 
Contrary to our expectations, often the binocular mapping is not a "mixture" of both monocular mappings. When comparing the data, we find that in about 40% of the data, the x and y position of the bino data will be either above or below BOTH monocular mappings. See the attached pictures for an example. ![recalibrated_ypos](https://cloud.githubusercontent.com/assets/25906072/23995753/280b609c-0a4b-11e7-9f73-d1757b095372.png)
As far as I have looked at the code, the difference between the two mappers is the number of coefficients used (`make_map_function`, 7 vs 13). Is this behavior something you would expect from the two mappers? Which gaze mapping/position is more reliable by means of the true gaze position?

**Comment by mkassner** [comment]
I guess this is somewhat expected. We usually use the 3d mode for binocular mapping. For 2d I think using two monocular mappers and using the mean will be more robust then using the binocular 2d mapper. (This is something I would love to get a PR for :-) )

**Comment by anligert** [comment]
Hi Moritz,

we were using the 2D algorithm, as it is running more reliably and faster with our release/system combination. Maybe I missed it, but is there a resource (e.g. wiki page) that tells me which mode I should use when?
Additionally, I don't think we can easily record 2D and 3D mode at the same time. Are you able to do that and check the differences in gaze positions in your lab?

**Comment by mkassner** [comment]
sorry for my late reply!

we are currently implementing offline detection and with this you can compare 2d vs 3d. 

There already is an option for the binocular 2d mapper to use either a single multivariate polynomial or take the mean of left and right eye. I think you should try that.

Additionally I was not able to reproduce your findings. Could you share the recording with me?
