### ISSUE TITLE
Open plugin in a new tab.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#67]
Some plugins allow multiple instances Like the vis_circle in the Player (something that I really didn't know until recently). "Adding Instance" button would be good too...

...

Another idea is to reserve a tab for each plugin instead pulling them to the bottom.

#57

**Comment by cpicanco** [comment]
This "note" is related to this issue:

> Open Plugin dropdown is fully functional? What I should expect when selecting an item? Maybe a brief caption description to each item would be great...
...
> I got it!! Some plugins are shown at the bottom! Some open on your face! Conditionally!
> So would be good to have some feedback when the plugin opens out of sight.
> Further, It is too much to ask for some immediate feedback when is not possible to open a plugin?

**Comment by mkassner** [comment]
I m not sure I understand what you mean by adding instance button. 

Should this be in the plugin or next to the plugin menu?

**Comment by cpicanco** [comment]
Some plugins allow multiple instances: [additive plugins] (https://github.com/pupil-labs/pupil/blob/master/pupil_src/player/main.py#L123)

I was thinking that it is a good feature for various reasons, but for me was difficult to find out it was possible.

Since not all plugins are additive, an "Add instance" button  wound be great. Or not??

**Comment by cpicanco** [comment]
Of course, you can think in a better name for it.

**Comment by cpicanco** [comment]
Some options about the tab idea:

- open each plugin in a new tab;
- open each plugin in the plugins tab;

I think that the second one is better, would be easier to look the caption names. The first one would be good with a single icon for each plugin.

**Comment by cpicanco** [comment]
I think that a tab is an Pyglui issue.
