### ISSUE TITLE
Pupil + LSL, timestamp and frame drawing

### ISSUE THREAD

**Issue by StolzChris** [pupil-labs/pupil#670]
Hi all,

we are able to record EEG and Pupil Labs data using LSL. In order to receive reliable data, there are several questions regarding the synchronisation. I found there wasn't a fit of EEG and eye timestamp data when comparing to the timestamp of "R record startet" which is saved to the Pupil Notification data field. This might be due to different sampling rates of the devices but also the current video frame. These questions raised since we want to analyse both the neural and eye tracking data based on the video record:

1. When pressing R for Record in Pupil Capture, does the software wait for the next frame drawing?

2. Taking the xdf file recorded via LSL: Are there any information about the frame number and their respective time stamps after starting the recording in Pupil Capture?

3. Are the eye data (assuming a binocular device) received by LSL already synchronised to the video frames or does LSL record the very raw data? Perhaps we have to calculate 'em offline.

Thank you very much!

Regards
Chris

**Comment by papr** [comment]
1. The Pupil Capture event loop looks roughly like this:

    1. Handle notifications (Recorder receives `recording.should_start`/`recording.should_stop`)
    2. Process `recent_events`
        1. Wait for world scene frame
        2. Map pupil positions to gaze positions
        3. ... other plugins ...
        4. Recorder stores events
    3. Draw UI

Events usually contain a timestamp of their creation. All system plugins use `g_pool.get_timestamp()` to create the timestamp. These timestamps are used for synchronization within Pupil Capture/Player.

2. LSL uses its own time reference system. All data sent out by the Pupil LSL Relay plugin contain the Pupil Capture timestamp. LSL augments each data point with its own timestamp. In the end each data point contains two timestamps, one created by Pupil Capture and one added by LSL. You can use the difference between these two to synchronize your other LSL data with the Pupil Capture recording.

3. The LSL Relay plugin only sends event data (pupil/gaze positions), not video data.

**Comment by papr** [comment]
closed because issue is stale
