### ISSUE TITLE
Ask Pupil community for contribution documentation.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#68]
It aims to centralize and make sharing information easier. Well, there are 70 forks and it is kind of hard clicking in each one of them, read the code, and so on. Maybe a space in the wiki?

**Comment by willpatera** [comment]
Hi @cpicanco -- Let me see if I understand your idea correctly. You propose that we create a page on the wiki to highlight/showcase/summarize what the community is doing with Pupil within their forks? 

The wiki is open for user edits - so we could create a page that asks those who have forked and have made changes to add a simple summary and then link to their fork. This page would rely on the community to maintain the page. My only concern is that this page might get quickly outdated but we could try it out and see.

**Comment by cpicanco** [comment]
I think that a wiki would be good. Why not?? Something like "we encourage you to describe your accomplished work/ ongoing work here". There are a lot of interesting stuff, eye catching stuff  in the google group, for example, that may be forgot pretty quickly in old threads. I am pretty sure that the community do not have only 77 ongoing works...

**Comment by cpicanco** [comment]
I didn't know that the wiki was open some time ago!

**Comment by willpatera** [comment]
We are working on a contribution guideline and will put that on the wiki soon. I will close this issue after we have added the docs on the wiki.

**Comment by cpicanco** [comment]
It seems related to #331. I will vote this one. Please reopen as you wish.
