### ISSUE TITLE
World camera (Logitech C525) is already in use or blocked

### ISSUE THREAD

**Issue by mompes** [pupil-labs/pupil#681]
We have recently acquired the binocular hardware without the world camera. And we are trying to use a logitech C525 as the world camera. However, we are having some troubles to make it work in Windows, it does work on Ubuntu without any problem.
It must be something related to the drivers, but we can't figure out what is going on. We have set the logitech C525 to use the libusbK drivers:
![image](https://cloud.githubusercontent.com/assets/1672579/24290221/703ae0e2-1084-11e7-9bf3-7aa8b45060b9.png)

The camera is listed as a source:
![image](https://cloud.githubusercontent.com/assets/1672579/24290571/c00f863a-1085-11e7-974a-430fae522855.png)

Unfortunately when we select the source for the world camera we get an error saying: "**The selected camera is already in use or blocked**"
![image](https://cloud.githubusercontent.com/assets/1672579/24290578/c5d31ad2-1085-11e7-93a6-f99088150332.png)

The app version is 0.9.2.3

Any help is highly appreciated

**Comment by cpicanco** [comment]
I would recommend logitech C615, you will receive some warnings though. It
has better resolution and I am currently using it with no problems.
