### ISSUE TITLE
surface event in offline_surface_tracker and surface_tracker

### ISSUE THREAD

**Issue by Lahorde** [pupil-labs/pupil#684]
In capture surface tracker plugin, `surface` events are sent, see [here](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/surface_tracker.py#L223)

In player offline surface tracker plugin, `surfaces` event is sent, see [here](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/offline_surface_tracker.py#L242)

Is there any reasons to not publish `surface` event in player? 
I'm developing a player/capture plugin that use this event, I could manually add `surface` event in offline surface tracker, but I'm curious to understand why this event is not published in offline tracker.

**Comment by mkassner** [comment]
@papr  did we agree on surfaces? I think we should do that for both.

**Comment by papr** [comment]
Yes, AFAIK we agreed on the plural: `surfaces`. Only case of a singular was `frame`

**Comment by Lahorde** [comment]
#684 "surfaces" renaming is not enough, "surfaces" event content must be same. [This must be event content in offline surface tracker](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/surface_tracker.py#L226)

**Comment by mkassner** [comment]
thanks for catching that!
