### ISSUE TITLE
Improve 3d eye model

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#685]
Improve 3d eye model by modelling corneal refraction

Rewrite the cost function for the 3d single eye model fitter: https://github.com/pupil-labs/pupil/blob/master/pupil_src/capture/pupil_detectors/singleeyefitter/EllipseDistanceResidualFunction.h#L15-L41

- Reverse the projection approach by:
  - projecting contour points onto the cornea
  - Refract them
  - Project the refracted points onto the pupil plane
  - Calculate point pupil-distances as residual
 - confirm this approach using eye videos and show that fitting residual is lower than before.
 - add a forward estimation function that takes a pupil ellipse and return the eye ball normal as well as fit error
  - optimise the implementation for speed.

**Comment by papr** [comment]
Superseded by pye3d implementation, included in version 3.0 and newer
