### ISSUE TITLE
Eye 1 initiallization fails

### ISSUE THREAD

**Issue by vivi9797** [pupil-labs/pupil#690]
Hi,
when initiallizing eye 0 everything works fine and I see the video stream of the right eye. However when I then click on eye1 I get this error message:
![getimage](https://cloud.githubusercontent.com/assets/26896298/24650999/6b677eee-192c-11e7-8f36-99bee925c74c.png)
I have the 9.3 version installed (the newest one if I'm right?) and am working with windows 10. What could I do to fix this issue?

**Comment by papr** [comment]
Dear @vivi9797 
Please refer to #673 for this issue.
