### ISSUE TITLE
Pupil Capture and Processing

### ISSUE THREAD

**Issue by kamiartik** [pupil-labs/pupil#692]
Hello,

I want to use the pupil camera both in processing and pupil capture software. But it is not working at the same time. I have to close the pupil capture to access the camera from processing. Do you know any solution?

**Comment by mkassner** [comment]
You can stream the data from pupil capture to processing via zmq. have a look at this code:
https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/recv_world_video_frames.py

**Comment by kamiartik** [comment]
Thanks for your support.
