### ISSUE TITLE
pupil player crashes export video

### ISSUE THREAD

**Issue by Ann98** [pupil-labs/pupil#693]
Hello,
I installed today the latest mac bundle (release 0.9.4). 
I have more than one issue with player plugins, but there is one that I really need to make it work. I hope you can help me even if I do not run from source, because the application is installed on a school computer on which I have restricted permissions. 

Every time I want to export video, the player automatically crashes. As soon as I hit "e" or the export arrow, the player just closes. I found it actually exports 

I tried to find the same issue on the github. I understand that this release was maybe suppose to fix this problem. 

I work on osX el capitan, version 10.11.6. 4Ghz i7, 32GB 1867 MHz DDR3. 

Let me know if there is anything else you need. 
Thx!
Andréann. 

This is the log:
Player: 2017-04-05 23:10:44,500 - __main__ - WARNING - You did not supply a data directory when you called this script!
Player: 2017-04-05 23:10:44,507 - player_methods - ERROR - No valid dir supplied
Player: 2017-04-05 23:10:44,507 - version_utils - DEBUG - Running version: 0.9.4.2
Player: 2017-04-05 23:10:59,722 - __main__ - DEBUG - Starting new session with '/Users/a_coss/recordings/2017_04_05/003'
Player: 2017-04-05 23:10:59,752 - version_utils - DEBUG - Running version: 0.9.4.2
Player: 2017-04-05 23:10:59,757 - player_methods - INFO - Updating meta info
Player: 2017-04-05 23:10:59,757 - version_utils - DEBUG - Recording version: 0.9.4.2
Player: 2017-04-05 23:10:59,758 - version_utils - DEBUG - Running version: 0.9.4.2
Player: 2017-04-05 23:10:59,758 - __main__ - INFO - Application Version: 0.9.4.2
Player: 2017-04-05 23:10:59,758 - __main__ - INFO - System Info: User: a_coss, Platform: Darwin, Machine: fa-ev6817edit.concordia.ca, Release: 15.6.0, Version: Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64
Player: 2017-04-05 23:10:59,774 - video_capture.file_backend - DEBUG - loaded videostream: <av.VideoStream #0 mjpeg, yuvj422p 1280x720 at 0x1175122a8>
Player: 2017-04-05 23:10:59,774 - video_capture.file_backend - DEBUG - No audiostream found in media container
Player: 2017-04-05 23:10:59,774 - video_capture.file_backend - DEBUG - using timestamps from list
Player: 2017-04-05 23:10:59,775 - version_utils - DEBUG - Running version: 0.9.4.2
Player: 2017-04-05 23:10:59,990 - plugin - DEBUG - Loading plugin: Trim_Marks with settings {}
Player: 2017-04-05 23:10:59,991 - plugin - INFO - Loaded: Trim_Marks
Player: 2017-04-05 23:10:59,991 - plugin - DEBUG - Loading plugin: Seek_Bar with settings {}
Player: 2017-04-05 23:10:59,991 - plugin - INFO - Loaded: Seek_Bar
Player: 2017-04-05 23:10:59,991 - plugin - DEBUG - Loading plugin: Log_Display with settings {}
Player: 2017-04-05 23:10:59,992 - plugin - INFO - Loaded: Log_Display
Player: 2017-04-05 23:10:59,992 - plugin - DEBUG - Loading plugin: Log_History with settings {}
Player: 2017-04-05 23:10:59,992 - plugin - INFO - Loaded: Log_History
Player: 2017-04-05 23:10:59,992 - plugin - DEBUG - Loading plugin: Vis_Scan_Path with settings {'timeframe': 1.0}
Player: 2017-04-05 23:10:59,992 - plugin - INFO - Loaded: Vis_Scan_Path
Player: 2017-04-05 23:10:59,992 - plugin - DEBUG - Loading plugin: Vis_Polyline with settings {'color': [1.0, 0.0, 0.75, 1.0], 'thickness': 1}
Player: 2017-04-05 23:10:59,993 - plugin - INFO - Loaded: Vis_Polyline
Player: 2017-04-05 23:10:59,993 - plugin - DEBUG - Loading plugin: Vis_Circle with settings {'radius': 4, 'color': [0.949999988079071, 0.0, 0.75, 0.2], 'thickness': 1, 'fill': True}
Player: 2017-04-05 23:10:59,993 - plugin - INFO - Loaded: Vis_Circle
Player: 2017-04-05 23:11:00,005 - plugin - WARNING - Trim_Marks: Update will be deprecated soon. Use 'recent_events instead.'
Player: 2017-04-05 23:11:00,005 - plugin - WARNING - Seek_Bar: Update will be deprecated soon. Use 'recent_events instead.'
Player: 2017-04-05 23:11:00,005 - plugin - WARNING - Log_History: Update will be deprecated soon. Use 'recent_events instead.'
Player: 2017-04-05 23:11:00,005 - plugin - WARNING - Vis_Scan_Path: Update will be deprecated soon. Use 'recent_events instead.'
Player: 2017-04-05 23:11:00,012 - plugin - WARNING - Vis_Polyline: Update will be deprecated soon. Use 'recent_events instead.'
Player: 2017-04-05 23:11:00,013 - plugin - WARNING - Vis_Circle: Update will be deprecated soon. Use 'recent_events instead.'
Player: 2017-04-05 23:11:17,928 - plugin - DEBUG - Unloaded Plugin: <log_history.Log_History object at 0x11cb76668>
Player: 2017-04-05 23:12:45,317 - __main__ - INFO - Created export dir at "/Users/a_coss/recordings/2017_04_05/003/exports/0-5983"
Player: 2017-04-05 23:13:14,358 - plugin - INFO - Loaded: Video_Export_Launcher
Player: 2017-04-05 23:13:14,371 - plugin - WARNING - Video_Export_Launcher: Update will be deprecated soon. Use 'recent_events instead.'
Player: 2017-04-05 23:13:20,146 - __main__ - WARNING - Previous export for range [0-5983] already exsits - overwriting.
Player: 2017-04-05 23:13:20,156 - video_export_launcher - DEBUG - Adding new video export process.
Player: 2017-04-05 23:13:20,198 - video_export_launcher - DEBUG - Saving Video to /Users/a_coss/recordings/2017_04_05/003/exports/0-5983/world_viz.mp4
Player: 2017-04-05 23:13:20,199 - video_export_launcher - DEBUG - Starting export as new process <Export_Process(Export_Process-1, initial)>

**Comment by papr** [comment]
Dear @Ann98 
we were able to reproduce the issue and will work on fix for it.

Please do not hesitate to open new issues for the other problems that you are having with the Pupil Player plugins!

**Comment by CrashJohnny** [comment]
Dear Pupil-Labs team

I have the same issue. Can you inform, when there is a fix for that? Thanks in advance!

**Comment by mkassner** [comment]
We just fixed this. I will upload the new rlease in a bit.

**Comment by LaurensvdBroek** [comment]
Hi, not sure this is related to this issue but I'm trying to export a video, using the latest Linux build, it doesn't crash but the progress bar just never starts moving, stays gray on 0. Any ideas? The raw data and surface data export just fine. I already removed and reinstalled the software and rebooted (I tried some other suggestions as well related to changing the info file but all didn't work so far).

I get this warning for each plugin: Update will be deprecated soon. Use 'recent_events instead.'
What does that mean exactly?

Here my log:

ai@ai-Precision-M4800:/$ pupil_player
Player [WARNING] __main__ : You did not supply a data directory when you called this script!
Player [ERROR] player_methods : No valid dir supplied
Player [INFO] player_methods : Updating meta info
Player [INFO] __main__ : Application Version: 0.9.4.2
Player [INFO] __main__ : System Info: User: ai, Platform: Linux, Machine: ai-Precision-M4800, Release: 4.8.0-46-generic, Version: #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017
Player [INFO] plugin : Loaded: Trim_Marks
Player [INFO] plugin : Loaded: Seek_Bar
Player [INFO] calibration_routines.camera_intrinsics_estimation : Loaded Camera calibration from file.
Player [INFO] plugin : Loaded: Offline_Surface_Tracker
Player [INFO] plugin : Loaded: Log_Display
Player [INFO] plugin : Loaded: Raw_Data_Exporter
Player [INFO] plugin : Loaded: Log_History
Player [INFO] plugin : Loaded: Vis_Scan_Path
Player [INFO] plugin : Loaded: Vis_Polyline
Player [INFO] plugin : Loaded: Vis_Circle
Player [WARNING] plugin : Trim_Marks: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Seek_Bar: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Raw_Data_Exporter: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Log_History: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Scan_Path: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Polyline: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Circle: Update will be deprecated soon. Use 'recent_events instead.'
Player [INFO] plugin : Loaded: Video_Export_Launcher
Player [WARNING] plugin : Video_Export_Launcher: Update will be deprecated soon. Use 'recent_events instead.'
Player [INFO] __main__ : Created export dir at "/home/ai/Desktop/Link to recordings/2017_04_07/005/exports/0-500"
Player [INFO] offline_surface_tracker : exporting metrics to /home/ai/Desktop/Link to recordings/2017_04_07/005/exports/0-500/surfaces
Player [INFO] offline_surface_tracker : Created 'surface_visibility.csv' file
Player [INFO] offline_surface_tracker : Created 'surface_gaze_distribution.csv' file
Player [INFO] offline_surface_tracker : Created 'surface_events.csv' file
Player [WARNING] file_methods : numpy array will be serialized as list. Invoked at:
  File "main.py", line 637, in <module>
  File "main.py", line 499, in session
  File "offline_surface_tracker.py", line 177, in on_notify
  File "offline_surface_tracker.py", line 481, in save_surface_statsics_to_file
  File "file_methods.py", line 82, in save_object
  File "msgpack/__init__.py", line 38, in pack
  File "file_methods.py", line 75, in ndarrray_to_list

Player [INFO] offline_surface_tracker : Saved surface positon gaze and fixation data for 'Page 9 AD' with uid:'1491576052.9226453'
Player [INFO] offline_surface_tracker : Saved Heatmap as .png file.
Player [WARNING] file_methods : numpy array will be serialized as list. Invoked at:
  File "main.py", line 637, in <module>
  File "main.py", line 499, in session
  File "offline_surface_tracker.py", line 177, in on_notify
  File "offline_surface_tracker.py", line 481, in save_surface_statsics_to_file
  File "file_methods.py", line 82, in save_object
  File "msgpack/__init__.py", line 38, in pack
  File "file_methods.py", line 75, in ndarrray_to_list

Player [INFO] offline_surface_tracker : Saved surface positon gaze and fixation data for 'Page 8' with uid:'1491576337.6635883'
Player [INFO] offline_surface_tracker : Saved Heatmap as .png file.
Player [INFO] offline_surface_tracker : Done exporting reference surface data.
Player [INFO] player_methods : Updating meta info
Player [WARNING] plugin : Vis_Scan_Path: Update will be deprecated soon. Use 'recent_events instead.'

**Comment by mkassner** [comment]
@LaurensvdBroek  since I cannot recreate your problem using our sample dataset could you email us you recording (without the video files)? Then I can debug this.

**Comment by Ann98** [comment]
Hi,
It's great that you could fix the issue. 
The new release was not uploaded yet, am I right?
Thx!!
Ann.

**Comment by mkassner** [comment]
Yes. Sorry. I ll do it within the next 24h

**Comment by sgreg001** [comment]
We are also still having this issue.

**Comment by mkassner** [comment]
OK. New release is out. This is fixed.

**Comment by mkassner** [comment]
If you have this issue running from source you will need to rebuild opencv as per updated instructions.
