### ISSUE TITLE
Pupil Player - pupil diameter visualizer

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#695]
we need a plugin that shows pupil diameter over time.

**Comment by papr** [comment]
Maybe as an extra graph? Or did you have a specific visualization in mind?

**Comment by mkassner** [comment]
I thought as a line graph on top of the seekbar.

**Comment by mkassner** [comment]
static. That would be

**Comment by papr** [comment]
Ah for player. There could be a running average for capture as well

**Comment by mkassner** [comment]
implemented with v1.3
