### ISSUE TITLE
Trouble to run the new mac bundles

### ISSUE THREAD

**Issue by uncflorians** [pupil-labs/pupil#697]
I did get the permission dialogue and I started the program with right-click > open. Afterwards it crashes. Any ideas? Or similar issues? This is the automated error report:

### Process:               pupil_capture [21484]
Path:                  /Volumes/VOLUME/*/Pupil Capture.app/Contents/MacOS/pupil_capture
Identifier:            Pupil Capture
Version:               0.9.4-2 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           pupil_capture [21484]
User ID:               501

Date/Time:             2017-04-08 16:28:17.609 +0200
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        B42AFD68-928F-4AC0-246F-8015E028A131

Sleep/Wake UUID:       488C7290-E284-4CCF-81E9-6697AB13996F

Time Awake Since Boot: 18000 seconds
Time Since Wake:       5700 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffd453bd42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffd46295bf pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffd4452497 raise + 26
3   Pupil Capture                 	0x000000010f89eed7 0x10f89b000 + 16087
4   Pupil Capture                 	0x000000010f89cec4 0x10f89b000 + 7876
5   Pupil Capture                 	0x000000010f89b8a4 0x10f89b000 + 2212

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000004  rcx: 0x00007fff50363df8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000004  rbp: 0x00007fff50363e20  rsp: 0x00007fff50363df8
   r8: 0x00007fffdd222278   r9: 0x00007fffdd222400  r10: 0x0000000000000000  r11: 0x0000000000000287
  r12: 0x00007fff50364290  r13: 0x00000000ffffffff  r14: 0x00007fffdd38c3c0  r15: 0x0000000000000000
  rip: 0x00007fffd453bd42  rfl: 0x0000000000000286  cr2: 0x000060800002db20
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Binary Images:
       0x10f89b000 -        0x10f8a0ff7 +Pupil Capture (0.9.4-2 - ???) <55B994E1-1614-3E85-B704-22C6158BB3D8> /var/folders/*/Pupil Capture.app/Contents/MacOS/pupil_capture
       0x11a86f000 -        0x11a8acdc7  dyld (433.5) <8239D0D7-66F6-3C44-A77F-586F74525DA3> /usr/lib/dyld
    0x7fffd2df0000 -     0x7fffd2df1ffb  libSystem.B.dylib (1238.51.1) <D9B20A4F-87BC-36CB-9405-80E105666725> /usr/lib/libSystem.B.dylib
    0x7fffd2fa3000 -     0x7fffd2ff9ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib
    0x7fffd2ffa000 -     0x7fffd3024fff  libc++abi.dylib (307.3) <30199352-88BF-30BD-8CFF-2A4FBE247523> /usr/lib/libc++abi.dylib
    0x7fffd3b17000 -     0x7fffd3eecbc7  libobjc.A.dylib (709) <54CD8D1A-5C98-3559-B13A-932B3D3DD338> /usr/lib/libobjc.A.dylib
    0x7fffd4311000 -     0x7fffd4322ff3  libz.1.dylib (67) <46E3FFA2-4328-327A-8D34-A03E20BFFB8E> /usr/lib/libz.1.dylib
    0x7fffd4331000 -     0x7fffd4335ff7  libcache.dylib (79) <093A4DAB-8385-3D47-A350-E20CB7CCF7BF> /usr/lib/system/libcache.dylib
    0x7fffd4336000 -     0x7fffd4340fff  libcommonCrypto.dylib (60092.50.5) <BE8380C5-C09D-3F48-A502-AEBB58231067> /usr/lib/system/libcommonCrypto.dylib
    0x7fffd4341000 -     0x7fffd4348fff  libcompiler_rt.dylib (62) <55D47421-772A-32AB-B529-1A46C2F43B4D> /usr/lib/system/libcompiler_rt.dylib
    0x7fffd4349000 -     0x7fffd4351fff  libcopyfile.dylib (138) <819BEA3C-DF11-3E3D-A1A1-5A51C5BF1961> /usr/lib/system/libcopyfile.dylib
    0x7fffd4352000 -     0x7fffd43d5fdf  libcorecrypto.dylib (442.50.19) <8A39EE06-121C-3731-A9E9-35847064B3EE> /usr/lib/system/libcorecrypto.dylib
    0x7fffd43d6000 -     0x7fffd4407fff  libdispatch.dylib (703.50.37) <D122E712-9593-31CA-BAC4-4A54410BF4A0> /usr/lib/system/libdispatch.dylib
    0x7fffd4408000 -     0x7fffd440dffb  libdyld.dylib (433.5) <129D3B44-FB21-3750-9A68-48B5C3DC632B> /usr/lib/system/libdyld.dylib
    0x7fffd440e000 -     0x7fffd440effb  libkeymgr.dylib (28) <7AA011A9-DC21-3488-BF73-3B5B14D1FDD6> /usr/lib/system/libkeymgr.dylib
    0x7fffd441c000 -     0x7fffd441cfff  liblaunch.dylib (972.50.27) <037D198D-9B02-3EF9-A8E9-6F43EA555A9E> /usr/lib/system/liblaunch.dylib
    0x7fffd441d000 -     0x7fffd4422ff3  libmacho.dylib (898) <17D5D855-F6C3-3B04-B680-E9BF02EF8AED> /usr/lib/system/libmacho.dylib
    0x7fffd4423000 -     0x7fffd4425ff3  libquarantine.dylib (85.50.1) <7B32EA91-AB8B-32A4-8E52-9D3ED46CAC8E> /usr/lib/system/libquarantine.dylib
    0x7fffd4426000 -     0x7fffd4427ffb  libremovefile.dylib (45) <38D4CB9C-10CD-30D3-8B7B-A515EC75FE85> /usr/lib/system/libremovefile.dylib
    0x7fffd4428000 -     0x7fffd4440ff7  libsystem_asl.dylib (349.50.5) <096E4228-3B7C-30A6-8B13-EC909A64499A> /usr/lib/system/libsystem_asl.dylib
    0x7fffd4441000 -     0x7fffd4441ff7  libsystem_blocks.dylib (67) <10DC5404-73AB-35B3-A277-A8AFECB476EB> /usr/lib/system/libsystem_blocks.dylib
    0x7fffd4442000 -     0x7fffd44cffef  libsystem_c.dylib (1158.50.2) <B03F8915-1E9B-3C84-AED5-68E2E0031630> /usr/lib/system/libsystem_c.dylib
    0x7fffd44d0000 -     0x7fffd44d3ffb  libsystem_configuration.dylib (888.51.2) <872C8A42-0871-3424-830B-84E587A75D27> /usr/lib/system/libsystem_configuration.dylib
    0x7fffd44d4000 -     0x7fffd44d7fff  libsystem_coreservices.dylib (41.4) <FD0915E8-9C43-3FCB-94E0-33C45DF028CD> /usr/lib/system/libsystem_coreservices.dylib
    0x7fffd44d8000 -     0x7fffd44f0fff  libsystem_coretls.dylib (121.50.4) <EC6FCF07-DCFB-3A03-9CC9-6DD3709974C6> /usr/lib/system/libsystem_coretls.dylib
    0x7fffd44f1000 -     0x7fffd44f7fff  libsystem_dnssd.dylib (765.50.9) <FF02A197-7CEF-3684-8155-E5E225051E44> /usr/lib/system/libsystem_dnssd.dylib
    0x7fffd44f8000 -     0x7fffd4521ff7  libsystem_info.dylib (503.50.4) <611DB84C-BF70-3F92-8702-B9F28A900920> /usr/lib/system/libsystem_info.dylib
    0x7fffd4522000 -     0x7fffd4544ff7  libsystem_kernel.dylib (3789.51.2) <FC51D7B0-8292-3F6A-9231-64340B237EB7> /usr/lib/system/libsystem_kernel.dylib
    0x7fffd4545000 -     0x7fffd458cfe7  libsystem_m.dylib (3121.6) <A790C9A5-DD24-32F5-8FD7-33BFCE79AC87> /usr/lib/system/libsystem_m.dylib
    0x7fffd458d000 -     0x7fffd45abff7  libsystem_malloc.dylib (116.50.8) <48D1BBA3-914E-3C65-AF70-C33B4A1B5233> /usr/lib/system/libsystem_malloc.dylib
    0x7fffd45ac000 -     0x7fffd4605ffb  libsystem_network.dylib (856.50.56) <FDE14243-4328-3EFD-824C-C0D314D7B540> /usr/lib/system/libsystem_network.dylib
    0x7fffd4606000 -     0x7fffd460fff3  libsystem_networkextension.dylib (563.50.32) <D5381DA9-529C-3588-BE16-A2245DE93423> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffd4610000 -     0x7fffd4619ff3  libsystem_notify.dylib (165.20.1) <B8160190-A069-3B3A-BDF6-2AA408221FAE> /usr/lib/system/libsystem_notify.dylib
    0x7fffd461a000 -     0x7fffd4622fe7  libsystem_platform.dylib (126.50.8) <5940EAB7-84D6-34DC-9B38-111648B2B589> /usr/lib/system/libsystem_platform.dylib
    0x7fffd4623000 -     0x7fffd462dff7  libsystem_pthread.dylib (218.51.1) <62A84A68-431D-3B54-A7B6-31367CCF2884> /usr/lib/system/libsystem_pthread.dylib
    0x7fffd462e000 -     0x7fffd4631ff7  libsystem_sandbox.dylib (592.50.47) <87A2327D-B7A1-3E4C-A85D-D3D9484003DB> /usr/lib/system/libsystem_sandbox.dylib
    0x7fffd4632000 -     0x7fffd4633ff3  libsystem_secinit.dylib (24.50.4) <F78B847B-3565-3E4B-98A6-F7AD40392E2D> /usr/lib/system/libsystem_secinit.dylib
    0x7fffd4634000 -     0x7fffd463bffb  libsystem_symptoms.dylib (532.50.47) <9CF6A47C-8343-3E85-9C27-A8D98E726A8B> /usr/lib/system/libsystem_symptoms.dylib
    0x7fffd463c000 -     0x7fffd464fff7  libsystem_trace.dylib (518.51.1) <E1D540D8-CC88-3901-92BA-FC4B802FE0E8> /usr/lib/system/libsystem_trace.dylib
    0x7fffd4650000 -     0x7fffd4655ffb  libunwind.dylib (35.3) <3D50D8A8-C460-334D-A519-2DA841102C6B> /usr/lib/system/libunwind.dylib
    0x7fffd4656000 -     0x7fffd467fff7  libxpc.dylib (972.50.27) <ABC45890-DA23-3A4A-B50B-1384BD4CBBDF> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 10564
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=127.0M resident=0K(0%) swapped_out_or_unallocated=127.0M(100%)
Writable regions: Total=19.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=19.3M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        2 
MALLOC                            11.2M       11 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                            1472K       43 
__LINKEDIT                       119.0M        4 
__TEXT                            8136K       42 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                            203.7M      104 

Model: MacBookPro7,1, BootROM MBP71.0039.B15, 2 processors, Intel Core 2 Duo, 2,4 GHz, 16 GB, SMC 1.62f7
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1067 MHz, 0x80CE, 0x5630314C3353463847423532383532383136
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1067 MHz, 0x80CE, 0x5630314C3353463847423532383532383136
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 5.0.4f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Samsung SSD 850 EVO 250GB, 250,06 GB
Serial ATA Device: ST1000LM014-1EJ164, 1 TB
USB Device: USB 2.0 Bus
USB Device: Card Reader
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
USB Device: Elements 1048
USB Device: USB Bus
USB Device: USB Bus
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus:

**Comment by mkassner** [comment]
hi,

Unfortunately you have a core2 duo mac. Our bundles do not work with this CPU. 

You will have to run from source. If I had access to a Core2Duo mac I could make bundles but I unfortunately do not :-(.
