### ISSUE TITLE
Time sync cannot find other node

### ISSUE THREAD

**Issue by sgreg001** [pupil-labs/pupil#700]
I have two systems trying to talk to each other so I can sync two sets of glasses through Capture. Using Pupil Groups and a closed local  network, the computers are able to find each other and each others' designated name shows under the group members. But when I turn on Time Sync for either computer, the message "World: dropped garbage data by peer _name_ _uuID_" (where the actual name and UUID of each computer displays) comes up. What am I not doing right?

**Comment by sgreg001** [comment]
New investigation has revealed that this is only a problem with the new Mac 9.4 version of Pupil Capture. If we assign computers with older versions (8.7, 8.5) to the same Pupil Group, the system running 9.4 will automatically serve as the master clock and all others will sync to it. But if more than one is using 9.4, they seem to compete for master clock status and reject the other one. I hope that helps.

**Comment by sgreg001** [comment]
Any ideas?

**Comment by papr** [comment]
Dear @sgreg001 
Sorry for the delayed response!

We are currently working on-rewriting out time sync protocol. You can track the progress with this branch: https://github.com/papr/pupil/tree/time_sync The new version will hopefully improve your situation.
