### ISSUE TITLE
Offline Surface Tracker

### ISSUE THREAD

**Issue by rclay26** [pupil-labs/pupil#702]
I will drop a capture into the Pupil Player and when I try to open the offline surface tracker, two extra Pupil Player icons pop up on my dock and then the Pupil Player crashes. Any thoughts on why this might be happening? 

I'm on a MacBook Pro running El Capitan

I'm running it via the bundled download from their website. Am I missing a dependency or something?

**Comment by mkassner** [comment]
This is a know issue. I just need to finally upload the fixed bundle. This will happen very soon.

**Comment by rclay26** [comment]
Great, thanks. I have another question though. There are multiple Macs in our office. Why would the offline surface tracker work with some but not the others?

**Comment by mkassner** [comment]
Is this really the case? I mean the bundle running on some macs and not on others? If so please paste some system info for the systems.

**Comment by catyouska** [comment]
I am having troubles with many recodrings I have. The markers are displayed and well visible in the video, but they are not recognized by Pupil Player. 
Is there a way to "force" pupil player to identify the markers from the video? 
Thanks in advance for your help!
