### ISSUE TITLE
Pupil Player v0.9.6 export hanging at a certain number

### ISSUE THREAD

**Issue by xiaoxuefu** [pupil-labs/pupil#706]
Hi Moritz,

With this new release, I am able to start exporting with all the plugins I added - vis cross, vis circle, eye video overlay and manual gaze correction. For the recording I have trouble with, it was recorded with Capture v0.9.3 running on Windows 10 pro (attached the system specs). The export stopped at frame 6989. I am unable to attach the world_timestamps.npy file here. I am sending it to you over email. 

Thank you very much!

P.S. We also recorded with Capture v0.9.3 running on Ubuntu. I was able to export one of the recordings using Player v0.9.6 successfully. 

![system](https://cloud.githubusercontent.com/assets/13022157/25239185/536e5c48-25bd-11e7-9576-f79e9075d1d1.png)

**Comment by mkassner** [comment]
I just looked the the timestamps. They are monotonically increasing as they should.

Could you run player in a terminal window and send the output when it hangs?

**Comment by xiaoxuefu** [comment]
I don't have the admin right on the mac that I was running the Player with - it's a university-supported computer. Maybe because of all the restrictions, I cannot run the program from terminal at the moment. In order to give you a quick response. I installed Player v0.9.6 on our Ubuntu system. I ran it from terminal, and replicated the same error - export stopped at frame 6989. Here is a screenshot of the terminal output. 
![screenshot from 2017-04-20 13-01-11](https://cloud.githubusercontent.com/assets/13022157/25243280/78053f10-25ca-11e7-840c-30cd1dd633b2.png)

Thank you again for your help!

**Comment by papr** [comment]
@mkassner Looks like the PTS are not *strictly* monotonic increasing.

**Comment by mkassner** [comment]
@papr  yes. I think this is a windows issue. The resolution of the windows timesource is not high enough. In this recording it could be that two timestamps have the same value. This would trigger this error.

**Comment by mkassner** [comment]
This is a know issue that happened when using windows capture. The new version v0.9.12 will have this fixed. For all old recording please use [this script here](https://gist.github.com/mkassner/f97e118e66f153fb6066a65df7b0bc4a) on the `world_timestamps.npy` file to fix it.
