### ISSUE TITLE
ImportError: No module named 'ndsi'

### ISSUE THREAD

**Issue by zhangp14** [pupil-labs/pupil#707]
OS: Linux Ubuntu 16.04 LTS
IDE: pyCharm

When I running /pupil/pupil_src/capture/main.py, there came an error:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pupil/pupil_src/capture/world.py", line 101, in world
    from recorder import Recorder
  File "/home/pupil/pupil_src/capture/recorder.py", line 25, in <module>
    from ndsi import H264Writer
ImportError: No module named 'ndsi'.

I think the ndsi was not installed correctly. then i running the following code on the terminal window
`sudo pip3 install git+https://github.com/pupil-labs/pyndsi` 
however, the terminal window outputs:
`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-xf7idn84-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cbz5ienh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-xf7idn84-build/
`
How to solve this problem and install ndsi correctly?
Thank you!

**Comment by papr** [comment]
@zhangp14 Is this still an issue with the current version of pyndsi? If yes, is pyndsi the only repository that raises this error?

**Comment by papr** [comment]
Apparently, this is a general problem that also affects other Pupil projects (see #713).

**Comment by papr** [comment]
@zhangp14 The problem in #713 was that something was not installed correctly. This could be the issue in your case as well. Could you post the full logs such that we can find out what the exact issue is?

**Comment by IngaIbs** [comment]
Hi, I have a similar issue with a failed install git+https://github.com/pupil-labs/pyuvc (similar to #713).
I checked the installations of turbojeg and libuv. But get the error
 ```   /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-3u7b0qrt-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c85d0bn1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-3u7b0qrt-build/ ```

Full log here: https://pastebin.com/H0dRGrUg

**Comment by diaztula** [comment]
Hi @IngaIbs 
I had the same issue, and this worked for me:

`sudo ln -s /usr/local/lib/libturbojpeg.so.0.1.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
`
After that, install pyuvc again.
Good luck!

**Comment by papr** [comment]
@IngaIbs did the above help? @zhangp14 Were you able to solve your issue?

**Comment by IngaIbs** [comment]
For some weird reason the above did not work on my system (though it should). I fixed it by setting library_dirs to ['/usr/local/lib'] in the setup.py, which is just a very unelegant alternative to the above
