### ISSUE TITLE
issue with gaze data display on Pupil_Player with Video File Source [pupil HMD]

### ISSUE THREAD

**Issue by zyzbilly** [pupil-labs/pupil#709]
I am using  Video File Source as Capture Source of world camera. For I plan to using pre-recording video as Capture Source.

When I start recording, I could see the gaze points moving on Pupil_Capture - World. 

Here comes the problem: Gaze detection works fine in Pupil_Capture, however, the gaze data could not display on Pupil_Player. Only the Video File Source displays. Then I check the exporting file:pupil_data has data in it. 

When I change the capture selection into Test Image, everything including gaze data recording is OK.

Any help would be most appreciated !
I am working on Win10 with v0.9.6&v0.9.3

**Comment by papr** [comment]
Dear @zyzbilly 
Could you make sure that one of the visualizer plugins is running? Simply click on "Open plugin" and open e.g. the `Vis Circle` plugin. A small menu should open that is titled "Gaze Circle". It might be hidden behind other menus though.

Does your problem still persist after these steps?
