### ISSUE TITLE
Problem: No Gaze on Any Surface

### ISSUE THREAD

**Issue by gladys0313** [pupil-labs/pupil#710]
Hi everyone,

I just started playing with pupil lab eye tracker this week and I encounter the problem of "No Gaze on Any Surface" all the time. 

I define the surface (A4 paper, 4 markers at 4 corners) during the capturing process and I record the process of reading the paper. However, when I use the pupil player to play my recording, the surface cannot be shown and it always says that there is no gaze on any surface. Output files from the capturing contain the surface definition and pupil data, so I have no idea why this happens and have no clue to fix it. Could anyone give a helping hand?
 
Here is the link to my files. Many appreciates!

[https://drive.google.com/open?id=0B6z9LW6mHIRsODBpSE8wQTJjRmM](url)

**Comment by mkassner** [comment]
Hi,

I looked at your recording. I m not sure why but the square marker cache was invalid. I deleted the 'square_marker_cache' file (do this while player is NOT running). After that is will redetect the markers in the video and that solved it for me. Also note that you have to click `recalculate gaze distributions` before export.

**Comment by mkassner** [comment]
Actually I found the real reason for this issue. You had set the detector to use inverted markers. No need to delete the marker cache file. Just uncheck `use_inverted_markers` and it will research the file and find all markers.

**Comment by gladys0313** [comment]
Hey, thank you very much for your help! It works now. 

I then have another question regarding the exported files. What's the difference between `fixation_on_surface` and `gaze_positions_on_surface`? I think that the fixation file includes gazes fixing at a single point for a period while the gaze file just records the positions of each gaze. 

And do you have document explaining the meaning of columns of these exported files? (e.g. world_timestamp, gaze_timestamp, etc.)

Many appreciates!
