### ISSUE TITLE
failed install git+https://github.com/pupil-labs/pyuvc

### ISSUE THREAD

**Issue by dmardanbeigi** [pupil-labs/pupil#713]
I'm trying to install pyuvc on macos 10.12.4 using sudo pip3 install git+https://github.com/pupil-labs/pyuvc but it fails:

`Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-9c1nazf2-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wayat4qq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-9c1nazf2-build/`

Here is the full log:  https://pastebin.com/Gi4xcQuc

**Comment by papr** [comment]
Thank you very much for reporting this issue! This seems to be the same issue as #707 . I will close this as duplicate.

**Comment by papr** [comment]
I am sorry. I might have misjudged the situation. The full log says `ld: library not found for -luvc.0.0.5`. Did you run the libuvc install step without problems?

libuvc install instructions from [docs](https://docs.pupil-labs.com/#dependencies-with-brew):

```
git clone https://github.com/pupil-labs/libuvc
cd libuvc
mkdir build
cd build
cmake ..
make && make install
```

**Comment by dmardanbeigi** [comment]
You are right. I remember that I did install the libuvc before! But I reinstall that again and now I'm able to install pyuvc with no error. Thanks
