### ISSUE TITLE
error when running capture main.py on mac

### ISSUE THREAD

**Issue by dmardanbeigi** [pupil-labs/pupil#714]
I'm not able to run the pupil from the source code. After installing all the dependencies, I get the following error when running main.py in the capture folder: 

full log: https://pastebin.com/K35Ad17a

macos 10.12.4
python 3.6.1

**Comment by papr** [comment]
Dear @dmardanbeigi 
it looks like ceres-solver is not installed correctly. Could you re-run `brew install ceres-solver` and test Capture again?

**Comment by dmardanbeigi** [comment]
Thanks Pablo. Reinstalled the ceres and now I can run the capture.
