### ISSUE TITLE
running the code inside a folder that has parentheses in its name

### ISSUE THREAD

**Issue by dmardanbeigi** [pupil-labs/pupil#716]
Why cannot I run the source code when it's inside a folder which has parentheses in its name. I get the following error:
`/bin/sh: -c: line 0: syntax error near unexpected token `('`

see the full log here: https://pastebin.com/8ZMsvK8v

**Comment by papr** [comment]
Apparently does not work on Windows. Requires investigation.

**Comment by papr** [comment]
Fixed with #730
