### ISSUE TITLE
Pupil Capture: continuously failed to get frames from world camera

### ISSUE THREAD

**Issue by dihimono** [pupil-labs/pupil#722]
Hi,
    I am running Pupil Capture on macOS Sierra 10.12.4. While both of the eye camera works perfectly fine, the world camera is not able to show any of the frame captured, showing only white screen. For the logs it shows:

[WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
[INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID2.

and repeats infinitely.

Attached is the screenshot of the screen.

![2017-05-12 8 16 02](https://cloud.githubusercontent.com/assets/5095588/25997720/ef929b40-374f-11e7-8f62-da0d5c19320c.png)

**Comment by papr** [comment]
Dear @dihimono 
did you try disconnecting the headset for multiple seconds and reconnecting it again?

Did the world camera work before or is this the first time that you connected the headset?

**Comment by dihimono** [comment]
@papr 

I did try disconnecting the headset and reconnect it, but this still occurs. I even tried restarted the computer, which also doesn't work.

The world camera did work before, this issue happened after I have used it for a bit of time.

Also I have just tried it on Ubuntu 14.04, which also appears to have the same issue.

**Comment by papr** [comment]
Ok, this sounds like a hardware problem. Please send an email with your order details and a reference to this issue to info@pupil-labs.com
