### ISSUE TITLE
questions about the "gaze_positions_on_surface.."  and "fixations_on_surface..." files

### ISSUE THREAD

**Issue by gladys0313** [pupil-labs/pupil#723]
Hi,

   I'm playing with the pupil lab eye tracker. I captured my gaze while viewing several pictures and export the heatmap together with gaze/fixation files. I have a few questions regarding the exported "gaze_position_on_surface..." and "fixations_on_surface..." files, thanks in advance for helping me:

   1. A "fixation" covers several gazes which are fixed at a single point for a period of time, right? Then what is the time threshold to define a fixation?

   2. Both files are named with the surface name, but I found there are a lot of "FALSE" in the column "on_srf", why is this so? Are the files named with the surface name just because the surface is visible in the frame? 

   Thanks again and I look forward to your answer!

**Comment by cpicanco** [comment]
1. Yes. The time is defined by you in the Fixation Plugin.
2. FALSE in both files means that the specified fixation or position was outside of surface boundaries. TRUE mean it was inside. Maybe renaming the column to is_inside_surface?

**Comment by gladys0313** [comment]
Thanks for your answer! 

Regarding the second question, it's still the problem: now that it is outside of the surface boundaries, then why is it included in the file named with the surface name? So I was wondering whether the surface-named-file just contains gazes which are recorded when the surface is visible in the frame. And in this case, maybe different gaze files contain overlapping gaze entries?

**Comment by cpicanco** [comment]
In my opinion redundancy is good in this case. Lets say you want to correct data using some sort of correction algorithm. You need to:

1) Interate over all data (in this case, fixations or positions)
2) Extract information about them (lets say, 90% inside surface)
3) Run your algorithm
4) Redo step 3 (lets say now its 95% inside)
5 ) and so on.

It is handy to have just one file with everything you need.

Redundancy also is a stratagy for performance (speed) optimization.

**Comment by gladys0313** [comment]
Ah I see, good point! Thank you for your idea!

**Comment by papr** [comment]
Hey @gladys0313 
do you have any other questions regarding this topic? Please close the issue, if this is not the case. :)
