### ISSUE TITLE
Avoid compiling the pupil detector twice

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#725]
When starting the eye processes for the first time, both start building the pupil detector in parallel, even though it would be enough if only one would be building it.

One solution would be to have a temporary file which signals that one eye process is building the module. The other eye process would check for the existance of the temp file first and only start compiling the module if it is not present. Else it could sleep for few seconds and check again. And alternative would be to wait for a specific "finish" notification.

**Comment by mkassner** [comment]
I dont think this happens. We are importing the detector in world to avoid this already.
