### ISSUE TITLE
Natural Features Calibration Error Crashes Pupil Capture on Win10 v.0.9.3

### ISSUE THREAD

**Issue by ogik13** [pupil-labs/pupil#729]
Hi all,

Since installing the latest version of Capture (v0.9.3), I have been experiencing a persistent error in Natural features calibration - the one crucial for our work with the Pupil Headset. specifically, there is an error in Command Prompt and the Capture stops responding. The error is:

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.3
world - [INFO] world: System Info: User: MoCap, Platform: Windows, Machine: DESKTOP-89LH25V, Release: 10, Version: 10.0.14393
world - [INFO] plugin: Loaded: UVC_Source
world - [INFO] plugin: Loaded: Pupil_Data_Relay
world - [INFO] plugin: Loaded: Pupil_Remote
world - [INFO] plugin: Loaded: Binocular_Vector_Gaze_Mapper
world - [INFO] plugin: Loaded: Fixation_Detector_3D
world - [INFO] plugin: Loaded: Log_Display
world - [INFO] plugin: Loaded: UVC_Manager
world - [INFO] plugin: Loaded: Screen_Marker_Calibration
world - [INFO] plugin: Loaded: Display_Recent_Gaze
world - [INFO] plugin: Loaded: Recorder
world - [WARNING] world: Process started.
Estimated / selected altsetting bandwith : 1768 / 2400.
world - [WARNING] plugin: Pupil_Remote: Update will be deprecated soon. Use 'recent_events instead.'
world - [WARNING] plugin: Binocular_Vector_Gaze_Mapper: Update will be deprecated soon. Use 'recent_events instead.'
world - [WARNING] plugin: Fixation_Detector_3D: Update will be deprecated soon. Use 'recent_events instead.'
eye0 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 767 / 800.
eye1 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 767 / 800.
world - [INFO] plugin: Loaded: Natural_Features_Calibration
world - [WARNING] plugin: Natural_Features_Calibration: Update will be deprecated soon. Use 'recent_events instead.'
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0517 10:45:35.773923  7888 levenberg_marquardt_strategy.cc:114] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
world - [INFO] calibration_routines.natural_features_calibration: Starting Calibration
world - [INFO] calibration_routines.natural_features_calibration: Stopping Calibration
world - [INFO] calibration_routines.camera_intrinsics_estimation: Loaded pre recorded calibration for Pupil Cam1 ID2@(1280, 720).
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
to far.
world - [INFO] calibration_routines.finish_calibration: Collected 298 monocular calibration data.
world - [INFO] calibration_routines.finish_calibration: Collected 152 binocular calibration data.
Reflection detected
Reflection detected
Ceres Solver Report: Iterations: 23, Initial cost: 2.504469e+01, Final cost: 4.618600e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 22, Initial cost: 2.135422e+01, Final cost: 2.835883e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 29, Initial cost: 1.131737e+01, Final cost: 2.225339e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 28, Initial cost: 9.026305e+00, Final cost: 2.040704e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 24, Initial cost: 7.714352e+00, Final cost: 1.906877e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 47, Initial cost: 6.840670e+00, Final cost: 1.795374e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 52, Initial cost: 6.244591e+00, Final cost: 1.710237e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 53, Initial cost: 5.844597e+00, Final cost: 1.652275e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 54, Initial cost: 5.588608e+00, Final cost: 1.616708e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 56, Initial cost: 5.440268e+00, Final cost: 1.599587e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 58, Initial cost: 5.373274e+00, Final cost: 1.598288e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 60, Initial cost: 5.368223e+00, Final cost: 1.612229e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 61, Initial cost: 5.410607e+00, Final cost: 1.638335e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 62, Initial cost: 5.489442e+00, Final cost: 1.673867e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 66, Initial cost: 5.596324e+00, Final cost: 1.716657e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 73, Initial cost: 5.724755e+00, Final cost: 1.765002e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 69, Initial cost: 5.869669e+00, Final cost: 1.817558e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 70, Initial cost: 6.027080e+00, Final cost: 1.873255e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 60, Initial cost: 6.193838e+00, Final cost: 1.931246e+00, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 58, Initial cost: 5.373274e+00, Final cost: 1.598288e+00, Termination: CONVERGENCE
world - [INFO] plugin: Loaded: Binocular_Vector_Gaze_Mapper
Process world:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "world.py", line 443, in world
  File "calibration_routines\calibration_plugin_base.py", line 49, in on_notify
  File "calibration_routines\natural_features_calibration.py", line 87, in stop
  File "calibration_routines\finish_calibration.py", line 332, in finish_calibration
  File "plugin.py", line 158, in notify_all
  File "zmq_tools.py", line 159, in notify
  File "zmq_tools.py", line 124, in send
  File "site-packages\msgpack\__init__.py", line 47, in packb
  File "msgpack\_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack\_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack\_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack\_packer.pyx", line 221, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3230)
  File "msgpack\_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack\_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize array([ 328.,   59.], dtype=float32)

On earlier versions, I never had issues with this type of calibration. Does anyone have an idea how to fix this? Or should I just go back to the previous version?

Thanks,
Ogi

**Comment by mkassner** [comment]
has this been resolved?

**Comment by ogik13** [comment]
Sorry Moritz, after posting the issue, I realized that there is a newer
software release. So, I will try with the new version first. That is why I
closed the issue. (I didn't know how to delete it.)

**Comment by mkassner** [comment]
closing if fine. A comment helps us follow your reasoning. Thank you!

**Comment by ogik13** [comment]
Sounds good. Thank you.

**Comment by ogik13** [comment]
Update: this issue was resolved in version 0.9.10
