### ISSUE TITLE
World Camera video feed not working

### ISSUE THREAD

**Issue by ogik13** [pupil-labs/pupil#733]
Hi,

After starting Capture, I have an issue with World Camera not initializing. I have used it last week and everything was working fine. It cannot be found in Source Devices and the World window is just solid grey colour. 
The following was in the command window when I run v.0.9.3 (there is no error shown when running v.0.9.10. but the video feed and the source selection for World Camera ID02 is still not present):

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.3
world - [INFO] world: System Info: User: MoCap, Platform: Windows, Machine: DESKTOP-89LH25V, Release: 10, Version: 10.0.14393
world - [WARNING] file_methods: Session settings file 'C:\Users\MoCap\pupil_capture_settings\user_settings_world'could not be read. Will overwrite on exit.
world - [INFO] world: Session setting are from older version of this app. I will not use those.
world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
world - [INFO] plugin: Loaded: UVC_Source
world - [INFO] plugin: Loaded: Pupil_Data_Relay
world - [INFO] plugin: Loaded: UVC_Manager
world - [INFO] plugin: Loaded: Log_Display
world - [INFO] plugin: Loaded: Dummy_Gaze_Mapper
world - [INFO] plugin: Loaded: Display_Recent_Gaze
world - [INFO] plugin: Loaded: Screen_Marker_Calibration
world - [INFO] plugin: Loaded: Recorder
world - [INFO] plugin: Loaded: Pupil_Remote
world - [INFO] plugin: Loaded: Fixation_Detector_3D
world - [WARNING] world: Process started.
world - [WARNING] plugin: Pupil_Remote: Update will be deprecated soon. Use 'recent_events instead.'
world - [WARNING] plugin: Dummy_Gaze_Mapper: Update will be deprecated soon. Use 'recent_events instead.'
world - [WARNING] plugin: Fixation_Detector_3D: Update will be deprecated soon. Use 'recent_events instead.'
eye0 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 579 / 800.

I don't think anything has changed since the last time I ran the software, unless there has been a Windows update that messed things up.

I appreciate any suggestions on how to fix this problem.

Thanks,
Ogi

**Comment by willpatera** [comment]
Hi @ogik13, could you please try deleting the directory `C:\Users\MoCap\pupil_capture_settings`? This will reset Pupil Capture back to default settings.

Drivers - If there was a Windows update, then drivers may have been uninstalled. Could you please check your [driver setup](https://docs.pupil-labs.com/#windows-driver-setup). Please see the troubleshooting section. 

Update to `v0.9.12` - while not related to the behavior you note in the issue, I would highly suggest updating to `v0.9.12`. The latest release is [here](https://github.com/pupil-labs/pupil/releases/tag/v0.9.12).

**Comment by papr** [comment]
Dear @ogik13 
Were you able to fix your problem? Did Will's tips work?

**Comment by ogik13** [comment]
Hi Pablo,

No, I was not able to fix it. The world camera seems to be broken. We are
in the process of sending it for repair under warranty.

Thanks for checking in on the issue. I was not sure if it should be closed
or not.

Best,
Ogi


On Jun 6, 2017 10:52 AM, "Pablo Prietz" <notifications@github.com> wrote:

Dear @ogik13 <https://github.com/ogik13>
Were you able to fix your problem? Did Will's tips work?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pupil-labs/pupil/issues/733#issuecomment-306548642>,
or mute
the thread

**Comment by papr** [comment]
Oh OK, perfect. I will close the issue.

**Comment by carsaab** [comment]
I see that this issue has been closed, but as someone who recently resolved a similar issue, I wanted to make a suggestion in the case that the camera returns and the issue still stands. 

Try disabling the requirement of drivers being signed using one of the methods described here [http://www.drivethelife.com/windows-drivers/how-to-disable-driver-signature-enforcement-on-windows-10-8-7-xp-vista.html](url) (method one worked for me), then reinstall the drivers using the provided pupil labs driver installer [https://docs.pupil-labs.com/#windows-driver-setup](url)
