### ISSUE TITLE
[Windows] 09.12.2 Player - "No JPEG data found in image" when world h264 transcoding turned OFF.

### ISSUE THREAD

**Issue by fosterseth** [pupil-labs/pupil#734]
I get this error when loading a recording\ folder into Pupil Player.

Setup: streaming from pupil mobile to Windows Capture client -- recorded from the windows client (not on phone).

The error only occurs when world h264 transcoding is turned OFF.

To note, eye0 is fine with h264 transcoding turned OFF.

Also, recording compression set to Bigger file, less CPU.

FFmpeg cannot process the output world.mp4 file either.

    Player [INFO] __main__ : Starting new session with 'C:\Users\sbf\Desktop\puptst\pup3\004'
    Player [INFO] player_methods : Updating meta info
    Player [INFO] player_methods : Updating meta info
    Player [INFO] __main__ : Application Version: 0.9.12.2
    Player [INFO] __main__ : System Info: User: sbf, Platform: Windows, Machine: sbf-PC, Release: 7, 
    Version: 6.1.7601
    Player [CRITICAL] libav.mjpeg : No JPEG data found in image
    Player [CRITICAL] libav.mjpeg : No JPEG data found in image
    Traceback (most recent call last):
    File "main.py", line 645, in <module>
    File "main.py", line 230, in session
    File "video_capture\file_backend.py", line 158, in __init__
    File "video_capture\file_backend.py", line 213, in _next_frame
    File "av\packet.pyx", line 38, in av.packet.Packet.decode (src\av\packet.c:2422)
    File "av\stream.pyx", line 203, in av.stream.Stream.decode (src\av\stream.c:4381)
    File "av\video\stream.pyx", line 51, in av.video.stream.VideoStream._decode_one 
    (src\av\video\stream.c:1900)
    File "av\utils.pyx", line 78, in av.utils.err_check (src\av\utils.c:1539)
    av.AVError: [Errno 1094995529] Invalid data found when processing input
    Failed to execute script main

**Comment by papr** [comment]
Dear @fosterseth 
Thank you for reporting this issue!

I have a few questions for you:
- Which Pupil Mobile version did you use?
- Which world camera are you using? `Pupil Cam1 ID2` or `Logitech Webcam C930e`?
- Would you be so kind and send the broken `world.mp4` to pp@pupil-labs.com such that I can have a look at the file?

**Comment by mkassner** [comment]
I was not able to recreate this error with the current version of Pupil. I m running Player on MacOS.

**Comment by mkassner** [comment]
Could you maybe attach that recording?

**Comment by fosterseth** [comment]
Sorry for the delay. Here is the recording
[https://drive.google.com/file/d/0B8-eEG8acn_AVlE2eE5TblEtS3c/view?usp=sharing](https://drive.google.com/file/d/0B8-eEG8acn_AVlE2eE5TblEtS3c/view?usp=sharing)
app 0.11.3
camera Pupil cam1 id2
player 09.12.2 Windows 10 64bit

**Comment by mkassner** [comment]
Stale
