### ISSUE TITLE
Vis Eye Video Overlay Crashing on opening

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#735]
player: v0.9.12
recording: v0.9.4
```
Traceback (most recent call last):
  File "main.py", line 645, in <module>
  File "main.py", line 502, in session
  File "plugin.py", line 66, in recent_events
  File "vis_eye_video_overlay.py", line 271, in update
KeyError: 'ellipse'
```

**Comment by papr** [comment]
My guess is that the recording includes byte strings as key instead of unicode strings. Can you confirm this?

**Comment by mkassner** [comment]
@cpicanco  can you attach the pupil_data file for this recording?

**Comment by cpicanco** [comment]
Here it is:
[pupil_data.zip](https://github.com/pupil-labs/pupil/files/1045358/pupil_data.zip)

**Comment by papr** [comment]
Ah, ok, the problem is that the eye video overlay plugin requires 3d pupil data to visualize the detected ellipse. Your data includes 2d data. I added a fix that disables ellpise drawing as soon as it encounters 2d data.

**Comment by cpicanco** [comment]
I think that a proper fix would be drawing the 2d ellipse.

**Comment by papr** [comment]
Yes, but unfortunately it is not part of the 2d datum. This is an example datum from your data set:
```python
{'confidence': 1.0,
 'diameter': 52.839576721191406,
 'id': 0.0,
 'method': '2d python',
 'norm_pos': [0.5712493658065796, 0.622674020131429],
 'timestamp': 4587.181494775,
 'topic': 'pupil_positions'}
```

**Comment by cpicanco** [comment]
Hummm... I see. So the ellipse data is not saved during 2d detection. An alternative is to re-run the detector and them save the data.

**Comment by papr** [comment]
Yes, with the offline detection you can redetect in 3d mode as well.

**Comment by cpicanco** [comment]
Can you confirm if recent versions will save the ellipse data in pupil capture? Redecting in 2d mode will be also available in offline detection?

**Comment by papr** [comment]
Yes, the offline pupil detection runs the same eye process as Pupil Capture

**Comment by cpicanco** [comment]
I think that a warning like should be included, like so:

```
WARNING : No ellipse data was found. You can redetect ellipses with offline detector plugin.
```

**Comment by mkassner** [comment]
@cpicanco  I just checked Pupil 2d detector it does contain the ellipse key. This must be use specific version being different.

**Comment by cpicanco** [comment]
Hi, @papr error persists in 0.9.13

**Comment by papr** [comment]
Could you try the current master branch? We refactored the whole plugin in #799

**Comment by cpicanco** [comment]
Ok, will try.

**Comment by cpicanco** [comment]
Sorry, I guess I can't run from source anymore:

```
W: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-3/ubuntu/dists/bunsen-hydrogen/main/binary-amd64/Packages  404  Not Found

```
Of course there is no ppa for bunsen-hydrogen. Any thoughts to workaround this?

**Comment by papr** [comment]
Not Exactly sure what you mean. Just install ffmpeg 3. You can compile it from source as well I guess.

**Comment by cpicanco** [comment]
Ok, I thought "how to make sure I am using the same version of ffmpeg as you".

**Comment by papr** [comment]
I do not think that you need the exact same version as us. The ffmpeg stuff is mostly for `ndsi`. You should be fine with `ffmpeg >= 3.2`

**Comment by cpicanco** [comment]
Ok, just checked and I have version 3.2.5-1~bpo8+1 installed :smile:
