### ISSUE TITLE
OFFLINE SURFACE TRACKER- Saved current image as .png. file

### ISSUE THREAD

**Issue by mattiaparentela** [pupil-labs/pupil#737]
Hi all,
I am Mattia Parentela, a student of Civil Engineering at Politecnico of Torino in Italy. I' m a novice with this instrument and i have use this for my thesis.  I followed the instructions to install pupil capture and player from bundle files because I am only a USER.  The problem is  that when I try to export all files linked to any surface created ( defined in pupil capture before ), the only .png file exported is the heatmap of any surface , but the images  of the surfaces (what I effectively see ) are not produced. 
Then i have also downloaded the source code to try to understand this problem and I found that code to export current image ( that can see before) is commented. I tried to remove # and save the files but the problem persist. How can I solve this problem? 
Thanks for your support.
PS. I'm not python's friendly.

![schermata del 2017-06-02 11-27-40](https://cloud.githubusercontent.com/assets/29141613/26721718/3297d570-478d-11e7-909e-55be436b0b91.png)

**Comment by cpicanco** [comment]
Hi, I have some work in progress using this very piece of code here:

https://github.com/cpicanco/player_plugins/blob/25c4b1d18026bf537c314a751e00140fcf01243c/screen_tracker_offline.py#L761-L789

I was also trying to extract single images with proper perspective transformation by choosing the frame here:

https://github.com/cpicanco/player_plugins/blob/master/export_images.py

Hope this helps,
Rafael

**Comment by cpicanco** [comment]
Maybe @papr or @mkassner could help giving us some instructions/requisites for a good pull request.

**Comment by mattiaparentela** [comment]
@cpicanco I'm sorry but i don't knwo where i have to use these codes. I installed the bundle version. Where i can find these folders?

**Comment by cpicanco** [comment]
Hi, plugins files should be put into `pupil_player_settings\plugins`.

**Comment by mattiaparentela** [comment]
@cpicanco Sorry again, but is normal that my folder of pupil_player_setting is empty.
![schermata del 2017-06-13 09-47-47](https://user-images.githubusercontent.com/29141613/27071487-7bfbaa0a-501d-11e7-84cf-a53eb0f47f09.png)

Also the folder in pupil_capture_setting/plugins is empty. 
![schermata del 2017-06-13 09-54-39](https://user-images.githubusercontent.com/29141613/27071748-639ff744-501e-11e7-94cf-c584f0198958.png)





Is it possible that i missed a step when i installed the two bundle file ? I followed the guide in the user docs

![schermata del 2017-06-13 09-54-46](https://user-images.githubusercontent.com/29141613/27071788-903bec2c-501e-11e7-95ce-0332bf266927.png)

**Comment by mattiaparentela** [comment]
@cpicanco Sorry again, but is normal that my folder of pupil_player_setting is empty.
![schermata del 2017-06-13 09-47-47](https://user-images.githubusercontent.com/29141613/27071487-7bfbaa0a-501d-11e7-84cf-a53eb0f47f09.png)

Also the folder in pupil_capture_setting/plugins is empty. 
![schermata del 2017-06-13 09-54-39](https://user-images.githubusercontent.com/29141613/27071748-639ff744-501e-11e7-94cf-c584f0198958.png)





Is it possible that i missed a step when i installed the two bundle file ? I followed the guide in the user docs

![schermata del 2017-06-13 09-54-46](https://user-images.githubusercontent.com/29141613/27071788-903bec2c-501e-11e7-95ce-0332bf266927.png)

**Comment by papr** [comment]
Dear @mattiaparentela 
There should be a `plugins` folder in `pupil_player_setting` as well. This might be a bug which I will investigate. These `plugins` folders are for user/third-arty plugins only. They are supposed to be empty. So, you did not miss an installation step. :)

Just create the `plugins` folder on your own with-in `pupil_player_setting` and add @cpicanco plugin to this folder.

**Comment by mattiaparentela** [comment]
Thanks @papr . I try to follow what you said me.

**Comment by mattiaparentela** [comment]
@papr I downloaded the folder player_plugins.zip by @cpicanco , I copied the files "screen_tracker_offline.py" and "export_images.py" in my folder as show below. 
![schermata del 2017-06-13 10-52-55](https://user-images.githubusercontent.com/29141613/27074144-8011a71c-5026-11e7-97fb-d881e557b789.png)

after, I opend pupil player by cmd to read the messages and this is result. The problem of saved_current_image persist :(
![schermata del 2017-06-13 10-47-55](https://user-images.githubusercontent.com/29141613/27074225-c96602b4-5026-11e7-9956-91a76dbfa258.png)

**Comment by papr** [comment]
This is an issue in @cpicanco code. It is based on code that he did not provide. But after skimming shortly over the export_images plugin, I think that it should not be a lot of work to remove the dependency on the screen_tracker plugin. 

@cpicanco It would be great if you could create a version of `export_images.py` that does not require any other 3rd-party plugins.

**Comment by mattiaparentela** [comment]
@papr Ah ok. Therefore there is a way to solve the problem of saved_current image as png file using the offline surface tracker ?

**Comment by papr** [comment]
There is no built-in possibility to do that right now. You will need 3rd-party code like @cpicanco code to solve your problem.

**Comment by mattiaparentela** [comment]
ok. thanks @papr

**Comment by cpicanco** [comment]
Sorry for this late response, I will update the `export_image.py` plugin it should not require any other dependencies. @mattiaparentella,  the screen tracker requires shared dependencies public available in another repository.

**Comment by cpicanco** [comment]
@mattiaparentela please, let me know if you have any success in loading and using the export_image.py plugin.

**Comment by mattiaparentela** [comment]
@cpicanco therefore i have to create on pupil_player_setting folder other two folders, one called plugins and the other called shared modules . In the plugins folder I have to copy the `export_image.py` , while in the shared modules folder I have to copy `surface_tracker.py`. It is right ?

**Comment by cpicanco** [comment]
Hi, both export_images.py and offline_screen_tracker.py goes into
pupil_player_settings/plugins and plugins dependencies have its own folder.
It should look like:

```text
./pupil_player_settings/plugins/some_plugin.py
./pupil_shared_modules/some_dependency.py
```

I would strongly recommend a quick look at the plugins section in the docs:
https://docs.pupil-labs.com/

**Comment by cpicanco** [comment]
Please, try the export image plugin first. Note that it does not require
any dependency.

On Jun 14, 2017 09:40, "Rafael Picanço" <cpicanco42@gmail.com> wrote:

Hi, both export_images.py and offline_screen_tracker.py goes into
pupil_player_settings/plugins and plugins dependencies have its own folder.
It should look like:

```text
./pupil_player_settings/plugins/some_plugin.py
./pupil_shared_modules/some_dependency.py
```

I would strongly recommend a quick look at the plugins section in the docs:
https://docs.pupil-labs.com/

**Comment by mattiaparentela** [comment]
i try the export image plugin. Thiese are the results

![schermata del 2017-06-14 17-20-29](https://user-images.githubusercontent.com/29141613/27140449-d89cfcd8-5125-11e7-8b55-297c467a3986.png)

![schermata del 2017-06-14 17-20-45](https://user-images.githubusercontent.com/29141613/27140458-e1183382-5125-11e7-922c-5e959b799409.png)
![schermata del 2017-06-14 17-20-40](https://user-images.githubusercontent.com/29141613/27140468-e7b8b612-5125-11e7-8d19-b6177338f081.png)

**Comment by mattiaparentela** [comment]
@cpicanco Hi, i have again the problem to export the image of the created surface. I add your plugin `export_image.py` in to the folder pupil_player_setting/plugins but when click on the plugins on the player application, the software give me an error. 
` export_images - ERROR - Open the Offline Screen Detector.` For understand better, i attached the screen of player and .log file to understand better.

![schermata del 2017-07-01 20-29-06](https://user-images.githubusercontent.com/29141613/27763820-4bbaf040-5e8b-11e7-83a0-a5ebdabca6f8.png)
![schermata del 2017-07-01 20-23-37](https://user-images.githubusercontent.com/29141613/27763822-58e5fa08-5e8b-11e7-90b5-2cb54a3392a5.png)

**Comment by cpicanco** [comment]
Hi, I will fix this today.

**Comment by mattiaparentela** [comment]
@cpicanco  Thanks. Can you write in this post, when you have solve this problem ?

**Comment by cpicanco** [comment]
Hi @mattiaparentela , it should work now.

**Comment by mattiaparentela** [comment]
@cpicanco Thanks, as the last time, i have to copy only the `export._images.py`in to the folder `/pupil_player_settings/plugins/`

**Comment by mattiaparentela** [comment]
@cpicanco The image has been exported ! thanks @cpicanco . You saved me
