### ISSUE TITLE
Minor issue - Frame scrubber problem in Pupil Player

### ISSUE THREAD

**Issue by jonmatthis** [pupil-labs/pupil#738]
When I drag the frame scrubber in Pupil Player, when I release white ball, it jumps ahead to a different part of the video. As near as I can tell, this is proportional to where I am trying to go in the video, e.g. if I am scrubbing to a point early in the video, it jumps ahead a small amount. If I am scrolling near the end of the video, it jumps ahead a large amount. 

It looks as though when you try to scroll to a particular part of a video it adds the frame number to the current frame upon release of the mouse button (i.e, dragging the white ball to frame#300 jumps to frame#600 upon release). 

Not a major issue, just annoying :)

**Comment by jonmatthis** [comment]
Also, while I'm making minor complaints -  your Eye Video Overlay references the eyes as Eye 1 and Eye 2, but Pupil Capture references them as Eye 0 and Eye 1 :)

**Comment by papr** [comment]
Dear @jonmatthis thanks for reporting your issues!
Your second issue will be fixed with the next release.

About your first issue: It arises probably due to inconsistent presentation time stamps within in the video. They need to be evenly spaced. If you want, you can send me a copy of the video file and the corresponding `world_timestamps.npy` file to `pp [at] pupil-labs [dot] com` and I will try to fix them for you.

**Comment by jonmatthis** [comment]
I'm not sure I understand what you're saying... This is a problem that is (in my experience) *always* present in Pupil Player. It's not a matter of fixing a single video, or if it is, it would necessitate fixing every single video that I record. Am I missing something?

**Comment by papr** [comment]
Oh, OK I see. Which Pupil Player version do you use and with which capture version did you make the recordings?

**Comment by jonmatthis** [comment]
Player Version: 0.9.12.2
Capture Version: 0.9.6

I will likely be making another recording relatively soon, which will use version 0.9.12

I'm on a Mac OS X 10.11.6

**Comment by mkassner** [comment]
@papr  I dont think pts spacing is the issue. More likely something to do with seeking through the container. 

Once we have a sample recording we can test.
