### ISSUE TITLE
Mac bundle cursor invisible after resize

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#74]
This happens only with the bundle version of mac player and capture. 

When the window gets resized the mouse curser becomes invisible over the window.

**Comment by mkassner** [comment]
This does not happen if the bundle is started from the command line.

**Comment by hookdump** [comment]
I think I've used the Mac bundle directly double-clicking it and this bug has not happened. I can double check later.

**Comment by mkassner** [comment]
This is with our new v04 bundle I m testing...

**Comment by willpatera** [comment]
I can replicate this error in *both* the v0.4.0 Capture and Player bundles. It happens after resize of the window, the mouse becomes invisible within that window, but not any others. GLWF error?

**Comment by mkassner** [comment]
Fixed with v0.5.3
