### ISSUE TITLE
windows - video manual install

### ISSUE THREAD

**Issue by odins1970** [pupil-labs/pupil#740]
anyone have a video about "step by step"  the installation for the windows version ??

**Comment by willpatera** [comment]
@odins1970 - we are working on revising the installation instructions, once we verify the new instructions we will put them in docs.pupil-labs.com.

**Comment by willpatera** [comment]
@odins1970l, I have updated windows development instructions for Pupil with Python36 and VS 2017 preview. I have verified that these instructions work on a clean machine (VM). Please see: https://docs.pupil-labs.com/master/#windows-dependencies
