### ISSUE TITLE
Audio settings

### ISSUE THREAD

**Issue by panhera** [pupil-labs/pupil#743]
Hi,

I have an issue on audio recording. There is no available option to select under "Audio Source", in order to choose a microphone before conducting the experiment. Do you have any idea about how to fix this problem? 

Best,
Panhera

**Comment by papr** [comment]
Dear @panhera 
it depends on your operating system how this list is generated. Unfortunately audio capture for Windows is not implemented yet (see #726).

Please close this issue if you are using Windows or tell us your OS and OS version such that we can investigate further.
