### ISSUE TITLE
Offline Surface Tracker Marker Detection AOI

### ISSUE THREAD

**Issue by zoenUKS** [pupil-labs/pupil#745]
Dear Github Member,

i just try to seperate my recording into diffenrent Area of Interest with the Funktion "add surfaces", but there are some complications during the setting.

whenever i try to set up a AOI, there's nothing on screen. the marker are fully visible and they're detected as blue (recognized that a marker is there).

I just used more than 4 Markers in screening.

**Comment by cpicanco** [comment]
Please, can you provide more details about the complications you have been found?

**Comment by zoenUKS** [comment]
Normally you can select every marker one by one  and whenever you are finished you can set the size of the Area.

When i start the plug in "Offline Surface Tracker" and choose "add surface" pupil_player is just calculating. After that there's an area appearing. On this i can select "add/remove marker" and "edit area".

During editing this there's sometimes changing his shape or its still gone away, so i cant pick up the point to shift it as i like.
Sometimes there's no shape, but the marker are still visible and are detected.

I just wanna try to detect the fixations on a screen, so i put some markers there on it, all in all there are more than 4 Markers (4 to 6 markers are always detected in online surface tracker during recording)
But now i cant figure out why i cant set my surface area in "offline mode"

**Comment by mkassner** [comment]
Stale, cannot reproduce.
