### ISSUE TITLE
Performance issue using Pupil Capture >=v0.9 on old hardware running Linux

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#746]
Starting with version 0.9, people have reported performance issues in the pupil detection algorithm when running Linux on old hardware.

Please comment below with your OS version and your hardware specs if you experience the above issue.

As a temporary fix, we recommend to downgrade to [v0.8.7](https://github.com/pupil-labs/pupil/releases/tag/v0.8.7).

**Comment by anligert** [comment]
Dear Pablo,
we have exactly this problem. Although setting the sampling rate of eye1 and eye0 to 90Hz, we only get a sampling rate of ~30-40 FPS at a CPU of ~100 (multiple tests on different subjects).

Release: 9.10
OS: 16.04.2 (64bit)
CPU: Intel i5 M520 2.4Ghz
Graphics: Intel Ironlake Mobile
RAM: 4GB

**Comment by behinger** [comment]
Hello!
3D Binocular recordings.

Release: 9.12
OS: Ubuntu 17.04 / Windows 10
CPU: i7-4800MQ 2.7Hz x8
Ram: 16GB

In a direct comparison to windows, I achieve ~170Hz under windows and only ~120Hz under Ubuntu.

**Comment by papr** [comment]
Good news @anligert and @behinger 
we found the reasons for the performance issues and fixed them in `0.9.13`.

Fix for Windows issue: https://github.com/pupil-labs/libuvc/pull/8
Fix for Linux issue: https://github.com/pupil-labs/pupil/commit/f64b7413715a1306633d05dac52ea3167ecc7c21

The Windows bundle for `0.9.13` will be uploaded tomorrow.

We would appreciate it if you could test `Pupil Capture 0.9.13` and confirm the performance improvements. :)
