### ISSUE TITLE
Fisheye calibration

### ISSUE THREAD

**Issue by pasbi** [pupil-labs/pupil#748]
How does calibration work if my lense is a fish eye lense? I am afraid that the eye to world mapping does not support that, since you [mention](https://github.com/pupil-labs/pupil/releases/tag/v0.9.0) that 

> [We] will start adding new futures like fisheye lens distorion modelling in the near future.

What do I need to take care of when I want to use a fisheye lense? I do not use surface tracking.

Related: https://github.com/pupil-labs/pupil/issues/605

**Comment by anligert** [comment]
I vaguely remember that there once was something about a world camera calibration with a checkerboard pattern in the wiki. I don't seem to be able to find it anymore. 
Is this outdated? And does this mean that we do not have to calibrate the world cam anymore?

**Comment by papr** [comment]
Dear @anligert 
the part about the camera calibration is indeed missing in the user docs right now. Please do not hesitate to raise issues over at https://github.com/pupil-labs/pupil-docs/issues if you find that the docs are missing information or if you find sections that require improvements. We are currently in the progress of updating all our documentation. Therefore feedback is very welcome.

The camera calibration is still [part of Pupil Capture](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py) . It assumes a [pinhole camera model with distortion](http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html). The new fish eye camera model calibration by opencv has not been integrated yet. See #605 for the progress on that issue.

Pupil Capture comes with a preset camera calibration that is valid for the shipped cameras with a resolution of 1280x720. You should re-calibrate your camera in case that you want to use different resolutions. I am aware that this is a crucial information that has been missing in the docs currently. We will update the docs as soon as possible on this issue.

**Comment by mkassner** [comment]
This feature has been added with #789
