### ISSUE TITLE
Lubuntu 14.10

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#75]
Hey guys, I am considering testing it on Lubuntu 14.10. Should I???

**Comment by cpicanco** [comment]
Better moving to Ubuntu 14.0.2 LTS??? @willpatera @mkassner ?

**Comment by cpicanco** [comment]
there is a Lubuntu 14.0.2 LTS as well

**Comment by mkassner** [comment]
Yes why not.

If you wait one more day you can try running the bundle.

M

**Comment by cpicanco** [comment]
That is ok, I am moving for a clean install. I will try to document the minimum free space on hard disc required.

**Comment by cpicanco** [comment]
Pupil Capture Bundle was running ok from Lubuntu 14.04.2 LTS live session cd without cameras. I will try now in a clean install (without updates), Capture and Player with cameras.

**Comment by cpicanco** [comment]
Of course, I am talking about Pupil v0.4

**Comment by cpicanco** [comment]
Running!
The layout of the Player is a little bit messy at the first start, though.
![2015-02-25-152311_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6377427/c244486a-bd02-11e4-9549-83f70c1c4f66.png)

Capture is ok
![2015-02-25-150138_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6377464/eae0a070-bd02-11e4-9aa5-597961388035.png)

**Comment by cpicanco** [comment]
I need to create a pupil_player symbolic link to pass a folder to it. For some reason this terminal was not seeing it even navigating to the current folder. And the desktop shortcut was not working

**Comment by cpicanco** [comment]
Now, lets installing it from source.

**Comment by cpicanco** [comment]
@mkassner and @willpatera, I was not able to install Pupil from source on a Debian/stable distribution (Crunchbang 11, RIP). Just for reference...

**Comment by cpicanco** [comment]
I had a problem trying to install 'python-dev'

```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-dev : Depends: libpython-dev (= 2.7.5-5ubuntu3) but it is not going to be installed
              Depends: python2.7-dev (>= 2.7.5-1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I am reading this right now:
http://askubuntu.com/questions/275861/problem-installing-python-dev

**Comment by willpatera** [comment]
@cpicanco -- thanks for sharing your process. It's great to know that Pupil runs on Lubuntu 14.04.2

Where are you having difficulty installing `python-dev` on Debian?

**Comment by cpicanco** [comment]
Sorry @willpatera, my mistake. I was able to install all dependencies of the v0.3.6.6 on Crunchbang 11. But I keep receiving:

> libv4l2: error turning on stream: No space left on device
> VIDIOC_STREAMON error 28, No space left on device

Even after the USB patch.

**Comment by cpicanco** [comment]
Difficults with python-dev are on Lubuntu 14.04.2 LTS, as mentioned above.

**Comment by cpicanco** [comment]
I did not test on the more recently Debian 7.8

**Comment by cpicanco** [comment]
after auto update (using the software manager) all security updates, except the kernel, I am able to install python-dev. Trying again running from source.
