### ISSUE TITLE
**eye1 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.**

### ISSUE THREAD

**Issue by mattiaparentela** [pupil-labs/pupil#750]
Hi,
I am a novice with this instrument. I installed pupil in bundle version on linux ( Ubuntu 16.04 LTS ) , exactly the 0.9.12.2 version for `capture` and `player`. Opening pupil capture and trying to detect both eye, for the `eye1` the capture application show this error : 

**eye1 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.**

![schermata del 2017-06-21 12-39-59](https://user-images.githubusercontent.com/29141613/27376604-f1982756-5672-11e7-8937-943103c76df0.png)

I thought that probably i had to change the usb port ( from 2.0 to 3.0 ) in my pc, but the problem persisted. After many changes ( about five times )  from 2.0 to 3.0 , close the application, open application, click on `detect eye1, the detect eye1 , show me the eye

**Comment by mkassner** [comment]
I believe we are solving this on discord. This is a hardware issue.

**Comment by mattiaparentela** [comment]
@mkassner ok thanks . I wait you on discord

**Comment by dabinder93** [comment]
I have the same issue. I tried it with 2 different Pupil Pro bilateral rev 021.
What was the Solution?
