### ISSUE TITLE
how create shared_modules folder

### ISSUE THREAD

**Issue by mattiaparentela** [pupil-labs/pupil#751]
Hi, 
i am a user of bundle version of pupil. If I start the first time both `pupil_capture `and` pupil_player`, in the "home" folder i see to create the pupil_capture_setting and pupil_player folder, but if i want to use also the `shared_modules folder `to copy in to this,  some plugins posted here, can i do this ? and again, can i say to both applications that with common files or plugins they have to read onto the `shared_modules folder `. I hope that is clear what i want to do

**Comment by mkassner** [comment]
Hi,

you can just import as if you are in shared module. We include that dir in
PYTHONPATH on startup.

Best,
Moritz

**Comment by mattiaparentela** [comment]
Therefore is not necessary to create the shared_modules folder ? it is right?

**Comment by cpicanco** [comment]
No, no need. Unless you were talking about shared modules from third party
plugins like noted in the wiki.

**Comment by mattiaparentela** [comment]
@cpicanco ok. if i want this, what are the steps ? I'm not a expert of python therefore i hope to follow you

**Comment by cpicanco** [comment]
What exactly are you trying to achieve?

**Comment by mattiaparentela** [comment]
I saw in the source code that , there are some plugins that i would in my bundle version, but i haven't the shared_modules folder to add these plugins ( as optimization of calibration and so on ) in to the folder

**Comment by cpicanco** [comment]
You really dont need to create the folder. You can import the stuff you
want directly.

**Comment by mattiaparentela** [comment]
Therefore, if I want add a plugins from the shared_modules to my bundle version , I have to copy this plugins in to pupil_capture_setting if I want this in pupil capture or in the player folder if I want ever this in pupil player . Right ?

**Comment by papr** [comment]
@mattiaparentela 

If you run from source (the recommended way for developers, opposed to running the bundle) you have to possibilities:

1. If you want to modify an existing plugin, just modify it in-place. No need to copy it somewhere else.
2. If you wrote your own plugin from scratch put it in `pupil_capture_setting/plugins` or `pupil_player_setting/plugins` accordingly.

There are only a few use-cases where writing a plugin that works for both applications  at the same time. It is easier to write to separate plugins at first. You can merge them later.

**Comment by mattiaparentela** [comment]
@papr  I running the bundle version. Therefore i have to copy only the plugins in the folders , on specific, `pupil_capture_setting` , `plugins pupil_player_setting/plugins`, right ?

**Comment by papr** [comment]
If they are your own plugins yes. They should automatically be listed in the "open plugin" menu. If they are not listed they are either not in the correct place or there is an error on startup when the application tries to load your plugin for the first time. In the second case you should see a warning `Failed to load '<plugin name>'. Reason: '<error>'`
