### ISSUE TITLE
Info.csv file in to surface folder 

### ISSUE THREAD

**Issue by mattiaparentela** [pupil-labs/pupil#753]
Hi, I have a problem to read all files in to surface folder. There is a way to involve a info.csv file that explain all element that there are in to each exported file

**Comment by papr** [comment]
Dear @mattiaparentela 
with which files exactly are you having problems? Can you name them? Can you name the header fields that you do not undertsand in case these files are `*.csv` files?

**Comment by mattiaparentela** [comment]
@papr I can do a list.
1. In `srf_position_surfacename` file. What are the data refer to m_to_screen and m_from_screen. I see a matrix , but i don't understand the mean of m_to and m_from
2. In the previous file i have the matrix of surface linked to a timestamp. In the `gaze position_on_srf_surfacename` file,  at the same timestamp i have the x/y_normal values. These are the coordinates  of the gaze for that specif timestamp on the surface for the same specific timestap identified by the matrix in the` srf_position_surfacename`. It is right ?
3. In `gaze_position_on_surface_surfacename`, in the last column on_srf there are true and false values. I understood that` true` mean in the srf and` false` no , but, why are in the same files if that gaze is not on srf, and again i mustn't to consider these gaze  in my analysis ,right?

Sorry for the complex question.

**Comment by papr** [comment]
1. `m_from_screen` and `m_to_screen` are the homography matrices used to project gaze points from the world coordinate system to the surface coordinate system and vice versa. (@mkassner might need to correct me on this one)

2. Yes, you are correct. These are mapped gaze positions normalized to the surface coordinate system.

3. This boolean is there for convenience. It is true if both `x_norm` and `y_norm` are part of the interval `[0,1]`. It is on you to decide if a gaze position that is not on a surface is of your interest or not. We include these values to provide as much data as possible.

**Comment by mattiaparentela** [comment]
thanks @papr. Therefore `m_from_screen `and `m_to_screen` are matrices that represent the coordinate of surface created by me and the x_norm and y_norm in the gaze_position file the coordinate of the gaze in the surface created. right? The "m" mean matrix ?

**Comment by papr** [comment]
This is my understanding, yes.

**Comment by mattiaparentela** [comment]
@papr can i ask a only one question ?

**Comment by papr** [comment]
Of course. We are also in the process of improving our documentation at http://docs.pupil-labs.com/ Please do not hesitate to open issues over at https://github.com/pupil-labs/pupil-docs if you encounter missing or unclear information in our documentation.

**Comment by mattiaparentela** [comment]
I want show and example of srf_position file to understand if is all clear.

[example of srf_position.txt](https://github.com/pupil-labs/pupil/files/1108735/example.of.srf_position.txt)

In this .txt file there are the two column m_from_screen and m_screen matrices (3x3) delimated by [[ ... ]]. If i understand what you said me. the element on the first row and column  in each matrix represent the coordinate on top to left of my surface and the last point on the third row and third column  in each matrix represent the coordinate on botton to right of my surface. Is it exact?

**Comment by papr** [comment]
No, not exactly. These matrices define the _linear transform which projects_ a point from one coordinate system to the other. This implicitly describes the surfaces coordinate system but you cannot read the coordinates from the matrix.

Imagine you have a gaze point `P = (x, y, 1)` in world coordinates. Then you can get `P* = P @ m_from_screen`, where `@` is a matrix multiplication, `P* = (x*, y*, z*)`, and `P** = (x*/z*, y*/z*, 1)` is the transformed point in surface coordinates.

P.S. in case that you are wondering why I used 3d points even though norm positions are 2d: The third component is a [Homogeneous coordinates](https://en.wikipedia.org/wiki/Homogeneous_coordinates) and allows translation within a single linear transform.

**Comment by mattiaparentela** [comment]
@papr  Therefore the last step to use P @ m_from_screen , is to have the gaze point (refered to world coordinates) in surface coordinates , right?

**Comment by mattiaparentela** [comment]
In any way sorry i all this is not clear immediately

**Comment by papr** [comment]
There are two steps:
1. `(x, y, 1) @ m_from_screen = (x*, y*, z*)`
2. `(x*/z*, y*/z*, 1) = P2`

(x*/z*, y*/z*) is the surface coordinate for the world coordinate `(x, y)`. The homogeneous coordinate needs to be normalized.

**Comment by mattiaparentela** [comment]
@papr  sorry if i answering now. Using all these information , how can to manipulate these data , to obtain the gaze position (x,y,)  in to surface. Or better, i want to obtain the result of the heatmap but using the coordinate. I don't know if is clear. In other way i want plot the gaze position (x,y) in to a area that it was represented by the coordinate of the surface

**Comment by papr** [comment]
The `gaze_position_on_surface_surfacename.csv` file contains the mapped gaze positions in surface coordinates. There is no need to transform them yourself.

**Comment by mattiaparentela** [comment]
great!Thanks

**Comment by mattiaparentela** [comment]
@papr sorry, but i have another question for this topic. `On the fixation.csv file`, there is a column called `fixation duration ` . The unit of these value is second right? .

**Comment by papr** [comment]
As @mkassner said on Discord, you may want to change minimum duration (seconds) and maximum dispersion (degree) depending on what literature you follow.

**Comment by mkassner** [comment]
I think we can close this?
