### ISSUE TITLE
libav.wav: Application provided invalid, non monotonically increasing dts

### ISSUE THREAD

**Issue by pasbi** [pupil-labs/pupil#762]
I got this error some time ago with an older version. If I remember correctly, it didn't occur after updating to a more recent version, until today when I get the error again using `v0.9.12`.

[world - [ERROR] libav.wav: Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1499789593215567 >= 1499789593214909](https://gist.github.com/pasbi/e37efc76612b2bcbfa5ab6b4641a02a3#file-gistfile1-txt)

I somehow understand the error message and I don't think that pupil is the source of the problem, however, wouldn't proper error handling be better than crashing? I loose several hours of recording when this occurs :/

**Comment by papr** [comment]
`v9.12` uses still the old capture method. This should not happen again after merging #757

**Comment by pasbi** [comment]
So do you propose to use `avsync` branch?

**Comment by papr** [comment]
Yes, I do. Even though it is not up-to-date with the other changes to come (see `player_launcher` branch)

**Comment by papr** [comment]
Do you use Time Sync?

**Comment by pasbi** [comment]
No, I don't. For simplicity, I use a stone-age method to synchronize the data streams I get from the devices (one of which is pupil-capture). That works quite well and accuracy is good enough for my purpose (<1s).

**Comment by papr** [comment]
You can always modify the timestamps file to avoid the error above if you do not need so much precision. ;)

**Comment by pasbi** [comment]
What timestamp file do you mean? The error occurs during recording and the timestamp files, including `audio_timestamps.npy` don't exist until the recording is orderly terminated.

**Comment by papr** [comment]
Oh, I see. No, this issue should not appear anymore on `avsync`.

**Comment by pasbi** [comment]
Today I got the very same issue while on `avsync` :thinking:
