### ISSUE TITLE
Unintended Time-Laps

### ISSUE THREAD

**Issue by pasbi** [pupil-labs/pupil#764]
I'm on `avsync` (commit  f8cb8f130f3e26c03a5961dfb206a4582983c752) because of #762, the software runs on a Ubuntu Laptop (t450s). 

Today I started recording, worked with that laptop for a few minutes, then closed the laptop for about 2 hours, then opened it again to stop the recording.
The videos `world.mp4` and `eye.mp4` are only about 6 minutes long.
As soon as I closed the laptop, the video runs in timelapse (about 10 to 20 times faster than would be normal).
I tried to reproduce this behavior immediately, but now everything seems to work fine.

What happened here?

The audio file is as short and contains very distorted voices (like when you fast-forward a CD).

**Comment by mkassner** [comment]
it seems like the laptop went to sleep and then picked right up where it left off when you opened the lid again. The recording uses timestamps so if you played this in player you would see a really long pause in the video. I recommend checking the system settings.

**Comment by pasbi** [comment]
Indeed I had problems to disable sleep mode, only disabling them in Unity System-Settings did not work.
However, if the laptop was sleeping
- wouldn't there be _no frames_ during that time? I get frames, but with wrong timing.
- wouldn't this happen _every time_ I close the lid? This happens only sometimes.

Currently, I'm on `v0.9.12` again and I disabled `Auto Exposure Priority`. It looks like everything's fine with this setup. Unfortunately, I have not the time to test why exactly.

**Comment by pasbi** [comment]
After seeing the videos again, I realized that the issue occurs even if the laptop is not closed.

**Comment by pasbi** [comment]
I use multiple workspaces (a standard feature of Unity).
I open pupil-capture on workspace 1, and as soon as I switch to another workspace, the time-lapse happens. When I switch back to workspace 1, the recording happens in real-time again.

So now I know how to ship around this issue, but I'm really curious about what happens here.

(Note: It's not real _time-lapse_, as the timestamp of each frame is correct. It's just too few FPS, hence it _looks like_ time-lapse before exporting the video using pupil-player).

**Comment by mkassner** [comment]
@pasbi  my guess is that the workspaces are stopping all GUI functions. Could you try minimizing the pupil windows before changing workspaces?

**Comment by pasbi** [comment]
You're right! if the main window of pupil_capture is minimized, switching the workspace has no effect.
