### ISSUE TITLE
Head pose inquiry

### ISSUE THREAD

**Issue by ghost** [pupil-labs/pupil#765]
Hey:
Is it possible to get the head pose (YAW, PITCH, ROLL) for each eye frame? Thanks a lot

**Comment by cpicanco** [comment]
It is possible. Not out-of-the-box though. Using fixed fiducial markers, for example.

**Comment by wusiyue93** [comment]
@cpicanco Thank you for your response. But I am not sure what is the fixed fiducial markers you meant. I saw another head pose inquiry said that head pose could get from surface tracker?

**Comment by cpicanco** [comment]
Yes, the surface tracker uses fiducial markers to define surfaces with
orientation data. In theory, if you have a stationary marker somewhere, you
can determine the head orientation and distance from the marker within the
limits of your camera resolution. An alternative approach would be to
integrate the pupil headset with some geolocalization/radio device.

**Comment by wusiyue93** [comment]
@cpicanco Got you! Thanks a lot!
