### ISSUE TITLE
Intel RealSense R200 RGBD camera NOT working

### ISSUE THREAD

**Issue by ganadarastudio** [pupil-labs/pupil#767]
The World camera(Intel RealSense R200 RGBD) is not working on neither of macOS nor windows10...
On windows I installed Intel RealSense R200 RGBD sdk and it worked seperately but not with Pupil Capture. Could you help me out please?

windows10
![windows10](https://user-images.githubusercontent.com/10971751/28351591-d0924fc6-6c8b-11e7-81ea-53622c488f5b.PNG)

macOS
<img width="1280" alt="macos" src="https://user-images.githubusercontent.com/10971751/28351540-8bf65894-6c8b-11e7-8c36-a297701cfe23.png">

**Comment by papr** [comment]
Unfortunately, the R200 is listed as a UVC (local USB) camera but is not compatible to the library that we use to talk to the cams (pyuvc/libuvc). You can see the same phenomenon in other software, e.g. Skype: The camera is listed but does not work.

We are currently working on a custom capture backend that uses the Intel SDK to integrate the R200 into Pupil Capture. You can see a preview by following these steps:

1. You will need to run Pupil Capture from source. Therefore you need to install all the requirements for your OS listed on Pupil Docs.
2. Install https://github.com/IntelRealSense/librealsense/
3. Install https://github.com/papr/pyrealsense
4. Checkout and run the [Pupil Capture `realsense` branch](https://github.com/papr/pupil/tree/realsense)

Be aware that this feature is being developed actively and that this branch is not stable but only a preview. You are responsible to keep all requirements up-to-date. Having said that, I look forward to your feedback on this feature.

P.S.: Make sure that your camera is calibrated using https://downloadcenter.intel.com/download/24958/Intel-RealSense-Camera-Calibrator-for-Windows-

**Comment by shrutiashi** [comment]
I am new to using Pupil tracker. I purchased 3D Intel Realsense world camera with binocular eye trackers. I am having the same issue, the world camera isn't working. Being new to the whole process of software and hardware, I couldn't follow the steps you mentioned in your comment above. Can you provide more simplified/clear step by step process to work out the world camera ??

Also, by when can we expect updated version of the pupil apps which will work with the Intel RealSense R200 camera?

**Comment by mkassner** [comment]
We plan to have the bundled version with realsense backend support ready
within the next two weeks.

**Comment by papr** [comment]
Closed with #782

**Comment by wadelab** [comment]
Any news on this? It's frustrating not to be able to use the world camera...

**Comment by papr** [comment]
Yes, the feature has been merged to master. Just check it out and run from source. You will have to install librealsense and pyrealsense for it to work. There will be no bundle including for Linux since the library requires patching the kernel.

**Comment by ganadarastudio** [comment]
How do I run from source? Could you provide a specific instruction? Thank you.

**Comment by papr** [comment]
@ganadarastudio The docs do not include instructions for `librealsense` and `pyrealsense` yet. You will need to follow the instructions at https://github.com/IntelRealSense/librealsense/ and run `pip3 install git+https://github.com/papr/pyrealsense` afterwards.

**Comment by mtee** [comment]
> There will be no bundle including the feature for Linux since the library requires patching the kernel.

Could you elaborate on this a bit? Doesn't the realsense backend work under linux? It's confusing because in the comments to the pull request another developer writes:

> General feedback. I think the backend on Mac is not quite as smooth as it is on Linux. Some settings do not work and the framerate control seems to be reversed.

**Comment by papr** [comment]
@mtee As you surely know there is a difference between running Pupil applications from bundle and from source. When running from source the user is required to install dependencies him- or herself. When using the bundle almost all dependencies come pre-compiled with it.

The [Linux `librealsense` instructions require patching the kernel](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md#video4linux-backend-preparation). This is not something we can easily do from within the bundle and would be very difficult to maintain as well. These reasons led us to the decision to not include the RealSense dependencies in the  bundle.

I think that you are still able to use the bundle by installing `librealsense` yourself (including kernel patching) and by installing `pyrealsense` into the Pupil Capture runtime plugin folder. The recommended (and tested) way would be to run from source nonetheless.

**Comment by mtee** [comment]
Ok, this clears it up. 
>  When running from source the user is required to install dependencies him- or herself. When using the bundle almost all dependencies come pre-compiled with it.

I actually never considered running the pupil software without building it from the sources, so the "bundle" was indeed a new word for me in this context. Thanks for the heads up.

So for those who build the pupil and all dependencies from sources under linux anyway there is nothing to fear regarding the realsense support? On a slightly related note, could you comment on the quality of the depth-to-RGB registration on your realsense cameras? Are there any noticeable discrepancies like 
[here](https://github.com/intel-ros/realsense/issues/201) or [here](https://github.com/intel-ros/realsense/issues/201)

**Comment by papr** [comment]
@mtee Correct, we will have continued support for the R200 when running from source on Mac and Linux.

Yes, we have noticed these discrepancies as well but were able to reduce them greatly by recalibrating the camera. You can do this using the [Intel® RealSense™ Camera Calibrator for Windows](https://downloadcenter.intel.com/download/24958/Intel-RealSense-Camera-Calibrator-for-Windows-).

**Comment by mtee** [comment]
@papr 
> You can do this using the Intel® RealSense™ Camera Calibrator for Windows.

Is the calibration data then stored on the device and is used automatically when I will be using the camera through the librealsense under linux?

I have seen that there is [no straight-forward way to use own calibration parameters in librealsense](https://github.com/IntelRealSense/librealsense/issues/463)

**Comment by papr** [comment]
Yes, this information is stored on the device itself (to my knowledge). What I definitely can say is that the depth-image quality on my Linux machine was much better after calibrating using the Windows tool on Windows.

**Comment by mtee** [comment]
@papr, great, thanks for the information!

**Comment by papr** [comment]
No problem :)

**Comment by mtee** [comment]
hey @papr I recently got a notice from your support team, that the intel calibration tool for windows currently does not work with the R200. Were you able to circumvent it or do you use the standalone r200 without the eye-tracking cameras attached? Also, do you happen to know, if it's possible to reflash the R200 firmware on the eye-tracker with R200? I have some issues with mine and I though reflashing firmware might help.

**Comment by papr** [comment]
@mtee There is no difference if the eye cameras are attached or not. The integrated R200 behaves the same way as if you would connect it in its original case. Therefore reflashing the camera should work. I do not have any experience with it though,

I do not know what the current state of the calibration tool on Windows is. AFAIK the issue arose with updating Windows.

**Comment by ferreira-santos** [comment]
I have been trying to follow instructions by @papr (from Jul 19, 2017) but Pupil-labs instructions on how to install librealsense for Windows does not link to any actual library (zip or installable) (https://github.com/pupil-labs/librealsense/blob/master/doc/installation_windows.md)
What do I actually need to install?
