### ISSUE TITLE
Closing Lid Recording Issue

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#768]
We noticed a power management change in Ubuntu 16.04

Usual we set up our system power settings to 'Don't suspend'. 
So the screen will just turn black when closing the lid. However this doesn't work anymore. Our computers suspend.

So we found the following workaround:
Set in /etc/systemd/logind.conf `HandleLidSwitch=ignore`
(sometimes it doesn't work) or
/etc/UPower/UPower.conf `IgnoreLid=true`

The problem is that the lid will still consume power. So if the lid shall be blank open a terminal and enter:

```
gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'blank'
gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action 'blank'
```

Hope this helps.
Best regards

**Comment by mkassner** [comment]
Thank you for the issue port and guide!

**Comment by fneitzel** [comment]
It is not really a pupil issue and I don't know if there is any place for hints like that in the docs?
