### ISSUE TITLE
pupil_capture crash on fresh Windows10 install

### ISSUE THREAD

**Issue by trialsrideraz** [pupil-labs/pupil#769]
- Completely fresh Windows 10 Home install
- un-archive pupil 0912
- install special drivers for headset
- plug in Microsoft LifeCam HD-6000
- plug in Logitech HD Webcam C615
- launch pupil_capture .... results below:

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.12.2
world - [INFO] world: System Info: User: trial, Platform: Windows, Machine: DESKTOP-7OO71MB, Release: 10, Version: 10.0.15063
world - [INFO] world: Session setting are from older version of this app. I will not use those.
Process world:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "world.py", line 294, in world
  File "glfw.py", line 522, in glfwCreateWindow
Exception: GLFW window failed to create.

**Comment by mkassner** [comment]
This error means that your gl setup is not quite right. please make sure you have recent drivers.

**Comment by mompes** [comment]
@trialsrideraz did you manage to fix it? I am having the same issue but with the pupil player (pupil capture works flawlessly).

**Comment by trialsrideraz** [comment]
@mompes (and @mkassner ), I did not get this to work at all and am still having issues.  I purchased a completely new laptop with fresh Win10 and tried the DIY cameras (Logitech and Microsoft for the World and Eye, respectively).  Installed the Windows 0913 version. I tried the Win10 drivers with no luck getting the libusbK to show up at all until i used the utility Zadig to force the driver onto the cameras.  Once that was done, now all i get is the world camera being recognized (but no image) and then indicating over and over again that:
`World found device HD Webcam 615
 World: Could not set value. 'Absolute Exposure Time'
 World: Could not set value. 'White balance temperature'.
`
The eye camera still gives "EYE0. Init failed. Starting in ghost mode..."

Any help would be greatly appreciated!

Best regards,
tr

**Comment by mkassner** [comment]
@trialsrideraz  I m not sure if the hd6000 cameras work on windows like this.

**Comment by cpicanco** [comment]
@trialsrideraz , I would recommend pupil cameras on windows. Also ubuntu and mac for DIY kits, in this order. On windows, pupil-labs priority has been for pupil cameras. I am not aware of extensive testing of DIY kits on windows neither.

**Comment by trialsrideraz** [comment]
@mkassner and @cpicanco , If i port to ubuntu (non-mac), do you think the DIY cameras will work?  the cost for the pupil cameras is out of budget for my project.

**Comment by cpicanco** [comment]
I have a DIY kit on Ubuntu. I cannot confirm if HD-6000 is still working
since I moved to another eye camera. Please, check the UVC repository for
camera alternatives.

**Comment by trialsrideraz** [comment]
@mkassner and @cpicanco , just an FYI - I installed on Ubuntu and got things going easily with the DIY cameras mentioned above.

**Comment by cpicanco** [comment]
Great!
