### ISSUE TITLE
Camera intrinsics estimation plugin incomplete

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#77]
This plugin needs to be completed for v0.4.0. At current it opens a blank window that can not be closed -- which is _very_ bad when `Use fullscreen` is selected because then you can't exit. 

Todo
  - [x] escape key to close window
  - [x] draw pattern in the plugin window
  - [x] copy touch to escape routine from `Screen Marker Calibration` to this plugin
  - [x] show 'c' button in this window without circle outline so user can touch something to capture the pattern -- or modify the touch to exit routine so that you touch anywhere to capture a pattern (or press `c` key on the keyboard) and exit by touching more than 10 times.

**Comment by mkassner** [comment]
done all for touch to capture in window. Usually you need the world window as feedback and you can use the control there.
