### ISSUE TITLE
Cannot open Pupil Capture or Pupil Player with the new release

### ISSUE THREAD

**Issue by rlawson9** [pupil-labs/pupil#774]
Just downloaded the new release of PupilLabs for MacOS (v0913). Now I cannot open the Pupil Capture or Pupil Player application. Any suggestions are greatly appreciated! I have a subject this Tuesday and desparately need this application. Thank you

**Comment by mkassner** [comment]
Hi,

Sorry to hear that! Please open terminal, paste the below and hit enter.
This will start capture in terminal.


/Applications/Pupil\ Capture.app/Contents/MacOS/pupil_capture


Please paste the output here so I can debug.

Best,
Moritz

**Comment by papr** [comment]
This has been fixed. Please download and install the newest release. Duplicate to #775
