### ISSUE TITLE
Offline Pupil Detector shows "Detecting..." when Progress bar is at 100%

### ISSUE THREAD

**Issue by jonmatthis** [pupil-labs/pupil#778]
I have gotten the Offline Pupil Detector to work on on short (~2000-3000 frame) videos, but when I have tried it on a longer videos (>10000 frames or so) the Offline Pupil Detector will get to 100% and then hang there indefinitely (I have waited for over an hour). When this happens, the eye video windows stay open and the plugin window stays showing "Detecting." Sometimes this happens to both eyes, sometimes one completes successfully and the other hangs. 

In either case, attempting to run the "Recalibrate" option of the Offline Calibration plugin returns the error "PLAYER: No pupil data to calibrate section '1'" 

Thank you!

**Comment by mkassner** [comment]
Thanks for the report. I just fixed this. Please update the latest release. I did not make a new release but updated the uploaded bundled.

**Comment by mkassner** [comment]
The bundles just finish uploading. Please try now.

**Comment by jonmatthis** [comment]
Seems to be working, thanks!!
