### ISSUE TITLE
Eye Video Overlay causes Player to crash in OSX

### ISSUE THREAD

**Issue by jonmatthis** [pupil-labs/pupil#784]
See title.

**Comment by jonmatthis** [comment]
...the Export Video plugin also hangs indefinitely without creating video (Progress bar stays on '0') 

Export Raw Data appears to perform  normally.

**Comment by papr** [comment]
Can you confirm that this happens with newly recorded eye videos as well?

**Comment by mkassner** [comment]
OK. I just fixed this. Please download latest bundle (I replaced the old version.)
