### ISSUE TITLE
Problem with frame scrubber has resurfaced (OS X)

### ISSUE THREAD

**Issue by jonmatthis** [pupil-labs/pupil#785]
The problem with the frame scrubber that I described in Issue #738 has resurfaced in the new version. Copied text below: 

> 
> When I drag the frame scrubber in Pupil Player, when I release white ball, it jumps ahead to a different part of the video. As near as I can tell, this is proportional to where I am trying to go in the video, e.g. if I am scrubbing to a point early in the video, it jumps ahead a small amount. If I am scrolling near the end of the video, it jumps ahead a large amount.
> 
> It looks as though when you try to scroll to a particular part of a video it adds the frame number to the current frame upon release of the mouse button (i.e, dragging the white ball to frame#300 jumps to frame#600 upon release).

**Comment by papr** [comment]
Does this happen only with older recordings or does it also happen with sessions recorded with Capture 0.9.13?

**Comment by mkassner** [comment]
@jonmatthis what the code that your videos are recorded in?

**Comment by jonmatthis** [comment]
It happens with recordings from 0.9.13. It was recorded with the "Bigger file, less CPU" option, if that is what you mean by the "code" it was recorded in

**Comment by jonmatthis** [comment]
FYI - this is still a problem in v0.9.14

**Comment by papr** [comment]
@jonmatthis Please send an example recording to pp@pupil-labs.com We will try to reproduce the issue.

**Comment by jonmatthis** [comment]
I really don't think this is a problem with a recording. This issue occurs literally every single time I use Pupil Player on a Mac. It does not occur when using player on a Linux machine, but it DOES occur when  I try to run a recording I made on a Linux machine on Player running on a Mac. 

I will send a recording over anyway, but this should be something you could verify very easily on any mac

**Comment by papr** [comment]
@jonmatthis Is it possible that you are using a Mac with a Retina Display? On our Mac in the office (without Retina Display) seeking works well. If this is the issue it will be fixed with the next release which comes with a new UI.

**Comment by jonmatthis** [comment]
Ah, that might be it! I have experienced this with two separate Mac laptops, both of which have Retina displays.

**Comment by papr** [comment]
I can confirm that this was was a problem with the ui scaling and will be resolved with the upcoming release.

**Comment by papr** [comment]
This has been fixed with #860
