### ISSUE TITLE
Blink plugin: Offset is not detected properly

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#792]
Hi,
The offset within the blink plugin is not detected properly. One blink takes several seconds or so, basically up until just before the next onset is being detected.

Something like this should fix it, but I am not sure what the proper value of `act` should be (it definitely doesn't go below `0` for me, so checking whether it's smaller than `-0.1` doesn't work at all):
```
@@ -118,7 +118,7 @@ class Blink_Detection(Plugin):
                 self.is_blink = True
 
             # If we also want to measure the off-set of a blink we could do it like this
-            if self.is_blink and act < -0.1:
+            if self.is_blink and act < 0.1:
                 self.is_blink = False
 
             logger.debug('{} {}'.format(self.is_blink, act))
```

**Comment by papr** [comment]
I think the actual fix here is to set the second half of the blink "filter" to `0` instead of `-1` since the confidence is normalized to `[0, 1]`. I will talk with @marc-tonsen about it.

**Comment by papr** [comment]
The above assumption is wrong. May I ask what your setup is? Binocular/monocular eye capture and video fps?

**Comment by Tobias-Fischer** [comment]
Sure, we're using the binocular eye capture with max fps.

**Comment by Tobias-Fischer** [comment]
Actually .. sorry, we use 30fps, and 90fps for the eyes.

**Comment by papr** [comment]
The issues arises probably since data for both eyes is queued separately and assumes similar fps numbers for both queues. I am refactoring the plugin right now such that the queues are unified. This should improve overall stability and will allow the user to change plugin properties.

**Comment by Tobias-Fischer** [comment]
I haven't tested the new blink detector yet, but I am sure it's fixed there :). If not, will re-open.
