### ISSUE TITLE
Webcam installation issue

### ISSUE THREAD

**Issue by carlstrath** [pupil-labs/pupil#793]
video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
world - [INFO] video_capture.uvc_backend: Found device. HD USB Camera.
world - [ERROR] uvc: Could not init 'Gain'! Error: range() arg 3 must not be zero
world - [WARNING] uvc: Could not set Value. 'White Balance temperature'.

Any ideas >? 

thanks :)

**Comment by papr** [comment]
It seems like your Webcam is not completely UVC compliant. You could comment out the lines in the source code that try to set these options. 

Be aware that the Pupil software does not work for remote eye trackers but head mounted eye trackers only.
