### ISSUE TITLE
[Bug][Auto Exposure Priority]Focus changes from Aperture to Manual 

### ISSUE THREAD

**Issue by AayushKumarChaudhary** [pupil-labs/pupil#794]
Steps:
Set eye video at 120Hz 640*480 resolution. 
Settings Aperture (Auto Exposure Priority set)
Reproduction Step: Focus additional infrared light on off in the eye-> Observe the aperture/manual mode setting bar
Observation: It switches from Auto Exposure to Manual

**Comment by mkassner** [comment]
We hardcode this change in the startup procedure. We can change this. So far nobody made this requirement, but I think your use-case is valid!

**Comment by papr** [comment]
Stale. Please re-open a new issue if the proposed change is still required.
