### ISSUE TITLE
[Bug]Blurred image observed

### ISSUE THREAD

**Issue by AayushKumarChaudhary** [pupil-labs/pupil#795]
Settings:
Set eye video at 120Hz 640*480 resolution.
Settings Aperture (Auto Exposure Priority set)
Open both eye video 

Observation:
Blurred image observed
<img width="639" alt="screen shot 2017-08-14 at 5 05 46 pm" src="https://user-images.githubusercontent.com/24684456/29292434-08a3e7ba-8115-11e7-9cf7-eb4127991e7f.png">
<img width="636" alt="screen shot 2017-08-14 at 5 04 46 pm" src="https://user-images.githubusercontent.com/24684456/29292443-0ad1ad2e-8115-11e7-8121-66a254dd51cb.png">

**Comment by papr** [comment]
Dear @AayushKumarChaudhary 
could you specify what you mean with
> Settings Aperture (Auto Exposure Priority set)

Do you only enable `Auto Exposure Priority` or do you change something further?

**Comment by AayushKumarChaudhary** [comment]
Auto Exposure Mode is set to Aperture
and Auto Exposure Priority is enabled

**Comment by mkassner** [comment]
This is an artefact of the usb bandwidth factor not set high enough. When you changes cameras to this configurations (AE and AEP) you might start seeing these. Make sure that saturation is set to 0 to reduce image size.

If you still see the issues there are a few ways of fixing this:
1) Increase the bandwith factor (this is done here: https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_capture/uvc_backend.py#L115) This requires changing the source code.
2) Reduce image resolution
3) Use manual exposure

**Comment by mkassner** [comment]
I m going to close this. please make a new isse if required!
