### ISSUE TITLE
assert pyglui_version >= '1.6'

### ISSUE THREAD

**Issue by injoonhong** [pupil-labs/pupil#797]
when I run "run_capture.bat", I got this error msgs.

File "C:\work\pupil\pupil_src\launchables\world.py", line 76, in world
    assert pyglui_version >= '1.6'
AssertionError

I have checked pyglui repository but the latest release version is 1.4. 
Does anyone has an idea where I could git clone the >=1.6 pyglui ?

**Comment by papr** [comment]
Dear @injoonhong 
The upgrade process differs from OS to OS. Please check https://docs.pupil-labs.com/ on how to install dependencies for your operating system.

You can `pip3 install git+https://github.com/pupil-labs/pyglui` on macOS and Linux to install `pyglui` via `pip`

**Comment by injoonhong** [comment]
Dear @papr 
Thanks for your quick response. I am using Windows, and have downloaded the latest 1.4 pyglui for Windows. I can't see the later than 1.6 version of pyglui. Please let me know if you know how to download >=1.6 pyglui for Windows.

**Comment by papr** [comment]
Please read [this](https://docs.pupil-labs.com/#windows-pupil-labs-python-libs-from-source) and follow the [pyglui part](https://docs.pupil-labs.com/#pyglui-from-source).

**Comment by mkassner** [comment]
I think this is resolved.
