### ISSUE TITLE
interface size slider pushes widgets off window

### ISSUE THREAD

**Issue by dschreij** [pupil-labs/pupil#80]
v4.0 Ubuntu
When you set the interface size too large, it's widget may be placed outside of the window. When this has happened, there is no possibility to change the interface size to another value anymore (restarting doesn't help, you need to delete your settings folder to reset things)

**Comment by mkassner** [comment]
Thanks for the report!

I have fixed this in pupil and pyglui:
https://github.com/pupil-labs/pupil/commit/47f084f54c6788bd66e70c2c45deb52c8f8ba530
and 
https://github.com/pupil-labs/pyglui/commit/d40b5afab16cfbba23411f92f12de0a68b3ea675

If you pull both repos and reinstall pyglui it should be fixed. Alternatively just wait for the next bundle release.
