### ISSUE TITLE
KeyError: 'resolution'

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#823]
rafael@rafael:~$ pupil_player 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [INFO] launchables.player: Starting new session with '/home/rafael/recordings/2016_10_26/000'
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Updating recording from v0.9.13 to v0.9.15
Process player:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "launchables/player.py", line 650, in player_drop
  File "shared_modules/player_methods.py", line 121, in update_recording_to_recent
  File "shared_modules/player_methods.py", line 402, in update_recording_v0913_to_v0915
KeyError: 'resolution'

**Comment by cpicanco** [comment]
I guess it should be:
```
try
     // do stuff
except IOError, KeyError:
     // do stuff
```
https://github.com/pupil-labs/pupil/blob/0a01a227d9aa23856ee836c307fa6293b3b76014/pupil_src/shared_modules/player_methods.py#L411

**Comment by mkassner** [comment]
@cpicanco  can you send us a recording that does this? (We dont need video files but the rest.)

**Comment by cpicanco** [comment]
[000.zip](https://github.com/pupil-labs/pupil/files/1272258/000.zip)

**Comment by cpicanco** [comment]
@mkassner any news about that?

**Comment by papr** [comment]
So for some reason your recording data (`pupil_data` and especially `camera_calibration`) still have byte strings as keys instead of unicode strings. This means that you skipped the following part during the recording update:
```python
    if rec_version <= VersionFormat('0.8.7'):
        update_recording_bytes_to_unicode(rec_dir)
```

Applying `player_methods.update_recording_bytes_to_unicode(recording_dir)` to your recording manually should fix this and all other KeyError related issues of yours. :) Please backup your files* before doing this.

\* by files I mean if files that have been serialized with `file_methods.save_object`, e.g. `pupil_data`

**Comment by cpicanco** [comment]
Thanks, will try this out.

**Comment by papr** [comment]
Hey @cpicanco were you able to test it?

**Comment by cpicanco** [comment]
I am afraid this option did not work:

```
import os, csv_utils, collections
import numpy as np

def load_object(file_path,allow_legacy=True):
    def load_object_legacy(file_path):
        import pickle
        
        file_path = os.path.expanduser(file_path)
        with open(file_path, 'rb') as fh:
            data = pickle.load(fh, encoding='bytes')
        return data
    import gc
    import msgpack

    file_path = os.path.expanduser(file_path)
    with open(file_path, 'rb') as fh:
        try:
            gc.disable()  # speeds deserialization up.
            data = msgpack.unpack(fh, encoding='utf-8')
        except Exception as e:
            if not allow_legacy:
                raise e
            else:
                # logger.info('{} has a deprecated format: Will be updated on save'.format(file_path))
                data = load_object_legacy(file_path)
        finally:
            gc.enable()
    return data

def save_object(object_, file_path):
    def ndarrray_to_list(o, _warned=[False]): # Use a mutlable default arg to hold a fn interal temp var.
        if isinstance(o, np.ndarray):
            if not _warned[0]:
                # logger.warning("numpy array will be serialized as list. Invoked at:\n"+''.join(tb.format_stack()))
                _warned[0] = True
            return o.tolist()
        return o

    file_path = os.path.expanduser(file_path)
    with open(file_path, 'wb') as fh:
        msgpack.pack(object_, fh, use_bin_type=True,default=ndarrray_to_list)


def update_recording_bytes_to_unicode(rec_dir):
    # logger.info("Updating recording from bytes to unicode.")

    def convert(data):
        if isinstance(data, bytes):
            return data.decode()
        elif isinstance(data, str) or isinstance(data, np.ndarray):
            return data
        elif isinstance(data, collections.Mapping):
            return dict(map(convert, data.items()))
        elif isinstance(data, collections.Iterable):
            return type(data)(map(convert, data))
        else:
            return data

    for file in os.listdir(rec_dir):
        if file.startswith('.') or os.path.splitext(file)[1] in ('.mp4', '.avi'):
            continue
        rec_file = os.path.join(rec_dir, file)
        try:
            rec_object = load_object(rec_file)
            converted_object = convert(rec_object)
            if converted_object != rec_object:
                # logger.info('Converted `{}` from bytes to unicode'.format(file))
                save_object(converted_object, rec_file)
        except:
            continue

    # manually convert k v dicts.
    meta_info_path = os.path.join(rec_dir, "info.csv")
    with open(meta_info_path, 'r', encoding='utf-8') as csvfile:
        meta_info = csv_utils.read_key_value_file(csvfile)
    with open(meta_info_path, 'w', newline='') as csvfile:
        csv_utils.write_key_value_file(csvfile, meta_info)

if __name__ == '__main__':
    update_recording_bytes_to_unicode('/home/rafael/recordings/2016_10_26/000-copy')
```

```
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [INFO] launchables.player: Starting new session with '/home/rafael/recordings/2016_10_26/000-copy'
player - [INFO] player_methods: Updating meta info
Process player:
Traceback (most recent call last):
  File "shared_modules/file_methods.py", line 58, in load_object
  File "msgpack/_unpacker.pyx", line 164, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:2622)
  File "msgpack/_unpacker.pyx", line 146, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2231)
player - [INFO] player_methods: Updating recording from v0.9.13 to v0.9.15
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "launchables/player.py", line 650, in player_drop
  File "shared_modules/player_methods.py", line 121, in update_recording_to_recent
  File "shared_modules/player_methods.py", line 394, in update_recording_v0913_to_v0915
  File "shared_modules/file_methods.py", line 64, in load_object
  File "shared_modules/file_methods.py", line 48, in _load_object_legacy
EOFError: Ran out of input
player - [INFO] file_methods: /home/rafael/recordings/2016_10_26/000-copy/pupil_data has a deprecated format: Will be updated on save

```

**Comment by qalhata** [comment]
Hi Guys, Updated my Pupil capture and player software and now my old recordings from version 9.12.2 will not open on the player, it throws out the following error - Interface still loads - I attempt to upload the recording folder anyway and it crashes.. Please help!

Error Message on attempting to load a file is as follows:
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
>>> loadLibraries()
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
>>> createNativeWindow()
>>>_glfwInitWGL()
>>>Loading opengl32.dll
>>> _glfwCreateContextWGL()
>>> loadWGLExtensions()
>>> choosePixelFormat()

i tseems pretty self explanatory but I am not sure how to go about  resolving this - SOunds like some backward compatibility issue. Has this being solved and if so, please can anyone point me to the thread?

Many Thanks

Worried researcher. :-(

**Comment by cpicanco** [comment]
@qalhata , I am afraid the issue reported by you is not related to the current thread. Please, create a new issue if it is the case.
