### ISSUE TITLE
Have separate accuracy test

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#824]
Hi, it would be great if one could do an accuracy test on an "existing" calibration. I.e., one calibrates a subject, and performs the test after the experiment has finished as a sanity test. Right now, the old calibration is overwritten, and the accuracy which is being reported is on the new calibration.

This feature should be easy to implement I guess - if you hint me in the right direction, I could help out.

Best, Tobias

**Comment by mkassner** [comment]
Hi Tobias,

this is already built in. Just hit "T" instead of "C" . This will not calibrate but run an accuracy test. It works for every type of calibration in 2d and 3d mode.

I think we need to be more clear on this in our docs.

**Comment by Tobias-Fischer** [comment]
Awesome, I didn't know this. Thanks a lot!
