### ISSUE TITLE
Plugin closing behaviour in the upcoming UI revision

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#828]
PSA: We are working on revising the UI. See [pupil-labs/pupil@ui_refactor](https://github.com/pupil-labs/pupil/tree/ui_refactor) and [pupil-labs/pyglui@ui_improvements](https://github.com/pupil-labs/pyglui/tree/ui_improvements) for details.

---
@mkassner @willpatera @nathakits 

Currently all user plugins have a close button in their menu that will close the plugin. When one hits the button the plugin in closes, the icon is removed and an empty menu stays behind. What do you think should be the correct behaviour?

1. Plugins should not have such a button. Plugins are only removed using the plugin manager
2. A mechanism checks if the menu is empty
    1. If empty close the menu
    2. If empty jump show a different menu
        1. Most recent open menu
        2. General settings (first element in list)
        3. Last menu in list
        4. Plugin Manager

**Comment by mkassner** [comment]
I think we converged on remove the button.
