### ISSUE TITLE
set detection method on pupil_service

### ISSUE THREAD

**Issue by dmardanbeigi** [pupil-labs/pupil#829]
How can I set the pupil detection method to "c++ 3d"? I'm starting the eye process by sending {'subject':'eye_process.should_start.0','eye_id':0, 'args':{}} and the eye window appears with the default 2d detection method.

**Comment by papr** [comment]
Send the following notification after receiving `eye_process.started`:
```python
{'subject': 'set_detection_mapping_mode', 'mode': '3d'}
```

**Comment by dmardanbeigi** [comment]
Thanks.
