### ISSUE TITLE
Starting a Recording with a broken `session_name` freezes Capture

### ISSUE THREAD

**Issue by marc-tonsen** [pupil-labs/pupil#830]
If I send a notification like this

```
notification = {
'subject': 'recording.should_start',                            
'session_name': "/some/where/broken", 'delay': 0
}
```

where `"/some/where/broken"` is a location I have no write permission for, Capture just freezes.
Expected behavior: log a warning, do not start a recording, do not freeze.

**Comment by mkassner** [comment]
we should use os.path.join(rec_dir,session_name) and the `verify_path` fn in recorder and use the output to catch this bad input.
