### ISSUE TITLE
The selected camera is already in use or blocked.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#831]
H i, I was testing a DIY pupil in Ubuntu 16.04 LTS, in a notebook dell inspiron 15 5000 and I am keeping receiving this message:

```
world - [ERROR] video_capture.uvc_backend: The selected camera is already in use or blocked.
```
It is fully working on a desktop in the same lab though. Anything I can do to debug this?

Things I have tried: 

- sudo modprobe -r uvcvideo/ sudo modprobe  uvcvideo

Video1 and video2 are cameras from diy kit:

- fuser /dev/video1
- fuser /dev/video2

 Video0 is the integrated webcam (this one just to see what would happen):

- fuser /dev/video0
 
Thanks in advance!

**Comment by cpicanco** [comment]
Please, create a LABEL for device specific bugs. It would be useful.

**Comment by willpatera** [comment]
@cpicanco the camera that is in use or blocked is `video0`? Do I understand your issue correctly?

**Comment by cpicanco** [comment]
@willpatera , no. Sorry for my poor English, I was in a rush. All the cameras are in use or blocked: video0, video1 and video2.
