### ISSUE TITLE
WORLD: Turbojpeg

### ISSUE THREAD

**Issue by br1cks** [pupil-labs/pupil#834]
Hi,
I am running Pupil Capture on Ubuntu 1.04 LTS and everytime I am getting these warnings:
![bildschirmfoto vom 2017-09-24 20 00 01](https://user-images.githubusercontent.com/32245855/30785225-63bfdbfe-a163-11e7-827b-510388228d17.png)
It would be grateful if someone could tell me, how to switch off these warnings

**Comment by cpicanco** [comment]
Hi, please take a look here: https://github.com/pupil-labs/pupil/issues/399

You will need to load a simple plugin with the following line of code:

```
# remove all warnings
logging.disable(logging.WARNING)
```
or try
```
# remove uvc warnings
logging.getLogger("uvc_backend").set_level(logging.CRITICAL)
```

**Comment by br1cks** [comment]
Now the warnings are disabled. Thanks a lot!

**Comment by neopostmodern** [comment]
For me the correct call was

    # remove uvc warnings
    logging.getLogger("uvc").setLevel(logging.CRITICAL)

(notice how it is `setLevel` rather then `set_level` and `uvc` instead of `uvc_backend`)
