### ISSUE TITLE
Windows Pupil Player (and Pupil Capture) Crash | GLFW

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#837]
Referring Issue: https://github.com/pupil-labs/pupil/issues/769

```
C:\Users\user>C:\Users\user\Downloads\pupil_player_windows_x64_v0.9.14-7\pupil_player.exe
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
Process player:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "launchables\player.py", line 601, in player_drop
  File "shared_modules\glfw.py", line 522, in glfwCreateWindow
Exception: GLFW window failed to create.
```

OS: Win10, 64-bit, x64, Version 1703 (Build 15063.483)
dxdiag: opengl 12
tested on: Lenovo Thinkpad X201 (i5 M520) | 4GB RAM | Intel HD Graphics 
                 Lenovo Thinkpad X200
tested_versions: v0.9.14-7, v0.9.13-48, v0.9.12

Any idea, which driver or what is missing?

EDIT: There are no Windows 10 graphic driver versions available for both laptops. windows drivers are used

**Comment by mkassner** [comment]
A second user reported this issue via email. Can this be reproduced on windows.

**Comment by fneitzel** [comment]
I checked again on a Lenovo Thinkpad X201 (i5 M520) | 4GB RAM | Intel HD Graphics but with Windows 7.
Pupil Capture is working.
Here the original Intel Graphic Driver is installed.

**Comment by NikolSe** [comment]
![player_error](https://user-images.githubusercontent.com/32697513/31425391-6c314738-ae5f-11e7-8902-24bbcb3b9f13.jpg)
![windows](https://user-images.githubusercontent.com/32697513/31425395-75fea864-ae5f-11e7-8448-682f7c74790b.jpg)

**Comment by willpatera** [comment]
@fneitzel and @NikolSe I tried to recreate this behavior on a Windows 10 machine (v 1703 OS Build 15063.608). Unfortunately, I was not able to recreate the behavior you both observed. 

@fneitzel The machine I tested on uses a Intel Iris Graphics (I am not sure this is relevant here), but drivers are supplied by Intel. 

Do either of you have admin permissions on these machines?

**Comment by NikolSe** [comment]
Yes, I do.

Best, N.

Dňa 11.10.2017 12:35 používateľ "Will" <notifications@github.com> napísal:

**Comment by fneitzel** [comment]
Yes. Executed with admin permissions.

**Comment by willpatera** [comment]
Hi @fneitzel it looks like this could be related to your graphics card driver. If your graphics card driver does not support OpenGL, then you will need to update drivers for your graphics card.

@fneitzel and @NikolSe can you please try using this tool: realtech-vr.com/admin/glview to diagnose OpenGL issues on your machines? @NikolSe please list your graphics card and driver version so we can gain more insight.

**Comment by NikolSe** [comment]
Hello,

are these attachments everything you need or can I send something else?

**Comment by genchukov** [comment]
Hello guys,

i´ve the same issue. The mentioned tool is reporting that i´ve OpenGL 4.4. I also uploaded the GL-report from this tool. I hope this helps.
Thank you
[GL-report.txt](https://github.com/pupil-labs/pupil/files/1398309/GL-report.txt)

**Comment by genchukov** [comment]
Hey guys, 
i´ve a workaround which worked on my computer. Get the v.0.9.13 start it once then try again the 0.9.14 then it should work. I dunno why but it worked for me. Hope for you guys too.

**Comment by sbanca** [comment]
Same exact issue here, when I  open the Player v.0.9,14. I get GLFW window failed to create.
The workaround to open first the Player v.0.9.13 and then attempt to open Player v.0.9,14.  works for me to ...

**Comment by fneitzel** [comment]
@genchukov and @sbanca In my case the workaround didn't help. 
I also cannot start the OpenGL-reporting tool. It will crash as soon as it is initializing.

**Comment by pointcontrols** [comment]
@fneitzel @NikolSe @genchukov @sbanca Can you pease try with this bundle, and share console output: https://drive.google.com/file/d/1Bc_SAY1A40ZuP5kPlIeEg3KoMEUzMUJ1/view
We have added more diagnostic output in order to localize the issue. Thanks.

**Comment by genchukov** [comment]
worked fine.
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
glfwCreateWindow called with args:  1280 720 Pupil Player None None
player - [INFO] launchables.player: Starting new session with 'D:\IntAKom_backup\Trilux_backups\nuc\2017_09_21\001'
player - [INFO] player_methods: Updating meta info
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
player - [INFO] launchables.player: Application Version: 0.8.7.788
player - [INFO] launchables.player: System Info: User: m.saki, Platform: Windows, Machine: DESKTOP-DL393MR, Release: 10, Version: 10.0.15063
player - [INFO] camera_models: Previously recorded calibration found and loaded!
player - [INFO] launchables.player: Session setting are a different version of this app. I will not use those.
glfwCreateWindow called with args:  1280 720 Pupil Player: 2017_09_21 - 001 None None
player - [INFO] plugin: Loaded: Trim_Marks
player - [INFO] plugin: Loaded: Seek_Bar
player - [INFO] plugin: Loaded: Log_Display
player - [INFO] plugin: Loaded: Vis_Scan_Path
player - [INFO] plugin: Loaded: Vis_Polyline
player - [INFO] plugin: Loaded: Vis_Circle
player - [INFO] plugin: Loaded: Video_Export_Launcher
player - [INFO] plugin: Loaded: Pupil_From_Recording
player - [INFO] plugin: Loaded: Gaze_From_Recording

**Comment by fneitzel** [comment]
"C:\Users\username\Downloads\pupil_issue_837_bundle\Pupil Capture\pupil_capture.exe"                    `MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.                                   world - [INFO] launchables.world: Application Version: 0.8.7.788                                                        world - [INFO] launchables.world: System Info: User: testing, Platform: Windows, Machine: bogart, Release: 10, Version: 10.0.15063                                                                                                              world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend                                    world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.
glfwCreateWindow called with args:  1280 720 Pupil Capture - World None None                                            Process world:                                                                                                          
Traceback (most recent call last):                                                                                        
File "multiprocessing\process.py", line 249, in _bootstrap                                                              
File "multiprocessing\process.py", line 93, in run                                                                      
File "launchables\world.py", line 298, in world                                                                         
File "shared_modules\glfw.py", line 525, in glfwCreateWindow                                                          Exception: GLFW window failed to create.`

**Comment by pointcontrols** [comment]
@fneitzel Can you please try player? The debugs are there.

**Comment by fneitzel** [comment]
"C:\Users\testing\Downloads\pupil_issue_837_bundle\Pupil Player\pupil_player.exe"
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
glfwCreateWindow called with args:  1280 720 Pupil Player None None
GLFW Error code 65542 msg: b'WGL: The driver does not appear to support OpenGL'
Process player:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "launchables\player.py", line 609, in player_drop
  File "shared_modules\glfw.py", line 525, in glfwCreateWindow
Exception: GLFW window failed to create.

**Comment by pointcontrols** [comment]
@fneitzel Thanks. Can you please summarize which components of which bundle versions are working correctly on this particular machine?

**Comment by pointcontrols** [comment]
@genchukov Thanks. Can you still re-created the issue with the original 0.9.14 bundle?

**Comment by fneitzel** [comment]
@pointcontrols 
Windows 10: No bundle is working 
[GLFW_capture_player.txt](https://github.com/pupil-labs/pupil/files/1452343/GLFW_capture_player.txt)

But i downloaded and compiled GLFW:
C:\Users\testing\Downloads\glfw-master\build>C:\Users\testing\CMakeBuilds\55d59388-e7cb-9430-b18b-3d6730300925\build\x64-Release\tests\glfwinfo.exe
GLFW header version: 3.2.1
GLFW library version: 3.2.1
GLFW library version string: "3.2.1 Win32 WGL EGL VisualC"
OpenGL context version string: "2.1.0 - Build 8.15.10.2900"
OpenGL context version parsed by GLFW: 2.1.0
OpenGL context renderer string: "Intel(R) HD Graphics"
OpenGL context vendor string: "Intel"
OpenGL context shading language version: "1.20  - Intel Build 8.15.10.2900"
OpenGL framebuffer:
 red: 8 green: 8 blue: 8 alpha: 8 depth: 24 stencil: 8
 samples: 0 sample buffers: 0
 accum red: 16 accum green: 16 accum blue: 16 accum alpha: 16 aux buffers: 0
Vulkan loader: missing

**Comment by pointcontrols** [comment]
@fneitzel did you run the windows test of glfw after building?

**Comment by fneitzel** [comment]
@pointcontrols Do you mean that test?
![windows_exe](https://user-images.githubusercontent.com/10213803/32595098-ca0b99f4-c52e-11e7-84d5-a6115290cc35.PNG)

**Comment by pointcontrols** [comment]
@fneitzel Thanks, indeed that one. Can you please copy the glfw3.dll that was build to the pupil player bundle directory, and try to start pupil_player? It should replace the existing dll in the bundle .

**Comment by fneitzel** [comment]
I rebuild as shared_library.
windows.exe test and glfwinfo.exe worked as before.
But replacing glfw3.dll within pupil_issue_837_bundle led to the same issue as before.. GLFW Error code 65542 msg: b'WGL: The driver does not appear to support OpenGL'

**Comment by pointcontrols** [comment]
@fneitzel Can you please copy the windows.exe I have attached to a directory where your built glfw3.dll resides and try to run it? I have changed the hints and sizes to match what pupil is requesting.

[windows.zip](https://github.com/pupil-labs/pupil/files/1466136/windows.zip)

**Comment by willpatera** [comment]
@fneitzel please let us know when you have been able to test the `windows.exe` file that @pointcontrols has posted in the [above comment](https://github.com/pupil-labs/pupil/issues/837#issuecomment-343853041), so that we can try to resolve this issue.

**Comment by fneitzel** [comment]
@pointcontrols @willpatera I executed the exe ;)

![windows_exe_pupil_labs](https://user-images.githubusercontent.com/10213803/32801913-bce892dc-c97e-11e7-9e19-429d5d268559.PNG)

**Comment by pointcontrols** [comment]
@fneitzel  Thanks. I have uploaded a recompiled the exact same version of glfw, but with additional debug prints. Can you please replace the glfw3.dll inside the player bundle and try to run player again?

[glfw3.zip](https://github.com/pupil-labs/pupil/files/1488037/glfw3.zip)

**Comment by fneitzel** [comment]
@pointcontrols Here is the output

```
C:\Users\testing\Downloads\pupil_issue_837_bundle\Pupil Player>pupil_player.exe
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
>>> loadLibraries()
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
glfwCreateWindow called with args:  1280 720 Pupil Player None None
>>> createNativeWindow()
>>>_glfwInitWGL()
>>>Loading opengl32.dll
>>> _glfwCreateContextWGL()
>>> loadWGLExtensions()
>>> choosePixelFormat()
GLFW Error code 65542 msg: b'WGL: The driver does not appear to support OpenGL'
Process player:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "launchables\player.py", line 609, in player_drop
  File "shared_modules\glfw.py", line 525, in glfwCreateWindow
Exception: GLFW window failed to create.
```

**Comment by pointcontrols** [comment]
@fneitzel So just to recap, on the very same X201 laptop that runs Windows 10, you get failure of pupil player but the windows.exe works?

**Comment by genchukov** [comment]
@pointcontrols sorry for late answer. No i can´t recreate the issue anymore.

**Comment by papr** [comment]
https://github.com/pupil-labs/pupil/blob/master/pupil_src/launchables/player.py#L558

Actually, this issue might arise of one of the both values `w`/`h` being invalid. I could imagine that there is an edge case where the window size is stored incorrectly in the session settings and causes the crash on the next launch.

**Comment by mattem86** [comment]
Just for fun, I had this issue too for two hours – then I realized I cannot start any OpenGL things through Remote Desktop. Locally on the physical machine everything works fine. Just in case....

**Comment by emolyzr** [comment]
Hi, it's been more than 8 months since this issue has been raised. Any progress yet? Faced the same issue on a windows 10 laptop (HP Elite 8570 Pro WIN10 64bit Pro Edition), but not an other WIN10 Laptop (DELL Latitude 5580 WIN10 64bit Pro Edition). Would be thankful for support.

**Comment by papr** [comment]
I have not seen this error for a long time and was probably caused by invalid session settings. Please use the newest release. Can you confirm that using the newest release fixes the problem?

**Comment by emolyzr** [comment]
Yes, the newest release was used. Deleting the session settings from the User folder didn't solve the problem. Graphics Card is Intel HD 4000. Which Version of open GL is needed? Thanks!

**Comment by pointcontrols** [comment]
@emolyzr Have you updated your graphics drivers?  Here is a link from Intel:

https://downloadcenter.intel.com/product/81499/Intel-HD-Graphics-4000

**Comment by emolyzr** [comment]
SOLVED: I found a way to install the Intel latest drivers (3/2018). It works now! With the HP drivers (8/2015), it did not work. May be helpful for future support. Many thanks!

**Comment by pointcontrols** [comment]
Thanks for the heads up, I am glad that the issue is resolved for you!

**Comment by willpatera** [comment]
I just discussed this issue with another user and updating drivers on their system resolved this issue. I will be closing this issue now as it is not Pupil related, but Windows driver related. 

Updating graphics drivers will resolve the issue.
