### ISSUE TITLE
v0.4 make player do not close on esc press

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#84]
That is it.

**Comment by mkassner** [comment]
added.

**Comment by cpicanco** [comment]
Sorry about that, but player was closing without any hotkey in the code! I have closed it by accident and I think it would be good to avoid closing it by pressing esc.

**Comment by cpicanco** [comment]
Player was closing without any hot key by pressing esc.

**Comment by cpicanco** [comment]
Maybe a warning prompt before the close action?? ?? ?? ?? ??

**Comment by mkassner** [comment]
Ah ok. I agree. I added a button instead and removed the hotkey.
