### ISSUE TITLE
Issue with offline calibration and RealSense R200 scene camera tracker.

### ISSUE THREAD

**Issue by ksm2264** [pupil-labs/pupil#845]
We are running Pupil Capture from source in order to record eye and scene camera videos through our R200 mounted tracker. When we try to use Pupil Player to do offline pupil detection, it runs all the way through both of the eye videos and files appear in the "offline_data" folder but then when we try to do offline calibration the message: "PLAYER: No pupil data to calibrate section '1'" appears. This is when we're trying from Linux, on Windows the player is unable to get all the way through the offline pupil detection and crashes. Could this be an issue with the R200 tracker and Pupil Player?

**Comment by papr** [comment]
Make sure that the `Detection Method` is set to the same mode as the pupil `detection mode`, matching your recorded data or settable in the `Pupil Offline Detector`.

**Comment by ksm2264** [comment]
Thanks for the reply.

If you are referring to the detection mode set in the eye camera windows during recording then yes they were set to the same mode as the detection method in the pupil offline detector. I just tried setting them all to 2d and recording a short video and I am getting the same error message. 

Also potentially related is a bug where the progress bar for the offline pupil detection goes over 100% until about 400% then becomes negative but eventually finishes and closes.

**Comment by papr** [comment]
Mmh, ok. Could you upload your recording to Google Drive and share it with me? This would help me to reproduce your issue. Please send the link to the recording to pp@pupil-labs.com

**Comment by ksm2264** [comment]
Alright just tried to make a recording to reproduce this to share with you
but it didn't have the problem and worked. I guess following the
instructions from your first response more carefully fixed the problem.
Thanks!

**Comment by papr** [comment]
Ok, good to hear! :)

**Comment by ksm2264** [comment]
Hi sorry to re-open this. I have run into this issue again, but found that I get around it by toggling "Detect Eye 0/1" off and on. If I do not do this I run into the problem.
