### ISSUE TITLE
Recording Interrupt / Lost data

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#854]
I recorded (v0.9.14) with a binocular pupil and the cable was accidently removed after 30 minutes.
Wasn't there something like a rescue saving? The only files i had in my recording folder, where broken mp4s.

Is it possible to save the current recording data if the pupil loses connection?

Best

**Comment by mkassner** [comment]
Usually this works. But we have recently fixed some bugs in the backend
that crashed the software on disconnects occasionally.
This should not happen with recent versions.

Do you happen to have a log or terminal output from that session?

**Comment by fneitzel** [comment]
I tried to reproduce the issue yesterday. When i lost recording files the world camera dissappeared including of an ubuntu bug notification.

This didn't happen yesterday. 
Recordings were saved correctly. 

If USB was disconnected - recording time continued.
- If Pupil Capture was stop by closing software - the recording was saved.
- If capture was stopped - the recording was saved.

If Pupil was reconnected while still recording - cameras were found and recording continued.
- saving files also worked with closing the software and stopping the recording. (the video just have gaps)

Today we will try to reproduce the issue with longer recording times close to 30 minutes.

**Comment by fneitzel** [comment]
I couldn't reproduce this Issue even with longer recordings.
