### ISSUE TITLE
Pupil Group Issue/Enhancement

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#856]
If the world camera is not initialized, then the recording will not start on the uninitialized computer. However it will start on the other computers in the group. 
If you press recording again on the uninitialized computer the recording will not stop on the other computers.

**Comment by mkassner** [comment]
@papr I see some options: make clear that the user should switch to fakeCapture or allow recordings with no world video. Any other ideas?

**Comment by papr** [comment]
I think it will be difficult to not have a world video. Where would we get the world timestamps from? We could automatically start a fake capture though...

**Comment by papr** [comment]
We decided to not go for the automatic fake capture activation. To solve this issue one would have to intercept notifications after they have been sent out. Implementing this would increase the code complexity disproportionately. In the end this is a configuration issue not a program issue.
