### ISSUE TITLE
Pupil Player - Offline Calibration - Close Plugin

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#859]
The Offline Calibration plugin is missing the 'Close' button.

**Comment by papr** [comment]
This is intentional since it is mutually exclusive to the Gaze From Recording plugin. This will be more clear in the new UI.

**Comment by papr** [comment]
But this brings me to the idea of integrating `Gaze From Recording` as a fixed, read-only calibration section in Offline Calibration...
