### ISSUE TITLE
ui refactor plugin api

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#861]
I think the new refactor is great. I would like to discuss:

```python
    @classmethod
    def icon_info(self):
        return 'roboto', '?'
```

I think just adding 

```python
class Plugin(object):
    icon_chr = '?'
    icon_font = 'roboto'
    ...
```

is more simplistic but behaves the same way.

Actually in an ideal world I would like to set both by modifying self.menu_icon.font and self.menu_icon.label in `init_ui`. But I understand that there are problems from the implementation side.

**Comment by papr** [comment]
It would also be more consistent with uniqueness and order

**Comment by mkassner** [comment]
Furthermore. Do we really need the icon_font option? I understand that being able to use letters helps but then again, just adding some more icons that the user can choose is equally helpful and reduces complexity in the below code as well:

```python
        font, symbol = self.icon_info() <<<<-
        y_offset = 1 if font == 'pupil_icons' else 0  <<<<-
        self.menu = ui.Growing_Menu('Unnamed Menu', header_pos='headline')
        if self.uniqueness == 'not_unique':
            self.menu.append(ui.Button('Close', close))
        self.menu_icon = ui.Icon('collapsed', self.menu, label=symbol,
                                 label_font=font, on_val=False, off_val=True,
                                 setter=toggle_menu, label_offset_y=y_offset) <<<<-
```
