### ISSUE TITLE
Insert Virtual Surface in frame

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#87]
It is an idea for both
- a) add a virtual ~~marker~~ surface when no ~~marker~~ surface was used at all
- b) when actual ~~markers~~ surfaces were not detected, one have the option to add it manually.

Automation is good, of course, but this feature, even being time consuming, can save your skin if anything goes wrong for any reason...

I think that a good way to implement would be an "add marker by id" button in the off line marker detector, surface edit mode.

Is it possible??

**Comment by cpicanco** [comment]
Kind of "Draw surface" feature hum?

**Comment by mkassner** [comment]
Yes, I think this could be very useful. I m not sure how to do it best though.

**Comment by cpicanco** [comment]
@mkassner, hope this help, I will try to describe some functionality I expect to be very useful and easy to use:

##### Inherit actual markers functionality as much as possible;
- session persistent;
- drag and drop;
- define surface;
- and so on);
- display frames with virtual markers in the seek bar (simple feedback);  

##### New functionality
- interaction with actual markers;
- add a new virtual marker by clicking in the world image;
- if the last frame already have a virtual marker, a shortcut to copy it to the current frame would be very handy;

**Comment by mkassner** [comment]
How about working with surfaces instead of markers? Feels more useful to me.

**Comment by cpicanco** [comment]
Since markers are used to define surfaces, agreed. I have suggested something like this in the [google group](https://groups.google.com/forum/#!topic/pupil-discuss/nzHl5Z_WQaE)

**Comment by mkassner** [comment]
With the new marker interface I think we can close this?

**Comment by cpicanco** [comment]
The new interface does not implemented inserting a virtual marker at a custom position. Better close due inactivity.
