### ISSUE TITLE
Pupil Player crashing when importing pupil mobile data

### ISSUE THREAD

**Issue by smousley1995** [pupil-labs/pupil#873]
When dragging the file of pupil mobile data into pupil player on macbook pro, OS X El Capitan V10.11.6, pupil player crashes and shuts down in a split second.
Tried running Pupil player on windows through parallels but same issue.

2015 macbook pro
Pupil player Version 0.9.14-10
Pupil mobile Version 0.17.0

**Comment by willpatera** [comment]
@smousley1995 this is known and is fixed in the current master branch. It will be fixed when we release the next app bundle (hopefully early next week :smile:).
