### ISSUE TITLE
v0.4 make resize square more appealing

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#88]
Maybe changing its color to some color different from the backgroud. I was not the first and [will not be last one](https://groups.google.com/forum/#!topic/pupil-discuss/33jQm4ykT1U) to have difficult moments trying to find the resize control.

**Comment by mkassner** [comment]
Agreed. We will have a look!

**Comment by mkassner** [comment]
I made the resize corner stand out more. please pull, rebuild pyglui and try.

**Comment by cpicanco** [comment]
I will do it on Tuesday!

**Comment by willpatera** [comment]
@mkassner Looks good!
