### ISSUE TITLE
Runtime calibration plugin ui does not initialize

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#880]
Hi, I am afraid recent changes in ui initialization (def init_ui) broken my custom runtime calibration plugin:

```python
    def init_ui(self):
        super().init_ui()
        self.menu.label = "Participant Driven Screen Marker Calibration"
        self.monitor_idx = 0
        self.monitor_names = [glfwGetMonitorName(m) for m in glfwGetMonitors()]
        #primary_monitor = glfwGetPrimaryMonitor()

        self.menu.append(ui.Info_Text("Calibrate gaze parameters pressing space key for each marker."))

        self.menu.append(ui.Selector('monitor_idx',self,selection = range(len(self.monitor_names)),labels=self.monitor_names,label='Monitor'))
        self.menu.append(ui.Switch('fullscreen',self,label='Use fullscreen'))
        self.menu.append(ui.Slider('marker_scale',self,step=0.1,min=0.5,max=2.0,label='Marker size'))
        self.menu.append(ui.Slider('sample_duration',self,step=1,min=10,max=100,label='Sample duration'))
```

Only the name of the plugin is showing up in the menu:
![image](https://user-images.githubusercontent.com/6511849/31788142-3906104c-b4e4-11e7-9fd8-b632c04dd44a.png)

So what should I do to initialize its ui???

**Comment by papr** [comment]
@cpicanco Hey, is this still an issue? From the screenshot it looks like you are not running v1 but an older version. E.g. the icon bar is missing.

**Comment by cpicanco** [comment]
@papr, I am running the most up to date bundle: v0.9.14.7, so yes, it is still an issue. I am not able to test from source right now.

**Comment by papr** [comment]
The new plugin ui initialization api is only available on v1 and therefore does not work on v0.9.14

**Comment by cpicanco** [comment]
Thanks for the information.

**Comment by cpicanco** [comment]
As a work around I am hard coding the stuff I want.
