### ISSUE TITLE
Support for ordinary webcam

### ISSUE THREAD

**Issue by breznak** [pupil-labs/pupil#887]
Could your solution work with a generic webcam available on most of the notebooks today? 
I'd like to use the framework, but I don't want to use the HW. I'm aware the functionality may be limited, I just want a basic eye-tracking, pupil/blink detection. 
Thank you,

**Comment by papr** [comment]
Hey @breznak 
Our software supports all usb cameras that support the UVC standard. Please be aware that our software is not designed for remote eye tracking but for head-mounted eye trackers.
