### ISSUE TITLE
macOS - brew OpenCV3.3.1 `lib` and `include` path update

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#890]
## Overview
OpenCV path for linking in OpenCV `v3.3.1` has changed for brew installed `opencv`. This is brew's current default opencv. 

## Changes suggested
Update paths to `/usr/local/opt/opencv/lib` and `/usr/local/opt/opencv/include` for pupil detectors and optimization calibration setup. 

https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py#L65-L66 

https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/pupil_detectors/setup.py#L65-L66

**Comment by papr** [comment]
Do I see it correctly that these need to change from `opencv3` to `opencv`?

**Comment by papr** [comment]
This is not the only change: https://github.com/pupil-labs/pupil/issues/893#issuecomment-340509806

**Comment by willpatera** [comment]
@papr I have updated opencv. We should also make the changes to the setup.py files as noted above.
