### ISSUE TITLE
Pupil Player - Offline Pupil Detector Plugin icon progress indicator with monocular eye video

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#892]
## Overview
The offline pupil detector plugin's icon in the sidebar only shows 50% progress when progress is actually 100% with monocular eye data. 

![pupil_player_icon_progress_issue](https://user-images.githubusercontent.com/1407224/32097911-3a9b7814-bb35-11e7-8055-acc1454a69aa.png)

## Todo
Icon's progress indicator should complete the circle even with monocular data.

**Comment by mkassner** [comment]
Fixed with #898
