### ISSUE TITLE
Pupil Player 0.9.15 - Memory load

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#895]
We have pupil recordings with 70GB file size. - 1hour recordings. ~30GB world.mp4 - rest eyes.
pupil_data is 1.2 GB file size. Memory usage is at 96% and it takes forever to open videos. I tried faking the world video and compressed the mp4 files, but it doesn't help to open them. Is it possible to speed up the opening process?

**Comment by willpatera** [comment]
@fneitzel this issue will be addressed in v1.1 - I would like to migrate discussion of this issue into a centralized location. Please see: https://github.com/pupil-labs/pupil/issues/889#issuecomment-340471511
