### ISSUE TITLE
subprocess.CalledProcessError: returned non-zero exit status 1

### ISSUE THREAD

**Issue by boxiXia** [pupil-labs/pupil#896]
Hello! I followed the instructions for installing windows dependencies. When I ran main.py I got this error:
`C:\work\pupil\pupil_src>python main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\work\pupil\pupil_src\launchables\world.py", line 113, in world
    import pupil_detectors
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python36\\python.exe', 'setup.py', 'install', '--install-lib=C:\\work\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 1.`
I have tried reinstalling multiple times but ended up the same error message. Any help would be appreciated!

**Comment by papr** [comment]
Hey @boxiXia 
Is this the complete terminal ouput? Unfortunately, the log does not say anything about the actual failure reason. =/

**Comment by boxiXia** [comment]
@papr 
Yes, this is the complete output, I suspect this`cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'` is causing the problem, please help, thank you!

**Comment by o221806** [comment]
Got the same problem here

Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
================== RESTART: C:\work\pupil\pupil_src\main.py ==================
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\work\pupil\pupil_src\launchables\world.py", line 113, in world
    import pupil_detectors
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 22, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python36\\pythonw.exe', 'setup.py', 'install', '--install-lib=C:\\work\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 120.

>>> 

Have no idea how to fix it.

**Comment by papr** [comment]
@willpatera What do you think? Could this issue be due to missing dependencies? Or what these show up in the log?

@boxiXia @o221806 Could you check if there is a log file after the crash? You should be able to find it (`capture.log`) in the Pupil Capture settings folder.

**Comment by willpatera** [comment]
@boxiXia and @o221806 it looks like modules that need to be compiled in `shared_modules` are not being compiled. I conjecture that you either do not have dependencies like Ceres and Boost installed as needed. 

Notes:
- Compiler warnings are not the cause of this issue (e.g. `overriding /w3 with w` or `ignoring unknown option '-std=c++11`). 
- Running Pupil. I would suggest using `run_capture.bat` to start Pupil Capture as noted in the docs. 
- Compile `pupil_detectors` with `python setup.py build` prior to running `run_catpure.bat` and inspect any error logs produced upon building these modules. 
- Compile `optimization_calibration` with `python setup.py build` prior to `run_capture.bat` and inspect any error logs produced upon building these modules. 
- Finally, please follow closely the notes in the [docs](https://docs.pupil-labs.com/#windows-dependencies) - these install instructions are proven to work on a clean/fresh install of Windows.

**Comment by o221806** [comment]
Got this imformation after running python build.py
C:\work\pupil\pupil_src\shared_modules\pupil_detectors>python build.py
INFO:__main__:Building extention modules...
error: Unable to find vcvarsall.bat
Traceback (most recent call last):
  File "build.py", line 29, in <module>
    build_cpp_extension()
  File "build.py", line 22, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python36\\python.exe', 'setup.py', 'install', '--install-lib=C:\\work\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 1.

**Comment by fneitzel** [comment]
@o221806 Your error notes that python cannot find the correct runtime environment
Visual C++ Redistributable for Visual Studio 2015 should help: https://www.microsoft.com/de-de/download/details.aspx?id=48145
Make sure to include vcvarsall.bat to your windows path.

**Comment by sunggeunAhn** [comment]
@willpatera I really appreciate your comment. I also have been suffered from same error and now I finally fixed this error. 
This problem comes from fixed path/file name with specific version of opencv, boost.
I think there need clarify the versions on the DOCS,
just like, in case of opencv, you should be download ver. 2.3 and, in case of boost, you should be use ver. 1.6.4, or state that if you use another version, you should be modify the file name in the xxx.py file.

**Comment by willpatera** [comment]
@sunggeunAhn Thanks for following up, this is very useful information. Please open an issue on the docs repo: https://github.com/pupil-labs/pupil-docs/ so that we can evaluate your changes and ideally improve the docs 😄

**Comment by jhs0053** [comment]
@sunggeunAhn  Hello. I have same problem. So, Could you explain 'This problem comes from fixed path/file name with specific version of boost in python code.' in detail?

**Comment by sweetboxwwy** [comment]
I have the problem:      subprocess.CalledProcessError: Command '['python', 'utils/get_pretrained_checkpoints.py', '--model=ResNet101']' returned non-zero exit status 1.

**Comment by ishaanchaturvedi** [comment]
@sweetboxwwy  i have the same issue could some one help

**Comment by papr** [comment]
The pupil detectors are no longer build on runtime (original issue). Instead they can be installed via PyPI
```
pip install pupil-detectors
```
This is only necessary if you run from source, though.

@ishaanchaturvedi @sweetboxwwy It looks like you are trying to run an external plugin or an outdated version of Pupil Capture. In case of the former, please contact the plugin's author. In case of the latter, please upgrade your Pupil Core software and create a new issue if you encounter any problems. Alternatively, chat with us on [Discord](https://pupil-labs.com/chat).
