### ISSUE TITLE
What are the exact requirements for the opengl rendering of Pupil Player?

### ISSUE THREAD

**Issue by kannes** [pupil-labs/pupil#907]
#837 has people confused and helpless with 

> Exception: GLFW window failed to create.

Can you please clarify which OpenGL features must be supported for Pupil Player to work?

**Comment by willpatera** [comment]
@kannes we are actively working to debug this issue. If you are having issues running Pupil Player on Windows 10, please provide us with feedback according to [this comment] in #837 

I would like to consolidate conversation concerning this issue in #837.
