### ISSUE TITLE
Eye Video causes Player to crash

### ISSUE THREAD

**Issue by drpearcy** [pupil-labs/pupil#910]
Using Pupil v0.9.14-7_windows_x64.7. I am using Windows 10
I can record both world and eye streams just fine, but when dragging and dropping the directory into the pupil player it crashes almost immediately. Does not occur when only the world video stream is there. I believe the only setting I changed was record eye video or not. Image below is screen shot of command window before it crashes and auto closes.
![screenshot 11](https://user-images.githubusercontent.com/33429276/32457930-a77bcb76-c2f8-11e7-94ba-eae5bd28c264.png)

**Comment by mkassner** [comment]
can use share the eye image video file?

**Comment by drpearcy** [comment]
Zip files contains files that are in a folder on my computer named "001" following the default path for saving files in the program. Just large enough not to fit as one attachment in the comment.
[Eye Video Files.zip](https://github.com/pupil-labs/pupil/files/1450496/Eye.Video.Files.zip)
[World Video Files.zip](https://github.com/pupil-labs/pupil/files/1450498/World.Video.Files.zip)

**Comment by mkassner** [comment]
We tested the video file and it seems that the eye video is corrupted. I m not sure how we can fix this.

**Comment by mkassner** [comment]
Does this happen with more than just this recording?

**Comment by drpearcy** [comment]
Yes. The original recording I had was too large to attach in a zip file to you, so I quickly made another short video (5seconds), and then tested it to see if it would crash like the original file. The tests were done on two separate days.

**Comment by mkassner** [comment]
ok. one more test: Can you change the recording setting to small file high cpu and try again?

**Comment by drpearcy** [comment]
Updated to App version 0.17.1 Commspec Version: v3. I seem to have the issue now where I cannot detect the eye in pupil capture. I just have a grayed out window. I have the record eye setting and I have the detect eye 0 engaged. I've tried both 2d and 3d detection and both show a grayed out window. This may fall under a different question though. 

Yes papr, I am streaming to pupil capture and recording it withing Pupil capture itself.

**Comment by papr** [comment]
1. Did you select the Pupil Mobile backend in the eye window and selected the correct eye camera as source? Please check if the cameras are listed correctly in the app if Pupil Capture does not list them.
2. We recommend recording on the phone directly. Streaming is meant more as a monitor feature where data loss does not matter. What happens is that you record broken frames that Pupil Player can not handle (yet) and will crash the application.

**Comment by drpearcy** [comment]
1. Yes, I selected Pupil Mobile, in the eye window and had the correct eye camera, which is showing up fine in the app. 
2. I understand that there is a chance of dropped frames. Before I saw your edit I did a local recording to the Android device and then transferred them to my computer. Where in they would cause pupil player to crash when dragging in the directory. I saw on issue "Pupil Player crashing when importing pupil mobile data #873", which has been closed, that this was a known issue and would be resolved shortly. has that patch been put out yet?

**Comment by mkassner** [comment]
@papr  I think the use case of streaming + local recording on the PC is valid. I think this should work. @drpearcy  please check if the issue remains once you have the latest version of Pupil Mobile running.

**Comment by drpearcy** [comment]
Where the system is at now: 
1. Pupil Mobile Version 0.17.1 (I believe this is the latest version of Pupil Mobile.) on Nexus 6P
2. Pupil Capture/Pupil Player v0.9.14
3. Using Windows Machine, Windows 10.

Recording on Computer via Private Network(only 2 devices on it, computer running Pupil Capture/Player and Android Device running Pupil Mobile) Streaming Pupil Mobile:
1. Record using Compression (larger file, smaller CPU) records fine. Upon putting directory into Pupil Player, Pupil Player crashes.
2. Record using Compression (smaller file, larger CPU) the eye video freezes immediately, and the recording folder is missing the "eye0" MP4 File and the "eye0_timestamps" NPY File. Upon putting directory into Pupil Player it opens, but there is an error message across the screen saying the eye files are gone/could not be opened (which makes sense, since they are not there). Pupil Player seems to work fine for the world view recording.
3. I mentioned earlier an issue with not being able to view the eye video stream. That was a settings error on my end. Sorry to add more confusion to the mix.

Recording on Android device and transferring files after the recording.
1. When putting the directory(Named as only the date example:20171107162717418 ) straight from the phone into Pupil Player. The player does not respond/doesn't recognize I am trying to drag and drop a directory.
2. Removed the folder from phone and placing it into \recordings\2017_11_07 on computer where Pupil Capture had saved my other pupil labs recordings I took on the same date reside. When dragging the directory(still named after the date) into Pupil Player, it crashes.
3. Changed the name of the folder from the date to "009" to follow the same naming convention as the other recorded folders in the folder "recordings". Upon dragging the newly named directory into Pupil Player, it crashes.

Hope this was a helpful breakdown of everything.

**Comment by papr** [comment]
This is very helpful! Thank you very much. @willpatera we should test this on the new bundles before releasing them.

**Comment by papr** [comment]
Reproducable when running from source on Linux.
