### ISSUE TITLE
Check update availibilty

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#925]
It would be great if people could be notified about new releases and updated bundles from within the app. Maybe with a link to the download page.

**Comment by cpicanco** [comment]
Please, do not do this during recordings!!! :smile:

**Comment by papr** [comment]
Very good point! My idea was to have a small overlay in the lower left corner that states 'Update available' and is clickable. This would be visualized with opengl and would not be part of the recording.

**Comment by cpicanco** [comment]
Maybe a notice during start-up? Like sublime text?

**Comment by papr** [comment]
Yes, this could be an option as well. We will evaluate different options. Please add further implementation ideas as they come up.

**Comment by cpicanco** [comment]
A "clickable" and "closeable" would be nice to. People with small screens like me would thank you.

**Comment by fneitzel** [comment]
Please don't make it too advertised in case of: 'I don't want to upgrade and I still don't want to upgrade on next restart'

**Comment by papr** [comment]
This can definitively be an opt-out feature.

**Comment by papr** [comment]
Implementation idea drafted by @willpatera and I:
Small plugin that is loaded by default but has no icon in the sidebar unless there is an update available. Users that do not want to check for updates can disable the plugin in the plugin manager. If an update is available the plugin's menu will include a button that will open the Github release page upon clicking the button.

**Comment by papr** [comment]
There will be no need for this as we continue stabilizing the software and its feature set.
