### ISSUE TITLE
Have you tested ELSE detector in offline mode?

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#928]
Just wondering. Non-commercial research would benefit a lot, I guess.

**Comment by papr** [comment]
There was no offline mode when we tested it. But this is a good idea since we decided against its used due to its high computational costs that are not relevant for offline detection. I am not sure though if their license allows it to bundle ELSE with our application.

**Comment by cpicanco** [comment]
Your application may be used for non-commercial purposes even inside pupil-labs. So, I would say not a problem at all for those use cases. Of course, you would remove this specifc feature when selling licenses. So, in accord with my interpretation, not a problem at all.

**Comment by cpicanco** [comment]
> Of course, you would remove this specifc feature when selling licenses. 

An alternative approach is discuss with ELSE author some sort of fee for selling it.

**Comment by papr** [comment]
Independent of any licensing issues, the ELSE detector only provides a 2d location without the pupil ellipse. The ellipse is required for our 3d model. Therefore the ELSE detector is not compatible with the current Pupil pipeline.
