### ISSUE TITLE
Pupil capture 1.1.2 processes crash when trying to change the camera source

### ISSUE THREAD

**Issue by gendelo3** [pupil-labs/pupil#932]
Hi, 
after updating to 1.1.2
(clean install using purge and apt install of the .deb packages on Ubuntu 16.04),
almost every time I try to change the camera that is used as source for eye detection or world, the corresponding process crashes.

Pupil capture selects my notebooks integrated camera per default for eye0, and I cant change that to "id0" or "id1", because when I try to do so via "Activate source" -> "Select to activate", the eye0  process crashes. The "Detect eye0" checkbox (green circle in pupil capture general settings) stays green and loses its functionality too (clicking it doesn't do anything anymore).

The crashes are not limited to the eye camera selection, when I change the world camera to "id0" it works, but trying to change it back to "id2" causes a crash of pupil capture.

Thanks for your time.

**Comment by papr** [comment]
Thanks for creating the github issue. Could you run `pupil_capture` from the terminal and test again? The trace back of the crash should have been logged to the terminal. Please copy and paste it to this issue.

**Comment by gendelo3** [comment]
This is the full outpup from the start till the crash of pupil capture. 
eye0 first uses my notebooks camera. 
I tried to switch/crash in the order:
- eye0 -> "id0" (crash)
- eye1 -> "id0" (crash)
- world -> "id1" (working)
- world -> "id0" (crash, back to terminal)

As far as i could see, the crashes did not generate extra output in the terminal I ran  pupil capture from.

From terminal (sorry, I#m not familiar with proper formatting)
13:38 $ pupil_capture
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.1.2
world - [INFO] launchables.world: System Info: User: username, Platform: Linux, Machine: mynotebook, Release: 4.10.0-38-generic, Version: #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017
world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
world - [INFO] plugin: Added: <class 'pupil_lsl_relay.Pupil_LSL_Relay'>
world - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution (1280, 720)
world - [INFO] camera_models: Loading pre-recorded calibration
world - [DEBUG] pupil_lsl_relay: Connecting to tcp://127.0.0.1:37419...
world - [WARNING] launchables.world: Process started.
Estimated / selected altsetting bandwith : 904 / 1600. 
!!!!Packets per transfer = 32 frameInterval = 327868
eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye0 - [INFO] camera_models: No user calibration found for camera Integrated Camera at resolution (640, 480)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] uvc: Could not set Value. 'Absolute Exposure Time'.
eye0 - [WARNING] uvc: Could not set Value. 'White Balance temperature'.
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
eye0 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 309 / 960. 
!!!!Packets per transfer = 32 frameInterval = 333333
eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID0 at resolution (640, 480)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
eye1 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 579 / 800. 
!!!!Packets per transfer = 32 frameInterval = 111111
eye0 - [INFO] video_capture.uvc_backend: Found device. Integrated Camera.
eye0 - [INFO] camera_models: No user calibration found for camera Integrated Camera at resolution (640, 480)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] uvc: Could not set Value. 'Absolute Exposure Time'.
eye0 - [WARNING] uvc: Could not set Value. 'White Balance temperature'.
Estimated / selected altsetting bandwith : 309 / 960. 
!!!!Packets per transfer = 32 frameInterval = 333333
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID1 at resolution (640, 480)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
Estimated / selected altsetting bandwith : 579 / 800. 
!!!!Packets per transfer = 32 frameInterval = 111111
world - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID0 at resolution (1280, 720)
world - [INFO] camera_models: No pre-recorded calibration available
world - [WARNING] camera_models: Loading dummy calibration
Estimated / selected altsetting bandwith : 592 / 800. 
!!!!Packets per transfer = 32 frameInterval = 327868
✔ ~/pupil_capture_settings/plugins 
13:38 $

**Comment by gendelo3** [comment]
I did a log with `pupil_capture debug`:

[pupil_capture_debug.txt](https://github.com/pupil-labs/pupil/files/1474122/pupil_capture_debug.txt)

**Comment by gendelo3** [comment]
And this one as well with a longer error message showing up too:
[pupil_capture_debug2.txt](https://github.com/pupil-labs/pupil/files/1474154/pupil_capture_debug2.txt)

**Comment by papr** [comment]
@gendelo3 Thank you for uploading the log files. The second log file indicates an underlying uvc issue that we will have to investigate.

For your interest, if `eye1` is using `id0` you will not be able to select `id0` in `eye0`. It will report that
> The selected camera is already in use or blocked.

Close the `eye1` window or activate the test image in `eye1` before setting `eye0` to `id0`.

**Comment by papr** [comment]
@gendelo3 Also try to use the `Restart with default settings` button in the general settings. This should reset the camera selection.

**Comment by gendelo3** [comment]
@papr 

> For your interest, if eye1 is using id0 you will not be able to select id0 in eye0. It will report that [...]

Yes, i know, that did only appear in the log because I accidentally selected a camera that was in use.

> Also try to use the Restart with default settings button in the general settings. This should reset the camera selection.

Doing this together with the changes in your pull request should be a workaround for my issue although I was not able to test it yet.

**Comment by gendelo3** [comment]
The workaround is working. It now selects the right cameras for each window. But I can still make the software crash by selecting another one of the eye cameras that are not in use.
