### ISSUE TITLE
Natural Features Offline Calibration Issue

### ISSUE THREAD

**Issue by LHicken** [pupil-labs/pupil#934]
I have downloaded the new Pupil Capture and Player. When I go into Player to do offline calibration with natural features, I click on a natural feature to mark it, but the mark appears up and to the left about two inches away on the screen.

**Comment by papr** [comment]
The issue was that position of the click was calculated incorrectly for Macs that have a Retina Display. This will be resolved with #935 and will be fixed in the next release.
