### ISSUE TITLE
Pupil Player 1.1 does not function

### ISSUE THREAD

**Issue by brittAnderson** [pupil-labs/pupil#936]
Downloaded the 1.1 service, capture, and player app debs for a fresh installation of linux 64 bit (Xubuntu 16.04). Installed with `sudo dpkg -i <app-name>.deb`. The pupil_capture app works properly, but attempting to launch the pupil_player produces only a single gray window which displays the message to drop the recording file on to it, but then does nothing when folder dropped. Same with dropping folder on the app icon. Same with going into the pupil_player folder in a terminal and launching.
  
    cd /opt/pupil_player
    ./pupil_player ~/recordings/2017_11_16/001/

Don't see any particular error messages in the terminal. It launches the gray window with the instructions to drop the folder, but nothing further. 
Please advise what other debugging information I should provide. Thanks.

**Comment by cpicanco** [comment]
I can see that you mention Xubuntu. Some time ago, I tested pupil on Lubuntu (running from source) and experienced a lot of problems. I have tested pupil bundles in other debian based distros and also found some problems. So would recommend you a clean Ubuntu 16.04 LTS before going any further.

**Comment by cpicanco** [comment]
Please see: https://github.com/pupil-labs/pupil/issues/810

**Comment by brittAnderson** [comment]
Following advice above I installed ubuntu-desktop over xbuntu-desktop. Same error. I then reinstalled the pupil debs and now both the capture and player apps work. While this fixes the problem, it would be preferable to use a lighter distro. Is it possible to identify the missing components from xubuntu? But for now I will close this issue, and open a new one that can be tagged as a feature request to support other, lighter weight distros.

**Comment by cpicanco** [comment]
Yes, it is possible (for advanced users) to identify, but pupil devs will not be able to maintain such a diverse set of distros. May I ask if you would be happy with Arch Linux? @willpatera  have been testing pupil against Arch Linux. Is there anything lighter than Arch Linux?

**Comment by brittAnderson** [comment]
I guess I used the wrong term. It isn't the linux distro, but rather linux desktop that is the issue. Unity uses more resources than xfce. But I agree, at the distro level Arch is the one I would prefer to use.
