### ISSUE TITLE
A basic issue possibly

### ISSUE THREAD

**Issue by Gopher-nz** [pupil-labs/pupil#937]
In pupil_positions.csv I notice timestamp is recorded for the duration of the video. The problem is it does not correspond to the time the recording took place.

If I understand it correctly the timestamp is a unix timestamp and I have to account for time difference on the day of the recording (and also that daylight saving time had started).

But the pupil_positions.csv recorded timestamps starting at 09:18am and yet other devices started at 08:24am. I don't believe I have the recording mixed up with any others, so am I misunderstanding the timestamp data or is this a case of the Pupil Eyetracker not being synchronised to my computer when it was connected?

**Comment by Gopher-nz** [comment]
Interestingly the folder time/date corresponds with the end time of my other device recordings - it just appears as though the timestamp does not comply.

**Comment by Gopher-nz** [comment]
It appears to be recording 45 minutes out ...

**Comment by papr** [comment]
We are not using the system time. Instead we use the monotonic clock provided by the libuvc library. This is to avoid time perturbation during recordings. Use Pupil Remote or Pupil Time Sync if you need the change the epoch of the recording timestamps.
