### ISSUE TITLE
v0.4 offline marker detector show metrics shows nothing

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#94]
The mode Show Metrics shows nothing with a surface defined.

**Comment by mkassner** [comment]
Hi,

did you click on recalculate first?

**Comment by mkassner** [comment]
please reopen if this issue remains.

**Comment by cpicanco** [comment]
Yes, I did click on recalculate first. Will try with the most recent commit.

**Comment by willpatera** [comment]
I confirm that this is now fixed.

**Comment by cpicanco** [comment]
@willpatera, the show metrics also dependends of x_scale y_scale variables?

**Comment by willpatera** [comment]
@cpicanco -- Surface metrics do not depend on the `X size` and `Y size` variables (note name changed for these variables). 

See the below screenshots from the demo dataset. The tablet front surface has the greatest number of gaze points on the surface, and is red. Check out the surface_gaze_distribution.csv file or see the table on -- http://pupil-labs.com/blog/2014/07/0392-player-release.html -- for some quick numbers. 

![screen shot 2015-03-07 at 15 40 37](https://cloud.githubusercontent.com/assets/1407224/6540743/ed26e174-c4e0-11e4-9c6d-68941fd30f09.png)
![screen shot 2015-03-07 at 15 40 31](https://cloud.githubusercontent.com/assets/1407224/6540745/ed28d97a-c4e0-11e4-83c0-bffccddba021.png)
![screen shot 2015-03-07 at 15 40 15](https://cloud.githubusercontent.com/assets/1407224/6540744/ed2871d8-c4e0-11e4-8742-1ede37f95bcb.png)
