### ISSUE TITLE
Strange gray world image flickering

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#942]
Please, see attached image:
![screenshot from 2017-11-17 18-19-33](https://user-images.githubusercontent.com/6511849/32969535-44a3236c-cbc4-11e7-9674-c9e9504008d7.png)

**Comment by cpicanco** [comment]
I can record normally, so not a blocking issue.

**Comment by papr** [comment]
Do I understand it correctly that this is only a display issue and that the gray part is not visible in the recorded video?

**Comment by cpicanco** [comment]
Yes, it is a display issue.

**Comment by papr** [comment]
Are you using custom hardware in this example? It looks like the received jpegs are only decoded partially. Does it work fine with older versions of Capture?

**Comment by cpicanco** [comment]
I have noticed that increasing a post processing option (sharpness)
increases the chances of those gray images. I am using a Logitech C610 and
no, previous versions of Capture did not have such problems.

**Comment by cpicanco** [comment]
Will close this one. Reopen at will.
