### ISSUE TITLE
Pupil Player Crash v1.1.2 Offline Pupil Detector

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#947]
By clicking 'Redetect' after the eye cams finished detection the following issue showed up:

![pupil_player_crash_1 1 2-dll](https://user-images.githubusercontent.com/10213803/33013222-900f86ee-cde3-11e7-869d-2b5cd46f12bf.png)

**Comment by papr** [comment]
@fneitzel is this still an issue?

**Comment by papr** [comment]
Closing since it seems to be stale.
