### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#95]
What can I do about it??

```bash
Traceback (most recent call last):
  File "/home/rafael/cpicanco/pupil/pupil_src/capture/main.py", line 89, in <module>
    version = pupil_version()
  File "/home/rafael/cpicanco/pupil/pupil_src/shared_modules/git_version.py", line 70, in pupil_version
    raise ValueError('Version Error')
ValueError: Version Error
```

**Comment by cpicanco** [comment]
I mean, I am running from source and I do not want to mess with anything. Commenting the version lines in main.py could generate problems?

**Comment by mkassner** [comment]
Its another bug. I ll fix it tomorrow. Thanks for spotting it.
M

**Comment by cpicanco** [comment]
Hope this help,

```bash
Traceback (most recent call last):
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 473, in <module>
    main()
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 196, in main
    patch_meta_info(rec_dir)
  File "/home/rafael/cpicanco/pupil/pupil_src/player/player_methods.py", line 164, in patch_meta_info
    new_info += e[0]+'\t'+e[1]+'\n'
IndexError: list index out of range
```

In player print e[0] returns:
> [Decode error - output not utf-8]

**Comment by cpicanco** [comment]
humm... decode error is an IDE issue.

**Comment by mkassner** [comment]
Hi,

are you running from a git repository? This error indicated that no git version information was found.

**Comment by cpicanco** [comment]
I am running it from a cloned git repository:
> cd cpicanco
> git clone https://github.com/pupil-labs/pupil.git

as you can see in the used path '/home/rafael/cpicanco/pupil/pupil_src/player/'

**Comment by cpicanco** [comment]
I have commented the version lines in capture/main.py and the recording gives the above mentioned player error. Other recordings are running ok.

**Comment by cpicanco** [comment]
Where is the version location inside the git folder?
![2015-03-06-160439_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6531809/ce8d6d1c-c41a-11e4-84b5-1033244dbf3a.png)

**Comment by cpicanco** [comment]
Well, building from inside sublime text does not raise this error. The version error is raised only when calling from inside the terminal:

> python /home/rafael/cpicanco/pupil/pupil_src/capture/main.py

**Comment by cpicanco** [comment]
There is a right way to call it from the terminal :)

> cd /home/rafael/cpicanco/pupil/pupil_src/capture/
> python main.py

**Comment by cpicanco** [comment]
Seems like it is not a real issue...

**Comment by cpicanco** [comment]
@mkassner @willpatera , what you say?

**Comment by cpicanco** [comment]
I really don't think that this exception deserves more than this:

https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/git_version.py#L81
```python
def get_tag_commit():
    """
    returns string: 'tag'-'commits since tag'-'7 digit commit id'
    """
    try:
        p = Popen(['git', 'describe'],
                  stdout=PIPE, stderr=PIPE)
        p.stderr.close()
        line = p.stdout.readlines()[0]
        return line.strip()

    except IndexError:
        print "Are you running from inside a git repository folder?"
    except:
        print "Unexpected error:", sys.exc_info()[0]
        raise
``` 

I will leave this `raise` as a suggestion for other try-except cases....... better than returning `none` for debugging.

**Comment by mkassner** [comment]
I made the script work even when calling pupil from outside the repo: de2748e170c69cb493f0e3b69d434be38f43af7c

**Comment by MichaelBarz** [comment]
Does not work for windows:

p = Popen(['git', 'describe'],
                  stdout=PIPE, stderr=PIPE,cwd=os.path.dirname(os.path.abspath(__file__)))

**Comment by MichaelBarz** [comment]
Works, when adding git to PATH ;)
I further simplified the function...
