### ISSUE TITLE
world-camera Unknown Device

### ISSUE THREAD

**Issue by BCIstorm** [pupil-labs/pupil#951]
Hello, I'm new to Pupil-Labs and just trying to get the eye-tracker running.
So, I download the Windows version 1.1.2 to run on a 64-bit Windows 7 SP1 with Intel core i5 3.3GHz and 8Gb RAM.

As I connect the USB to the PC it automatically detects and install "Pupil Cam 1 ID0" and "Pupil Cam 1 ID1", but then there's a problem with an "Unknown Device" (I guess this might be the world camera).
Running from the directory "pupil_capture_windows_x64_v1.1.2" I execute "pupil_capture.exe".
I can see both both eye cameras but no world camera.

Any help, please?

Here are the messages I get on the cmd:
```
C:\ET\pupil_capture_windows_x64_v1.1.2>pupil_capture.exe
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS ver
sion.
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
Running  PupilDrvInst.exe --vid 1443 --pid 37425
OPT: VID number 1443
OPT: PID number 37425
Running  PupilDrvInst.exe --vid 1443 --pid 37426
OPT: VID number 1443
OPT: PID number 37426
Running  PupilDrvInst.exe --vid 1133 --pid 2115
OPT: VID number 1133
OPT: PID number 2115
Running  PupilDrvInst.exe --vid 6127 --pid 18447
OPT: VID number 6127
OPT: PID number 18447
world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in gh
ost mode. No images will be supplied.
world - [WARNING] camera_models: Loading dummy calibration
world - [ERROR] pupil_remote: Could not bind to Socket: tcp://*:50020. Reason: A
ddress in use
world - [WARNING] launchables.world: Process started.
eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense back
end
eye0 - [INFO] launchables.eye: Session setting are from a different version of t
his app. I will not use those.
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
Running  PupilDrvInst.exe --vid 1443 --pid 37425
OPT: VID number 1443
OPT: PID number 37425
Running  PupilDrvInst.exe --vid 1443 --pid 37426
OPT: VID number 1443
OPT: PID number 37426
Running  PupilDrvInst.exe --vid 1133 --pid 2115
OPT: VID number 1133
OPT: PID number 2115
Running  PupilDrvInst.exe --vid 6127 --pid 18447
OPT: VID number 6127
OPT: PID number 18447
eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID0
 at resolution (640, 480)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 579 / 800.
!!!!Packets per transfer = 32 frameInterval = 111111
eye0 - [INFO] launchables.eye: Process shutting down.
```

**Comment by papr** [comment]
We do not officially support Windows 7. Please upgrade to Windows 10 to use the Pupil applications. You could try to follow the [driver install instructions](https://docs.pupil-labs.com/#windows-driver-setup) but we cannot give any guarantee that they work on Windows 7.

**Comment by papr** [comment]
@BCIstorm In case that you use the RealSense 3D camera as world camera: Currently, running from bundle does not support the RealSense camera. We are releasing a bundle that supports it soon.

**Comment by BCIstorm** [comment]
Thank you @papr , but still not working.
I've spent a whole day backing up and upgrading the system to windows 10 Pro. Disk formatted and fresh windows installation. Followed the "driver install instructions" and "Troubleshooting" but not working.

In Device Manager, under "libusbK Usb Devices" there are "Pupil Cam1 ID0" and "Pupil Cam1 ID1".
Under "Universal Serial Bus controllers" there's an "Unknown USB Device (Device Descriptor Request Failed)" that I guess is the camera world.

Please help. 

Here's what I get in the command prompt when executing the "pupil_capture.exe":
```
C:\ET\pupil_capture_windows_x64_v1.1.2>pupil_capture.exe
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
Running  PupilDrvInst.exe --vid 1443 --pid 37425
OPT: VID number 1443
OPT: PID number 37425
Running  PupilDrvInst.exe --vid 1443 --pid 37426
OPT: VID number 1443
OPT: PID number 37426
Running  PupilDrvInst.exe --vid 1133 --pid 2115
OPT: VID number 1133
OPT: PID number 2115
Running  PupilDrvInst.exe --vid 6127 --pid 18447
OPT: VID number 6127
OPT: PID number 18447
world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
world - [WARNING] camera_models: Loading dummy calibration
world - [WARNING] launchables.world: Process started.
```

**Comment by BCIstorm** [comment]
I also tried installing the drivers with "Disable Driver Signature Enforcement" and got the same problem.
Running Windows 10 Pro, Version 1709, OS Build 16299.64 on a PC with Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz 3.30GHz processor, 8GB of RAM and Nvidia GeForce GTX 750Ti.

**Comment by BCIstorm** [comment]
@papr and @willpatera , this issue is not closed. Any help? Sorry, I really need this to work a.s.a.p.  for my investigation.

**Comment by mkassner** [comment]
@BCIstorm please contact us via email info[at]pupil-labs[dot]com so we can get this sorted!

**Comment by BCIstorm** [comment]
Thank you @mkassner . Just sent an email.

**Comment by BCIstorm** [comment]
@mkassner have you seen the email?
