### ISSUE TITLE
pupil capture 1-1.2, white world image and grey eye images.

### ISSUE THREAD

**Issue by callummole** [pupil-labs/pupil#954]
Hi,

I recently accepted some small linux software updates, but now pupil capture is not providing a good image for the world or the eyes. 

The output continues to throw errors which look like this:

eyetrike@eyetrike-ThinkPad-E570:~$ pupil_capture
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.1.7
world - [INFO] launchables.world: System Info: User: eyetrike, Platform: Linux, Machine: eyetrike-ThinkPad-E570, Release: 4.13.0-17-generic, Version: #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017
world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
world - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution (1280, 720)
world - [INFO] camera_models: Loading pre-recorded calibration
world - [WARNING] launchables.world: Process started.
Estimated / selected altsetting bandwith : 904 / 1600. 
!!!!Packets per transfer = 32 frameInterval = 327868
world - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
world - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID2.
world - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution (1280, 720)
world - [INFO] camera_models: Loading pre-recorded calibration
Estimated / selected altsetting bandwith : 904 / 1600. 
!!!!Packets per transfer = 32 frameInterval = 327868
eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID0 at resolution (640, 480)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID1 at resolution (640, 480)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 205 / 256. 
!!!!Packets per transfer = 32 frameInterval = 331125
eye1 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 579 / 800. 
!!!!Packets per transfer = 32 frameInterval = 111111
eye0 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye0 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID0.
eye1 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID0 at resolution (640, 480)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye1 - [INFO] video_capture.uvc_backend: Found device. Pupil Cam1 ID1.
Estimated / selected altsetting bandwith : 205 / 256. 
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID1 at resolution (640, 480)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
!!!!Packets per transfer = 32 frameInterval = 331125
Estimated / selected altsetting bandwith : 579 / 800. 
!!!!Packets per transfer = 32 frameInterval = 111111

All the best,

Callum

**Comment by pointcontrols** [comment]
@callummole Can you please elaborate what updates did you perform?

**Comment by callummole** [comment]
I accepted some recommended software updates. After some digging I think they were these:

Start-Date: 2017-11-21  15:59:44
Commandline: aptdaemon role='role-commit-packages' sender=':1.150'
Install: gir1.2-gmenu-3.0:amd64 (3.13.3-6ubuntu5, automatic), linux-image-extra-4.13.0-17-generic:amd64 (4.13.0-17.20, automatic), linux-headers-4.13.0-17-generic:amd64 (4.13.0-17.20, automatic), linux-headers-4.13.0-17:amd64 (4.13.0-17.20, automatic), linux-image-4.13.0-17-generic:amd64 (4.13.0-17.20, automatic)
Upgrade: linux-headers-generic:amd64 (4.13.0.16.17, 4.13.0.17.18), linux-image-generic:amd64 (4.13.0.16.17, 4.13.0.17.18), ubuntu-desktop:amd64 (1.404, 1.404.1), linux-generic:amd64 (4.13.0.16.17, 4.13.0.17.18)

I'm pretty certain that the pupil capture was working before these updates, but not after.

I did, however, take some general upgrades earlier on in the day. I think pupil capture was working fine after these, although I didn't take specific notes. Pasted below in case:

Start-Date: 2017-11-21  14:06:43
Commandline: apt-get upgrade
Requested-By: eyetrike (1000)
Upgrade: libcups2:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), gir1.2-gtk-3.0:amd64 (
3.22.24-0ubuntu1, 3.22.25-0ubuntu0.1), gir1.2-mutter-1:amd64 (3.26.1-2ubuntu2, 3
.26.2-0ubuntu0.1), linux-libc-dev:amd64 (4.13.0-16.19, 4.13.0-17.20), libapt-ins
t2.0:amd64 (1.5, 1.5.1), sane-utils:amd64 (1.0.27-1~experimental2ubuntu1, 1.0.27
-1~experimental2ubuntu2.1), libwbclient0:amd64 (2:4.6.7+dfsg-1ubuntu3, 2:4.6.7+d
fsg-1ubuntu3.1), libgtk-3-common:amd64 (3.22.24-0ubuntu1, 3.22.25-0ubuntu0.1), a
pt:amd64 (1.5, 1.5.1), libgtk-3-0:amd64 (3.22.24-0ubuntu1, 3.22.25-0ubuntu0.1), 
xul-ext-ubufox:amd64 (3.4-0ubuntu0.17.04.1, 3.4-0ubuntu1.17.10.1), language-sele
ctor-common:amd64 (0.180, 0.180.1), libmutter-1-0:amd64 (3.26.1-2ubuntu2, 3.26.2
-0ubuntu0.1), ubuntu-standard:amd64 (1.404, 1.404.1), gir1.2-accountsservice-1.0
:amd64 (0.6.42-0ubuntu3, 0.6.42-0ubuntu3.1), cups-server-common:amd64 (2.2.4-7ub
untu2, 2.2.4-7ubuntu3), cups-common:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), liba
pt-pkg5.0:amd64 (1.5, 1.5.1), mutter-common:amd64 (3.26.1-2ubuntu2, 3.26.2-0ubun
tu0.1), samba-libs:amd64 (2:4.6.7+dfsg-1ubuntu3, 2:4.6.7+dfsg-1ubuntu3.1), ubuntu-minimal:amd64 (1.404, 1.404.1), apport:amd64 (2.20.7-0ubuntu3.1, 2.20.7-0ubuntu3.5), libsane1:amd64 (1.0.27-1~experimental2ubuntu1, 1.0.27-1~experimental2ubuntu2.1), libgtk-3-bin:amd64 (3.22.24-0ubuntu1, 3.22.25-0ubuntu0.1), cups-ppdc:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), libcupsmime1:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), python3-apport:amd64 (2.20.7-0ubuntu3.1, 2.20.7-0ubuntu3.5), firefox-locale-en:amd64 (56.0+build6-0ubuntu1, 57.0+build4-0ubuntu0.17.10.5), libgail-3-0:amd64 (3.22.24-0ubuntu1, 3.22.25-0ubuntu0.1), libwebkit2gtk-4.0-37:amd64 (2.18.0-2, 2.18.3-0ubuntu0.17.10.1), apt-utils:amd64 (1.5, 1.5.1), libsmbclient:amd64 (2:4.6.7+dfsg-1ubuntu3, 2:4.6.7+dfsg-1ubuntu3.1), apport-gtk:amd64 (2.20.7-0ubuntu3.1, 2.20.7-0ubuntu3.5), libsane-common:amd64 (1.0.27-1~experimental2ubuntu1, 1.0.27-1~experimental2ubuntu2.1), libcupsppdc1:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), gir1.2-webkit2-4.0:amd64 (2.18.0-2, 2.18.3-0ubuntu0.17.10.1), firefox:amd64 (56.0+build6-0ubuntu1, 57.0+build4-0ubuntu0.17.10.5), cups-bsd:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), gtk-update-icon-cache:amd64 (3.22.24-0ubuntu1, 3.22.25-0ubuntu0.1), cups-core-drivers:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), cups-daemon:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), accountsservice:amd64 (0.6.42-0ubuntu3, 0.6.42-0ubuntu3.1), language-selector-gnome:amd64 (0.180, 0.180.1), libcupsimage2:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), cups:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), libcupscgi1:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), cups-client:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), libjavascriptcoregtk-4.0-18:amd64 (2.18.0-2, 2.18.3-0ubuntu0.17.10.1), cups-ipp-utils:amd64 (2.2.4-7ubuntu2, 2.2.4-7ubuntu3), python3-problem-report:amd64 (2.20.7-0ubuntu3.1, 2.20.7-0ubuntu3.5), libaccountsservice0:amd64 (0.6.42-0ubuntu3, 0.6.42-0ubuntu3.1), gir1.2-javascriptcoregtk-4.0:amd64 (2.18.0-2, 2.18.3-0ubuntu0.17.10.1), mutter:amd64 (3.26.1-2ubuntu2, 3.26.2-0ubuntu0.1)
End-Date: 2017-11-21  14:07:21

**Comment by mkassner** [comment]
@pointcontrols  has identified the issue and made a fix. We will make new bundles this weekend.

**Comment by cpicanco** [comment]
Maybe related to #942 ?

**Comment by mkassner** [comment]
@cpicanco  this is not related. Your issue is because you are using different hardware. I recommend playing with the bandwidth factor in the uvc_backend.py file.

**Comment by callummole** [comment]
Great. Looking forward to trying out the new bundles.

**Comment by callummole** [comment]
@mkassner just wondering if the bundles have been updated?
