### ISSUE TITLE
Hidden Left buttons

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#956]
I think left buttons are not responsive to low resolutions. My screen is 1024x768 and I need to reduce the window size of World and Eye so that both fit inside the screen.

![screenshot from 2017-11-24 11-00-37](https://user-images.githubusercontent.com/6511849/33213597-f71dace6-d106-11e7-8b5a-81e877f58f67.png)

**Comment by cpicanco** [comment]
Please, don't mind about the extended desktop.

**Comment by mkassner** [comment]
@cpicanco  are you saying that the icons on the left are to big for you screen layout?

**Comment by papr** [comment]
@cpicanco Did you try to reduce the UI scaling in the general settings?

**Comment by cpicanco** [comment]
Please look at the top left of the screen and you will notice an icon that is hiding. So I think that there is too much space in between. I am guessing you can try for your self. Just reduce the size os the window, you should replicate the issue.

**Comment by papr** [comment]
Ah, now I know what you mean. It is weird though since the thumb bar menu should behave differently (and also does for me): Thumbs overlap each other when I decrease the window size. I wonder why this does not happen for you.
 
![screenshot](https://user-images.githubusercontent.com/168390/33263349-d0f5c430-d369-11e7-8d53-74f7f13f31f7.png)

**Comment by cpicanco** [comment]
I am running the bundle, I wasn't expecting any difference. Maybe a custom plugin is breaking your code?

**Comment by papr** [comment]
To be clear: My screenshot shows expected bahvior. The thumbs are inserted into a `pyglui.ui.Stretching_Menu`. It scales with window size and places the elements such that they have the same distance to each other but still fit into the menu.

I get the same behavior aas on my screenshot when running from bundle.

**Comment by cpicanco** [comment]
Hi, I deleted the `user_settings_world` file and now it is scaling correctly (as far as I known). It is magic.

**Comment by cpicanco** [comment]
![screenshot from 2017-11-27 14-07-05](https://user-images.githubusercontent.com/6511849/33279227-9e947a78-d37c-11e7-96ff-f95de162fd10.png)
