### ISSUE TITLE
Do not autoshow Vector Gaze Mapper after calibration

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#957]
I would like to suggest to not auto-show the Vector Gaze Mapper after calibration. I need to inspect the capture screen during recordings **without clicking** in anything because I have other apps running at the same time that should not loose focus.

**Comment by papr** [comment]
Mmh, this is kind of difficult to change. Gaze mappers are plugins and all plugins have their menu opened after loading. You can either change that behavior by
1. Changing the default behavior for all plugins by commenting out https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/plugin.py#L258 
2. By subclassing the specific gaze mapper plugin and changing the `add_menu` behavior for the subclass.

These are not changes that we will deploy on master. You will have to make these changes locally.

**Comment by cpicanco** [comment]
@papr , the Vector Gaze Mapper is already loaded by default as far as I known. After a successfully calibration, this already loaded plugin is auto-shown. Please reconsider. Of course, changing that does not requires changing anything in the base plugin.

**Comment by papr** [comment]
No, the dummy mapper is loaded by default. If there was a previous calibration the according mapper is loaded.
