### ISSUE TITLE
Anchor Eye Model Option

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#958]
Hi, sometimes, due to bad pupil detection, good eye models are lost even with sensitivity at 0.9900. In some cases, you have just enough information to conclude that nothing has changed that justify model compensations. Example of those bad model compensations are very tiny eye models and very big ones. I would like to ask if it makes any sense to have a toggle button to anchor the current eye model. No matter what, the model will not change or compensate for anything.

**Comment by mkassner** [comment]
@cpicanco  this is a good idea. We are reworking the entire 3d model approach right now. Once we release please give it a good test and let us know what should be improved! For the current implementation, I dont think it makes sense to add new features, since we will replace it anyways soon.
