### ISSUE TITLE
Windows automatic driver installation does not work

### ISSUE THREAD

**Issue by DouglasMackay** [pupil-labs/pupil#962]
Steps to reproduce, follow steps 1 - 5 from the [troubleshooting instructions](https://docs.pupil-labs.com/master/#troubleshooting), restart Capture, connect headset, `PupilDrvInst.exe` runs, but cameras are not recognized and show up as unknown.

System information:
![image](https://user-images.githubusercontent.com/18257891/33325002-6519da4c-d451-11e7-9aac-a882b0416d29.png)

**Comment by papr** [comment]
Workaround: Install drivers manually.

**Comment by willpatera** [comment]
@pointcontrols please take a look at driver installation also for `e200` cameras.

**Comment by papr** [comment]
Pupil Capture needs to be started with administrator rights to successfully install the drivers
