### ISSUE TITLE
Calibration and intrinsics estimation gui conflicting

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#967]
![screenshot from 2017-12-04 10-30-42](https://user-images.githubusercontent.com/6511849/33555270-7e7d86be-d8de-11e7-8e6f-83b9af0b0b08.png)

**Comment by cpicanco** [comment]
When you press C, both are being started.

**Comment by mkassner** [comment]
Yes. I saw that too. We need to remove the C for camera intrinsics and use a different UI element for that.
