### ISSUE TITLE
Pupil Capture recoding do not work with Pupil Mobile source

### ISSUE THREAD

**Issue by AtsushiSuzuki** [pupil-labs/pupil#976]
Hi.

I am trying to capture Pupil World Camera (high speed) video via Pupil Mobile
but I cannot record video with Pupil Capture.

## Steps to reproduce
1. Set up Pupil Mobile with Pupil World Camera
2. Start Pupil Capture on PC/Mac, select backend as "Pupil Mobile"
3. Start recoding by pressing "R" screen button

## case 1:
If Pupil Capture's recorder option "Compression" is set to "bigger file, less CPU",
video is wrote to "world.mp4" but the video seems to be broken.

[capture.zip](https://github.com/pupil-labs/pupil/files/1537935/capture.zip)

VLC cannot play the video file (shows blank screen), or transcoding with ffmpeg gives error message.

[ffmpeg.log](https://github.com/pupil-labs/pupil/files/1537929/ffmpeg.log)

## case 2:
If Pupil Capture's recorder option "Compression" is set to "smaller file, more CPU",
after pressing "R", Pupil Capture freezes and outputs error message.

```
eye0 - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
eye0 - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [640, 480]
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] launchables.eye: Process started.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables\world.py", line 437, in world
  File "shared_modules\recorder.py", line 307, in recent_events
  File "shared_modules\av_writer.py", line 144, in write_video_frame
  File "ndsi\frame.pyx", line 205, in ndsi.frame.JPEGFrame.yuv422.__get__
TypeError: 'float' object cannot be interpreted as an integer
```

[pupil_capture.log](https://github.com/pupil-labs/pupil/files/1537932/pupil_capture.log)

## Environment
- Camera: Pupil World Camera (high speed)
- Android: Galaxy Note 8, Android 7.1.1
- Pupil Mobile: 0.17.1
- PC: Windows 10 or OS X High Sierra
- Pupil Capture: 1.1.2

**Comment by papr** [comment]
This issue looks like it is related/duplicates #910

**Comment by AtsushiSuzuki** [comment]
I think case 1 seems to be same as #910.
About case 2, it looks similar to #617. (this is about ndsi but #617 is about uvc)

**Comment by papr** [comment]
@AtsushiSuzuki You are right about case 2. See this fix: https://github.com/pupil-labs/pyndsi/pull/31

**Comment by AtsushiSuzuki** [comment]
Thank you so much.

**Comment by papr** [comment]
I found the reason for issue 1 as well and added a fix to the existing PR.

**Comment by AtsushiSuzuki** [comment]
Thank you!
I look forward to the release.
