### ISSUE TITLE
Audio playback in Pupil Player

### ISSUE THREAD

**Issue by erdincisbilir** [pupil-labs/pupil#978]
Hi all,
Is there a way to playback recorded audio simultaneously with the world video within the Pupil Player? 
I can export and then audio file is merged with the video file but what I really want is to be able to playback audio synchronously with the video in Pupil Player without having to export first.

Thanks a lot! 

OS version: macOS Sierra10.12.5

**Comment by papr** [comment]
Hey @erdincisbilir 
Currently, this is not implemented.

**Comment by papr** [comment]
Implemented in #1111
