### ISSUE TITLE
Audio recording is not working in Ubuntu

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#979]
Hi, for some reason audio is recorded using Audacity software, but is not recorded using Pupil Capture. @papr said that ALSA should be installed. Well, I think it is. I am reporting this just for your information, I don't really need this for my stuff. So, for me is not a blocking bug.

**Comment by papr** [comment]
Do you get no audio file at all, an empty audio file or an audio file containing garbage data? I guess there are no error messages?

You can try to add this line either to the audio capture plugin or to a small custom python file in the plugins folder to get more av related log messages: `av.logging.set_level(av.logging.DEBUG)`

**Comment by cpicanco** [comment]
No audio file at all and no error messages.

**Comment by cpicanco** [comment]
Ok. It is really ALSA related:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "shared_modules/audio_capture.py", line 154, in capture_thread
  File "av/container/core.pyx", line 288, in av.container.core.open (src/av/container/core.c:4987)
  File "av/container/core.pyx", line 250, in av.container.core.Container.__cinit__ (src/av/container/core.c:4323)
  File "av/format.pyx", line 49, in av.format.ContainerFormat.__cinit__ (src/av/format.c:1512)
ValueError: no container format 'alsa'

```

**Comment by phauly** [comment]
I have the same problem

**Comment by mkassner** [comment]
I can recreate this on ubuntu. We need to investigate.

**Comment by papr** [comment]
@mkassner @phauly @cpicanco Did you run `sudo apt-get install libasound-dev`? This is a recommendation from the [`portaudio` install page](http://portaudio.com/docs/v19-doxydocs/compile_linux.html)

**Comment by mkassner** [comment]
@papr  does audio work on your machine?

**Comment by xszym** [comment]
I had similar issue. If your script works from bash, but does not from python code this is what you should uninstall av and then install it without binary:
`pip3 uninstall av`
`pip3 install av --no-binary av`
