### ISSUE TITLE
v0.4.2 - Ubuntu 3.13.0.46-77 - Priviliges freezing Pupil Capture

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#98]
If the path to recordings is not existing, then the path is set back to defaults.

Could you please adapt that behaviour for paths where the user hasn't the necessary rights to access/write/read them. Currently Pupil Capture freezes, when entering '/boot/' as unpriviliged user.

**Comment by mkassner** [comment]
I added the test. Will be in the next release!
