### ISSUE TITLE
How to translate or map Pupil player timestamps to realtime 

### ISSUE THREAD

**Issue by jooni41** [pupil-labs/pupil#982]
I want to map or translate pupil player timestamps to real time for synchronisation purposes. what would be the most appropriate way

**Comment by cpicanco** [comment]
I am afraid it is not possible, unless you have annotated the (real) start time of your target Pupil recording. If you have the start time, then you can convert any pupil player timestamps to real time in two steps. First convert pupil timestamps from Epoch start to zero start (by subtracting all timestamps from the first one). Then add your annotated real time to all timestamps. Hope this helps.
