### ISSUE TITLE
Multiple Pupil Player Icons and zombie processes

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#985]
When opening a file with drag and drop you will get multiple pupil player icons. I think it is a minor bug. In the image below I have just one Pupil Player instance opened.
![screenshot from 2017-12-14 10-09-48](https://user-images.githubusercontent.com/6511849/33993968-821ccbbe-e0b7-11e7-805f-cd94576ac20e.png)

I think it is related to zombie processes:
![screenshot from 2017-12-14 10-15-06](https://user-images.githubusercontent.com/6511849/33994090-f289f9f8-e0b7-11e7-8d66-e9c9e0eba9a6.png)

I could not see any impact on memory. But it may exist.

**Comment by mkassner** [comment]
I cant reproduce this. Please reopen if required
