### ISSUE TITLE
How to extract pupil_data from pupil_remote

### ISSUE THREAD

**Issue by kt10aan** [pupil-labs/pupil#987]
Hi,

if this is not appropriate for the issues section, please close it and I will move it to Discord. :)

So, we have the Vive tracker, and we are running the pupil service. We want to have a small script, like the one in https://docs.pupil-labs.com/master/#pupil-service that gives us access to streaming (raw) data of the pupil's position etc.. I.e., we do not want to access them after the capture using the pupil_data file, but rather to have access to them, as they come, in real-time

I hope I was not very vague! Any help will be greatly appreciated.

**Comment by papr** [comment]
Hi @kt10aan 
Please have a look at our example script: https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/filter_messages.py

**Comment by varunjammula** [comment]
The link above is not working. Is there a new link? Thanks!

**Comment by papr** [comment]
@varunjammula https://github.com/pupil-labs/pupil-helpers/blob/master/python/filter_messages.py
