### ISSUE TITLE
Request - Save "Start Time" in "Info.csv" with floating point accuracy

### ISSUE THREAD

**Issue by jonmatthis** [pupil-labs/pupil#989]
At the moment the "Start Time" value saved in the "info.csv file is accurate down to seconds (e.g, Start Time, 11:12:55). 

It would be very helpful if the accuracy of this value was increased, so that start time is labeled with fractions of seconds (e.g, Start Time, 11:12:55.12345). This would help synchronize data recorded from pupil with data recorded from other programs on the same computer.

**Comment by jonmatthis** [comment]
Alternatively, you could alter the "Info.csv" code to record the System boot time value. At the moment, it is not possible to translate the World and Eye timestamps to real-world times, as they are zero-indexed against the last system reboot, which is not recorded anywhere.

**Comment by mkassner** [comment]
What about a button that set the pupil time to system time (the time reported by python time.time)?

**Comment by jonmatthis** [comment]
I would definitely love an option to output timestamps in UNIX Epoch time format (that is, outputting the number of seconds since Jan 1 1970). 

That would solve my particular problem here, but feel I should reiterate that I think you should consider putting *something* in the default data output that would give the ability to precisely convert the recorded time stamps into some kind of  real-world time frame. You could do this by specifying "Start time" with floating point precision, or outputting the system boot time value to the Info.csv file, or (my personal preference) change your default timestamp format to Unix epoch time. 

Considering how great of a job you guys do at recording accurate time stamps, it seems like an oversight not to have *some* way to convert the systemboot-relative timestamps to real-world timestamps using the default data output.

**Comment by mkassner** [comment]
you are right. This is easy to do and useful. We will add the start time or recording as reported by time.time()
