### ISSUE TITLE
Natural feature edit mode - mouse clicks appear in wrong position on screen

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#994]
Version 1.1-2 does not properly account for resolution of retina display.  In the attached screenshot, I have just clicked on the center of the X drawn on the white sheet.  The natural feature (the blue circle) appears at approximately pix/2 and pix/2 of it's true location (see it there near the top left eye image overlay?) 

<img width="1571" alt="screenshot 2018-01-03 15 15 36" src="https://user-images.githubusercontent.com/8962011/34538096-f8de2cb6-f098-11e7-8f9b-1f0d86d33e8a.png">

**Comment by performlabrit** [comment]
Sorry, was running the previous version.  This has already been addressed.

**Comment by LHicken** [comment]
I am also still having this problem, but I have updated to version 1.1-2. My marker is appearing the same distance away as @performlabrit picture.

**Comment by performlabrit** [comment]
I spoke with @LHicken, who reports that it was a human mistake related to versions.  Indeed, this issue has been resolved in version 1.1-2.  Closing this issue again.
