### ISSUE TITLE
P.Player - Offline calibration - crashes if last section removed (v 1.1.2)

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#995]
On a macbook pro running version 1.1.2

**Comment by mkassner** [comment]
is this still an issue?

**Comment by performlabrit** [comment]
Sorry - had some version confusion yesterday, where I was accidentally
running a previous version.  This is no longer an issue as of 1.2.7

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu
