### ISSUE TITLE
Player - offline calibration - new sections should have a default calibration range that spans the full video.

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#996]

**Comment by mkassner** [comment]
We choose to do a smaller section to show the user that this is adjustable.

**Comment by performlabrit** [comment]
Isn't this made explicit by the "calibration range" field?

If you choose the default to a smaller section, then I suggest that you add
a button for "select entire range."

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
Isn't it the actual problem that setting the ranges (both calibration and mapping) is a pain in *** when using the test field?

I suggest we look for an intuitive way to change the ranges without adding further ui that is only useful for special cases anyway...

**Comment by cpicanco** [comment]
Writing numbers using the number pad is sort of tricky. There is sanitization, but instead of a simple warning when strange characters or formats are found, the field will be reseted. You need to care about brackets and commas. The enter key in the number pad does not work in text fields.  Right now it is a nighmare.

**Comment by cpicanco** [comment]
But removing them completely would be worse. So I think some redundancy would be nice.

**Comment by papr** [comment]
No, you are right. The text field needs to stay for precise input. But we need a method to change the ranges quickly without having to be precise.

**Comment by papr** [comment]
Will be fixed with #1057
