### ISSUE TITLE
Player (Mac - 1.2.7) - A click on video timeline is unresponsive.

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#997]
I cannot jump to a point in the video anymore.  Sad.

**Comment by mkassner** [comment]
@performlabrit  you mean you would like to click instead of drag? I think that could be usefull. @papr  what do you think?

**Comment by performlabrit** [comment]
No, I mean that the timeline is entirely unresponsive to any mouse
interactions at all.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
Please be aware that moving the time indicator is only possible in the lower part. I know that it is confusing that it extends upwards but is not draggable in that area.

**Comment by performlabrit** [comment]
Yeah, there is no region with which I can interact.

I wonder if this is related to the same issue that has
​previously ​
caused the pixel position of a new natural feature to be displaced from the
position under the mouse.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
Are you able to change the trim mark positions?

**Comment by performlabrit** [comment]
Yes, I am.  Also, a bit more playing shows that there is a very thin
horizontal region between the visual location of the timeline that does
react to mouse interaction.  It's fine, and takes a lot of clicking around
to find.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
You mentioned that you are using a Mac with Retina Display. Could you specify which Mac exactly?

**Comment by performlabrit** [comment]
​Macbook Pro with 15 inch retina display 2016
​

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
Ok, I will try to improve the ui handling starting next week.

**Comment by performlabrit** [comment]
Ok.  So, now I'm clicking around some more and finding that I *can*
interact.  I'm not sure what changed, though - the inability to interact
has been persistent across multiple sessions, so it's not a rare
irreproducible bug.  I'll try and track down the cause/remedy and will let
you know what I find.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
Currently, this should be the area where the indicator is draggable:
<img width="1184" alt="screenshot 2018-01-04 13 40 08" src="https://user-images.githubusercontent.com/168390/34564011-69904d06-f155-11e7-9d43-ed22f09d5499.png">

**Comment by cpicanco** [comment]
Sometimes the problem is that the app itself is unresponsive. The player (since the introduction of autoupdate everywhere through events) is hanging a lot.

**Comment by performlabrit** [comment]
Yes, I'm clear on that.  That draggable area is unresponsive.   Here is a
video demonstrating the issue.  Sadly, you can't tell when I'm clicking
from the video, but be assured that Im clicking like mad.

https://www.dropbox.com/s/twpv9k23f2qchbm/pupil_player_scrollBarBug.mov?dl=0

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by performlabrit** [comment]
Certain aspects of the app are responsive.  I can mess with trim regions
and region boundaries without noticeable delay.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by cpicanco** [comment]
@performlabrit , you to click on top of the left most line inside the dragable area.

**Comment by papr** [comment]
Try _dragging_ here:
<img width="351" alt="screenshot 2018-01-04 13 59 51" src="https://user-images.githubusercontent.com/168390/34564639-c8a5f546-f157-11e7-905d-7f3158b2ef1a.png">

Please be aware that clicking somewhere to jump there is currently not implemented!

**Comment by cpicanco** [comment]
Also, you can press space key to start-stop playing.

**Comment by performlabrit** [comment]
Yes, I can press the space key.  Pablo, I'll pay attention to your previous
suggestion and see if it's simply a matter of me expecting behavior that
isn't yet implemented.  If that's the case, then I suggest some sort of
visual aid (e.g. a circle in the clickable region that visually responds to
a click).

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu

**Comment by papr** [comment]
You are right, but I think it is better to implement the expected behavior than adding aids for the restricted behavior. :)

**Comment by performlabrit** [comment]
Agreed.  Thanks!

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu
