### ISSUE TITLE
Player - eye video overlay plugin - Request: retain pupil outline when paused/scrobbling 

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#999]
The red outline of the pupil is valuable as an indication of the quality of pupil detection, especially when deciding to add natural features during the calibration process.  This is usually done with a lot of scrobbling through the paused video.  Unfortunately, the red overlay is only visible when the video is being played.

**Comment by papr** [comment]
I agree that this should be the expected behavior and is probably a bug.

**Comment by cpicanco** [comment]
@mkassner has changed how the pupil is draw in master. Maybe it already fixed.

**Comment by papr** [comment]
I can confirm that 30781d9da1d1f1e14aadc7b6165bdb7142ad3de4 fixed this issue.
